hokusai/production.yml
Seeing that CPU use is not so evenly distributed between pods - some close to 1 while some at 0.2
To apply immediately w/out a deploy, pull these changes locally then run `hokusai production update`
=> scale out MP more aggressively

renovate.json
This removes @alloy from being an assignee in renovate and adds @mzikherman as a reviewer. 
@joeyAghion I'm not sure if it would be more appropriate to have someone else as the assignee. Open to suggestions.
=> Removes alloy as an assignee and adds matt as a reviewer

_schemaV2.graphql, src/lib/loaders/loaders_without_authentication/gravity.ts, src/schema/v2/fields/__tests__/money.test.ts, src/schema/v2/fields/money.ts
https://artsyproduct.atlassian.net/browse/GROW-1679
This gives `Money` fields the ability to do a query-time conversion to USD dollars:
The conversion is based on the exchange rate data held by Gravity, which is updated nightly and served from `/api/v1/exchange_rates`.
Because it is based on Gravity's exchange rate data, conversion rates may be up to a day old, which should be fine for our present purposes.
This is my and @jiahaodavid's first time mucking around with currency fields. We are open to suggestion about field naming, proper use of major/minor etc.
=> Add currency conversion to Money type

src/schema/v2/artist/highlights.ts
Can’t seem to find any more Blue Chip, Established, or Emerging badges under “Selected Career Achievements”.
Metaphysics was returning an empty array because not all options were being passed properly. Now an array of strings ("blue-chip", "emerging", etc) are being returned correctly.
__Before:__
__After:__
=> Blue Chip / Emerging / Established Badges no longer appearing under Career Achievements

package.json, src/index.ts, src/lib/rateLimiter.ts, yarn.lock
Today we saw very very slow memcache server responses, as there was some brief AWS infrastructure issues.
Simulating this locally by using http://slowwly.robertomurray.co.uk/ and setting slow response times, I saw that when removing rate limiting, locally things actually worked!
The step that accesses the cache during query resolution (at the data loader level), is [already wrapped](https://github.com/artsy/metaphysics/blob/64253ff75e9bc47515ddd813f259d10651eb884f/src/lib/cache.ts#L89) to add some custom behavior around the default memcache client. Specifically, early timeouts, datadog logging, etc. We've seen occasions of high memcache latency frequently enough to warrant this. Indeed, this step timed out locally and it fell back to the underlying API. That's a good thing for resilience! …
=> @izakp => [Rate Limiting] Wrap middleware to timeout when cache is slow

.prettierignore, _schemaV2.graphql, src/lib/loaders/__tests__/api.test.ts, src/lib/loaders/api/loader_without_authentication_factory.ts, src/lib/loaders/loaders_with_authentication/gravity.ts, src/lib/loaders/loaders_without_authentication/gravity.ts, src/schema/v2/__tests__/createAccountRequestMutation.test.ts, src/schema/v2/createAccountRequestMutation.ts, src/schema/v2/schema.ts
Uses https://github.com/artsy/gravity/pull/12707/files
Rather than stitch a new mutation in, this adds a bespoke one pointing to the V1 API endpoint, which is already in use by other clients.
Looks like:
```
gravity:development> AccountRequest.first
=> #<AccountRequest _id: 5dfd70d310f20c7e6501824f, created_at: 2019-12-21 01:09:39 UTC, updated_at: 2019-12-21 01:09:39 UTC, requester_id: nil, user_id: nil, action: "user_data", tracking_number: "257C7A31DEF6", notes: "dont sell", email: "percy@cat.com", name: "percy", stripe_customer_id: nil>
```
=> @joeyAghion => [Account Request] Add mutation to create account request

src/lib/loaders/api/loader_without_authentication_factory.ts
Noticed by default this option being unset will result in a GET, so those were being excluded too.
=> @mzikherman => [Cache] Proper check for POST/PUT/DELETE to skip cache

src/lib/rateLimiter.ts
When disabled with a value of 0, the cache access, incrementing, etc. is all invoked. It's only at the [very end](https://github.com/nfriedly/express-rate-limit/blob/757fb450241748ba970315c81df203a9bbd394ba/lib/express-rate-limit.js#L123-L127) where the actual request is simply not blocked.
=> @joeyAghion => [Rate Limiting] Skip middleware entirely when disabled

dangerfile.ts, src/lib/__tests__/date.test.ts
Problem
Before this change, `yarn lint` failed with the following error:
```sh
dl@phoenix:~/src/metaphysics (master)
$ yarn lint
yarn run v1.17.3
$ eslint . --ext ts
/Users/dl/src/metaphysics/dangerfile.ts
8:20  error  Unable to resolve path to module './build/src/schema/v1'  import/no-unresolved
✖ 1 problem (1 error, 0 warnings)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Solution:
Update file path reference to the v1 schema, leading to a clean `yarn
lint`.
=> Fix broken v1 schema reference in dangerfile.ts

README.md
Does adding a description after the fact fix the Peril build?
=> Remove alloy as a point-person of MP

src/schema/v1/__tests__/fair.test.js, src/schema/v2/__tests__/fair.test.js
* Removed unused attribute stubs
* Update assertion such that specs expect that year of exhibition period is
included.
* exhibition period uses `dateRange` under the hood, which has its own
thorough unit test suite, so I don't think there's any loss of
coverage from changing the "case" (from present year to past year) of
the exhibition period being asserted upon in the spec.
* Moreover, 2019 is always in the past, so test should be stable now.
=> Fix Fair exhibition period spec failures (v1 and v2 schemas)

src/lib/tracer.ts
Was thinking about doing `hokusai env unset ENABLE_QUERY_TRACING && hokusai refresh`, but looks like that would turn off _all_ the Datadog tracing here, whereas the others here (`express` and `http`) are still moderately useful.
=> @joeyAghion => [Tracing] Remove graphql resolver tracking

_schemaV2.graphql, src/schema/v2/__tests__/filterArtworksConnection.test.ts, src/schema/v2/filterArtworksConnection.ts
https://artsyproduct.atlassian.net/browse/FX-1706
When fetching artworks belonging to a collection, we usually also want to fetch a list of merchandisable artists that is extrapolated from that artwork result set.
Currently the list of merchandisable artists is unbounded. This PR adds the ability to cap that list at a provided `size`.
Digging into this I [realized](https://artsy.slack.com/archives/C1HH3KNJG/p1579281411000500) that this root `artworksConnection` field had its specs [disabled](https://github.com/artsy/metaphysics/pull/1920) back in the v2 migration. So I re-enable them here, and update a few things while I'm at it in 04362de
Following that, the real business of adding the `size` argument is in c98c46f
=> [FX-1706] Add ability to limit number of merchandisable artists in a collection

_schemaV2.graphql, src/schema/v2/sorts/artwork_sorts.ts
This looks like a breaking change, but `AVAILABILITY_DESC` must not be used by clients currently as it's not a valid sort value according to gravity, which only accepts [`availability`](https://github.com/artsy/gravity/blob/master/app/models/domain/artwork.rb#L153).
Indeed, passing `AVAILABILITY_DESC` returns an error:
This PR updates this sort to `AVAILABILITY_ASC`, which is a valid sort value.
=> Fix availability sort to use correct value sent to gravity

.circleci/config.yml, package.json, scripts/compare-reaction-schema.ts, yarn.lock
(when compared to currently deployed Reaction).
I _think_ this makes sense as a check? It's sort of the Force production schema check (does MP production have any breaking changes when compared to the one included in the to-be-released version), but inverted.
Does this MP PR have any breaking changes when compared to the currently deployed Force version? If so, that makes Force undeployable.
=> @zephraph => [Danger] Warn when MP PR introduces breaking changes to V2 schema

src/schema/v2/artwork/artworkContextGrids/ArtistArtworkGrid.ts, src/schema/v2/artwork/artworkContextGrids/__tests__/defaultContext.test.ts
Update sorting in the Other Works By section of the artist page to be based on desc merchandisability
[Jira Ticket](https://artsyproduct.atlassian.net/browse/PURCHASE-1602)
Paired with @sepans 🎉 
Testing
To test this change we ran metaphysics locally and saw the data sorting change
Before code change:
`artist/jr/artworks?exclude_ids%5B%5D=5b5ca00b5622c23c3700fa8b&page=1&size=8&sort=-published_at`
After code change:
`artist/jr/artworks?exclude_ids%5B%5D=5b5ca00b5622c23c3700fa8b&page=1&size=8&sort=-merchandisability`
=> [PUR-1602] Sort Other Works By section by merchandisability rating

_schema.graphql, _schemaV2.graphql, src/lib/stitching/__tests__/mergeSchemas.test.js, src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/schema.ts, src/lib/stitching/exchange/stitching.ts
We want to move newly added `commerceMyOrders` root field coming from Exchange to under `me` root field.
We need to update Reaction's newly my purchases query to use this field under `me`. If we managed to remove `commerceMyOrders` root field here it may break that page but since it's admin only it should be ok.
=> Moving commerceMyOrders under me root field

_schemaV2.graphql, src/integration/__tests__/integration.test.ts, src/schema/v2/artist/index.ts, src/schema/v2/auction_result.ts
Following https://github.com/artsy/diffusion/pull/182 we now add support for filtering by organization for `Artist.auctionResults`. 
- Also added `boughtIn` that is now exposed from diffusion
Note:  I didn't make this change in V1, assuming all clients of this change are/will be on V2.
=> PURCHASE-1745: add support for filter by organization

_schemaV2.graphql, src/schema/v2/schema.ts
This undeprecates `viewer`, which we're still using extensively across our frontend code and have found to still be valuable.
=> Undeprecate Viewer

src/lib/sponsoredContent/data.json
https://artsyproduct.atlassian.net/browse/FX-1791
=> Adds copy + press release url for Frieze LA 2020 fair

_schemaV2.graphql, src/schema/v2/artist/index.ts, src/schema/v2/artwork/artworkSizes.ts
Depends on https://github.com/artsy/diffusion/pull/188
Adds search by list of new `ArtworkSizes` enum when filtering auction results.
=> Add artworkSizes filter to auction results and remove unused arg

.env.example, .env.test
Found this while debugging some [pesky local development issues](https://artsy.slack.com/archives/C1HH3KNJG/p1581540116042300).
=> Update kaws example urls to https

_schema.graphql, _schemaV2.graphql, src/data/kaws.graphql, src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
Addresses: [FX-1697](https://artsyproduct.atlassian.net/browse/FX-1697)
This is follow up to [kaws work](https://github.com/artsy/kaws/pull/196) that introduces a new `size` argument that allows for limiting the number of collections that `relatedCollections` returns.
=> [FX-1697] update kaws schema with new size arg for relatedCollections

src/schema/v2/me/conversation/index.ts
As part of https://github.com/artsy/metaphysics/pull/926 we removed message snippet from conversation. Now that the original issue is solved. I think we are safe to bring this back.
I only brought back snippet for V2 schema. V1 still returns `null`.
=> Bring back last message snippet

src/schema/v2/home/__tests__/home_page_artwork_modules.test.js, src/schema/v2/home/home_page_artwork_modules.ts
Mobile Experience is going to be removing the generic genes from the home page of the app, but we found that Metaphysics was _always_ adding them (despite including them in the `exclude` parameter). This PR adds support for this use case, as well as some typings.
Co-authored-by: David Sheldrick <david.sheldrick@artsymail.com>
Co-authored-by: Brian Beckerle <brian.beckerle@artsymail.com>
=> [MX-195] Adds support for excluding generic genes from homepage modules

_schemaV2.graphql, src/schema/v2/me/__tests__/index.test.js, src/schema/v2/me/index.ts
This PR adds `unreadNotificationsCount`, which returns only the `total_unread` count from gravity's notifications API.
Currently, the `NotificationsBadge` in reaction uses a different count (one that _won't_ get updated when a user views their `/works-for-you` tab). This means that users are never able to "dismiss" that badge. I believe this is just a regression from when we added the new nav bar.
After this, I'll update reaction to pull from this value when setting the server-side "notifications count". This should fix the regression.
[Note that there are [many ways to skin this cat](https://artsy.slack.com/archives/CA8SANW3W/p1582140879406800)! We should have a larger conversation about what these "notifications" even _mean_ and whether we need a cross-platform solution, but I'd like to …
=> Adds unreadNotificationsCount to "Me"

src/schema/v2/__tests__/auction_results.test.js, src/schema/v2/artist/index.ts
https://artsy.slack.com/archives/C0HP61PUJ/p1582318930117800
Right now when going to auction results page on artists we get an empty page because of current latency issues. We decided to return empty results back so artist page shows up but we won't have any auction results till database is back to normal.
=> Remove auction results for now

_schemaV2.graphql, src/schema/v2/me/__tests__/identity_verification.test.ts, src/schema/v2/me/identity_verification.ts
Noticed that there was a v1 import into v2, which included an invalid `__id` field. This fixes the import reference. 
For reference, started noticing test failures downstream as can be [seen here](https://circleci.com/gh/artsy/reaction/52499?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).
=> Fix ID mismatch between v1 and v2

src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/startIdentityVerificationMutation.test.ts
* remove `STUB: ` language from docstrings
* update test data to be more realistic
Jira: https://artsyproduct.atlassian.net/browse/AUCT-897
Bit hard to know that this is working from the diff itself, so here are a couple of selfies proving it
=> Mutate in Gravity when calling `startIdentityVerification` mutation

_schema.graphql, src/schema/v1/artwork/__tests__/artwork.test.js, src/schema/v1/artwork/index.ts
Pairing with @ansor4 
This will be used to calculate local shipping for artworks within EU local shipping zone.
We've added this eu_shipping_origin in Gravity here: https://github.com/artsy/gravity/pull/12795
=> Add euShippingOrigin as an attribute on the Artwork

_schemaV2.graphql, src/schema/v2/__tests__/startIdentityVerificationMutation.test.ts, src/schema/v2/startIdentityVerificationMutation.ts
builds off of https://github.com/artsy/metaphysics/pull/2202
- We want to keep language consistent everywhere – "flow" in Gravity but "wizard" in MP is no good
- THIS MUTATION ISN'T YET USED IN REACTION YET
+ so this should be safe to deploy with 0 production risks
STEP 2: https://github.com/artsy/reaction/pull/3205
=> [step 1] UNUSED API BREAKING CHANGE: Rename identityVerification{Wizard,Flow}Url …Rename wizard to flow

README.md
I swear I've done this before... 
Anyway, updates he endpoint links to point to v2 by default.
=> Set v2 as default endpoint

.vscode/settings.json, index.js
The default (non v2) is now a bit confusing since most clients have been migrated.
=> Update "listening on" log to point to v2 and exclude from VSCode search

_schemaV2.graphql, src/schema/v2/artist/index.ts
Fixes [PURCHASE-1764](https://artsyproduct.atlassian.net/browse/PURCHASE-1764)
~Depends on https://github.com/artsy/diffusion/pull/191 to work but since diffusion is REST this is _safe_ to merge.~ (merged)
Also removed the last pieces of old `organization` param (replaced by `organizations`)
**Screenshot:**
=> [PURCHASE-1764] Add `categories` (also known as medium in UI) to auction results

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
Apparently `sale.live` is not a thing in Gravity API v1 and this was always evaluating to `false` in staging. Instead, we should be looking at [`auction_state`](https://github.com/artsy/gravity/blob/6f3f75b39fd88dbc7181c71a53f128aefd00e8f5/app/models/domain/sale.rb#L201-L207), which has no ambiguity 😎 I've also added one more test for the `preview` state.
=> Fixes a bug where lot condition report can not be enabled

src/schema/v2/home/context.ts, src/schema/v2/home/fetch.ts
This `featuredGene` loader can return `undefined` (changed to `null` here for TypeScript's sake), but the result was being treated as a valid `Gene` object here. This caused problems further down the line when trying to extract data from the gene. The solution is just to propagate the `null` so that downstream we don't expect any data to be there.
Here's an example error report that this fixes: https://sentry.io/organizations/artsynet/issues/1214701920/?project=299996&query=is%3Aunresolved
https://artsyproduct.atlassian.net/browse/MX-252
=> [MX-252] Fix bug in For You query

_schema.graphql, _schemaV2.graphql, src/schema/v2/__tests__/artworksByInternalID.test.ts, src/schema/v2/artworksByInternalID.ts, src/schema/v2/schema.ts
Adds a new root field `artworksByInternalID` which allows us to query for a specific array of artworks:
```graphql
{  
artworksByInternalID(ids:["597ff9ba2a893a25d8244bac"]) {
internalID
}
}
```
=> [Addition] Add new `artworksByInternalID` root field

src/data/convection.graphql, src/lib/stitching/convection/__tests__/stitching.test.ts
This PR gets MP up to date with the changes over on https://github.com/artsy/convection/pull/526. There are breaking changes here, but only on the query operations, not the mutations. That's important because Eigen uses those mutations and drift here would cause errors on shipped versions of the app.
=> Update convection schema

src/lib/stitching/convection/stitching.ts
This was a miss on my part where I didn't check that the mapping from convection artist ids to gravity artist ids was lined up. Volt couldn't resolve this so once this is in, then I can go back over there and get my stitching working correctly again.
=> Fix convection artist id mapping

_schemaV2.graphql, src/schema/v2/home/__tests__/home_page_sales_module.test.js, src/schema/v2/home/home_page_sales_module.ts, src/schema/v2/home/index.ts
This is to support an in-progress Eigen PR: https://github.com/artsy/eigen/pull/3142
It supports a query that looks like this:
I'm adding it to the `HomePage` type because that's what the app uses for its home screen. We want to show live sales on that screen (instead of, as currently, showing some artworks from a [single "featured" sale](https://github.com/artsy/metaphysics/blob/4bad8cfc0ece757a981f9fda93a3845ffd0c534b/src/schema/v2/home/fetch.ts#L48-L60)).
I've got an `any` on `HomePageSalesModuleType` that I don't like but I'm not familiar enough with Metaphysics to figure out what it's _supposed_ to be.
=> Adds sales module to home page

_schemaV2.graphql, src/lib/stitching/kaws/stitching.ts
Noticed that not all arguments, when on Artist, were able to be passed in our stitching configuration for kaws:
=> Pass all arguments to marketingCollections stitching

src/lib/stitching/kaws/__tests__/stitching.test.ts, src/lib/stitching/kaws/stitching.ts
Noticed we were getting back a default collection when querying `... on Artist` and saw that we were passing old v1 `_id`. Updated to pass `internalID`.
=> [Kaws/Stitching] Fix deprecated _id field

_schemaV2.graphql, src/schema/v2/artist/targetSupply/__tests__/index.test.ts, src/schema/v2/artist/targetSupply/index.ts
Adds a new field `isTargetSupply` under our `targetSupply` field namespace. 
```gql
{
artist(id: "andy-warhol") {
targetSupply {
isTargetSupply
}
}
}
```
```json
{
"data": {
"artist": {
"targetSupply": {
"isTargetSupply": true
}
}
}
}
```
=> [Consignments] Add Artist.isTargetSupply

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
The purpose of this PR is to reflect changes that were made to the Gravity GraphQL schema in https://github.com/artsy/gravity/pull/12933. This replaces the `subsectionConnection` that is queryable in a viewing room with a simple array of subsections for simplicity.
=> Reflect changes to the viewing room schema in Gravity

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/stitching.ts, src/lib/stitching/mergeSchemas.ts
Turns out that because we effectively [erase Gravity's version](https://github.com/artsy/metaphysics/blob/19246f1b3caa99f7e9f143168621c3bc8680643b/src/lib/stitching/gravity/schema.ts#L26) of the GQL `Artwork` type when merging Gravity's schema into MP, we were losing that type under `ViewingRoomArtwork`. In other words, we couldn't run a query like this:
```graphql
{
viewingRoom(id: "") {
title
edges {
node {
internalID
artwork {
id
}
}
}
}
}
}
```
...because Metaphysics' schema only had `internalID` inside of `node`.
@mzikherman was kind enough to sit down with me and work through this. With this PR, we're now referencing MP's own `Artwork` type, which is actually handy in the long run since Gravity's `Artwork` type was missing some things like `price` that …
=> Stitch MP Artwork under Grav ViewingRoomArtwork

_schemaV2.graphql, src/schema/v2/artist/targetSupply/index.ts
Forcing a schema rebuild. Something happened where `targetSupply` field was removed from production schema.
=> Fix typo in docs

_schema.graphql, _schemaV2.graphql, src/data/convection.graphql, src/lib/stitching/convection/schema.ts
Partially addresses https://artsyproduct.atlassian.net/browse/CSGN-37.
Depends on https://github.com/artsy/convection/pull/568.
This PR updates the schemas to account for new pagination fields on convection submissions.
=> Submission pagination in convection

_schemaV2.graphql, src/schema/v2/me/__tests__/index.test.js, src/schema/v2/me/index.ts
Add an attribute to the Me type to represent 2FA enrollment status.
Depends upon this API update :lock: : https://github.com/artsy/gravity/pull/12947
=> Add hasSecondFactorEnabled attribute to Me type

README.md
This link has been shared via Slack during recent Metaphysics development. Add the link here so that it's easier to find.
=> Add documentation link for GraphQL Schema Design playbook

scripts/push-schema-changes.js
Following [recent work to sync changes to Eigen](https://github.com/artsy/metaphysics/pull/2288/), lets carry it on to Reaction 🥳 
Ran script locally and seemed to work great, but no actual changes to sync yet: 
@ds300 - https://github.com/artsy/update-repo is seriously cool! Lets broadcast it.
=> Sync schema to reaction on update

_schemaV2.graphql, src/schema/v2/artist/index.ts
Add new filter allows users to filter out lots where created date information is blank.
diffusion changes: https://github.com/artsy/diffusion/pull/226
This can also be used in combination with other date filters:
`allowEmptyCreatedDates=true`
`allowEmptyCreatedDates=false`
when not present - it defaults to true
=> [PURCHASE-1870] Add filter to allow filtering for lots with empty date info

.circleci/config.yml
#2294 upgraded the node image used for the schema sync job to node 12, but MP is still running on node 10 so this broke the build and we need to downgrade again.
Trivial fix, going to self merge.
=> fix node executor

_schemaV2.graphql, src/lib/loaders/searchLoader.ts, src/schema/v2/search/SearchEntity.ts
I noticed that we'd stopped exposing static pages in our search/autocomplete results! Tracked the issue down to here.
This works as expected:
(And with local force pointing this way:)
=> Allow page types to be exposed in search

.circleci/config.yml
#2315 failed [here](https://circleci.com/gh/artsy/metaphysics/8649) because I accidentally used a tag from the `circleci/node` docker images when the new orb had switched to `cimg/node` 🤷‍♂️ . This is trivial again so #self-merging
=> Fix circleci node image tag

.circleci/config.yml
more fallout from #2315 – need to run `apt-get upgrade` before installing pip with this new image
I've tested this locally with the circleci cli tool.
#trivial #selfmerging
=> [Circle config] fix pip installation

_schemaV2.graphql, src/schema/v2/me/__tests__/conversation/__snapshots__/message.test.js.snap, src/schema/v2/me/__tests__/conversation/message.test.js, src/schema/v2/me/conversation/index.ts
Addresses PURCHASE-1868
This PR does 2 things
1. Adds a `totalCount` response to the `MessagesConnection` type. 
2. It deprecates the `messages` field in favor of `messagesConnection`. This wasn't strictly necessary, but was performed for the sake of good schema hygiene.
=> Add total count to messagesConnection

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/__tests__/testingUtils.ts, src/lib/stitching/gravity/stitching.ts, src/lib/stitching/mergeSchemas.ts, src/schema/v2/artworks.ts, src/schema/v2/schema.ts
This PR updates the Gravity stitching library to extend the `ViewingRoom` type with an artwork connection field that will fetch all artworks in a viewing room as a paginated batch.
A resolver for the `ViewingRoomArtwork` type already exist, and its job is to fetch an individual artwork that matches the `artworkID` field. What I am attempting to do is fetch all of the artworks in a viewing room with one query by stitching-in a new connection field on the `ViewingRoom` type that fetches all associated `artworkID`s at once.
=> Resolve viewing room artworks as a batch instead of individually (GALL-2766)

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
Stitching is fun! This PR allows us to access the `partner` type on `viewingRoom` queries so that we can display the partner name and logo in viewing rooms.
I'll note that it looks like not all partners have a `profile` (e.g. an attempt to query for Invoicing Demo Partner's `profile` returns null) and I'm not entirely clear on why they would/wouldn't - might just be a matter of someone having entered information into CMS. Either way, we should make sure to account for the scenario when `profile` is null, but I'm of the opinion that that's Eigen's responsibility.
An example query that gets a partner name and icon:
=> Add partners to viewing rooms

_schemaV2.graphql, src/schema/v2/sale/__tests__/index.test.js, src/schema/v2/sale/index.ts
Problem:
Logic about whether the current user needs to undergo identity
verification is scattered around Reaction and Eigen, increasing risk
that business logic starts to drift and generally is a larger code
surface area than needed.
Solution:
Introduce new field to `Sale` which is the source of truth as to whether
the current user needs to undergo identity verification or not for the
sale in question.
Why introduce this field to `Sale` instead of `me`, `User`, or `Bidder`?
- See this [Slack convo][0].
- Because there are times where the user isn't yet registered to bid, but we
need to know if the current user needs to undergo identity verification
or not, so extending `Bidder` doesn't seem to make sense.
- Moreover, there are even times whether there's no reference to a
current user …
=> Introduce Sale.userNeedsIdentityVerification field

_schemaV2.graphql, src/schema/v2/me/__tests__/conversation/__snapshots__/message.test.js.snap, src/schema/v2/me/__tests__/conversation/message.test.js, src/schema/v2/me/conversation/index.ts, src/schema/v2/me/conversation/message.ts
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-1867
This PR does a few things:
1. Exposes the new `is_first_message` field from impulse as `isFirstMessage` on the `Message` object. This is a useful field to simplify the rendering logic that clients have to perform for rendering the first message. 
2. Updates how `Message.body` renders when it's the first message. Previously, [clients had to determine](https://github.com/artsy/eigen/blob/1c5994a58f6ffb7f1fa83bf9c6e23601f66e01a5/src/lib/Components/Inbox/Conversations/Message.tsx#L140) if they should use `initialMessage` from the conversation or the message. This is unnecessary logic for the clients to have to perform because we _never_ want to show the collector what was being displayed as the first message text. Now, clients …
=> Provide isFirstMessage from Message, remove need for initialMessage

src/schema/v2/image/index.ts, src/types/gravity/artworkResponse.d.ts
We were using the wrong name coming from gravity.
Using this query
```
{
show(id: "5e6e2efe4d2aa0000e2be3da") {
name
images {
imageURL
isDefault
}
}
}
```
I would get something like
```
{
"data": {
"show": {
"name": "ART ON PAPER",
"images": [
{
"imageURL": "https://d32dm0rphc51dk.cloudfront.net/7vFrlr0sqJBwP7T478Vvbw/:version.jpg",
"isDefault": null
},
{
"imageURL": "https://d2v80f5yrouhh2.cloudfront.net/prVTNCjKDNEdVPYoq41prQ/:version.jpg",
"isDefault": null
},
{
"imageURL": "https://d2v80f5yrouhh2.cloudfront.net/6aAeK7lCF1bQxBeeXxteIA/:version.jpg",
"isDefault": null
}
]
}
}
```
but now I get
```
{
"data": {
"show": {
"name": "ART ON PAPER",
"images": [
{
"imageURL": "https://d32dm0rphc51dk.cloudfront.net/7vFrlr0sqJBwP7T478Vvbw/:version.jpg",
"isDefault": false
},
{
"imageURL": …
```
=> Read the correct field from gravity

_schemaV2.graphql, src/schema/v2/artist/index.ts, src/schema/v2/home/__tests__/home_page_artist_module.test.js, src/schema/v2/home/homePageArtistInterface.ts, src/schema/v2/home/home_page_artist_module.ts, src/schema/v2/schema.ts
These were being returned from Gravity but then discarded. This exposes them through a new GraphQL Interface using a conditionally backwards-compatible schema change (ie: we need to make sure to expose any data clients are expecting in the new Interface). I've checked Emission's history to gather them all, and the resolver isn't currently referenced in Reaction, so we should be fine.
This allows us to continue requesting the data in queries as-is, but also expose a new `basedOn` field for `SuggestedArtist` objects. Existing queries work, and we don't need to deprecate anything to get the data 🎉  
The query looks like this:
```graphql
{
homePage {
artistModules {
id
key
results {
__typename
name
... on SuggestedArtist {
basedOn {
name
}
}
}
}
}
}
```
And we receive results like this: …
=> [MX-245] Exposes basis of artist suggestions through schema

src/schema/v1/home/__tests__/home_page_artwork_module.test.js, src/schema/v1/home/title.ts
https://artsyproduct.atlassian.net/browse/MX-281
Updates the home rails on web to use title casing and be consistent with mobile. schema v1 vs v2.
=> [MX-281] - Title casing for web home rails #trivial

_schemaV2.graphql, src/schema/v2/artist/index.ts, src/schema/v2/home/__tests__/home_page_artist_module.test.js, src/schema/v2/home/home_page_artist_module.ts
Originally implemented in https://github.com/artsy/metaphysics/pull/2335. We had to revert that change in #2338 because it broke the existing app. It turns out that the schema change wasn't as backwards-compatible as we'd thought. 
Everything would work as expected in a structured query like this:
```graphql
{
homePage {
artistModules {
results {
name
... on SuggestedArtist {
basedOn {
name
}
}
}
}
}
}
```
But the problem is that Relay is more explicit in how it asks for data, creating queries that explicitly reference the type in a fragment spread:
```graphql
fragment ArtistCard_artist on Artist {
name
}
fragment ArtistRail_rail on HomePageArtistModule {
results {
__typename
...ArtistCard_artist
}
}
fragment Home_homePage on HomePage {
artistModules {
...ArtistRail_rail
}
}
query …
```
=> [MX-245] Adds basis for artist suggestions in schema

src/schema/v2/home/__tests__/home_page_fairs_module.test.js, src/schema/v2/home/home_page_fairs_module.ts
We were seeing fairs listed in the app sorted only by start_at, which put some fairs that haven't actually started yet at the front of the list. This places fairs whose `start_at` is in the future at the end of the list.
I've taken a follow-up to re-examine some of the other logic in here, since it's kind of weird!
=> Re-orders fair results so that fairs that haven't started yet are at the end

src/lib/__tests__/helpers.test.ts, src/lib/helpers.ts
https://artsy.slack.com/archives/CP9P4KR35/p1588364384042800
When working on https://github.com/artsy/metaphysics/pull/2345 I noticed a viewing room without any artworks will return artworks connection with `totalCount 0` but with real artwork nodes (see screenshot below).
It turns out qs [`stringify`](https://github.com/artsy/metaphysics/blob/c501f9063d1c3d573db86d1006b58939dc2357f8/src/lib/helpers.ts#L71) [ignores empty array/object](https://github.com/ljharb/qs/issues/362) so we are not sending `ids[]=` to Gravity when it's empty. Therefore, Gravity is returning _all_ artworks.
This adds a regression test and uses qs `filter` function as a workaround to map empty array to value that it respects. It's a workaround, but since it's implementation details of the `toQueryString` helper and …
=> Preserve empty array in query string

src/lib/__tests__/helpers.test.ts, src/lib/helpers.ts
Reverts artsy/metaphysics#2351
Rather than fixing this globally, we should just fix these as they come up. So in the specific case of `artworks`, it can be addressed specifically there (removing the param entirely if empty).
=> Revert "Preserve empty array in query string"

src/lib/__tests__/helpers.test.ts, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
https://artsyproduct.atlassian.net/browse/GALL-2836
In https://github.com/artsy/metaphysics/pull/2351, we changed the behavior globally. Unfortunately, there are multiple places clients are sending empty array params but expecting APIs (e.g. Gravity) to ignore that and return non-empty results.
It seems not easy to exhaustively fix everywhere so this is a fix just for viewing room artworks.
Tests are trying to catch issues by this workaround in case the underlying implementation changes. Ideally I'd be interested in more integration type of tests but I'm not sure how. So my approach here is:
- Test that we are mapping argument properly for dataloader to use.
- Then test with the mapped argument, the query string conversion that dataloader is relying on converts the argument to desired …
=> Preserve empty array in query string for viewing room artworks (GALL-2836)

_schemaV2.graphql, src/lib/stitching/kaws/__tests__/stitching.test.ts, src/lib/stitching/kaws/stitching.ts, src/schema/v2/home/homePageMarketingCollectionsModule.ts, src/schema/v2/home/index.ts
This PR adds a new module to the top-level `homePage` field so that we can make queries like this:
```graphql
{
homePage {
marketingCollectionsModule {
results {
title
artworksConnection(first: 3) {
edges {
node {
slug
}
}
}
}
}
}
}
```
Here it is working locally:
This is to support MX work to include three collections (New this Week, Highlights at Auction, and Trending Emerging Artists) in the app's home page. I chose to add this `homePage` module, rather than have the app query the collections itself, so that MP is the source of truth for which collections get displayed in the app.
GraphQL objects must have _at least one_ field prior to being stitched, so I had to add an `_unusedField` field. I marked it as deprecated with a clear explainer and it always returns `null`, but I'm open to …
=> [MX-291] Adds homePage.marketingCollectionModule.results

.circleci/config.yml
Halt the CI release if a Horizon deploy block is found.
=> Add horizon/block step to release Circle CI workflow

src/schema/v1/__tests__/ordered_sets.test.js, src/schema/v1/ordered_sets.ts, src/schema/v2/__tests__/ordered_sets.test.js, src/schema/v2/ordered_sets.ts
This is only exposed in v1 apparently. Used for fetching sets of pre-defined genes.
=> Fixes for return value of setsLoader

index.js, src/index.ts
Problem
Currently, the V1 and V2 routes are being as originating from the
URL in Datadog. This is preventing us from being able to track how
many requests are hitting each endpoint and determine how many
clients are still using the V1 routes.
Solution
This change initializes Datadog earlier so that we will be able to 
differentiate the V1 and V2 APIs.
Due to the way that Datadog internally recognizes "valid" routes, if
dd-trace has not loaded and monkey patched express prior to a
route being defined. Datadog will associated it with the highest
applicable bucket. In this case that would be `/`.
Additionally, there is a minor refactoring that removes a extra 
express app that wasn't required.
=> Add Datadog Route Tracing for V2 Routes

src/schema/v2/me/index.ts
This seems like a pattern we had adapted a long time ago that no longer seems to be valid. WIth this change, we will be able to see the error in the `errors` property in the response:
=> Remove error handling from meLoader

src/schema/v2/home/home_page_sales_module.ts
We were showing all the sales on the home page instead of just the sales that are auctions (a slight difference, but basically we have some BNMO sales that aren't auctions – see the ticket for more info). This PR updates the home page to return the same data as fetched in the Auctions view in the app:
https://github.com/artsy/eigen/blob/dd7c200a809fa81a423c94fab28097cc261ff15c/src/lib/Scenes/Sales/index.tsx#L115
By fixing this on MP, we'll get this to all users without an app update.
=> [MX-325] Limits home page sales to auctions #trivial

_schema.graphql, _schemaV2.graphql, package.json, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts, yarn.lock
This adds a new `formattedEndAt` field to our stitched viewingRoom field off of Gravity. 
This doesn't match the comps exactly, but gets close via the [moment.distance](https://github.com/SokratisVidros/moment.distance.js) plugin.
=> Add formattedEndAt to viewingRoom

src/data/gravity.graphql, src/lib/stitching/gravity/schema.ts
For ticket: https://artsyproduct.atlassian.net/browse/AUCT-1007
To un-stitch Gravity `IdentityVerification` graphql schema/type which has not been in use.
Related Gravity PR: https://github.com/artsy/gravity/pull/13054
Metaphysics PR is to be merged/deployed first. Then Gravity PR.
The type was listed in `lib/stitching/gravity/schema.ts` under `duplicatedTypes`. My understanding is is that MP has a type of the same name (resolving to Gravity's REST endpoints). `duplicatedTypes` hides Gravity's version so it has not been visible to clients. Therefore, this change does not require any client-side changes.
=> Un-stitch Gravity IdentityVerification.

scripts/push-schema-changes.js
Following up on https://github.com/artsy/eigen/pull/3319, this PR adds a conditional `yarn relay` that is triggered when updating Eigen's copy of MP schema.
@ds300 I'm not sure how to go about testing this, either writing tests or just running them in my terminal. Any advice for me?
=> Update relay types when updating Eigen's copy of MP schema

scripts/push-schema-changes.js
Reimplementation of #2396 
This time we call relay-compiler directly instead of using `yarn`, to avoid the engines check (MP is on node 10 while eigen and reaction are on 12). I also moved the code around a little to make sure that TypeScript can check the data we pass to `updateRepo` (cc @damassi)
Gonna self-merge before y'all wake up to make sure it works this time.
=> Run relay-compiler when updating emission/eigen

src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
Followup on https://github.com/artsy/eigen/pull/3322
We learned that the viewing rooms connection stitched under partner is returning _all_ viewing rooms, regardless of specified partner id. It turns out to be another 🐍 vs. 🐫 issue.
=> Fix viewing rooms not filtered by partner id

_schemaV2.graphql, src/schema/v2/me/__tests__/index.test.ts, src/schema/v2/me/index.ts
Builds off of https://github.com/artsy/metaphysics/pull/2402 (but OK to merge this in before that I think)
One feature of email verification is the ability for an existing user to
verify their email from web or iOS via a banner on web and a sash on
iOS.
One important aspect of these UIs is knowing _whether it is
appropriate to display them or not_.
Moreover, we have been bitten a bit in the past by pushing too much of
this "should I display this UI" logic directly to Reaction or Eigen.
This has resulted in:
1. High risk of code duplication and therefore drift between web and iOS
clients
2. iOS binary lock-in: Important "should I display this UI" logic lives
forever in old binaries of Eigen, making it hard for our engineering
team to ensure a particular experience and locking us in to old …
=>  Introduce `Me.canRequestEmailConfirmation`

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/send_confirmation_email_mutation.test.js, src/schema/v2/me/sendConfirmationEmailMutation.ts, src/schema/v2/schema.ts
This PR adds a new mutation `sendConfirmationEmail`:
```graphql
mutation {
sendConfirmationEmail(input: {}) {
confirmationOrError {
... on SendConfirmationEmailMutationSuccess {
confirmationSentAt
unconfirmedEmail
}
... on SendConfirmationEmailMutationFailure {
message
}
}
}
}
}
```
The empty `input: {}` is a little odd, but I wasn't sure how I could make a mutation without inputs, so I just left it there. In the future, it might make sense to update it to e.g. `sendConfirmationEmail(input: { newEmail: "..." })` so users can request an email update using the same mutation, so it might not be that bad.
```
src/schema/v2/me/sendConfirmationEmailMutation.ts:74:12 - error TS2722: Cannot invoke an object which is possibly 'undefined'.
74     return emailConfirmationLoader() …
```
=> Blocked: Add SendConfirmationEmail mutation

src/schema/v2/__tests__/artworks.test.ts, src/schema/v2/artworks.ts
https://artsyproduct.atlassian.net/browse/GALL-2844
Following up on https://github.com/artsy/metaphysics/pull/2364, the workaround of using `[null]` as the empty `ids` param ended up causing the artworks loader to return `totalCount: 1` when it should be `0`.
In fact, the total count should not rely on the `ids` params caller passed in, and should instead calculated from the response. In this case when `ids` are passed in, Gravity [doesn't paginate](https://github.com/artsy/gravity/blob/6df1e3524d1bcb60a6c6773a487b4a560788b5db/app/api/v1/artworks_endpoint.rb#L166-L169) (and include the `X-TOTAL-COUNT` in the headers), so we can simply use the length of the response body.
=> Fix total count from v2 root artworks field (GALL-2844)

_schemaV2.graphql, package.json, src/schema/v2/artist/targetSupply/__tests__/index.test.ts, src/schema/v2/artist/targetSupply/index.ts, src/schema/v2/artist/targetSupply/utils/getMicrofunnelData.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, yarn.lock
Adds a new `artworksConnection` to `microfunnel` and moves `realizedPrice` directly to the artwork type, which fixes a handful of issues around querying for microfunnel data inside of a connection context. This should also make work in https://github.com/artsy/metaphysics/pull/2414 much more seamless. 
```graphql
{
artist(id: "alex-katz") {
targetSupply {
microfunnel {
artworksConnection(randomize: true, first: 1) {
edges {
node {
realizedPrice
}
}
}
}
}
}
}
```
```json
{
"data": {
"artist": {
"targetSupply": {
"microfunnel": {
"edges": [
{
"node": {
"realizedPrice": "$5,000"
}
}
]
}
}
}
}
}
}
```
=> [Consignments] Add artworksConnection to microfunnel & realizedPrice to Artwork

_schemaV2.graphql, src/schema/v2/filterArtworksConnection.ts
~~⚠️ Dont merge before https://github.com/artsy/gravity/pull/13109 is deployed. ⚠️~~
Artist Auction Results already has a field called `sizes`, so we can use the same, for consistency.
=> consistency with auctions existing filter for size buckets

src/schema/v2/me/index.ts
It was assumed that Gravity was respecting the feature flag, but it
wasn't, caused this to be released too early.
=> Hotfix: hardcode `canRequestEmailConfirmation` to `false`

src/schema/v2/me/index.ts
Reverts artsy/metaphysics#2444
Now that https://github.com/artsy/gravity/pull/13132 is deployed to production, we can re-enable our MP to Gravity proxy, unblocking further QA/work on email verification.
=> Revert "Hotfix: hardcode `canRequestEmailConfirmation` to `false`"

_schemaV2.graphql, src/schema/v2/me/__tests__/index.test.ts, src/schema/v2/me/index.ts
A `phone` field is already being returned from gravity, we just expose it in this PR.
=> Add phone number to Me type

_schemaV2.graphql, package.json, src/lib/stitching/exchange/stitching.ts, src/schema/v2/artwork_version.ts, src/schema/v2/object_identification.ts, yarn.lock
@zephraph and I paired on this for a while this afternoon. We removed `ArtworkVersions` as a root field from MP v2 and we rely on it for some orders (see Jira ticket linked below for more details). We figured that instead of just re-adding `ArtworkVersions` as a root field, we might be able to instead have it `implement Node` and stitch it into MP's Exchange schema that way.
We got pretty far with that approach, but we got stuck at the end: we could return `id` and `__typename`, but not the actual contents of `ArtworkVersions`. When running a query ourselves, we did that by adding `... on ArtworkVersions`, but we're unsure if it's possible to add that to the `ArtworkVersion` fragment.
@mzikherman any ideas on this? @zephraph anything I missed?
Some screenshots that demonstrate this: …
=> Query for ArtworkVersions on orders using Node [GALL-2963]

README.md
Just removing the `$` from script parts in the README.
=> these just make copy paste harder

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap, src/lib/stitching/gravity/schema.ts
https://artsyproduct.atlassian.net/browse/FX-2005
This PR stitches `ArtistSeries` field from Gravity into Metaphysics.
`DO NOT MERGE` until we have clarity on schema changes from Viewing Room.
collab: @ashleyjelks @anandaroop
=> Add stitched ArtistSeries field

src/index.ts
Use Raven's config to ignore 404s from Gravity and requests without a query. I tested locally with Sentry staging's DSN.
https://artsyproduct.atlassian.net/browse/AUCT-1088 🔒
=> exclude noisy Sentry errors

Dockerfile
Potential fix to post-deploy errors, adds bash to Dockerfile (node upgrade pr included switch to alpine). I'm guessing that we aren't able to run the script because we don't have bash installed. The error itself is `[dumb-init] .circleci/deploy_event.sh: No such file or directory` however.
https://circleci.com/gh/artsy/metaphysics/10090
=> Add bash to docker image

src/schema/v2/home/__tests__/home_page_hero_units.test.js, src/schema/v2/home/home_page_hero_units.ts
Last one I'm pretty sure 🙈 
Follow-up to the work in gravity (https://github.com/artsy/gravity/pull/13153, https://github.com/artsy/gravity/pull/13163, https://github.com/artsy/gravity/pull/13179) and torque (https://github.com/artsy/torque/pull/1180).
This PR updates the resolution logic for the background image, the title, and the description (aka subtitle) to make sure that mobile (app, not web) hero units are taking data from the correct gravity fields.
=> Add new mobile hero unit resolution logic

_schemaV2.graphql, src/schema/v2/__tests__/ordered_sets.test.js, src/schema/v2/ordered_sets.ts, src/schema/v2/schema.ts
This is needed for /artists to be converted to use Metaphysics V2. I was thinking about re-adding this as a connection, but all the use cases of this in Force truly use it as an array and want to fetch all of them (or rather, up to 10 since that's Gravity's default size, and none of the usages in Force specify any size or pagination).
So, I opted to re-add this as a straight list, but explicitly removed any pagination arguments (which were unused).
=> @dzucconi => [OrderedSets] Readd root type to V2 schema

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
https://artsyproduct.atlassian.net/browse/FX-2054
Allow for metaphysics to return an artist series' artists. 
Current artists fields is a list, rather than an artistsConnection field, this is reasonable for our use case because we don't expect the list of artists to be so long that it needs pagination. 
We followed existing patterns from Viewing Rooms.
=> Add Artists field to Artist Series

_schemaV2.graphql, src/schema/v2/__tests__/shows.test.js, src/schema/v2/schema.ts, src/schema/v2/shows.ts
Add endpoint `Shows` to fetch a list of shows by id, required for Positron to use v2: artsy/positron#2734
Addresses: https://artsyproduct.atlassian.net/browse/PLATFORM-2541
Related conversation: https://artsy.slack.com/archives/C1HH3KNJG/p1591886620093000
=> Add Shows endpoint

_schemaV2.graphql, src/schema/v2/__tests__/partners.test.js, src/schema/v2/filter_partners.ts, src/schema/v2/partner_category.ts, src/schema/v2/partners.ts, src/schema/v2/schema.ts
Partners is required for Positron to use v2, https://github.com/artsy/positron/pull/2734
Addresses: https://artsyproduct.atlassian.net/browse/PLATFORM-2491
Related conversation: https://artsy.slack.com/archives/C1HH3KNJG/p1591886620093000
=> Re-enable Partners root field, convert to connection

_schemaV2.graphql, src/schema/v2/__tests__/show.test.js, src/schema/v2/fields/__tests__/markdown.test.ts, src/schema/v2/fields/markdown.ts
We have this `markdown` helper for text fields. It's for text that contains markdown. It has an optional parameter called `format` which can have a value of either `HTML` or `MARKDOWN`. the `HTML` option is used in web clients to avoid the need to convert the markdown to html in the client itself.
So if you request a text field like
```graphql
someObject {
textField
}
```
you get markdown back
and if you request a text field like
```graphql
someObject {
textField(format: HTML)
}
```
you get HTML back
but if you request a text field like
```graphql
someObject {
textField(format: MARKDOWN)
}
```
you _also get HTML back_ !
This PR fixes that.
This won't be a breaking change. I checked the whole of the artsy org and didn't find any places where the 'markdown' format option is explicitly used.
=> Fix markdown formatter args handling

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/impulse.ts
Fixes [PURCHASE-1959](https://artsyproduct.atlassian.net/browse/PURCHASE-1959) and last piece of [PURCHASE-1954](https://artsyproduct.atlassian.net/browse/PURCHASE-1954)
Follow up to https://github.com/artsy/impulse/pull/621 we want the client to see authorized pending delivery messages
=> [PURCHASE-1959] Add `include_delivery_pending` flag to impulse `message_details` query

_schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/__tests__/testingUtils.ts, src/lib/stitching/gravity/stitching.ts, src/lib/stitching/mergeSchemas.ts, src/schema/v2/filterArtworksConnection.ts
https://artsyproduct.atlassian.net/browse/FX-2035
---
Users need to be able to look up all the artworks associated with a given artist series.
After modifying the `/filter/artworks` endpoint to be able to query for artworks associated with an artist series (https://github.com/artsy/gravity/pull/13211), we now need to expose querying for an artist series's artworks in Metaphysics. Once this is merged, a frontend client will be able to request the artworks associated with an artist series.
The bulk of this work is stitching `FilterArtworks` into `ArtistSeries` for v2. We did _not_ stitch for v1 because we are deprecating v1.
=> Expose filteredArtworksConnection under ArtistSeries

_schemaV2.graphql, src/index.ts, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/sales.test.ts, src/schema/v2/sales.ts, src/types/graphql.d.ts
- Adds `userRoles` to `ResolverContext`, decoded from JWT when present
Updates `salesConnection` to:
- remove default arguments `published`, `isAdmin`, `isLive` (let gravity provide defaults)
- use authenticated loader if user role is `team`
Context:
Positron's admin UI allows artsy staff to link articles to gravity models. The `salesConnection` must return unpublished/non-live content so that these associations can be added or removed from an article despite changes to publish status. 
This endpoint is limited to `team` under the assumption that all `admin` users are also `team` users. The positron UI is currently limited to `admin`s only, but is ticketed to use `team` instead.
Follow up to https://github.com/artsy/metaphysics/pull/2499
Related to …
=> salesConnection endpoint can return unpublished content to team users

_schemaV2.graphql, src/schema/v2/__tests__/users.test.js, src/schema/v2/schema.ts, src/schema/v2/user.ts, src/schema/v2/users.ts
Required for Positron to migrate to v2.
Re-enables `users` endpoint as `usersConnection`.
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-2574
Related to https://artsyproduct.atlassian.net/browse/PLATFORM-2473
=> Reenable users endpoint, convert to connection.

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/schema.ts, src/lib/stitching/gravity/stitching.ts
[FX-2059](https://artsyproduct.atlassian.net/browse/FX-2059)
---
Users want to be able to see lists of artist series, including all the artist series by a given artist. Currently, we can only query that information from Gravity, which means clients can't query for it.
Add `artistSeriesConnection` type to Metaphysics and stitch into `Artist`.
=> Add artistSeriesConnection and stitch into Artist

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
https://artsyproduct.atlassian.net/browse/FX-2060
This PR just adds a missing schema bump to support the earlier work for this^ ticket that happened in https://github.com/artsy/gravity/pull/13263
=> Update gravity schema

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
Pretty minor! We have to include the standard pagination arguments in this stitched file (ie- `first` for the size), even though all we do is pass it through to the underlying subschema.
=> @williardx => [ArtistSeries] Include pagination args for stitched connection under artist

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
Pretty much an exact duplicate of what was already done in https://github.com/artsy/metaphysics/pull/2524 to stitch in an `artistSeriesConnection` under an `Artist`.
This follows that pattern, but for `Artwork`. The reality is most likely an artwork will be in one series (and the designs for 'More works from this series' with one rail should select the first one based on the default order), but, we support multiples so it seems easier to keep that consistent. For an `Artist`, it's of course more natural than for an `Artwork` to have multiple series to return and display.
=> @anandaroop => [Artwork] Stitch in artistSeriesConnection

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
Whoops forgot this one! Exposes a plain `artworksConnection` which skips ES.
=> @anandaroop => [ArtistSeries] Expose artworksConnection

src/schema/v2/me/index.ts
I was QA'ing [MX-414] and I noticed that the fields were being returned as `null` and that Gravity wasn't being hit, unless I requested other fields.
Before:
After:
Looks like this is to avoiding hitting Gravity unnecessarily. But in the case of Pulse, we might only be getting these attributes, so I've removed the fields from the list of things we don't need to ask Gravity about.
Follow-up from #2536.
[MX-414]: https://artsyproduct.atlassian.net/browse/MX-414
=> Forces Gravity request for push notification settings fields.

hokusai/production.yml
HPA threshold was raised to 70% under this PR:
https://github.com/artsy/metaphysics/pull/2552
After its release p95 latency increased.
This PR is to revert the threshold to 60%.
=> Revert prod HPA threshold to 60%.

_schemaV2.graphql, src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/index.ts
Partially addresses https://artsyproduct.atlassian.net/browse/AUCT-1164
This exposed the newly added `is_artsy_licensed` flag on the sale model so our clients can use that in e.g. sale winning emails.
=> Add isArtsyLicensed to the sale type

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
https://artsyproduct.atlassian.net/browse/FX-2120
We want to show lists of related artist series but exclude some artist series from showing, e.g. the current artist series the user is looking at.
Expose `excludeIDs` as an argument for `artistSeriesConnection` on `Artist` and `Artwork`.
**Before**
**After**
=> Add excludeIDs as argument for artistSeriesConnection

_schemaV2.graphql, src/schema/v2/SearchableItem/SearchableItemPresenter.ts, src/schema/v2/search/SearchEntity.ts
Pretty straightforward. It works just as well w/ or w/o any actual artist series results being returned in search (which is based on the gravity feature flag, on in staging and off in prod).
=> @sweir27 => [Search] Allow artist series to be returned from search

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
https://artsyproduct.atlassian.net/browse/FX-2122
When viewing an artist series users can see a list of other series by that artist. We don't want that list to show the current artist series.
When querying for an `artistSeriesConnection` on an artist, pass in the current artist series as an `excludeID` parameter to Gravity which will return a list without the current artist series. If there's no current artist series then we don't send the parameter.
This is an alternative solution to https://github.com/artsy/metaphysics/pull/2569 and undoes the work in that PR.
This bakes in an assumption in our product that, when querying for an `artistSeriesConnection` on an artist, we don't want to see the current artist series in that list if there is one. As of now there's no product use case where …
=> Exclude current artist series when querying for related artist series

src/index.ts
Context here is that Googlebot (and others?) are erroneously crawling and causing undue load on Metaphysics, leading to instability in Force. See `#incident-96` for more details.
Already mentioned in the README is:
So I think we just need to make it known to anyone who was still relying on the hosted instances.
=> Disables GraphiQL in production

_schema.graphql, _schemaV2.graphql, src/lib/stitching/convection/__tests__/stitching.test.ts, src/lib/stitching/convection/__tests__/testingUtils.ts, src/lib/stitching/convection/stitching.ts, src/schema/v2/fields/__tests__/money.test.ts, src/schema/v2/fields/money.ts
This PR stitches in a few new fields which piggy back on our [money utils](https://github.com/damassi/metaphysics/blob/2e1c89f763d9f15d16c02f5ca193d5d1d641048c/src/schema/v2/fields/money.ts#L28) and will allow us to extend things around different currencies, etc:
- `lowEstimateAmount` 
- `highEstimateAmount`
Additionally cleaned up our testing environment by setting up some common things based on existing patterns. 
```graphql
{
offers(gravityPartnerId: "-----") {
edges {
node {
currency
id
highEstimateAmount
highEstimateCents
lowEstimateCents
submission {
id
}
}
}
}
}
```
```js
{
"data": {
"offers": {
"edges": [
{
"node": {
"currency": "USD",
"id": "4477",
"highEstimateAmount": "$100,000",
"highEstimateCents": 10000000,
"lowEstimateAmount": "$10,000",
"lowEstimateCents": 1000000, …
```
=> [Convection] Stitch in currency fields

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
For context: https://artsy.slack.com/archives/C9ZJYFDNF/p1596812574455900.
The gravity schema on MP was not synced with the actual gravity schema generated by gravity, so eigen/force/volt would go to MP asking for `viewingRooms {`, MP would take that and make it `viewingRooms(statuses: []) {` and gravity would return the empty array. The default value in gravity is `[live]`, but this was not in sync with MP. It still had the old schema with the default value of `[]`.
=> Quick fix for MP and viewingRooms using `statuses`

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
This PR adds the `statuses` field in the viewer we created for force for `viewingRooms`
I tried adding a test for `inputFields include statuses`, but I couldn't add this in an easy way.
I tried getting it by using something like `getFieldsForTypeFromSchema` but for inputFields, but there is no "type" that these are attached to.
I did find and try [this](https://gist.githubusercontent.com/craigbeck/b90915d49fda19d5b2b17ead14dcd6da/raw/e50819812a7a8a95b303ac0ea1464e2679e3e4bc/introspection-query.graphql) which worked and gave me the whole schema basically. I'm sure we could use this in a test and get everything and them map it in an object that we can ask like `Viewer.viewingRoomsConnection.inputFields includes statuses`.
=> Viewer fix for statuses

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
We need to be able to input markdown for Artist Series descriptions and have them render properly. While we do have a coffeescript-based markdown -> html converter already in force, it seems that we prefer to be able to return multiple formats from metaphysics and have this layer do the conversion.
[Note: happy to adjust course if we want to handle markdown in force, but converting to HTML here seemed like the cleanest option that followed existing patterns].
For types defined in metaphysics, we have an easy way to include handling for different formats. However, `ArtistSeries` is a type stitched in from Gravity. I extended the type in gravity's stitching file as `descriptionFormatted`. The naming was chosen so that it would show up alphabetically next to `description` in the docs.
The …
=> Allow for formatting of markdown description for artist series

hokusai/production.yml, hokusai/staging.yml
- The current staging rolling update settings (`maxSurge`, `maxUnavailable`), along with HPA `minReplicas` setting, allow the situation of having 0 pods during a rolling update. Changing rolling update settings to ensure that there's always at least 1 pod available during deployment.
- True up staging/prod preStop settings according to: https://github.com/artsy/artsy-hokusai-templates/blob/ac33c4db8754143318612497f68361b64ea1abd6/nodejs/hokusai/staging.yml.j2#L68
These changes should eliminate some Pingdom alerts.
---
Kubernetes doc on rolling update parameters: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-surge
=> Tune staging rolling update parameters.

_schema.graphql, _schemaV2.graphql, src/data/vortex.graphql, src/lib/stitching/vortex/schema.ts, src/lib/stitching/vortex/stitching.ts
Metaphysics wrapper to expose new Vortex user stats graphQL endpoint to client
Vortex API work here: https://github.com/artsy/vortex/pull/260
The only client currently accessing the endpoint will be Volt (sketch PR here: https://github.com/artsy/volt/pull/4529)
Allow authenticated partners and admins to query against a user's total purchase counts
---
Unauthenticated users/non-partner users will not be authorized to hit this endpoint
=> Allow querying for user stats information in vortex

src/schema/v2/me/conversation/index.ts
This is a first step to fix https://artsyproduct.atlassian.net/browse/MX-499 and https://artsyproduct.atlassian.net/browse/PURCHASE-2074. It at least ensures metaphysics doesn't throw an exception if the `intial_message` is `undefined`.
=> If initial message undefined, don't blow up

_schemaV2.graphql, src/schema/v2/__tests__/salesConnection.test.ts, src/schema/v2/sales.ts
partially addresses https://artsyproduct.atlassian.net/browse/AUCT-1151
blocked by https://github.com/artsy/gravity/pull/13354
This simply exposes the new `registered` argument [being added to Gravity](https://github.com/artsy/gravity/pull/13354). I also added a new test file `src/schema/v2/__tests__/salesConnection.test.ts` since there didn't seem to be a test for `salesConnection`.
=> Add registered argument to salesConnection

src/schema/v2/home/__tests__/home_page_artwork_module.test.js, src/schema/v2/home/title.ts
The type of this PR is: **Enhancement**
This PR resolves **[MX-483]**
Most of our section titles are currently using title case, but Brand has suggested we move to sentence case as its more approachable/welcoming! 
The following PR makes adjustments to our home subtitles
Slack thread for reference: https://artsy.slack.com/archives/CV68RJVV3/p1594923419020700
[MX-483]: https://artsyproduct.atlassian.net/browse/MX-483
=> [MX-483] Updated home subtitles to sentence case

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
https://artsyproduct.atlassian.net/browse/FX-2123
When an artist series has no for-sale works we don't want to simply show "0 available"
- Use the count of all works (not just for-sale ones) as a fallback
- Return a consistently formatted string ("42 available" when there are for-sale works vs "42 works" when there are no for-sale works)
Originally I had this logic living in Force and Eigen, but for the sake of consistency and reusability it seemed sensible to have this in MP, since it is a common formatting concern across clients and surfaces. 
So this will be followed up by PRs to Force and Eigen to simply use the new `artworksCountMessage` field.
=> [FX-2123] Add a formatted artwork count to ArtistSeries

src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/salesConnection.test.ts, src/schema/v2/sales.ts
I added a new `registered` argument to filter sales by registration, which requires authentication: https://github.com/artsy/metaphysics/pull/2584
Apparently, the authenticated loader also need to exist in `src/lib/loaders/loaders_with_authentication/gravity.ts` otherwise the loaders with authentication headers will never delegate the `X-ACCESS-TOKEN` header value. To fix this issue, I just simply added the same loader to `src/lib/loaders/loaders_with_authentication/gravity.ts`. While this seems to be working fine, I wasn't 100% sure that two different loaders with the same name could co-exist. There does seem to be other examples such as `filterArtworksLoader`, `partnerArtworksLoader`, and `popularArtistsLoader`, but please let me know if this could cause a problem.
=> Add an authenticated sales loader

src/schema/v2/__tests__/salesConnection.test.ts, src/schema/v2/sales.ts
addresses https://github.com/artsy/metaphysics/pull/2616#discussion_r470315496
@mzikherman has pointed out that we aren't using the `loaderWithoutCache` properly when the `registered` argument is `false`. I wasn't sure how I should check it in JS as it could be `undefined` or `null` when it's not specified, so I ended up checking the type of the value and pick up the `loaderWithoutCache` if it's a boolean value. I'm still not 100% confidenent, but at least the test should demonstrate that the authenticated loader is properly picked up.
Let me know if there is anything to think about in this PR.
=> Make sure salesConection resolver uses a loader without cache if registered is false

_schemaV2.graphql, src/schema/v2/fair.ts
This PR adds the remaining fields we need to populate the "More info" page on the new fair landing.
It also makes a few of the fields `markdown`-style, which means they can be formatted into `HTML`. By default (if you don't pass a `format: HTML` argument) it returns the same value that's been inputted so it should be backwards-compatible.
I didn't add tests since we're just passing through fields from gravity so I didn't think they added much, but happy to!
=> Adds remaining fair-related fields

_schema.graphql, _schemaV2.graphql, src/lib/stitching/gravity/stitching.ts
Follow up to https://github.com/artsy/metaphysics/pull/2621
Adds optional parameters to enable querying `viewingRoomsConnection` by `published` and `partnerID`.
=> Add published and partnerID params to viewingRoomsConnection field

src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
https://artsyproduct.atlassian.net/browse/FX-2157
On the artwork page, currently a user can see the same artwork in the “more works from this series” rail. This creates a less-polished browsing experience.
Exclude the current artwork (when it exists) from the `artworksConnection` query on `ArtistSeries`.
QA Note: We'll want to check the UIs in Force and iOS to make sure that any relevant artwork counts we display are correct.
**Before**
**After**
=> Exclude current from artworksConnection on ArtistSeries

_schemaV2.graphql, src/schema/v2/filterArtworksConnection.ts
In order for an artwork rail ('More works from this series') to exclude the current artwork (in a first-class way), we'll want to pass that in. Gravity already supports the `exclude_artwork_ids` param.
=> @sweir27 -> [FilterArtworks] Add excludeArtworkIDs as an argument

src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/stitching.ts
When we switch the artwork rail to use `filterArtworksConnection` (instead of `artworksConnection`), we'll want to exclude the current artwork (which is set if the context the field is being used in started with an artwork).
=> @dzucconi => [ArtistSeries] Exclude current artwork from filterArtworksConnection

_schemaV2.graphql, src/schema/v2/__tests__/show.test.js, src/schema/v2/show.ts
This PR exposes the `created_at` field on a show in the v2 schema because Force is currently querying for it in the v1 schema (to pass on to Sailthru).
This work will unblock work to deprecate the use of v1 endpoints in Force.
=> Expose the date that a show was created in the v2 schema

_schemaV2.graphql, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollection.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
In what appears to be an endless journey to get a list to update after a mutation via the [declarative mutation update API](https://relay.dev/docs/en/v2.0.0/mutations.html#range_add), this adds a new artwork edge return object to our mutation response. Applies to both Create / Update: 
```graphql
mutation CreateArtwork($input: MyCollectionCreateArtworkInput!) {
myCollectionCreateArtwork(input: $input) {
artworkEdge {
node {
medium
}
}
}
}
```
=> [MyCollection] Add edge to create artwork mutation response

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionDeleteArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollection.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionDeleteArtworkMutation.ts, src/schema/v2/schema.ts
Digging through other mutations for example code I noticed that we were using an interesting `thingOrDelete` pattern which seemed more robust than the more vanilla mutations we were currently using in My Collection. This refactors things per [Alloy's blog post](https://artsy.github.io/blog/2018/10/19/where-art-thou-my-error/). 
Additionally, this DRYs things up and adds a delete mutation. 
```graphql
mutation CreateArtwork($input: MyCollectionCreateArtworkInput!) {
myCollectionCreateArtwork(input: $input) {
artworkEdge {
node {
medium
id
internalID
dimensions {
cm
in
}
}
}
}
... on MyCollectionArtworkMutationFailure {
error
}
}
}
}
}
```
```graphql
mutation DeleteArtwork($input: MyCollectionDeleteArtworkInput!) { …
```
=> [MyCollection] Refactor mutations

_schemaV2.graphql, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
This updates our MyCollection artwork mutations to match actual artwork expectations:
- `year` -> `date`
- `dimensions` -> `width`, `height`, `depth`
(Gonna self-merge as this is pretty trivial)
=> [MyCollection] Revise mutations

_schemaV2.graphql, src/schema/v2/me/myCollection.ts
Follow-up PR to https://github.com/artsy/gravity/pull/13439 which trims our sort options down to those attached to the `CollectionArtwork` vs `Artwork`:
- `position`
- `created_at`
=> [MyCollection] Trim sort options 

.env.test, _schema.graphql, _schemaV2.graphql, src/data/diffusion.graphql, src/lib/stitching/diffusion/link.ts, src/lib/stitching/diffusion/schema.ts, src/lib/stitching/diffusion/stitching.ts, src/lib/stitching/mergeSchemas.ts
This PR stitches in the diffusion GQL schema. It is about as basic as possible - it does not do anything to forward the auth, for example. Which means that the query actually fails because diffusion is setup with authentication but that's not this PR's problem!
I will follow up on this topic if a future PR - either relaxing diffusion's checks or improving this stitching code to properly pass auth creds over to diffusion.
https://artsyproduct.atlassian.net/browse/CSGN-327
/cc @artsy/csgn-devs
=> CSGN-327: Stitch in diffusion schema

scripts/push-schema-changes.js
Like Volt, Pulse uses `artemis` to store and use a copy of Metaphysics' schema. Unlike Volt, it doesn't use `prettier`, so I had to make that step optional.
=> Update Pulse's schema automatically too

src/lib/sponsoredContent/data.json
Addresses the request outlined in [this ticket](https://artsyproduct.atlassian.net/browse/FX-2272).
=> FX-2272: Adds sponsored content for Gallery Weekend Berlin

src/lib/apis/diffusion.ts
I believe this is all that's required to send a user's token to diffusion so that it can verify that the user is signed in and has access to the data being requested. This won't do much until this one lands: https://github.com/artsy/diffusion/pull/319.
/cc @artsy/csgn-devs
=> Pass user token to diffusion when available

src/lib/sponsoredContent/data.json
Had an ask to remove the `Munich/Berlin` line from the beginning of this text. 😅
=> Update sponsored content for Gallery Weekend Berlin (again!)

_schemaV2.graphql, src/schema/v2/__tests__/sale_artworks.test.js, src/schema/v2/sale_artworks.ts
Enable `includeArtworksByFollowedArtists` flag on SaleArtworksConnection
By default, I am setting the flag to `true` to keep the existing behavior on Force
=> Enable includeArtworksByFollowedArtists flag on SaleArtworksConnection

.env.example, src/index.ts
The introspection authorization is already conditional on the presence of `INTROSPECT_TOKEN`, so it doesn't need to be conditional on `PRODUCTION_ENV`. This makes it more straightforward to test and simulate locally, and removes unnecessary env-specific logic.
=> Simplify introspection enforcement

src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/display.ts
Bug discovery and discussion [here 🔒 ](https://artsy.slack.com/archives/CP9P4KR35/p1599767367137800).
cc @joeyAghion @starsirius 
This PR fixes 2 issues I discovered in how we calculate our `displayTimelyAt` property on the `Sale` type. It was happening in places we do not convert a JSON string timestamp into a `Moment` before doing a time comparison. In the process of fixing the first bug I noticed we using values that were already moments instead of normal strings, so I converted them all and discovered the second issue.
=> fix bug in Sale.displayTimelyAt

.env.example
Updates `.env.example` with `DIFFUSION_APP_ID`. Noticed this was missing.
=> Update .env.example with DIFFUSION_APP_ID

_schemaV2.graphql, src/schema/v2/artwork/index.ts, src/schema/v2/me/myCollection.ts
Related https://github.com/artsy/gravity/pull/13468
Adds `metric`, `height`, `width` and `depth` fields to the Artwork type.
=> [Artwork] Add metric field to artwork, as well as individual dimensions

src/schema/v2/home/__tests__/__snapshots__/home_page_fairs_module.test.js.snap, src/schema/v2/home/__tests__/home_page_fairs_module.test.js, src/schema/v2/home/home_page_fairs_module.ts
We were previously only showing fairs on the home page when they had a `mobile_image` set, but this is causing issues (see: [Slack thread](https://artsy.slack.com/archives/CN8S32FJR/p1600876254022800) and a [recent waves change](https://github.com/artsy/waves/pull/275)).
Since we launched a new home feed early this spring, the app doesn't actually use this `mobile_image`. Making this change will affect older versions of the app, which will now show a grey circle on the old home screen (not a huge UX problem but wanted to bring it up).
Tested this locally:
=> Shows all fairs on home, regardles of mobile image

_schemaV2.graphql, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Adds the parameters `editionSize` and `editionNumber` to myCollection's create and update mutations.
https://artsyproduct.atlassian.net/browse/CSGN-379
=> [My Collection]: Add edition number + size to my collection mutation params

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/home/__tests__/home_page_fairs_module.test.js
Adds `editionSize` and `editionNumber` fields  to `Artwork` query object.
=> [My Collection] Expose edition size + set in Artwork query

_schemaV2.graphql, src/schema/v2/artwork/index.ts, src/schema/v2/home/__tests__/home_page_fairs_module.test.js
Follow up to #2721. `editionNumber` should be a string, rather than an integer.
=> Change Artwork editionNumber field to String

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/inquiry_question.ts
This is a pretty critical piece of pre-work to quickly unblock UI work for the first inquiry project so that we can begin parallelizing asap.
This adds a `inquiryQuestions` field to the `Artwork` type. This field will be used to power a modal after the user taps contact gallery that will send structured questions to gravity (and ultimately to our partners) so that they can provide more consistent, faster responses (all while reducing the overhead for collectors in deciding how to ask about basic questions). 
We'll follow up on hooking this up to gravity soon.
=> Add a placeholder response for inquiry questions to unblock ui work

src/schema/v2/me/myCollectionCreateArtworkMutation.ts
This PR moves the mutation for creating an artwork in a user's My Collection to using `artists` as the attribute name. This is safer because there is code in the API to "upgrade" this param to full BSON objects rather than the strings we'll get by default. You can see this here:
https://github.com/artsy/gravity/blob/ff280189e8f54dd6e5cf70ec17093b320123d7ec/app/api/util/find_by_slug_helpers.rb#L102-L110
So what was happening prior to this change is that we'd set the `artist_ids` field on the artwork model to strings rather than BSON keys:
```
gravity:staging> user.my_collection.artworks.first.artist_ids
=> ["52500dc7139b214dc40004c0"]
```
And then everything would be fine until our data pals did an update to the data pipeline and the type mis-match would show up. More chatter here: …
=> Use safer param for artist ids

_schemaV2.graphql, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts
Follow up to #2721. `editionNumber` should be a string, rather than an integer.
=> Additional type change on Artwork editionNumber field

src/lib/stitching/kaws/__tests__/stitching.test.ts, src/lib/stitching/kaws/stitching.ts
When there are no slugs set, this winds up performing an empty `where({})` query in KAWS, and thus returning actual collections. Just short-circuit here.
=> @anandaroop => [Fair] Return an empty list if there are no kawsCollectionSlugs set

src/schema/v2/fair.ts
Kind of a weird one. Basically this param lets you filter out booths which don't have any published artworks (https://github.com/artsy/gravity/blob/102d637a44124e0901eae52f47d983ad3de6ee28/app/api/v1/fairs_shows_endpoint.rb#L39). This feels like a sensible default here.
Fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=FX&modal=detail&selectedIssue=FX-2312
=> @dzucconi => [Fair] Only request fair booths with artworks

_schemaV2.graphql, src/lib/shared_resolvers/followedArtistsResolver.ts, src/schema/v2/aggregations/filter_artworks_aggregation.ts, src/schema/v2/me/__tests__/followed_artists.test.js, src/schema/v2/me/followed_artists.ts
- MP part of https://github.com/artsy/gravity/pull/13531 (exposing artist as a type of aggregation to request)
- also adds a `fairID` param when fetching follows, so one can fetch all followed artists at the fair directly
=> @anandaroop => Allow artist aggregation, and fair filtering in followed artists

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts
This PR uses an update I made over on Gravity here:
https://github.com/artsy/gravity/pull/13512
That PR allows one to pass `source_bucket` and `source_key` when creating an `AdditionalArtwork` record. Those arguments will then be passed to Gemini which will fetch and process the corresponding images.
https://artsyproduct.atlassian.net/browse/CSGN-356
/cc @artsy/csgn-devs
=> CSGN-356: Support creating images for My Collection artworks

src/schema/v1/__tests__/partner_show_events.test.ts, src/schema/v1/partner_show_event.ts, src/schema/v2/__tests__/show_events.test.ts, src/schema/v2/show_event.ts
Back in the Before Times...
- we found a nasty date-related City Guide [bug](https://artsyproduct.atlassian.net/browse/LD-561)
- we wrote an expedient UA-sniffing [hack](https://github.com/artsy/metaphysics/pull/1642) to address it
- we added a time-bomb [spec](https://github.com/artsy/metaphysics/blob/5e3587518ea274ef6eed5e046d2eeb0f8d480f31/src/schema/v2/__tests__/show_events.test.ts#L6-L18) to remind us to undo the hack
Now in 2020 AD:
- the bomb [went off](https://artsy.slack.com/archives/C02BC3HEJ/p1601567857100300) 
- our prediction about the fix being obsoleted [panned out](https://artsy.slack.com/archives/CN8S32FJR/p1601657401152400)
And I'll be damned if I'm not going to remove that hack just like we said we would 👼
=> chore: remove Eigen date hack now that it is unnecessary

src/lib/sponsoredContent/data.json
Include activation text and press release URL for Frieze London sponsorship content.
=> chore(FX-2340): Add sponsored content for Frieze London

_schema.graphql, _schemaV2.graphql, src/data/exchange.graphql, src/lib/stitching/exchange/stitching.ts
Change `myOrder` `state` param to `states`
This query is only being used on production behind a flag so safe to synchronously update it.
=> Update exchange schema

src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
This PR follows on #2742 and adds support for adding additional images when editing a My Collection artwork.
After some chatter here:
https://artsy.slack.com/archives/C01B2P6LJUU/p1602188267269900
I set out to add the `externalImageUrls` prop to the `myCollectionUpdateArtworkMutation` and did extract a func to compute the image sources so that the business logic around matching and parsing these URLs could be encapsulated. Then I updated both mutations to use the func.
Then I updated the tests like so:
* leave some of the tests right where they were for the create mutation - these serve as integration tests
* extract some of the existing tests to focus on the newly extracted helper func
* copy/paste those integration tests into the update mutation test file - more integration coverage
So …
=> Add more images to my collection artworks

_schemaV2.graphql, src/schema/v2/SearchableItem/SearchableItemPresenter.ts, src/schema/v2/search/SearchEntity.ts
This PR adds VRs to the list of entities that can be returned from search. After this PR is merged, next steps:
Tested it out locally with Insomnia and successfully returned a VR :tada: this image shows `AUTOSUGGEST` mode, which is what we use when a user starts typing and we want to show suggestions, but we also now return VRs in `SITE` mode, which is when they hit enter and run a search:
Draws from https://github.com/artsy/metaphysics/pull/2574!
Jira ticket: https://artsyproduct.atlassian.net/browse/GALL-3351
=> feat: allow viewing rooms to be returned from search [GALL-3351]

src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v1/me/__tests__/save_artwork.test.js, src/schema/v1/me/save_artwork_mutation.ts, src/schema/v2/me/__tests__/myCollectionDeleteArtworkMutation.test.ts, src/schema/v2/me/__tests__/save_artwork.test.js, src/schema/v2/me/myCollection.ts, src/schema/v2/me/myCollectionDeleteArtworkMutation.ts, src/schema/v2/me/saveArtworkMutation.ts
This PR updates the mutation that deletes a My Collection artwork to favor the existing REST endpoint rather than the ones I made for this use-case. It is based on this one: https://github.com/artsy/gravity/pull/13547.
To make this change I started by discovering that there was already a `deleteArtworkLoader` but it was for removing an artwork from one's saved artworks collection. So I renamed that and then renamed the My Collection-specific loader to the more general name.
The only other notable change here is that I'm sending these params: `{ permanent: true }` which just helps indicate that for this situation we're not looking for a soft-delete, but a full blown removal of the artwork record.
https://artsyproduct.atlassian.net/browse/CX-678
=> CX-678: Use existing delete artwork endpoint for my collection

_schemaV2.graphql, src/schema/v2/sale_artworks.ts
- add a usage comment on how to use aggregations at the `saleArtworksConnection` interface.
=> chore: add sale artworks connection aggregation comment

src/schema/v2/me/followed_fairs.ts, src/schema/v2/me/followed_galleries.ts
A couple of errors relating to queries for retrieving followed fairs and galleries. Not sure how no-one ever noticed this with the galleries query before, since it means that fairs will also be returned when requesting followed galleries.
=> fix: followed fairs galleries schema errors

_schemaV2.graphql, src/schema/v2/me/__tests__/bidders.test.js, src/schema/v2/me/bidders.ts
Not blocked by, but depends on https://github.com/artsy/gravity/pull/13571 to work.
Completes PURCHASE-2194
This PR adds an optional `active: Boolean` arg to the Me.bidders field, allowing a user to query her bidders limiting them to only active (published, unended) sales. Omitting it or setting `active: false` would match today's behavior and `active: true` opts into the filter.
=> Add `active` arg to Me.bidders

_schema.graphql, _schemaV2.graphql, src/data/vortex.graphql
Bump MP schema for new field in vortex. It looks like it's been awhile since vortex's schema has been updated, but all of the changes are additions of new fields, deprecation reasons, or comments.
Relevant code for lastUpdatedAt all the way at the bottom!
=> feat: add vortex schema and regenerate stitched schema

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
The type of this PR is: **Chore**
This PR resolves [CX-704]
- Check if an artwork (sale artwork) is inquirable before calling the gravity loader.
**PS: the artwork used in the picture below is from an auction**
[CX-704]: https://artsyproduct.atlassian.net/browse/CX-704
Issue: https://artsyproduct.atlassian.net/browse/CX-746
Co-authored-by: David Sheldrick <djsheldrick@gmail.com>
=> fix: disable inquiryQuestions for non inquirable artworks

src/schema/v2/me/conversation/submit_inquiry_request_mutation.ts
Tiny bug fix that we noticed when reviewing some of the functionality of the inquiry request mutation.
=> Ensure we don't try to parse details if they don't exist

src/schema/v2/__tests__/auction_results.test.js, src/schema/v2/auction_result.ts
(CX-761) https://artsyproduct.atlassian.net/browse/CX-761
With changes to the diffusion collectoriq import, lots can now have a null `realized_price`. This was resulting in force displaying `$NaN` for some newly imported lots. 
This PR adds a guard to the function that resolves the `display` property of the `realizedPrice`. MP will return `null` instead of `$NaN` when there is no realized price. On force's end, a null `priceRealized.display` will be treated as if the realized price was 0.
Note that I've verified that force has the appropriate check to handle null values from here properly. [It determines which property to use here](https://github.com/artsy/force/blob/9ae2d6722d189d1313ae2f423e43cbbecd392601/src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx#L297), and …
=> fix: protect against lots that don't have a realized price

_schemaV2.graphql, src/schema/v2/sale/index.ts
Because it will alway be null. The current implementation returns an array, not an object.
related Slack discussion: 
https://artsy.slack.com/archives/CP9P4KR35/p1604430180080000
Without this change, the relay-generated queries in Eigen will fail with 
> Cannot return null for non-nullable field BuyersPremium.id
=> remove SlugAndInternalIDFields from sale.buyersPremium

src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/myCollection.test.ts, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollection.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Ok I think this is the last one! I've been on a quest to retire all the My Collection-specific endpoints in favor of leveraging existing Gravity endpoints and unless I'm missing something I believe this wraps it. What this PR does is clean up the artwork image loader, switch calls to use the existing artwork loader and then updates the loader for drawing the list of artworks to use the existing collection artworks loader. It's a lot but I broke it into a commit for each thing.
To ensure this doesn't break anything, I booted MP locally with these changes and then pointed my simulator at it. I verified the My Collection interactions and saw that things were working.
https://artsyproduct.atlassian.net/browse/GRO-70
/cc @artsy/grow-devs @artsy/collector-experience
=> feat: Update remaining My Collection apis

_schemaV2.graphql, src/schema/v2/fair.ts
Allows this param to thread through to the Gravity endpoint (needed as part of https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=FX&modal=detail&selectedIssue=FX-2389)
=> feat: allow totalCount to be requested for fair booths connection

src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/index.ts
Metaphysics is returning this:
```json
{
"data": {
"sale": {
"isWithBuyersPremium": true,
"buyersPremium": [
{
"amount": "USD0",
"percent": 0.25
},
{
"amount": "USD250,000",
"percent": 0.2
},
{
"amount": "USD4,000,000",
"percent": 0.125
}
]
}
}
```
when it should be returning:
```json
{
"data": {
"sale": {
"isWithBuyersPremium": true,
"buyersPremium": [
{
"amount": "$0",
"percent": 0.25
},
{
"amount": "$250,000",
"percent": 0.2
},
{
"amount": "$4,000,000",
"percent": 0.125
}
]
}
}
=> fix: use symbol for sale.buyersPremium not currency

src/schema/v2/me/__tests__/myCollection.test.ts, src/schema/v2/me/myCollection.ts
I was looking into why myCollection calls were failing in Eigen and saw an error in gravity logs for an improper sort type that wasn't showing up in metaphysics. It looks like we were suppressing all errors because the myCollectionArtwork loader in some circumstances can return a 404 when a user does not have a collection. This PR instead checks for that particular error and throws for all other errors for hopefully a bit easier debugging.
=> fix: don't suppress all myCollectionArtwork errors

src/schema/v2/SearchableItem/SearchableItemPresenter.ts, src/schema/v2/SearchableItem/__tests__/SearchableItemPresenter.test.ts
Because of a missing space in the `case` statement, we weren't returning descriptions for viewing rooms in calls to Metaphysics. Fixes the issue and adds a test for it! 
More context here: https://github.com/artsy/gravity/pull/13596#issuecomment-724387229
=> fix: return descriptions for viewing rooms

src/schema/v2/me/__tests__/conversation/__snapshots__/conversation.test.js.snap, src/schema/v2/me/__tests__/conversation/conversation.test.js, src/schema/v2/me/conversation/index.ts, src/schema/v2/me/conversation/message.ts
[PURCHASE-2211]
Information about the collector meant for the gallery was appended to the `lastMessage` and was thus being displayed to the user in the inbox. This PR resolves `lastMessage` to `initial_message` (which has no collector info) if the last message is the only message. Paired with @zephraph 
Before:
After:
[PURCHASE-2211]: https://artsyproduct.atlassian.net/browse/PURCHASE-2211
=> chore: Remove collector info from lastMessage and clean up code

src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/artwork/index.ts, src/schema/v2/sale/__tests__/index.test.ts
[CX-822]
It seems like the gravity endpoint used by `savedArtworkLoader` had previously used the artwork slug for filtering and now seems to only work with the artwork's mongo ID.
✨ Bonus ✨ 
Fixed a flaky test that fails when your laptop is going slow because you're sharing your screen on zoom.
[CX-822]: https://artsyproduct.atlassian.net/browse/CX-822
=> fix: Artwork->isSaved resolver

_schemaV2.graphql, src/schema/v2/me/update_me_mutation.ts
Add `password` to allowed `input` fields for `updateMeMutation`.
Gravity will soon require a password for this mutation when changing user email addresses.
Follow up to #2845 and https://github.com/artsy/gravity/pull/13675
=> add password to updateMeMutation input

_schema.graphql, _schemaV2.graphql, src/data/causality.graphql, src/integration/__tests__/__fixtures__/knownV2Failures.json, src/lib/stitching/causality/__tests__/stitching.test.ts, src/lib/stitching/causality/__tests__/testingUtils.ts, src/lib/stitching/causality/stitching.ts, src/schema/v2/fields/money.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-2171
This stitches in `floorSellingPrice` and `onlineAskingPrice` fields in `AcutionsLotState` type, and uses the recommended Metaphysics `Money` type. The field names were removed in https://github.com/artsy/causality/pull/852 so we can reuse them here.
Migration steps:
=> feat: stitch in money-typed price fields in AuctionsLotState type (PURCHASE-2171)

src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/stitching.ts
This PR allows us to query the `listPrice` field on an artwork when that artwork is a line item on a `CommerceOrder` from the stitched Exchange schema like so:
```graphql
{
commerceOrder(id: "2e8c7a62-37fe-4702-9e58-2227dd45e295") {
lineItems {
edges {
node {
artwork {
listPrice {
... on PriceRange {
display
}
}
}
}
}
}
}
}
```
Before this change, the above query threw the following error because the `PriceRange` type was being transformed as part of the Exchange schema:
```
__typename did not match an object type: CommercePriceRange
```
**See also:** 
- #1878
=> fix: allow listPrice to be queried on CommerceOrder line items

_schema.graphql, _schemaV2.graphql, src/data/causality.graphql
This is a followup to https://github.com/artsy/causality/pull/861 (already in staging, not production) which fixed some `ID`-typed args that had been changed to `Strings`. I don't think we are currently using any of these argument-containing fields in metaphysics.
Please let me know if this isn't the right way to go about this schema upgrade 🤝
=> update causality schema

_schema.graphql, _schemaV2.graphql, src/schema/v1/artwork/index.ts, src/schema/v2/artwork/index.ts
It has come to light that our [always](https://artsy.slack.com/archives/C04KVDZU6/p1607107159063800?thread_ts=1607106319.063200&cid=C04KVDZU6), [always](https://artsy.slack.com/archives/C01B2P6LJUU/p1606928260015100?thread_ts=1606927746.014400&cid=C01B2P6LJUU), [always](https://artsy.slack.com/archives/C9SATFLUU/p1603390117262300?thread_ts=1603303917.232100&cid=C9SATFLUU), [always](https://github.com/artsy/reaction/pull/3121#issuecomment-581450001), [always](https://artsy.slack.com/archives/C9SATFLUU/p1560978400046700) [confusing](https://github.com/artsy/candela/pull/123) naming of `artwork.category` and `artwork.medium` has tripped up the team a couple of more times recently.
Adding some documentation at the point where devs are likely to encounter these fields seemed like a good …
=> docs: describe artwork's medium, category, and attribution_class fields

src/lib/stitching/causality/__tests__/stitching.test.ts, src/lib/stitching/causality/stitching.ts
__Before:__
__After:__
[PURCHASE-2295]: https://artsyproduct.atlassian.net/browse/PURCHASE-2295
=> My bids - remove cents from formatted currencies

_schema.graphql, _schemaV2.graphql, src/data/causality.graphql, src/lib/stitching/causality/__tests__/stitching.test.ts, src/lib/stitching/causality/stitching.ts
Part of [PURCHASE-2294]
#minor
This PR updates our stitched causality schema to include the `sellingPrice` field, which is the primary field we want for representing the selling price of an auction lot.
[PURCHASE-2294]: https://artsyproduct.atlassian.net/browse/PURCHASE-2294
=> add stitched sellingPrice field

src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts
We have discovered a race condition in the `POST /artwork/:id/image` gravity endpoint that is causing corrupt data. This PR adds a workaround while we track down the root cause in gravity, in order to unblock work in eigen.
=> fix(my collection) Create images synchronously to avoid gravity race condition

_schemaV2.graphql, src/schema/v2/__tests__/deleteArtworkImageMutation.test.ts, src/schema/v2/deleteArtworkImageMutation.ts
The deletion mutation added here works but looks like the return type of the loader is actually the deleted image rather than a success boolean. 
- Changes the success type check to look for an image_url property 
- Updates the tests and suppresses some errors output to console
- Removes an extra success return type
=> fix(my collection): return type check for successful artwork image delete

README.md
After pairing with @annacarey, I noticed that this is only documented on slack [here](https://artsy.slack.com/archives/C02BC3HEJ/p1599250831072100).
I added this in the readme here so it's fast to find when any artsy dev sets up a new app/machine.
=> update readme for introspection setup

_schemaV2.graphql, src/lib/mediumTypes.ts, src/schema/v2/__tests__/artworkMediumTypes.test.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/artwork/mediumType.ts, src/schema/v2/artworkMediumTypes.ts, src/schema/v2/schema.ts
- feat: add `artworkMediumTypes` root field
Add `artworkMediumTypes` root field to list known artwork medium types and corresponding documentation.
- feat: add `mediumType` field to Artwork type
Add `mediumType` field on Artwork type to expose medium type documentation.
- chore(artwork): Deprecate Artwork category field in favor of mediumType
In addition to `name`, we now support documentation copy within the `mediumType` field.
Jira 🔒 : https://artsyproduct.atlassian.net/browse/FX-2556
Rebase and merge please!
=> Add artwork medium type fields

src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
This implements the ability for create/update mutations on 'my collection' artworks to set/update edition information.
=> feat(my collection): create/update edition information

src/lib/stitching/causality/__tests__/stitching.test.ts, src/lib/stitching/causality/stitching.ts
The Causality LotStanding type needs to be stitched and assembled using data from Gravity. This PR fixes a bug where unpublished gravity data ruins a graphql query, when really it just means that the lot should be treated as nonexistent.
Causality's part is really just the calculated state portion of a gravity sale artwork, and the `saleArtwork` field is stitched into the underlying type in order to make a query like `auctionsLotStandingConnection.edges[0].node.saleArtwork.sale.name`. This works fine unless the sale artwork is unpublished; additionally the sale artwork is implicitly queried for currency-related fields in order to resolve the `display` values. If a sale artwork is unpublished, the entire query fails.
WIP solution: 
- get a list of lot standings (lotStandingConnection) as …
=> Fix failed lotStandingConnection queries when a sale artwork is unpublished

_schemaV2.graphql, src/lib/attributionClasses.ts, src/schema/v1/__tests__/artworkAttributionClasses.test.ts, src/schema/v1/artwork/__tests__/artwork.test.js, src/schema/v2/__tests__/artworkAttributionClasses.test.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/attributionClass.ts
- chore: Mark AttributionClass#info as deprecated
This attribute doesn't seem to be used in any of our clients and came up while we were updating copy for new classification options.
- chore: update copy for artwork classifications
Introduce minor copy updates for shortDescription.
@oxaudo I couldn't find any client using the `info` field. Think it's alright to deprecate until we're confident in removing it?
Note: Rebase and merge
=> Update copy for artwork classifications

_schemaV2.graphql, src/schema/v2/me/index.ts, src/schema/v2/me/update_me_mutation.ts
This builds on https://github.com/artsy/gravity/pull/13723 by adding the email frequency field to the me type for reading and writing. I can then use this over in force to get the value and set it when a user manages this setting.
/cc @zephraph @mdole
=> chore: Expose email frequency reads and writes

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
**New behavior:** We are hoping to support users creating artworks marked as editions without requiring them to provide **editionSize** or **editionNumber**
**Old behavior:** Editions were only created when a user passed either editionSize or editionNumber. There was a small bug here where if only editionSize was passed creation would fail validation because of explicit null being passed in the field. This instead doesn't provide the field when it isn't present.
To support the new behavior this PR:
- adds a new field to the `myCollectionCreateArtworkMutation` `isEdition` to explicitly ask for an edition to be created. 
- only passes provided fields to edition creation to prevent validation error from explicit null
- To stay backwards compatible this also keeps logic to create an edition …
=> feat(my collection): allow marking works as editions without requiring extra fields

_schemaV2.graphql, src/schema/v2/me/__tests__/sale_registrations.test.js, src/schema/v2/me/index.ts, src/schema/v2/me/sale_registrations.ts
Part 1 of 2 for resolving [PURCHASE-2185](https://artsyproduct.atlassian.net/browse/PURCHASE-2185).
Commenting `me.saleRegistrations` field back in to allow for move from `v1` to `v2` on `force`, and turning it into a connection.
Follow up on [this](https://github.com/artsy/force/pull/6810) PR.
=> chore: Bring back me.saleRegistrations as a connection

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
There is a request not to display the note that COA is not included when it's marked as false. I think this will solve that for all clients.
We are still waiting for confirmation from Product that there is no additional concerns with that removal hence the WIP message here.
=> feat(PX-3603): do not return certificate of authenticity data if certificate is false

_schema.graphql, _schemaV2.graphql, src/data/vortex.graphql, src/lib/stitching/mergeSchemas.ts, src/lib/stitching/vortex/stitching.ts, src/lib/stitching/vortex/stitchingv1.ts
Builds out the Metaphysics interface to allow for querying of the new Vortex partner analytics of a partner's most viewed viewing rooms.
Associated Vortex changes: https://github.com/artsy/vortex/pull/291 
Takes a partner id, period, and the new viewing room query enum (defined in vortex) and returns a list of Viewing Rooms with the number of user views it has received during the given time period. Also allows us to pull additional viewing room attributes from Gravity's GraphQL schema.
This data will drive Most Viewed VR in CMS partner analytics 
Paired with some cool friends on this - shoutout to Sarah, Matt, and Justin for the help here! 🎉
=> Allow for query of partner top viewed viewing room data

src/lib/stitching/causality/stitching.ts
Update to #2925 's stub data on Causality's 'watchedLotConnection' to also stub out `id`.
cc @artsy/purchase-devs
=> fix: Updates causality stub data to include id on watchedLotConnection

_schema.graphql, _schemaV2.graphql, src/data/diffusion.graphql
Partially addresses https://artsyproduct.atlassian.net/browse/CX-738.
Stitches in a new field named `medianSaleOverEstimatePercentage`, which we'll be using in Eigen for displaying market stats for an artist.
=> chore: update schema for diffusion medianSaleOverEstimatePercentage field

src/schema/v2/partner.ts
Co-authored-by: mdole <mdole7@gmail.com>
Fixes a bug where we are trying to grab the value of `args.for_sale`, the thing is this will always return `undefined`, and not allow us to properly filter by works that are `forSale=true/false`
Bug - artworks regardless of `isForSale` status are returned in the query response:
Fix - artworks where only `isForSale=true` are returned in the query response:
=> Fix casing to allow for filtering artworks by forSale argument

_schemaV2.graphql, src/schema/v2/__tests__/auction_result.test.ts, src/schema/v2/auction_result.ts
This PR resolves: https://artsyproduct.atlassian.net/browse/CX-955
- Add percentage performance over mid estimate to auction result
TODO:
=> feat: add percentage performance over mid estimate to auction result

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
Addresses: https://artsyproduct.atlassian.net/browse/GRO-164 
Updates our Artwork meta data to include more info for SEO purposes. 
cc @artsy/grow-devs
=> feat: [Artwork] Expand formattedMetadata output for SEO

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/edition_set.ts, src/schema/v2/sellable.ts, src/types/gravity/artworkResponse.d.ts, src/types/runtime/gravity/Artwork.ts, src/types/runtime/gravity/EditionSet.ts
This PR resolves [\[PURCHASE-2413\]](https://artsyproduct.atlassian.net/browse/PURCHASE-2413)
Adds `offerable_from_inquiry` flag for `EditionSet` and `Artwork` to be used with Inquiry Checkout. Relates to [this](https://github.com/artsy/gravity/pull/13786) gravity PR.
[PURCHASE-2413]: https://artsyproduct.atlassian.net/browse/PURCHASE-2413
=> feat: Adds offerable_from_inquiry flag for Inquiry Checkout

_schemaV2.graphql, src/schema/v2/__tests__/shows.test.js, src/schema/v2/shows.ts, src/schema/v2/sorts/show_sorts.ts
For now this just cleans up the top-level showsConnection and adds some of the supported options.
The query criteria for online exclusives according to Force is:
```
has_location: false,
displayable: true,
at_a_fair: false,
```
------
As an aside it does seem like we might want to actually model this or at least remove the `at_a_fair: false` constraint, considering that we have online exclusive fairs on the site.
=> feat(shows): expands args on top level shows connection

_schemaV2.graphql, src/schema/v2/partner.ts
Took me a moment to realize we supported this and how it worked... but there ya go.
=> feat(partner): exposes filter artworks connection; deprecates old connection

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
Added new copy about certificate of authentication to provide more detail around COA—whether the COA was issued by an authorized authenticating body and/or by the gallery. These correspond to new checkbox inputs in the artwork form in CMS that allows galleries to provide this further detail.
Case for w/ issued by gallery checked:
Case for w/ issued by authenticating body checked:
Case for w/ both checked:
[Jira ticket](https://artsyproduct.atlassian.net/browse/PX-3608)
=> feat: Display info from new COA checkboxes to user on artwork page

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/impulse.ts, src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/__tests__/testingUtils.ts, src/lib/stitching/exchange/v2/stitching.ts
completes [PURCHASE-2381]
This pr updates our exchange `commerceCreateInquiryOfferOrderWithArtwork` mutation resolver to make additional calls to impulse before and after the exchange call, failing if any request along the way fails. This could mean returning a `data...orderOrError.error` from exchange or no data but an `errors` key in the graphql response. 
<strike>It relies on `order.internalID` being selected in the query - we currently have some commented-out code where we tried and failed to use a `WrapQuery` transform to achieve this automatically but it didn't work so far. So for now just make sure you request the `order.internalID`.</strike> *We got this working with `WrapQuery` 🎉*
Consumers will have to handle a rejected request, a success with `errors`, and a success with …
=> When creating an inquiry-offer-order, associate the offer and order in the mutation

_schema.graphql, _schemaV2.graphql, src/data/exchange.graphql
Addresses: [PURCHASE-2418](https://artsyproduct.atlassian.net/browse/PURCHASE-2418)
⚠️ Blocked by https://github.com/artsy/exchange/pull/677 ⚠️ 
This updates the exchange schema to include `impulse_conversation_id` in the `OfferOrderType`.
cc @artsy/purchase-devs
=> Chore: update exchange schema

src/schema/v2/__tests__/auction_result.test.ts, src/schema/v2/__tests__/auction_results.test.js, src/schema/v2/auction_result.ts
Use **en-dash** (&ndash;) on auction results estimate range
=> fix: use en-dash for estimate

_schemaV2.graphql, src/schema/v2/partner.ts
Following up on https://github.com/artsy/gravity/pull/13790, this PR allows us to use the new `imageCountLessThan`, `publishedWithin` (seconds) and `artworkID`. We can thus execute a query like this:
```graphql
{ 
artworkMetadataChecklistItems: artworksConnection(first: 5 publishedWithin: 7776000 imageCountLessThan:2 artworkID:["5fadb09499a3f8000e1c8afe","5fcfef6acdefca0012db87b2"] exclude:"5fcfef6acdefca0012db87b2") {
edges {
node {
internalID
title
image {
href
}
artistNames
slug
}
}
}
}
}
```
...and get back artworks that meet all of the criteria in the params. Woohoo!
=> Feat: un-deprecate and add params to partner artworksConnection

_schemaV2.graphql, src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/v2/stitching.ts, src/schema/v2/schema.ts
This PR follows up on https://github.com/artsy/metaphysics/pull/2990 by stitching in `conversation` under a `CommerceOrder` and delegating it to a new root `conversation` field. The previous PR used `me.conversation` but we realized this field would not work for queries from volt which do not use `me`. Still WIP, but if we like this approach it should also hopefully be easier to test.
[PURCHASE-2375]
cc @artsy/purchase-devs 
[PURCHASE-2375]: https://artsyproduct.atlassian.net/browse/PURCHASE-2375
=> Add conversation to Order type (with new root conversation field)

src/lib/apis/fetch.ts, src/lib/loaders/__tests__/request_id.test.js, src/lib/loaders/__tests__/user_agent.test.js, src/lib/loaders/api/index.ts, src/lib/loaders/api/loader_interface.ts, src/lib/loaders/api/loader_with_authentication_factory.ts, src/lib/loaders/api/loader_without_authentication_factory.ts, src/lib/loaders/api/loader_without_cache_factory.ts
This re-reverts, but with a change (https://github.com/artsy/metaphysics/commit/d9536d23e47e8cb05ce540a1bea613cf75a53eab), that threads arguments through properly.
=> fix: dont use query params for PUT/POST requests

src/lib/apis/fetch.ts, src/lib/loaders/__tests__/request_id.test.js, src/lib/loaders/__tests__/user_agent.test.js, src/lib/loaders/api/index.ts, src/lib/loaders/api/loader_interface.ts, src/lib/loaders/api/loader_with_authentication_factory.ts, src/lib/loaders/api/loader_without_authentication_factory.ts, src/lib/loaders/api/loader_without_cache_factory.ts
Reverts artsy/metaphysics#3001
See if this solves the new Integrity failures discussed in https://artsy.slack.com/archives/C9YNS4X32/p1613569288257200.
=> Revert "fix: dont use query params for PUT/POST requests"

_schemaV2.graphql, src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/v2/stitching.ts, src/schema/v2/me/conversation/index.ts, src/schema/v2/schema.ts
This PR fixes:
This was causing issues with our resolvers, and unfortunately this new approach breaks testing. It also includes a fix for our root _do_not_use_conversation field which was incorrectly not accepting the proper arguments (obscured by a mocked conversationLoader in test).
Mobbed with @starsirius @sepans and @starsirius to get this working, and it is - but tests are not. We agreed to temporarily disable the tests and circle back soon.
**The breaking schema changes are not yet used so should not be a problem.**
=> Fix broken conversation query

src/schema/v2/__tests__/auction_result.test.ts, src/schema/v2/auction_result.ts
Resolves: https://artsyproduct.atlassian.net/browse/CX-1113
An error is currently being thrown when lots with unsupported currencies are returned from the `auctionResultsConnection`. Eigen is treating these errors as fatal right now and since adding the auctionResults to the artist page in Eigen this is causing the Artist page not to load for artists with the problematic lots. This instead returns null for the displayPrice and estimate of auction lots with unsupported currencies and does not throw an error.
- Eigen probably should not show the retry page in this case since the query is returning the rest of the data
- Find currencies that we are not currently supporting in our lot data and add them to metaphysics
- Add a test case for this
=> fix: return null for display and estimate for unsupported currencies

_schemaV2.graphql, src/schema/v2/me/update_me_mutation.ts
Note: this PR depends on this one: https://github.com/artsy/gravity/pull/13858 so I'm starting this as a draft.
The PR adds support to MP for setting a timestamp on a user for when they have completed onboarding. I'll follow up with a PR in force that sends this over.
https://artsyproduct.atlassian.net/browse/GRO-125
=> feat: Support setting timestamp on user for onboarding complete GRO-125

_schemaV2.graphql, src/schema/v2/partner.ts, src/schema/v2/show.ts
This PR enables us to fetch only shows that are part of fairs using the `atAFair` param, and it allows us to fetch counts of ALL artworks (published or unpublished) that are in a show. These attributes will be used for the CMS homepage checklist, allowing us to display shows that the partner needs to upload artworks to.
```graphql
{
partner(id: "xavier-hufkens") {
showsConnection(first: 5, atAFair: true) {
edges {
node {
artworksCount
name
isFairBooth
}
}
}
}
}
```
Jira ticket: https://artsyproduct.atlassian.net/browse/PX-3768
=> Feat(PX-3768): add atAFair param & artworksCount to show type

_schema.graphql, _schemaV2.graphql, src/data/exchange.graphql, src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/v2/stitching.ts, src/schema/v2/me/conversation/index.ts
This will be a first step in implementing [PURCHASE-2449] to interleave order updates with conversations - We add an `orderConnection` to conversation. See below for a possible query shape.
[PURCHASE-2449]: https://artsyproduct.atlassian.net/browse/PURCHASE-2449
cc @artsy/purchase-devs
=> feat: Add orderConnection to Conversation

_schema.graphql, _schemaV2.graphql, src/lib/stitching/causality/__tests__/stitching.test.ts, src/lib/stitching/causality/schema.ts, src/lib/stitching/causality/v2/stitching.ts, src/lib/stitching/logLinkMiddleware.ts, src/schema/v2/lot.ts, src/schema/v2/me/__tests__/watchedLotConnection.test.ts, src/schema/v2/me/index.ts, src/schema/v2/me/watchedLotConnection.ts
As I started working on moving the MyBids logic from Eigen to MP, I noticed some places where we might run into confusion/trouble later and wanted to open a PR up for discussion. 
This refactors a [previous PR](https://github.com/artsy/metaphysics/pull/2928) to simplify our Causality `Lot` stitching code by deferring to more conventional stitching patterns seen throughout MP, removing indirection, and deleting a good amount of code. 
All in all, no breaking changes have been made to the schema, and everything should be backwards compatible; however, as detailed below, we're now returning _all_ `watchedLotConnection` nodes, versus just some. I'll defer to @erikdstock as to whether follow-up work is necessary in Eigen and am happy to tackle that as well.  
```graphql
{
me { …
```
=> refactor: Simplify Causality Lot stitching 

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/partner.test.js, src/schema/v2/partner.ts
Have partner artworks connection accept new `shallow` argument to fetch additional artwork information.
If `shallow: false` make an additional request to the `partnerArtworksAllLoader` to fetch more data on the artwork (note the `isPriceHidden: false`)
If `shallow:true` or not present in the parameters, fall back on default `partnerArtworksLoader` behavior (note the `isPriceHidden: null`)
Also encaptulates @annacarey's new work to support a new MP filter: https://github.com/artsy/metaphysics/pull/3020
Mobbing with @sweir27 @annacarey  @mdole @oxaudo
=> [PX-3747] Add data loader for PartnerArtworksAll + add custom handling for additional artwork data

_schema.graphql, _schemaV2.graphql, src/lib/stitching/causality/schema.ts, src/lib/stitching/causality/v2/stitching.ts
I just realized we could make `auctionsLot` private, since we're simply pointing at causality now.
=> fix: [Causality Stitching] Make `lot` private

_schemaV2.graphql, src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/v2/stitching.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-2463
We want to hide the "Make Offer" button when there is an active/submitted order associated with a conversation. To support that, we want to filter the orders by state. This adds it as an argument in `orderConnection` and it's already [supported in Exchange](https://github.com/artsy/exchange/blob/1cd7df5d875e6a04b5a22a3c6585df71af25b304/app/graphql/types/query_type.rb#L18).
=> feat: support filtering conversation.orderConnection by order state (PURCHASE-2463)

_schema.graphql, _schemaV2.graphql, src/data/exchange.graphql
#Minor yet-unused update to a field name to reduce ambiguity.
=> chore: update exchange schema (again)

_schemaV2.graphql, src/schema/v2/aggregations/filter_artworks_aggregation.ts, src/schema/v2/filterArtworksConnection.ts
https://artsyproduct.atlassian.net/browse/FX-2665
https://artsyproduct.atlassian.net/browse/FX-2667
Wires up the new **materials terms** field for artwork filtering and aggregating.
```graphql
{
artworksConnection(
first: 5, 
materialsTerms: ["watercolor", "paper"], 
aggregations: [MATERIALS_TERMS]
) {
edges {
node {
slug
medium
}
}
aggregations {
slice
counts {
value  
count
}
}
}
}
```
```json
{
"data": {
"edges": [
{
"node": {
"slug": "alfred-figueras-sanmarti-circ",
"medium": "Watercolor on paper"
}
},
{
"node": {
"slug": "bernard-buffet-assiette-de-fruits-2",
"medium": "Watercolor and pastel on paper"
}
},
{
"node": {
"slug": "javier-perez-non-melancholic-scenes-dot-4",
"medium": "Watercolour on paper"
}
},
{
"node": {
"slug": …
```
=> feat(materials filter): add materialsTerms to artwork filtering and aggregation

_schemaV2.graphql, src/lib/__tests__/helpers.test.ts, src/lib/helpers.ts, src/lib/stitching/gravity/v2/stitching.ts, src/lib/stitching/kaws/v1/stitching.ts, src/lib/stitching/kaws/v2/stitching.ts, src/lib/stitching/lib/printType.ts, src/schema/v2/__tests__/filterArtworksConnection.test.ts, src/schema/v2/filterArtworksConnection.ts
This adds _yet another_ argument to our filter artworks type (but I swear, this one is for a good cause! In fact, it might be the _last_ argument we ever need...).
Basically, converts all the existing ones into a more proper `input` type. This allows the underlying arguments here to change w/o needing long lists to be maintained alongside the GraphQL query for each page that uses a filter (now, a single `input: $input` and `input: FilterArtworksInput` would be all that's needed).
Leaving this in draft as I have a corresponding Force branch in progress locally with this. Also specs.
=> feat: add a single `input` arg to filter artworks

package.json
Remembered [this blog post](https://artsy.github.io/blog/2018/08/24/How-to-debug-jest-tests). Didn't realize it wasn't in metaphysics:
```bash
yarn test:debug someTestFile --watch
```
=> toolchain: Add `yarn test:debug` for debugger

_schemaV2.graphql, src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/v2/stitching.ts
cc @artsy/purchase-devs - We went over this together this morning so this should be a relatively uncontroversial fix. To avoid a bad dev experience I will wait to remove `participantType` completely until lily & I's args have switched to use it.
=> fix: pass partner id, not user id, when querying by seller

_schemaV2.graphql
Looks like V2 schema became out-of-sync following #3054.
This is usually updated automatically in a pre-commit hook.
Ran the following command locally to sync things back up:
```
$ node_modules/.bin/nf run --env .env.shared,.env yarn dump:local
```
cc/ @sweir27
=> chore: update v2 schema

src/lib/helpers.ts
I noticed we had hundreds of warnings spitting out in MP's tests around a moment method deprecation. This update silences all those warnings. 
Here's a build w/ the example of the warning output: https://app.circleci.com/pipelines/github/artsy/metaphysics/7437/workflows/5e5ea152-53bc-4f27-bd3d-7313bb9fcfbc/jobs/14460
=> Remove moment warnings about deprecated method

src/schema/v2/__tests__/partner.test.js, src/schema/v2/partner.ts
Implemented `totalCount` for `artworksConnection` and `showsConnection` on the partner by calculating the count from the `total-count` header and adding to the result returned from MP. For the case with `artworksConnection`, I calculated `totalCount` twice for each case (when authenticated and `shallow=false` and for our default case).
```gql
{
artworksConnection(first: 25) {
totalCount
}
showsConnection(first: 30) {
totalCount
}
}
}
```
=> fix: Fix total count partner endpoints

src/schema/v2/__tests__/partner.test.js, src/schema/v2/partner.ts, src/schema/v2/profile.ts
This PR adds `distinguishRepresentedArtists`, `displayArtistsSection` and `profileArtistsLayout` fields that controls rendering process.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3840
=> feat: add fields controlling artist list rendering

_schemaV2.graphql, src/schema/v2/me/__tests__/sale_registrations.test.js, src/schema/v2/me/sale_registrations.ts
This PR relates to [PURCHASE-2185].
It sidesteps an issue that was raised after merging [this](https://github.com/artsy/metaphysics/pull/2894) PR in which the batch loader was causing the result to have an unexpected shape. Once merged, the part pertaining to `force` can be brought back.
Note: The PR mentioned above was working locally, but not on Staging due to the `ENABLE_RESOLVER_BATCHING` environment variable not being set locally.
Done alongside @zephraph 
cc @artsy/purchase-devs 
[PURCHASE-2185]: https://artsyproduct.atlassian.net/browse/PURCHASE-2185
=> fix: Sidestep batch loader to fix SaleRegistrationConnection

_schemaV2.graphql, src/lib/stitching/exchange/v2/stitching.ts
This PR adds the [new order connection `states` filter](https://github.com/artsy/metaphysics/pull/3078/files) to Conversation#orderConnection.
cc @artsy/purchase-devs
=> chore: add states filter to Conversation#orderConnection

src/schema/v2/sales.ts
Slight issue when calling the API. The Enum wasn't matching the upstream case that was expected by gravity and the param needed to be passed as snake case to gravity instead of camel case.
=> Fix incorrect args sent to sales endpoint for auctions filtering

src/schema/v2/__tests__/partner.test.js, src/schema/v2/partner.ts
This PR adds the `totalCount` field to the artists connection.
=> Fix: add total count to partner artists connection.

_schemaV2.graphql, src/schema/v2/partner.ts
Remoes for `image_count_less_than` from the `partner` object in Metaphysics. The corresponding gravity work is [here](https://github.com/artsy/gravity/pull/13961). I also regenerated the schema so it would not include this attribute.
Let me know if I missed anything!
[Jira ticket](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3772)
=> chore(PX-3772): Remove image_count_less_than from MP

hokusai/production.yml
https://artsy.slack.com/archives/CA8SANW3W/p1618942835151400
during investigation of high load on metaphysics caused by bot traffic, we see that mp has been at max pod count (25) for most of the day even w/o that bot traffic happening, decided to raise max by 3.
=> feat: increase max pod count to 28.

_schemaV2.graphql, src/schema/v2/__tests__/partner_artist.test.js, src/schema/v2/partner.ts, src/schema/v2/partner_artist.ts
This PR fixes a couple of things related to partner artists:
1. Exposes a way to get a partner artist's displayable biography. We either show the partner-provided biography, or the artsy one based on the `use_default_biography` flag.
2. Adds the `artistIDs` and `displayOnPartnerProfile` parameters to the `artistsConnection` under a partner so that we're able to retrieve a single, displayable partner artist edge.
=> Fixes biography handling for partner artists + exposes additional API parameters

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-2573
This exposes `domesticShippingFee` and `internationalShippingFee` on `Artwork` type as `Money` type. CMS can use it to determine if the artwork of an inquiry order has sufficient metadata for partners to "counter" an offer that'd be transactable.
For artwork location, I think we can rely on the existing [`shippingOrigin`](https://github.com/artsy/gravity/blob/0a9e0da15053c7935d9f9051b9175ec34f34dbd6/app/models/domain/artwork.rb#L1223) field.
=> Add shipping fees to artwork type

src/lib/__tests__/helpers.test.ts, src/lib/helpers.ts, src/schema/v2/filterArtworksConnection.ts
Draft because this is sort of incorrect but I'm a little unsure about alternatives.
The problem here is that where ever we use `page=n` based pagination we're never getting a correct offset back from this function. We throw away most of the object and just use that `offset` for the `sliceStart` which is then always zero. The result is that `hasNextPage` is never `false` (unless `first` happens to be more than the total amount of items on the first page).
The alternative would be to manually investigate every place we're using this function (~80) and correctly calculate the offset in place.
I'm more or less fine with this — add a spec or two and this fixes the root issue. It's just ugly.
------
You can replicate this issue by querying pretty much anything that has pagination and switching …
=> fix(pagination): returns correct offset when using page based pagination

_schemaV2.graphql, src/schema/v2/__tests__/partner.test.js, src/schema/v2/partner.ts
This PR adds `allArtistsConnection` to the `partner` type. Since we load all artists for the artist list on the client-side we decided with @sweir27  to move the loading logic to the server-side.
=> feat: add all partner artists connection

src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
Open up PRs early and get feedback. I'll work on tests separately.
In https://github.com/artsy/gravity/pull/13995, we exposed a new `vat_requirement_complete` field on `Artwork` json response, and it relies on some fields on the `Partner` model such as `vat_status`. One issue we noticed was that the artwork json response is cached and is not updated when the partner gets updated.
We could invalidate artworks from the partners when, say, the `vat_status` on the partner was updated. But I wonder if it's better to not keep adding this caching complexity.
So this PR follows https://github.com/artsy/gravity/pull/14019 and updates `vatRequirementComplete` to fetch data individually closer to the source. UI can still use the same `vatRequirementComplete` flag and MP will do the heavy lifting.
=> wip: fetch partner to determine artwork vat completeness

_schemaV2.graphql, src/schema/v2/__tests__/partner.test.js, src/schema/v2/partner.ts
This PR adds profileBannerDisplay field to the partner. This field indicates what type of banner should be shown on the partner page.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4016
=> feat(PX-4016): add profileBannerDisplay field to the partner

hokusai/staging.yml
https://artsy.slack.com/archives/CA8SANW3W/p1620140319056400
So that the service does not go down when cluster-autoscaler evicts one pod (when removing a k8s node for cluster scale-down).
For most apps we are okay with min pod count of 1 and once in a while service down. But MP is important so let's up it.
=> feat: raise staging min pod count to 2.

_schemaV2.graphql, src/schema/v2/__tests__/partner.test.js, src/schema/v2/partner.ts
Renamed `isNonSubscriber` field to `fullProfileEligible` according to the comment: https://github.com/artsy/force/pull/7502#discussion_r629800741
=> fix(PX-4044): rename isNonSubscriber to fullProfileEligible

src/schema/v2/image/__tests__/cropped.test.ts, src/schema/v2/image/__tests__/resized.test.ts, src/schema/v2/image/cropped.ts, src/schema/v2/image/resized.ts
This change should brings the 2x image urls that are generated in
metaphysics in line with the recent changes to force.
=> feature: Set 2x Images to Use 50 Quality

src/schema/v2/image/__tests__/resized.test.ts, src/schema/v2/image/resized.ts
Going to add a spec here before merging.
I'm really weirded out this is the first time I'm running into this bug.
I noticed that passing both a width and a height was returning images resized favoring width:
Specifying both a width and a height should return an image resized proportionally within those max dimensions:
Now, for the most part we should be OK in terms of what this breaks. This is definitely the correct and desired behavior, and there's no real way to tell other than let issues shake out if they present themselves. I say we make the change and I can just run through staging and adjust any values that we run into.
=> fix(resized): correctly handles situations where we pass both a width and a height

_schemaV2.graphql, src/schema/v2/partners.ts
This PR adds new arguments to the `partnersConnection` to support filtering by nearby galleries. V2 schema didn't have any query that I can use to get nearby galleries so I extended partnersConnection and added the same arguments as for [galleries page](https://staging.artsy.net/galleries) ([query](https://github.com/artsy/force/blob/94df9ba495f88bed2b466d682b045c23907f0088/src/desktop/apps/galleries_institutions/queries/partners_filter_query.coffee#L15-L20))
JIRA - https://artsyproduct.atlassian.net/browse/PX-4027
=> feat(PX-4027): extend partner connection to support filtering by nearby galleries

src/lib/__tests__/graphqlErrorHandler.test.ts, src/lib/graphqlErrorHandler.ts
This is not a great or long-term fix. However, it does currently satisfy the issue of getting `@principalField` working (thru proper propagation of HTTP status codes) of stitched backends (collections, artist series, etc.). It also defensive in that it shouldn't cause a crash of its own (famous last words...), but exists as a fallback to parsing status codes from underlying errors.
Once this is merged and deployed, we can add @principalField to collection and artist series pages, and remove any custom (non-working?!) error page/status code handling.
When querying GravQL directly w/ an unknown artist series:
When querying KAWS directly w/ an unknown collection:
Everything looks good!
However, there is some code in `graphql-tools` that incorrectly parses those into a string: …
=> fix: get principalField working for stitched types

src/lib/sponsoredContent/data.json
Added the activationText but still wating on the pressReleaseURL.
=> chore: add sponsored content for Art Basel Hong Kong 2021

_schemaV2.graphql, src/schema/v2/artist/__tests__/index.test.js, src/schema/v2/artist/index.ts
Jira ticket: https://artsyproduct.atlassian.net/browse/CX-1464
This PR adds the auction results count to the artist interface. This will be useful for us to display the links to the auction results tab for the new price insights feature. @edez1t  The query that we will need to run will look similar to the one in the screenshot below:
=> feat(CX-1464): add auction results count to the artist interface

package.json, yarn.lock
Looks like TS 4.3.2 has some issues 😢 This pins things to 4.2.4, the last good known version. See [this thread](https://artsy.slack.com/archives/CP9P4KR35/p1622232236226000) for some context. 
Related force PR: https://github.com/artsy/force/pull/7658
=> fix: Pin TS version 4.2.4

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap, src/lib/stitching/gravity/v1/stitching.ts
Jira: [FX-2989]
- includes support for `savedSearch` query field
Additionally stitches in the new field under `me`:
```graphql
{
me {
savedSearch(criteria: { artistID: "andy-warhol", classification: "unique" }) {
internalID
}
}
}
```
[FX-2989]: https://artsyproduct.atlassian.net/browse/FX-2989
=> chore: stitch savedSearch query field from Gravity

_schema.graphql, src/lib/stitching/gravity/v1/stitching.ts, src/lib/stitching/gravity/v2/stitching.ts
- No V1 clients need access to the savedSearch query field so make it V2 only
=> chore: move savedSearch query field entirely to V2

src/schema/v2/artist/index.ts
This is an update in MP to allow us to access the partner href that is used to create slugs. 
We are seeing issues with certain slugs not being updated to accurately reflect Partner name changes. This is because we are creating our associated partner hrefs using partnerID `const partnerHref = `${sd.APP_URL}/${partnerID}``
This update will allow us to pull in the correct href value for slug creation.
=> GRO-350: Updated to allow the partner.href property to be used for Artist Bio links

src/index.ts
Adds the `Access-Control-Max-Age` header to allow caching CORS preflight
headers for 10 minutes.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age
=> feature CORS Preflight Caching

_schema.graphql, _schemaV2.graphql, src/data/convection.graphql
syncs convection schema stitching in order to support utm campaign params in consignment submissions in Eigen:
https://artsyproduct.atlassian.net/browse/CX-1431
companion PRs:
https://github.com/artsy/convection/pull/1087
https://github.com/artsy/convection/pull/1075
=> chore: sync convection schema changes

_schema.graphql, _schemaV2.graphql
Volt can't be deployed because its schema is incompatible with Metaphysics' production-deployed schema. This was initially confusing, because Metaphysics is fully released and Volt has been getting the usual schema updates. It turns out that https://github.com/artsy/metaphysics/pull/3238 didn't fully update the committed schema file. Running `yarn dump:local` again resulted in these changes, which should hopefully (once released) allow Volt to be released.
Co-authored by: @starsirius
=> Re-dump schema for Convection updates

_schemaV2.graphql, src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/v2/stitching.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
This PR adds formatted price to CommerceShippingQuote object and artaShippingEnabled field for the artwork.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4226
=> feat(PX-4226): shipping quotes

src/schema/v2/me/auction_results_by_followed_artists.ts
Addresses a bug discussed [here](https://artsy.slack.com/archives/C02BAQ5K7/p1624982653469000).
=> fix: check if artist exists in AuctionResultsByFollowedArtists resolver

src/schema/v2/me/__tests__/auction_results_by_followed_artists.test.ts, src/schema/v2/me/auction_results_by_followed_artists.ts
Addresses [CX-1676]
This PR filters out auction results without an artist id in the auctionResultsByFollowedArtists resolver.
[CX-1676]: https://artsyproduct.atlassian.net/browse/CX-1676
=> fix: filter out auction results without artist id

src/schema/v2/filter_partners.ts, src/schema/v2/partner_category.ts, src/schema/v2/schema.ts
Jira ticket: https://artsyproduct.atlassian.net/browse/PX-2975
When we created metaphysics v2, we intentionally commented out some fields at the root to avoid unnecessary fields.
It turns out, we do actually need a few of these for the /galleries and /institutions page on Artsy.net!
=> [PX-2975] Exposes schema necessary to support the galleries_institutions page on Artsy.net

_schemaV2.graphql, src/schema/v2/articles.ts
Very minor thing: simply adds a `featured` boolean option to the top-level `articles` field.
(Some unrelated schema changes showing up here.)
=> feat(articles): adds featured option

src/schema/v2/me/auction_results_by_followed_artists.ts
We are seeing expensive queries to diffusion coming through from the new "Auction Lots by Artists you Follow" rail for users with no followed artists. Since the intention of the rail is to show auction lots by the artists the user follows I believe it should be okay to return empty in this case and not call diffusion.
=> fix: auction results by followed artists, bail out early when user has no follows

src/schema/v2/home/__tests__/home_page_artwork_module.test.js, src/schema/v2/home/title.ts
The type of this PR is: **Update**
This PR resolves [CX-1602]
Artsy is moving away from Sentence Case across Titles and CTAs throughout the UI. I'm starting this change by updating all titles in the App Home Feed.
_Home screen_
[CX-1347]: https://artsyproduct.atlassian.net/browse/CX-1347
[CX-1602]: https://artsyproduct.atlassian.net/browse/CX-1602
=> Update home screen titles

_schemaV2.graphql, src/schema/v2/me/__tests__/conversation/conversation.test.js, src/schema/v2/me/conversation/index.ts
Addresses: [PURCHASE-2747](https://artsyproduct.atlassian.net/browse/PURCHASE-2747)
**Issue:**
When we fetch items _(a collection of artworks or partner shows a user has inquired on)_, we are fetching a [snapshot version](https://github.com/artsy/impulse/blob/master/app/services/item_service.rb#L17-L46) of these items from impulse. This is particularly beneficial in the event a partner deletes or un-publishes an artwork or show. The conversation still maintains relevant context. However, when we need actual (not a snapshot) and up-to-date information from the artwork object (as is the case for the `isOfferableFromInquiry` property), this presents a problem.
Previously we got around this by creating a [new query renderer](https://github.com/artsy/eigen/pull/4637) and just fetching the …
=> [PURCHASE-2747] - enable fetching a live artwork instead of the snapshot

src/schema/v2/me/myBids.ts
Addresses https://artsyproduct.atlassian.net/browse/GRO-455
This fixes an issue where we were seeing duplicate entries in /auctions MyBids components when a user has registered for a sale and watches a lot that's in that sale.
The issue was that we can query for artworks by slug _or_ internalID, and so the `uniq` check was failing to filter out one work that was returned as an internalID and slug.
=> bugfix: Fix duplicate items in MyBids component

_schemaV2.graphql, src/schema/v2/__tests__/fair.test.js, src/schema/v2/fair.ts
In #3256, we accidentally introduced a bug where we would only ever fetch the first page of results. We introduced a default `page 1` argument, then [in Gravity](https://github.com/artsy/gravity/pull/14273), we introduced behavior that prioritized `page` over `cursor`. End result: we always fetch page 1 and nothing beyond.
This PR removes the default value for page so that we can once again fetch more than 1 page of results.
=> fix: fetch more than the first page

Brewfile, README.md, package.json, scripts/setup.sh
Related https://github.com/artsy/force/pull/8031
This updates the setup script to match force, with notable changes being:
- check for `yarn` before trying to install 
- check for `memcached` before trying to install
- add `setup` to `package.json` 
- add `sync-env` to `package.json`
=> toolchain: Match setup script with force

scripts/setup.sh
Do not use brew to install yarn. There is no need as the preferred
method is to install it with `npm`, this also has the benefit of being
cross platform.
=> chore: Simplify Yarn Install

_schemaV2.graphql, src/lib/loaders/loaders_without_authentication/gravity.ts, src/schema/v2/__tests__/fair_organizer.test.ts, src/schema/v2/fair.ts, src/schema/v2/fair_organizer.ts, src/schema/v2/schema.ts
In our quest to update Force's fair organizer app, we realized that we don't have a good way of fetching a fair organizer from Metaphysics when it's not nested inside of something else.
In the "old" [implementation of the fair organizer app in Force](https://github.com/artsy/force/blob/bb0564b88c7aa06f407fd8e9a75577c3ad0f8f0f/src/desktop/apps/fair_organizer/index.coffee#L22), we hit Gravity's `/fair_organizer/:id` route, e.g. `/fair_organizer/the-armory-show`, which gives us back a very limited amount of information about the fair organizer - including the `profile_id`. We then use that ID as a param and pass it to Gravity's `/fairs` endpoint: `/fairs?fair_organizer_id=the-armory-show`. This gets us a paginated list of fairs associated with the fair organizer, which we can then display. …
=> feat: add root-level fairOrganizer field

index.js, package.json, tsconfig.json
Opening a different approach to #3313 for consideration.
- Specify `src/**/*` and `index.js` include pattern in tsconfig (default: `**/*`)
- Enable `resolveJsonModule` compiler option
- Remove rootDir, which we were not using correctly
- Remove early ./src require
Addresses the following compilation errors:
```
error TS6059: File '/Users/devon/code/artsy/metaphysics/wallaby.js' is not under 'rootDir' '/Users/devon/code/artsy/metaphysics/src'. 'rootDir' is expected to contain all source files.
The file is in the program because:
Matched by include pattern '**/*' in '/Users/devon/code/artsy/metaphysics/tsconfig.json'
```
```
src/schema/v2/fields/money.ts:14:27 - error TS2732: Cannot find module 'lib/currency_codes.json'. Consider using '--resolveJsonModule' to import module with '.json' …
```
=> chore: fix typescript compilation

_schemaV2.graphql, src/lib/stitching/gravity/v2/stitching.ts
savedSearchesConnection was unable to take args for connection and we needed to explicitly declare them on the gravity/v2/stiching.ts file like that:
` after: String
before: String
first: Int
last: Int`
=> fix: add savedSearchesConnection arguments first/last/before

_schemaV2.graphql, src/schema/v2/fair_organizer.ts
- The about property from Gravity is stored in markdown. This update allows the client to render the text in html, markdown, or plaintext.
cc/ @anastasiapyzhik 
**Request**
```graphql
{
fairOrganizer(id: "the-armory-show") {
about(format: HTML)
}
}
```
**Response**
```json
{
"data": {
"fairOrganizer": {
"about": "<p>The Armory Show is New York City’s premier art fair and a leading cultural destination for discovering and collecting the world’s most important 20th- and 21st-century art. The Armory Show features presentations by leading international galleries, innovative artist commissions, and dynamic public programs. Since its founding in 1994, The Armory Show has served as a nexus for the art world, inspiring dialogue, discovery, and patronage in the visual arts.</p>\n<p><strong>More …
```
=> feat: update fair organizer about field to take format argument

scripts/push-schema-changes.js
Co-authored with @gkartalis 
This PR fixes an issue related to the new changelog checking step that is included in Peril.
Context:  https://artsy.slack.com/archives/C02BAQ5K7/p1628091193081900
=> fix: failed changelog parser checking on Eigen

.github/dependabot.yml
This transitions security updates from dependabot (which is [pending retirement](https://github.blog/2021-04-29-goodbye-dependabot-preview-hello-dependabot/)) to Github-managed.
**Step 1** (already complete): Enable "Dependabot security updates" under the repo's [Security & analysis settings](https://github.com/artsy/pulse/settings/security_analysis).
**Step 2** (this PR): Commit a minimal `.github/dependabot.yml` specifying `open-pull-requests-limit: 0` (this is [a hack to enable only security updates](https://stackoverflow.com/a/68254421), which can't otherwise be configured), the same assignee as currently specified [in dependabot's UI](https://app.dependabot.com/accounts/artsy/projects/61325), and the associated team as reviewers. …
=> Transition from legacy dependabot to native github security updates (PLATFORM-3470)

.circleci/config.yml
After upgrading to the CircleCI Node 14 image the python dependency
names changed. This updates the depenedcies that hokusai depends on.
=> fix: Hokusai Deps

package.json, yarn.lock
Bumps the `@arsty/update-repo` library.
=> chore: Bump Update Repo

.circleci/config.yml
In the latest CircleCI Node image python is installed as python 3, this
sets an alias so that yarn post install hooks execute successfully.
=> fix: Fix Python Installation Path

src/schema/v2/home/__tests__/home_page_artwork_modules.test.js, src/schema/v2/home/home_page_artwork_modules.ts
Contributes towards [CX-1796] by adding an `include` variable to `artworkModules` to specify exactly which modules will be returned from the query. So far we can only exclude modules.
[CX-1796]: https://artsyproduct.atlassian.net/browse/CX-1796
=> feature: Add include variable to artworkModules field

_schemaV2.graphql, src/config.ts, src/schema/v2/system/algolia/index.ts
Clients need both an app ID and API key to initialize an API client.
=> feat: expose algolia app id under system>algolia query field

src/schema/v2/articlesConnection.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/fair_organizer.ts, src/schema/v2/partner.ts, src/schema/v2/partner_category.ts
This PR updates `shippingInfo` field to inform users that the shipping price is calculated at checkout if ARTA shipping enabled.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4446 
international_shipping = $200
international_shipping = free
no international_shipping
Let me know if you want to change the messages.
=> feat(PX-4128): arta shipping costs for the artwork

_schemaV2.graphql, src/schema/v2/__tests__/fair.test.js, src/schema/v2/fair.ts
We're working on a new fair tab that groups exhibitors alphanumerically. This allows the client to fetch partner data without needing to make separate GraphQL requests to:
- Fetch all of the groups including partner IDs
- For all groups, utilizing the IDs, fetch the full partner info
In support of [FX-3077]
cc/ @tr-ann 
[FX-3077]: https://artsyproduct.atlassian.net/browse/FX-3077
=> feat: expose partner field under FairExhibitor type

src/schema/v2/__tests__/partner_categories.test.ts, src/schema/v2/partner_category.ts
This PR fixes the bug reported in #product-find-explore, where all of the category-based carousels on the /galleries page were returning the same set of galleries.
I tracked this down to a bug in [this PR](https://github.com/artsy/metaphysics/pull/3259). When exposing the `partnerCategories` field in the v2 schema, I realized that we weren't properly converting camelCase to snake_case for all of the arguments under the sub-`partners` field. I saw an opportunity to simplify this resolver, but in doing so missed [a crucial piece of logic](https://github.com/artsy/metaphysics/pull/3259/files#diff-8e9b07cef48b76d0559107831dc93046d531c35b68dc8c9154052ab3d9b9e2a3L34)! (Where we explicitly pass the parent partner category as an argument).
This PR does the more verbose, but correct, thing and …
=> Fix partner category query by properly passing category ID to partners endpoint

_schema.graphql, _schemaV2.graphql, src/data/exchange.graphql
Exchange changes here: https://github.com/artsy/exchange/pull/831
Part of this ticket: https://artsyproduct.atlassian.net/browse/PX-4379
Allows clients to be able to query for attributes on a collector's selected shipping quote
=> [PX-4379] Surface selected shipping quote as part of order query

_schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/v2/stitching.ts
Jira Ticket: https://artsyproduct.atlassian.net/browse/PX-4286
This PR expands `ViewingRoom` with the `exhibitionPeriod` field
Related PR for Force: https://github.com/artsy/force/pull/8224
=> feat(PX-4286): Users can see viewing rooms on the gallery profile page

_schemaV2.graphql, src/schema/v2/__tests__/auction_results.test.js, src/schema/v2/auction_result.ts
Contributes towards [CX-1707]
Adds a `displayUSD` field to auction results `prizeRealized` (returns e.g. "$100.00").
[CX-1707]: https://artsyproduct.atlassian.net/browse/CX-1707
=> feature: Add displayUSD to auction results realized price

src/lib/stitching/gravity/__tests__/stitching.test.ts
Addresses a flaky test with this failure output:
```
Summary of all failing tests
FAIL  src/lib/stitching/gravity/__tests__/stitching.test.ts
● gravity/stitching › #exhibitionPeriod › resolves the exhibitionPeriod field on ViewingRoom
expect(received).toEqual(expected) // deep equality
Expected: "Sep 1 – Sep 30"
Received: "Sep 1 – 30"
493 |           endAt: momentAdd(30, "days"),
494 |         })
> 495 |       ).toEqual(`${startAt} – ${endAt}`)
|         ^
496 |     })
497 |
498 |     it("returns Invalid dates if dates are missing", async () => {
at Object.<anonymous> (src/lib/stitching/gravity/__tests__/stitching.test.ts:495:9)
```
=> test: use consistent inputs to address spec flakiness

_schemaV2.graphql, src/schema/v2/__tests__/fair_organizer.test.ts, src/schema/v2/fair_organizer.ts
Includes `hasFullFeature`, `hasHomepageSection`, `hasListing`, `sort`, and `status`.
The default fair sort in Gravity is `-created_at`. When looking for an upcoming fair for an organizer, we currently fetch the first fair and check if the start time is in the future. If a past fair is created after a future fair, we might be checking the wrong entity in the system.
For example:
```
Fair A: created_at=2021-06-30 start_at=2021-08-01 end_at=2021-08-15
Fair B: created_at=2021-06-29 start_at=2021-10-01 end_at=2021-10-31
```
On 2021-09-15, we want to show fair B on the organizer page because it's upcoming but we only check fair A because it was created more recently and returned first due to the default sort.
This gives the client more control over sorting and filtering so that we get the right …
=> feat: add fair sort/filter args to fairOrganizer>fairsConnection

.dockerignore, Dockerfile
The hokusai post-deploy script was being excluded from the docker image, this brings it back.
=> fix: Missing Post-Deploy Script

_schemaV2.graphql, src/schema/v2/External/External.ts
Minor thing to clean up the types. Longing for the day when we could do this for other parts of the schema.
=> chore(schema): makes external non-nullable

_schemaV2.graphql, src/schema/v2/artwork/index.ts
Part of https://artsyproduct.atlassian.net/browse/PX-4369
Add the possibility to query for artwork location, using the REST endpoint in gravity.
=> feat(PX-4369): add location to artwork schema

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/artwork/utilities.ts
User can still see view 2D works on wall that now have Depth
While looking into this story, I realized we were already enabling VIR for works with a depth of >1. Based on [this discussion](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=41&projectKey=PURCHASE&modal=detail&selectedIssue=PURCHASE-2719&quickFilter=61) with stakeholders, I refined the logic to make `isHangable` always true and thus enable VIR for all works in certain categories (like "painting"), always false for all works in other categories (like "sound"), and for all other works, it is true if the depth of the work is less than 3.
=> chore: refining isHangable logic to enable View in Room for more works with depth

_schemaV2.graphql, src/lib/__tests__/moneyHelpers.test.ts, src/lib/moneyHelpers.ts, src/schema/v2/__tests__/auction_results.test.js, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
solves [https://artsyproduct.atlassian.net/browse/PURCHASE-2824]
might solve [https://artsyproduct.atlassian.net/browse/PURCHASE-2404]
Change saleMessage field to display price formatted at metaphysics instead of gravity 
Results: (as is => to be)
AUD $420 => A$420
HKD $420 => HK$420
$420 => US$420
AUD $400-420 => AU$400-AU$420
It affected only saleMessage field, but in other places similar approach could be taken. 
It could affect some tests in other projects as well as integrity tests.
=> Change saleMessage price formatting

src/lib/currency_codes.json
solves [PURCHASE-2928] 
Change swiss frank formatting from **CHF CHF1,000** to **CHF1,000** by setting **CHF** as disambiguate symbol
[PURCHASE-2928]: https://artsyproduct.atlassian.net/browse/PURCHASE-2928
=> fix(PURCHASE-2928): Add disambiguate symbol to swiss frank

src/schema/v2/fair_organizer.ts
[FX-3277]
In the current implementation when requesting fairsConnection of fairOrganizer we send to gravity fairOrganizer's profile id instead of it's own id and thus getting an error in cases those values are not equal 
**Before**
**After**
[FX-3277]: https://artsyproduct.atlassian.net/browse/FX-3277
=> FX-3277 Send fair organizer id to gravity instead of it's pofile id

src/schema/v2/__tests__/fair.test.js, src/schema/v2/fair.ts
solves [FX-3294] 
- Special characters will go first, then numbers
```javascript
{
"data": {
"fair": {
"exhibitorsGroupedByName": [
{
"letter": "#",
"exhibitors": [
{
"partner": {
"name": "{Suit}"
}
},
{
"partner": {
"name": "193 Gallery"
}
},
{
"partner": {
"name": "313 Art Project"
}
},
]
},
{
"letter": "A",
"exhibitors": [
{
"partner": {
"name": "A2Z Art Gallery"
}
},
]
},
]
}
}
}
```
[FX-3294]: https://artsyproduct.atlassian.net/browse/FX-3294
=> fix(FX-3294): Group fair exhibitors by numeric or special character within `#` group

package.json, yarn.lock
Adding `chalk`  because it is one of the required dependencies. Yarn
doesn't validate deps as long as they are indirectly included by other
libraries. Recent changes have surfaced this.
=> fix: Chalk

src/schema/v2/__tests__/fair.test.js, src/schema/v2/fair.ts
The type of this PR is: **Feature**
This PR resolves [FX-3301]
```javascript
{
"data": {
"fair": {
"exhibitorsGroupedByName": [
{
"letter": "A"
},
{
"letter": "B"
},
{
"letter": "C"
},
{
"letter": "D"
},
...
{
"letter": "#"
}
]
}
}
}
```
[FX-3301]: https://artsyproduct.atlassian.net/browse/FX-3301
=> feat(FX-3301): return sorted letters in order for `exhibitorsGroupedByName`

src/schema/v2/home/__tests__/home_page_artwork_modules.test.js, src/schema/v2/home/fetch.ts
The type of this PR is: **Fix**
Solves: [FX-3300]
* Art Fair rail is appearing on the homepage, even though the fair has not yet launched. Clicking into the fair leads to a 404 error.
* Fairs should not be appearing on homepage rail ahead of start date.
It's now **September 13**
```javascript
{
"data": {
"homePage": {
"artworkModules": [
{
"key": "current_fairs",
"context": {
"name": "The Armory Show 2021",
"exhibitionPeriod": "Sep 9 – 30"
}
}
]
}
}
}
```
[FX-3300]: https://artsyproduct.atlassian.net/browse/FX-3300
=> fix(FX-3300): return only running fairs

src/schema/v2/item.ts, src/types/runtime/gravity/OrderedSet.ts
This updates `OrderedSet` to support a new `Profile` type. 
```graphql
{
orderedSet(id: "5638fdfb7261690296000031") {
description
itemType
orderedItemsConnection(first: 10) {
edges {
node {
__typename
... on Profile {
slug
internalID
}
}
}
}
}
}
```
=> feat: [OrderedSet] Add additional Profile type

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
This PR fixes shipping label for artworks with Arta shipping.
Discussed here - https://artsy.slack.com/archives/C9ZJYFDNF/p1629972053009400
JIRA - https://artsyproduct.atlassian.net/browse/PX-4576
=> fix(PX-4576): use "Shipping: Сalculated in checkout" for artworks with arta shipping

src/lib/loaders/loaders_without_authentication/vortex.ts
Addresses [CX-1891]
Removes duplicated `/api` from `vortexGraphqlLoader` path.
[CX-1891]: https://artsyproduct.atlassian.net/browse/CX-1891
=> fix: Remove duplicated "/api" from vortexGraphqlLoader path

src/schema/v2/me/__tests__/newWorksByInterestingArtists.test.ts, src/schema/v2/me/newWorksByInterestingArtists.ts
Addresses [CX-1891]
Changes the `newWorksByInterestingArtists` resolver in order to filter out sold artworks for.
[CX-1891]: https://artsyproduct.atlassian.net/browse/CX-1891
=> fix: Filter out sold artworks for newWorksByInterestingArtists

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
To support phone number validation, we need to add a  phone number country code field to the Address model in [Gravity](https://github.com/artsy/gravity/pull/14447) and enable storing values in the db via MP mutations. This PR introduces the necessary schema updates to support this ch.
https://artsyproduct.atlassian.net/browse/PURCHASE-2938
=> feat: support adding country code to address field

_schemaV2.graphql, src/schema/v2/__tests__/object_identification.test.js, src/schema/v2/home/__tests__/home_page_artwork_module.test.js, src/schema/v2/home/__tests__/home_page_artwork_modules.test.js, src/schema/v2/home/home_page_artwork_module.ts
Noticed that we weren't getting proper types / intellisense for requesting home modules, looked, and realized that the enum wasn't being assigned: 
Have looked through Force and Eigen and it appears this field isn't yet being used, though it might be accessed in some old version of the mobile app. Thoughts?
=> feat: [Home] Use HomePageArtworkModuleTypes enum

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/showsByFollowedArtists.test.ts, src/schema/v2/me/index.ts, src/schema/v2/me/showsByFollowedArtists.ts
Addresses [CX-1957]
Adds showsByFollowedArtists field under me that returns all shows including artists the user follows.
Depends on https://github.com/artsy/gravity/pull/14458
```
query ShowsByFollowedArtistsQuery {
me {
showsByFollowedArtists(first: 100, sort: NAME_ASC, status: UPCOMING) {
totalCount
edges {
node {
name
}
}
}
}
}
```
[CX-1957]: https://artsyproduct.atlassian.net/browse/CX-1957
=> feat: Add showsByFollowedArtists

src/lib/__tests__/moneyHelpers.test.ts, src/lib/moneyHelpers.ts, src/schema/v2/artwork/index.ts
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-2970
When an artwork is set as displaying price range and is in the lowest (`[nil, 1000]`) or highest (`[10_000_000, nil]`) bucket, the price is displayed incorrectly with an exact price, rather than the "Under [price]" or "[price] and up" language.
This fixes it by updating the `priceRangeDisplayText` logic and the `saleMessage` resolver. More details inline.
It's not ideal there if duplicate and inconsistent formatting logic in MP and Gravity that deserves a bigger discussion. This only fixes the immediate issue.
=> Fix price range display when price is in the lowest or highest bucket (PURCHASE-2970)

_schemaV2.graphql, src/schema/v2/city/index.ts
A nice surprise: simply adding these arguments works because the helpers already anticipate them.
=> fix(city): adds support for page and size params

src/schema/v2/city/index.ts
Allows us to support 404s for city pages in Force.
=> fix(city): throws 404 to support principal field

package.json, yarn.lock
Reverts artsy/metaphysics#3368
This never ran the type-check and is blocking production deploys 🤔 Let's revert since there's an important bugfix to send out (https://github.com/artsy/metaphysics/pull/3449/commits/61f416eb9024db07c07a6aae4e4c8447ed1d8b1f), and then re-update TypeScript later
=> Revert "chore(deps): update dep typescript from 4.3.5 to v4.4.3"

tsconfig.json
Re: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables
Not sure why this passed and merged: https://github.com/artsy/metaphysics/pull/3368
=> fix(types): disables use unknown in catch

_schema.graphql, _schemaV2.graphql, src/schema/v2/me/myCollection.ts
Addresses [CX-1868]
Adds a flag to exclude purchased artworks from "My Collection" query. This is necessary to only show artworks that have been automatically added to "My Collection" to specific users until we release the feature for all users.
[CX-1868]: https://artsyproduct.atlassian.net/browse/CX-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add flag to exclude purchased artworks from My Collection query

_schemaV2.graphql, src/lib/loaders/loaders_without_authentication/gravity.ts, src/schema/v1/__tests__/partners.test.js, src/schema/v1/partners.ts, src/schema/v2/__tests__/partners.test.js, src/schema/v2/partners.ts
Closes [GRO-646](https://artsyproduct.atlassian.net/browse/GRO-646)
Thankfully we already have a partners connection; it just didn't correctly implement total count and is missing some params. This also doesn't expose the aggregations which we'll probably want to do and then deprecate `filterPartners` entirely.
=> fix(partners): fixes connection; adds args

src/schema/v2/partners.ts
Here we also have to compact the arguments — `near: null` causes a 500. cc @mzikherman — this should likely be fixed in Gravity.
=> fix(partnersConnection): removes null/undefined values from gravity args

src/schema/v2/partners.ts
OK, a quick read of the source of [connectionFromArraySlice](https://github.com/graphql/graphql-relay-js/blob/17231860ee64431009c193be2e6ac444936a88ea/src/connection/arrayConnection.js#L49-L111) and it seems like we were passing the gravity args rather than the connection pagination args. This PR fixes that and cleans up a bit.
=> fix(partnersConnection): corrects hasNextPage calculation

_schemaV2.graphql, src/schema/v2/me/myCollection.ts
This changes the default behavior of metaphysics to ask gravity to exclude users imported purchases from their collection. This is to maintain backwards compatibility with old clients until the feature is ready. 
Conversation here on justification: https://github.com/artsy/gravity/pull/14610
=> fix: default to excluding purchased artworks from my collection 

_schemaV2.graphql, src/schema/v2/schema.ts
Closes [GRO-602](https://artsyproduct.atlassian.net/browse/GRO-602)
So this apparently existed but was disabled with [this commit](https://github.com/artsy/metaphysics/commit/dde8efc4b76dcfbeb3bf2d68bbb09ce42bab04ad). This PR re-enables the field `partnerCategory(id)` field.
=> feat(schema): exposes partner category

src/index.ts, src/lib/stitching/gravity/link.ts, src/types/graphql.d.ts
This should fix the behavior you were seeing. Namely, Pulse was passing an `X-XAPP-TOKEN` to Metaphysics, which wasn't being propagated when a stitching request occurs. Metaphysics' own token is used instead, and it is not a trusted app.
This switches the behavior for gravity stitching to match the behavior for data loaders: namely, if the request passes an `X-XAPP-TOKEN`, pass that through to Gravity instead of using Metaphysics' own.
=> fix: propagate a requests xapp token when using stitching

_schemaV2.graphql, src/lib/__tests__/date.test.ts, src/lib/date.ts, src/schema/v2/__tests__/fair.test.js, src/schema/v2/__tests__/show.test.js, src/schema/v2/fair.ts, src/schema/v2/show.ts, src/schema/v2/show_event.ts
Add a `shortExhibitionPeriod` property that shows exhibition period display text in the old style with shortened months. In the app in some places we are displaying these dates we are pretty space constrained so in order to prevent wrapping to next line or cutting off text as much as possible we should use this instead. 
Instead of: `"February 25 – May 24, 2015"` => `"Feb 25 - May 24, 2015"`
Way around my hacky way of fixing this in Eigen: https://github.com/artsy/eigen/pull/5802
This logic was updated here to show longer months and it does look nicer so we should use it still where we can: https://github.com/artsy/metaphysics/pull/3497
=> feat: short exhibition dates for shows + fairs

_schemaV2.graphql, src/lib/__tests__/date.test.ts, src/lib/date.ts, src/schema/v2/__tests__/fair.test.js, src/schema/v2/__tests__/show.test.js, src/schema/v2/fair.ts, src/schema/v2/show.ts, src/schema/v2/show_event.ts, src/schema/v2/types/exhibitonPeriod.ts
some PR review follow up from https://github.com/artsy/metaphysics/pull/3550
Instead of having a separate field add a format arg to the existing exhibitionPeriod field, right now just `LONG` and `SHORT` supported.
=> fix: short show exhibition period as a format arg

_schemaV2.graphql, src/schema/v2/fair.ts, src/schema/v2/show.ts, src/schema/v2/show_event.ts
former PR made the format arg required which was incompatible with Eigen's existing schema. This makes the arg not required but we still have a default.
=> fix: make format arg not required

_schemaV2.graphql, src/lib/helpers.ts, src/schema/v2/me/__tests__/artistRecommendations.test.ts, src/schema/v2/me/artistRecommendations.ts, src/schema/v2/me/index.ts, src/schema/v2/me/newWorksByInterestingArtists.ts
Addresses [CX-2131]
Adds a new `artistRecommendations` connection to `me`. The connection fetches artist recommendations for the current user from **Vortex** and the artist details from **Gravity**.
```graphql
query ArtistRecommendationsQuery {
me {
artistRecommendations(first: 10) {
totalCount
edges {
node {
artistId
score
}
}
}
}
}
```
[CX-2120]: https://artsyproduct.atlassian.net/browse/CX-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2131]: https://artsyproduct.atlassian.net/browse/CX-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2131): Add artist recommendations

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
https://artsyproduct.atlassian.net/browse/TX-135
We want to enable BNMO (including Make Offer in Inquiries) for artworks located in relevant countries as long as partners have provided a VAT status (and necessary exemption documentation for us to review), regardless of the selected status.
With this, clients (i.e. Volt) will not block taking actions on MOI orders as long as there is _a_ VAT status set. The recording below shows the flow of selecting exempt and the blocking banner going away. Note that the actions are still disabled because of metadata that's also required by Make Offer in Inquiries.
=> [COORDINATE-DEPLOY] feat: relax VAT requirements for artworks (TX-135)

_schema.graphql, _schemaV2.graphql, src/data/convection.graphql
Ticket: [SWA-134](https://artsyproduct.atlassian.net/browse/SWA-134)
As part of the above ticket's implementation [in Convection](https://github.com/artsy/convection/pull/1184), our DB schema has slightly changed with the addition of a new column called `created_by` on Submissions, which is also reflected Convection's graphQL schema since this new field is automatically added for sorting only. 
This PR updates Convection's schema in MP to reflect the above change.
=> [feat]: update convection schema

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
[FX-3624]
At the moment, the principle of operation of the Size filter on Force (we can choose several size values) and Eigen (we can choose only one size value) is different and we decided to make the same behavior on the two platforms the same (the user can select multiple filter values). For this reason, we need to add support for the sizes attribute in SearchCriteria, SearchCriteriaAttributes.
[FX-3624]: https://artsyproduct.atlassian.net/browse/FX-3624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-3624): Add "sizes" attribute to SearchCriteria and SearchCriteriaAttributes

package.json, scripts/push-schema-changes.js, yarn.lock
https://github.com/artsy/update-repo/releases/tag/v0.5.0
Update the @artsy/update-repo package to address the failing CI step in #3596. Our push-schema-changes step is failing due to recent default branch updates across other repositories to `main`. The recently released @artsy/update-repo version should fix the targetBranch behavior.
cc/ @mc-jones
=> chore: update @artsy/update-repo package to v0.5.0

yarn.lock
This PR bumps `set-value` to address a security vulnerability, see the [Dependabot Alert](https://github.com/artsy/metaphysics/security/dependabot/yarn.lock/set-value/open) for details.
=> chore: bump set-value to 2.0.1

_schemaV2.graphql, src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Addresses [CX-2218]
Add artwork_location to artwork
It needs [gravity PR](https://github.com/artsy/gravity/pull/14759) to be deployed first. 
[CX-2218]: https://artsyproduct.atlassian.net/browse/CX-2218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add artwork_location to artwork

scripts/push-schema-changes.js
Follow up after https://artsy.slack.com/archives/C02BAQ5K7/p1639509813109500.
We tend to prefer a squash-merge to avoid the merge commit these days.
=> chore: use Squash on Green label when pushing schema updates to client repos

src/lib/apis/fetch.ts, src/schema/v2/me/unlinkAuthenticationMutation.ts
So, for whatever reason: https://github.com/artsy/gravity/blob/31ced403829a5b4b4f3618075345a2f5cef0730f/app/api/v1/me_authentications_endpoint.rb#L26 is returning a successful but empty response.
This PR both prevents us from parsing empty string, which is correct. And just returns empty object on the mutation, which is fine since we don't actually use the response, the only output field on this mutation is `me`.
=> fix(mutations): success for unlink auth

package.json, src/lib/stats.js, yarn.lock
`appmetrics` is blocking the upgrade to Node 16 and one critical
security vulnerability.
After a comprehensive investigation it was determined that all of the
metrics (except loop latency) were already tracked by DataDog. The
information reported by the loop latency monitor is still available 
albeit this requires combining existing metrics.
If it turns out we still need loop latency Node 16 has built in support
for tracking this value.
=> chore: Remove Appmetrics

peril/compareForceSchema.ts
Updating the branch reference from `master` to `main` in `ForceSchemaUrl` after the [adoption of inclusive language](https://github.com/artsy/force/pull/9041). 
This should resolve an issue that surfaced in #3618, due to Peril not being able to fetch the GraphQL schema as https://github.com/artsy/force/raw/master/data/schema.graphql 404s. Per [GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch), “Although file URLs are automatically redirected, raw file URLs are not redirected”
=> fix: update master to main in force schema url

yarn.lock
This PR dedupes `Request`, removing the transitive dependency on `cryptiles` and closes out the related [vulnerability](https://github.com/artsy/metaphysics/security/dependabot/yarn.lock/cryptiles/open).
=> chore: remove cryptiles as a transitive dependency of hawk

_schemaV2.graphql, src/schema/v2/artwork/index.ts
So: 
Downloadable images for admins are currently broken in Force.
Previously we were constructing this URL with some methods on the old Backbone models and then proxying the download. I don't really see a reason though why we can't just conditionally display this URL directly on the client-side — this will redirect. Let me know if I'm missing something obvious. This endpoint will redirect to the S3 asset with a `X-Amz-Expires=43200` query param.
=> feat(artwork): exposes downloadableImageUrl

_schema.graphql, _schemaV2.graphql, src/data/convection.graphql
In a [previous PR](https://github.com/artsy/metaphysics/pull/3628/files), session ID sorting was changed by the auto-schema update. However, running a schema synch in Convection creates the diff with session ID sorting. 
This PR simply brings back the session Id as a sorting param. 
Note that: the actual changes (for removeAsset mutation) has already been merged in the above PR in metaphysics.
=> feat: bring back sorting for submissions

index.js, package.json, yarn.lock
Drop Bluebird in favor of Node.js native promises the native performance is now 
better than Bluebird.
=> feature: Remove Bluebird

_schemaV2.graphql, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
This PR resolves [CX-2232](https://artsyproduct.atlassian.net/browse/CX-2232) changes the medium field as optional in add/update artwork form on my collection.
=> fix: Medium as optional on My Collection form

src/schema/v2/partner.ts
Reverts artsy/metaphysics#3193
Reverting this because there are a few places in force that are incorrectly already adding a /partner at the front of the URL. Will update those and then re-merge this in!
=> Revert "feat(PX-4058): partner transition part 3"

src/schema/v2/partner.ts
Reverts artsy/metaphysics#3641
A double-revert!
This gets us back to the original state, and effectively re-merges in [this PR](https://github.com/artsy/metaphysics/pull/3193). The end-result is that metaphysics will serve our new URL-style `/partner/:partner_slug` for the partner `href` field. We updated the URL from `/:profile_id` -> `/partner/:partner_slug` back when we rebuilt the partner profile page. This is one of the lingering changes from that effort.
The first revert was because we noticed a few broken links on the homepage. [This PR](https://github.com/artsy/force/pull/9137) has fixed those, so now we're good to merge in this change!
=> Revert "Revert "feat(PX-4058): partner transition part 3""

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
[TX-148](https://artsyproduct.atlassian.net/browse/TX-148)
We want to enable BNMO (including Make Offer in Inquiries) for artworks located in relevant countries as long as partners have provided a VAT status (and necessary exemption documentation for us to review), regardless of the selected status.
With this, clients (i.e. Volt) will not block taking actions on MOI orders as long as there is a VAT status set.
Currently, VAT-exempted partners cannot take actions (e.g. accepting) on MOI orders in CMS. This PR will add a new flag to enable it once the partner’s VAT exempt status has been approved by Artsy.
=> feat(TX-148): relax vat requirements and add exempt approval flag

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/artist/index.ts, src/schema/v2/sorts/artist_sorts.ts
See: [Hackathon card](https://www.notion.so/artsy/37f51b29fb994928bcacd49b17d0ac78?v=20814d7262fe45f4afc46905aa6a6b90&p=3b9274b7b69c4ff789776e765b2403dd)
Follow-up to https://github.com/artsy/gravity/pull/14840, whose new features are served up here:
- exposes the `CREATED_AT_DESC` and `CREATED_AT_ASC` sorts on `artistsConnection`
- exposes the `createdAt` field on the `Artist` type
- exposes the `duplicates` field on the `Artist` type (authenticated users only)
=> feat(artist dupes): expose new sorts and fields for artists

_schemaV2.graphql, src/schema/v2/me/__tests__/collector_profile.test.js, src/schema/v2/me/__tests__/update_me_mutation.test.js, src/schema/v2/me/collector_profile.ts, src/schema/v2/me/index.ts, src/schema/v2/me/update_me_mutation.ts
Relates to #3640
After some discussion, we decided to have the privacy field as String in Gravity, so we needed to reflect the changes here as well.
See https://github.com/artsy/gravity/pull/14815 for more context.
=> refactor: make CollectorProfile#privacy String

src/schema/v2/me/myCollection.ts
Addresses [CX-2269]
There is no need anymore to exclude purchased artworks from "My Collection". Therefore we can default `excludePurchasedArtworks` to false so clients don't have to send the param anymore.
Relates to https://github.com/artsy/eigen/pull/6036
[CX-2269]: https://artsyproduct.atlassian.net/browse/CX-2269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Set excludePurchasedArtworks to false

_schemaV2.graphql, src/schema/v2/article/sections/ArticleSectionImageCollection.ts, src/schema/v2/article/sections/ArticleSectionImageSet.ts
So articles may have unpublished works and since we are loading the actual artwork now we need to catch and filter them out.
=> fix(article): filters out unpublished artworks

src/schema/v2/artwork/index.ts
Changed condition that handles the price paid for the artwork in a user's 'my collection. With this fixes collectors can enter the price paid for the artwork equal to 0 and it will be displayed in the artwork details. - daria
Before: 
After:
=> fix(CX-2262): price_paid_cents check for zero value

_schemaV2.graphql, src/schema/v2/me/linkAuthenticationMutation.ts
This PR resolves [CX-2303]
Fixes Typo in AppleUid params sent to gravity from Metaphysics
[CX-2303]: https://artsyproduct.atlassian.net/browse/CX-2303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix(CX-2303): fix appleuid typos

_schemaV2.graphql, src/schema/v2/me/__tests__/index.test.ts, src/schema/v2/me/index.ts
This PR adds `emailConfirmed` to the me interface.
This PR comes as a follow-up on @lordkiz comment [here](https://github.com/artsy/eigen/pull/6076#issuecomment-1026843273)
=> feat: add emailConfirmed to me interface

_schemaV2.graphql, src/schema/v2/static_content.ts
This updates the staticContent.content field to use `markdown()` helper, which can convert to regular html on the fly
=> feat(static-content): Add markdown formatter to field

src/schema/v2/requestLocation.ts
Turn out the api key only works if you are hitting the api subdomain. Nothing is easy folks.
https://artsyproduct.atlassian.net/browse/GRO-784
=> fix: Use correct geolocation url GRO-784

src/schema/v2/article/index.ts
Oddly enough, if this receives `null` Positron will `403` error...
=> fix(article): correctly passes tags

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts, src/schema/v2/artwork/artworkConsignmentSubmissionType.ts, src/schema/v2/me/__tests__/myCollection.test.ts
The goal is to hide Artwork Edit Button when the submission is in progress. This is a BE part of the story: adds inProgress field to artworkConsignmentSubmission type
Jira - https://artsyproduct.atlassian.net/browse/CX-2328
=> [CX-2328]: adds inProgress to artworkConsignmentSubmission

_schemaV2.graphql, src/schema/v2/partnerInquirerCollectorProfile.ts
This PR resolves [CX-2257](https://artsyproduct.atlassian.net/browse/CX-2257)
This is a follow up on #3710 
This PR adds `userIntroduction` field into the Partner inquirer collector profile endpoint to be used by the old design of the the collector profile
It also adds `affiliatedGalleryIds` and `affiliatedGalleryIds` fields to be used in the collector profile controller in volt
=> fix [CX-2257]: update  partner inquirer collector profile fields

src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/v2/stitching.ts
Fixes a doubled inquiry from the mutation `submitOfferOrderWithConversation` when the `source` of the offer is `inquiry`. For these cases, we don't need to create another `inquiry`.
=> fix: doubled inquiries from Exchange stitching

src/schema/v1/artwork/__tests__/artwork.test.js, src/schema/v1/artwork/index.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
[NX-3081] We don't need to check here if an artwork is not `ecommerce` in order to determine if it's `inquireable`. This is Gravity responsibility.
See: https://github.com/artsy/gravity/pull/14971
[NX-3081]: https://artsyproduct.atlassian.net/browse/NX-3081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove unneeded conditionals from inquireable

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts, src/schema/v2/artwork/artworkConsignmentSubmissionType.ts, src/schema/v2/artwork/index.ts, src/schema/v2/me/myCollection.ts
Jira: https://artsyproduct.atlassian.net/browse/CX-2343
The task is to add the rest of the statuses from this document: https://www.notion.so/artsy/SWA-My-Collection-integration-8d02370063b444e19036dc19f8e73915#b8d078fc5c064e0592c67da44fd824e8
Another change - now it is possible to query consignmentSubmission directly by artwork:
```
{
artwork(id: ...) {
title
internalID
consignmentSubmission {
inProgress
}
}
}
```
=> [CX-2343]: Adds consignment submission statuses to artworks

_schemaV2.graphql, package.json, src/lib/colors.ts, src/lib/stitching/gravity/v2/stitching.ts, src/schema/v2/__tests__/searchCriteriaLabel.test.ts, src/schema/v2/schema.ts, src/schema/v2/searchCriteriaLabel.ts, yarn.lock
https://artsyproduct.atlassian.net/browse/FX-3216
Supersedes:  ~https://github.com/artsy/gravity/pull/14926~
This gives Metaphysics the ability to add human-readable search criteria into the `SearchCriteria` response coming from upstream in Gravity.
So, whereas Gravity's GraphQL API might produce a response like this…
Metaphysics can now additionally fulfill a new `labels` field on `SearchCriteria`…
See the first commit (https://github.com/artsy/metaphysics/pull/3762/commits/7fec9bda1e4f078903c1566c95fd61580c596147) where the basic plumbing is laid down. Subsequent commits add the various facets, one at a time.
=> feat(alerts): render human-friendly criteria labels

_schemaV2.graphql, src/schema/v2/fields/__tests__/money.test.ts, src/schema/v2/fields/money.ts
This PR introduces an optional parameter on the amount field that when passed will return the `disambiguate_symbol` subfield if present. 
This should allow us to display `US$XXX` instead of `$XXX` to distinguish US from other dollar-based currencies (e.g. AUD,   HKD) optionally, and without introducing breaking changes in all of the places the money helper is used.
This is a requirement from [NX-2405](https://artsyproduct.atlassian.net/browse/NX-2405) and it fixes this [bug](https://github.com/artsy/force/pull/8963).
[NX-3031](https://artsyproduct.atlassian.net/browse/NX-3031)
Thank you to @starsirius for their help on this!
=> fix: disambiguate currency symbols

_schemaV2.graphql, src/schema/v2/article/lib/extractEmbed.ts, src/schema/v2/article/models.ts
So, Positron seems to have some layouts that are more or less just implemented via convention in the UI rather than modeled explicitly. In this case: if there's a hero unit in the "basic" layout; then you can have a URL associated with it; that URL isn't an image as in the other layouts; but is an embed.
=> feat(article): detect and supports embeds

src/schema/v2/me/index.ts
Follow-up for https://github.com/artsy/metaphysics/pull/3759
This PR adds default values to user metric preferences. These default values are just needed because we cannot guarantee that Gravity always sends values due to caching issues.
=> fix: Add user metric preference default values

_schemaV2.graphql, src/schema/v2/articlesConnection.ts, src/schema/v2/artist/index.ts, src/schema/v2/fair.ts, src/schema/v2/fair_organizer.ts, src/schema/v2/partner.ts
Type: **Chore**
Jira ticket: [FX-3753]
Update description for `inEditorialFeed` field based on artsy/positron#1669 and [this code](https://github.com/artsy/positron/blob/80d34bcc17b47c9d80f95e5a8187565a9e51740b/src/api/apps/articles/model/retrieve.js#L142)
[FX-3753]: https://artsyproduct.atlassian.net/browse/FX-3753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-3753): update description for inEditorialFeed field

_schemaV2.graphql, src/schema/v2/partnerInquirerCollectorProfile.ts
This PR is a follow up to #3747
This PR updates the CMS Collector Profile fields to remove unused fields and fixes the `emailConfirmed` resolver
=> Fix [CX-2257]: CMS Collector Profile 

_schemaV2.graphql, src/schema/v2/featured_link.ts
Adds a proper `entity` union type to the featured link; wherein we try to load the thing that is being linked to.
I'm also removing this crazy `internalID` overwrite that apparently I introduced many, many years ago.
=> feat(featuredlink): exposes entities

src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts
Fix for users that were created without names, which is breaking MP queries, since name is supposed to be non-nullable.
https://artsyproduct.atlassian.net/browse/BID-220
=> fix:fallback to email if user.name is null

_schemaV2.graphql, src/schema/v2/sale_artworks.ts
This is a somewhat hacky fix to get around arg type mismatches in Relay, which causes problems as args are often passed down at the top of the app to various parts of the sub tree. 
Since `sale(id: "foo")` expects `String!` one would expect the other field to accept the same too. Not a pleasing situation but not sure what else to do.
=> feat(saleArtworksConnection): Add saleSlug input arg

_schemaV2.graphql, src/schema/v2/me/__tests__/bidder_position.test.js, src/schema/v2/me/__tests__/bidder_position_mutation.test.js, src/schema/v2/me/bidder_position.ts, src/schema/v2/me/bidder_position_messages.ts, src/schema/v2/me/bidder_position_mutation.ts, src/schema/v2/types/bidder_position_result.ts
This fixes some error handling issues we were seeing with the bidder position. I'm not sure how it worked before, unless we changed the structure of our error response in Gravity? In any case this works:
From grav: 
In MP: 
Additionally, added a new field, `rawError`, which returns the error as it originates from gravity. I have no clue why we aren't using this in the UI? It's quite informative (as one would expect). 
cc @artsy/grow-devs
=> fix(bidder-position): Fix error status handling

src/schema/v2/__tests__/searchCriteriaLabel.test.ts, src/schema/v2/searchCriteriaLabel.ts
~~WIP: planning to move some of the parsing and formatting of size values to a util package so that they can be shared between Force, Eigen, and Metaphysics, per [this conversation](https://artsy.slack.com/archives/C9SATFLUU/p1645445717561499) on Slack.~~
~~We should also consider if there's any logic for other filter formatting that could be moved to this util! Prices perhaps? Planning on creating that package tomorrow~~
We ended up having more conversations about this and deciding that we want to store in/cm units on SearchCriteria in Gravity, which means we'll need to update this parsing anyway. For now, we'll go with the copy/paste approach to unblock displaying these labels.
Jira ticket: https://artsyproduct.atlassian.net/browse/FX-3451
=> feat[FX-3451]: human-readable size labels for SearchCriteria

_schemaV2.graphql, src/schema/v2/me/__tests__/artworkRecommendations.test.ts, src/schema/v2/me/artworkRecommendations.ts, src/schema/v2/me/index.ts
Addresses [CX-2371]
This PR adds the new `artworkRecommendations` connection to `me`. The connection fetches artwork recommendations for the current user from **Vortex** and the artwork details from **Gravity**.
```graphql
query ArtworkRecommendationsQuery {
me {
artworkRecommendations(first: 10) {
totalCount
edges {
node {
artistId
score
}
}
}
}
}
```
[CX-2371]: https://artsyproduct.atlassian.net/browse/CX-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Artwork recommendations

_schemaV2.graphql, src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/index.ts
[BX-230](https://artsyproduct.atlassian.net/browse/BID-230)
Adding `cascadingEndTimeInterval` to MP so we can access it as a feature flag in Force and Eigen.
MP query in Insomnia hitting local endpoint w/ these changes:
=> feat: Add cascading_end_time_interval to MP sale type

src/lib/colors.ts, src/schema/v2/__tests__/searchCriteriaLabel.test.ts, src/schema/v2/searchCriteriaLabel.ts
Follow-up on https://github.com/artsy/metaphysics/pull/3762
- Adds new colors and keeps old ones as `OLD_COLORS`
more context on this [slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1646316037871739)
=> feat(alerts): add support for new colors

src/schema/v2/article/index.ts
Positron will (annoyingly) 403 if `channel_id` is `undefined`. So this introduces some guards against that. Very rarely articles may be missing a channel.
=> fix(article): fixes when articles are missing channel ids

_schemaV2.graphql, src/schema/v2/sale_artwork.ts
Adding `end_at` to the `SaleArtwork` type in Metaphysics:
Query running locally:
=> chore: Add end at to saleArtwork

.circleci/config.yml
Similar to https://github.com/artsy/force/pull/9533, this PR removes the unused Codecov orb.
=> Remove unused Codecov orb

src/schema/v2/me/auction_results_by_followed_artists.ts
Addresses [CX-2423]
This PR increases the number of considered followed artists for AuctionResultsByFollowedArtists from 50 to 200.
This change will affect the performance of the query for users with more than 100 followed artists slightly which is expected.
[CX-2423]: https://artsyproduct.atlassian.net/browse/CX-2423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Increase number of considered artists for AuctionResultsByFollowedArtists to 200

_schemaV2.graphql, src/schema/v2/artist/targetSupply/__tests__/index.test.ts, src/schema/v2/artist/targetSupply/index.ts
Addresses [CX-2351]
Adds isP1 field to artist target supply.
This comment explains the data model in Gravity: [FX-3023: Enable admins to update artists' Target Supply Status from admin.artsy.net UIDONE](https://artsyproduct.atlassian.net/browse/FX-3023?focusedCommentId=39537)
[CX-2351]: https://artsyproduct.atlassian.net/browse/CX-2351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add isP1 field to artist target supply

_schemaV2.graphql, src/lib/date.ts, src/schema/v2/__tests__/sale_artwork.test.js, src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/display.ts, src/schema/v2/sale/index.ts, src/schema/v2/sale_artwork.ts
Add `formattedStartDateTime` to `SaleArtwork` type so I can use it in [my PR](https://github.com/artsy/force/pull/9550) to add a label under the timer on the lot page. We need to show the correct copy depending on whether the sale has started and whether the lot itself has closed.
=> feat: Add formattedStartDateTime to MP

src/schema/v2/article/__tests__/article.test.ts, src/schema/v2/article/index.ts
Discovered that classic layout articles will utilize the `author` field, which is otherwise only used to control the article slug (lol).
=> fix(article): fallback to author field before editors default

_schemaV2.graphql, src/schema/v2/__tests__/previewSavedSearch.test.ts, src/schema/v2/previewSavedSearch.ts, src/schema/v2/schema.ts
Allows a client to preview the formatted labels for an unpersisted alert criteria.
Jira: [FX-3819](https://artsyproduct.atlassian.net/browse/FX-3819)
**Request**
```graphql
{
previewSavedSearch(attributes: { attributionClass: ["unique"], artistIDs: ["4e934002e340fa0001005336"], acquireable: true }) {
labels {
field
name
value
}
}
}
```
**Response**
```json
{
"data": {
"previewSavedSearch": {
"labels": [
{
"field": "artistIDs",
"name": "Artist",
"value": "KAWS"
},
{
"field": "attributionClass",
"name": "Rarity",
"value": "Unique"
},
{
"field": "acquireable",
"name": "Ways to Buy",
"value": "Buy Now"
}
]
}
}
}
```
=> feat: add previewSavedSearch query field

_schemaV2.graphql, src/lib/date.ts, src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/index.ts
This PR addresses an [issue brought up in slack](https://artsy.slack.com/archives/C01PBEBRB0V/p1647482514904939) where the date in force was displaying invalid date to invalid date. This was caused by auctionsDetailFormattedStartDateTime not accounting for live sale integrations.
=> bug:ensure auctions detail formatted start date time works with live auction integrations

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts
Addresses [CX-2455]
This PR adds `importSource` as an enum to the artwork type and `myCollectionCreateArtworkMutation`. I've added `UNKNOWN` to it because there are no validations in Gravity and import source can be any string. 
Suggestions for a better solution are very welcome :)
[CX-2455]: https://artsyproduct.atlassian.net/browse/CX-2455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add importSource to artworks

src/schema/v2/me/__tests__/bidder_position.test.js, src/schema/v2/me/bidder_position.ts, src/schema/v2/me/bidder_position_messages.ts
This PR adds a new error state for bidder positions when a lot is closed but the sale is still open.
[BID-257](https://artsyproduct.atlassian.net/browse/BID-257)
I chose to do this in MP because we append the error "Lot must be open" in Gravity ([here](https://github.com/artsy/gravity/blob/1d339c53d3482b522952b9534b31ae774e70c50a/app/models/lot_events/max_bid_placed.rb#L217)) so even the `SALE_CLOSED` case checks for that error. Interested in feedback on doing this extra check the position's sale's auction state. 
Here's what it looks like in Force w/ [corresponding Force PR](https://github.com/artsy/force/pull/9721):
Example: Must be run on a bidder position that was placed on a lot that was closed but when the sale was open:
example from staging that will work for a few days: `{ …
=> feat: Add status for LOT_CLOSED when bidder position is on a sale that is open but a lot that is closed

_schemaV2.graphql, src/schema/v2/notification_preferences.ts
The `channel` and `id` fields aren't used by [Gravity](https://github.com/artsy/gravity/blob/main/app/api/v1/notification_preferences_endpoint.rb), so we can remove them and simplify the component using this data!
=> chore(GRO-844): Remove input values that aren't used by Gravity

_schemaV2.graphql, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
`title` doesn't need to be required when updating an artwork. It's just required when creating an artwork to prevent artworks without a title in My Collection. This change is needed to update the submission_id when a submission gets created for a My Collection artwork.
Context can be found here: https://github.com/artsy/metaphysics/pull/3638
=> fix: Make title unrequired again in myCollectionUpdateArtworkMutation

src/lib/__tests__/helpers.test.ts, src/lib/helpers.ts, src/schema/v2/artwork/comparableAuctionResults.ts
Addresses [CX-2467]
Check if ComparableAuctionResults date is a valid integer to allow negative dates like `-200`.
Follow up for https://github.com/artsy/metaphysics/pull/3907
[CX-2467]: https://artsyproduct.atlassian.net/browse/CX-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Check if ComparableAuctionResults date is a valid integer

_schemaV2.graphql, src/schema/v2/__tests__/previewSavedSearch.test.ts, src/schema/v2/__tests__/searchCriteriaLabel.test.ts, src/schema/v2/searchCriteriaLabel.ts
This PR adds the ability to query the initial value of search criteria, not just the human-readable label. This changes will allow us to replace the current implementation of label extraction for pills on Force/Eigen, where aggregations are now needed.
```
[
{
"field": "attributionClass",
"name": "Rarity",
"value": "Unique"
},
{
"field": "additionalGeneIDs",
"name": "Medium",
"value": "Prints"
},
{
"field": "sizes",
"name": "Size",
"value": "Small (under 40cm)"
},
{
"field": "acquireable",
"name": "Ways to Buy",
"value": "Buy Now"
},
{
"field": "partnerIDs",
"name": "Galleries and Institutions",
"value": "3 White Dots"
}
]
```
```
[
{
"field": "attributionClass",
"name": "Rarity",
"value": "unique", // search criteria value
"displayValue": "Unique" // human-readable label (it used to be a …
```
=> feat: add the ability to return value and displayValue fields in SearchCriteriaLabel

src/lib/date.ts, src/schema/v2/__tests__/sale_artwork.test.js, src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/index.ts, src/schema/v2/sale_artwork.ts
[BX-309](https://artsyproduct.atlassian.net/browse/BID-309)
Update cascading-end-time-relevant time fields to show local timezone or if not present, UTC.
Lot grid:
Sale details:
Lot page (date/time below timer):
=> chore: Use user tz for cascade end time timing fields

_schemaV2.graphql, src/schema/v2/user.ts, src/schema/v2/users/updateUserMutation.ts
Small one - turns out there was only one missing field for user data. I wrongly assumed some other fields were on user but they are actually on the SaleProfile model in Gravity. That means all I had to do here was add this flag to the query and mutation in order for Forque to be able to edit it.
While I was working through this I realized that I wrongly typed the phone number is NOT optional - it can def be `nil` in Gravity.
=> feat: Add data transfer bool for user

src/schema/v2/__tests__/previewSavedSearch.test.ts, src/schema/v2/searchCriteriaLabel.ts
Type: **Fix**
[ArtworkSizes](https://github.com/artsy/metaphysics/blob/main/src/schema/v2/artwork/artworkSizes.ts#L3-L16) values are stored in lowercase and for this reason we received an error when [parsing values](https://github.com/artsy/metaphysics/blob/main/src/schema/v2/searchCriteriaLabel.ts#L210) in [getSizeLabels](https://github.com/artsy/metaphysics/blob/main/src/schema/v2/searchCriteriaLabel.ts#L205-L214)
=> fix: parse error for sizes in `previewSavedSearch`

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap, src/lib/stitching/gravity/v2/stitching.ts
Type: **Feature**
Jira ticket: [FX-3831]
Gravity PR: artsy/gravity#15166
* `sort` argument must support `CREATED_AT_DESC`
* `sort` argument must support `NAME_ASC`
* As a developer, I can execute the following GraphQL query against Metaphysics (e.g. via Insomnia).
```graphql
{
me {
savedSearchesConnection(sort: CREATED_AT_DESC) {
edges {
node {
userAlertSettings {
name
}
}
}
}
}
}
```
[FX-3831]: https://artsyproduct.atlassian.net/browse/FX-3831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update stitched `savedSearchesConnection` to support new `sort` input argument

_schemaV2.graphql, src/lib/artworkMediums.ts, src/schema/v2/__tests__/artworkMediums.test.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/artworkMedium.ts
_Leaving this as a DRAFT until we can answer the question below_
https://artsyproduct.atlassian.net/browse/FX-3820
This allows artworks' medium types to be associated with their corresponding genes — which is what we actually use for filtering on the frontend in our artwork grids.
- Every artwork has a medium type field, which is exposed in Metaphysics as `{ artwork { mediumType { name … } } }`
- This ultimately derives from `Artwork#category` in the corresponding Gravity record; this value is originally supplied by the partner in CMS
- But that medium type is not sufficient for our desired Alerts functionality, because alerts are based on our artworks grids' filter facets — and the medium facet actually filters on the artworks' _genes_, through [a bit of indirection that is described …
=> feat(alerts): expose a medium type's corresponding filter gene

_schema.graphql, _schemaV2.graphql, src/data/gravity.graphql, src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
Just a schema bump now that we include these groups in Gravity's schema!
=> chore: update grav schema to include MarketingCollectionGroup

_schemaV2.graphql, src/schema/v2/article/channel.ts
The pinned articles aren't really relevant it seems — as those are managed via Parsely. Just exposes a normal articles connection here.
=> fix(channel): adds articles connection removes pinned articles

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
After deploying the final renaming of JSON fields `process_with_arta_shipping` to `process_with_artsy_shipping` in gravity: https://github.com/artsy/gravity/pull/15206 we can remove the fallbacks that check for `process_with_arta_shipping` in metaphysics and clean out all the fields we marked for deprecation last time.
Q: 
- Force is updated and deployed using the new fields, is it cool to remove the deprecated fields here altogether?
=> [PX-4946] Remove fallbacks + deprecated arta related fields

_schemaV2.graphql, src/schema/v2/sale/index.ts, src/schema/v2/sale_artwork.ts
Adds the fields for popcorn bidding, this lets the front-end start using them.
=> chore: add new fields for popcorn bidding to sale and sale artwork

.env.test, src/lib/__tests__/apis/galaxy.test.js
https://artsyproduct.atlassian.net/browse/PLATFORM-4041
As part of making diffusion internal only Metaphysics, a consumer of diffusion, will now use `artsy.systems` domain to reach diffusion. 
The environments (and `.env.shared`) have already been updated to use internal hostname:
```
➜  metaphysics git:(ovasdi/PLATFORM-4041/diffusion-internal-routing) hokusai staging env get | grep -i diffusion
DIFFUSION_API_BASE=https://diffusion.stg.artsy.systems/api
➜  metaphysics git:(ovasdi/PLATFORM-4041/diffusion-internal-routing) hokusai production env get | grep -i diffusion
DIFFUSION_API_BASE=https://diffusion.prd.artsy.systems/api
```
I noticed that galaxy URL is out of date so that was also updated as part of this PR.
=> chore: connect to diffusion using internal hostname

_schemaV2.graphql, src/schema/v2/artist/related.ts
This PR solves [GRO-861] to backfill featured artists if no artists are followed by user
[GRO-861]: https://artsyproduct.atlassian.net/browse/GRO-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GRO-861] add include_fallback_artists param to related artists schema

src/schema/v2/home/home_page_sales_module.ts
A small PR to update the sort on the sales that are shown on the home screen. This aligns what a user sees in the app with what they see on the auctions landing page per this one: https://github.com/artsy/force/pull/9557.
https://artsyproduct.atlassian.net/browse/GRO-904
=> feat: Boost licensed sales on the home screen GRO-904

_schemaV2.graphql, src/schema/v2/__tests__/user.test.ts, src/schema/v2/me/__tests__/__snapshots__/update_me_mutation.test.js.snap, src/schema/v2/me/__tests__/index.test.ts, src/schema/v2/me/__tests__/update_me_mutation.test.js, src/schema/v2/me/index.ts, src/schema/v2/me/update_me_mutation.ts, src/schema/v2/user.ts
Updates the user and associated update mutations to add access to the new order notification preference in gravity.
This PR should not be merged until gravity is updated!
https://github.com/artsy/gravity/pull/15186
=> feat: update user schema and mutations for order notifications

_schemaV2.graphql, src/schema/v2/__tests__/sale_artwork.test.js, src/schema/v2/sale_artwork.ts
Two semi-related updates here!
- add `lotID` to the `SaleArtwork` type. The websocket is at the level of a sale, broadcasting messages in the form `{lot_id: ..., extended_bidding_end_at: ...}` , so Force needs to be able to get the `lotID` in order to know what to update when a websocket comes in (on a lot page, it would only care about that specific lot, but on the auction page there might be multiple artworks that are getting extended).
- testing locally, I noticed that if you reloaded the page after a lot has been extended, the artwork sidebar will say 'Ended May 2...', coming from `formattedStartDateTime`.
=> feat: add lot id and modify formattedStartDateTime to take into account extended time

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/myCollectionAuctionResults.test.ts, src/schema/v2/me/index.ts, src/schema/v2/me/myCollectionAuctionResults.ts
Addresses [CX-2512]
Introduces `myCollectionAuctionResults` endpoint under `me` which returns auction results for artists from a user's "My Collection".
**Query:**
```graphql
{
me {
myCollectionAuctionResults(first: 10) {
edges {
node {
id
}
}
}
}
}
```
[CX-2512]: https://artsyproduct.atlassian.net/browse/CX-2512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Introduce myCollectionAuctionResults

src/schema/v2/me/__tests__/myCollectionAuctionResults.test.ts, src/schema/v2/me/myCollectionAuctionResults.ts
Addresses [CX-2512]
Use internal IDs for `MyCollectionAuctionResults` artist matching.
[CX-2512]: https://artsyproduct.atlassian.net/browse/CX-2512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Use internal IDs for MyCollectionAuctionResults artist matching

src/index.ts, src/lib/graphqlErrorHandler.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4120
Thanks @mc-jones for pairing on this.
---
This CL addresses a warning logged on every request in metaphysics which is polluting our logs. Most recently flagged by @mdole [here](https://artsy.slack.com/archives/CA8SANW3W/p1650641537810109).
- remove the `formatError` configuration option as it does not get used and is removed in [express-graphql v1.0.0](https://github.com/graphql/express-graphql/blob/92088332c3d81174a82a77abfdea8e4b5fc77100/src/index.ts#L113)
- The [message option](https://github.com/artsy/metaphysics/blob/main/src/index.ts#L208) `formatError` sets is set [here](https://github.com/artsy/metaphysics/blob/ddb359cd7fe45b21058fead58a4389ad93fee641/src/lib/graphqlErrorHandler.ts#L124) in `formattedGraphQLError`
- The …
=> chore: resolve `formatError` warning

_schemaV2.graphql, src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/v2/stitching.ts
[NX-3163]
Adds a new mutation `createInquiryOrder` that pretty much does the same as `createInquiryOfferOrder` but stitches to another mutation in Exchange.
Reasoning about why stitching again, Exchange doesn't support Rest API, has no Grape or other utility tool, we already use stitching here and the AST complexity was quite simple but happy and open to discuss if someone wants to 🙂 
[NX-3163]: https://artsyproduct.atlassian.net/browse/NX-3163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(NX-3163): createInquiryOrder mutation

_schemaV2.graphql, src/lib/loaders/loaders_without_authentication/index.ts, src/lib/loaders/loaders_without_authentication/vortex.ts, src/schema/v2/__tests__/artworksForUser.test.ts, src/schema/v2/artworksForUser.ts, src/schema/v2/schema.ts
This PR adds a new root query that can be used like so:
```gql
query ArtworksForUserAccessToken {
artworksForUser {
edges {
node {
title
}
}
}
}
```
Or:
```gql
query ArtworksForUserSignedAppToken {
artworksForUser(userId:"587aef0ea09a67787600115b") {
edges {
node {
title
}
}
}
}
```
Note that attempting to use it without either a user token or a signed app token will result in an error.
In terms of what this is doing - it moves the `newWorksByInterestingArtists` query up out of the `me` namespace and allows for two kinds of graphql loaders to hit vortex:
* one that uses the existing access token
* one that falls back to the app token being sent in
Note: depends on this one https://github.com/artsy/vortex/pull/446.
=> feat: Add artworksForUser root level query

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/__tests__/utilities.test.ts, src/schema/v2/artwork/index.ts, src/schema/v2/artwork/utilities.ts
A gallery partner [asked](https://artsy.slack.com/archives/C7LEJU1QU/p1651828938959449) why one of their works did not have the "view in room" button on the desktop artwork page.
The [only thing](https://github.com/artsy/force/blob/6609be28a4657e9d65f435b74c7de59edbe4fcb0/src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx#L165) that determines whether we show or hide that button in the Force UI is a computed field `isHangable` in Metaphysics.
Looking into how `isHangable` is computed, I noticed that we were comparing the wrong category names, so we were effectively never making use of a "is2DCategory" and "is3DCategory" check. More digging also uncovered some bugs with how we parsed depth (see below for breakdown of what was happening and what's changing), and with how …
=> Fix: address bugs with isHangable [FX-3950]

_schemaV2.graphql, src/schema/v2/__tests__/reverseImageSearch.test.ts, src/schema/v2/reverseImageSearch.ts
Jira ticket [FX-3940]
Define an artwork subfield under each result, backed by a Gravity loader to fetch artwork details.
```graphql
{
reverseImageSearch(image: $file) {
results {
artwork {
href
internalID
}
}
}
}
```
* Given an image is indexed to TinEye
* When I query for the image using what should be a match
* Then I get back some results
* And I can fetch the corresponding artwork for each match
https://user-images.githubusercontent.com/3513494/168045437-505ca98c-de49-4917-b7d7-f9942cb498a2.mp4
[FX-3940]: https://artsyproduct.atlassian.net/browse/FX-3940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-3940): query for an artwork within a tineye match

_schemaV2.graphql, src/lib/__tests__/apis/fetch.test.ts, src/lib/apis/fetch.ts, src/schema/v2/me/delete_account_mutation.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4152
Add an optional `password` field to account deletion mutation.
After this we will update clients (e.g. Force) to require user password when deleting account. After that we will come back here to make `password` field required for the mutation.
(see similar [PR](https://github.com/artsy/gravity/pull/15289) for gravity)
=> feat: accept password for account deletion

_schemaV2.graphql, src/lib/stitching/exchange/v2/stitching.ts
Solves: [NX-3138](https://artsyproduct.atlassian.net/browse/NX-3138)
Added Conversation to CommerceBuyOrder that was causing issues for the "Purchase" cta redirection in Conversations.
=> fix(NX-3138): add conversation to CommerceBuyOrder in stitching

_schemaV2.graphql
Over on #4066 I made an argument non-null and then forgot to dump the schema again - this PR gets us back in working order.
/cc @starsirius
=> Dump latest schema

src/schema/v2/me/__tests__/myCollection.test.ts, src/schema/v2/me/myCollection.ts
[Slack Thread](https://artsy.slack.com/archives/C01B2P6LJUU/p1652404071482149)
This change prevents the My Collection connection query from failing if the list of artworks contains an artwork without an artist. Since we do not validate the presence of artists, this case is to be expected.
=> fix: Allow My Collection artworks without artist

.circleci/config.yml, scripts/ensure-schema-update.sh
Surfaced (but not directly related to) this [thread](https://artsy.slack.com/archives/C02BC3HEJ/p1652989950505809), we currently use a [git pre-commit hook](https://github.com/artsy/metaphysics/blob/21698481018fa8e3b4d7f2df0daf8d8f2d308f72/package.json#L166) to update the schema, but we don't have a corresponding check/block on CI. It's possible the hook is skipped and outdated schema lands in the main branch.
This introduces a new schema check on CI for PRs, and blocks merge when schema is not up-to-date.
=> chore: check schema drift on CI

src/schema/v2/me/__tests__/myBids.test.ts, src/schema/v2/me/myBids.ts
This was a bug from a large refactor of this schema back in https://github.com/artsy/metaphysics/pull/3714
The shape of the `lotStanding` being destructured in the function is slightly different than what it was doing, and so `sale_artwork` was always `null`. That is the `null` that winds up being evaluated (`sale_artwork.reserve_status`) a few lines down only when the sale is closed.
[This](https://github.com/artsy/gravity/blob/0c998ec21a4f373dbc042159d0ff7f6b41349735/app/services/lot_standing_service.rb#L37-L42) is the object from Gravity that is being used for `lotStanding` here.
Closes [BID-395]
[BID-395]: https://artsyproduct.atlassian.net/browse/BID-395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: correct shape for lot standings to properly return sold status after sale is closed

_schemaV2.graphql, src/lib/loadBatchPriceInsights.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/me/myCollection.ts
This PR adds `hasMarketPriceInsights` to the artwork model.
=> feat: add has market price insights flag to the artwork model

_schemaV2.graphql, src/schema/v2/fields/hybridConnection/hybridConnectionFromArraySlice.ts, src/schema/v2/me/conversation/eventConnection/orderEvents.ts
This is a PR to fix some bugs I discovered with @lilyfromseattle during implementation of this new hybrid relay connection in force. So far we've identified:
- a nasty bug due to a bad sorting method which led to us not giving the correct subset of order events on long conversations
- totalCount was missing in the result
- bad typing on our `offerEvent.offer.respondsTo` object - this wasn't needed since we only have to determine whether it is present for the `isCounter` property. **This is a breaking change to our schema, but the field has never been used in production.**
This has been really difficult to test in development, so we aren't yet 100% certain the current changes are enough to render conversations.
=> fix: minor bugs in [still unused] hybrid conversation/order event connection

src/schema/v2/article/index.ts
Apparently a few legacy articles have unsupported section types like "slideshow" — this filters those out (which is what the front end is currently doing)
=> fix(article): filters out unsupported section types

_schemaV2.graphql, src/lib/attributionClasses.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/attributionClass.ts
[NX-3129]
Adds `shortArrayDescription` to the `attributionClass` of the `Artwork`.
The same info as `shortDescription` but broken down as an array.
[NX-3129]: https://artsyproduct.atlassian.net/browse/NX-3129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(NX-3129): add shortArrayDescription to attributionClass of artwork

_schema.graphql, _schemaV2.graphql, src/data/exchange.graphql
Addresses: https://artsyproduct.atlassian.net/browse/PX-5023
Exposes new field for shipping quotes to map the correct currency from the database to the UI: 
https://github.com/artsy/exchange/pull/1185/files
Additional details in pr above ^
=> (fix: px-5023) Surface currencyCode field on ShippingQuote interface

_schemaV2.graphql, src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/index.ts
This adds a new `status` argument that can be passed down when fetching sale artworks.
Additionally, the existing pagination used `sale.eigible_sale_artworks_count` as the 'total count' to construct pagination options. I decided to leave that alone (gremlins may be there?!), and add in the more typical 'total count for that particular API request from the "x-total-count" header' only when the `status` argument is present.
=> chore: add support for a `status` argument for sale artworks and tigthen up pagination

src/lib/loaders/loaders_with_authentication/gravity.ts, src/lib/loaders/loaders_without_authentication/gravity.ts, src/schema/v2/__tests__/startIdentityVerificationMutation.test.ts, src/schema/v2/startIdentityVerificationMutation.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4203
Similar to https://github.com/artsy/metaphysics/pull/4117, this PR allows unauthenticated mutation to start identity verification. This is in support of [this ticket](https://artsyproduct.atlassian.net/browse/PLATFORM-4165) and this [Force PR](https://github.com/artsy/force/pull/10263) to allow unauthenticated users to start identity verification process. These changes should be merged before the Force changes.
* moves `startIdentityVerificationLoader` into `loaders_without_authentication`
* instead of returning an error when loader not available, return null
* update tests to reflect changes
=> feat: start identity verification without authenticating

_schemaV2.graphql, src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/index.ts
Doing [this](https://github.com/artsy/metaphysics/pull/4128) for a different field.
It turns out that the `saleArtworksConnection` under `Sale` is a different type than the root `saleArtworksConnection`, and does _not_ implement the `ArtworkConnectionInterface` needed to use Force's `ArtworkGrid` component.
So!
Decided to use `artworksConnection` field instead, which being an artworks connection already _does_ implement `ArtworkConnectionInterface`.
I probably should have used this field in the first place, but I'm not reverting https://github.com/artsy/metaphysics/pull/4128 as it's an improvement anyhow.
=> chore: add support for a `status` argument to `artworksConnection` under `Sale` type

_schemaV2.graphql, src/schema/v2/__tests__/identityVerification.test.ts, src/schema/v2/identityVerification.ts
https://artsy.slack.com/archives/CA8SANW3W/p1654889772383309
Expose `created_at` for these types:
- `IdentityVerification`
- `IdentityVerificationScanReference`
So the info can be displayed in Forque.
=> feat: expose created_at for IdentityVerification types.

_schemaV2.graphql, src/lib/loaders/api/loader_without_cache_factory.ts, src/lib/loaders/loaders_without_authentication/gravity.ts, src/schema/v2/sale/__tests__/index.test.ts, src/schema/v2/sale/index.ts
This adds `isLotsClosing` , which is an attribute that is nice to have since we will be forking based on this in the UI (when true, leads to a different exp. on the auction page), it's pretty self-explanatory + tests.
This also adds an uncached loader, which is opt-in to use, in order to fetch sale artworks. Logged-in users automatically use the same-named loader which skips the cache, this is more for logged-out users.
I added it as a new loader with opt-in functionality to still keep the benefit of MP throttling of backend requests for logged-out users, which _might_ be an over-optimization, but why not!
=> feat: add isLotsClosing to Sale, and also let an uncached loader be used to fetch sale artworks

src/schema/v2/asset_uploads/create_asset_request_mutation.ts, src/schema/v2/asset_uploads/finalize_asset_mutation.ts
This PR fixes image uploading on the submission flow. The error was caused after updating `loader_without_cache_factory` [here](https://github.com/artsy/metaphysics/pull/4141/files), updated loader returns an object that contains `body` field if the loader receives `headers`. Since [Gemini loaders use the headers](https://github.com/artsy/metaphysics/blob/0e7202ed5899e9dee465ddded88950138ee7e5f3/src/lib/loaders/loaders_without_authentication/gemini.ts#L16-L18) we got this error.
Integrity error - https://artsy.slack.com/archives/C02B4Q2TKGW/p1655107547276509
=> fix: image uploading on the submission flow

_schemaV2.graphql, src/schema/v2/admin/index.ts
No need to assign an `id` to admin field.
=> fix(admin): remove unnecessary global id

_schemaV2.graphql, src/schema/v2/admin/mutations/createFeatureFlagMutation.ts, src/schema/v2/admin/mutations/updateFeatureFlagMutation.ts
Since all we're doing is creating and updating main list, no need to return individual feature flags on create or edit mutation for now.
=> fix(feature-flag): simplify create / update mutations

_schemaV2.graphql, src/schema/v2/__tests__/identityVerification.test.ts, src/schema/v2/identityVerification.ts
Supports https://artsyproduct.atlassian.net/browse/PLATFORM-4199
Forque's List view [shall show](https://excalidraw.com/#room=f29b1c531adfce1cee60,o1Kx52ea3VotetP6dsal6A) `name` and `email` columns in top-level row.
=> feat: add creator email field to identity verification overrides type

_schemaV2.graphql, src/schema/v2/artist/__tests__/insights.test.ts, src/schema/v2/artist/insights.ts
The type of PR is: feat (plus a little bit of refactoring)
The goal of this PR is to do some refactoring to the Artist insights schema design to allow for querying on the frontend for insights based on the type that is needed. Overall, we wanna make Force as ignorant as possible of the data pipeline. 
Here's an example of a query for insights based on the new setup:
=> feat(artist-insights): make metaphysics single source of truth for querying artist insights

yarn.lock
Updates the transitive dep `ansi-regex` to the latest patch versions.
=> chore(deps): bump ansi-regex

package.json, yarn.lock
This PR bumps `node-fetch` from `2.6.1` to `2.6.7`
=> chore: bump-node-fetch

_schemaV2.graphql, src/lib/loadBatchPriceInsights.ts, src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/myCollection.test.ts, src/schema/v2/me/myCollection.ts
Addresses [CX-2503]
🔴 Depends on https://github.com/artsy/vortex/pull/473
In order to get the most recent price insight updates for My Collection artworks, this PR adds the argument `sortedByMostRecentInsightUpdates` to `myCollectionConnection`. If this argument is provided, the resolver fetches all (limited to 100) artworks from the user's collection and sorts them by the most recent price insight update (which comes from **Vortex**).
```graphql
{ 
me {
myCollectionConnection(first: 18, sortByLastAuctionResultDate: true) {
edges {
node {
medium
artist {
name
}
marketPriceInsights {
demandRank
annualValueSoldCents
annualLotsSold
lastAuctionResultDate
}
}
}
}
}
}
```
[CX-2503]: https://artsyproduct.atlassian.net/browse/CX-2503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> feat: Add sorting by most recent insight update to My Collection artwork connection

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/artists/__tests__/mergeArtistsMutation.test.ts, src/schema/v2/artists/mergeArtistsMutation.ts, src/schema/v2/schema.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4225
This adds a `mergeArtist` mutation that sends the artist merger request up to Gravity and returns the response
- In the success case, this will be the artist record that was retained and updated
- In the error case, we implement the typical [data-or-errors union pattern](https://artsy.github.io/blog/2018/10/19/where-art-thou-my-error/). (For this to work, we will require a tweak to the `api/v1/artists/merge` endpoint in Gravity, which is in https://github.com/artsy/gravity/pull/15454)
=> feat(artist dupes): wire up artist merger mutation to Gravity

_schemaV2.graphql, src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/myCollection.test.ts
This PR adds `averageSalePriceDisplayText` (display price text in USD) to artwork market price insights.
```graphql
{
me {
myCollectionConnection(first: 10) {
edges {
node {
medium
artist {
name
}
marketPriceInsights {
averageSalePriceDisplayText
}
}
}
}
}
}
```
```
{
"data": {
"me": {
"myCollectionConnection": {
"edges": [
{
"node": {
"marketPriceInsights": {
"averageSalePriceDisplayText": "US$1,019"
}
}
}
]
}
}
}
}
```
=> feat: Add averageSalePriceDisplayText to artwork market price insights

_schemaV2.graphql, src/schema/v2/me/__tests__/myCollection.test.ts, src/schema/v2/me/myCollection.ts
Return uniq artworks when passing `sortByLastAuctionResultDate` to the My Collection artwork connection.
[Slack Thread](https://artsy.slack.com/archives/C01B2P6LJUU/p1655801368386259)
=> fix: Return uniq artworks when passing sortByLastAuctionResultDate to My Collection

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
Addresses this bug: https://artsyproduct.atlassian.net/browse/PX-5094
MP's `onlyShipsDomestically` field was only checking flat rate shipping fees to determine if an artwork could be shipping domestically vs internationally.
This was causing users to not be able to check out adding a new `NEW` address if the work was international artsy shipping enabled but had a domestic shipping fee cent value
The form would lock and not allow international addresses to be added by collectors:
=> fix: (PX-5094) account for artsy shipping logic in onlyShipsDomestically function

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
Because `figures` and `images` were ordered differently, we were getting some buggy behavior on Force where clicking an image would take you to a different image's deep zoom view.
This PR should fix the problem by introducing the same sorting and normalization to images in `figures` as in `images`.
[Slack context](https://artsy.slack.com/archives/C2TQ4PT8R/p1656063626023679)
=> fix: sort figures the same way as images

_schemaV2.graphql, src/schema/v2/artists/__tests__/mergeArtistsMutation.test.ts, src/schema/v2/artists/mergeArtistsMutation.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4228
This is one of three PRs to enable the [field-level overrides](https://user-images.githubusercontent.com/140521/149867535-309f46de-dfe8-4add-99ca-42f59c2869af.gif) that are a feature of the new deduping UI.
Gravity: https://github.com/artsy/gravity/pull/15477 
👉🏽 Metaphysics: https://github.com/artsy/metaphysics/pull/4189
Forque: https://github.com/artsy/forque/pull/256
This mostly just declares the overridable fields that can be passed through to Gravity, in a query such as:
```graphql
mutation {
mergeArtists(
input: {
goodId: "62a89de6bbce14000c2968fc"
badIds: ["62a89f0647f3e7000ebe9232"]
overrides: {
birthday: "62a89f0647f3e7000ebe9232"
deathday: "62a89f0647f3e7000ebe9232"
}
}
)
}
```
And it adds some light inline documentation:
=> feat(artist dupes): enable field-level overrides when merging

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
Following up with the European Union shipping zone after the release of Artsy Shipping
=> fix: Replace Continental Europe with European Union

src/schema/v2/me/myCollectionInfo.ts
We need to pass the user ID to the `myCollectionInfo` context to then pass it as an argument to the `collectedArtistsConnection` loader.
This avoids the following error:
=> fix: Pass user ID to myCollectionInfo context

_schemaV2.graphql, src/schema/v2/artist/insights.ts
Addresses [CX-2644]
Adds a `count` field to artist insights to be able to check which artist has which insights without loading all the insights when fetching My Collection insights
--------
We'll be able to fetch artist insights like this:
```
{
me {
myCollectionInfo {
collectedArtistsConnection(first: $first) {
edges {
node {
name
insights(
kind: [SOLO_SHOW, GROUP_SHOW, COLLECTED, REVIEWED, BIENNIAL]
) {
kind
count
}
}
}
}
}
}
}
```
[CX-2644]: https://artsyproduct.atlassian.net/browse/CX-2644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add count to artist insights

src/schema/v2/artist/__tests__/index.test.js, src/schema/v2/artist/index.ts
Addresses [CX-2654]
Follow-Up PR for https://github.com/artsy/metaphysics/pull/4205
Don't filter out auction results without `sale_end_date.`
[CX-2654]: https://artsyproduct.atlassian.net/browse/CX-2654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Don't filter out auction results without sale_end_date

_schemaV2.graphql, src/schema/v2/artist/insights.ts, src/schema/v2/me/__tests__/myCollectionInfo.test.ts, src/schema/v2/me/myCollectionAuctionResults.ts, src/schema/v2/me/myCollectionInfo.ts
Addresses [CX-2644]
Depends on https://github.com/artsy/gravity/pull/15493
Introduces new My Collection artist insights field (`artistInsights`) that returns insights for all collected artists by kind.
```graphql
{
me {
myCollectionInfo {
artistInsights(kind: COLLECTED) {
artist {
name
}
kind
type
label
entities
}
}
}
}
```
```
{
"data": {
"me": {
"myCollectionInfo": {
"active_secondary_market": [
{
"kind": "ACTIVE_SECONDARY_MARKET",
"label": "Active Secondary Market",
"artist": {
"name": "Banksy"
}
},
{
"kind": "ACTIVE_SECONDARY_MARKET",
"label": "Active Secondary Market",
"artist": {
"name": "Joan Miró"
}
}
}
}
}
}
}
```
[CX-2644]: https://artsyproduct.atlassian.net/browse/CX-2644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Introduce My Collection artist insights

_schemaV2.graphql, src/schema/v2/Match.ts, src/schema/v2/schema.ts
So it turns out that the `searchConnection` field has some problems that make it unusable for particular kinds of UI.
It exposes a union on _some_ of its types. But you can't really use those types since named fragments aren't supported. And just using the common interface isn't workable since we can't use existing UI with those.
The solution is to expose a simpler field that just takes the results, loads the records, and simply exposes a union of them. This works as you'd expect it to and makes it simple to use existing pieces of UI. (Let's say you wanted to search for artists and then load one of our standard artist card components: couldn't do that with `searchConnection`, can do that with `match`/`matchConnection`.
=> feat(schema): exposes match fields

_schema.graphql, _schemaV2.graphql, src/data/exchange.graphql
https://artsyproduct.atlassian.net/browse/TX-440
This should be merged after https://github.com/artsy/exchange/pull/1245.
This updates the schema for the new `oneTimeUse` argument added in Exchange.
=> [Coordinated merge] Update schema to support one time use payment for bank accounts

_schemaV2.graphql, src/schema/v2/schema.ts
This re-enables profile as a top-level field, which is needed in Force to handle the legacy top-level path redirects.
=> feat(schema): re-enables profiles

_schemaV2.graphql, src/schema/v2/artworksForUser/artworksForUser.ts, src/schema/v2/artworksForUser/helpers.ts
This PR updates MP to be in sync with the new field on new for you recs. While I was at it I extracted some locals so that when optional values are not passed then they shouldn't appear in the query at all. (h/t @dzucconi on that one)
=> Add version to artworks for user

src/schema/v2/artworksForUser/helpers.ts
Without this `batched` flag the list of artwork ids will get shuffled - not sure why! Anyway this fixes the ordering problem we saw yesterday!
/cc @artsy/grow-devs @joeyAghion
=> Order of artworks should match what's passed in

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/partnerShowDocumentsConnection.test.ts, src/schema/v2/partnerShowDocumentsConnection.ts, src/schema/v2/schema.ts
Jira ticket: https://artsyproduct.atlassian.net/browse/MOPLAT-306
```graphql
{
partnerShowDocumentsConnection(
showID: "showID"
partnerID: "partnerID"
first: 10
) {
edges {
node {
title
filename
size
}
}
}
}
```
```graphql
{
"partnerShowDocumentsConnection": {
"edges": [
{
"node": {
"title": "2000",
"filename": "2000.jpeg",
"size": 226862
}
}
]
}
}
```
=> feat(MOPLAT-306): add `partnerShowDocumentsConnection` field

yarn.lock
tiny tiny update to get rid of the message
```
$ node scripts/dump-staging-schema.js
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
=> can i use update

_schemaV2.graphql, src/schema/v2/me/__tests__/myCollectionInfo.test.ts, src/schema/v2/me/myCollectionInfo.ts
This PR resolves [CX-2670]
This PR adds a count for the insights kinds for the artists inside my collection
- Query:
```graphql
query {
me {
myCollectionInfo {
artistInsightsCount {
activeSecondaryMarketCount
biennialCount
groupShowCount
collectedCount
soloShowCount
reviewedCount
}
}
}
}
```
- Response
```json
{
"data": {
"me": {
"myCollectionInfo": {
"artistInsightsCount": {
"activeSecondaryMarketCount": 5,
"biennialCount": 1,
"groupShowCount": 0,
"collectedCount": 2,
"soloShowCount": 0,
"reviewedCount": 2
}
}
}
}
}
```
[CX-2670]: https://artsyproduct.atlassian.net/browse/CX-2670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat: add my collection artist insights count endpoint

_schemaV2.graphql, src/schema/v2/__tests__/partnerArtistDocumentsConnection.test.ts, src/schema/v2/__tests__/partnerShowDocumentsConnection.test.ts, src/schema/v2/partnerArtistDocumentsConnection.ts, src/schema/v2/partnerShowDocumentsConnection.ts
Jira ticket: https://artsyproduct.atlassian.net/browse/MOPLAT-305
Related PR: https://github.com/artsy/metaphysics/pull/4227, https://github.com/artsy/metaphysics/pull/4230
More context you can find here: https://artsy.slack.com/archives/C02NAJ2CGLW/p1658411062552889
=> feat: add `publicUrl` field for partner artist and partner show documents

_schemaV2.graphql, src/schema/v2/me/completedOnboardingMutation.ts, src/schema/v2/schema.ts, src/schema/v2/user.ts
This adds a new `completedOnboarding` mutation:
```graphql
mutation {
completedOnboarding(input:{ userID:"58828b1e9c18db30f3002fba",, timestamp:"222"}) {
user {
completedOnboardingAt     
}
}
}
```
Related: https://github.com/artsy/gravity/pull/15544
=> feat(user): Add completedOnboardingAt mutation

_schemaV2.graphql, src/schema/v2/user.ts, src/schema/v2/users/updateUserMutation.ts
Turns out we don't need to add anything for `completedOnboarding` as we've already [got a mutation](https://github.com/artsy/metaphysics/blob/main/src/schema/v2/me/update_me_mutation.ts#L117-L120) setup that can handle this. 
cc @artsy/grow-devs
=> chore(user): Remove unused fields

src/schema/v2/sale/__tests__/index.test.ts
This test flakes a lot (takes enough time to run that even w/ the stubbing, the test sometimes prints "in a few seconds" instead of "in a minute"). Not worth keeping.
=> chore: remove flaky test

README.md, src/index.ts, src/test/supportedV2Routes.test.ts
Wanted to be a bit more explicit about how routes are handled for /v2.
This was prompted by a recent #dev-help question where someone was hitting "/api/v2" in Metaphysics, which matched the catch-all V1 route (!), and thus was actually running V1 with no complaints, which was of course quite confusing.
This tries to be a bit more explicit about the very limited set of valid paths we accept.
=> chore: update route handling of /v2 to be more explicit

_schemaV2.graphql, src/schema/v2/match/__tests__/artist.test.js, src/schema/v2/schema.ts
This is being used by Currents, so it's time to re-add this!
I recall some discussion about a more proper Relay/Next auto-complete for artist in Forque's dupe tool, but that winds up using Gravity directly (but side-note, the one in Currents seems like a decent auto-complete that uses Relay/GraphQL as an example)?
=> feat: re-add matchArtist to root

src/schema/v2/bulkUpdatePartnerArtworksMutation.ts
I introduced a breaking typo ("error" instead of "errors") when making changes requested in PR comments. My bad!
I also decided along with @ansor4 to mov the response formatting to the resolver.
=> Fix typos in bulk update mutation

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/vortex.ts, src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/myCollection.test.ts
Addresses [CX-2688]
Add `medianSalePriceDisplayText` to artwork price insights.
[CX-2688]: https://artsyproduct.atlassian.net/browse/CX-2688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add medianSalePriceDisplayText to artwork price insights

src/schema/v2/me/__tests__/myCollection.test.ts, src/schema/v2/me/myCollection.ts
We are filtering using the medium instead of the category and this results on the mediums displayed in the insights tab. 
After changes locally 
Note: the category is displayed twice because we run uniqWith also applied to medium, we will need to delete that in few weeks
=> fix(CX-2748): show category instead of medium

_schemaV2.graphql, package.json, src/lib/__tests__/formatLargeNumber.test.ts, src/lib/fillers/enrichArtworksWithPriceInsights.ts, src/lib/formatLargeNumber.ts, src/lib/ifFieldRequested.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/myCollection.test.ts, src/schema/v2/me/myCollection.ts, yarn.lock
The `marketPriceInsights` interface was broken for artwork and was always returning `null`. The problem was that there was no resolver supplied to it.
I also added some of the logic of the display that we need for the artist insights inside Force. The next step will be to use those new field in Eigen since Eigen is now doing that logic locally.
**Jira ticket:** https://artsyproduct.atlassian.net/browse/CX-2768
=> feat: add marketPriceInsights to the artwork interface

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/vortex.ts, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
This PR adds the missing fields needed for the artist market insights to the artwork market insights interface
=> feat: return the sell through rate and median sale over estimate percentage

_schemaV2.graphql, src/lib/__tests__/getDemandRank.test.ts, src/lib/getDemandRank.ts, src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/myCollection.test.ts
This PR adds `demandRankDisplayText` to the artwork price insights
- Query 
```graphql
query {
artwork(id: "artwork-id") {
artistNames
title
marketPriceInsights {
demandRank
demandRankDisplayText
}
}
}
```
- Result
```json
{
"data": {
"artwork": {
"artistNames": "FamousArtist",
"title": "CoolWork",
"marketPriceInsights": {
"demandRank": 0.877,
"demandRankDisplayText": "Active Demand"
}
}
}
}
```
=> feat: Add demandRankDisplayText to Artwork Price Insights

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
This PR adds `isHighDemand` flag to the market price insights flag. The goal from this PR is to make sure we are safe in case the value for what's in high demand changes in the future.
**Bonus:** I alphabetically sorted the interface before it gets messier.
=> chore: add is high demand flag to the artwork market price insights

_schemaV2.graphql, src/schema/v2/notifications/__tests__/index.test.ts, src/schema/v2/notifications/index.ts, src/schema/v2/schema.ts
Spike on exposing notifications via notificationsConnection query field.
cc/ @evaschilken @nickskalkin 
**Query**
```graphql
{
notificationsConnection(first: 1) {
edges {
node {
internalID
title
message
createdAt
isUnread
targetHref
artworksConnection(first: 5) {
edges {
node {
title
}
}
}
}
}
}
}
```
**Response**
```json
{
"data": {
"notificationsConnection": {
"edges": [
{
"node": {
"internalID": "62fe270e071fb90007594c12",
"title": "Gina Beavers",
"message": "1 Work Added",
"createdAt": "2022-08-18T11:48:30.000Z",
"isUnread": true,
"targetHref": "/artist/damien-hirst/works-for-sale",
"edges": [
{
"node": {
"title": "Florescent Lip"
}
}
]
}
}
}
]
}
}
}
```
```
=> feat: expose notificationsConnection using existing /feed structure

src/schema/v2/notifications/__tests__/index.test.ts, src/schema/v2/notifications/index.ts
Initial PR: artsy/metaphysics#4316
Small changes that allow to return the correct value of `totalCount`
=> chore: expose `totalCount` field for `notificationsConnection`

_schemaV2.graphql, src/schema/v2/shortcut.ts
Currently, if you query MP for a shortcut that doesn't exist, MP actually returns a 500 status code! However, GraphiQL kind of looks correct w an `errors` body (which is somewhat confusing!)
Additionally, there's a middleware to handle redirects in Force which makes this query, can cause a 500 behind a `try/catch` (so this wasn't affecting users or an unhandled exception within Force). That's in https://github.com/artsy/force/blob/d61e77ee76e7847f7168f921b2fa2808deeb20c6/src/Apps/Redirects/redirectsServerRoutes.tsx#L30-L39
This redirect is mounted fairly high in our middleware stack, and based on functionality, seems like it could actually move to the bottom of our middleware (saving lots of 'shortcut not found' requests) - that's a separate Force update. Adding it fairly high in the …
=> feat: relax typing when shortcuts dont exist

hokusai/staging.yml
The type of this PR is: Feat
This PR solves PLATFORM-4514
Part of spike on using AWS Spot instances.
Follows https://github.com/artsy/metaphysics/pull/4341
Spot tiers were [tainted](https://github.com/artsy/substance/pull/285) with `reserved=spot:NoSchedule`. Now for any deployment we want to run on Spot, we must add a [toleration](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/). Adding that for `web` deployment.
=> feat: staging to tolerate spot instance taint.

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/CollectorProfile/collectorProfile.ts, src/schema/v2/__tests__/user.test.ts, src/schema/v2/me/userInterests.ts, src/schema/v2/user.ts, src/schema/v2/userInterests.ts
This adds a new `interestsConnection` field under a `User`, without being scoped to `me` and using the admin endpoint.
It also adjusts the schema to store some of the 'join' data between a user and the interest on the edge, so the nodes stay as meaningful entities.
=> feat: add interestsConnection under User

src/schema/v2/image/__tests__/index.test.js, src/schema/v2/image/index.ts
Addresses [CX-2854]
In cases when no geometry is provided for an image, we return a square image by default. This PR fixes the placeholder field that was returning "NaN%" instead of "100%" if the original image width and height are `0`.
The placeholder is important to correctly display the images in the frontend. Without this value being set correctly, My Collection images are not displayed correctly shortly after an artwork has been created.
[CX-2854]: https://artsyproduct.atlassian.net/browse/CX-2854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Return image square placeholder when no geometry is provided

_schemaV2.graphql, src/data/vortex.graphql, src/schema/v2/artworksForUser/artworksForUser.ts, src/schema/v2/artworksForUser/helpers.ts
This commit threads a new argument to an underlying Vortex query field. The backfill logic doesn't currently respect this argument.
cc/ @olerichter00 @jonallured
=> feat: expose maxWorksPerArtist arg for artworksForUser

src/schema/v2/artworksForUser/helpers.ts
The first iteration had a couple problems:
- Name was mistyped as `maxWorksPerUser`
- The integer value was incorrectly quoted
Testing this against staging was difficult but I was eventually able to generate the appropriate `VORTEX_TOKEN` to test against production data which helped surface these issues.
```ruby
subject = ClientApplication.find_by(name: "Metaphysics")
app = ClientApplication.find_by(name: "vortex-production")
ApplicationTrust.create_for_token_authentication(mp, subject_application: app)
```
=> fix: correctly thread maxWorksPerArtist arg to newForYouRecommendations

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts
This PR adds a field on the user schema to return `follows` connections. In this PR we expose two `connections` under a `follows` field, which leverage the existing `connection` types of `genesConnection` and `artistsConnection`.
We also add the following loaders:
1. `userArtistFollowsLoader`
2. `userGeneFollowsLoader`
This work supports the migration of the `Users` page of `admin.artsy.net` to `tools.artsy.net`.
[PLATFORM-4434]
[PLATFORM-4434]: https://artsyproduct.atlassian.net/browse/PLATFORM-4434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add user follows

_schemaV2.graphql, src/schema/v2/__tests__/user.test.ts, src/schema/v2/object_identification.ts, src/schema/v2/user.ts
This lets some conventional refetching within `User` (of a particular tab showing Forque data in https://github.com/artsy/forque/pull/375#discussion_r965208250) start happening.
> The @refetchable directive can only be added to fragments that are "refetchable", that is, on fragments that are declared on Viewer or Query types, or on a type that implements Node (i.e. a type that has an id).
from https://relay.dev/docs/api-reference/use-refetchable-fragment/
On my machine, running Forque pointing to my local Metaphysics running this code, and everything is 👌
=> feat: let User type implement NodeInterface in order for refetchability

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/CollectorProfile/collectorProfile.ts, src/schema/v2/__tests__/user.test.ts, src/schema/v2/me/__tests__/collector_profile.test.js, src/schema/v2/me/index.ts, src/schema/v2/user.ts
This addresses the bug where the data for `collectorProfile` reflected a 'me'-style API call, vs. that user's data. This updates the existing `collectorProfileLoader` to be called `meCollectorProfileLoader` (since that's what it does), and adds a new `collectorProfilesLoader`.
The partner-inbox query for an order should be able to get the proper data querying this field.
=> fix: update collectorProfile field on User to reflect that user's profile, vs. the requesting user

src/schema/v2/__tests__/reverseImageSearch.test.ts, src/schema/v2/reverseImageSearch.ts
https://artsyproduct.atlassian.net/browse/FX-4202
Follow-up to https://github.com/artsy/metaphysics/pull/4369
The recent change to the convention for the TinEye filepath that we use as an identifier…
|which version|filepath convention|
|---|---|
|old|`artwork/<artwork id>/image/<image token>`|
|new|`<current env>/artwork/<artwork id>/image/<image token>`|
…means that we need to change the way we parse that identifier in order to extract the artwork id — it's now the third segment in that path, not the second.
There wasn't an existing test to catch that, which is why it slipped through #4369 and resulted in broken image matching.
This PR adds the test and updates the implementation.
=> fix(reverse image search): parsing of TinEye artwork result

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts, src/schema/v2/userInquiredArtworks.ts
Exposes a connection of artworks, with inquiry data along the edge (pretty much like lots of these other connections we've been adding). This should be enough to power the Forque UI ('Inquiries' tab for user management) and can be built upon further if needed.
=> feat: add inquiredArtworksConnection to User

_schemaV2.graphql, src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts, src/schema/v2/userInterests.ts
Easy one! I forgot about this when working on user interests - this adds the proper plumbing for our pagination components.
The other place in Forque to add proper pagination to, user follows, already fully supports the pagination schema (on the MP side).
=> chore: add proper pagination support to user interests

_schemaV2.graphql, src/schema/v2/gene.ts
This was using the proper resolver (so I assumed pagination was working with a genes connection), but the type definition didn't have the right schema.
=> fix: proper schema for pagination on GenesConnection

hokusai/production.yml, hokusai/staging.yml
[PLATFORM-4571]
Staging [has been partly run on Spot nodes](https://github.com/artsy/metaphysics/pull/4341) for a while. I haven't heard of any problems. This PR spikes Prod on Spot.
- Allow pods in Prod to run on Spot nodes.
- Don't let pods run in `api` tier anymore. (as having affinity for 3 tiers, including spot, seems too complicated.)
And (as [done for Gravity](https://github.com/artsy/gravity/pull/15646)):
- Remove topologySpreadConstraints in Staging.
[PLATFORM-4571]: https://artsyproduct.atlassian.net/browse/PLATFORM-4571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: allow prod to run on spot

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/mark_all_notifications_as_read_mutation.test.ts, src/schema/v2/me/mark_all_notifications_as_read_mutation.ts, src/schema/v2/schema.ts
Jira ticket: [FX-4181]
```graphql
mutation {
markAllNotificationsAsRead(input: {}) {
... on MarkAllNotificationsAsReadSuccess {
success
}
... on MarkAllNotificationsAsReadFailure {
error
}
}
}
}
}
```
```graphql
markAllNotificationsAsRead: {
responseOrError: {
success: true
}
}
```
```graphql
{
"mutationError": {
"error": "...",
"message": "..."
...
}
}
}
```
```javascript
{
"data": {
"markAllNotificationsAsRead": {
"success": true
}
}
},
"requests": {
"gravity": {
"requests": {
"me/notifications?status=read": {
"time": "0s 524.472ms",
"cache": false,
"length": "0 B"
}
}
}
},
"requestID": "6d1956a0-34dc-11ed-94de-1dd82adc179a"
}
}
```
[FX-4181]: …
=> feat(FX-4181): Create a mutation to mark all unread notifications as read

hokusai/production.yml
Missed this config in https://github.com/artsy/metaphysics/pull/4383
=> fix: for prod, add toleration for spot node taint

_schemaV2.graphql, src/schema/v2/notifications/index.ts
Adds some rough support to recognize ViewingRoomPublishedActivity events separate from the other two currently recognized.
We should move the type and targetHref awareness over to the modeling in Gravity and stop doing this in Metaphysics though.
Example of the notification payload via Gravity's API:
```json
{
"feed": [
{
"actors": "Commerce Test Partner",
"message": "1 Viewing Room Published",
"status": "unread",
"date": "2022-09-16T12:45:53.000Z",
"object": {
"id": "cbf1888e-47f6-40e0-ac9d-162041004045",
"start_at": "2022-09-15T14:30:00.000Z",
"end_at": "2022-10-14T14:30:00.000Z",
"title": "Matt tests image uploads"
},
"object_ids": [
"cbf1888e-47f6-40e0-ac9d-162041004045"
],
"id": "6324700153b5930007e6c0eb"
}
],
"total_unread": 1,
"total": 1
}
```
=> feat: recognize ViewingRoomPublishedActivity events

src/schema/v2/show_event.ts
There's a pattern in the way Force and MP work together where times can appear in a user's local timezone when rendered client side. The way this works in MP is via a header called `X-Timezone` - it's value is available to resolver functions and there's also a default.
To complete that thought here's how that's set client side in Force:
https://github.com/artsy/force/blob/22fb4e1451302b0ddf1a009b5fb873110ce0293f/src/System/Relay/createRelaySSREnvironment.ts#L84-L85
So anyway all this PR does is pluck these timezone values out of the arguments passed to the resolver and then sends them down to the date formatting function rather than hard-coding UTC.
https://artsyproduct.atlassian.net/browse/GRO-1024
=> feat: Respect timezones for event time ranges GRO-1024

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/__tests__/comparableAuctionResults.test.ts, src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/newWorksByInterestingArtists.test.ts
Removing `unlisted` field on `artwork` and the `includeUnlisted` argument on the `artwork` field.
Basically reverting [this PR](https://github.com/artsy/metaphysics/pull/2428)
-----------------------------
Expected failure when querying with`includeUnlisted` param
Expected failure when querying for `unlisted` field
A successful query
=> chore(PX-5236): remove unlisted and includeUnlisted

_schemaV2.graphql, src/schema/v2/bank_account.ts, src/schema/v2/me/bank_accounts.test.ts, src/schema/v2/me/bank_accounts.ts
This PR adds `type` field to the bank accounts query(argument and field at response) to filter bank accounts by ACH or SEPA.
JIRA - [TX-555]
[TX-555]: https://artsyproduct.atlassian.net/browse/TX-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: allow filtering bank accounts by the bank account type

_schemaV2.graphql, src/schema/v2/users/updateUserSaleProfileMutation.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4588
This change adds the `requireBidderApproval` field to the existing `updateUserSaleProfileMutation` mutation to allow toggling of that field from the Forque users' view.
=> feat: add requireBidderApproval field to updateUserSaleProfileMutation

_schemaV2.graphql, src/schema/v2/artist/__tests__/helpers.test.ts, src/schema/v2/artist/__tests__/insights.test.ts, src/schema/v2/artist/helpers.ts, src/schema/v2/artist/insights.ts, src/schema/v2/me/myCollectionInfo.ts
This PR moves calculating an artist's high auction record up into MP from Force. Right now this is done like here:
https://github.com/artsy/force/blob/9fb0f70c7abda2db06a79d80d4a77dea68c53334/src/Apps/Artist/Components/ArtistInsights/ArtistInsightBadges.tsx#L75
I think this is better because it pulls logic out of the client which is always a win but it also makes the mental model easier: if you want insights they are on the `artist.insights` field full stop. No more having to think about where they are.
And so then this sets me up to add both critically acclaimed and Artsy vanguard as the next two artist insights. I'll follow up with that work as I get things in place.
https://artsyproduct.atlassian.net/browse/GRO-841
=> feat: Add high auction record to artist insights GRO-841

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
This PR adds visibility level to artwork per [PX-5249]. It also has a related [gravity ticket ](https://github.com/artsy/gravity/pull/15693)that needs to be merged first.
[PX-5249]: https://artsyproduct.atlassian.net/browse/PX-5249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore:add visibility level to artwork

_schemaV2.graphql, src/schema/v2/artist/helpers.ts, src/schema/v2/artist/index.ts
This PR updates the Artist schema to include two new artist insight fields from Gravity:
* criticallyAcclaimed
* vanguardYear
But then I also went to the insights field and updated that to use these fields to return the formatted bits and bobs. Once this is merged I can turn to Force and start in on that last piece of the puzzle.
https://artsyproduct.atlassian.net/browse/GRO-841
https://artsyproduct.atlassian.net/browse/GRO-916
=> feat: Support two new artist insights GRO-916

_schemaV2.graphql, src/schema/v2/__tests__/createUserAdminNoteMutation.test.ts, src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts, src/schema/v2/users/createUserAdminNoteMutation.ts
This PR does two things in support of [PLATFORM-4594]. 
1. It updates `createUserAdminNoteMutation` to use our `responseOrError` pattern.
2. It [sorts](https://github.com/artsy/metaphysics/compare/mc-jones/admin-note?expand=1#diff-53a08671c7ab0c03c56b68075478ab8b4b79e04a1c3f946e29aed49569a66abcR57) the admin notes in descending order.
TO-DO:
[PLATFORM-4594]: https://artsyproduct.atlassian.net/browse/PLATFORM-4594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: use responseOrError pattern for createUserAdminNoteMutation

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/lib/loaders/loaders_without_authentication/gravity.ts, src/schema/v2/__tests__/users.test.ts, src/schema/v2/match/__tests__/gene.test.js, src/schema/v2/match/gene.ts, src/schema/v2/users.ts
Depends on https://github.com/artsy/gravity/pull/15704 , which properly exposes the total count for a match query on users, so that we can have a properly paginated list of search results in Forque.
Since there's already a `usersConnection` root field, rather than add a separate field (`matchUsersConnection`?), which would likely be of the same type as `usersConnection` (namely, a connection where the `node` is a `User`), figured can add a `term` argument to the existing field, and then branch in the resolver based on that argument (perform a match API request, vs. the regular one).
Looks like:
=> feat: allow `term` argument to `usersConnection` root field, used to match users

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/deleteUserAdminNoteMutation.test.ts, src/schema/v2/schema.ts, src/schema/v2/users/deleteUserAdminNoteMutation.ts
This PR adds a loader and mutation to delete an admin note associated with a user. This will be used by `Forque` and supports the work to migrate the `User` app over from `Torque`. 
The `Gravity` endpoint is [here](https://github.com/artsy/gravity/blob/ef8cba1c109a005912af21dfdcda899125ba1b08/app/api/v1/users_admin_notes_endpoint.rb#L61).
[PLATFORM-4600]
[PLATFORM-4600]: https://artsyproduct.atlassian.net/browse/PLATFORM-4600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add deleteUserAdminNote mutation

_schemaV2.graphql, src/schema/v2/PartnerMatch.ts, src/schema/v2/__tests__/partner.test.js, src/schema/v2/partner.ts
As discussed, I re-used the existing artist/artwork/show connection types for match purposes, rather than creating new types.
Also, can use `paginationResolver` helper instead of having to do the weird dance of creating the proper paginated structure w/ cursor stuff.
Also, renamed the fields under `Partner` to get rid of the redundant `partner` prefix (this might be a breaking change to current development of Folio).
In terms of whether these fields need to even exist (or we can re-use the existing artist/artworks/shows connection that already exist under `Partner`) -> I'll leave that up to you to decide! I would be happy either way, just want to support y'all.
=> chore: dont create duplicate connection types, some tweaks to partner search naming

_schemaV2.graphql, src/schema/v2/article/models.ts, src/schema/v2/article/sections/ArticleSectionImageCollection.ts
If we fetch an unpublished artwork, it errors, so we assume it's unpublished and use the response that Writer has stored to display a stub of the artwork. In practice this works OK since all we need is the image and a credit.
=> fix(article): exposes unpublished artworks

src/schema/v2/artwork/index.ts, src/schema/v2/me/__tests__/myCollection.test.ts
We used cants as if it was dollars, which caused the Annual Value Sold to be 100 times bigger than it should be.
=> fix: divide value by 100 vo cut the cents

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts, src/schema/v2/userAccessibleProperties.ts
This depends on https://github.com/artsy/gravity/pull/15722 in order to properly resolve the data re: counts and all the cursor/pagination stuff.
Posted a screenshot in Slack (private data) to show the example schema.
This is in response to https://github.com/artsy/metaphysics/pull/4428
Essentially, rather than worrying about specifics of the current UI (wanting to link to a partner - which might change, now we want to show partner name, etc.), this adds support for a connection of accessible properties to `User`.
There isn't much info on the `edge`, and then the `node` is a union of the possible types that are currently in use:
```
> AccessControl.distinct(:property_type)
=> ["Artist", "Artwork", "Partner", "Profile"]
```
=> feat: add accessiblePropertiesConnection to User

_schemaV2.graphql, src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts, src/schema/v2/userSaleProfile.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4647
This depends on fields getting exposed in https://github.com/artsy/gravity/pull/15720
In support of ongoing work to improve user account management via https://tools.artsy.net, this PR exposes additional fields around email confirmation states and couple of minor fixes:
* adds `emailConfirmationSentAt` and `unconfirmedEmail` fields on _user schema_
* fixes `emailConfirmedAt` to resolve the correct field on _user schema_
* fixes `jobTitle` to resolve the correct field on _userSaleProfile_
=> feat: expose additional email confirmation related fields on user schema

src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4647
This fixes an oversight when resolving `unconfirmedEmail` field which was exposed on the `User` schema in https://github.com/artsy/metaphysics/pull/4435
=> fix: unconfirmedEmail field on User

hokusai/production.yml, hokusai/staging.yml
[PLATFORM-4614]
Follows https://github.com/artsy/metaphysics/pull/4389
Make web deployment prefer Spot tier, to maximize Spot usage. [Dashboard](https://app.datadoghq.com/dashboard/2n5-6tr-ypp/kubernetes-deployments?tpl_var_deployment%5B0%5D=metaphysics-web&tpl_var_hpa%5B0%5D=metaphysics-web&from_ts=1665066550292&to_ts=1665671350292&live=true) shows spot/on-demand distribution.
[PLATFORM-4614]: https://artsyproduct.atlassian.net/browse/PLATFORM-4614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: web deployment to prefer spot tier

src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/update_me_mutation.ts
Addresses [CX-2983]
In order to support adding images from a remote URL (not S3) to a My Collection artwork, this PR adds the functionality to the function that computes the image source. 
This PR prepares the endpoint for https://github.com/artsy/convection/pull/1348 and uses Gravity's optional parameter [remote_image_url](https://github.com/artsy/gravity/blob/bcf19fd80bc908a802191e80366685c346bc3f53/app/api/v1/artworks_images_endpoint.rb#L49) (`POST /api/v1/artwork/:artwork_id/image`)
[CX-2983]: https://artsyproduct.atlassian.net/browse/CX-2983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add support for remote images to My Collection artwork mutations

_schemaV2.graphql, src/schema/v2/artwork/index.ts
This PR adds some description to the artwork insights type to mention that it is not available for all artwork connections.
=> chore: add comment about the artwork price insights type

src/lib/stitching/gravity/v2/stitching.ts
Once curated marketing collections are launched, we can also update the collections in the app rail.
https://artsyproduct.atlassian.net/browse/FX-3981
=> feat[FX-3981]: update app home marketing collections

_schemaV2.graphql, src/schema/v2/notifications/__tests__/index.test.ts, src/schema/v2/notifications/index.ts
Jira ticket: [FX-4313]
Add a new field for [Notification](https://github.com/artsy/metaphysics/blob/main/src/schema/v2/notifications/index.ts#L34) type to be able to query a formatted date
* Formatted date labels
* `Today` when notification was published today
* `Yesterday` when notification was published yesterday
* `x days ago` when the notification was published 2 or more days ago
* It is necessary to take into account the user's time zone
[FX-4313]: https://artsyproduct.atlassian.net/browse/FX-4313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4313): Add the ability to query a formatted date for notification

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
Adding a property called `isEligibleForArtsyGuarantee`  to encapsulate conditions of eligibility for [Artsy Guarantee](https://www.artsy.net/buyer-guarantee)
```graphql
{
artwork(id: "foo-bar") {
isEligibleForArtsyGuarantee
}
}
```
=> feat: add isEligibleForArtsyGuarantee

_schemaV2.graphql, src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
As we continue to work on the artwork page/screen and associated details, we've realized that it would be useful to have a consistent definition for when an artwork is eligble to transact on-platform. We have a lot of checks for `isAcquireable || isOfferable` in clients. We've recently introduced the notion of "offerable by inquiry" which expands the cases for which an artwork supports on-platform commercial action. Beyond simplifying these client conditionals today, this also gives us a single source of truth we can adjust as this definition changes in the future.
cc/ @anandaroop @nickskalkin @dimatretyak @gkartalis
=> feat: Artwork#isEligibleForOnPlatformTransaction

src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts
This field is typed as non-null, but there is no such constraint on the backend that actually enforces that.
So, there are a few options:
- migrate data + enforce constraint on backend
- remove non-null typing
- add a fallback
The last option (fallback), is the easiest and is what's implemented here. The first option requires further work elsewhere in the stack, and the middle option will cause some disruption to client repos when this schema is updated as it's a breaking change.
=> fix: add a fallback name to User if one is not set

src/schema/v2/image/__tests__/index.test.js, src/schema/v2/image/index.ts
Addresses [CX-3058]
This PR adjusts the logic to get the default artwork images to not return broken images without URL which happened in the case described in the Jira ticket. 
[CX-3058]: https://artsyproduct.atlassian.net/browse/CX-3058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Adjust logic to get the default artwork images to not return broken images without URL

_schemaV2.graphql, src/schema/v2/artwork/__tests__/utilities.test.ts, src/schema/v2/artwork/index.ts, src/schema/v2/artwork/utilities.ts
Addresses https://artsyproduct.atlassian.net/browse/GRO-1306
This updates video support in the artwork type in support of the `setVideoAsCover` prop, which will push the video to the front. 
cc @artsy/grow-devs
=> feat(artwork): Update figure with new video

_schemaV2.graphql, src/schema/v2/__tests__/user.test.ts, src/schema/v2/me/__tests__/__snapshots__/update_me_mutation.test.js.snap, src/schema/v2/me/__tests__/index.test.ts, src/schema/v2/me/__tests__/update_me_mutation.test.js, src/schema/v2/me/index.ts, src/schema/v2/me/update_me_mutation.ts, src/schema/v2/user.ts
[Jira](https://artsyproduct.atlassian.net/browse/FX-4412)
Recently we introduced a new user preference - receive_partner_show_notification. We want to add functionality to add this setting in Eigen. For this purpose, we need to add a mutation in Metaphysics to alter this field.
=> feat(FX-4212): add receivePartnerShowNotification user preference

_schemaV2.graphql, src/schema/v2/types/Video.ts
So this just encodes the URL as an ID. I realize we can parse the ID out but that makes an assumption about the service. Then again, the way we're doing width/height also makes an assumption about the underlying service.
I do very much wish we had a real underlying model with more metadata here. It makes it hard to do the union type of Image/Video since fields conflict. Anyway: we _always_ need IDs or the Relay cache is gonna break.
=> feat(video): adds id

_schemaV2.graphql, src/schema/v2/artwork/__tests__/utilities.test.ts, src/schema/v2/artwork/utilities.ts, src/schema/v2/types/Video.ts
This migrates `url` to `playerUrl` for clarity. A follow-up PR will remove `url` next, after Force and MP is deployed.
=> chore(video): Migrate url -> playerUrl

_schemaV2.graphql, src/schema/v2/artwork/__tests__/utilities.test.ts, src/schema/v2/artwork/utilities.ts, src/schema/v2/types/Video.ts
Follow up to https://github.com/artsy/metaphysics/pull/4501
Removes the `url` field for now.
=> chore(video): Remove `url` field on video

_schemaV2.graphql, src/schema/v2/artist/index.ts
* Positron apparently supports BOTH `size` and `limit` params, but `size` is capped at `10` because of a bug where there's a default `limit` of `10`
* Someone exposed `limit` as an argument here which is Positron-specific and we should strive for a consistent pagination interface on Metaphysics' side of things. I'm not removing limit because I don't want to break the schema, but it won't work. I wish there was a proper way to deprecate arguments.
=> fix(artist): correctly passes size argument

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/__tests__/partnerArtistDocumentsConnection.test.ts, src/schema/v2/__tests__/partnerDocumentsConnection.test.ts, src/schema/v2/__tests__/partnerShowDocumentsConnection.test.ts, src/schema/v2/partner.ts, src/schema/v2/partnerArtistDocumentsConnection.ts, src/schema/v2/partnerDocumentsConnection.ts, src/schema/v2/partnerShowDocumentsConnection.ts, src/schema/v2/schema.ts
This PR resolves: https://artsyproduct.atlassian.net/browse/MOPLAT-477
To fetch documents of the partner by its ID(s)
**Query**
```graphql
{
partner(id: "partnerID") {
documentsByID: documentsConnection(first: 10, documentIDs: ["4faae457c056c20001000113", "4fc3b2b06c53ad0001000883"]) {
edges {
node {
title
}
}
}
documentsByArtist: documentsConnection(first: 10, artistID: "abe-ajax") {
edges {
node {
title
}
}
}
documentsByShow: documentsConnection(first: 10, showID: "folio-test-partner-mega-show-with-lots-of-artworks") {
edges {
node {
title
}
}
}
}
}
```
**Response**
```json
{
"partner": {
"documentsByID": {
"edges": [
{
"node": {
"title": "hi"
}
},
{
"node": {
"title": "hi"
}
}
]
},
"documentsByArtist": {
"edges": [
{
"node": {
"title": "Bla bl;a"
}
}
]
},
"documentsByShow": {
"edges": …
```
=> feat: add partner.documentsConnection query field

_schemaV2.graphql, src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4713
This builds on the [recent change](https://github.com/artsy/gravity/pull/15838) to the admin note API which exposed the `created_by` field (_user ID_) on the note.
As far as this PR, it updates the `UserAdminNoteType` to include a new field `creator` which, using the `created_by` field coming from gravity, _resolves_ using `userByIDLoader` to return the `user` who created the note.
`null` is returned in case of [legacy note](https://github.com/artsy/metaphysics/pull/4515#discussion_r1019651031) where the`created_by` field was never set during note creation:
Example shape of admin notes with `body` and `creator` selecting only the _name_ field would look like so:
---
I _could really use some advice_ as far as how to test this change. …
=> feat: admin note includes creator name when available

_schemaV2.graphql, src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4714
This PR exposes `identityVerified` field on the `User` type by mapping [this](https://github.com/artsy/gravity/blob/90621a2e3234f7f94e56e4f736055dc453af7642/app/models/domain/user.rb#L785) gravity field.
=> feat: expose identityVerified field on User type

_schemaV2.graphql, src/schema/v2/__tests__/user.test.ts, src/schema/v2/user.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-4714
This renames the field based on [feedback](https://github.com/artsy/metaphysics/pull/4524#discussion_r1024494776) to promote the use of `is[FieldName]` for boolean fields.
=> refactor: identityVerified field on User

src/lib/loaders/loaders_with_authentication/impulse.ts, src/schema/v2/conversation/conversations.ts, src/schema/v2/conversation/send_message_mutation.ts, src/schema/v2/me/index.ts
Currently we have a number of static props defined in our loaders that are very specific to the client and aren't configurable. This makes it so that we can dynamically pass in values to our resolvers to keep them generic. Step PR for wiring up partner-specific convo work in follow-up. 
=> refactor(conversations): Migrate static conversation props to resolvers

_schemaV2.graphql, src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/schema.ts, src/lib/stitching/gravity/v2/stitching.ts
[Jira](https://artsyproduct.atlassian.net/browse/FX-4437)
Adds query field to for new Artsy curated collection section
```graphql
{
curatedMarketingCollections(first: 5) {
slug
title
thumbnailImage {
resized(width: 200) {
url
}
}
}
}
```
```json
{
"data": {
"curatedMarketingCollections": [
{
"slug": "photography",
"title": "Photography",
"thumbnailImage": {
"resized": {
"url": "https://d7hftxdivxxvm.cloudfront.net?resize_to=width&width=200&quality=80&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2F_zWRgEXoyJtTVaM6NznROw%2Fnormalized.jpg"
}
}
},
{
"slug": "painting",
"title": "Painting",
"thumbnailImage": null
},
{
"slug": "artists-on-the-rise",
"title": "Artists on the Rise",
"thumbnailImage": null
},
{
"slug": "trending-this-week",
"title": "Trending This Week",
"thumbnailImage": null …
```
=> feat(FX-4437): Add curated marketing collections query field

_schemaV2.graphql, src/lib/__tests__/shuffle.test.ts, src/lib/shuffle.ts, src/schema/v2/artists/__tests__/curatedTrending.test.ts, src/schema/v2/artists/curatedTrending.ts, src/schema/v2/schema.ts
https://artsyproduct.atlassian.net/browse/FX-4451
This adds a new `curatedTrendingArtists` root-level field in order to expose a timely list of Artsy-suggested artists for use in various client-side contexts — starting with search suggestions in Eigen.
The list of artists:
- is sourced from the [Trending This Week](https://www.artsy.net/collection/trending-this-week) marketing collection
- for an idea of what that would feel like, see [here](https://artsy.slack.com/archives/C9SATFLUU/p1668542926931289)
- is exposed as a GraphQL connection
- has a built-in daily shuffle, such that each user will get a different sampling of artists every day
- the shuffle attempts to be time zone aware, so that the shuffle happens at midnight in the user's time zone
Since seeded random numbers are [not a …
=> feat: add a curated trending artists connection

_schemaV2.graphql, src/schema/v2/artwork/artworkContextGrids/__tests__/auctionContext.test.ts, src/schema/v2/artwork/artworkContextGrids/__tests__/defaultContext.test.ts, src/schema/v2/artwork/artworkContextGrids/__tests__/fairContext.test.ts, src/schema/v2/artwork/artworkContextGrids/__tests__/showContext.test.ts, src/schema/v2/artwork/artworkContextGrids/index.ts
https://artsyproduct.atlassian.net/browse/FX-4454
This partially addresses some potentially expensive over-fetching currently affecting the artwork page.
The Artwork page in Force currently does some lazy loading of other artworks’ data, e.g. artworks from the same show, fair, auction — _or_ artworks related by our similarity algorithm.
The last one, the "related artworks" grid, currently backs up onto a sometimes expensive ES query. Therefore we'd like to defer and minimize it as much as possible.
Funny thing is, although this can be addressed from the client side, there is a whole server-side orchestration of these artwork grid fetches that needs to be addressed at the Metaphysics layer.
So this PR makes the most expensive fetch _optional_ by:
- adding a new `includeRelatedArtworks` arg …
=> refactor: allow opt-out for related works in artwork context grids

scripts/push-schema-changes.js
This adds `volt-v2` to schema push list so that it receives schema changes when MP changes. 
=> feat(volt-v2): add to schema push

_schemaV2.graphql, src/schema/v2/schema.ts
We previously exposed `conversationsConnection` from the root level and we want to also expose `conversation` to use in the new Volt workflow.
=> feat(schema): expose conversation query in the root level

_schemaV2.graphql, src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
This PR resolves: [CX-2847]
This PR allows us to send the price paid for my collection artwork in the more common way we do it in MP by specifying the cost major and cost minor separately.
Co-authored-by: Daria Kozlova <daria.kozlova@artsymail.com>
Co-authored-by: Kizito Egeonu <kizito.egeonu@gmail.com>
Co-authored-by: Sultan Al-Maari <sultan.al-maari@artsymail.com>
[CX-2847]: https://artsyproduct.atlassian.net/browse/CX-2847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: use cost Major for price paid in MyC

_schemaV2.graphql, src/schema/v2/partner/__tests__/partner.test.js, src/schema/v2/partner/partner.ts
https://artsyproduct.atlassian.net/browse/FX-4484
Auction artwork pages were rendering links to auction profile pages that were unreachable and 404-ing
In https://github.com/artsy/force/pull/11465 we addressed that on the client side.
This goes a step further and ensures that we don't return a partner `href` for partner types that are not eligible for public pages in the first place, such as Auction, Demo, Private Dealer, etc.
(Note that CI is failing on some python build step at the moment; tests seem ok.)
=> fix(partner): do not return invalid href

_schemaV2.graphql, src/schema/v2/me/update_me_mutation.ts
This PR adds new field `coordinates` for `updateMyUserProfile` mutation to set correct user's timezone after address update.
JIRA - [TX-926]
[TX-926]: https://artsyproduct.atlassian.net/browse/TX-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add user coordinates for user location

_schemaV2.graphql, src/schema/v2/__tests__/sale_artwork.test.js, src/schema/v2/sale_artwork.ts
We've encountered cases where sale artworks in Gravity have non-numeric characters to store metadata related to the lot. This isn't a recommended use of the lot label field. As an alternative, we've recommended that colleagues use the `blurb` field which is also exposed on the same surfaces across web and app ([Slack](https://artsy.slack.com/archives/C02RAMW9QQJ/p1664364783118159)).
This PR updates the lotLabel resolver to accept an optional `trim` argument (default=false) to strip away anything past the first alphanumeric chunk from the Gravity-backed input. We'll use this in clients that need a shorter display string but we might consider adding this formatting and perhaps validation upstream in Gravity.
**Desired design**:
**Example of undesired use of the `lotLabel` field**:
=> feat: add trim option to strip away lot label past first alphanumeric chunk

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts
Patches a backend data issue for which an artwork can be both available for sale _and_ sold at the same time.
See [this Slack thread](https://artsy.slack.com/archives/CP9P4KR35/p1669977785252689) for more context.
=> fix: return isForSale=false if artwork is sold

_schemaV2.graphql, src/schema/v2/consignments/__tests__/createConsignmentInquiryMutation.test.js, src/schema/v2/consignments/createConsignmentInquiryMutation.ts
- Refactor to use internalID as the key for id in ConsignmentInquiry type since id is a reserved word in Relay. Clients using Relay such as Eigen are unable to query for the field id of a consignment inquiry.
=> Refactor: Use of reserved word ID in ConsignmentInquiry type

src/schema/v2/conversation/conversations.ts
Related to #4530 
We notice Impulse returning errors when we don't pass these args, now forcing them to `undefined` if they're not present solves the issue.
=> fix(filter): force undefined when partners filters are not present

package.json, src/schema/v2/image/services/gemini.ts, yarn.lock
With this we shouldn't see any changes to the URL output (so specs should pass) since these were already being alphabetized.
=> refactor(gemini): uses @artsy/img to mint urls

src/index.ts, src/schema/v2/image/cropped.ts, src/schema/v2/image/normalize.ts, src/schema/v2/image/resized.ts, src/schema/v2/image/services/config.ts, src/schema/v2/image/services/index.ts, src/schema/v2/image/services/lambda.ts, src/types/graphql.d.ts
This supports `X-Image-Service` to be set (or not), and if set will support "gemini" and "lambda" as possible values (which will switch support for which image service provides resized and cropped URL's). The default fallback is "gemini".
=> feat: allow X-Image-Service header to specify backend image service

_schemaV2.graphql, src/schema/v2/me/index.ts
Generally anything the `UserType` has the `MeType` should have as well. And easy to add. It's simpler and more consistent to be querying for things from the logged in user rather than having to pull the ID out of the current user and querying for it that way.
=> feat(me): adds quiz field

_schemaV2.graphql, src/schema/v2/quiz.ts
Quick little optimization since we're doing it in a few places. Doesn't need to be a connection since it's a bounded list that won't be paginated.
=> feat(quiz): exposes saved artworks field

_schemaV2.graphql, src/schema/v2/CollectorProfile/collectorProfile.ts, src/schema/v2/me/__tests__/collector_profile.test.js, src/schema/v2/partner/partnerInquirerCollectorProfile.ts
[NX-3395]
Some fields we use to query on Volt V1 like [here](https://github.com/artsy/volt/blob/d2a043a7f249c27116fd8c8c0407a20cfaf67acc/app/javascript/v2/apps/CollectorProfile/CollectorProfile.tsx#L111) but they were not fully exposed to the `collectorProfile` on the `Conversation` level. 
We have the data already, we just don't expose it, this PR expands the fields expositions under `Conversation.fromUser.collectorProfile`.
[NX-3395]: https://artsyproduct.atlassian.net/browse/NX-3395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(type): expose types from InquirerCollectorProfile on CollectorProfileType

src/schema/v2/conversation/index.ts
[NX-3325]
Provides a fallback when the name is null for some cases.
Related to #4467 
paired with @lidimayra
[NX-3325]: https://artsyproduct.atlassian.net/browse/NX-3325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(null): create a fallback when name is null

_schemaV2.graphql, src/schema/v2/CollectorProfile/collectorProfile.ts, src/schema/v2/me/__tests__/collector_profile.test.js
This PR addresses this [request](https://github.com/artsy/metaphysics/pull/4628#discussion_r1053407946) deprecating `emailConfirmed` and adding `isEmailConfirmed` as an option.
We'll have PRs to update the clients to use the new field, then we can retire the field.
=> feat(graphql): deprecate emailConfirmed field

_schemaV2.graphql, src/schema/v2/CollectorProfile/collectorProfile.ts, src/schema/v2/me/__tests__/collector_profile.test.js
related to #4639 
Deprecates also `identityVerified` in favor of `isIdentityVerified`.
=> feat(graphql): deprecate identityVerified field

src/schema/v2/me/__tests__/index.test.ts, src/schema/v2/me/index.ts
Completes [TX-854](https://artsyproduct.atlassian.net/jira/software/c/projects/TX/boards/114?modal=detail&selectedIssue=TX-854)
This pr updates our `Me.hasQualifiedCreditCards` field to filter out expired cards, which are not 'qualified.'
I verified that cards are [still good during their expiration month](https://www.americanexpress.com/en-us/credit-cards/credit-intel/what-happens-when-credit-card-expires/), so only check whether the current date is after that.
I tried to take the quickest route to implementation and defaulted to measuring by utc. I considered adding a 1-day buffer to the expiration date to account for time zone weirdness, but that seemed like it might be confusing later, and really whether your card is considered qualified or not in this short period isn't very …
=> feat: only non-expired credit cards are qualified

_schemaV2.graphql, src/schema/v2/__tests__/auction_result.test.ts, src/schema/v2/auction_result.ts
This PR adds `isUpcoming` to the auction result interface. 
**Notes:** 
- ⭐️This is important to avoid doing this computation on the frontend side.
- ⭐️⭐️ We intentionally compare to the beginning of the day instead of the exact moments
=> feat: add isUpcoming to auction result interface

_schemaV2.graphql, src/schema/v2/me/myCollectionInfo.ts
Addresses [CX-3285]
🔴  Depends on https://github.com/artsy/gravity/pull/15975
Adding includePersonalArtists param to the collection artist endpoint. This param will be used to make sure personal artists don't show up when fetching artists to show insights.
[CX-3285]: https://artsyproduct.atlassian.net/browse/CX-3285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add includePersonalArtists param to collectedArtistsConnection

src/schema/v2/me/myCollectionInfo.ts
Addresses [CX-3285]
Because `includePersonalArtists` defaults to `false`, we need to use a hack for older clients that don't send the parameter introduced in https://github.com/artsy/eigen/pull/7904. The only query we need to set the param to true is part of the My Collection artwork form (which sets `size` to `100`). 
[CX-3285]: https://artsyproduct.atlassian.net/browse/CX-3285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Set includePersonalArtists to true for artwork form query

src/schema/v2/me/myCollectionInfo.ts
Addresses [CX-3285]
Adjust includePersonalArtists hack introduced in https://github.com/artsy/metaphysics/pull/4657 (`size` -> `first`).
[CX-3285]: https://artsyproduct.atlassian.net/browse/CX-3285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: adjust includePersonalArtists hack

_schemaV2.graphql, src/schema/v2/OrderedSet/OrderedSet.ts, src/schema/v2/OrderedSet/createOrderedSetMutation.ts
This PR   adds `internalName` as an input in the `createOrderedSet` mutation and to the `OrderedSetType` schema.
This supports having the field available as part of the figma [design](https://www.figma.com/file/RiH2Y6TKOPG1kyEWdkJ0Zw/Forque-Platform-redesign?node-id=169%3A27331&t=bVA0aYK7MkgLvaXA-0). 
[PLATFORM-4810]
[PLATFORM-4810]: https://artsyproduct.atlassian.net/browse/PLATFORM-4810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: support ordered set internal name field

src/lib/loaders/loaders_with_authentication/gravity.ts
This should be enough to propagate the user's token (and thus be able to retrieve unpublished sets from Gravity).
=> chore: add an authenticated setsLoader

_schemaV2.graphql, src/schema/v2/artwork_version.ts
[TX-947](https://artsyproduct.atlassian.net/browse/TX-947)
This PR adds medium and attribution class to the artwork version type in preparation for private sales. 
[TX-947]: https://artsyproduct.atlassian.net/browse/TX-947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-947): add medium and attribution class to artwork version type

_schemaV2.graphql, src/schema/v2/CollectorProfile/collectorProfile.ts, src/schema/v2/me/__tests__/collector_profile.test.js
This PR resolves [CX-2964]
This PR adds a new field to the collector profile. It's a new boolean field called `isProfileComlete` that returns `true` if the user has a **name**, **location**, **profession**, **other relevant positions**, and a **bio**, and returns `false` otherwise
Query:
```graphql
{
me {
collectorProfile {
isProfileComplete
}
}
}
```
Response:
```json
{
"data": {
"me": {
"collectorProfile": {
"isProfileComplete": false
}
}
}
}
```
[CX-2964]: https://artsyproduct.atlassian.net/browse/CX-2964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2964): add isProfileComplete to Collector Profile

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/triggerCampaignMutation.test.ts, src/schema/v2/me/triggerCampaignMutation.ts, src/schema/v2/schema.ts
The type of this PR is: feat
This PR solves [GRO-1262]
The goal of this PR is to add a mutation for a `POST` request that triggers a Braze campaign send for authenticated users taking the art quiz to receive their results via email. 
This mutation is also pretty generalized so that any client making a call to `/me/trigger_campaign` with a new campaign can be mapped w/ an appropriate `campaign_id`. A spec is included to test that the call was made w/ the correct values passed to gravity. 
TODO:
Note: the `clientMutationId` is returned as a response and returns null but that seems to be a graphql/relay thing and isn't a problem here.
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> feat(art-quiz) create triggerCampaignMutation and gravity loader

src/lib/stitching/gravity/v2/stitching.ts
Minor update to get the new Trove rebranding in MP.
https://artsyproduct.atlassian.net/browse/GRO-1495
=> chore: Trove Rebranding GRO-1495

yarn.lock
This PR bumps `json5` at `^2.x.x` to use the latest version.
=> chore: bump json5

_schemaV2.graphql, src/data/diffusion.graphql, src/schema/v2/__tests__/auction_result.test.ts, src/schema/v2/auction_result.ts
This PR adds `lotNumber` to the auction results type to be used by the new design for the auction results on Force
**Query**
```graphql
query {
artist (id: "andy-warhol") {
name
auctionResultsConnection (first: 1) { 
edges {
node {
lotNumber
}
}
}
}
}
```
**Result**
```json
{
"data": {
"artist": {
"name": "Andy Warhol",
"auctionResultsConnection": {
"edges": [
{
"node": {
"title": "Jean Cocteau",
"lotNumber": null
}
}
]
}
}
}
}
```
=> feat(CX-3280): Add lotNumber to Auction Results type

_schemaV2.graphql, src/schema/v2/artwork_version.ts
Related to [TX-948](https://artsyproduct.atlassian.net/browse/TX-948)
I realized that we specifically need the "short description" of the attribution class on ArtworkVersion. This allows us to access all of the sub-fields instead of only the name. 
[TX-948]: https://artsyproduct.atlassian.net/browse/TX-948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-948): add attribution class fields to artwork version

_schemaV2.graphql, src/schema/v2/me/__tests__/mark_notification_as_read_mutation.test.ts, src/schema/v2/me/mark_notification_as_read_mutation.ts, src/schema/v2/schema.ts
- Do not merge until https://github.com/artsy/gravity/pull/15999 is merged
- [Jira ticket](https://artsyproduct.atlassian.net/browse/FX-4534)
Adds a mutation to mark a notification as read:
```graphql
mutation {
markNotificationAsRead(input: { id: "63c55aeacde4edd6cf014d66" }) {
... on MarkNotificationAsReadSuccess {
success
}
... on MarkNotificationAsReadFailure {
error
message
}
}
}
}
}
```
After that in my feed:
=> feat(FX-4534): GraphQL mutation for marking a specific entry in the activity panel as read

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/Feature/CreateFeatureMutation.ts, src/schema/v2/Feature/DeleteFeatureMutation.ts, src/schema/v2/Feature/Feature.ts, src/schema/v2/Feature/FeaturesConnection.ts, src/schema/v2/Feature/UpdateFeatureMutation.ts, src/schema/v2/Feature/__tests__/CreateFeatureMutation.test.ts, src/schema/v2/Feature/__tests__/DeleteFeatureMutation.test.ts, src/schema/v2/Feature/__tests__/FeaturesConnection.test.ts, src/schema/v2/Feature/__tests__/UpdateFeatureMutation.test.ts, src/schema/v2/OrderedSet/orderedSetsConnection.ts, src/schema/v2/schema.ts
This adds the CRUD mutations to manage a `Feature`, as well as the `featuresConnection` listings root field.
=> feat: Add CRUD and listings for Feature management

_schemaV2.graphql, src/schema/v2/conversation/__tests__/__snapshots__/message.test.js.snap, src/schema/v2/conversation/__tests__/message.test.js, src/schema/v2/conversation/message.ts
This PR solves part of [NX-3371](https://artsyproduct.atlassian.net/browse/NX-3371)
Expose `message` recipients on `to` and `cc`, so we can determine who has opened an email on Volt's Conversations.
[NX-3371]: https://artsyproduct.atlassian.net/browse/NX-3371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(NX-3371): Expose message's to and cc

_schemaV2.graphql, src/schema/v2/conversation/message.ts
Solves part of [NX-3371](https://artsyproduct.atlassian.net/browse/NX-3371)
As a follow-up of https://github.com/artsy/metaphysics/pull/4698, define `message`'s `to` and `cc` as non-nullable since they can be empty arrays. More context [here](https://github.com/artsy/metaphysics/pull/4698#discussion_r1081643489).
[NX-3371]: https://artsyproduct.atlassian.net/browse/NX-3371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(NX-3371): make message's to and cc non-nullable

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/FeaturedLink/__tests__/createFeaturedLinkMutation.test.ts, src/schema/v2/FeaturedLink/__tests__/deleteFeaturedLinkMutation.test.ts, src/schema/v2/FeaturedLink/__tests__/featuredLinksConnection.test.ts, src/schema/v2/FeaturedLink/__tests__/updateFeaturedLinkMutation.test.ts, src/schema/v2/FeaturedLink/createFeaturedLinkMutation.ts, src/schema/v2/FeaturedLink/deleteFeaturedLinkMutation.ts, src/schema/v2/FeaturedLink/featuredLink.ts, src/schema/v2/FeaturedLink/featuredLinksConnection.ts, src/schema/v2/FeaturedLink/updateFeaturedLinkMutation.ts, src/schema/v2/item.ts, src/schema/v2/schema.ts
Opening this in draft mode b/c I still need to add some tests.
But! This adds the usual CRUD mutations, plus a listings root field `featuredLinksConnection` which supports the match-querying as well (as per usual).
=> feat: add CRUD and listings for FeaturedLink

_schemaV2.graphql, src/lib/customTypes/GraphQLLong.ts, src/schema/v2/fields/money.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts
This PR resolves [CX-2847]
We are unable to create artworks priced above 2**32 $. While we can pass this to gravity, we cannot get past Metaphysics because GraphQLInt will only allow values below a 32 bit signed integer.
This  PR does the following: 
- adds a custom Long type to Metaphysics to allow us pass up to javascript's Number.MAX_SAFE_INTEGER which is 52 bits signed integer.
- Updates the type for pricePaidCents for MyCollection Artwork to use this type.
- Updates the type for `minor` in `Money` to use this type. By updating this, this enables us to be able to read money.minor values of up to our current definition of Long.
https://user-images.githubusercontent.com/18648835/213712541-151d2aff-c098-4b11-b7fd-f7115b068162.mov …
=> feat(CX-2847): GraphQLLong

_schemaV2.graphql, src/schema/v2/me/__tests__/collection.test.ts, src/schema/v2/me/collection.ts, src/schema/v2/sorts/collection_sorts.ts
https://artsyproduct.atlassian.net/browse/FX-4513
This adds a `me.collection.artworksConnection` field such that the following query for a user's saved artworks can be resolved via an authenticated loader:
```graphql
query {
me {
collection(id: "saved-artwork") { # 👈🏽 pseudo-slug or database ID works here
artworksConnection(first: 3 sort: SAVED_AT_DESC) {
totalCount
edges {
node {
slug
}
}
}
}
}
}
```
```json
{
"data": {
"me": {
"totalCount": 42,
"edges": [
{
"node": {
"slug": "a-saved-artwork"
}
},
{
"node": {
"slug": "another-saved-artwork"
}
},
{
"node": {
"slug": "yet-another-saved-artwork"
}
}
]
}
}
}
}
}
```
If there is a mismatch between the collection owner and the user associated with the current access token
```json
{
"data": {
"me": { …
```
=> feat(wishlists): add artworksConnection to me.collection

_schemaV2.graphql, src/lib/customTypes/GraphQLLong.ts, src/schema/v2/fields/money.ts, src/schema/v2/me/myCollectionCreateArtworkMutation.ts, src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
This PR resolves [CX-2847]
- This PR is same as https://github.com/artsy/metaphysics/pull/4702 except for a single line that updates the updateArtworkCollection Mutation pricePaidCents type to use the custom Long type.
This PR resolves [CX-2847]
We are unable to create artworks priced above 2**32 $. While we can pass this to gravity, we cannot get past Metaphysics because GraphQLInt will only allow values below a 32 bit signed integer.
This  PR does the following: 
- adds a custom Long type to Metaphysics to allow us pass up to javascript's Number.MAX_SAFE_INTEGER which is 52 bits signed integer.
- Updates the type for pricePaidCents for MyCollection Artwork to use this type.
- Updates the type for `minor` in `Money` to use this type. By updating this, this enables us to be able to read …
=> Feat(CX-2847): Updated GraphQLLong

src/schema/v2/conversation/index.ts
[NX-3421]
When we soft remove user data the field `fromUser` throws an error from the `conversations` domain. This PR gracefully handles the error; no changes within the returned data, only does not pollute the client logs with the error anymore.
@artsy/negotiate-devs 
[NX-3421]: https://artsyproduct.atlassian.net/browse/NX-3421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(NX-3412): gracefully handle errors from fromUser

_schemaV2.graphql, src/schema/v2/artwork/layer.ts, src/schema/v2/quiz.ts, src/schema/v2/quizArtworkConnection.ts
So, primarily what this does is expose a new `recommendedArtworks` field to the `Quiz`. It looks for your saved artworks, then uses those to directly request the `main` layer and caches it for 24 hours.
=> feat(quiz): exposes a (cached) recommended artworks field

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/createCollectionMutation.test.ts, src/schema/v2/me/createCollectionMutation.ts, src/schema/v2/schema.ts
[Jira ticket](https://artsyproduct.atlassian.net/browse/FX-4524)
Add a `createCollection` mutation
```graphql
mutation {
createCollection(input: {name: "Wishlist" }) {
... on CreateCollectionSuccess {
collection {
internalID
name
}
}
... on CreateCollectionFailure {
message
}
}
}
}
}
```
```graphql
{
"data": {
"createCollection": {
"internalID": "7c041eb3-b528-466f-ae72-1b1253eaa5d8",
"name": "Wishlist"
}
}
}
}
}
```
```graphql
{
"data": {
"createCollection": {
"mutationError": {
"message": "Name Already exists."
}
}
}
}
}
```
=> feat(FX-4524): add createCollection mutation

_schemaV2.graphql, src/schema/v2/conversation/conversations.ts
[NX-3411]
Use the new scope implemented during:
- https://github.com/artsy/impulse/pull/889
- https://github.com/artsy/impulse/pull/891
We want this param to be passed when filtering conversations that must be listed in the `New` tab in CMS (conversations to be replied).
```graphql
{
conversationsConnection(	
type: PARTNER,
partnerId: "5f80bfefe8d808000ea212c1",
first: 3,
toBeReplied: true
) {
edges {
node {
internalID
fromUser {
name
}
}
}
}
}
```
The query above returns the 3 most recent conversations that should be listed as "to be replied" (new tab) for Commerce Test Partner (conversations that contains messages, that contains no replies, that are not dismissed and which the last message was sent less than a year ago)
[NX-3411]: …
=> feat(NX-3411): Enable `to_be_replied` param to filter new conversations

src/schema/v2/artwork/__tests__/utilities.test.ts, src/schema/v2/artwork/utilities.ts
Pass includeAll arg correctly to artwork figures resolver
=> fix: Pass includeAll arg correctly to artwork figures resolver

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/deleteCollectionMutation.test.ts, src/schema/v2/me/deleteCollectionMutation.ts, src/schema/v2/schema.ts
https://artsyproduct.atlassian.net/browse/FX-4530
Adds a mutation to delete the current user's collection by id.
```graphql
mutation DeleteCollection {
deleteCollection(input: { id: "ee941f42-9d1e-41e2-ad47-6f5b53315fc9" }) {
... on DeleteCollectionSuccess {
collection {
internalID
name
}
}
... on DeleteCollectionFailure {
statusCode
message
}
}
}
}
}
```
```json
{
"data": {
"deleteCollection": {
"internalID": "dc24d286-4621-4613-bb63-c709e97ee789",
"name": "Delete me"
}
}
}
}
}
```
If there is a mismatch between the collection owner and the user associated with the current access token
```json
{
"data": {
"deleteCollection": {
"mutationError": {
"message": "Collection Not Found"
}
}
}
}
}
```
=> feat(wishlists): add deleteCollection mutation

_schemaV2.graphql, src/schema/v2/Feature/CreateFeatureMutation.ts, src/schema/v2/Feature/UpdateFeatureMutation.ts, src/schema/v2/Feature/__tests__/CreateFeatureMutation.test.ts, src/schema/v2/Feature/__tests__/UpdateFeatureMutation.test.ts
Threads through `sourceBucket` and `sourceKey` to the backing endpoints.
=> feat: allow create and update feature mutations to accept sourceBucket and key

_schemaV2.graphql, package.json, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/me/__tests__/index.test.ts, src/schema/v2/me/__tests__/markNotificationsAsSeenMutation.test.ts, src/schema/v2/me/index.ts, src/schema/v2/me/markNotificationsAsSeenMutation.ts, src/schema/v2/notifications/__tests__/index.test.ts, src/schema/v2/notifications/index.ts, src/schema/v2/schema.ts, yarn.lock
[Jira ticket](https://artsyproduct.atlassian.net/browse/FX-4574)
- Adds `unseen` counter to the `notificationsConnection`
- Adds `markNotificationsAsSeen` mutation
```graphql
{
notificationsConnection(first: 1){
counts {
unseen
}
}
}
```
```graphql
mutation {
markNotificationsAsSeen(input: { until: "2023-01-30T11:05:19Z"}) {
... on MarkNotificationsAsSeenSuccess {
success
}
... on MarkNotificationsAsSeenFailure {
message
}
}
}
}
}
```
```graphql
{
"data": {
"markNotificationsAsSeen": {
"success": true
}
}
}
}
```
=> feat(FX-4574): add markNotificationsAsSeen mutation

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/lib/loaders/loaders_without_authentication/gravity.ts, src/schema/v2/artists.ts, src/schema/v2/match/__tests__/artist.test.js, src/schema/v2/match/artist.ts, src/schema/v2/sales.ts, src/schema/v2/shows.ts
This PR adds the ability the search by a `term` to `artistsConnection`, `salesConnection`, and `showsConnection`. When a `term` is not provided the query falls through to the connection's default behavior.
This supports the work in `forque` to add a sets editor. 
[PLATFORM-4927] 
[PLATFORM-4927]: https://artsyproduct.atlassian.net/browse/PLATFORM-4927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: search Artists, Sales, and Shows by term argument

_schemaV2.graphql, src/schema/v2/me/__tests__/collectionsConnection.test.ts, src/schema/v2/me/collectionsConnection.ts
https://artsyproduct.atlassian.net/browse/FX-4596
Adds support for `default` and `saves` fields, which are already support at the upstream Gravity endpoint, e.g.:
```graphql
{
me {
defaultSaves: collection(id: "saved-artwork") {
name
artworksCount
}
artworkLists: collectionsConnection(first: 10, default: false, saves: true) {
edges {
node {
name
artworksCount
}
}
}
}
}
```
This would return every collection that is a user-defined saves collection, but not the default saved-artworks collection:
```json
{
"data": {
"me": {
"defaultSaves": {
"name": "Saved Artwork",
"artworksCount": 19
},
"artworkLists": {
"edges": [
{
"node": {
"name": "For the kitchen",
"artworksCount": 3
}
},
{
"node": {
"name": "For the living room",
"artworksCount": 7
}
}
]
}
}
}
}
```
=> feat(artwork lists): support 'saves' and 'default' args

_schemaV2.graphql, src/schema/v2/user.ts
Now that access to user data depends on more fine-grained privileges (such as `role_manager` for roles and `customer_support` for account details), certain schema properties may not be accessible to the authenticated administrator. Currently, querying any of these results in the top-level `user` being `null` (confusingly), even though most other properties _are_ accessible.
This PR adjusts the `adminNotes` to anticipate `null`s, which is enough in my tests for role management to function without the `customer_support` privilege. I think it would be even better for clients to avoid querying for inaccessible data (maybe via `@include` directives), but that is left as a separate improvement.
https://artsyproduct.atlassian.net/browse/PLATFORM-4901
=> fix: admin notes can be null, because the requester may be unauthorized (PLATFORM-4901)

_schemaV2.graphql, src/data/exchange.graphql
This PR updates Exchange schema to provide `artworkDetails` of an order for private sales.
=> chore: Update exchange schema with artwork details

src/lib/loaders/loaders_with_authentication/gravity.ts
This PR adds in a `batchSize` of 10 so that saved artwork requests don't send more ids than the endpoint can handle. What we saw prior to this change was that we were sending the 16 artwork ids from the quiz but only getting back accurate liked info on exactly 10 of them.
With this change in place a single Gravity API call to the saved artwork collection turns into 2 and all the liked info comes back accurately. So this solves the bug as outlined in the ticket.
But technically all 16 artwork ids could be sent in a single request - this abstraction is causing us to send 2. So another approach here could be to send a size to gravity based on the number of ids. That type of change would alter the behavior of a few more fields so I'm hesitant to make it:
``` …
```
=> fix: Return all saved artworks from quiz GRO-1547

_schemaV2.graphql, src/schema/v2/me/__tests__/collectionsConnection.test.ts, src/schema/v2/me/collection.ts, src/schema/v2/me/collectionsConnection.ts, src/schema/v2/me/savedArtworks.ts, src/schema/v2/sorts/collection_sorts.ts
https://artsyproduct.atlassian.net/browse/FX-4598
(And follow-up to https://github.com/artsy/gravity/pull/16058)
Supports a new sort param on collectionsConnection, e.g. 
```graphql
{
me {
collectionsConnection(first: 10, sort: CREATED_AT_DESC) {
edges {
node {
internalID
name
}
}
}
}
}
```
Note: before introducing `CollectionSorts` I wanted to rename the already-existing `CollectionSorts` to the more apt `CollectionArtworkSorts`. I think this is a non-breaking change at least in terms of the _data_ being passed around. Though I'm not sure if any Relay compilers in other projects might complain about the types having changed names, before this schema update makes the rounds.
=> feat(artwork lists): add sort option to collectionsConnection

src/schema/v2/__tests__/show_events.test.ts, src/schema/v2/show_event.ts
While investigating a tangential [bug](https://artsyproduct.atlassian.net/browse/PX-5385), came across an issue here where `timezone` on show events was always returning `undefined` from gravity. If timezone is undefined, we fallback to UTC
That is because we are using the wrong attribute name in the resolver, `timezone` vs `time_zone` (the [ShowEvent](https://github.com/artsy/gravity/blob/main/app/models/domain/partner_show_event.rb#L15) model in gravity is using the snake case)
PS youll notice is gravity we use a mix of the different spellings which makes this interface a little more confusing, both [timezone](https://github.com/artsy/gravity/blob/fa87f2b5a51e01bd3777218b468bb45bb5360ce6/app/models/domain/partner_location.rb#L28) and …
=> fix: Match gravity's snake_case for time_zone in show event resolver

src/schema/v2/me/triggerCampaignMutation.ts
The goal of this PR is to switch the production campaign IDs for Braze to be sent to users for the art quiz after launching the app.
=> fix(art-quiz) switch production campaign ids for braze

_schemaV2.graphql, src/schema/v2/me/__tests__/collection.test.ts, src/schema/v2/me/collection.ts
https://artsyproduct.atlassian.net/browse/FX-4593
Adds missing `page` arg for `collection.artworksConnection`
```graphql
{
me {
collection(id: "42427e8172616975e8004242") {
👇🏽
artworksConnection(page: 2) {
edges {
node {
slug
}
}
}
}
}
}
```
=> fix(artwork lists): collection artworks pagination

src/lib/stitching/exchange/__tests__/stitching.test.ts, src/lib/stitching/exchange/v2/stitching.ts
Per the [tech plan](https://www.notion.so/artsy/Prevent-sellers-receiving-conversations-associated-with-in_review-offers-9d43b056735f489788a17ce4357cfc08), we'll skip creating conversations at offer creation time when the associated order is held for review.
For the time being, this will never actually trigger (even if we were to launch putting orders with offers `in_review`) because of the changes in [this PR](https://github.com/artsy/exchange/pull/1464). To summarize, when a buyer-facing client (Force, Exchange) requests the `state` field exposed by Exchange's GraphQL API, we return `submitted` whenever the order is `in_review` to maintain the illusion that the order is not being held for review, and to avoid having to update clients to know how to display `in_review` orders.
We're …
=> feat: skip InquiryRequest creation for in_review offers

src/lib/stitching/gravity/__tests__/stitching.test.ts, src/lib/stitching/gravity/v2/stitching.ts
https://artsyproduct.atlassian.net/browse/FX-4543
Fixes one actual, and several potential, bugs by moving away from the pattern of mutating the global shared `context` object for the current request when fulfilling stitched fields.
(I also tried to automate a Danger check to prevent this from happening again in the future, but [hit some blockers](https://artsy.slack.com/archives/CP9P4KR35/p1675978327622389) there.)
Taking for example the [Street Art collection](https://www.artsy.net/collection/street-art)…
Starting with the recent refactor https://github.com/artsy/force/pull/11715 — which started using `MarketingCollection.thumbnailImage` — this leaky `context` was being inadvertently read from the [Image resolver](https://github.com/artsy/metaphysics/blob/99a12ac1c449379f128e5ad01794f6443 …
=> fix(collections): avatar bug caused by shared mutable context

_schemaV2.graphql, src/schema/v2/OrderedSet/__tests__/updateOrderedSetMutation.test.ts, src/schema/v2/OrderedSet/updateOrderedSetMutation.ts
I need this to be able to add sets (ie- update their owner) to a Feature. You may need this as well on the sets side (to assign an owner on the set page).
=> chore: allow ownerId to be passed in to the update set mutation

_schemaV2.graphql, src/schema/v2/OrderedSet/updateOrderedSetMutation.ts
It's nice to be able to resolve the feature owner (when updating a set), such as re-fetching the sets belonging to that owner!
=> chore: resolve a feature when updating a set

_schemaV2.graphql, src/schema/v2/__tests__/markdownContent.test.ts, src/schema/v2/markdownContent.ts, src/schema/v2/schema.ts
This is going to be used to generate live previews for entered text in Markdown fields in Forque!
=> feat: add root-level markdown field for use in live previews

src/lib/stitching/exchange/v2/stitching.ts
I am trying to understand why a conversation is being created for an order that ends up in the review queue. I realized that we're comparing the payment method with `==` instead of `===`.
=> Compare order payment method with triple equals

src/lib/stitching/exchange/v2/stitching.ts
When an offer order is submitted, Metaphysics decides whether a Conversation needs to be created for that order. In #4785 we updated this logic, but forgot to request a field from the Exchange schema that is used in the new logic. This PR makes the request for that field.
=> fix: added missing field that was needed in stitching logic

_schemaV2.graphql, src/lib/loaders/loaders_with_authentication/gravity.ts, src/schema/v2/artist/__tests__/updateArtistMutation.test.ts, src/schema/v2/artist/index.ts, src/schema/v2/artist/updateArtistMutation.ts, src/schema/v2/schema.ts
This PR adds a new top-level mutation called `updateArtist`. It's a copy/paste/update job from the other user update mutation I made before on https://github.com/artsy/metaphysics/pull/3918 and https://github.com/artsy/metaphysics/pull/3926. At this point all it supports is managing this list of data about an artist:
* displayName
* first
* id
* last
* middle
And my intention here is to lay down the basics but we'll ultimately be adding a bunch of fields here as we migrate over the artist edit page.
=> Add mutation to edit an artist

src/schema/v2/artist/helpers.ts
For whatever reason it looks like Diffusion sometimes returns bad data — I'm not digging into the root cause here but _someone_ should take a look. Specifically this is able to be reproduced with the artist `robert-mangold`.
=> fix(artist): guards against possibly null data

_schemaV2.graphql, src/schema/v2/me/index.ts, src/schema/v2/me/savedArtworks.ts
We need to be able to update a counts field on follows and saves in order to support progressive onboarding dismissals. Currently you can get these by accessing `totalCount`s on the related connections but we'd have to have identical query params for the optimistic updates to work. This is much simpler.
=> feat(me): exposes counts

src/schema/v2/conversation/send_message_mutation.ts
[NX-3465]
Attachments were not correctly parsed as`array`, the data loader parses the parameter as query string like `path?attachments[][name]="name.jpg"` instead of providing an index.
Spreading the array inside an object fixes the query string to be like `path?attachments[0][name]="name.jpg"&attachments[1][name]="2nd.png"`.
[NX-3465]: https://artsyproduct.atlassian.net/browse/NX-3465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(NX-3465): attachments array in SendMessageMutation

_schemaV2.graphql, src/schema/v2/conversation/__tests__/__snapshots__/conversation.test.js.snap, src/schema/v2/conversation/__tests__/conversation.test.js, src/schema/v2/conversation/index.ts, src/schema/v2/partner/partner.ts, src/schema/v2/partner/partnerInquirerCollectorProfile.ts, src/schema/v2/partner/partnerInquiryRequest.ts
Addresses [NX-3383]
Exposes the associated `InquiryRequest` as part of the conversation. This allows us to access the questions and shipping locations stored on Gravity, which mobile app users might fill in on initial inquiries.
[NX-3383]: https://artsyproduct.atlassian.net/browse/NX-3383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(NX-3383): Expose the associated inquiry request with a conversation

src/lib/fillers/enrichArtworksWithPriceInsights.ts, src/lib/loaders/loaders_with_authentication/vortex.ts
We need to filter out `null` values in the price insights batch loader input because the params `artistId` and `medium` are [required in Vortex](https://github.com/artsy/vortex/blob/34991742b702d00e697399acce769e64373cc5f9/app/graphql/types/artist_id_medium_tuple_type.rb#L6) and the loader will fail silently when we send null values.
Related issue: https://github.com/artsy/metaphysics/pull/4800
=> fix: Filter null values in price insights batch loader input

_schemaV2.graphql, src/schema/v2/me/__tests__/collection.test.ts, src/schema/v2/me/__tests__/collectionsConnection.test.ts, src/schema/v2/me/collection.ts
The type of this PR is: **Feat**
Jira ticket: [FX-4623]
```graphql
{
me {
collection(id: "collection-id") {
isSavedArtwork(artworkID: "artwork-id")
}
collectionsConnection(first: 1) {
edges {
node {
isSavedArtwork(artworkID: "artwork-id")
}
}
}
}
}
```
[FX-4623]: https://artsyproduct.atlassian.net/browse/FX-4623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4623): add `isArtworkSaved` field to `Collection` type

src/lib/fillers/enrichArtworksWithPriceInsights.ts, src/lib/loaders/loaders_with_authentication/vortex.ts
Reverts artsy/metaphysics#4811 and fixes the bug:
`vortexResult.errors.length` -> `vortexResult?.errors?.length`.
=> Revert "Revert "fix: Filter null values in price insights batch loader input""

_schemaV2.graphql, src/schema/v2/conversation/__tests__/__snapshots__/conversation.test.js.snap, src/schema/v2/conversation/__tests__/conversation.test.js, src/schema/v2/partner/partnerInquiryRequest.ts
Partly resolves [NX-3441]
Exposes a `formattedFirstMessage` field on the `inquiryRequest`, which includes the first message and the formatted inquiry questions and location. If no questions are present, it'll default to the first message and return only the formatted questions if the opposite is true.
Example:
```
{
conversation (id: "123") {
inquiryRequest: {
message: "Hello world!",
questions: [
{
"internalID": "shipping_quote",
"question": "Shipping"
}, {
"internalID": "condition_and_provenance",
"question": "Condition & Provenance"
}
],
shippingLocation: {
city: "Montevideo",
country: "Uruguay"
},
formattedFirstMessage: "Hello world!\n\nI would like to request the following information about this artwork:\n• Shipping Quote to Montevideo, Uruguay\n• Condition & Provenance"
}
}
}
``` …
=> feat(NX-3441): Expose a formatted first message including questions

src/schema/v2/artist/helpers.ts
The entities on the new fields returned empty arrays before. I tested this with the the `splitEntities` helper and got back the actual data:
Resolves [GROW-1563](https://artsyproduct.atlassian.net/browse/GRO-1563)
Related to: #4815 and https://github.com/artsy/force/pull/11966
=> fix: use split helper for new fields string

_schemaV2.graphql, src/schema/v2/OrderedSet/updateOrderedSetMutation.ts
Needed to allow explicit unsetting of an owner from an existing set.
=> chore: thread argument through so a set owner can be unset

src/schema/v2/__tests__/searchCriteriaLabel.test.ts, src/schema/v2/searchCriteriaLabel.ts
Find corresponding medium type via gene slug and use the defined name. When a corresponding medium type is not found, use `Other (<slug>)` as the display name.
Jira: [FX-4578](https://artsyproduct.atlassian.net/browse/FX-4578) 🔒 
[FX-4578]: https://artsyproduct.atlassian.net/browse/FX-4578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: align alert labels with known artwork medium types

_schemaV2.graphql, src/schema/v2/me/__tests__/newWorksFromGalleriesYouFollow.test.ts, src/schema/v2/me/index.ts, src/schema/v2/me/newWorksFromGalleriesYouFollow.ts
Addresses [CX-3411]
Introduce new `newWorksFromGalleriesYouFollow` artworks connection under `me`.
```graphql
{
me {
newWorksFromGalleriesYouFollowConnection(
first: 20
) {
pageInfo {
endCursor
hasNextPage
hasPreviousPage
}
edges {
cursor
node {
title
}
}
}
}
}
```
[CX-3411]: https://artsyproduct.atlassian.net/browse/CX-3411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: newWorksFromGalleriesYouFollow artworks connection

_schemaV2.graphql, src/schema/v2/me/__tests__/similarToRecentlyViewed.test.ts, src/schema/v2/me/index.ts, src/schema/v2/me/similarToRecentlyViewed.ts
Addresses [CX-3411]
This PR introduces the SimilarToRecentlyViewed connection under `me`.
```graphql
{
me {
similarToRecentlyViewedConnection(
first: 50 ,
) {
pageInfo {
endCursor
hasNextPage
hasPreviousPage
}
edges {
cursor
node {
title
}
}
}
}
}
```
[CX-3411]: https://artsyproduct.atlassian.net/browse/CX-3411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: SimilarToRecentlyViewed connection

src/schema/v2/me/newWorksFromGalleriesYouFollow.ts
Only load artworks for sale for newWorksFromGalleriesYouFollow (we do the same on the home screen module resolver).
=> fix: Only load artworks for sale for newWorksFromGalleriesYouFollow

src/schema/v2/me/showsByFollowedArtists.ts
Addresses [CX-3475]
Change ShowsByFollowedArtists default sorting to `-created_at` to show the most recently published shows first. Before the sorting defaulted to [start_at](https://github.com/artsy/gravity/blob/main/app/api/v1/me_follow_shows_endpoint.rb#L36)
[CX-3475]: https://artsyproduct.atlassian.net/browse/CX-3475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Change ShowsByFollowedArtists default sorting to created_at desc

_schemaV2.graphql, src/schema/v2/consignments/createConsignmentInquiryMutation.ts
co-authored-by: Daria Kozlova <daria.kozlova@artsymail.com>
This PR enables optionally specify specify recipient_email in the ConsignmentInquiryMutation.
The recipient_email is the email of any of the collector services team member for whom an Inquiry is specific for.
=> Feat(CX-3410): Introduce optional recipient_email to ConsignmentInquiryMutation

src/schema/v2/artwork/__tests__/artwork.test.js, src/schema/v2/artwork/index.ts, src/schema/v2/edition_set.ts, src/schema/v2/me/__tests__/newWorksByInterestingArtists.test.ts, src/test/fixtures/gravity/order.json, src/types/runtime/gravity/Artwork.ts, src/types/runtime/gravity/EditionSet.ts
Addresses: https://artsyproduct.atlassian.net/browse/PX-5026
Removing usage of deprecated concept of `availability_hidden` for artworks and edition sets
=> chore(PX-5026): Remove references to artwork availability_hidden

_schemaV2.graphql, src/schema/v2/artwork_version.ts
https://artsyproduct.atlassian.net/browse/TX-1061
Following the [Gravity work](https://github.com/artsy/gravity/pull/16132/files), this exposes provenance and condition description fields in artwork versions.
Artwork version is only exposed through [stitching](https://github.com/artsy/metaphysics/blob/75106b0c6e05e1543e83a1c0f39feddf3b5965c7/src/lib/stitching/exchange/v2/stitching.ts#L265), and I still want to find a better way of testing it. This PR should unblock UI work first.
=> feat: expose provenance and condition description in artwork versions

_schemaV2.graphql, src/schema/v2/me/sendIdentityVerficationEmailMutation.ts
This PR introduces `sendEmail` as a field that can be included in a mutation to request an IDV (identity verification) creation. It will instruct downstream services to not send an automated email after the IDV record has been created. Its purpose is to allow admins to send custom-made emails to collectors who need a more hands-on experience.
=> feat: allow optional identity verification emails (PRO-79)

src/schema/v2/CollectorProfile/__tests__/updateCollectorProfileWithID.test.ts, src/schema/v2/CollectorProfile/collectorProfile.ts, src/schema/v2/me/__tests__/collector_profile.test.js, src/schema/v2/me/__tests__/update_collector_profile.test.js, src/schema/v2/partner/__tests__/partnerInquirerCollectorProfile.test.ts
This PR resolves [CX-3459]
This PR is a follow-up on artsy/gravity#16149 🔒
This PR updates the collector profile fields (`email`, `name`, `location`, `profession`) to use the `owner` property in the JSON response to eliminate the caching issue with the collector profile
[CX-3459]: https://artsyproduct.atlassian.net/browse/CX-3459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-3459): Update collector profile resolvers

src/schema/v2/home/results.ts, src/schema/v2/me/__tests__/recentlyViewedArtworks.test.ts, src/schema/v2/me/recentlyViewedArtworks.ts
Reverts artsy/metaphysics#4867
Reverting rather than fixing because we should just fix this in Gravity if it's actually a problem. @mzikherman states that Gravity should be returning artworks in the order they are requested in.
That said: the reason this is causing a problem is because you'd want to just use a sort function not a map + find. Gravity might not return all the artworks, so where an ID might be missing this is returning a `null`.
=> Revert "fix: Sort recently viewed artworks correctly"
