_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap

followup from https://github.com/artsy/gravity/pull/13344

pulling gravity schema

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap

https://artsyproduct.atlassian.net/browse/FX-2128
Follow-up to https://github.com/artsy/gravity/pull/13346

Bump gravity schema, to get totalCount in connections

---

hokusai/production.yml
hokusai/staging.yml

Connections through ELBs from external clients should be routed through Nginx.

route external clients through nginx

---

_schema.graphql
_schemaV2.graphql
src/data/convection.graphql

[Stitching] Expose published_at field from Convection 

---

src/lib/stitching/gravity/stitching.ts

Remove unused code block

---

_schemaV2.graphql
src/schema/v2/Feature/FeatureLayoutsEnum.ts
src/schema/v2/Feature/FeatureType.ts
src/schema/v2/__tests__/Feature.test.ts
src/types/runtime/gravity/Feature.ts

Re: [FX-2132](https://artsyproduct.atlassian.net/browse/FX-2132)
(The Gravity side of this is already in production)

[FX-2132] Exposes Feature#layout

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap

https://artsyproduct.atlassian.net/browse/FX-2123
Follow up to https://github.com/artsy/gravity/pull/13363

Bump Gravity schema to get artistSeries.artworksCount

---

_schemaV2.graphql
src/schema/v2/fair.ts

Re: [FX-2171](https://artsyproduct.atlassian.net/browse/FX-2171)

[FX-2171] Adds Fair#articlesConnection

---

src/lib/stitching/causality/stitching.ts

My apologies. I left a debugging statement in my previous pr.
#minor #mergeongreen

remove stray log

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Adds a couple more fields to our MyCollection mutations. 
(Pretty trivial so just gonna merge.)

[MyCollection] Add title and year

---

_schemaV2.graphql
src/schema/v2/me/myCollection.ts

Related https://github.com/artsy/gravity/pull/13433 
Adds additional sort parameters to our artworks connection.

[MyCollection] Add sorting to connection

---

hokusai/production.yml
hokusai/staging.yml

Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-2602
Will follow-up with a PR here and in Substance to switch Cloudflare and CoreDNS DNS records.

add Ingress resources

---

scripts/push-schema-changes.js

Today there were several stop-and-go moments while trying to release minor changes to Volt. Metaphysics' schema would undergo modifications, and suddenly the pending Volt release would be blocked on new conflicts (necessitating a manual `rake graphql:schema:update`, PR, merge, build, and release).
@damassi suggested we push schema updates to Volt much like we already do to Force and Eigen.
Volt uses [artemis](https://github.com/yuki24/artemis#the-convention), which expects a JSON-formatted GraphQL schema at a particular file location. I had to hack up the original script to operate in these 2 modes: `.graphql` (with `relay-compiler` and a `data/schema.graphql` file) or `.json` (at an arbitrary other path).
There's some work in progress …

Push schema changes to non-relay clients like Volt, too

---

src/lib/sponsoredContent/data.json

Apparently this is the correct one!

Update slug for sponsored content

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

A couple light changes:
- Make dimensions optional
- Add `category`
- Add `metric` 
#trivial

[MyCollection] Update input fields 

---

_schemaV2.graphql
src/lib/stitching/kaws/__tests__/stitching.test.ts
src/lib/stitching/kaws/stitching.ts
src/schema/v2/fair.ts

Pretty straightforward, uses the slugs field from https://github.com/artsy/gravity/pull/13454

@anandaroop => [Fair] Stitch in marketingCollections under a fair

---

src/schema/v2/me/myCollection.ts

Remove log

---

_schema.graphql
_schemaV2.graphql
src/data/diffusion.graphql

Following up on https://github.com/artsy/diffusion/pull/329 this PR updates MP with the latest from diffusion.

Update diffusion schema

---

hokusai/production.yml
hokusai/staging.yml

Cleanup ELB services and Nginx sidecar containers
```
kubectl delete  service metaphysics-web
```

#MIGRATION remove nginx sidecars - ELB service and internal service ports

---

_schemaV2.graphql
src/schema/v2/sale/__tests__/index.test.ts
src/schema/v2/sale/index.ts

https://artsyproduct.atlassian.net/browse/AUCT-1218

Add collectPayments flag to Sale

---

src/schema/v2/sale/index.ts

handle null case for collectPayments since it's a new field

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionDeleteArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Adds two new fields to the artwork model:
- `costMinor`
- `costCurrencyCode` 
And additionally updates My Collection mutations with these two new fields.

[Artwork] Add costMinor and costCurrencyType and update MyCollection mutations

---

_schemaV2.graphql
src/schema/v2/fair.ts

Allows string fields to be formatted as Markdown

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Follow up to #2721. `editionNumber` should be a string, rather than an integer.

Change Artwork editionNumber field to String

---

src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Related: https://github.com/artsy/metaphysics/pull/2734
I believe we've identified this payload computation is a place we could improve things, but I just wanted to fix it for now. Going to mark this MOG but happy to revisit if there are ideas about a better approach.
/cc @artsy/csgn-devs @joeyAghion

Fix the update mutation too

---

src/schema/v1/__tests__/partner_show_events.test.ts
src/schema/v2/__tests__/show_events.test.ts

Chatter over here:
https://artsy.slack.com/archives/C02BC3HEJ/p1601567857100300
But in an effort to un-block the master branch I'm going to pend these tests. We can follow up if/when we can remember what this was all about. 😝

Pend some time-bombs to unblock master branch

---

_schemaV2.graphql
src/schema/v2/me/__tests__/followed_galleries.test.ts
src/schema/v2/me/followed_galleries.ts
src/schema/v2/me/index.ts

Adds a followedGalleriesConnection to the Me type

feat: followed galleries

---

_schemaV2.graphql

All I did here was dump the local schema to get things back in sync:
```
jon@juggernaut:~/code/metaphysics(master)% fup
upstream
HEAD is now at 8b74dddf Merge pull request #2763 from mdole/viewing-rooms-search
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:jonallured/metaphysics.git
7cc291d1..8b74dddf  master -> master
13:14:40
jon@juggernaut:~/code/metaphysics(master)% yarn dump:local
yarn run v1.22.5
$ yarn dump-schema v1 _schema.graphql & yarn dump-schema v2 _schemaV2.graphql & wait
$ babel-node --extensions '.ts,.js' ./scripts/dump-schema.ts v1 _schema.graphql
$ babel-node --extensions '.ts,.js' ./scripts/dump-schema.ts v2 _schemaV2.graphql
[V1] [FEATURE] Enabling Schema Stitching
[V1] [FEATURE] Enabling Schema Stitching
[V2] [FEATURE] Enabling Schema Stitching …
```

Fix mysterious schema drift

---

src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

This PR builds on top of https://github.com/artsy/gravity/pull/13559 and is a sibling of https://github.com/artsy/metaphysics/pull/2755. This PR moves us to using the basic artwork endpoints for create/update.
https://artsyproduct.atlassian.net/browse/CX-676
https://artsyproduct.atlassian.net/browse/CX-677

Use basic endpoints to create/update My Collection artworks

---

.vscode/settings.json
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts
src/schema/v2/inquiry_question.ts

Co-authored-by: Sepand Ansari <sepans@sepans.com>
cc @artsy/purchase-devs 
https://artsyproduct.atlassian.net/browse/PURCHASE-2134

feat: [PURCHASE-2134] Set up Artwork resolver to query Gravity's inquiry request questions endpoint

---

_schemaV2.graphql
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts

https://artsyproduct.atlassian.net/browse/CX-714
@ansor4, wanted to make sure this approach makes sense to you. We would like to start using an array, so that we don't have to add a new field to `me` every time we add a new lab feature.

feat: Add me.labFeatures

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/stitching.ts
src/schema/v2/show.ts

This adds in `viewingRoomsConnection` under the `Show` type, to support including that information in the new show views.

@dzucconi => [Show] Stitch in viewingRoomsConnection

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/conversation/__snapshots__/submit_inquiry_request_mutation.test.ts.snap
src/schema/v2/me/__tests__/conversation/submit_inquiry_request_mutation.test.ts
src/schema/v2/me/conversation/submit_inquiry_request_mutation.ts
src/schema/v2/schema.ts

[PURCHASE-2133]
Sample query/response
```graphql
mutation sendinquiry {
submitInquiryRequestMutation(input: {
inquireableID: "yaacov-agam-color-pyramids",
inquireableType: "Artwork"
questions: [
{questionID: "price_and_availability"},
{questionID:"shipping_quote", details: "{ \"address\": \"112 Main st Brooklyn NY 11211\"}"}]
}) {
inquiryRequest {
inquireable {
__typename
... on Artwork {
title
artists {
name
birthday
}
partner {
name
}
}
}
inquirer {
name
email
}
shippingLocation {
address
city
country
}
inquiryQuestions
}
}
}
```
Response: 
```json
{
"data": {
"submitInquiryRequestMutation": {
"inquiryRequest": {
"inquireable": {
"__typename": "Artwork",
"title": "Color Pyramids",
"artists": [
{
"name": "Yaacov Agam",
"birthday": "1928"
}
],
"partner": {
"name": "Ai Bo Gallery"
}
}, …
```

feat: Add `SubmitInquiryRequestMutation` for artwork inquiry

---

src/schema/v2/sale/__tests__/index.test.ts
src/schema/v2/sale/display.ts
src/schema/v2/sale/index.ts

**Description:** 
- Format displayTimeleyAt according to the user timeZone
**Context**: https://artsy.slack.com/archives/CCS8TMQ0K/p1603808304011900?thread_ts=1603808248.010400&cid=CCS8TMQ0K
**Jira ticket**: https://artsyproduct.atlassian.net/browse/CX-757
Co-authored-by: David Sheldrick <djsheldrick@gmail.com>

fix: format displayTimeleyAt according to the user timeZone

---

src/data/kaws.graphql
src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
src/lib/stitching/kaws/__tests__/stitching.test.ts
src/lib/stitching/kaws/stitching.ts

Fixes https://artsyproduct.atlassian.net/browse/FX-2343?atlOrigin=eyJpIjoiY2NlZGViMDlhZDg0NGVkYjlhYmVjY2VmMDljYTUwODUiLCJwIjoiaiJ9

@dzucconi => feat: stitch internalID into MarketingCollection

---

_schema.graphql
_schemaV2.graphql
src/data/diffusion.graphql

Updates Metaphysics's schema to incorporate changes in Diffusion's schema.

Update schema reflecting Diffusion changes #trivial

---

src/schema/v2/__tests__/fair.test.js
src/schema/v2/fair.ts

feat: update fair href to point to new page structure

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
src/lib/stitching/gravity/stitching.ts

chore(graphql): remove unused field argument `published`

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts
src/schema/v2/edition_set.ts

completes https://artsyproduct.atlassian.net/browse/CX-788

Feature: Add sizeScore to artwork and editionSet

---

_schema.graphql
_schemaV2.graphql
src/data/convection.graphql

Companion to https://github.com/artsy/convection/pull/860

chore: update convection schema

---

.vscode/settings.json

Everything works locally, I think there are the current recommended options.

chore: some vscode settings/prettier updates

---

src/lib/sponsoredContent/data.json

> In collaboration with Acute Art, leading producer of visionary virtual and augmented reality (AR) artworks, and Lu Yang, BMW will present a new AR work where “DOKU”, the artist’s digital avatar, takes over the physical world in the form of a giant dancing superhero. The installation, titled “Gigant DOKU”, is developed by a game engine and incorporates motion capture image data from Tokyo and Bali gathered during the artist’s BMW Art Journey.
Press Release: https://www.press.bmwgroup.com/global/article/detail/T0321554EN/bmw-announces-collaboration-with-acute-art-to-realize-a-project-with-bmw-art-journey-awardee-lu-yang-lu-yang-presents-latest-artworks-in-art-basel-s-%E2%80%9Covr:-miami-beach%E2%80%9D
Jira 🔒 : https://artsyproduct.atlassian.net/browse/FX-2501

feat: add sponsored content for Art Basel OVR:2020

---

_schemaV2.graphql
src/lib/helpers.ts
src/lib/loaders/index.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v1/__tests__/artists.test.js
src/schema/v1/__tests__/fair.test.js
src/schema/v1/artists.ts
src/schema/v1/artwork_version.ts
src/schema/v1/fair.ts
src/schema/v1/filter_artworks.ts
src/schema/v2/__tests__/artists.test.ts
src/schema/v2/__tests__/fair.test.js
src/schema/v2/__tests__/filterArtworksConnection.test.ts
src/schema/v2/artists.ts
src/schema/v2/artwork_version.ts
src/schema/v2/fair.ts
src/schema/v2/filterArtworksConnection.ts
src/schema/v2/schema.ts
src/schema/v2/sorts/artist_sorts.ts

Closes: [FX-2512](https://artsyproduct.atlassian.net/browse/FX-2512)

feat(fx-2512): exposes artists connection; supports letter argument

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Task for [CX-602].
[CX-602]: https://artsyproduct.atlassian.net/browse/CX-602

chore: Add provenance to My Collection Artwork mutations

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/diffusion.ts
src/schema/v1/__tests__/auction_results.test.js
src/schema/v1/artist/index.ts
src/schema/v2/__tests__/auction_result.test.ts
src/schema/v2/__tests__/auction_results.test.js
src/schema/v2/artist/index.ts
src/schema/v2/auction_result.ts
src/schema/v2/schema.ts

The type of this PR is: Feature
This PR helps resolve https://artsyproduct.atlassian.net/browse/CX-740
- Expose auctionResult type

feat: add auction result type

---

_schemaV2.graphql
src/schema/v2/__tests__/auction_result.test.ts
src/schema/v2/auction_result.ts

- Expose `location` on auctionResult

feat: expose auctionResult location

---

src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Follow up to #2893 — I forgot that we have the same logic in this mutation too.

fix(my collection): update MyCollectionUpdateArtwork mutation to avoid gravity race condition

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/stitching.ts

Co-authored-by: Sepand Ansari <sepand.ansari@artsymail.com>
This PR merges gravity schema that includes new `userAddress` type and `userAddressConnection`. The PR also stitches in the `addressConnection` query. 
Jira ticket [2291](https://artsyproduct.atlassian.net/browse/PURCHASE-2291)

feat: Stitch addressConnection into Me query and merge gravity schema

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Jira ticket: https://artsyproduct.atlassian.net/browse/CX-945
This is my first time using the `Money` type, so I need help figuring out why `display` isn't working.
Related Gravity PR: https://github.com/artsy/gravity/pull/13766

add pricePaid to artworks

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

This commit didn't get pushed to the previous PR https://github.com/artsy/metaphysics/pull/2929 before merging.

fix: use amount helper for pricePaid display

---

src/schema/v2/show.ts

Thanks for spotting this @mzikherman

fix(show): avoids swallowing error

---

_schemaV2.graphql
src/schema/v2/show.ts

feat(show): exposes online exclusive flag

---

_schemaV2.graphql
src/schema/v2/aggregations/filter_artworks_aggregation.ts

Support artwork filter aggregation for classification / attribution class.
Jira: [FX-2626]
[FX-2626]: https://artsyproduct.atlassian.net/browse/FX-2626

feat: support artwork classification aggregation

---

_schemaV2.graphql
src/schema/v2/aggregations/filter_artworks_aggregation.ts
src/schema/v2/filterArtworksConnection.ts

**Request**
```graphql
{
artworksConnection(first: 0, aggregations: [ARTIST_NATIONALITY], artistNationalities: ["French", "British"]) {
aggregations {
counts {
name
count
}
}
}
}
```
**Response**
```json
{
"data": {
"aggregations": [
{
"counts": [
{
"name": "British",
"count": 12
},
{
"name": "French",
"count": 1
}
]
}
]
}
}
}
```

feat: support artwork artist nationality filtering and aggregation

---

src/schema/v2/__tests__/fairsConnection.test.ts

Just following up https://github.com/artsy/metaphysics/pull/2927 with a simple spec

test(fairsconnection): adds simple specs

---

_schemaV2.graphql
src/schema/v2/aggregations/filter_artworks_aggregation.ts
src/schema/v2/filterArtworksConnection.ts

Pretty simple, just adding the arg and enum declaration.

chore: expose colors + partner(s) for filtering API

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Reverts artsy/metaphysics#2942

Revert "feature: Artwork price paid mutations for artworks"

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Follow-up to reverted #2942 due to rebase confusion.

feature: Artwork price paid mutations for artworks

---

scripts/push-schema-changes.js

Should fix https://artsy.slack.com/archives/CP9P4KR35/p1612820275253800
Gonna self merge

chore(CI): Set ignore-engines globally when pushing schema changes

---

_schemaV2.graphql
src/schema/v2/filterArtworksConnection.ts

exposes https://github.com/artsy/gravity/pull/13841 (when merged)

chore: expose additionalGeneIDs arg to filterArtworskConnection

---

src/lib/apis/fetch.ts
src/lib/loaders/__tests__/request_id.test.js
src/lib/loaders/__tests__/user_agent.test.js
src/lib/loaders/api/index.ts
src/lib/loaders/api/loader_interface.ts
src/lib/loaders/api/loader_with_authentication_factory.ts
src/lib/loaders/api/loader_without_authentication_factory.ts

A little clunky, but works! Closes https://artsyproduct.atlassian.net/browse/PLATFORM-3080 (more discussion there).

fix: use a request body instead of query params for PUT/POST/DELETE

---

src/lib/apis/fetch.ts
src/lib/loaders/__tests__/request_id.test.js
src/lib/loaders/__tests__/user_agent.test.js
src/lib/loaders/api/index.ts
src/lib/loaders/api/loader_interface.ts
src/lib/loaders/api/loader_with_authentication_factory.ts
src/lib/loaders/api/loader_without_authentication_factory.ts

Reverts artsy/metaphysics#2996
Seeing some weirdness (collection pages 500'ing), something is not perfectly correct with this.

Revert "fix: use a request body instead of query params for PUT/POST/DELETE"

---

src/lib/__tests__/apis/fetch.test.ts
src/lib/apis/fetch.ts

Rather than futz with loader factories and trying to thread params through all the way to `fetch`, (and also punting on a larger refactor of some of the loader...management and creation, since the factories can be very challenging), why not just decode the query params in `fetch`?
The code which creates the URL w/ query params is very simple: https://github.com/artsy/metaphysics/blob/e8d43693aba2651a2bdacee7f7ee7f6e6e6255b4/src/lib/helpers.ts#L76
It always appends a `?` and a `qs.stringify` call (specifying the `brackets` format for arrays (`?a[]=...&a[]=...`), and also sorting the query params within the string which increases the cache hit ratio). When we decode using `qs.parse`, we shouldn't have to worry about any of that. All the various array formats are supported via `parse` …

fix: dont send PUT/POST parameters as query params, but into the request body

---

_schemaV2.graphql
src/schema/v2/filterArtworksConnection.ts

feat: add locationCities to filter args

---

src/lib/gravityErrorHandler.ts
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionDeleteArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Allow deleting pricePaid information from My Collection artworks.
https://artsyproduct.atlassian.net/browse/CX-945
- Returns null when price_paid_cents is not populated on an artwork to avoid type issues with Money requiring all fields to be populated
- Fixes a bug with error formatting for the my collection update artwork mutation

fix: price paid delete

---

src/lib/sponsoredContent/data.json

**From:** https://www.bmw-arts-design.com/artsy
**To:** https://emt.bmw-arts-design.com/bmw-art-guide?partner=q73iAFGdha
Jira: [FX-2722]
[FX-2722]: https://artsyproduct.atlassian.net/browse/FX-2722

chore: update bmw arts design sponsored content link

---

src/schema/v2/__tests__/partner.test.js
src/schema/v2/partner.ts

- Created a connectionArticles feature to a patner to be able fetching articles by a partner ID
- Created a test for the feature
link to the Jira task -> https://artsyproduct.atlassian.net/browse/PX-3833

feat: Create partner -> articles connection

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myBids.test.ts
src/schema/v2/me/myBids.ts
src/schema/v2/sale_artwork.ts

Just a small rename to better reflect the actual function -> lot = sale artwork -> lot state = saleArtwork lot state.

refactor: Rename SaleArtwork.lot to lotState

---

_schemaV2.graphql

whoops! just ran a `yarn dump:local` to update the MP schemas

chore: run yarn dump:local to get schema up-to-date

---

_schema.graphql
_schemaV2.graphql
src/data/exchange.graphql

Follow up to PURCHASE-2500 updates exchange schema in MP

feat: Update exchange schema with `states`

---

src/schema/v2/partner.ts
src/schema/v2/sorts/article_sorts.ts

Added pagination for articles page
JIRA - https://artsyproduct.atlassian.net/browse/PX-3828
Screenshot:

feat: Add articles pagination

---

src/schema/v2/me/myBids.ts

This turned out to be a pretty minor change all said. Rather than just returning early with sales that include a watched lot, we concatenate the watched lots array with the other lots, and if a user has bid on a lot that they've already watched, we filter out the watched lot and just return the one that they bid on so there aren't duplicates, reflecting the current state of the in progress sale (in the UI: user has bid, doesn't care about the fact that they've watched anymore). 
This pr is mostly just shuffling code around a bit, but the final outputted schema doesn't change at all, so nothing different with the tests. Gonna merge to get this to staging but happy to follow up.
@artsy/grow-devs

fix: Merge watched and bidded-on artworks

---

_schemaV2.graphql
src/schema/v2/partner.ts
src/schema/v2/profile.ts

Added `displayArtistsSection` and `profileArtistsLayout` fields to `Partner` entity.

fix: use fields from partner entity instead of profile.

---

_schemaV2.graphql
src/schema/v2/gene.ts

Closes: [FX-2856](https://artsyproduct.atlassian.net/browse/FX-2856)

feat(gene): converts description to markdown field

---

src/schema/v2/me/__tests__/follow_gene.test.ts

Resolves [FX-2876]
[FX-2876]: https://artsyproduct.atlassian.net/browse/FX-2876

fix: make follow gene test more specific

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

MP follow up for this pr: https://github.com/artsy/gravity/pull/13995 
Next step in completing PURCHASE-2593

feat: add vat_requirement_complete to artwork

---

_schemaV2.graphql
src/schema/v2/input_fields/event_status.ts

This PR adds `ALL` filter option to the `EventStatus` enum.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3970

feat(PX-3970): Add ALL filter option

---

_schema.graphql
_schemaV2.graphql
src/data/exchange.graphql

waiting for exchange deploy....

Update exchange schema (add `hasDefiniteTotal`)

---

src/schema/v2/partner.ts

JIRA
- [shows tab pagination](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3972&quickFilter=228)

feat: add page cursors for showsConnection

---

src/schema/v2/partner.ts

- Jira -> [Pagination on reload defect](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4035&quickFilter=228)
Minor fix: added page type to articles and shows connection

fix: Add page type in args

---

_schemaV2.graphql

Updates schema

---

_schemaV2.graphql
src/schema/v2/partner.ts
src/schema/v2/profile.ts

JIRA -> [create about partner component on overview page](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4019&quickFilter=228)
Added fields:
- vatNumber for VAT ID number display
- fullBio for displaying full bio

feat: Add vatNumber and fullBio fields

---

_schemaV2.graphql
src/schema/v2/partner.ts

JIRA -> [Works tab displays when it is off on CMS](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4098&quickFilter=228)
Added a flag connected with CMS which responsible for displaying the works tab on PPP

feat: add flag for works tab display

---

.circleci/config.yml

Noticed that type-checking was missing from our CI flows

ci: Add type-checking to CI flow

---

_schema.graphql
_schemaV2.graphql
src/data/diffusion.graphql
src/lib/stitching/diffusion/link.ts
src/lib/stitching/diffusion/schema.ts
src/lib/stitching/diffusion/v2/stitching.ts
src/lib/stitching/mergeSchemas.ts

Jira: https://artsyproduct.atlassian.net/browse/CX-1475
related Metaphysics PR: https://github.com/artsy/diffusion/pull/450

feat:allow querying auction results by a list of artist IDs

---

_schemaV2.graphql
src/schema/v2/article.ts
src/schema/v2/articlesConnection.ts
src/schema/v2/artist/index.ts
src/schema/v2/me/__tests__/articlesConnection.test.ts

Addresses [CX-1400]
[CX-1400]: https://artsyproduct.atlassian.net/browse/CX-1400

feat: add vertical field and in editorial feed flag to articles query

---

_schemaV2.graphql

This is to add the schema update from my GRO-350 PR

forgot to include a schema update for my GRO-350 PR

---

_schemaV2.graphql
src/schema/v2/__tests__/partner.test.js
src/schema/v2/partner.ts

This PR adds the ability to identify which type of partner page should be used.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4079

feat(PX-4079): partner profile page states

---

src/schema/v1/artwork/artworkContextGrids/ArtistArtworkGrid.ts
src/schema/v1/artwork/artworkContextGrids/__tests__/auctionContext.test.ts
src/schema/v1/artwork/artworkContextGrids/__tests__/defaultContext.test.ts
src/schema/v1/artwork/artworkContextGrids/__tests__/fairContext.test.ts
src/schema/v1/artwork/artworkContextGrids/__tests__/showContext.test.ts
src/schema/v1/artwork/artworkContextGrids/index.ts
src/schema/v2/artwork/artworkContextGrids/ArtistArtworkGrid.ts
src/schema/v2/artwork/artworkContextGrids/__tests__/auctionContext.test.ts
src/schema/v2/artwork/artworkContextGrids/__tests__/defaultContext.test.ts
src/schema/v2/artwork/artworkContextGrids/__tests__/fairContext.test.ts
src/schema/v2/artwork/artworkContextGrids/__tests__/showContext.test.ts
src/schema/v2/artwork/artworkContextGrids/index.ts

This PR resolves [FX-3002]
The type of this PR is: **Feature**
Description: "Other works by artist" rail should display available works only
[A little discussion in slack](https://artsy.slack.com/archives/CP9P4KR35/p1623674672071700)
https://user-images.githubusercontent.com/3513494/121940509-daffa280-cd56-11eb-8335-2164fcdb858a.mp4
[FX-3002]: https://artsyproduct.atlassian.net/browse/FX-3002

feat: request only available for sale artist artworks

---

_schemaV2.graphql
src/schema/v2/artist/index.ts

Addresses [CX-1594]
Depends on https://github.com/artsy/diffusion/pull/454
[CX-1594]: https://artsyproduct.atlassian.net/browse/CX-1594

feat: Add ability to search artist auction results by keyword

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap

fix: update search criteria width type to string

---

renovate.json

cc @joeyAghion 
I'll be opening up a few of these PRs. I've set @mzikherman as the Assignee given he was already a reviewer, but y'all can feel free to update to whomever you need.

Remove me from renovate.json

---

_schema.graphql
_schemaV2.graphql
src/data/convection.graphql

Related to this PR on convection: https://github.com/artsy/convection/pull/1091

update: coa fields on convection schema

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap

Part of https://artsyproduct.atlassian.net/browse/FX-3045
This propagates the breaking changes to the Gravity GraphQL schema, resulting from https://github.com/artsy/gravity/pull/14207

chore(saved search): update gravity gql schema

---

_schemaV2.graphql

ran `yarn dump:local` and committed those changes, this should probably be automated!

chore: dump MP schema

---

_schema.graphql
_schemaV2.graphql
src/data/exchange.graphql

Propagating exchange schema changes from this PR: https://github.com/artsy/exchange/pull/777

chore: update exchange gql schema

---

_schemaV2.graphql
src/schema/v2/shows.ts

To support the v3 shows page we need to add this argument to replicate the feed API functionality.

feat(shows): adds filter for event status

---

src/schema/v2/show.ts

Returns the `totalCount` along with the connection.

fix(show): returns total count for artworks connection

---

src/schema/v2/home/results.ts

Type: **Feature**
Jira ticket: [FX-1834)](https://artsyproduct.atlassian.net/browse/FX-1834)
Changes on the Gravity side: [PR 14217](https://github.com/artsy/gravity/pull/14217)
Requests similar works that are available for sale only (_where it is supported_)

feat: show only for_sale artworks on "similar grid"

---

_schema.graphql
_schemaV2.graphql
src/data/exchange.graphql

Updating the exchange schema in the context of https://github.com/artsy/exchange/pull/795

update: add estimated schedule details to exchange schema

---

_schemaV2.graphql

Related https://github.com/artsy/metaphysics/pull/3291
This PR adds the missing schema contents of the work completed in #3291.

Add missing dumped schema

---

_schemaV2.graphql
src/schema/v2/fair_organizer.ts

Allow client to query for articles associated with any fairs associated with a fair organizer.
Capped to support at most 100 fairs for a particular fair organizer which should be more than enough to support all current fair organizers.
Jira: [FX-3152]
[FX-3152]: https://artsyproduct.atlassian.net/browse/FX-3152
**Request**
```graphql
{
fairOrganizer(id: "the-armory-show") {
articlesConnection(first: 5, inEditorialFeed: false, sort: PUBLISHED_AT_DESC) {
totalCount
edges {
node {
title
publishedAt
author {
name
}
}
}
}    
}
}
```
**Response**
```json
{
"data": {
"fairOrganizer": {
"articlesConnection": {
"totalCount": 159,
"edges": [
{
"node": {
"title": "What Sold during Armory Week",
"publishedAt": "2020-03-09T17:07:10.641Z",
"author": {
"name": "Artsy Editorial"
}
}
},
{
"node": { …
```

feat: add articlesConnection to FairOrganizer type

---

src/schema/v2/__tests__/fair_organizer.test.ts
src/schema/v2/fair_organizer.ts

Follow up to #3320 and #3321 to add test coverage.
cc/ @damassi

test: improve test coverage of fairOrganizer field

---

_schema.graphql
_schemaV2.graphql
src/data/exchange.graphql

This PR updates gql schema from exchange.

chore: update exchange schema

---

src/schema/v2/system/algolia/__tests__/index.test.ts
src/schema/v2/system/algolia/index.ts

And add a spec to ensure it works this time 😅
Follow-up to #3345

fix: update algolia appID return

---

package.json
yarn.lock

See https://github.com/artsy/express-reloadable/pull/45

lib: bump express-reloadable

---

Dockerfile

Add bash for post-deploy hook.

fix: Need Bash for Post Deploy

---

_schemaV2.graphql
src/schema/v2/External/External.ts
src/schema/v2/External/ExternalAuctionHouse.ts
src/schema/v2/External/ExternalFair.ts
src/schema/v2/External/ExternalGallery.ts

fix(external): uses id fields

---

_schemaV2.graphql
src/schema/v2/me/update_collector_profile.ts

fix(mutations): use correct name for collector profile input attr

---

_schemaV2.graphql
src/lib/helpers.ts
src/schema/v2/location.ts
src/schema/v2/me/index.ts
src/schema/v2/me/myLocation.ts

feat(me): exposes additional fields for inquiry flow

---

_schemaV2.graphql
src/schema/v2/me/conversation/submit_inquiry_request_mutation.ts

Needed for the specialist contact inquiry form.

feat(inquiry): adds contact gallery field

---

src/schema/v2/home/home_page_artwork_modules.ts

Noticed that the `exclude` key wasn't being fully respected. This fixes that and makes the logic a little more linear.

fix: [HomePageArtworkModules] Respect exclude argument

---

package.json
src/index.ts
yarn.lock

Upgrade to @artsy/morgan removing the installation that used the git
address.

chore: @artsy/morgan

---

src/schema/v2/profile.ts

Adds a new `location` field to the `Profile` type and a little bit of alphabetization cleanup.

feat: [Profile] Add `location` field

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/page.ts
src/schema/v2/schema.ts

feat(schema): exposes page

---

src/schema/v2/__tests__/shows.test.js
src/schema/v2/shows.ts

Previously `hasNextPage` was always `false`

fix(showsconnection): uses connection from array slice

---

src/schema/v2/city/index.ts

We've somehow managed to do pagination completely differently for every field, and haven't done anything like created a consistent type for what's desirable. This PR adds the `pageCursors` field for `city#showsConnection` which is non-nullable if you're trying to do pagination.

fix(cities): adds pagecursors to shows field

---

src/schema/v2/city/index.ts

So this is a little odd but I think ultimately makes sense. See this comment thread for some discussion: https://github.com/artsy/force/pull/6956#discussion_r567112791

feat(city): adds support for online exclusives

---

package.json
yarn.lock

Reverts artsy/metaphysics#3460 in favor of #3461

Revert "Revert "chore(deps): update dep typescript from 4.3.5 to v4.4.3""

---

src/data/exchange.graphql

Those exchange updates to propagate here.

chore(PX-4675): update exchange schema to latest

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/index.ts

In support of [GRO-596](https://artsyproduct.atlassian.net/browse/GRO-596), this PR exposes additional fields on `me`

feat(me): exposes additional fields for settings

---

src/schema/v2/me/savedArtworks.ts

Another day, another connection to fix pagination for.

fix(saved-artworks): fixes pagination for saved artworks

---

_schemaV2.graphql
src/schema/v2/me/savedArtworks.ts

Minor thing: this already works; but we needed to add the args.

fix(saved-artworks): adds page & size args

---

_schemaV2.graphql
src/lib/shared_resolvers/followedArtistsResolver.ts
src/schema/v2/me/followed_artists.ts

Fixes the pagination for `me.followsAndSaves.artistsConnection`

fix(me): fixes pagination count, cursors, and page/size support

---

_schemaV2.graphql
docs/pagination.md
src/lib/helpers.ts
src/schema/v2/fields/pagination.ts
src/schema/v2/me/followed_genes.ts
src/schema/v2/me/savedArtworks.ts

Minor fix but I added a helper and some docs for doing pagination since it's incomplete or broken in almost every implementation.

feat(GRO-595): fixes followed genes pagination

---

_schemaV2.graphql
src/schema/v2/me/followedProfiles.ts
src/schema/v2/me/index.ts

Required for the "Follows & Saves" portion of settings.

feat(GRO-595): exposes followed profiles field on me

---

_schema.graphql
_schemaV2.graphql
src/data/convection.graphql

Within the scope of [SWA-100](https://artsyproduct.atlassian.net/browse/SWA-100), we are updating the schema in Convection for add asset mutations. 
This PR is an extension of that work, updating the schemas here in MP.

[chore-ish]: Update convection schema with sessionID for asset mutations

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Reverts artsy/metaphysics#3568

Revert "[COORDINATE-DEPLOY] feat: relax VAT requirements for artworks (TX-135)"

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/updateMyPasswordMutation.ts
src/schema/v2/schema.ts

Supports https://github.com/artsy/force/pull/8997

feat: adds update password mutation

---

scripts/push-schema-changes.js

This PR updates the target branch for Eigen to be the new default branch "main" instead of "master".
PS: I already updated the default branch Eigen to be **main**
This comes as a follow-up from this [RFC](https://github.com/artsy/README/issues/386)

chore: Update target branch on update repo for Eigen [RFC Follow-up]

---

.circleci/config.yml
README.md
dangerfile.ts
docs/dataloaders.md
scripts/push-schema-changes.js
scripts/schema-drift.ts
src/lib/modifyOldEigenQueries.ts

Favor inclusive language in the Metaphysics codebase per this [RFC][].
[RFC]: artsy/README#427

feat: adopt inclusive language - main default branch

---

_schema.graphql
_schemaV2.graphql
src/data/convection.graphql

Update convection schema
Resolve [SWA-164](https://artsyproduct.atlassian.net/browse/SWA-164)
Add new fields to Asset model and mutations([convection pull](https://github.com/artsy/convection/pull/1190))

feat[SWA-164] Add asset size and name on convection

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
src/lib/stitching/gravity/schema.ts

Includes new `key` attribute for algolia index configuration. The value is consistent across environments and can be used for specifying which indexes to support within the mobile app.

chore: update stitched gravity graphql schema

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

This PR helps in adding descriptions for My Collection artwork's location which is discussed [here](https://github.com/artsy/metaphysics/pull/3598#discussion_r769124885).

docs: Artwork's location description

---

src/schema/v2/me/__tests__/bidder_position.test.js
src/schema/v2/me/bidder_position_messages.ts

Metphysics component of: https://artsyproduct.atlassian.net/jira/software/c/projects/BID/boards/106?modal=detail&selectedIssue=BID-119&search=119

chore:update copy for reserve not met error message

---

_schema.graphql
_schemaV2.graphql
src/data/convection.graphql

[Convection pull](https://github.com/artsy/convection/pull/1192)
[SWA-108](https://artsyproduct.atlassian.net/browse/SWA-108) ticket
Change submission Graphql params

[SWA-108] Update convection schema

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/authenticationStatus.ts
src/schema/v2/schema.ts

Picking up from https://github.com/artsy/force/pull/9093 — this gives us a single field for determining auth status.

feat(schema): exposes a field for getting authentication status

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

This PR resolves to add attribution Class in MyCollection artwork - [CX-2224](https://artsyproduct.atlassian.net/browse/CX-2224)

feat: add attributionClass to MyCollectionCreateArtworkInput

---

src/schema/v2/partner.ts

**Do not merge this PR until the first part will be merged https://github.com/artsy/force/pull/7682**
The 3rd step of the partner profile page transition. https://github.com/artsy/force/pull/7611
JIRA - https://artsyproduct.atlassian.net/browse/PX-4058

feat(PX-4058): partner transition part 3

---

_schemaV2.graphql
src/schema/v2/me/__tests__/collector_profile.test.js
src/schema/v2/me/__tests__/update_me_mutation.test.js
src/schema/v2/me/collector_profile.ts
src/schema/v2/me/index.ts
src/schema/v2/me/update_me_mutation.ts

Relates to https://github.com/artsy/gravity/pull/14815

feat: expose collector profile privacy field

---

src/data/positron.graphql

feat(stitching): Update positron schema

---

_schemaV2.graphql
src/schema/v2/articlesConnection.ts

Adding the featured argument to support the editorial index page.

feat(articles): adds featured argument

---

README.md

Add link to the graphql workshop repo

docs(workshop): Add workshop link

---

_schemaV2.graphql
src/schema/v2/article/index.ts

We were doing this in a few places in Force.

feat(article): adds byline field

---

_schemaV2.graphql
src/schema/v2/me/index.ts
src/schema/v2/me/partners.ts

Exposes `me.partners` for the user's managed partners.
_Preliminary work for [hackathon](https://www.notion.so/artsy/Native-seller-app-8a23bf8241664b67a3a7f6f17e0ebaac)._

chore: expose me.partners

---

src/lib/artworkMediums.ts

[PX-4823](https://artsyproduct.atlassian.net/browse/PX-4823)
Consumed by Force and Eigen under artwork details

feat: Add NFT as artwork medium

---

_schemaV2.graphql
src/schema/v2/article/index.ts
src/schema/v2/article/models.ts
src/schema/v2/article/sections/ArticleSectionImageCollection.ts
src/schema/v2/article/sections/ArticleSectionImageSet.ts
src/schema/v2/article/sections/ArticleSectionText.ts
src/schema/v2/image/index.ts

Extended schema to support rebuilt article pages.

feat(articles): fleshes out article schema

---

_schema.graphql
_schemaV2.graphql
src/data/exchange.graphql

Added `source` to `order`. Copied [updated Exchange schema](https://github.com/artsy/exchange/pull/1041) to Metaphysics.
[NX-3037](https://artsyproduct.atlassian.net/browse/NX-3037)

chore: update Exchange schema in Metaphysics.

---

src/schema/v2/me/index.ts
src/schema/v2/me/update_me_mutation.ts

Addresses [CX-2240]
🔴  Depends on https://github.com/artsy/gravity/pull/14812
Add otherRelevantPosition to collector profile.
[CX-2240]: https://artsyproduct.atlassian.net/browse/CX-2240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add otherRelevantPosition to collector profile

---

_schemaV2.graphql
src/lib/stitching/gravity/v2/stitching.ts

Stitches the `me` field into these Gravity mutations.

feat(mutations): adds me to output fields

---

_schemaV2.graphql
src/lib/stitching/gravity/v2/stitching.ts

Inserted these at the wrong level of the object 😬 
Also they can't be non-nullable since if there are `errors` that field would be null.

fix(mutations): corrects extended types

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap

Pulls in new artistIDs array types for Search Criteria, following up on https://github.com/artsy/gravity/pull/14910/files

chore: update grav schema

---

src/schema/v2/me/index.ts

Adjust otherRelevantPositions resolver.

fix: Adjust otherRelevantPositions resolver

---

src/schema/v2/me/index.ts

Addresses [CX-2179]
This PR fixes the issue of `otherRelevantPositions` returning `null` by fetching the field from the Gravity collector profile endpoint instead of Gravity's me endpoint.
[CX-2179]: https://artsyproduct.atlassian.net/browse/CX-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Load otherRelevantPositions from collector profile

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Related to https://github.com/artsy/gravity/pull/14942
Exposing field to allow Arta eligible artworks in MOI

feat(PX-4842): Add process with Arta boolean

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap

following up on https://github.com/artsy/gravity/pull/14954

chore: update gravity schema

---

_schemaV2.graphql
src/schema/v2/me/myCollectionCreateArtworkMutation.ts

Resolve SWA-150
Task: When a submission’s status changes to submitted, create an artwork in the user's collection in Gravity
In this ticket, I added a new user_id field in order to understand for which user the artwork will be created when requested

feat[SWA-150]: Add userId to MyCollectionUpdateArtworkInput

---

src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/__tests__/notification_preferences.test.ts
src/schema/v2/notification_preferences.ts
src/schema/v2/schema.ts

This PR adds a query/mutation duo for the notification preferences.
https://artsyproduct.atlassian.net/browse/GRO-704

Adding in the query for Notification Preferences: GRO-704

---

_schemaV2.graphql
src/lib/loaders/api/loader_with_authentication_factory.ts
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts

Addresses [CX-2318]
Add metric preferences to me.
[CX-2318]: https://artsyproduct.atlassian.net/browse/CX-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Co-authored-by: dariakoko

feat: Add metric preferences to me

---

_schemaV2.graphql
src/schema/v2/article/index.ts

Adding schema required to support video layouts.

feat(article): fleshes out article schema for media

---

_schemaV2.graphql
src/schema/v2/articlesConnection.ts

Adds `channelId` arg to `articlesConnection`

feat(articles): adds channel id to args

---

_schemaV2.graphql
src/schema/v2/article/index.ts

Exposes other articles in the same channel.

feat(article): adds channel articles

---

_schemaV2.graphql
src/schema/v2/article/index.ts

Exposes source for news articles

feat(article): adds news source

---

_schemaV2.graphql
src/schema/v2/me/__tests__/update_me_mutation.test.js
src/schema/v2/me/update_me_mutation.ts

Addresses [CX-2319]
Add metric preferences to update me mutation.
[CX-2319]: https://artsyproduct.atlassian.net/browse/CX-2319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add metric preferences to update me mutation

---

_schemaV2.graphql
src/schema/v2/me/myCollectionCreateArtworkMutation.ts

In this PR i removed userId from MyCollectionCreateArtworkInput
Also i rename submisssionId to submission_id in loader params
because in gravity I got this:

Fix[SWA-150] Remove userId and rename submissionId params

---

src/schema/v2/article/index.ts

fix(article): early return null for null news sources

---

_schemaV2.graphql
src/schema/v2/article/index.ts
src/schema/v2/article/models.ts
src/schema/v2/articles.ts
src/schema/v2/articlesConnection.ts

Gives us the ability to query for news

feat(articles): adds ability to query by layout

---

_schemaV2.graphql
src/schema/v2/article/__tests__/isMedia.test.ts
src/schema/v2/article/lib/isMedia.ts
src/schema/v2/article/models.ts

A union type would be better here but Positron is so... _freestyle_, nothing _really_ matters. 🤷

fix(article): differentiates media

---

src/schema/v2/me/__tests__/bidder_position.test.js
src/schema/v2/me/bidder_position.ts

Metaphysics component of [BID-197](https://artsyproduct.atlassian.net/jira/software/c/projects/BID/boards/106?modal=detail&selectedIssue=BID-197)

chore:update bidder position to utilize sale closed status

---

_schema.graphql
_schemaV2.graphql
src/data/exchange.graphql

Following https://github.com/artsy/exchange/pull/1082, this updates the MP schema with the change.

chore: update schema with Exchange changes

---

_schemaV2.graphql
src/schema/v2/articles.ts
src/schema/v2/articlesConnection.ts

Expands args to be able to query articles for infinite scrolling pages.

feat(articles): expands args

---

src/schema/v2/__tests__/searchCriteriaLabel.test.ts
src/schema/v2/searchCriteriaLabel.ts

Jira - https://artsyproduct.atlassian.net/browse/FX-3452
The task is to make price ranges in SearchCriteriaLabel human-readable

feat: [FX-3452] human-readable values for Price filters

---

src/lib/loaders/loaders_without_authentication/diffusion.ts
src/schema/v2/artwork/comparableAuctionResults.ts

Adjust comparableAuctionResultsLoader path.

fix: Adjust comparableAuctionResultsLoader path

---

_schemaV2.graphql
src/schema/v2/__tests__/sale_artwork.test.js
src/schema/v2/sale_artwork.ts

Adds the field which lets you know if the lot has already closed.

feat: add endedAt to SaleArtwork type

---

index.js
package.json
yarn.lock

Removes the no longer required package `express-force-ssl`

chore: Remove express-force-ssl

---

src/schema/v2/article/index.ts

Minor fix for interstitial related articles query.

fix(article): omit tags for in vertical query

---

_schemaV2.graphql
src/schema/v2/article/index.ts

Another classic layout feature.

feat(article): exposes lead paragraph

---

_schema.graphql
_schemaV2.graphql
src/data/convection.graphql
src/lib/stitching/convection/schema.ts

This PR updates gql schema from convection.

feat: update convection schema

---

src/schema/v2/article/index.ts

fix(article): early null on media

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Part of https://artsyproduct.atlassian.net/browse/PX-4898
Exposes new boolean field on artwork model to denote international arta shipping
https://github.com/artsy/gravity/pull/15110/files

Exposes new field for artsy international shipping

---

_schema.graphql
_schemaV2.graphql
src/data/exchange.graphql

MP side of: https://artsyproduct.atlassian.net/browse/PX-4916
Surface shipping contact information for volt to consume
Related PR in exchange: https://github.com/artsy/exchange/pull/1109

[PX-4916] Expose shipping contact information

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts

Add inProgress field to ArtworkConsignmentSubmission.

feat: Add inProgress field to ArtworkConsignmentSubmission

---

_schema.graphql
_schemaV2.graphql
src/data/convection.graphql

Addresses [CX-2384]
Update Convection GraphQL schema.
[CX-2384]: https://artsyproduct.atlassian.net/browse/CX-2384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update Convection GraphQL schema

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/requestPriceEstimate.test.js
src/schema/v2/me/requestPriceEstimate.ts
src/schema/v2/schema.ts

This PR resolves part of [CX-2355]
This PR adds the loader necessary for the Gravity --> Pulse email request for price estimate
[CX-2355]: https://artsyproduct.atlassian.net/browse/CX-2355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(cx-2355): Implementation - Request Price Estimate (Metaphysics)

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Addresses [CX-2454]
Add submissionId to myCollectionUpdateArtworkMutation input fields.
[CX-2454]: https://artsyproduct.atlassian.net/browse/CX-2454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add submissionId to myCollectionUpdateArtworkMutation input fields

---

src/schema/v2/me/update_me_mutation.ts

Re: [GRO-877](https://artsyproduct.atlassian.net/browse/GRO-877)
Force will also require an update here; which I'll PR in a moment. Here we need to actually wait for the loader for the catch to catch.

fix(me): awaits loader so as to catch errors

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

- add submission id to artwork interface

chore: add submission id to artwork interface

---

_schemaV2.graphql
src/schema/v2/users/updateUserMutation.ts

This PR just adds `name` and `phone` to the basic user mutation. It sets up a Forque PR that I'll link when I make it.

feat: Allow more user updates

---

_schemaV2.graphql

This PR is just a:
```
$ yarn dump:local
```
I forgot to run it when working on #3882 🙇

Fix: Update schema

---

_schemaV2.graphql
src/schema/v2/sale/__tests__/index.test.ts
src/schema/v2/sale/index.ts

re: https://artsyproduct.atlassian.net/browse/BID-348
This is a placeholder with a `/ 60` calculation until Gravity has been updated.

chore:add placeholder for cascadingEndTimeIntervalMinutes

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/schema.ts
src/schema/v2/shortcut.ts

Moving the shortcut app in Force. We'll need this for Forque, as well.

feat: exposes shortcut

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Reverts artsy/metaphysics#3958
Contains breaking changes with Volt 😬

Revert "[PX-4946] Remove fallbacks + deprecated arta related fields"

---

_schemaV2.graphql
src/integration/__tests__/__fixtures__/knownV2Failures.json
src/schema/v2/__tests__/sale_artwork.test.js
src/schema/v2/sale/__tests__/index.test.ts
src/schema/v2/sale/index.ts
src/schema/v2/sale_artwork.ts

completes https://artsyproduct.atlassian.net/browse/BID-348
The related [Gravity PR](https://github.com/artsy/gravity/pull/15243) has been merged.

chore:use minutes for cascading time interval

---

_schemaV2.graphql
src/lib/apis/greenhouse.ts
src/lib/loaders/api/index.ts
src/lib/loaders/loaders_without_authentication/greenhouse.ts
src/lib/loaders/loaders_without_authentication/index.ts
src/schema/v2/jobs.ts
src/schema/v2/schema.ts

Exposes Greenhouse data to support jobs page rebuild: https://github.com/artsy/force/pull/9937

feat: exposes greenhouse jobs data

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
src/lib/stitching/gravity/schema.ts

Co-authored-by: Matt Dole <mdole7@gmail.com>
Bumps gravity graphql schema

Kaws deprecation: bump gravity schema

---

_schema.graphql
_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap

Bump gravity schema

---

README.md

because it [tripped](https://artsy.slack.com/archives/CP9P4KR35/p1652129500509699) me up.
should be useful to other newbies.

feat: tip about api version

---

_schemaV2.graphql
src/schema/v2/__tests__/user.test.ts
src/schema/v2/me/__tests__/__snapshots__/update_me_mutation.test.js.snap
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/__tests__/update_me_mutation.test.js
src/schema/v2/me/index.ts
src/schema/v2/me/update_me_mutation.ts
src/schema/v2/user.ts

Depends on https://github.com/artsy/gravity/pull/15319 and shouldn't be merged until that's released.
(Once again I'm closely following your lead in https://github.com/artsy/metaphysics/pull/3930.)

add receiveViewingRoomNotification user preference

---

src/schema/v1/artwork/index.ts
src/schema/v2/me/__tests__/newWorksByInterestingArtists.test.ts
src/test/fixtures/gravity/artworks_array.json
src/test/fixtures/gravity/order.json
src/types/runtime/gravity/Partner.ts

See https://github.com/artsy/gravity/pull/15329 for details

chore: remove has_limited_fair_partnership

---

_schemaV2.graphql
src/lib/stitching/exchange/__tests__/additionalPaymentMethods.test.ts
src/lib/stitching/exchange/v2/stitching.ts
src/schema/v2/partner.ts

This PR adds a list of additional payment methods for the order query. 
JIRA - [TX-331]
[TX-331]: https://artsyproduct.atlassian.net/browse/TX-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add additional payment methods 

---

src/schema/v2/me/__tests__/myCollectionInfo.test.ts
src/schema/v2/me/myCollectionInfo.ts

Addresses [CX-2599]
Adjust my collection info resolver.
[CX-2599]: https://artsyproduct.atlassian.net/browse/CX-2599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Adjust My Collection info resolver

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollection.test.ts
src/schema/v2/me/myCollection.ts

This change is needed to make pagination for My Collection work in Force. I just used the same helper we already [use for saved artworks](https://github.com/artsy/metaphysics/blob/0f90d50899db09d0ca63f584b0a5c3c01d438e2a/src/schema/v2/me/savedArtworks.ts#L76).

feat: Add pagination functionality to myCollectionConnection

---

src/schema/v2/artwork/artworkVideos.ts

Requested during initial video QA. Adding query to vimeo url to fetch muted videos.

chore(video): add mute query param to video urls

---

_schemaV2.graphql
src/schema/v2/article/index.ts

Acceptance tests caught some difference in page titles.

fix(article): exposes meta tag favored fields

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollectionInfo.test.ts
src/schema/v2/me/myCollectionInfo.ts

This PR Resolves [CX-2605]
This PR exposes the list of the artists that in the user's My Collection
- Query
```graphql
query {
me {
myCollectionInfo {
collectedArtistsConnection(first: 5) {
totalCount
edges {
node {
name
}
}
}
}
}
}
```
- Result
```json
"data": {
"me": {
"myCollectionInfo": {
"collectedArtistsConnection": {
"totalCount": 4,
"edges": [
{
"node": {
"name": "Banksy"
}
},
{
"node": {
"name": "Flavio Favelli"
}
},
{
"node": {
"name": "Fabio Viscogliosi"
}
},
{
"node": {
"name": "Amoako Boafo"
}
}
]
}
}
}
```
[CX-2605]: https://artsyproduct.atlassian.net/browse/CX-2605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat [CX-2605]: Add the list of the artists in My Collection to myCollectionInfo

---

yarn.lock

The type of this PR is: chore
This PR bumps jsprim to 1.4.2 from 1.4.1

chore: bump jsprim

---

package.json
yarn.lock

This PR bumps `danger` from `7.0.14` to `^10.9.0`.

chore: bump-danger

---

_schemaV2.graphql
src/schema/v2/me/myCollectionInfo.ts

This PR adds `sort` to collectedArtistsConnection
This PR relies on artsy/gravity#15474

feat: adding sort to my collection artists

---

_schemaV2.graphql
src/schema/v2/image/index.ts

docs: some schema docs for `Image.position`

---

_schema.graphql
_schemaV2.graphql
src/data/exchange.graphql

relates to https://github.com/artsy/exchange/pull/1274

chore: update exchange graphql schema

---

_schemaV2.graphql
src/data/exchange.graphql

Relates to https://github.com/artsy/exchange/pull/1299

chore: Update exchange.graphql

---

_schemaV2.graphql
src/data/vortex.graphql

🔴 Depends on https://github.com/artsy/vortex/pull/535
Do not merge before
Update Vortex schema to include newest price insight fields.

feat: Update Vortex schema to include newest price insight fields

---

_schemaV2.graphql
src/data/vortex.graphql

Updates Vortex schema to add `medianSalePriceLast96Months` to price insighs.

feat: Update Vortex schema, add medianSalePriceLast96Months

---

src/lib/loaders/loaders_with_authentication/vortex.ts

- add liquidityRank to the query we use to get data from vortex.
- Follow-up on https://github.com/artsy/metaphysics/pull/4317

chore: return liquidity rank with market insights

---

_schemaV2.graphql
src/data/vortex.graphql

Update vortex schema 
cc @olerichter00

chore: Update vortex schema 

---

_schemaV2.graphql
src/data/vortex.graphql

Reverts artsy/metaphysics#4323

revert: Revert "chore: Update vortex schema "

---

scripts/push-schema-changes.js

This PR makes sure that we update the schema inside energy to match the one in metaphysics to avoid manual updates like this one https://github.com/artsy/energy/pull/143
cc @rajsam003

feat: push schema updates to energy

---

_schemaV2.graphql
src/schema/v2/userSaleProfile.ts

This is a minor follow-up to #4336 to fix incorrect casing and typing.

fix: casing and types

---

hokusai/staging.yml

The type of this PR is: Feat
This PR solves PLATFORM-4514
Part of spike on using AWS Spot instances.
[Had created spot tier](https://github.com/artsy/substance/pull/283) in staging Kubernetes cluster.
See [Force PR](https://github.com/artsy/force/pull/10846) for more details.

feat: run some staging pods in kubernetes spot tier.

---

_schemaV2.graphql
src/schema/v2/partner.ts

pr review from [#4313](https://github.com/artsy/metaphysics/pull/4313)

fix: less confusing published param name

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/__tests__/user.test.ts
src/schema/v2/user.ts
src/schema/v2/userPurchases.ts

https://artsyproduct.atlassian.net/browse/PLATFORM-4437
This adds a `purchasesConnection` field under User which will be used to display users' purchases in [Forque](https://github.com/artsy/forque).
Thanks @mzikherman for the initial commit and support in getting this done.

feat: add purchasesConnection under User

---

_schemaV2.graphql
src/schema/v2/user.ts
src/schema/v2/userPurchases.ts

https://artsyproduct.atlassian.net/browse/PLATFORM-4437
This updates the `User` to return a paginated connection for purchased artworks.

feat: user purchased artworks connection is paginated

---

src/schema/v2/notifications/__tests__/index.test.ts
src/schema/v2/notifications/index.ts

Addresses [FX-4200]
Filter notifications by notification type using the new param introduced in https://github.com/artsy/gravity/pull/15643.
[FX-4200]: https://artsyproduct.atlassian.net/browse/FX-4200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Filter notifications by notification type

---

src/schema/v2/sale/__tests__/index.test.ts
src/schema/v2/sale/display.ts

Follow-up for https://artsyproduct.atlassian.net/browse/GRO-1354 once I realized that Force was over-doing formatting rather than just using the return value from Metaphysics.
https://artsy.slack.com/archives/CP9P4KR35/p1665603207987159
I'm self-assigning since it's a tiny copy change.

fix: GROW-1354 capitalize Register in 'Register by'

---

src/index.ts

This should be flattened and moved out of this callback. Based on some Slack conversations about recent-ish changes to this file/server setup and increased latency.

fix: move this expensive line out of request loop

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

- Expose `hasPriceEstimateRequest` field on Artwork
This PR resolves [CX-3000]
[CX-3000]: https://artsyproduct.atlassian.net/browse/CX-3000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3000): Expose has price estimate boolean field

---

src/schema/v2/artwork/__tests__/utilities.test.ts
src/schema/v2/artwork/utilities.ts

Adds in missing video dimensions to the type.

feat(video): add video dimensions to type

---

src/schema/v2/me/myCollectionInfo.ts

Fetch all artwork fields in collectedArtistsConnection resolver.

fix: Fetch all artwork fields in collectedArtistsConnection resolver

---

_schemaV2.graphql
src/schema/v2/artist/__tests__/index.test.js
src/schema/v2/artist/shows.ts
src/schema/v2/fields/pagination.ts

Switches to use our `paginationResolver` and adds support for a `page` param.

fix(artist): fixes related shows pagination

---

_schemaV2.graphql
src/schema/v2/types/Video.ts

Fixes an issue with a field rename in the Video resolver.

fix(video): fix ref to `url` in resolver

---

_schemaV2.graphql
src/schema/v2/fair.ts

Needed to support consistency effort in the fair app.

fix(fair): adds page/size support to articles connection

---

_schemaV2.graphql
src/schema/v2/notifications/index.ts

- [Jira](https://artsyproduct.atlassian.net/browse/FX-4254)
- [Gravity PR](https://github.com/artsy/gravity/pull/15818)
Introducing new Activity panel notification type

feat(FX-4254): recognize PartnerShowPublishedActivity events

---

_schemaV2.graphql
src/schema/v2/conversation/conversations.ts
src/schema/v2/me/__tests__/conversations.test.js

Addresses some follow-up feedback from https://github.com/artsy/metaphysics/pull/4530

chore(conversations): Address follow-up feedback

---

src/schema/v2/sale/__tests__/__snapshots__/index.test.ts.snap
src/schema/v2/sale/__tests__/index.test.ts
src/schema/v2/sale/index.ts

chore: expose `totalCount` field

---

scripts/push-schema-changes.js

[NX-33490]
Enables volt-v2 repo to receive PRs from the bot.

feat(NX-3340): add volt-v2 to schema updates

---

scripts/push-schema-changes.js

Oops! This had already been done.

fix(schema): remove volt-v2 schema

---

_schemaV2.graphql
src/schema/v2/notifications/__tests__/index.test.ts
src/schema/v2/notifications/index.ts

- [Jira ticket](https://artsyproduct.atlassian.net/browse/FX-4473)
- [Linked Gravity PR](https://github.com/artsy/gravity/pull/15902)
We are adding new `objects_count` field to display total number of objects in Activity Panel

feat(FX-4473): notificationsConnection has new field objects_count

---

src/lib/loaders/loaders_with_authentication/gravity.ts

This PR orders gravity authentication loaders alphabetically. Motivation https://github.com/artsy/metaphysics/pull/4582#discussion_r1041572188

chore: alphabetically order gravity auth loaders

---

_schemaV2.graphql
src/schema/v2/__tests__/auction_results.test.js
src/schema/v2/artist/index.ts
src/schema/v2/me/auction_results_by_followed_artists.ts
src/schema/v2/me/myCollectionAuctionResults.ts

This PR resolves [CX-3222]
Related Diffusion changes: https://github.com/artsy/diffusion/pull/653
**What's still required:**
- Update params according to the changes in Diffusion
@egdbear I am making some changes to the API. thanks for checking this out
[CX-3222]: https://artsyproduct.atlassian.net/browse/CX-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allow filtering for upcoming lots

---

_schemaV2.graphql
src/schema/v2/conversation/__tests__/updateMessageMutation.test.ts
src/schema/v2/conversation/updateMessageMutation.ts

Updates the casing on the mutation types to make things consistent

fix(updateMessageMutation): Fix type caps case

---

_schemaV2.graphql
src/schema/v2/__tests__/user.test.ts
src/schema/v2/userPurchases.ts

We want to display the date of the purchase on the User-Purchases tab on the forque side and need to access the data through metaphysics.

chore: access sale_date from user purchase

---

_schemaV2.graphql
src/schema/v2/artists/curatedTrending.ts
src/schema/v2/home/__tests__/home_page_artist_modules.test.js
src/schema/v2/home/home_page_artist_module.ts

This PR steals all of the good work done by @anandaroop and uses it on the home feed in the app. It'll require a PR over on Eigen to actually use this `TRENDING` flavor of artists but this is the first step.
https://artsyproduct.atlassian.net/browse/GRO-1381

feat: Use curated trending for app home feed artist GRO-1381

---

_schemaV2.graphql
src/schema/v2/__tests__/auction_results.test.js
src/schema/v2/artist/index.ts
src/schema/v2/auction_result.ts
src/schema/v2/me/auction_results_by_followed_artists.ts
src/schema/v2/me/myCollectionAuctionResults.ts

This is going to be a non-breaking change to our frontend since we still did not roll this change out to App.
What's needed before merging this
1. ✅ Revert PR on Eigen: https://github.com/artsy/eigen/pull/7867
2. ✅ Revert PR on Force: https://github.com/artsy/force/pull/11575#pullrequestreview-1220973769

refactor: improve auctionResultsConnection interface [DO NOT MERGE]

---

_schemaV2.graphql
src/data/exchange.graphql

updating Exchange schema for adding phone number country code field to set_shipping mutation and order.

chore(): Update exchange schema

---

_schemaV2.graphql
src/schema/v2/user.ts

[NX-3400] Initials on User
( My first PR on metaphysics 🎉 - thank you @dblandin ! )
[NX-3400]: https://artsyproduct.atlassian.net/browse/NX-3400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: NX-3400 Initials on User

---

package.json
yarn.lock

chore(deps): bumps img

---

src/schema/v2/artist/helpers.ts

Beep boop, I did the thing! Also relies on a Force PR to update the placeholder.
https://artsyproduct.atlassian.net/browse/GRO-1440

chore: Minor artist insights copy changes GRO-1440

---

_schemaV2.graphql
src/schema/v2/artwork_version.ts

Used the wrong case for attribution class

style: update attribution class case

---

package.json
yarn.lock

Let's keep deps up to date! Bumping danger to `^11.2.1`.

chore: bump danger to v11

---

_schemaV2.graphql
src/schema/v2/notifications/index.ts

Recognize ArticleFeaturedArtistActivity events

feat(FX-4497): Article featured artist activity

---

src/schema/v2/requestLocation.ts

This resolver was only handling the happy path; which presents a problem for actually handling the error state in Force. Really; this shouldn't ever error; just return `null` for the other fields.

fix(requestlocation): better handles error cases

---

src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Addresses [CX-3333]
Expose images in update artwork mutation.
[CX-3333]: https://artsyproduct.atlassian.net/browse/CX-3333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Expose images in update artwork mutation

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts
src/schema/v2/artwork/utilities.ts

This PR adds the `includeAll` param to artwork's `figures` field.

feat: Add includeAll param to artwork figures field

---

_schemaV2.graphql
src/schema/v2/OrderedSet/__tests__/createOrderedSetMutation.test.ts
src/schema/v2/OrderedSet/createOrderedSetMutation.ts

Is part of the work described here: https://github.com/artsy/gravity/pull/16025

chore: add item ids to create set mutation

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/collectionsConnection.test.ts
src/schema/v2/me/collection.ts
src/schema/v2/me/collectionsConnection.ts
src/schema/v2/me/index.ts

[Jira ticket](https://artsyproduct.atlassian.net/browse/FX-4523)
Adds `me.collectionsConnection` query
```graphql
{
me {
collectionsConnection(first: 3){
edges {
node {
internalID
name
saves
edges {
node {
title
}
}
}
}
}
}
}
}
```
```json
{
"data": {
"me": {
"collectionsConnection": {
"edges": [
{
"node": {
"internalID": "2fc5f80e-759f-4fbf-90a1-5a7f58785921",
"name": "Saved Artwork",
"saves": false,
"edges": [
{
"node": {
"title": "Sentimental Journey"
}
}
]
}
}
}
]
}
}
}
}
```

feat(FX-4523): me.collectionsConnection

---

src/schema/v2/CollectorProfile/collectorProfile.ts

[NX-3406]
Add date format helper helper to the field `collectorProfile.artsyUserSince`
[NX-3406]: https://artsyproduct.atlassian.net/browse/NX-3406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3406): add date formatter to arstyUserSince field

---

src/schema/v2/artist/__tests__/helpers.test.ts
src/schema/v2/artist/helpers.ts

Gravity PR - https://github.com/artsy/gravity/pull/16029
[Ticket](https://artsyproduct.atlassian.net/browse/DO-421)

feat: use pipe-delimited collections

---

src/schema/v2/me/unlinkAuthenticationMutation.ts

Re: [GRO-1541](https://artsyproduct.atlassian.net/browse/GRO-1541)
First step in debugging this is returning some actual errors.
[GRO-1541]: https://artsyproduct.atlassian.net/browse/GRO-1541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: surfaces error messages

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/updateCollectionMutation.test.ts
src/schema/v2/me/updateCollectionMutation.ts
src/schema/v2/schema.ts

[Jira ticket](https://artsyproduct.atlassian.net/browse/FX-4529)
Add a `updateCollection` mutation
```graphql
mutation {
updateCollection(input: {id: "485437bf-7949-43b5-ab5d-f1d7c9b64ffa", name: "test" }) {
... on UpdateCollectionSuccess {
collection {
internalID
name
}
}
... on UpdateCollectionFailure {
message
}
}
}
}
}
```
```graphql
{
"data": {
"updateCollection": {
"internalID": "485437bf-7949-43b5-ab5d-f1d7c9b64ffa",
"name": "test"
}
}
}
}
}
```
```graphql
{
"data": {
"updateCollection": {
"mutationError": {
"message": "Name can't be blank."
}
}
}
}
}
```

feat(FX-4529): add updateCollection mutation

---

_schemaV2.graphql
src/schema/v2/artwork_version.ts

This PR add `date` and `dimensions` for the artwork version model.
JIRA - [TX-1036]
[TX-1036]: https://artsyproduct.atlassian.net/browse/TX-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update artwork version fields

---

_schemaV2.graphql
src/schema/v2/artwork_version.ts

This PR adds description for the fields.
JIRA - [TX-1036]
[TX-1036]: https://artsyproduct.atlassian.net/browse/TX-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add field descriptions

---

_schemaV2.graphql
src/schema/v2/partner/__tests__/partner.test.js
src/schema/v2/partner/partner.ts

This PR resolves [FX-4584](https://artsyproduct.atlassian.net/browse/FX-4584)
Exposes isInquireable on partner
[FX-4584]: https://artsyproduct.atlassian.net/browse/FX-4584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: expose isInquireable on partner

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

This PR resolves [CX-3426]
- Allows users add personal notes to their MyCollection Artworks.
[CX-3426]: https://artsyproduct.atlassian.net/browse/CX-3426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(CX-3426): Allow MyCollection Users add Notes to Artworks

---

src/lib/stitching/exchange/__tests__/stitching.test.ts
src/lib/stitching/exchange/v2/stitching.ts

Jira ticket: https://artsyproduct.atlassian.net/browse/PRO-57

feat: replace explicit state check with facsimile

---

src/lib/fillers/enrichArtworksWithPriceInsights.ts
src/lib/loaders/loaders_with_authentication/vortex.ts

Addresses [CX-2685]
Remove medium category mapping code.
[CX-2685]: https://artsyproduct.atlassian.net/browse/CX-2685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove medium category mapping code

---

_schemaV2.graphql
src/schema/v2/__tests__/recentlySoldArtworks.test.ts
src/schema/v2/recentlySoldArtworks.ts

Description: Add performance to the recentlySoldArtworks query

[DRAFT] feat: add performance to recentlySoldArtworks

---

src/schema/v2/me/myCollection.ts

Add comment to explain sortByLastAuctionResultDate size.

chore: Add comment to explain sortByLastAuctionResultDate size

---

src/lib/fillers/enrichArtworksWithPriceInsights.ts
src/lib/loaders/loaders_with_authentication/vortex.ts

Reverts artsy/metaphysics#4806
Reverting this since it's breaking the mutation https://artsynet.sentry.io/issues/3891971626/?project=5867225&query=is%3Aunresolved&referrer=issue-stream
Let's follow-up on this tomorrow morning

Revert "fix: Filter null values in price insights batch loader input"

---

src/schema/v2/conversation/send_message_mutation.ts

Reverts artsy/metaphysics#4805

Revert "fix(NX-3465): attachments array in SendMessageMutation"

---

_schemaV2.graphql
src/schema/v2/artist/helpers.ts

Related to 
https://github.com/artsy/gravity/pull/16085
https://github.com/artsy/torque/pull/1329
https://github.com/artsy/force/pull/11966

chore: add new fields to artist achievements

---

src/schema/v2/me/artworkRecommendations.ts

Addresses [CX-3411]
Fix Artwork Recommendations Connection (similar to https://github.com/artsy/metaphysics/pull/4828)
[CX-3411]: https://artsyproduct.atlassian.net/browse/CX-3411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Artwork Recommendations Connection

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts
src/schema/v2/me/collectionsConnection.ts

```graphql
{
artwork(id: "rodney-smith-pears-clinton-connecticut") {
id
collectionsConnection(first: 2) {
totalCount
edges {
node {
internalID
name
default
saves
totalCount
}
}
}
}
}
}
```
```graphql
{
"data": {
"artwork": {
"id": "QXJ0d29yazo2M2RhZGI1Y2Y3MDg0MTAwMGI3YWY2Njc=",
"collectionsConnection": {
"totalCount": 2,
"edges": [
{
"node": {
"internalID": "ce7852f8-da4a-4c7f-be98-9d77970549b5",
"name": "Photography",
"default": false,
"saves": true,
"totalCount": 1
}
}
},
{
"node": {
"internalID": "2fc5f80e-759f-4fbf-90a1-5a7f58785921",
"name": "Saved Artwork",
"default": true,
"saves": false,
"totalCount": 81
}
}
}
]
}
}
},
"requests": {
"gravity": {
"requests": { …
```

feat(FX-4599): add collectionsConnection to artwork field

---

src/schema/v2/me/artworksCollectionsBatchUpdateMutation.ts

```
mutation {
artworksCollectionsBatchUpdate(input: { artworkIDs: ["alfred-leslie-untitled-67"], addToCollectionIDs: ["ce7852f8-da4a-4c7f-be98-9d77970549b5"]}) {
... on ArtworksCollectionsBatchUpdateSuccess {
counts {
artworks
addedToCollections
removedFromCollections
}
addedToCollections {
internalID
name
artworksCount
artworksConnection(first: 1, sort: POSITION_DESC) {edges{node{slug}}}
}
removedFromCollections {
internalID
name
}
}
... on ArtworksCollectionsBatchUpdateFailure {
message
}
}
}
}
}
```
```
{
"data": {
"artworksCollectionsBatchUpdate": {
"counts": {
"artworks": 1,
"addedToCollections": 1,
"removedFromCollections": 0
},
"addedToCollections": [
{
"internalID": "ce7852f8-da4a-4c7f-be98-9d77970549b5",
"name": …
```

feat(fx-4641): add artworksConnection to artworksCollectionsBatchUpdate.addedToCollections and artworksCollectionsBatchUpdate.removedFromCollections

---

src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/newWorksFromGalleriesYouFollow.test.ts
src/schema/v2/me/newWorksFromGalleriesYouFollow.ts

Calculate total count in newWorksFromGalleriesYouFollow connection.

fix: Calculate total count in newWorksFromGalleriesYouFollow connection

---

src/schema/v2/me/__tests__/artworkRecommendations.test.ts
src/schema/v2/me/artworkRecommendations.ts

Fix ArtworkRecommendations resolver to calculate `totalCount` correctly.

fix: ArtworkRecommendations connection

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

feat(artwork): exposes dominant colors

---

src/schema/v2/artwork/index.ts
src/schema/v2/me/collection.ts
src/schema/v2/me/collectionsConnection.ts

Jira ticket: [FX-4681](https://artsyproduct.atlassian.net/browse/FX-4681)
[FX-4681]: https://artsyproduct.atlassian.net/browse/FX-4681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4681): extract `userID` from `context` for collections

---

_schemaV2.graphql
src/lib/apis/gravityGraphQL.ts
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/index.ts

One thing I'm not clear on is how to get this fetch to expose itself in the requests extension?

feat(me): exposes saved searches count

---

_schemaV2.graphql
src/schema/v2/auction_result.ts

This PR resolves https://artsyproduct.atlassian.net/browse/CX-3575
Add `date-asc` sorting to metaphysics

chore: support Date ASC sorting MP

---

src/schema/v2/auction_result.ts

Will merge this to get it ready to Pierluca to test it tomorrow

chore: adjust is upcoming logic to match diffusion

---

_schemaV2.graphql
src/schema/v2/__tests__/auction_result.test.ts
src/schema/v2/auction_result.ts

This PR resolves [CX-3583]
Expose in Artsy Auction to Client apps
[CX-3583]: https://artsyproduct.atlassian.net/browse/CX-3583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: expose isInArtsyAuction 

---

src/schema/v2/auction_result.ts

chore: adjust isUpcoming logic to match diffusion

---

_schemaV2.graphql
src/schema/v2/auction_result.ts

Address
https://github.com/artsy/metaphysics/pull/4891#pullrequestreview-1362834247

chore: add comment to avoid usage of the artist inside connections

---

src/lib/stitching/gravity/v2/stitching.ts

This PR addresses [CX-3543]
Update curated collection list that is displayed on the homepage in the app.
[CX-3543]: https://artsyproduct.atlassian.net/browse/CX-3543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(cx-3543): Update curated collection list

---

.vscode/launch.json

Add "Test Current File With Debugger" to VSCode launch.json.

chore: Add Debug Jest Current File to VSCode launch.json

---

src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/myCollection.test.ts
src/schema/v2/me/myCollection.ts

This PR partly resolves [CX-2613]
This PR moves the myCollection artworks connection away from using collection_artworks_endpoint to use `MeMyCollectionArtworksEndpoint`
[CX-2613]: https://artsyproduct.atlassian.net/browse/CX-2613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(CX-2613): Use MeMyCollectionArtworksEndpoint for MyCollection Artworks

---

_schemaV2.graphql
src/schema/v2/me/myCollectionInfo.ts

Reverts artsy/metaphysics#5000
The id from my collection is not returning properly. Reverting this until we fix it.

Revert "chore: make my collection info node"

---

_schemaV2.graphql
src/schema/v2/artist/index.ts
src/schema/v2/me/__tests__/myCollectionInfo.test.ts
src/schema/v2/me/myCollectionInfo.ts

Add `artworks_count_within_collection` to the collection artists endpoint.
Related Gravity PR: https://github.com/artsy/gravity/pull/16328

feat: Add collected_artworks_count to collection artists endpoint

---

src/schema/v2/me/myCollectionInfo.ts

Addresses [CX-3692]
🔴  Depends on https://github.com/artsy/gravity/pull/16337
Remove all param from collectedArtists resolver.
[CX-3692]: https://artsyproduct.atlassian.net/browse/CX-3692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove all param from collectedArtists resolver

---

_schemaV2.graphql
src/schema/v2/identityVerification.ts

Companion to https://github.com/artsy/gravity/pull/16367

feat: support searching IDV records by name

---

_schemaV2.graphql
src/schema/v2/me/__tests__/collectionsConnection.test.ts
src/schema/v2/me/collectionsConnection.ts

Jira ticket: [FX-4784](https://artsyproduct.atlassian.net/browse/FX-4784)
https://github.com/artsy/metaphysics/assets/3513494/9ac28f2d-4dca-4219-bb87-248b0d24d71d
[FX-4784]: https://artsyproduct.atlassian.net/browse/FX-4784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add ability to pass `includesArtworkID` arg to `collectionsConnection`

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfiles.ts
src/schema/v2/__tests__/collectorProfiles.test.ts
src/schema/v2/schema.ts

Resolves [NX-3536]
Adds query for collector profiles search.
[NX-3536]: https://artsyproduct.atlassian.net/browse/NX-3536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3536): Add query for collector profiles search.

---

src/schema/v2/auction_result.ts

This PR removes current user id from the comparables query.
**DO NOT MERGE** before https://github.com/artsy/diffusion/pull/764 will be merged
JIRA - [PLATFORM-5236]
[PLATFORM-5236]: https://artsyproduct.atlassian.net/browse/PLATFORM-5236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove user id from comparables query

---

src/schema/v2/artist/__tests__/helpers.test.ts
src/schema/v2/artist/helpers.ts

Closes [DIA-39](https://artsyproduct.atlassian.net/browse/DIA-39)
[DIA-39]: https://artsyproduct.atlassian.net/browse/DIA-39?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(artist): alters high auction record insights label & description

---

_schemaV2.graphql
src/schema/v2/artist/__tests__/helpers.test.ts
src/schema/v2/artist/helpers.ts
src/schema/v2/artist/meta.ts

feat(artist): adds series meta tags

---

src/schema/v2/artist/__tests__/helpers.test.ts
src/schema/v2/artist/__tests__/insights.test.ts
src/schema/v2/artist/helpers.ts

fix(artist): adjusts insights copy

---

_schemaV2.graphql
src/schema/v2/__tests__/verify_address.test.ts
src/schema/v2/verifyAddress.ts

fix: wrongly-typed addressLine2 field

---

hokusai/staging.yml

Prevent staging pods from running on Spot instances.
[PHIRE-102]
[PHIRE-102]: https://artsyproduct.atlassian.net/browse/PHIRE-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: do not use spot in staging

---

_schemaV2.graphql
src/schema/v2/me/deleteUserInterestMutation.ts

Follow-up from https://github.com/artsy/gravity/pull/16446

chore: add comment to delete user interest mutation

---

_schemaV2.graphql
src/schema/v2/me/myCollectionInfo.ts

Addresses [ONYX-142]
Deprecate collectedArtistsConnection.
[ONYX-142]: https://artsyproduct.atlassian.net/browse/ONYX-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Deprecate collectedArtistsConnection

---

_schemaV2.graphql
src/lib/__tests__/moneyHelper.test.ts
src/lib/loaders/loaders_without_authentication/diffusion.ts
src/lib/moneyHelper.ts
src/schema/v2/__tests__/auction_results.test.js
src/schema/v2/aggregations/filterAuctionResultsAggregation.ts
src/schema/v2/artist/index.ts
src/schema/v2/auction_result.ts

This PR adds fields and arguments needed for the price range filtering on the auction results page.
JIRA - [DIA-29]
CC @artsy/diamond-devs 
[DIA-29]: https://artsyproduct.atlassian.net/browse/DIA-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add fields and arguments for price range filter

---

src/lib/locationHelpers.ts
src/schema/v2/me/__tests__/showsConnection.test.ts

Disabling the "IP-based" location feature for now until we resolve this rate-limiting issue. ([Slack Thread](https://artsy.slack.com/archives/C02BAQ5K7/p1691567528217389)).
This change will affect the "Shows for You" rail on the home screen and the "Galleries for You" screen in the app.

fix: Disable IP-based location "near you" feature

---

src/schema/v2/artist/helpers.ts

Use sentence case for Recent career event.
[Ticket](https://artsyproduct.atlassian.net/browse/DIA-94)

fix: use sentence case for recent career event

---

_schemaV2.graphql
src/schema/v2/artist/updateArtistMutation.ts

GRRRRRRRR
/cc @dzucconi @damassi

Add missing mutation input

---

_schemaV2.graphql
src/schema/v2/verifiedRepresentative/verifiedRepresentative.ts

Reissue of #5229 this time from origin rather than my fork.

Add not null to verified rep type

---

_schemaV2.graphql
src/data/gravity.graphql

This brings over the updates from gravity's graphql schema:
```
gravity > rake graphql:schema:idl
gravity > cp _schema.graphql ../metaphysics/src/data/gravity.graphql
cd metaphysics 
metaphysics > git commit -am 'chore(stitching): add gravity schema'
```

chore(stitching): add gravity schema

---

src/schema/v2/__tests__/search.test.ts
src/schema/v2/search/SearchResolver.ts

Assigning you @olerichter00 since I believe myself, @MounirDhahri and @nickskalkin who were discussing this in refinement are going to be out next week!
The issue is we have a lag where sometimes a record is returned from ElasticSearch via search results, where that record when queried for in Gravity no longer exists (errors with a 404).
This PR catches those lookups made in search results and swallows the error (which I think is fine in this context b/c that is occasionally expected, although swallowing errors isn't a typical pattern we encourage). Then, to avoid a `node: null` being included in the connection (which _might_ still cause an issue for clients), we remove that node entirely from the connection.
I think this will prevent a crash and still return the proper list of search …

fix: catch errors and filter out missing entries from search results

---

_schemaV2.graphql
src/schema/v2/artist/index.ts

Re: [DIA-10](https://artsyproduct.atlassian.net/browse/DIA-10)
[DIA-10]: https://artsyproduct.atlassian.net/browse/DIA-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(artist): deprecates counts#auctionresults

---

_schemaV2.graphql
src/data/gravity.graphql

Updates with the latest gravity stitched schema.  
cc @jpotts244 - check out the diff to see which fields it added. Super useful

chore(stitching): Update gravity schema

---

_schemaV2.graphql
src/data/gravity.graphql

Expose new summary field and update the default sorting for `SearchCriteriaConnection`
- https://github.com/artsy/gravity/pull/16772

chore: Update sorting default for search criteria connection

---

_schemaV2.graphql
src/data/gravity.graphql

Sync Gravity's graphql schema for stitching.

chore(stitching): Sync gravity schema

---

_schemaV2.graphql
src/schema/v2/__tests__/verify_address.test.ts
src/schema/v2/verifyAddress.ts

Followup from https://github.com/artsy/gravity/pull/16740/files
Just exposing a new field for the UI to use for tracking purposes.

feat(EMI-1308): expose addressVerificationId on VerifyAddressType

---

_schemaV2.graphql
src/schema/v2/artist/index.ts
src/schema/v2/artist/updateArtistMutation.ts

Adds support for updating `public` and `blurb`

feat(artist): adds public and blurb fields as inputs

---

_schemaV2.graphql
src/data/gravity.graphql

Update with latest gravity schema

chore: Update with latest gravity schema

---

_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/v2/stitching.ts

https://artsyproduct.atlassian.net/browse/ONYX-293
Follow-up to https://github.com/artsy/gravity/pull/16797
Stitches in the new <code>savedSearchesConnection(**artistIDs: […]**)</code> arg from Gravity.

chore(alerts): update Gravity stitched schema with alerts filtering

---

_schemaV2.graphql
src/data/gravity.graphql

This PR updates gravity graphql schema to match the one in Gravity.
Steps followed to generate this changes
1. Generate the latest schema on Gravity main using
```
bundle exec rake graphql:schema:idl
```
2. Copy the generated schema
3. Paste the changes to `gravity.graphql` in MP
4. run yarn `dump:local` (not necessary since we generate the schema again as part of pre-commit any way)
5. PR changes

chore: update gravity graphql schema

---

_schemaV2.graphql
src/data/gravity.graphql

Update to latest gravity graphql schema

chore: Update to latest gravity graphql schema

---

README.md

chore: remove outdated link to Jenkins (PHIRE-276)

---

hokusai/production.yml
hokusai/staging.yml

chore: replace deprecated k8s specs

chore: replace deprecated k8s specs

---

src/schema/v2/artist/__tests__/insights.test.ts
src/schema/v2/artist/helpers.ts

[Ticket](https://artsyproduct.atlassian.net/jira/software/projects/DIA/boards/146?selectedIssue=DIA-179) 
Changes 
```
- `Recent [auction results](/artist/${artist.id}/auction-results) in the Artsy Price Database`,
+ `Recent auction results in the [Artsy Price Database](/artist/${artist.id}/auction-results)`,
```

feat: update the linked text in insights

---

_schemaV2.graphql
src/schema/v2/me/update_me_mutation.ts

Added the inputs to the mutation used in the settings page to update the user.

chore: allow more structured phone/country code to be persisted to the user

---

src/index.ts
src/schema/v2/me/index.ts
src/schema/v2/me/similarToRecentlyViewed.ts
src/types/graphql.d.ts

This is the follow-up [Gravity PR](https://github.com/artsy/gravity/pull/16932) where we introduced high priority endpoints for the braze.

feat: enable high priority queries for the braze

---

_schemaV2.graphql
src/data/gravity.graphql

Updates gravity graphql schema to support the new `represented` filter introduced here: https://github.com/artsy/gravity/pull/16948

chore: Updates gravity graphql schema

---

_schemaV2.graphql
src/schema/v2/aggregations/filter_artworks_aggregation.ts
src/schema/v2/filterArtworksConnection.ts

https://artsyproduct.atlassian.net/browse/ONYX-441
Follow-up to https://github.com/artsy/gravity/pull/16947
Simply wires up the new params from this^ Gravity PR

feat(artist series filter): add filtering and aggregation support to filterArtworksConnection

---

src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/me/__tests__/similarToRecentlyViewed.test.ts
src/schema/v2/me/index.ts
src/schema/v2/me/similarToRecentlyViewed.ts

Follow-up on [Gravity PR](https://github.com/artsy/gravity/pull/16932)
@artsy/diamond-devs

feat: enable impersonation for similarToRecentlyViewed connection

---

_schemaV2.graphql
src/data/gravity.graphql

Update gravity schema (changes made in [this PR](https://github.com/artsy/gravity/pull/16965))
Merge after https://github.com/artsy/gravity/pull/16965!

Update gravity graphql schema

---

scripts/push-schema-changes.js

This PR adds prediction schema updates to MP to make sure that the schema is always up to date.

feat: update prediction mp schema

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/system/__tests__/userRoles.test.ts
src/schema/v2/system/causality_jwt.ts
src/schema/v2/system/index.ts
src/schema/v2/system/userRoles.ts

Reverts artsy/metaphysics#5359 and re-adds https://github.com/artsy/metaphysics/pull/5356.

Revert "Revert "Merge pull request #5356 from artsy/joeyAghion/userRoles""

---

_schemaV2.graphql
src/data/gravity.graphql

Adds additional sort from gravity graphql schema
https://github.com/artsy/gravity/pull/16992

core: Adds additional sort from gravity graphql schema

---

_schemaV2.graphql
src/data/gravity.graphql

companion to https://github.com/artsy/gravity/pull/16990

chore: update gravity gql schema

---

_schemaV2.graphql
src/schema/v2/system/userRoles.ts

I think these can be tightened up like so.

chore: add some non-nullability to user roles

---

src/schema/v2/me/__tests__/followed_shows.test.ts
src/schema/v2/me/__tests__/recentlyViewedArtworks.test.ts
src/schema/v2/me/__tests__/userInterestsConnection.test.ts
src/schema/v2/me/artwork_inquiries.ts
src/schema/v2/me/followed_shows.ts
src/schema/v2/me/index.ts
src/schema/v2/me/recentlyViewedArtworks.ts
src/schema/v2/me/userInterestsConnection.ts
src/schema/v2/me/watchedLotConnection.ts

This PR enables the remaining queries from [the ticket](https://artsyproduct.atlassian.net/browse/DIA-206).
```sh
watchedLotConnection
userInterestsConnection
myCollectionConnection
followsAndSaves {
galleriesConnection
fairsConnection
artistsConnection
}
artworkInquiriesConnection
collectionsConnection
lotStanding
auctionResultsByFollowedArtists
myCollectionAuctionResults
```
[Gravity PR](https://github.com/artsy/gravity/pull/16974)
@artsy/diamond-devs

feat: enable more queries for the braze

---

src/schema/v2/artworksForUser/helpers.ts
src/schema/v2/me/__tests__/artistRecommendations.test.ts
src/schema/v2/me/artistRecommendations.ts
src/schema/v2/me/artworkRecommendations.ts
src/schema/v2/me/newWorksByInterestingArtists.ts

This PR adds a friendlier message for non-authenticated requests.
Follow-up on [this comment](https://github.com/artsy/metaphysics/pull/5383/files#r1385388186).

feat: add error handling messages for queries

---

_schemaV2.graphql
src/data/gravity.graphql

https://artsyproduct.atlassian.net/browse/ONYX-514
Follow-up to https://github.com/artsy/gravity/pull/17045
> **warning**
> Gravity PR ☝🏽 must be merged first

chore(alerts): bump Gravity GraphQL schema for artist series additions

---

src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/__tests__/searchCriteriaLabel.test.ts
src/schema/v2/searchCriteriaLabel.ts

Ticket: [ONYX-523](https://artsyproduct.atlassian.net/browse/ONYX-523)
Update labels for Ways To Buy, `Purchase` instead of `Buy Now` and `Contact Gallery` instead of `Inquire`.
[ONYX-523]: https://artsyproduct.atlassian.net/browse/ONYX-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-523): update labels for ways to buy

---

src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch.ts

This PR addresses review comments on https://github.com/artsy/metaphysics/pull/5418 
Thanks @anandaroop for the thorough review.
I added a check for the `artistIDs` since we need them for suggestions. Let me know what you think about that
_Making sure I didn't break anything_

chore: address review comments on rarity suggested filters

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Follow up of https://github.com/artsy/gravity/pull/17079

feat(EMI-1545): expose Artwork#recentSavesCount field

---

src/schema/v2/artist/helpers.ts

[Resolves DIA-324](https://artsyproduct.atlassian.net/jira/software/projects/DIA/boards/146?selectedIssue=DIA-324)

fix: typo for insights helpers

---

_schemaV2.graphql
src/data/exchange.graphql

Follow up for: https://github.com/artsy/exchange/pull/1926

chore: exchange schema update

---

src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch.ts

This PR resolves [ONYX-581]
**Example Of suggested alerts for **Yayoi Kusama****
_Yayoi Kusama 2nd most popular rarity is `unknown edition` (it is not returned to client)_
**Example Of suggested alerts for **Andy Warhol****
[ONYX-581]: https://artsyproduct.atlassian.net/browse/ONYX-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: increase number of suggested results

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

Adding on to this previous PR: https://github.com/artsy/metaphysics/pull/5414

chore: adding medium, rarity, and price filters to alerts connection

---

_schemaV2.graphql
src/lib/__tests__/helpers.test.ts
src/lib/helpers.ts
src/schema/v2/alerts.ts
src/schema/v2/me/index.ts
src/schema/v2/notifications/Item/__tests__/index.test.ts
src/schema/v2/previewSavedSearch/searchCriteriaLabel.ts

This pull request adds the `labels` field to the `Alert` type in order to display the search criteria pills within the new Alert Notification screen in the app.

feat: Add labels fields to Alert type

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Changing the type to Money as per @starsirius comment at https://github.com/artsy/metaphysics/pull/5486/files#r1441712833

feat(EMI-1589): change Artwork#price_listed field type to Money

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/notifications/Item/PartnerOfferCreatedNotificationItem.ts
src/schema/v2/notifications/Item/__tests__/index.test.ts
src/schema/v2/notifications/Item/index.ts
src/schema/v2/notifications/index.ts

[Jira ticket](https://artsyproduct.atlassian.net/browse/ONYX-637)
[Gravity PR](https://github.com/artsy/gravity/pull/17224)
Adds support for such queries:
```graphql
query MyQuery {
me {
email
notification(id: "...") {
title
message
item {
... on PartnerOfferCreatedNotificationItem {
expiresAt
edges {
node {
title
}
}
}
}
}
}
}
}
```
```graphql
query MyQuery{ 
notificationsConnection(first: 5) {
edges {
node {
title
message
item {
... on PartnerOfferCreatedNotificationItem {
expiresAt
edges {
node {
title
}
}
}
}
}
}
}
}
}
```

feat(onyx-637): Add PartnerOfferCreated activity event

---

_schemaV2.graphql
src/schema/v2/me/__tests__/notification.test.ts
src/schema/v2/notifications/index.ts

Addresses [ONYX-657]
- Corresponding Gravity PR: https://github.com/artsy/gravity/pull/17284
Add headline field to Notification type.
[ONYX-657]: https://artsyproduct.atlassian.net/browse/ONYX-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add headline field to Notification type

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfile.ts

Addresses [this](https://github.com/artsy/metaphysics/pull/5530#discussion_r1466346675) comment.
Makes the inquiry requests count exposed on #5530 non-nullable.

fix(DIA-398): Make inquiry requests count non-nullable

---

_schemaV2.graphql
src/schema/v2/artworkResult/__tests__/index.test.ts
src/schema/v2/artworkResult/index.ts

Running Force + MP locally, and flushing out the schema a bit more. This is what was needed to render some reasonable grids.

chore: clean up data for PartialArtwork

---

_schemaV2.graphql
src/schema/v2/conversation/collectorResume.ts

Not sure if this description is meaningful - open to suggestions!

chore: add description for userId in collectorResume

---

_schemaV2.graphql
src/schema/v2/notifications/Item/PartnerOfferCreatedNotificationItem.ts
src/schema/v2/notifications/Item/__tests__/index.test.ts
src/schema/v2/partnerOffer.ts

Follow-up for https://github.com/artsy/gravity/pull/17314
We need to display price with and without discount in activity panel for partner offer notifications.

feat(onyx-718): add partnerOffer field for PartnerOfferCreated notifications

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

https://artsyproduct.atlassian.net/browse/EMI-1689
Expose purchasable in order to be used by the saved artworks table in Volt V2

feat: expose purchasable

---

_schemaV2.graphql
src/schema/v2/Alerts/createAlertMutation.ts
src/schema/v2/Alerts/deleteAlertMutation.ts
src/schema/v2/Alerts/index.ts
src/schema/v2/Alerts/updateAlertMutation.ts
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts

Let's thread this through so we can have access to it when we resolve an alert.

chore: add searchCriteriaID to Alert type

---

.eslintrc.json
peril/schemaValidatorUtils.ts
src/integration/__tests__/runStoredQueryTests.ts
src/lib/date.ts
src/lib/graphqlErrorHandler.ts
src/lib/graphqlTimeoutMiddleware.ts
src/lib/gravityErrorHandler.ts
src/lib/routing.ts
src/lib/stitching/causality/__tests__/testingUtils.ts
src/lib/stitching/convection/__tests__/testingUtils.ts
src/lib/stitching/exchange/__tests__/testingUtils.ts
src/lib/stitching/gravity/__tests__/testingUtils.ts
src/schema/v2/SearchableItem/SearchableItemPresenter.ts
src/schema/v2/__tests__/collectorProfiles.test.ts
src/schema/v2/artist/insights.ts
src/schema/v2/artwork/index.ts
src/schema/v2/artworkResult/index.ts
src/schema/v2/fields/numeral.ts
src/schema/v2/home/types.ts
src/schema/v2/image/normalize.ts
src/schema/v2/me/myCollectionInfo.ts
src/schema/v2/me/newWorksFromGalleriesYouFollow.ts
src/schema/v2/me/partners.ts
src/schema/v2/me/recentlyViewedArtworks.ts
src/schema/v2/me/similarToRecentlyViewed.ts
src/schema/v2/partner/partner.ts
src/schema/v2/sale/index.ts
src/schema/v2/sale_artwork.ts
src/schema/v2/search/SearchResolver.ts
src/schema/v2/test/utils.ts

This PR adds `"eslint:recommended",` to [.eslintrc.json](https://github.com/artsy/metaphysics/pull/5574/files#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090f) to add some more rules (e.g. [to avoid committing `debugger`](https://github.com/artsy/metaphysics/pull/5570#discussion_r1494314305)).

chore: Add eslint recommended rule to eslint config

---

src/schema/v2/notifications/__tests__/index.test.ts
src/schema/v2/notifications/index.ts

https://www.notion.so/artsy/Missing-sentence-casing-for-editorial-notification-912cc91082f749e8ba415c0ce88b850d?pvs=4
- Related Gravity PR: https://github.com/artsy/gravity/pull/17382
Remove toLowerCase on Notification message to keep them sentense case.

fix: Remove toLowerCase on Notification message to keep them sentence case

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/conversation/__tests__/conversation.test.js
src/schema/v2/conversation/index.ts

[DIA-481]
Wires up interestsConnection to the new endpoint `PartnerCollectorProfile#userInterests` endpoint on Gravity.
[DIA-481]: https://artsyproduct.atlassian.net/browse/DIA-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-481): wire up CollectorProfile#interestsConnection

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfile.ts

Enables Relay to use `@refetchable` annotation under `CollectorProfileType`.

feat(CollectorProfileType): implements Node on CollectorProfileType

---

_schemaV2.graphql
src/schema/v2/__tests__/createPartnerOfferMutation.test.ts
src/schema/v2/createPartnerOfferMutation.ts
src/schema/v2/partnerOffer.ts

https://artsyproduct.atlassian.net/browse/EMI-1734
Allow a note param when creating partner offers

feat(EMI-1734): partner offer note

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/me/__tests__/collector_profile.test.js

Description: 
We are removing this query in favor of [UserInterestsConnection](https://github.com/artsy/metaphysics/blob/main/src/schema/v2/CollectorProfile/collectorProfile.ts#L75).
collectorProfileArtists on this clients:
[Follow-up PR on volt-v2](https://github.com/artsy/volt-v2/pull/1305) ✅ 
Eigen ❌ 
Force ❌ 
Ticket: [DIA-532]
[DIA-532]: https://artsyproduct.atlassian.net/browse/DIA-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove collected artist names from collector profile

---

_schemaV2.graphql
src/schema/v2/me/userInterestsConnection.ts

Required to do numeric pagination

fix(me): adds page/size to args

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Addresses part 1 of Amber 515, adding this new field to ME to then be surfaced for Private Artworks listings.

chore: add new display_artist_bio field to Artwork

---

_schemaV2.graphql
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts

[Ticket](https://artsyproduct.atlassian.net/browse/DIA-553)
This PR adds the 'genomic' recommendations to `me`. This is the follow-up for https://github.com/artsy/gravity/pull/17568 
Genomic recommendations will only be used for Braze purposes.

feat: add genomic recommendations to me query

---

_schemaV2.graphql
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/partnerOfferToCollector.ts

In order to support showing the partner offer note in the artwork page for this ticket https://artsyproduct.atlassian.net/browse/EMI-1782

chore: add note to partner offer to collector

---

_schemaV2.graphql
src/schema/v2/artist/index.ts

The count in the collection table should be the count of the artworks you've collected.

feat(artist): exposes collected artworks count

---

src/schema/v2/me/index.ts

Not sure why I didn't think of this yesterday! We have this count denormalized already - it's just part of the collector profile.

fix: update to use denormalized saved_artworks_count

---

_schemaV2.graphql
src/data/specialistBios.json
src/schema/v2/__tests__/specialistBios.test.ts
src/schema/v2/specialistBios.ts

As requested by the Sales team:
- update the list of specialists
-  remove the speciality field as we are removing the specialists' filter
This data is not yet used by Eigen or Force so we should not worry about removing the speciality field in this PR, it will not cause issues

chore(ONYX-938): edit the list of specialists, remove specialty field

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Followup from https://github.com/artsy/gravity/pull/17666

feat(EMI-1853): expose Artwork abandoned order fields

---

_schemaV2.graphql
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/partnerOffer.ts
src/schema/v2/partnerOfferToCollector.ts

https://artsyproduct.atlassian.net/browse/EMI-1854
Support querying for https://github.com/artsy/gravity/pull/17669

feat(EMI-1854): add source to partner offer

---

src/data/specialistBios.json
src/schema/v2/__tests__/specialistBios.test.ts
src/schema/v2/specialistBios.ts

Add new specialists to the list of specialists
Add firstName field instead of parsing the name

adjust the list of specialists, add first name field

---

_schemaV2.graphql
src/schema/v2/me/update_me_mutation.ts

chore: allow promptedForUpdate argument in UpdateMyUserProfile mutation

---

_schemaV2.graphql
src/schema/v2/homeView/index.ts
src/schema/v2/homeView/stubDataResolver.ts

Implements `homeView.sectionsConnection`

feat: implements homeView.sectionsConnection

---

scripts/push-schema-changes.js

Noticed [some failures related to this](https://app.circleci.com/pipelines/github/artsy/metaphysics?branch=main).

chore: remove archived volt-v2 repo from schema change step

---

src/schema/v2/__tests__/marketingCollections.test.ts

This PR adds the base tests for marketing collections.

test: add base tests for marketing collections

---

src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts

Remove Listed submission type as with the current implementation it will not be used

chore: remove listed type

---

_schemaV2.graphql
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/index.ts
src/schema/v2/homeView/sections.ts

**Example**
```graphql
{
homeView {
section(id: "home-view-section-auction-lots-for-you") {
__typename
... on GenericHomeViewSection {
component {
title
}
}
}
}
}
```

feat: add homeView > section query field

---

_schemaV2.graphql
src/schema/v2/location.ts

Adds missing euShippingLocation field. 

feat(location): Add missing euShippingLocation field

---

src/schema/v2/marketingCollections.ts

This PR corrects thumbnail resolving field.

fix: resolve thumbnail for marketing collections

---

src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/artworkResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

This PR resolves [ONYX-1175]
This PR adds new works from galleries you follow artworks to the home view.
[ONYX-1175]: https://artsyproduct.atlassian.net/browse/ONYX-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add new works from galleries you follow

---

src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/artistResolvers.ts
src/schema/v2/homeView/artworkResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

Resolves [ONYX-1176]
This PR adds **Recommended Artists** as new artist section to the home view
[ONYX-1176]: https://artsyproduct.atlassian.net/browse/ONYX-1176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add recommended artists section

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewComponent.ts
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/heroUnitsResolver.ts
src/schema/v2/homeView/sections.ts

[Jira ticket](https://artsyproduct.atlassian.net/browse/ONYX-1187)
Adds `HeroUnitsHomeViewSection`:
```graphql
query X {
homeView {
sectionsConnection(first: 10) {
edges {
node {
... on HeroUnitsHomeViewSection {
heroUnitsConnection(first: 10, private: false) {
edges {
node {
title
}
}
}
}
}
}
}
}
}
```

feat(onyx): add hero units to new home view schema

---

src/schema/v2/homeView/HomeViewSection.ts

Looks like a type-error creeped through CI from the homeview work; fixing.

fix(homeview): Fix type error

---

src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/artworkResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

Request:
```graphql
query {
homeView {
section(id: "home-view-section-active-bids") {
... on ArtworksRailHomeViewSection {
component {
title
}
edges {
node {
title
}
}
}
}
}
}
}
```
Response:
```json
{
"data": {
"homeView": {
"section": {
"component": {
"title": "Your Active Bids"
},
"edges": [
{
"node": {
"title": "Untitled (Tiles)"
}
}
]
}
}
}
}
}
```

feat(onyx-1240): add Your Active Bids home view section

---

src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/artworkResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

Resolves [ONYX-1211]
This PR adds the artworks recommendations section.
[ONYX-1211]: https://artsyproduct.atlassian.net/browse/ONYX-1211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add artwork recommendations section

---

src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts

Addressed [Notion card](https://www.notion.so/artsy/Design-As-a-status-the-Complete-Listing-text-is-a-little-odd-it-sounds-like-it-already-is-a--edbb5f03e02d46dd99d77c99a7bc4154)
[Slack thread with discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1724940097819479)

chore: use Complete your Listing copy

---

src/schema/v2/__tests__/artistSeries.test.ts
src/schema/v2/artist/__tests__/index.test.js
src/schema/v2/artwork/__tests__/artwork.test.js

Was going to add these specs today, now that staging looks good before flipping the switch in production.
Indeed I did wind up flipping the switch in production before adding these (😆) so figured I'll get these in now before I forget.

chore: add tests for unstitched ArtistSeries

---

src/data/specialistBios.json

As [requested by Rachel H](https://docs.google.com/document/d/1IZmqoNsX-hWeLzuuiIvfiXZ1IWo8dK2Gz4KwSCPhymE/edit?disco=AAABP_q57ug), update the list of SWA specialists
Removed Caroline, added Susanna

feat(ONYX-1247): remove Caroline, add Susanna

---

src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/sections.ts

correct title for Recently viewed home view section

fix: correct title for Recently viewed home view section

---

src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts

Nice one on identifying this @joeyAghion ! We must have missed it when unwinding stitching from alerts earlier in the year.

chore: remove legacy use of savedSearchesConnection GravQL field

---

_schemaV2.graphql
package.json
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/sections.ts
yarn.lock

This PR adds a new string attribute, `contextModule`, to the HomeViewSection type in order to provide clients with a consistent label for use in analytics event payloads.
We had previously experimented with inferring this label from the section internal IDs but I think decoupling the two gives us more stability and flexibility as the Home View architecture matures.
Note: The second commit in this PR switches from hard-coded strings to imports from our [@artsy/cohesion](https://github.com/artsy/cohesion) package. This would introduce a dependency on cohesion for properly typing new section definition but I don't think would add considerably friction to the process overall. Open for debate though. cc/ @joeyAghion 
**Request**
```graphql
{
homeView {
sectionsConnection(first: 5) {
edges { …
```

feat: add contextModule property to HomeViewSection type

---

.circleci/config.yml
.gitignore
package.json
workers/test/ciTestWorker.toml
workers/test/ciTestWorker.ts
yarn.lock

This has yet to be updated with the exact script, but this PR supplies the infrastructure, pointed at our ci-test-worker namespace. 
Opening to get the CircleCI bits right. 

ci(cloudflare): Add automated deployments

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/CommerceOptIn/__tests__/commerceOptInMutation.test.ts
src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
src/schema/v2/schema.ts

This PR addressed ticket [AMBER-1019]
Description:
Creating a new mutation and loader in Metaphysics to allow for BNMO opt-in (actual updates, not the report).
[AMBER-1019]: https://artsyproduct.atlassian.net/browse/AMBER-1019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(AMBER-1019): Create Metaphysics mutation to opt-in artworks

---

src/lib/featureFlags.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/helpers/isSectionDisplayable.ts
src/schema/v2/homeView/index.ts
src/schema/v2/homeView/sections/FeaturedFairs.ts
src/schema/v2/homeView/sections/index.ts
src/schema/v2/homeView/zones/legacy.ts

@anandaroop Opened up this PR to illustrate a few potential adjustments to #6042.
- chore: update isDisplayable code comment
- refactor: include featureFlag in the section definition
- refactor: extract isSectionDisplayable

refactor: introduce featureFlag on section definition and extract isSectionDisplayable

---

_schemaV2.graphql
src/data/exchange.graphql

chore: update to latest exchange schema

---

package.json
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/sections/AuctionLotsForYou.ts
src/schema/v2/homeView/sections/News.ts
yarn.lock

Update contextModule/ownerType values for a couple sections.
Jira: [ONYX-1318](https://artsyproduct.atlassian.net/browse/ONYX-1318)
[ONYX-1318]: https://artsyproduct.atlassian.net/browse/ONYX-1318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(analytics): update contextModule/ownerType values for a couple sections

---

workers/caching/metaphysics-cdn.ts

Experimental: handle preflight requests directly from the worker, saving a little bit of network time requesting to and responding from our origin servers.

feat: respond to preflight requests from CDN (DIA-889)

---

src/schema/v2/homeView/sections/_ExampleSection.ts

Follow-up to the relaxation of the Cohesion requirements from  #6055 
And I saw a few minor opportunities for touch-ups and simplifications

docs(homeView): amend and simplify example section

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/tasks.test.ts
src/schema/v2/me/index.ts
src/schema/v2/me/task.ts

https://artsyproduct.atlassian.net/browse/EMI-2087
Opening https://github.com/artsy/gravity/pull/18184

feat(EMI-2087): add me tasks

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/dismiss_task_mutation.test.js
src/schema/v2/me/dismiss_task_mutation.ts
src/schema/v2/me/task.ts
src/schema/v2/schema.ts

https://artsyproduct.atlassian.net/browse/EMI-2088
Opening https://github.com/artsy/gravity/pull/18194

feat(EMI-2088): dismiss me tasks

---

docs/adding_a_new_home_view_section.md

This PR is still in progress - reviews are welcome though 👋 
This PR defines some guidelines on how to add a new home view section.
What's missing:

docs: add docs for creating a new home view section

---

src/schema/v2/me/__tests__/tasks.test.ts
src/schema/v2/me/index.ts

Addresses [EMI-2105]
* Follow-Up PR for https://github.com/artsy/gravity/pull/18220
This updates the me tasks pagination param from `limit` to` size`.
[EMI-2105]: https://artsyproduct.atlassian.net/browse/EMI-2105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Change `me/tasks` pagination param from `limit` to `size`

---

package.json
src/schema/v2/homeView/sections/Tasks.ts
src/schema/v2/homeView/sections/__tests__/Tasks.test.ts
yarn.lock

This PR resolves [EMI-2098]
This PR is a follow-up on artsy/cohesion#533
This PR adds a context module for tracking to the Tasks section in the HomeView
[EMI-2098]: https://artsyproduct.atlassian.net/browse/EMI-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2098): Add context module to Tasks section in the HomeView

---

src/schema/v2/homeView/sections/DiscoverSomethingNew.ts

This PR updates the final list for the 'Discover something new' component.

feat: updates the final list of the discover new collections

---

package.json
src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
src/schema/v2/homeView/sections/ExploreByCategory.ts
src/schema/v2/homeView/sections/__tests__/DiscoverSomethingNew.test.ts
src/schema/v2/homeView/sections/__tests__/ExploreByCategory.test.ts
yarn.lock

Related to [DIA-863]
This PR adds tracking to the Explore By and Discover Something New sections in the home view.
Extra: adds coverage to the Discover Something New that was missing
[DIA-863]: https://artsyproduct.atlassian.net/browse/DIA-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-863): add tracking to explore and discover home view sections

---

.circleci/config.yml

Fix a named messed up from the previous PR

ci(push-schema): correct push schema step name

---

src/lib/featureFlags.ts
src/schema/v2/artwork/collectorSignals.ts

Cleaning up signals flags so we can retire them.

chore: clean up emerald_signals-auction-improvements

---

src/schema/v2/partner/partner.ts

Closes: [DIA-760](https://artsyproduct.atlassian.net/browse/DIA-760)
Partner pages utilize the meta-schema on partners, so updating the title there will propagate automatically. I needed to explicitly pass the partner object attached to the profile since the owner is a stub lacking the required field. Beyond that, it's a straightforward change.
[DIA-760]: https://artsyproduct.atlassian.net/browse/DIA-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: differentiates churned gallery page titles

---

src/schema/v2/infiniteDiscovery/discoverArtworks.ts

1. Return curated works when user has no liked artworks.
2. Inject 2 random "challenge" artworks, also coming from the curated collection.

feat: infinite disco return curated artworks

---

Dockerfile

Follows https://github.com/artsy/metaphysics/pull/6242

fix: add load secrets script

---

Dockerfile

Follows https://github.com/artsy/metaphysics/pull/6243

fix: script path

---

src/data/specialistBios.json

Remove Jessica Backus from SWA specialists list as requested by Rachel H.

chore: remove Jessica Backus from SWA specialists list

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts
src/schema/v2/artwork/index.ts

Ass discussed, add isEditable field that indicates if an artwork can be edited to MP: https://github.com/artsy/eigen/pull/11249#pullrequestreview-2480985833

chore: add is editable field to ArtworkConsignmentSubmission

---

src/schema/v2/homeView/sections/_ExampleSection.ts

https://artsyproduct.atlassian.net/browse/ONYX-1444
Adds the `minimumEigenVersion` optional config from #6297 into the `_ExampleSection.ts` file.

docs(home view): add minimumEigenVersion to sample code

---

src/schema/v2/infiniteDiscovery/discoverArtworks.ts

- Hardcode limit to 10
- Fix the clause for initial taste

fix: use constant limit and fix the clause for initial taste

---

src/lib/infiniteDiscovery/findSimilarArtworks.ts

Forgot to update in https://github.com/artsy/metaphysics/pull/6334

fix: update query to support new fields

---

_schemaV2.graphql
src/lib/infiniteDiscovery/findSimilarArtworks.ts

This PR combines MLT with a filter to prevent duplicates from appearing in the results.
fyi @lilyfromseattle there are some format changes to the schema file related to https://github.com/artsy/metaphysics/pull/6339/files.

fix: use filter with mlt query

---

src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR adds hardcodes the limit for infinite discovery recommendations

chore: limit the amount of recommendations

---

_schemaV2.graphql
src/schema/v2/sale/__tests__/index.test.ts
src/schema/v2/sale/index.ts

Followup from https://github.com/artsy/gravity/pull/18499/files

feat: expose Sale hide_total and total_raised_minor fields

---

src/schema/v2/infiniteDiscovery/__tests__/discoverArtworks.test.ts
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

Replaces meLoader and uses the userID for the Gravity parameters.

fix: replace meLoader with userId

---

src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/sections/GalleriesNearYou.ts
src/schema/v2/homeView/sections/__tests__/GalleriesNearYou.test.ts

This PR addresses [ONYX-1511](https://artsyproduct.atlassian.net/browse/ONYX-1511)
[ONYX-1511]: https://artsyproduct.atlassian.net/browse/ONYX-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ONYX-1511): rename alleries section title

---

_schemaV2.graphql
src/schema/v2/homeView/sectionTypes/Card.ts
src/schema/v2/homeView/sections/InfiniteDiscovery.ts
src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts

Resolves [DIA-1126]
**Description**
This PR adds a new field to card to show a hint above the title. It will look like the image below.
[DIA-1126]: https://artsyproduct.atlassian.net/browse/DIA-1126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add badgeText to card

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/__tests__/creatArtworkImportMutation.test.ts
src/schema/v2/ArtworkImport/createArtworkImportMutation.ts

MP version of https://github.com/artsy/gravity/pull/18590 - just propagating the argument through.

chore: propagate original filename for artwork import

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

feat: add currency/price fields to ArtworkImport/Row schema

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Exposing the new row params added [in Gravity](https://github.com/artsy/gravity/pull/18639)

chore: adding new artwork import rows parameter

---

src/schema/v2/homeView/sections/QuickLinks.ts
src/schema/v2/homeView/sections/__tests__/QuickLinks.test.ts

Add two last quick links to MP: Featured fairs and Medium
https://github.com/user-attachments/assets/5636ea5f-5b5c-4a39-b49b-6e9593c0eadb

feat: add fairs and meduim quick links

---

src/schema/v2/previewSavedSearch/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch/searchCriteriaLabel.ts

https://artsyproduct.atlassian.net/browse/ONYX-1549
On rare occasions we unpublish an Artist Series for various marketplace integrity reasons.
When MP's `previewSavedSearch` logic encounters such a series, it currently errors because of the upstream 404.
This introduces more resilient handing of this edge case.
In the example below, the inclusion of Banksy's Dismaland (which _is_ still present in artwork aggregations — that's a separate issue) prevented the skeletons from resolving:
| Before | After |
|--------|--------|
| ![b](https://github.com/user-attachments/assets/5a0abc51-2cd1-48cf-a5a7-92b796479095) | ![a](https://github.com/user-attachments/assets/53ba877c-30fe-43b6-8bf3-54b23ca9bc2b) | 
You can see the upstream error here. Now we will simply skip over any 404-ing artists series …

fix(alerts): do not include unpublished artist series in previews

---

src/schema/v2/homeView/sections/InfiniteDiscovery.ts

Bumps minimumEigenVersion for infinite discovery

chore: bump minimumEigenVersion for infinite discovery

---

src/schema/v2/homeView/sections/InfiniteDiscovery.ts
src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts

This PR addresses [DIA-1189] providing some updates the the home view section of Discover Daily, additional changes in eigen portion. 
[DIA-1189]: https://artsyproduct.atlassian.net/browse/DIA-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-1189): Copy and creative changes to Discover Daily

---

src/schema/v2/homeView/sections/InfiniteDiscovery.ts

This PR updates the button on the Discover Daily entry point from "Try it" to "Try It"

fix(discover-daily): change entry point button text

---

src/schema/v2/artwork/index.ts

This PR adds the "Sculpture" medium to the list of 3D ones that are excluded from our View in Room feature on the artwork page. More chatter here:
https://artsy.slack.com/archives/C07PRTJSD6G/p1742485050792069?thread_ts=1742403472.263009&cid=C07PRTJSD6G
https://artsyproduct.atlassian.net/browse/AMBER-1398

chore: Add sculpture to 3d category list AMBER-1398

---

src/lib/featureFlags.ts
src/schema/v2/image/__tests__/index.test.js
src/schema/v2/image/index.ts

Reverts artsy/metaphysics#6538

chore: Revert "chore: removes blurhash feature flag"

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/Show/__tests__/createPartnerShowDocumentMutation.test.ts
src/schema/v2/Show/__tests__/deletePartnerShowDocumentMutation.test.ts
src/schema/v2/Show/__tests__/updatePartnerShowDocumentMutation.test.ts
src/schema/v2/Show/createPartnerShowDocumentMutation.ts
src/schema/v2/Show/deletePartnerShowDocumentMutation.ts
src/schema/v2/Show/updatePartnerShowDocumentMutation.ts
src/schema/v2/partner/partnerDocumentsConnection.ts
src/schema/v2/schema.ts

chore: add CRUD mutations for partner show document

---

_schemaV2.graphql
src/schema/v2/Feature/FeatureMeta.ts
src/schema/v2/Feature/FeatureType.ts
src/schema/v2/Feature/UpdateFeatureMutation.ts
src/schema/v2/__tests__/Feature.test.ts
src/types/runtime/gravity/Feature.ts

Exposes the `meta_title` field / supports editing.

feat(feature): exposes meta title

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/Show/__tests__/repositionArtworksInPartnerShowMutation.test.ts
src/schema/v2/Show/repositionArtworksInPartnerShowMutation.ts
src/schema/v2/schema.ts

chore: add mutation to reposition artworks in a show

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/Show/__tests__/repositionInstallShotsInPartnerShowMutation.test.ts
src/schema/v2/Show/repositionInstallShotsInPartnerShowMutation.ts
src/schema/v2/schema.ts

The last of the partner show related mutations!

chore: add mutation to reposition install shots in a show

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/exchange.ts
src/schema/v2/order/__tests__/submitOrderMutation.test.ts
src/schema/v2/order/index.ts
src/schema/v2/order/sharedOrderTypes.ts
src/schema/v2/order/submitOrderMutation.ts
src/schema/v2/order/updateOrderMutation.ts
src/schema/v2/schema.ts

https://artsyproduct.atlassian.net/browse/EMI-2304
This is the MP side of the [Exchange PR](https://github.com/artsy/exchange/pull/2470) to support submitting an Apple Pay order.

feat: submit an ApplePay order

---

_schemaV2.graphql
src/schema/v2/Feature/CreateFeatureMutation.ts
src/schema/v2/Feature/UpdateFeatureMutation.ts

Missed this for the create input/mutation.

fix(feature): adds field for create

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/createArtworkMutation.test.ts
src/schema/v2/artwork/createArtworkMutation.ts

A bit of orchestration to make it easier on the client - be able to not only create an artwork (w/ an artist + partner) and associate an uploaded image, but also optionally add it to a show!

chore: add a newly uploaded artwork to a show

---

src/schema/v2/partner/Settings/createPartnerContactMutation.ts

Fix: remove obnoxious console.log

fix: Removes console.log

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts
src/schema/v2/edition_set.ts
src/schema/v2/fields/money.ts
src/schema/v2/sellable.ts

Adds a few more fields to the `EditionSets` type and related network. 

feat(edition-sets): Add more fields

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts
src/schema/v2/edition_set.ts

Auditing Volt for missing artwork schema items and so far these items have come up. 

feat(artwork): Add some missing fields

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

Exposes `diameter` on artwork.

feat(artwork): add raw diameter field

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/exchange.ts
src/schema/v2/me/index.ts
src/schema/v2/order/__tests__/confirmationToken.test.ts
src/schema/v2/order/confirmationToken.ts

https://artsyproduct.atlassian.net/browse/EMI-2327
Follow up for https://github.com/artsy/exchange/pull/2513

feat(EMI-2327): stripe confirmation token

---

_schemaV2.graphql
src/schema/v2/partner/Mutations/PartnerArtist/updatePartnerArtistMutation.ts

These visibility fields are toggle-able by the partner.

chore: add some more visibility fields to updatePartnerArtist mutation

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/deleteArtworkMutation.test.ts
src/schema/v2/artwork/deleteArtworkMutation.ts
src/schema/v2/schema.ts

Seems inevitable we need this (on artwork edit form at least), plus _potentially_ on new uploads flow (depending on how eagerly we're creating artworks).

chore: add deleteArtwork mutation

---

_schemaV2.graphql
src/schema/v2/filterArtworksConnection.ts

Just threads through the argument added in https://github.com/artsy/gravity/pull/18857

chore: add categories as an input to filterArtworksConnection

---

_schemaV2.graphql
src/schema/v2/order/sharedOrderTypes.ts

https://artsyproduct.atlassian.net/browse/EMI-2431
`google_pay` is a payment method option for submitOrderMutation in MP

feat(EMI-2431): google pay option

---

_schemaV2.graphql
src/schema/v2/artwork/createArtworkMutation.ts

`deprecationReason` is not supported yet in Force.
Should fix https://github.com/artsy/force/pull/15473

chore: remove deprecation from input

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

This is now supported in https://github.com/artsy/gravity/pull/18855

chore: add inventory ID to artwork import row fields

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

chore: add Materials to artwork import row

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts
src/schema/v2/types/availability.ts

Relates to https://github.com/artsy/gravity/pull/18860
Add support for availability on Batch Edits through the bulk update mutation.

feat: Enable availability to be updated in Batch

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

Enable filtering artworks by:
- Availability
- Artist ID
Enable metadata update for:
- ecommerce (Purchase)
- offer (Make Offer)

chore: Enable more filters and fields for Batch Edits

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Solves [AMBER-1615]
Adds mapping for the new fields added in https://github.com/artsy/gravity/pull/18915
[AMBER-1615]: https://artsyproduct.atlassian.net/browse/AMBER-1615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-1615 - adding signature and condition for batch import

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Solves [AMBER-1535](https://artsyproduct.atlassian.net/browse/AMBER-1535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Adds the mapping introduced in https://github.com/artsy/gravity/pull/18910
[AMBER-1535]: https://artsyproduct.atlassian.net/browse/AMBER-1535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-1535 - bulk import signatures

---

_schemaV2.graphql
src/schema/v2/order/types/DisplayTexts.ts

This is just to get auto deploy possible. Will follow with actual removal after Force update.

chore: add back fields for automatic schema update

---

_schemaV2.graphql
src/schema/v2/order/types/DisplayTexts.ts

Quick clean up before we try to add some more experimental things to this type

chore: delete unused field as force schema was updated

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

Just noticed while working in Volt that I added the flat fee argument as snake_case. Replace it with camelCase instead.

chore: Apply camelCase to flat fee argument

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Solves [AMBER-1628]
Connects the fields that were added in https://github.com/artsy/gravity/pull/18931
[AMBER-1628]: https://artsyproduct.atlassian.net/browse/AMBER-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-1628 - batch import framed dimensions

---

src/schema/v2/filterArtworksConnection.ts

Hot fix: Follows https://github.com/artsy/gravity/pull/18927.

fix: reject 1 price range

---

src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/sections/AuctionLotsForYou.ts
src/schema/v2/homeView/sections/Auctions.ts
src/schema/v2/homeView/sections/LatestArticles.ts
src/schema/v2/homeView/sections/LatestAuctionResults.ts
src/schema/v2/homeView/sections/NewWorksForYou.ts
src/schema/v2/homeView/sections/RecommendedArtworks.ts
src/schema/v2/homeView/sections/ViewingRooms.ts
src/schema/v2/homeView/sections/__tests__/AuctionLotsForYou.test.ts
src/schema/v2/homeView/sections/__tests__/Auctions.test.ts
src/schema/v2/homeView/sections/__tests__/LatestArticles.test.ts
src/schema/v2/homeView/sections/__tests__/LatestAuctionResults.test.ts
src/schema/v2/homeView/sections/__tests__/RecommendedArtworks.test.ts
src/schema/v2/homeView/sections/__tests__/ViewingRooms.test.ts

Update homeview section titles and descriptions according to the Figma: https://www.figma.com/design/3LYkzfvfTPcYAIgzkaOM1C/Personalization?node-id=120-14348&m=dev

feat(ONYX-1729): update homeview section titles and descriptions

---

_schemaV2.graphql
src/schema/v2/bank_account.ts
src/schema/v2/credit_card.ts
src/schema/v2/me/__tests__/credit_cards.test.ts
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/exchangeJson.ts
src/schema/v2/order/types/sharedOrderTypes.ts

This PR resolves part of [EMI-2426]
This PR requires merging artsy/exchange#2583
This PR exposes the order payment details through MP
```graphql
query Query {
me {
order(id: "order-id") {
creditCardWalletType
paymentMethod
paymentMethodDetails {
__typename
... on CreditCard {
brand
lastDigits
expirationMonth
expirationYear
}
... on BankAccount {
last4
}
... on WireTransfer {
isManualPayment
}
}
}
}
}
```
<details><summary>Results</summary>
<p>
```json
{
"data": {
"me": {
"order": {
"creditCardWalletType": "GOOGLE_PAY",
"paymentMethod": "CREDIT_CARD",
"paymentMethodDetails": {
"__typename": "CreditCard",
"brand": "Visa",
"lastDigits": "4242",
"expirationMonth": 12,
"expirationYear": 2027
}
}
}
}
}
```
```json
{
"data": {
"me": {
"order": {
"creditCardWalletType": null,
"paymentMethod": …
```

feat(EMI-2426): Expose Order payment details

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/exchangeJson.ts
src/schema/v2/order/types/sharedOrderTypes.ts

Just adding this shippingOrigin to order Json to use on clients. The rest is just alphabetizing props as I noticed one duplicate. Hard to see if they are not alphabetical...

chore: add shippingOrigin to OrderJson

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/ArtworkImport/__tests__/updateArtworkImportMutation.test.ts
src/schema/v2/ArtworkImport/artworkImport.ts
src/schema/v2/ArtworkImport/updateArtworkImportMutation.ts
src/schema/v2/schema.ts

Solves [AMBER-1688]
This consumes the new and the updated endpoints added in Gravity https://github.com/artsy/gravity/pull/19063
[AMBER-1688]: https://artsyproduct.atlassian.net/browse/AMBER-1688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-1688 - artwork import preferences

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/sharedOrderTypes.ts

We need this data available in Force for the redirect logic.
https://artsyproduct.atlassian.net/browse/EMI-2591

feat(EMI-2591): expose Order#buyer_state field

---

_schemaV2.graphql
src/schema/v2/order/types/exchangeJson.ts
src/schema/v2/order/types/sharedOrderTypes.ts

https://artsyproduct.atlassian.net/browse/EMI-2487
We need to be able to have “contact the gallery” copy linking to the existing inquiry

feat(EMI-2487): impulse conversation id in order

---

_schemaV2.graphql
src/data/exchange.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/__tests__/updateOrderMutation.test.ts
src/schema/v2/order/types/exchangeJson.ts
src/schema/v2/order/types/sharedOrderTypes.ts
src/schema/v2/order/updateOrderMutation.ts

Followup from https://github.com/artsy/exchange/pull/2635

feat(EMI-2620): add Order#stripeConfirmationToken as param to order update

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

This PR introduces a catch to gracefully handle missing caption errors

fix: gracefully handle missing caption errors

---

_schemaV2.graphql
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts

Blocked by: https://github.com/artsy/gravity/pull/19125
This PR adds `hasPriceRange` to the Me interface.

feat: add hasPriceRange to Me interface

---

src/schema/v2/artist/helpers.ts

This PR adds the URL for the Summer 2025 Foundations exposed on clients.

feat: add foundations fair url for 2025

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

feat: Support provenance and medium batch fields
Connection these two PRs 
- https://github.com/artsy/gravity/pull/19136
- https://github.com/artsy/volt/pull/9505

feat: Support provenance and medium batch fields

---

_schemaV2.graphql
src/schema/v2/articles.ts

Adds ability to filter articles by author.

feat(articles): adds ability to filter by author

---

_schemaV2.graphql
src/schema/v2/author.ts

Adds the connection field for doing pagination.

feat(author): adds articles connection

---

_schemaV2.graphql
src/schema/v2/author.ts

Exposes the newly added Instagram handle.

feat(author): exposes instagram handle

---

_schemaV2.graphql
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts

Add `priceRangeUpdatedAt` introduced in following Gravity PR: https://github.com/artsy/gravity/pull/19198

feat(ONYX-1860): expose priceRangeUpdatedAt

---

_schemaV2.graphql

My pre-commit hook failed silently in #6980. Running it manually to update the schema v2.
Thanks, @leamotta for the pair.

fix: pre-commit schema-v2 updated

---

mcp-config.yml
mcp/operations/artist/updateArtist.graphql

This PR adds the update artist mutation as a addition to original PR https://github.com/artsy/metaphysics/pull/6982

feat(mcp update artist): add update artist mcp mutation

---

scripts/push-schema-changes.js

Updates our `push-schema-changes` config with `artsy-mcp`.

chore: Add artsy-mcp to push-schema-changes config

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Related:
- https://github.com/artsy/gravity/pull/19227
Exposes publicUrl on ArtworkImportImage.

feat(imports): Add publicUrl to import image

---

.circleci/config.yml

Followup from https://github.com/artsy/metaphysics/pull/7029

chore: decrease push-schema-changes parallelism

---

_schemaV2.graphql
src/schema/v2/author.ts
src/schema/v2/schema.ts

We'd like to add an authors index page to assist crawling. This adds a top-level authors connection.

feat(authors): adds top-level authors connection

---

src/schema/v2/conversation/conversations.ts
src/schema/v2/me/__tests__/conversations.test.js

https://artsyproduct.atlassian.net/browse/EMI-2750
Filter by conversation type after backend changes in Impulse https://github.com/artsy/impulse/pull/1291

feat(EMI-2750): filter by conversation type

---

_schemaV2.graphql
src/schema/v2/author.ts

Adds a better schema for social links.

feat(author): improves socials schema

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Solves [AMBER-1779]
Connects the fields that were added in https://github.com/artsy/gravity/pull/19316
[AMBER-1779]: https://artsyproduct.atlassian.net/browse/AMBER-1779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-1779 - adding more free text fields

---

_schemaV2.graphql
src/schema/v2/conversation/conversations.ts

https://artsyproduct.atlassian.net/browse/EMI-2834
Unread by partner param support after https://github.com/artsy/impulse/pull/1334

feat(EMI-2834): unread by partner param
