- schema/artist/index.js
- schema/artists.js
- schema/fields/event_status.js
- schema/index.js
- schema/partner_shows.js
- schema/sorts/artist_sorts.js
- schema/sorts/artwork_sorts.js
- schema/sorts/partner_show_sorts.js
> Shows schema

- package.json
No longer deferred require so this is failing in staging.
> @dzucconi: Move fakeredis to normal dependencies

- schema/article.js
- schema/articles.js
- schema/artists.js
- schema/author.js
- schema/fair.js
- schema/index.js
This is to support related articles on the new /show2 page.
> @craigspaeth => Adding some articles schema

- npm-shrinkwrap.json
- package.json
I think I need to adjust a setting in Semaphore as well.
> @broskoski: Upgrades to Node 5.1.1

- schema/input_fields/category_type.js
- schema/partner_category.js
Weird naming but it is what it is.
> @1aurabrown: PartnerCategoryTypeType

- schema/article.js
- schema/artist/carousel.js
- schema/artist/index.js
- schema/artwork/index.js
- schema/featured_link.js
- schema/gene.js
- schema/image/cropped.js
- schema/image/index.js
- schema/image/normalize.js
- schema/image/resized.js
- schema/image/versioned.js
- schema/partner_show.js
- schema/profile.js
- schema/search/search_result.js
- test/schema/artist/carousel.js
- test/schema/image/cropped.js
- test/schema/image/normalize.js
- test/schema/image/resized.js
- test/schema/image/versioned.js
> @mzikherman: Normalize image responses

- npm-shrinkwrap.json
- package.json
- schema/artwork/index.js
Adds related shows for an artwork!!!!! :art:
> @dzucconi - related shows

- schema/artwork/utilities.js
- test/schema/artwork/index.js
I was accidently using the v2 responses.
> @dzucconi: Fix `is_hangable` to work with API v1

- .env.test
- integration/index.js
- package.json
I'm not really sold on this as something that should be integrated as a build step and block a deploy. I more wanted to codify something I was manually doing before promoting staging => production.
Obviously this hits the network and isn't the fastest thing in the world.
> @mzikherman & @broskoski: Stab at integration specs

- schema/artwork/index.js
- schema/dimensions.js
- schema/edition_set.js
- schema/location.js
Mostly relevant to you is afb6498
> @broskoski: Artwork updates

- schema/aggregations/aggregation_count_type.js
- schema/aggregations/filter_partners_aggregation.js
- schema/filter_partners.js
- schema/index.js
results in this
lmk if you think it should be organized differently
> @dzucconi -> Filter partners

- lib/loaders/http.js
- schema/partner_show.js
I don't think we should be using this endpoint in the first place.
> @broskoski: Fix for default_image 404

- schema/partner.js
- schema/partners.js
I haven't utilized the partner shows bit on force yet, but basically what i wanted to do was to replace the primary carousel fetches with metaphysics. For the time being gravity is still being used.
I added these sorts to partners to randomize the carousels, etc.
> @dzucconi -> add some things

- schema/aggregations/filter_artworks_aggregation.js
- schema/filter_artworks.js
- schema/index.js
> @dzucconi - adds filter artwork schema

- schema/fairs.js
- schema/index.js
- schema/sorts/fair_sorts.js
> @broskoski => Fairs schema

- schema/partner_show.js
> @mzikherman: Fix for solo shows

- schema/me.js
- test/schema/me.js
This is kinda ugly, I'll comment inline.
> @dzucconi: Getting current bids only returns bids from open auctions

- schema/me.js
- test/schema/me.js
Implements [this Force PR](https://github.com/artsy/force/pull/4377) properly on the Metaphysics-side.
> @dzucconi: Stifle 404ed artworks from getting "my current bids"

- schema/bidder.js
- schema/me/bidders.js
- schema/me/index.js
- schema/me/sale_registrations.js
- schema/sale.js
- schema/sales.js
- test/schema/me/bidder_positions.js
- test/schema/me/sale_registrations.js
Other side of this coin looks like https://github.com/artsy/force/compare/master...dzucconi:settings?expand=1
> @craigspaeth: Me Auction Registrations

- schema/artist/carousel.js
- schema/artist/index.js
- schema/artist/statuses.js
- schema/image/index.js
> @dzucconi -> add some fields pertaining to artists

- schema/trending.js
In response to https://github.com/artsy/metaphysics/pull/140#issuecomment-196278383
Am pretty sure nothing actually uses this now—so there shouldn't be any issues with altering the args like this?
> @broskoski: Firm up TrendingArtists args

- schema/artist/index.js
> @dzucconi -> filter for active shows

- schema/artwork/index.js
Best guess at why https://github.com/artsy/force/issues/4570 is happening.
cc @briansw
> @mzikherman - catch is_contactable if related sale can't be fetched

- schema/me/bidder_positions.js
> @craigspaeth - allows filtering bidder positions by artwork id

- schema/artist/index.js
see https://github.com/artsy/gravity/pull/9865
> @broskoski -> filter related sales for live and is_auction

- lib/helpers.js
- test/lib/helpers.js
> @dzucconi: Empty strings should be false as well

- schema/image/deep_zoom.js
Now it *actually* works :tada:
> @dzucconi: Keys must be capitalized for deep zoom schema

- schema/artist/index.js
This adds a few new properties on the Artist object which are needed per [#1260](https://github.com/artsy/microgravity/issues/1260) this spec. The overview section is a bit premature, but later when the show logic for the artist is complete I think the overview property will be needed.
> @dzucconi: add new properties on artist schema

- schema/artist/index.js
Something like:
```
{
"data": {
"artist": {
"id": "pablo-picasso",
"name": "Pablo Picasso",
"exhibition_highlights": [
{
"id": "centre-for-fine-arts-bozar-picasso-sculptures"
},
{
"id": "musee-picasso-paris-picasso-an-anniversary-exhibition"
},
{
"id": "musee-picasso-paris-picasso-sculptor"
},
{
"id": "museum-of-modern-art-picasso-sculpture"
},
{
"id": "the-metropolitan-museum-of-art-unfinished-thoughts-left-visible"
}
]
}
}
}
```
> @dzucconi => Artist exhibition highlights

- schema/artist/index.js
cc @briansw 
Closes https://github.com/artsy/metaphysics/issues/173
> Tweaking exhibition highlights waterfall

- schema/partner.js
- schema/partner_shows.js
Wack diff due to this circular dependency work around. Which may or may not be fixed in some newer version of Babel. I'd update if I wasn't traumatized by every attempt.
> @broskoski: Better Artwork#shows fetch

- schema/artist/index.js
updated metaphysics for https://github.com/artsy/gravity/pull/9922
> @dzucconi -> related shows status param

- lib/helpers.js
- schema/artwork/index.js
- schema/artwork/meta.js
> @dzucconi: ArtworkMeta schema

- schema/partner_show.js
see the discussion in here about show cover images: https://github.com/artsy/force/issues/4768
lmk if this is not the way to do this.
> @dzucconi -> fallback partnershow cover image to artwork image

- lib/all.js
- lib/apis/fetch.js
- lib/loaders/gravity.js
- lib/loaders/http.js
- lib/loaders/index.js
- lib/loaders/total.js
- schema/artwork/index.js
- schema/ping.js
- schema/sale/index.js
- test/lib/all.js
- test/lib/apis/gravity.js
- test/lib/loaders/http.js
- test/lib/loaders/total.js
> @craigspaeth: "fetchUntilEndInParallel"

- schema/artist/index.js
for https://github.com/artsy/force/issues/4825
> @dzucconi: consignable flag on artist

- lib/loaders/authenticated_http.js
- test/lib/loaders/gravity.js
This deserves a spec—which I'll follow up with
> @craigspaeth: Resolve with body

- lib/helpers.js
- schema/artist/index.js
- schema/partner_show.js
- test/lib/helpers.js
> @dzucconi: Exclude artworks

- schema/artist/index.js
Super tiny change that adds nationality to the bio string per this [#1348](https://github.com/artsy/microgravity/issues/1348) QA issue.
> @dzucconi: adds nationality to bio

- schema/bidder_position.js
- schema/me/bidder_status.js
- schema/me/index.js
- test/schema/me/bidder_status.js
Implements schema needed for bidding module
> @craigspaeth: Me BidderStatus schema

- schema/me/index.js
> @craigspaeth => add a few fields to user

- schema/artist/meta.js
- test/schema/artist/meta.js
Misinterpreted the rounding rules:
> @dzucconi - update rounding rules for artwork count

- schema/artwork/index.js
- schema/partner.js
Changes are simple here. We can probably delete the field—but I'm not sure if Microgravity is using it yet. cc @xtina-starr
> @broskoski: Deprecate limited fair partnerships

- schema/artwork/index.js
- schema/partner.js
Reverts artsy/metaphysics#241 
we shall hold off on this until we get clear answers. valiant effort though.
> Revert "@broskoski: Deprecate limited fair partnerships"

- package.json
- scripts/dump-schema.js
Making this PR now so we can have discussions about how to do things, but probably ways off from merging.
> Schema dump script

- schema/causality_jwt.js
- test/schema/causality_jwt.js
MP side of this https://github.com/artsy/causality/pull/141
> @acjay: Observer role JWT

- schema/home/add_generic_genes.js
- schema/home/home_page_module.js
- schema/home/home_page_modules.js
- schema/home/params.js
- schema/index.js
Adds a query for getting a single home page module (which takes a key and optional id for `generic_gene` queries).
> @dzucconi - adds home_page_module query

- schema/artist/index.js
Updates bio property from 'lives and work in' to 'based in' [#1388](https://github.com/artsy/microgravity/issues/1388)
> @broskoski: update overview

- schema/artwork/context.js
- schema/artwork/index.js
- schema/artwork/layer.js
- schema/artwork/layers.js
- schema/artwork_layers.js
- schema/partner_show.js
- schema/profile.js
- test/schema/artwork/index.js
Mostly just correcting some of the fetch logic surrounding the ArtworkContext
> @broskoski: Artwork fetch refinements

- schema/artwork/index.js
> @dzucconi: Adds ability to fetch single show

- schema/artwork/context.js
> @broskoski: Exclude fair booths from context

- schema/sale/index.js
To update the new artwork views—and eventually an auction page refactor 😁
> @craigspaeth: `is_live_open` state for auctions

- schema/home/results.js
See https://github.com/artsy/force/issues/4704
and https://github.com/artsy/force/issues/4703
> @dzucconi - pull random sampling of results for fairs and galleries

- schema/bidder_position.js
- schema/fields/money.js
- schema/sale_artwork.js
- test/schema/sale_artwork.js
This keeps the existing interface working but also pulls through the `display` fields. Force PR coming.
> @broskoski: Support `display...dollars` fields

- lib/loaders/total.js
- schema/home/context.js
- schema/home/fetch.js
- schema/me/follow_artists.js
- schema/me/index.js
> @dzucconi - adds follow artists schema and context for following artists module

- schema/fair.js
talk to me if you have questions
> @dzucconi -> dont fetch an unpublished fair because it will error

- schema/home/context.js
- schema/home/fetch.js
- schema/home/results.js
- schema/home/title.js
This works to just render a regular rail, based on a related artist to a followed artist. Corresponding Force PR coming.
> @broskoski => Related Artist rail for homepage

- schema/artist/index.js
- test/schema/artist/index.js
> @alloy=> Partner Show Counts

- schema/sale_artwork.js
- test/schema/sale_artwork.js
This populates the full array of increments you would need to render the max bid select...
> @sweir27: Add full bid increments array

- schema/sale/index.js
For the clock on new artwork page
> @craigspaeth + @sweir: Expose live_start_at date

- schema/home/title.js
Re: https://github.com/artsy/force/issues/5207
> @broskoski - Update auction and fair module titles

- schema/artist/index.js
I though that this was in my last PR. anyway, here it is.
> @broskoski -> biography blurb with text and credit

- schema/author.js
> @kanaabe deprecate author href

- schema/artworks.js
- schema/index.js
Uses https://github.com/artsy/gravity/pull/10189
> @broskoski => Query for artworks by id

- schema/sale_artwork.js
Solves https://github.com/artsy/force/issues/5301
> @craigspaeth - Show reserve not met message if there is more than one bid and reserve is not yet met

- schema/article.js
- schema/artist/index.js
- schema/artwork/index.js
- schema/fair.js
- schema/gene.js
- schema/object_identification.js
- schema/partner.js
- schema/partner_category.js
- schema/partner_show.js
- schema/profile.js
- schema/sale/index.js
- schema/sale_artwork.js
The change was made in 545eb4c211641390defdd579affb5066de9c5276.
Related to #339.
> Revert the GraphQLString to GraphQLID argument type change.

- schema/artwork/index.js
This one is causing an issue in prod still.
cc @briansw
> @alloy => Revert GraphQLID for layer to string

- schema/fields/money.js
Related to the discussion here https://github.com/artsy/emission/issues/191
> [money] Add field descriptions.

- schema/home/home_page_module.js
Another one, this one affecting /home_2 (new homepage).
> @alloy => Relax a GraphQLID requirement

- schema/artist/index.js
- test/schema/artist/index.js
- if both nationality and birthday exist, MP will create a string of the form: "American, b. 2000"
- changes **Born 2000** or **born 2000** to **b. 2000**
- adds a **b.** if `birthday` is just a year
- will not change birthdays that include "Founded" or "Est."
made w help from @mennenia  ⭐
> Added a formatted birthday and nationality string

- schema/artist/index.js
> @alloy=>Made formatted_nationality_and_birthday syntax nicer

- schema/artwork/index.js
> @joeyAghion - Do not make multiple requests for checking biddable status

- schema/article.js
- schema/artist/index.js
- schema/artwork/index.js
- schema/home/fetch.js
- schema/home/home_page_artist_module.js
- schema/home/home_page_artist_modules.js
- schema/home/home_page_artwork_module.js
- schema/home/home_page_artwork_modules.js
- schema/home/home_page_module.js
- schema/home/home_page_modules.js
- schema/home/index.js
- schema/home/results.js
- schema/object_identification.js
- schema/partner.js
- schema/partner_show.js
- server.js
- test/schema/artist/carousel.js
- test/schema/artist/index.js
- test/schema/artwork/index.js
- test/schema/image/index.js
- test/schema/object_identification.js
- test/schema/partner_show.js
- test/schema/partner_shows.js
This adds artist rails to the `home_page` field, that work in much the same way as the artwork ones. The only artist rail that currently always returns an empty list is the `iconic` one, that needs some Gravity work that I’ll do next week or so.
In addition I have added `HomePageArtworkModule` to replace `HomePageModule`, but for now made it so that the existing root fields will still have the old types. Going forward we should get rid of those.
```graphql
{
home_page {
artist_modules {
__id
key
}
artwork_modules(max_rails: 1) {
__id
key
}
}
}
```
```json
{
"data": {
"home_page": {
"artist_modules": [
{
"__id": "SG9tZVBhZ2VBcnRpc3RNb2R1bGU6eyJrZXkiOiJzdWdnZXN0ZWQifQ==",
"key": "suggested"
},
{
"__id": "SG9tZVBhZ2VBcnRpc3RNb2R1bGU6eyJrZXkiOiJ0cmVuZGluZyJ9",
"key": "trending"
},
{
"__id": …
```
> [Home] Add artist modules

- .eslintrc.json
- schema/home/home_page_artist_module.js
- schema/home/home_page_artist_modules.js
- test/schema/home/home_page_artist_module.js
- test/schema/home/home_page_artist_modules.js
- test/schema/object_identification.js
This depends on https://github.com/artsy/gravity/pull/10241 being deployed.
> @broskoski => [Home] Add popular artists

- schema/fair.js
- schema/partner.js
- schema/partner_show.js
Also removes `is_limited_fair_partner` :) 👋
> @xtina-starr - Add some fields for Other Works updates

- schema/filter_artworks.js
- schema/partner.js
See https://github.com/artsy/force/issues/5068
> @broskoski: Filter partner artworks by for_sale

- schema/home/home_page_artwork_module.js
- test/schema/object_identification.js
This fixes https://github.com/artsy/emission/issues/253 by making [this](https://github.com/artsy/metaphysics/pull/388) work as suggested [here](https://github.com/artsy/metaphysics/pull/388#issuecomment-241855796).
```graphql
{
home_page {
artwork_module(key: "related_artists",
related_artist_id: "charles-broskoski",
followed_artist_id: "pablo-picasso") {
__id
key
params {
related_artist_id
followed_artist_id
}
}
}
}
```
```json
{
"data": {
"home_page": {
"artwork_module": {
"__id": "SG9tZVBhZ2VBcnR3b3JrTW9kdWxlOnsiZm9sbG93ZWRfYXJ0aXN0X2lkIjoicGFibG8tcGljYXNzbyIsInJlbGF0ZWRfYXJ0aXN0X2lkIjoiY2hhcmxlcy1icm9za29za2kiLCJrZXkiOiJyZWxhdGVkX2FydGlzdHMifQ==",
"key": "related_artists",
"params": {
"related_artist_id": "charles-broskoski",
"followed_artist_id": "pablo-picasso"
}
}
}
}
}
``` …
> [Home] Encode all required params for works for related artists.

- schema/artwork/index.js
This is a new (or maybe just reworked) endpoint that we are going to take a look at on the artwork page. Force PR forthcoming.
> @mzikherman - Adds related artworks to artwork schema

- schema/home/fetch.js
This reverts commit 8aaa4fdd195bfecf91af693972661a54ef60d9bd.
https://github.com/artsy/metaphysics/pull/397#issuecomment-244403441
> @mzikherman => Revert "[Home/Fair Artworks] Hotfix to work around Gravity bug."

- schema/fields/date.js
- schema/home/fetch.js
This adds an option to the date field to not convert the value to UTC as well as gets the auction that is closing first.
> @mzikherman - Add auction sort and additional time formatting options

- npm-shrinkwrap.json
- package.json
Looks like I downgraded and thought I updated :/
> @sweir27 - Actually update moment

- schema/home/home_page_artist_module.js
For the artist rails on the homepage, we don't want to show any artists who have 0 forsale works.
> @sweir27 - Exclude artists without for sale works from suggested endpoint

- schema/gene.js
Looks like people aren't adding tests for existing attributes - makes sense, so I've not included any. 
If you're also interested, I played with [support for types etc in VS Code](https://github.com/artsy/metaphysics/commit/64fad1cf33a6b4bc62a4c71d4f11b22bb768ecf3) too, might not PR that unless I have to ever do some real work in here.
> [Schema] Add description to the Gene

- schema/home/home_page_hero_units.js
- schema/home/index.js
- test/helper.js
- test/schema/home/home_page_hero_units.js
This has a little bit of support for the various platforms, but not too much, because we’re probably switching to a new system in the future.
> [Home] Add hero units.

- schema/aggregations/filter_artworks_aggregation.js
https://github.com/artsy/force/issues/206#issuecomment-251670568 item #2 and https://github.com/artsy/force/issues/88 # 3
> @broskoski: ability to sort each aggregation's counts differently

- lib/graphql-error-handler.js
- npm-shrinkwrap.json
- package.json
- server.js
Without this data it would be impossible to reproduce and debug what lead to an error.
> [logging] Include query and variables when reporting errors.

- index.js
- server.js
Small cleanup to address https://github.com/artsy/metaphysics/pull/420#issuecomment-251815694
> [logging] Move stack trace symbolication registration to index file.

- lib/graphql-error-handler.js
- test/helper.js
Continuation of the discussion on #430.
> [logging] Prefer the original error, when wrapped by graphql-js.

- lib/graphql-error-handler.js
- schema/show.js
- test/schema/show.js
Some shows seem to have no partner information. So switches from `if...else` to `if...if`
> @mzikherman => Don't ping Galaxy when shows lack any partner information

- schema/artist/index.js
- schema/show.js
Now that the Force artwork page supports these new types of shows, the next steps were to get it to the artist page. These are some minor updates for that.
> @mzikherman => Minor updates to support ref shows on Force artist page

- schema/partner.js
Closes https://github.com/artsy/force/issues/270
> @mzikherman - If the partner is an auction, give the proper href

- schema/home/context.js
- schema/home/fetch.js
- schema/home/logged_out_modules.js
- schema/home/results.js
- schema/home/title.js
- test/schema/home/home_page_artwork_module.js
- test/schema/object_identification.js
Part of https://github.com/artsy/force/issues/291
Fixes https://github.com/artsy/metaphysics/issues/438
⚠️ Be sure to do a synced merge/deploy with https://github.com/artsy/force/pull/297
> [Home/Artworks] Change iconic to popular and based on follows.

- schema/home/fetch.js
- schema/home/home_page_artwork_module.js
- schema/home/home_page_artwork_modules.js
- schema/home/results.js
- schema/home/title.js
- test/schema/home/home_page_artwork_modules.js
Fixes #447.
Part of https://github.com/artsy/emission/issues/321 & https://github.com/artsy/emission/issues/314.
The defaults should all be backwards compatible for Force.
> [Home] Optionally add more followed genes and allow client to dictate order of rails.

- schema/artist/index.js
> Add a description to the is_display_auction_link

- .eslintrc.json
- README.md
- npm-shrinkwrap.json
- package.json
- test/__mocks__/node-uuid.js
- test/helper.js
- test/lib/apis/gravity.js
- test/lib/auth.js
- test/lib/cache.js
- test/mocha.opts
Switches our test runner from Mocha to Jest, as they both have the same things under the hood, a lot of the changes end up being cosmetic main `before` -> `beforeAll`.
> Convert to Jest

- schema/home/home_page_artwork_module.js
This is also when a gene’s artworks are requested through the Node
interface.
Fixes https://github.com/artsy/emission/issues/379
> [Home/Artworks] Fetch a Gene when only an ID is provided.

- schema/filter_artworks.js
I _think_ this was removed accidentally.
> @mzikherman => Add back user access token to filter artwork requests

- lib/helpers.js
- schema/artist/meta.js
Closes https://github.com/artsy/force/issues/277
> @mzikherman - Actually strip markdown and truncate description

- schema/artwork/index.js
- test/schema/artwork/index.js
Depends on query param format being discussed in https://github.com/artsy/gravity/pull/10546. Code talks = +1 for `sale_ids`!!
> @joeyAghion => Reimplement is_in_auction to move away from ElasticSearch

- schema/artist/index.js
- test/schema/artist/index.js
Depends on https://github.com/artsy/gravity/pull/10553
> @cavvia => Use new partner_shows_count for artist counts

- schema/show.js
- test/schema/show.js
> @xtina-starr => Trim whitespace from exhibition titles

- schema/causality_jwt.js
- schema/me/index.js
- test/schema/causality_jwt.js
Closes https://github.com/artsy/auctions/issues/243
cc @erikdstock @sweir27
> Fall back to observer JWT for disqualified bidders

- schema/artwork/index.js
- schema/artwork/meta.js
I want this to be available for the purchase checkout page!
> @craigspaeth multiple artist names on artwork

- schema/artist/index.js
- test/schema/artist/index.js
Metaphysics part to allow queries for partner-submitted bios to return Markdown.
> @ashkan18 => Allow partner submitted bios to support Markdown params

- schema/artist/index.js
- test/schema/artist/index.js
Partly addresses https://github.com/artsy/force/issues/22
> @sarahscott - Adds deathday to formatted_nationality_and_birthday

- schema/artwork/index.js
- test/schema/artwork/index.js
See https://github.com/artsy/force/issues/457
> Return 'Untitled' for empty title fields on artworks

- schema/artwork/index.js
- test/schema/artwork/index.js
This should still display the range, but will only display 'Price' and no tooltip.
> @xtina-starr => Amend is_price_range to be false for multiple edition sets

- schema/artwork/index.js
- test/schema/artwork/index.js
Any work with multiple edition sets will be automatically not purchasable.
> @1aurabrown => Make works with multiple edition sets not purchasable

- changelog.md
- dangerfile.js
- package.json
- yarn.lock
This is a clone of #505 - my PRs were being classed as branch based, instead of  PR based CI builds.
> Testing whether PR ENV vars only appear from cross-repo PRs

- package.json
- server.js
- yarn.lock
I enabled a 14 day free trial, you can access it with your GitHub account at https://optics.apollodata.com/service/metaphysics
> Adds Apollo Optics instrumentation.

- schema/artwork/index.js
Going thru our Apollo Optics free trial, trying to optimize/remove expensive calls.
> @sweir27 => Replace some unneeded related/sales calls

- schema/filter_artworks.js
fixes https://github.com/artsy/metaphysics/issues/350
> @alloy -> move filter artworks totals to better counts pattern

- schema/artwork/index.js
For SEO purposes, we want an the `title` attribute on artwork images to have some extra info.
> @sweir27 - Adds image_title attr for artwork images

- index.js
- package.json
- yarn.lock
See discussion in #515 and closes #515.
> Reverts addition of Apollo Optics.

- schema/filter_artworks.js
Womp, forgot to add this before.
> @mzikherman => filter by artist ids in the filter artworks endpoint

- schema/viewer.js
In support of Prediction, this PR adds two additional fields to our new `Viewer` type, `Me` and `CausalityJWT`.
> Add Me and CausalityJWT to Viewer

- schema/artwork/index.js
- test/schema/artwork/index.js
Re: https://github.com/artsy/force/issues/791 and https://github.com/artsy/force/issues/790
Some additional options for getting the fine-grained states that determine artwork inquireability.
> @mzikherman - Update artwork sale message, add two new fields

- schema/artwork/index.js
- test/schema/artwork/index.js
This is preferable for Emission/Eigen.
> @broskoski => Return null instead of a blank string for not for sale sale_message

- schema/viewer.js
Adds a new `Sale` type to `Viewer` for use in Prediction.
> Add Sale to Viewer

- schema/artist/index.js
- test/schema/artist/index.js
Makes sense. `hasNextPage` was returning incorrect values because we weren't taking the filter into account when calculating the `arrayLength`
> @alloy - 	Calculate array length and take filter into account for artworks_connection

- lib/helpers.js
- schema/artist/index.js
- schema/artwork/index.js
- schema/filter_artworks.js
- schema/gene.js
- test/schema/gene/gene.js
Does some work to get artworks connection into the `Gene` schema (in order to fix your Gene page in Emission!).
> @orta - add artworks connection to gene schema

- schema/artists.js
See https://github.com/artsy/gravity/pull/10834
> @mzikherman => revert sale id on artist option

- .env.test
Specify the port in the sample `.env` included.
> Specify port 5001 in sample .env.test

- schema/me/notifications.js
fixes https://github.com/artsy/metaphysics/issues/557
> @mzikherman include image with notification bundle

- schema/artist/index.js
Not sure if this is even used anywhere?
This was the one other place that seemed to be querying for a count from positron.
> @kanaabe => One more articles count on artist

- schema/filter_artworks.js
This new commercial filter allows us to do keyword filtering on `/collect`.
> @mzikherman : add keyword filtering param for use on collect.

- schema/home/fetch.js
- schema/home/results.js
This is a WIP because I'm still setting up Emission locally to test that everything works. 
Fixes https://github.com/artsy/eigen/issues/2237
> @orta => Adds fetching for artworks with active bids

- schema/sale_artwork.js
(so we can start to use this in prediction/force/etc.)
> @joeyAghion => add reference to lot label

- schema/sale/index.js
- test/schema/sale/index.js
Little error here-- I'm actually not sure how I didn't notice it before since everything seemed to be working for me locally, but definitely a bug. 😮
> @mzikherman => dont fetch sale if it does not have an ID

- schema/me/artwork_inquiries.js
- test/schema/me/artwork_inquiries.js
> @l2succes => Expose impulse_conversation_id for inquiries

- schema/me/notifications.js
- test/schema/me/notifications.js
Depends on https://github.com/artsy/gravity/pull/10932 (which adds `id` to the response).
> @sarahscott => Add __id to notification connection for Relay

- schema/me/conversations.js
- schema/me/update_conversation.js
- test/schema/me/update_conversation.js
> @l2succes => Bring updateConversation up to Relay spec

- schema/artwork/index.js
- schema/index.js
- schema/me/save_artwork.js
- test/schema/me/save_artwork.js
Getting a weird error with about `deprecationReason`, will figure it out shortly...
> @mzikherman - Add saveArtwork mutation

- schema/sale/index.js
This is needed for an Eigen request.
> Adds require_bidder_approval field to Sale schema.

- schema/image/index.js
- schema/sale_artwork.js
We're moving some native code to use metaphysics, and it has some additional requirements.
> Adds fields required for eigen.

- index.js
- package.json
- yarn.lock
> @izakp => Adds artsy-morgan

- schema/artwork/index.js
Been banging my head on why this mutation in reaction-force wasn't working, turns out its because there were no id fields being returned...
> @mzikherman - Add gravity id fields to artworkField export

- package.json
- yarn.lock
vscode-jest won't give an annoying warning, and danger is pretty old on here.
Running tests locally actually fails for me, due to it calling out to memcached, wanted to test if it was just me or happens on CI too.
> Updates Jest and Danger

- changelog.md
- dangerfile.js
- schema/filter_artworks.js
- schema/index.js
- schema/tag.js
This is so we can get the objects we are filtering artworks on. Just supports `Tag` for now, but could support `Artist`, `Sale`, `Gene`, etc.
> @damassi - Add ArtworkFilterFacet and Tag schema

- package.json
> @sweir27 => Use node_modules/.bin/babel maybe?

- package.json
- yarn.lock
> @sweir27 => Explicitly add the babel-cli dep

- README.md
Merging so I can test deployment to staging.
> [README] Update to reflect MP wraps various services.

- lib/loaders/followed_artist.js
- schema/artist/index.js
- test/lib/loaders/followed_artist.js
> @mzikherman - Adds is_followed property on artist

- schema/artist/index.js
- schema/index.js
- schema/me/follow_artist.js
- test/schema/me/follow_artist.js
> @mzikherman - Adds followArtist mutation

- schema/index.js
- schema/match/artist.js
- test/schema/match/artist.js
Adds support for querying Artists using Elastic Search.
> [Consignments] Adds Artist match search to metaphysics

- schema/me/conversations.js
- test/schema/me/conversations.js
This PR adds some missing fields to the conversations schema to support the Inbox view
> [Messaging] adds artworks to conversation type

- schema/me/conversation.js
- schema/me/index.js
- test/schema/me/conversation.js
> [MSG] Adds Conversation to Me schema

- schema/show.js
For getting artworks in shows....the _relay_ way
> Add artworks_connection to show schema

- schema/fair.js
- schema/show.js
Same as earlier, adds shows connection to fairs.
> @damassi - Add Show connection to fair schema

- schema/me/conversation.js
- schema/me/conversations.js
- test/schema/me/conversation.js
Should be useful in the future when we have very long message threads.
Fixes #660
> [MSG] Made a Messages connection for conversations

- schema/me/conversation.js
- schema/me/conversations.js
- test/schema/me/conversation.js
I forgot to change the base branch back to master - this is part of #661
> [MSG] Made the messages field in a Conversation into a connection

- schema/object_identification.js
- schema/show.js
> @mzikherman - Add show to supported node types

- circle.yml
- lib/cache.js
- test/lib/auth/middleware.js
- test/lib/cache.js
- test/lib/loaders/http.js
> @joeyAghion => See if this fixes the memcache test failures

- circle.yml
> @orta => Deploy on PRs from master -> release via Circle

- schema/me/index.js
Following up on this PR: https://github.com/artsy/metaphysics/pull/668
Moved the initials to me
> [Conversations] Add initials field to user for avatar purposes (part 2)

- schema/artwork/index.js
- test/schema/artwork/index.js
Reverts artsy/metaphysics#689. See discussion in Slack: https://artsy.slack.com/archives/C0C4AJ1PF/p1499717572201483
> Revert "Filters closed sales from is_in_auction field."

- Procfile.dev
- schema/me/conversation/index.js
- schema/show.js
- test/schema/me/conversation/index.js
Part of https://github.com/artsy/emission/issues/672
> [Conversation] Add field to hold list of artwork and/or shows.

- schema/me/conversation/delivery.js
- schema/me/conversation/index.js
- schema/me/conversation/message.js
- test/schema/me/conversation/index.js
This should allow us to render the unread indicator correctly (will tackle that next).
> @joeyAghion => Expose expanded delivery information for message details

- schema/me/conversation/index.js
- test/schema/me/conversation/index.js
As discussed, this adds 2 fields that can be simply used by Emission (coming next) to render the indicator.
All future work can be done in Metaphysics/Impulse/Radiation, transparent to Emission.
> @joeyAghion => Add some fields to determine an unread indicator for a given recipient

- README.md
Shhh, let's pretend this never happened.
> Remove mentions of Semaphore

- README.md
- bin/setup
- yarn.lock
You never get a second chance to setup a project for the first time, so I went slow and noted where there were some rough edges. One pattern I've been using on Partner Success projects is a setup script that does some checking for dependencies and automates the obvious stuff, so this commit brings that to MP.
I hope you like it! ❤️
> Setup stuffs

- test/utils.js
Got this feedback from @alloy on #704, but then got sidetracked by robots.
> Further improve util func

- lib/loaders/per_type.js
- schema/article.js
- schema/articles.js
- schema/artwork/index.js
- schema/home/context.js
- schema/home/fetch.js
- schema/home/title.js
- schema/me/follow_artist.js
- test/schema/article.js
- test/schema/me/follow_artist.js
- test/schema/object_identification.js
This PR represents a bunch of work around understanding how loaders glue together and also are tested. I naively thought "oh, I'll just go through and find all the places where we're not using already extracted loaders and update them" - that's a lot of places!!
So, that's where I started, but then I found that I didn't always understand how the tests worked, so got into some trouble there and had to fix some things there. This was quite interesting and exposed me to some patterns there that I hadn't seen.
Anyway, time to open a PR for this and then move onto something else. 😉
> More loader work

- schema/home/fetch.js
- schema/home/home_page_artwork_modules.js
This extraction caused more problems than it was worth, so I'm reverting it for now and we can come back to it later.
/cc @alloy
> Revert using extracted loader

- schema/me/conversation/index.js
- test/schema/me/conversation/index.js
Based on the various in-flight PRs...
> @joeyAghion => Make the unread indicator accurate

- schema/home/home_page_artwork_modules.js
- schema/home/logged_out_modules.js
related issue: https://github.com/artsy/collector-experience/issues/362
> logged-out modules should respect requested order

- schema/home/home_page_artwork_modules.js
- schema/home/logged_out_modules.js
> Revert "logged-out modules should respect requested order"

- schema/me/conversations.js
- test/schema/me/conversations.js
Was noticing the pagination was being wonky, this looks like a bug.
> @l2succes => Fix pagination for conversations

- schema/me/conversation/index.js
- test/schema/me/conversation/index.js
Until I move the purch request copy! This gets the inbox nicely cleaned up, which was bugging me before.
> @ashkan18 => Temp hack to sanitize purch request text

- lib/loaders/loaders_with_authentication/impulse.js
- schema/index.js
- schema/me/conversation/index.js
- schema/me/conversation/mark_read_message_mutation.js
- test/schema/me/conversation/__snapshots__/index.js.snap
- test/schema/me/conversation/__snapshots__/mark_read_message_mutation.js.snap
- test/schema/me/conversation/index.js
- test/schema/me/conversation/mark_read_message_mutation.js
This works with my WIP Emission branch for this!
I'll clean up/add specs shortly...
> @l2succes => Mark message read mutation

- lib/apis/fetch.js
- lib/http_error.js
- schema/partner_show.js
- schema/show.js
- test/schema/partner_show.js
- test/schema/show.js
This will make those errors filtered out and not sent to NewRelic.
> [Show] Mark non-displayable shows as 404.

- .vscode/settings.json
- schema/me/consignments/create_submission_mutation.js
- schema/me/consignments/submission.js
- schema/me/consignments/update_submission_mutation.js
- test/schema/me/consignments/__snapshots__/add_asset_to_submission_mutation.js.snap
- test/schema/me/consignments/add_asset_to_submission_mutation.js
- test/schema/me/consignments/create_submission_mutation.js
- test/schema/me/consignments/update_submission_mutation.js
We removed it during feedback of https://github.com/artsy/metaphysics/pull/726 - but it's actually needed 👍
> Adds state to the submission mutations

- schema/me/conversation/index.js
- test/schema/me/conversation/__snapshots__/index.js.snap
- test/schema/me/conversation/index.js
As discussed, this can be added to a fragment and passed into the mutation.
> @l2succes => Add last_message_id to Conversation schema

- index.js
- lib/apis/gravity.js
- lib/loaders/api/index.js
- lib/loaders/api/loader_with_authentication_factory.js
- lib/loaders/api/loader_without_authentication_factory.js
- lib/loaders/index.js
- lib/loaders/loaders_with_authentication/index.js
- lib/loaders/loaders_without_authentication/index.js
- test/lib/apis/gravity.js
- test/lib/loaders/api.js
- yarn.lock
Reverts artsy/metaphysics#730
This PR appears to be causing issues in staging-- I want to investigate more without blocking deploys, so reverting this for now!
> Revert "@alloy => send request id to gravity"

- package.json
> Use the local copy of yarn for linting js files

- schema/artist/index.js
- test/schema/artist/index.js
This should fix the issue discussed, private shows appearing.
I think this is relatively harmless in the interim!
> @anandaroop => Dont return related shows for an artist from private partners

- schema/artist/index.js
- test/schema/artist/index.js
further investigation into weird shows on artist pages, revealed some of these.
> @mzikherman => Dont return partner-less related shows

- schema/me/conversation/invoice.js
- schema/me/index.js
- test/schema/me/conversation/__snapshots__/index.js.snap
- test/schema/me/conversation/index.js
I'm working on re-fetching a given Invoice (once a payment notification is received). I _think_ this may make it easier to do that, but I'm still messing around.
> @l2succes => Invoice implements NodeInterface (for easier re-fetching)

- schema/artist/index.js
- schema/object_identification.js
- test/schema/artist/index.js
> @mzikherman => Make sure we dont blacklist galaxy partners

- schema/me/consignments/submission.js
Updates the submission typings based on the schema [inside Convection](https://github.com/artsy/convection/blob/2052d5d4555b5e12c69bb937456ad2da83962be1/db/schema.rb#L43) 👍
> [Consignments] Updates the submission types

- index.js
- lib/apis/gravity.js
- lib/loaders/api/index.js
- lib/loaders/api/loader_with_authentication_factory.js
- lib/loaders/api/loader_without_authentication_factory.js
- lib/loaders/index.js
- lib/loaders/loaders_with_authentication/convection.js
- lib/loaders/loaders_with_authentication/impulse.js
- lib/loaders/loaders_with_authentication/index.js
- lib/loaders/loaders_without_authentication/gravity.js
- lib/loaders/loaders_without_authentication/index.js
- lib/loaders/loaders_without_authentication/positron.js
- test/lib/loaders/request_id.js
Paired with @orta on this iteration!
It's basically the same concept as the [last PR](https://github.com/artsy/metaphysics/pull/730), but I understand it a bit better and it has tests that execute the entire data-loader-creation flow, which is 👍 .
> @alloy => another attempt at passing through a request id to gravity

- .vscode/extensions.json
- lib/loaders/loaders_without_authentication/gemini.js
- lib/loaders/loaders_without_authentication/index.js
- test/lib/loaders/ensure_functions.js
Runs a test to ensure all objects in the loaders default to functions, not objects
> Ensure that all loaders return functions:

- .env.test
- index.js
Env var name is `QUERY_DEPTH_LIMIT`.
> Adds query depth limit env var.

- schema/asset_uploads/create_asset_request_mutation.js
These details are necessary in order to replicate [this section of gemup](https://github.com/artsy/gemup/blob/master/gemup.js#L38-L55)
> Adds more gemini metadata to the types

- schema/artwork/index.js
- test/schema/artwork/index.js
I believe this is causing all of these errors in force: https://sentry.io/artsynet/force-production/issues/345366185/.
> @mzikherman => be defensive about artworks with no images

- schema/sale/index.js
> @mzikherman => Remove redundant import statement

- lib/loaders/loaders_with_authentication/index.js
- schema/artist/index.js
- schema/me/suggested_artists.js
- schema/me/suggested_artists_args.js
- test/schema/me/__snapshots__/suggested_artists.js.snap
- test/schema/me/suggested_artists.js
Still to do: adding in that schema we talked about in https://github.com/artsy/metaphysics/pull/790#issuecomment-339298135
> @xtina-starr => [Onboarding] Add a proper loader for suggested artists

- schema/suggested_genes.js
Simple name changes to follow convention.
> Rename the SuggestedGenes schema name to be singular

- index.js
- lib/loaders/loaders_with_authentication/gravity.js
- lib/loaders/loaders_with_authentication/index.js
- lib/loaders/loaders_with_authentication/tracked_entity.js
- package.json
- schema/index.js
- schema/location.js
- schema/me/consignments/add_asset_to_submission_mutation.js
- schema/me/consignments/create_submission_mutation.js
- schema/me/update_me_mutation.js
- schema/user.js
- test/schema/me/__snapshots__/update_me_mutation.js.snap
- test/schema/me/update_me_mutation.js
For this screen
I'm going to need to be able to mutate the user's profile: thus, this PR.
There's one or two other things, will comment inline.
> Adds a mutation for editing a user

- schema/home/home_page_artwork_modules.js
- test/schema/home/home_page_artwork_modules.js
Part of https://github.com/artsy/collector-experience/issues/659
> [Home] Add option to exclude modules.

- lib/loaders/loaders_with_authentication/gravity.js
- lib/loaders/loaders_without_authentication/gravity.js
- schema/__tests__/sale_artworks.test.js
- schema/sale_artworks.js
```
{
sale_artworks {
edges {
node {
artwork {
id
}
}
}
}
}
```
```
{
sale_artworks(include_artworks_by_followed_artists:true) {
edges {
node {
artwork {
id
}
}
}
}
}
```
> [Loader] Add authenticatedSaleArtworksFilterLoader

- lib/__tests__/mergeSchemas.js
- lib/mergeSchemas.js
You were so close ;)
Took us a while to find this, but on the flip side - both me + @sweir27 now know how a bunch of this works 🌮 👯‍♂️ 👯 🍡
> Adds headers to convection requests with stitched schemas

- schema/partners.js
I think this closes https://github.com/artsy/metaphysics/issues/839
> @anandaroop => Fix partners loader use

- lib/loaders/loaders_with_authentication/gravity.js
- lib/loaders/loaders_without_authentication/gravity.js
- schema/gene.js
- schema/index.js
- schema/me/__tests__/follow_gene.test.js
- schema/me/follow_gene.js
This PR adds follow gene mutation so we can implement https://github.com/artsy/collector-experience/issues/506:
> Follow gene

- schema/__tests__/auction_results.test.js
- schema/artist/index.js
- schema/auction_result.js
I'll self merge since this is innocuous, but FYI!
> @joeyAghion => Add desired sort to auction results

- index.js
- schema/__tests__/sale_artworks.test.js
- schema/sale_artworks.js
Fixes an issue where pagination wasn't being properly passed to relay.
> @mzikherman => [Bugfix] Pagination in sale_artworks

- .env.test
- schema/sale/__tests__/index.test.js
- schema/sale/index.js
```
{
sale(id:"eriks-moction") {
is_live_open
live_url_if_open
id
}
}
```
> [Sale] Add live_url_if_open to Sale query

- schema/artwork/__tests__/artwork.test.js
- schema/edition_set.js
Closes https://github.com/artsy/collector-experience/issues/679
Updates from 'Available' to 'Contact for price'
> @mzikherman => Update edition set sale_message to match artwork

- schema/filter_artworks.js
Similar to tags, we want to be able to pull out the facet when filtering by gene, in order to be able to dynamically use the gene name in a headline view "Minimalism", "Minimalism for sale", etc on filters.
> @mzikherman => Add gene facet for use in gene filter headline

- lib/loaders/loaders_with_authentication/impulse.js
> Move has_message to @GET conversations

- schema/me/__tests__/follow_artist.test.js
- schema/me/follow_artist.js
This is the change we discussed on slack about adding a `popular_artists` field to the `FollowArtist` mutation so we can implement https://github.com/artsy/collector-experience/issues/811.
> Add popular_artists to FollowArtist mutation as an output field

- index.js
Not even gonna wait for this to go green.
> [server] Don’t try to load dev dependency in production.

- src/lib/loaders/loaders_with_authentication/gravity.js
- src/lib/loaders/loaders_without_authentication/gravity.js
- src/schema/match/__tests__/artist.test.js
- src/schema/match/artist.js
- src/schema/me/__tests__/artwork_inquiries.test.js
- src/schema/me/__tests__/save_artwork.test.js
- src/schema/me/artwork_inquiries.js
- src/schema/me/save_artwork_mutation.js
- wallaby.js
Wanted to make sure wallaby was working fine post #874 - it wasn't (paths changed) so I did some loaders.
> Add some more loaders (and fix wallaby post-reloadable merge)

- package.json
- patches/graphql+0.12.3.patch
- yarn.lock
Wanted to take another look at stitching, but figured I'd make separate PR updating it's dependents first.
> Update graph*ql deps, and apollo deps

- scripts/dump-schema.js
Will insta-merge, missed from the `src/` directory introduction.
> @mzikherman => Update path to schema in dump-schema script

- package.json
- src/schema/auction_result.js
> @mzikherman => Maybe correct currency code path

- package.json
Convert the post-build to be many steps and handles more json files in lib if they pop up.
> Minor build improvements

- src/lib/loaders/loaders_with_authentication/gravity.js
- src/schema/me/__tests__/bidders.test.js
- src/schema/me/bidders.js
Was waiting on CI for something else.
> Convert another gravity call to a loader

- package.json
- yarn.lock
Should get rid of the security vulnerability warning.
> @orta => Bump marked package for XSS vunerability

- src/schema/sale/index.js
Fixes https://github.com/artsy/collector-experience/issues/854#issuecomment-355557692
I'm somewhat certain that this bug was pre-metaphysics, but in any case I was able to tighten up the logic a bit to ensure more correctness.
> @sweir27 => [Bugfix] Ensure replace works correctly in `display_timely_at`

- src/schema/sale/__tests__/index.test.js
- src/schema/sale/index.js
This is a follow-up to https://github.com/artsy/gravity/pull/11495.
> @damassi => adds promoted_sale relation to sale model

- package.json
- patches/graphql-relay+0.5.3.patch
- src/schema/partner_artist.js
- yarn.lock
Revert the revert (what can go wrong?), and add `yarn patch-package` to the `heroku-postbuild` hook.
> @alloy => Re-add patch-package

- package.json
- patches/graphql-relay+0.5.3.patch
- yarn.lock
This should fix the build on Heroku.
> @mzikherman => Move patch-package out of dev dependencies

- src/schema/me/conversation/index.js
As discussed, let's just remove nullability here since these can be blank.
> @sarahscott => Last message can sometimes be null

- src/schema/home/__tests__/home_page_artwork_module.test.js
- src/schema/home/__tests__/home_page_artwork_modules.test.js
- src/schema/home/context.js
Just some more coverage as I was trying to understand an emission crasher.
> [HomePage] Add test coverage for followed and related artist context.

- src/schema/me/conversation/index.js
*BUT* does not do anything with it
Unblocks: https://github.com/artsy/emission/pull/968
> [Messaging] Adds a param for ignoreBlankMessages to the messages connection

- src/schema/filter_sale_artworks.js
For https://artsyproduct.atlassian.net/browse/IN-73
This does nothing yet.
> [SaleArtworks] Add param to filter by live sales.

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.js
Welp, turns out these messages come from MP, not the code in force that I changed here: artsy/force#2117
So, I'm doing that same change here.
AS-7 #close
> On loan default inquiry message

- src/lib/cache.js
> [cache] Actually use the parsed redis URL.

- src/schema/__tests__/sale_artwork.test.js
* Need to await
* Had to use this way to assert, as suggested here:
https://github.com/facebook/jest/issues/3601#issuecomment-333094824
> [test] Fix unhandled promise and the assertion.

- package.json
- yarn.lock
> [Lib] Bump express-reloadable 1.2.3

- src/lib/__tests__/cache.test.js
- src/lib/cache.js
This is still a stub, but I guess its spec/documentation now.
> @joeyAghion => Spec for correct delete method

- package.json
cc @izakp we were just talking about this lol https://github.com/heroku/heroku-buildpack-nodejs/issues/523
> @mzikherman => Pin yarn for heroku buildpack workaround

- package.json
Doh, I pinned this to the latest stable version for Heroku to use, but its not on Circle :(
> @mzikherman => Pin yarn to Circle CI version

- src/schema/__tests__/partners.test.js
- src/schema/partners.js
Adds `:ids` param to partners endpoint
> @mzikherman => Search partners by [:ids]

- src/schema/artist/__tests__/carousel.test.js
- src/schema/image/__tests__/cropped.test.js
- src/schema/image/__tests__/resized.test.js
- src/schema/image/proxies/embedly.js
- src/schema/image/proxies/gemini.js
Related to: https://github.com/artsy/force/pull/2226
We'll see a big increase in image loading speed by requesting images of a lower quality here.
cc @yuki24
> @mzikherman => change default image quality to 80

- .env.test
Didn't realize this was already listed.
> @mzikherman => Remove dupe from .env.test

- package.json
- yarn.lock
(Includes unpinning yarn per convo in #graphql channel)
> [Lib] Bump express-reloadable@1.3.0

- src/lib/loaders/loaders_with_authentication/gravity.js
- src/schema/home/__tests__/home_page_artwork_modules.test.js
- src/schema/home/fetch.js
pretty minor! Emission looks good on homepage with this change
> @mzikherman => Fix some fallout from homepage data loader refactors

- src/schema/home/__tests__/home_page_artist_module.test.js
- src/schema/home/home_page_artist_module.js
Missed this in https://github.com/artsy/metaphysics/pull/961
> @mzikherman => Fix last occurrence of improper resolving of a homepage loader

- README.md
> update README with links to Kubernetes, DataDog, Sentry 

- src/schema/me/__tests__/__snapshots__/update_me_mutation.test.js.snap
- src/schema/me/__tests__/update_me_mutation.test.js
- src/schema/me/update_me_mutation.js
Noticed some of these in prod: https://sentry.io/artsynet/metaphysics-production/issues/490033077/
I think theres an issue with recording the answer 'No Budget in Mind' currently.
> @yuki24 => Switch to float from int for budget question in /personalize

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.js
- src/schema/artwork/meta.js
Fixes a couple of Sentry issues for MP.
This is on top of https://github.com/artsy/metaphysics/pull/969
> @sweir27 => Be more defensive about partnerless artworks

- src/schema/__tests__/partner_shows.test.js
- src/schema/partner_shows.js
Adds support for fetching partner_shows with an array of ids.
> @mzikherman => Fetch partner_shows by [ids]

- src/lib/attributionClasses.js
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=SELL&modal=detail&selectedIssue=SELL-240&sprint=49
> Text change for Ephemera description.

- .env.test
- src/config.js
> Validate the ENV VARs for your current environment

- src/schema/collection.js
- src/schema/gene.js
- src/schema/me/consignments/submission.js
- src/schema/me/conversation/invoice.js
- src/schema/me/followed_artists_artworks_group.js
- src/schema/partner.js
- src/schema/partner_show.js
- src/schema/show.js
- src/schema/tag.js
After https://github.com/artsy/metaphysics/pull/913 , I think we can remove all of these.
> @orta => Remove isTypeOf from types implementing NodeInterface, in favor of resolveType

- package.json
Gotta tell babel to include these
> [build] Also include ts files

- src/schema/me/__tests__/recently_viewed_artworks.test.js
- src/schema/me/index.js
- src/schema/me/recently_viewed_artworks.ts
This adds `recentlyViewedArtworks`, which I decided to expose as a connection. Fairly standard, I'll make a comment in-line.
> @ashkan18 => Add recentlyViewedArtworks to Me schema

- src/lib/loaders/loaders_with_authentication/gravity.js
- src/schema/index.js
- src/schema/me/__tests__/recently_viewed_artworks.test.js
- src/schema/me/recently_viewed_artworks.ts
Adds a mutation to record an artwork view, based on https://github.com/artsy/gravity/pull/11649.
Will make a (hopefully) interesting comment in-line.
> @joeyAghion => Add mutation to record an artwork view

- src/schema/index.js
> @mzikherman => Prefer stitched version of recordArtworkView mutation, when flag is set

- src/lib/loaders/loaders_with_authentication/gravity.js
- src/schema/index.js
- src/schema/me/__tests__/bidder_position_mutation.test.js
- src/schema/me/bidder_position_mutation.js
Fixes [PURCHASE-65](https://artsyproduct.atlassian.net/browse/PURCHASE-65)
I wasn't sure about the naming conventions especially here that we have both `bidder_position` query and mutation so I would be happy to change them.
```
mutation {
createBidderPosition(input: {
artwork_id: "daryl-daniels-free-thyself-1"
max_bid_amount_cents: 380000
sale_id: "one-year-of-resistance-benefit-auction-2018"
}) 
{
position {
suggested_next_bid_cents
}
}
}
```
> Adds Bidder Position Mutation

- src/schema/home/__tests__/home_page_artwork_module.test.js
- src/schema/home/title.js
Fixes https://artsyproduct.atlassian.net/browse/DISCOVER-61
> @damassi => Changes home page module titles to sentence case

- hokusai/production.yml
Overprovisioning in response to https://trello.com/c/9LRDBDH4/64-api-load-spikes-and-metaphysics-crashes
cc @alloy @mzikherman
> more aggressive Metaphysics autoscaling parameters in production

- src/lib/loaders/loaders_without_authentication/gravity.js
- src/schema/artist/__tests__/index.test.js
- src/schema/artist/index.js
Artist can return an array of associated genes -- a collaborative effort with @xtina-starr.
> @joeyAghion => Artist genes

- src/lib/loaders/loaders_with_authentication/gravity.js
- src/schema/__tests__/gene.test.js
- src/schema/gene.js
Adds support for `is_followed` in gene schema
> @l2success => Gene can return is_followed

- src/schema/me/index.js
pretty easy, just expose the field (but make 🐫  case)
> @mzikherman => Add recently viewed artwork ids to me schema

- src/schema/home/title.js
Updates titles of new homepage modules
> capitalisation fix #minor

- src/schema/home/title.js
> switch to curly apostrophe in homepage module titles

- src/index.js
- src/lib/logQueryDetails.ts
The complete query and variables should now show up in a paper trail search.
> [debug] Log query details on 1 line to improve papertrail UX.

- package.json
- yarn.lock
> dependency "graphql-middleware"

- src/lib/tracer.js
Makes our traces each get their own service name so they show up in the datadog dashboard.
> service names

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.js
Fixes [EV-110](https://artsyproduct.atlassian.net/browse/EV-110)
> is_price_range should return true for single editioned artwork with price range

- package.json
- src/config.js
- src/lib/cache.js
- src/lib/stats.js
- yarn.lock
Set `STATSD_HOST=datadog` in staging and production
cc @alloy @acjay
> add statsd lib - counter and timer for cache slowlog

- src/lib/__tests__/cache.test.js
- src/lib/cache.js
This reverts commit 63fa0f742b493c2d2c4ef13050174d70b014d6d5.
> Revert "split cache client to reader and writer clients"

- src/schema/auction_result.js
Finishing up the container in Reaction.
> @mzikherman => Add remaining auction result sort options

- src/lib/graphqlTimeoutMiddleware.ts
This is a 1-liner fix, but something still keeps getting awry with my local setup, I always have these diffs (cc @damassi who tried to help, we thought it was just when I was touching files that weren't touched in a while), and this is a new file I believe.
> @orta => Return value from resolver

- package.json
Noticed some typescript formatting wasn't happening.
> @orta => Update precommit hook filetypes

- src/schema/artist/__tests__/index.test.js
- src/schema/artist/index.js
Whoops forgot to add this in https://github.com/artsy/metaphysics/pull/1123, just adds the prev/next functionality for articles.
> @mzikherman => Support hasNextPage and hasPreviousPage for articles connection

- src/schema/artist/__tests__/index.test.js
- src/schema/artist/index.js
Whoops, meant to deep-merge this in, added a spec.
> @mzikherman => Merge in data properly for article connection metadata

- src/lib/loaders/loaders_without_authentication/gravity.js
- src/schema/artist/__tests__/related.test.js
- src/schema/artist/index.js
- src/schema/artist/related.js
The current artist page was fetching the list of 'Related Categories' directly from the endpoint in Gravity, this adds it to Metaphysics.
> @damassi => Add related genes for an artist

- src/schema/__tests__/show.test.js
- src/schema/show.js
> @damassi => Return the fair city if available

- hokusai/production.yml
- hokusai/staging.yml
Only raise the memory limits for the moment - let's see how it behaves
> raise memory limits to 1Gi

- src/schema/auction_result.js
> @mzikherman => Be defensive about missing estimates for auction results

- src/schema/artwork/index.js
- src/schema/edition_set.js
- src/schema/sellable.ts
> [Sellable] Renamed from Saleable.

- src/schema/__tests__/ecommerce/create_order_mutation.test.js
- src/schema/__tests__/ecommerce/order.test.js
- src/schema/__tests__/ecommerce/orders.test.js
- src/schema/__tests__/ecommerce/submit_order_mutation.test.js
- src/schema/ecommerce/create_order_mutation.js
- src/schema/ecommerce/order.js
- src/schema/ecommerce/orders.js
- src/schema/ecommerce/submit_order_mutation.js
- src/test/fixtures/exchange/order.json
- src/test/fixtures/exchange/orders.json
- src/test/fixtures/results/sample_order.js
Adding more Order price related fields, follow up on #1152 
cc: @jonallured
> Add other price related fields

- src/schema/__tests__/ecommerce/approve_order_mutation.test.js
- src/schema/__tests__/ecommerce/create_order_mutation.test.js
- src/schema/__tests__/ecommerce/finalize_order_mutation.test.js
- src/schema/__tests__/ecommerce/order.test.js
- src/schema/__tests__/ecommerce/orders.test.js
- src/schema/__tests__/ecommerce/reject_order_mutation.test.js
- src/schema/__tests__/ecommerce/submit_order_mutation.test.js
- src/schema/ecommerce/approve_order_mutation.js
- src/schema/ecommerce/create_order_mutation.js
- src/schema/ecommerce/finalize_order_mutation.js
- src/schema/ecommerce/reject_order_mutation.js
- src/schema/ecommerce/types/order_mutation_input.js
- src/schema/index.js
- src/test/fixtures/exchange/order.json
- src/test/fixtures/exchange/orders.json
- src/test/fixtures/results/sample_order.js
Adds mutations to approve/reject/finalize orders, to be called from CMS.
> Adds approve/reject/finalize order mutations for partner users

- src/schema/__tests__/ecommerce/approve_order_mutation.test.js
- src/schema/__tests__/ecommerce/create_order_mutation.test.js
- src/schema/__tests__/ecommerce/finalize_order_mutation.test.js
- src/schema/__tests__/ecommerce/order.test.js
- src/schema/__tests__/ecommerce/orders.test.js
- src/schema/__tests__/ecommerce/reject_order_mutation.test.js
- src/schema/__tests__/ecommerce/submit_order_mutation.test.js
- src/schema/ecommerce/approve_order_mutation.js
- src/schema/ecommerce/create_order_mutation.js
- src/schema/ecommerce/finalize_order_mutation.js
- src/schema/ecommerce/reject_order_mutation.js
- src/schema/ecommerce/types/order_mutation_input.js
- src/schema/index.js
- src/test/fixtures/exchange/order.json
- src/test/fixtures/exchange/orders.json
- src/test/fixtures/results/sample_order.js
WIP: needs to be rebased
Moves mocking exchange schema code into a helper file to be reused.
> WIP: Refactors exchange schema mocking

- src/schema/__tests__/ecommerce/approve_order_mutation.test.js
- src/schema/__tests__/ecommerce/create_order_mutation.test.js
- src/schema/__tests__/ecommerce/finalize_order_mutation.test.js
- src/schema/__tests__/ecommerce/order.test.js
- src/schema/__tests__/ecommerce/orders.test.js
- src/schema/__tests__/ecommerce/reject_order_mutation.test.js
- src/schema/__tests__/ecommerce/submit_order_mutation.test.js
- src/test/fixtures/exchange/mockxchange.js
#Trivial
Moved code for mocking exchange schema for tests into a helper function.
> Refactors mocking exchange

- src/schema/artist/__tests__/index.test.js
- src/schema/artist/shows.js
> @zephraph => Add total count for artist shows connection

- src/data/exchange.graphql
- src/schema/__tests__/ecommerce/approve_order_mutation.test.js
- src/schema/__tests__/ecommerce/create_order_mutation.test.js
- src/schema/__tests__/ecommerce/finalize_order_mutation.test.js
- src/schema/__tests__/ecommerce/order.test.js
- src/schema/__tests__/ecommerce/orders.test.js
- src/schema/__tests__/ecommerce/reject_order_mutation.test.js
- src/schema/__tests__/ecommerce/submit_order_mutation.test.js
- src/schema/ecommerce/approve_order_mutation.js
- src/schema/ecommerce/create_order_mutation.js
- src/schema/ecommerce/finalize_order_mutation.js
- src/schema/ecommerce/order.js
- src/schema/ecommerce/orders.js
- src/schema/ecommerce/reject_order_mutation.js
- src/schema/ecommerce/submit_order_mutation.js
- src/schema/ecommerce/types/order.js
- src/test/fixtures/exchange/order.json
- src/test/fixtures/exchange/orders.json
- src/test/fixtures/results/sample_order.js
`totalCents` and `subtotalCents` were added as part of https://github.com/artsy/exchange/pull/56, this PR basically adds those to MP.
> Add totalCents and subtotalCents

- .vscode/settings.json
- src/lib/gravityErrorHandler.js
- src/lib/loaders/api/loader_interface.ts
- src/lib/loaders/api/loader_one_off_factory.ts
- src/lib/loaders/api/loader_with_authentication_factory.ts
- src/lib/loaders/api/loader_without_authentication_factory.ts
- src/lib/stitching/convection/__tests__/stitching.test.ts
- src/schema/artwork/index.js
- src/schema/asset_uploads/create_asset_request_mutation.ts
- src/schema/asset_uploads/finalize_asset_mutation.ts
- src/schema/auction_result.js
- src/schema/ecommerce/types/order.js
- src/schema/index.ts
- src/schema/me/__tests__/bidder_position_mutation.test.js
- src/schema/me/__tests__/consignments/create_submission_mutation.test.js
- src/schema/me/__tests__/consignments/update_submission_mutation.test.js
- src/schema/me/bidder_position_messages.ts
- src/schema/me/consignments/create_submission_mutation.ts
- src/schema/me/consignments/update_submission_mutation.ts
- src/schema/me/lot_standing.js
- src/schema/sale_artwork.js
- src/schema/sales.js
- src/schema/system/__tests__/time.test.js
By fixing small typescript errors and moving a few more files to be `*.ts`.
> [dev] Make yarn tsc pass

- src/schema/artist/__tests__/current.test.js
- src/schema/artist/current.js
```graphql
{
artist(id: "andy-warhol") {
currentEvent {
event {
__typename
... on Sale {
id
}
}
}
}
}
```
```json
{
"data": {
"artist": {
"currentEvent": {
"event": {
"__typename": "Sale",
"id": "alpha-137-prints-and-exhibition-ephemera-iv"
}
}
}
}
}
```
> [CurrentEvent] Expose actual event object as well.

- index.js
- package.json
- yarn.lock
Reverts artsy/metaphysics#1176 - looks like performance is better with bluebird
> Revert "Switch to the native promise in node"

- src/schema/__tests__/ecommerce/set_order_payment_mutation.test.js
- src/schema/ecommerce/create_order_mutation.js
- src/schema/ecommerce/finalize_order_mutation.js
- src/schema/ecommerce/reject_order_mutation.js
- src/schema/ecommerce/set_order_payment_mutation.js
- src/schema/ecommerce/set_order_payment_mutation.ts
- src/schema/ecommerce/submit_order_mutation.js
- src/schema/index.ts
This adds `setOrderPayment` mutation to match `setPayment` mutation that was added to exchange + few small typo fixes.
> Add setPayment

- src/schema/artist/__tests__/current.test.js
- src/schema/artist/current.js
defaults to EST/EDT (which is the current behavior), if client doesnt specify.
> @mzikherman => Include time of day and better label for artist current event

- src/lib/loaders/api/loader_without_cache_factory.ts
Still not 100% sure, but this fixes the repro'd issue.
> @orta => Dont batch uncached calls

- hokusai/production.yml
Set max replicas to 20 - target CPU utilization to 70%
> allow production to scale out more

- package.json
From the comments in https://github.com/artsy/metaphysics/pull/1170
> Removes the danger check on a push

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.js
Not sure if we have to account for some other rules here but for now just putting the default implementation of converting cents to money string. Also seems like in most cases where we use this - the cents are ignored in the full amount. So doing it here as well, not sure that is correct. 
Some formatting changes just from my re save of the file...
> add domesticShipping and internationalShipping to artwork

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.js
- src/schema/fields/money.js
This change might be a bit controversial but none of the specs are failing and I've added a spec that I wanted to be true.
Basically we need to be able to distinguish amount is not entered vs amount is 0 for money. That is one way to achieve that.
> Merging domesticShipping and internationalShipping into shippingInfo property

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.js
- src/schema/me/conversation/index.js
> deprecating is_purchasable on artwork and purchase_request on conversation

- src/schema/artist/index.js
reflecting 2 new counts for artist (to control UI 'does this artist have any works currently at auction' 'does this artist have any ecommerce enabled works')
> @mzikherman => Add ecommerce and auction artworks count to artist schema

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.js
Simple addition to get shippingOrigin into Force.
> add shippingOrigin to artwork

- src/schema/filter_artworks.js
Once https://github.com/artsy/gravity/pull/11866 is deployed
> @mzikherman => Use new acquireable filter instead of ecommerce

- src/data/exchange.graphql
- src/schema/__tests__/ecommerce/approve_order_mutation.test.js
- src/schema/__tests__/ecommerce/create_order_with_artwork_mutation.test.js
- src/schema/__tests__/ecommerce/fulfill_order_at_once_mutation.test.js
- src/schema/__tests__/ecommerce/order.test.js
- src/schema/__tests__/ecommerce/orders.test.js
- src/schema/__tests__/ecommerce/reject_order_mutation.test.js
- src/schema/__tests__/ecommerce/set_order_payment_mutation.test.js
- src/schema/__tests__/ecommerce/set_order_shipping_mutation.test.js
- src/schema/__tests__/ecommerce/submit_order_mutation.test.js
- src/schema/ecommerce/approve_order_mutation.js
- src/schema/ecommerce/create_order_with_artwork_mutation.js
- src/schema/ecommerce/fulfill_order_at_once_mutation.ts
- src/schema/ecommerce/order.js
- src/schema/ecommerce/orders.js
- src/schema/ecommerce/reject_order_mutation.js
- src/schema/ecommerce/set_order_payment_mutation.ts
- src/schema/ecommerce/set_order_shipping_mutation.ts
- src/schema/ecommerce/submit_order_mutation.js
- src/schema/ecommerce/types/order.ts
- src/test/fixtures/exchange/order.json
- src/test/fixtures/exchange/orders.json
- src/test/fixtures/results/sample_order.js
Catch up with Exchange schema updates for adding `shippingName` to `Order` and `setShipping` mutation.
> Add shippingName and catch up with Exchange schema updates

- src/data/exchange.graphql
I'm not sure what all the other formatting is all about :(
> @ashkan18 an18 => update schema to allow null shipping names

- src/schema/me/followed_artists_artworks_group.js
> @mzikherman => Allow for_sale to be passed in for bundled artwork groups #minor

- src/schema/filter_artworks.js
If https://github.com/artsy/gravity/pull/11868 gets the nod
> @mzikherman => Add inquireable filter param

- src/schema/me/followed_artists_artworks_group.js
For use in linking, and displaying a date.
> @mzikherman => Add a couple more fields to notifications for use in new /works-for-you

- src/schema/ecommerce/approve_order_mutation.ts
- src/schema/ecommerce/create_order_with_artwork_mutation.ts
- src/schema/ecommerce/extractEcommerceResponse.ts
- src/schema/ecommerce/fulfill_order_at_once_mutation.ts
- src/schema/ecommerce/order.js
- src/schema/ecommerce/orders.js
- src/schema/ecommerce/reject_order_mutation.ts
- src/schema/ecommerce/set_order_payment_mutation.ts
- src/schema/ecommerce/set_order_shipping_mutation.ts
- src/schema/ecommerce/submit_order_mutation.ts
Following on from this discussion: https://github.com/artsy/metaphysics/pull/1247#discussion_r213449603
> reinstate error handling for ecommerce requests

- src/lib/nameOldEigenQueries.ts
Catches [these traces](https://app.datadoghq.com/apm/resource/metaphysics.graphql/graphql.query/c1dc8c86a146ee60?env=production&paused=false&traceID=6262491963127494092&spanID=11765257474762036498&start=1535733328214&end=1535736928214)
> Fix typo in catch for unread count in eigen

- src/lib/nameOldEigenQueries.ts
Moves the check for a query to where it's being used.
> Refactor the query check in the eigen queries

- src/lib/tracer.ts
- yarn.lock
> [tracer] More refinements

- src/lib/nameOldEigenQueries.ts
Found more:
```
Thu, 13 Sep 2018 20:30:36 GMT error Unexpected Eigen query: mutation {
createConsignmentSubmission(input:{ clientMutationId: "shgwi9vtqe", artist_id: "5603b9167261695a8d000633", edition: false, location_city: "Vestavia Hills", location_country: "United States", location_state: "Alabama"}) {
consignment_submission {
id
}
}
}
POST / 400 6.521ms 108.54.246.210 "Mozilla/5.0 Artsy-Mobile/4.2.1 Eigen/2018.07.23.07/4.2.1 (iPhone; iOS 12.0; Scale/3.00) AppleWebKit/601.1.46 (KHTML, like Gecko)"
Thu, 13 Sep 2018 20:31:00 GMT error Unexpected Eigen query: mutation {
updateConsignmentSubmission(input:{ clientMutationId: "tkcmeqweax", artist_id: "5603b9167261695a8d000633", state: SUBMITTED, category: PRINT, depth: "1", edition: true, height: "58", location_city: "Vestavia Hills", …
```
> Adds some more eigen queries

- hokusai/production.yml
Been running this all week and it seems better - still getting OOMKilled but not as frequently
> bump memory limits in prod

- src/lib/tracer.ts
> [tracer] Fix Express configuration.

- _schema.graphql
- src/schema/index.ts
Alright, this should make #1279 not a breaking change for volt 👍
> Adds the underscore fields to the schema for exchange

- _schema.graphql
- src/data/exchange.graphql
- src/lib/stitching/exchange/__tests__/__snapshots__/schema.test.ts.snap
- src/schema/ecommerce/types/orders_sort_method_enum.ts
This PR gets MP back in sync with Exchange for the order sorts that I added over there with https://github.com/artsy/exchange/pull/186.
> Update exchange schema

- _schema.graphql
- src/schema/credit_card.js
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-466
> Add billing address fields to the CreditCard type

- src/schema/sale/__tests__/index.test.js
- src/schema/sale/display.ts
- yarn.lock
Uses the recommended approach in https://github.com/moment/moment/issues/2781 , which feels...unexpected.
> @damassi => Customize relative time formatting for moment

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.ts
This addresses https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-305
Force just displays this property, so the change is here in metaphysics.
> handle null domestic shipping when international is present for artwork

- _schema.graphql
- src/data/exchange.graphql
- src/lib/stitching/exchange/__tests__/__snapshots__/schema.test.ts.snap
- src/schema/__tests__/ecommerce/order_fields.ts
- src/schema/ecommerce/approve_order_mutation.ts
- src/schema/ecommerce/create_order_with_artwork_mutation.ts
- src/schema/ecommerce/fulfill_order_at_once_mutation.ts
- src/schema/ecommerce/order.js
- src/schema/ecommerce/orders.js
- src/schema/ecommerce/reject_order_mutation.ts
- src/schema/ecommerce/types/order.ts
- src/test/fixtures/exchange/order.json
- src/test/fixtures/exchange/orders.json
- src/test/fixtures/results/sample_order.js
Depends on https://github.com/artsy/exchange/pull/196
Updates Exchange schema and adds `stateReason` to order fields.
> Adds stateReason to MP

- scripts/dump-schema.ts
Adds the ability to dump the schema as a json as well as continuing support to dump the schema as SDL.
> Add support for dumping schema as json

- _schema.graphql
- src/schema/filter_artworks.js
- yarn.lock
Pretty boilerplate, we can now pass in an array of these for filtering once https://github.com/artsy/gravity/pull/11947 is in.
> @cavvia => Allow filtering by attribution class for artworks

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.ts
This is the first part of https://artsyproduct.atlassian.net/browse/DISCO-402
The minimal version for now that just changes the signature name and removes icons.
> signed should be displayed as signature on artwork details page

- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.ts
Address https://artsyproduct.atlassian.net/browse/DISCO-395
> fix null internation shipping for works with free domestic only shipping

- _schema.graphql
- src/data/exchange.graphql
- src/lib/stitching/exchange/__tests__/__snapshots__/schema.test.ts.snap
- src/schema/ecommerce/types/orders_sort_method_enum.ts
Exposes additional Order sorting options added in https://github.com/artsy/exchange/pull/229 as part of [SELL-1042](https://artsyproduct.atlassian.net/browse/SELL-1042).
> Expand OrderSortMethodEnum to sort over state_expires_at

- README.md
@orta mentioned these queries in https://github.com/artsy/graphql-workshop; I think they'd be useful in the setup instructions.
> Add some sample queries to the setup instructions

- _schema.graphql
- src/schema/__tests__/partner.test.js
- src/schema/home/home_page_hero_units.js
- src/schema/image/__tests__/index.test.js
- src/schema/image/index.js
- src/test/fixtures/exchange/mockxchange.js
Also cleaning up some unused variables to make lint happy.
This PR is a follow up on discussion here: https://github.com/artsy/reaction/pull/1467
> add default to aspect ratio for an image

- .eslintrc.json
- src/schema/sale/__tests__/index.test.js
- src/schema/sale/index.js
~Blocker: https://github.com/artsy/gravity/pull/12003~
Follow up to https://github.com/artsy/metaphysics/pull/1382#discussion_r234804254. Moved the filter out of MP and into Gravity so that connections and so on can maintain consistent pagination.
> [Sale] Add Gravity exclude param to saleArtworkLoader

- Dockerfile
- hokusai/production.yml
- hokusai/staging.yml
- scripts/run-goreplay.sh
As you all were in this thread: https://artsy.slack.com/archives/C2TQ4PT8R/p1543350165754200
Remove goreplay as we're not actively using it.  Will pull this boilerplate out into its own Dockerfile in https://github.com/artsy/docker-images
> remove goreplay

- package.json
#trivial 
Move `prepush` command out of `scripts` and into `husky`.
> [Toolchain] Move pre-push command to `husky` key

- _schema.graphql
- src/schema/artist/index.ts
Quick follow-up to https://github.com/artsy/metaphysics/pull/1413
#trivial
> [Artwork] Add missing `exclude` arg

- Dockerfile
Bumping to ensure we have the latest security patches.
> Upgrade node to v10.14.1 for security updates

- src/schema/ecommerce/query_helpers.ts
> Add respondsTo

- _schema.graphql
- src/schema/__tests__/fair.test.js
- src/schema/fair.ts
> Expose partners, artists, artworks, and partner show counts in Fair

- src/schema/partner.ts
We want to use these params for the 'Other works from partner' grid. #minor
> @damassi => Pass thru sort and for_sale param to artworks connection for a partner

- _schema.graphql
- src/schema/filter_artworks.ts
- Adds `offerable` to artwork filters
> Adds offerable to artwork filters

- Dockerfile
**Related:** https://github.com/artsy/force/pull/3235
This is to address the mysterious and periodic 504 issues we've been seeing in staging.
> [Server] Downgrade Node to 10.13.0

- _schema.graphql
- src/lib/stitching/kaws/stitching.ts
Worked with @mzikherman to figure out what was missing for https://github.com/artsy/reaction/pull/1744 and found this bit of paperwork to add.
> Add offerable to kaws stitched schema

- src/schema/ecommerce/order.ts
- src/schema/ecommerce/orders.ts
- src/test/fixtures/exchange/orders.json
This was missing and was causing the resolver to get an undefined.
> Add the version id to a couple places

- .circleci/deploy_event.sh
- hokusai/config.yml
> dd deploy events

- _schema.graphql
- src/schema/fair.ts
Implements [LD-99](https://artsyproduct.atlassian.net/browse/LD-99)
Exposes fair `about`, `links`, and `tickets_link` fields.
> feat: expose fair about, links, tickets_link fields

- src/schema/artwork_version.ts
> Use the right key name for artist ids

- _schema.graphql
- src/schema/fair.ts
Satisfies [this ticket.](url
https://artsyproduct.atlassian.net/browse/LD-124)
This adds a website field to FairOrganizer to match changes made in gravity with ticket [#LD-123](url
https://artsyproduct.atlassian.net/browse/LD-123).
> added website field to FairOrganizer schema in fair.ts

- _schema.graphql
- src/schema/sale/index.ts
This will be used to accomplish: https://artsyproduct.atlassian.net/browse/DISCO-456 on new artwork page.
> add is_benefit property to auction

- package.json
- yarn.lock
Part of https://artsyproduct.atlassian.net/browse/PLATFORM-1129
> [package] Update dd-trace client to latest.

- _schema.graphql
- src/schema/__tests__/ecommerce/add_initial_offer_to_order_mutation.test.ts
- src/schema/ecommerce/add_initial_offer_to_order_mutation.ts
- src/schema/ecommerce/buyer_counter_offer_mutation.ts
- src/schema/ecommerce/seller_counter_offer_mutation.ts
cc @ashkan18 is there currently a way to confirm this via tests?
I verified locally that these three mutations work!
> Send offer note in initial + counter mutations

- src/lib/__tests__/modifyOldEigenQueries.test.ts
- src/lib/modifyOldEigenQueries.ts
I knew something was bothering me with #1487 last night, but couldn't place it. This was it.
> Ensures eigen mutations are only re-written when the stitching config flag is on

- src/lib/__tests__/modifyOldEigenQueries.test.ts
- src/lib/modifyOldEigenQueries.ts
Ensures that the Eigen query modifiers aren't overreaching.
> Hotfix for the eigen query detection

- package.json
- yarn.lock
This reverts commit 5628353078127e122032b889cc79966a0e7edefb.
> Revert "[package] Update dd-trace client to latest."

- package.json
- patches/dd-trace+0.7.3.patch
- yarn.lock
Going to log out some details about this issue:
```
TypeError: Cannot convert object to primitive value
at String (<anonymous>)
at Object.keys.forEach.tag (/app/node_modules/dd-trace/src/format.js:63:27)
at Array.forEach (<anonymous>)
at extractTags (/app/node_modules/dd-trace/src/format.js:44:21)
at format (/app/node_modules/dd-trace/src/format.js:18:3)
at Array.map (<anonymous>)
at Writer.append (/app/node_modules/dd-trace/src/writer.js:25:45)
at Recorder.record (/app/node_modules/dd-trace/src/recorder.js:21:18)
at DatadogSpan._finish (/app/node_modules/dd-trace/src/opentracing/span.js:121:22)
at DatadogSpan.Span.finish (/app/node_modules/opentracing/lib/span.js:160:14)
at IncomingMessage.res.on (/app/node_modules/dd-trace/src/plugins/http/client.js:62:34)
at IncomingMessage.emit …
```
> Debug dd trace client issue

- dangerfile.ts
#1485 had an accidental `describe.only` left in the PR. On other repos, Eigen for example, we use Danger to prevent this from getting merged:
https://github.com/artsy/eigen/blob/328aa92f005734608545871f659601c6db6ec5a2/Dangerfile.swift#L18-L28
This PR ports that check to this repo.
> Adds Danger check for testing shortcuts

- patches/dd-trace+0.7.3.patch
As discussed here https://datadoghq.slack.com/archives/C3SH3KCQG/p1549567052332400?thread_ts=1549477262.317000&cid=C3SH3KCQG
> [dd-trace] Test a patch that should work around the type error.

- _schema.graphql
- src/data/kaws.graphql
- src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
Updates schema with new fields `price_guidance` and `show_on_editorial`, and query for `showOnEditorial`.
> Update Kaws schema

- _schema.graphql
- src/schema/location.ts
- Exposes `summary` to `Location` to be used for LD fair address
> Exposes summary to location

- src/schema/__tests__/show.test.js
- src/schema/show.ts
Fix fair booth slug routing (certain fair booths returning 404s) https://artsyproduct.atlassian.net/browse/LD-239
> Fixes fair booths being filtered out

- _schema.graphql
- src/schema/__tests__/fair.test.js
- src/schema/fair.ts
- This is dependent on https://github.com/artsy/gravity/pull/12158
> Adds _id to exhibitors grouped by name

- _schema.graphql
- src/schema/show.ts
And also and set default state to `current` so by default we only show current shows.
> Make sure we filter out online-only shows for nearbyShows

- _schema.graphql
- src/lib/loaders/loaders_without_authentication/gravity.ts
- src/schema/__tests__/city.test.ts
- src/schema/__tests__/fairs.test.js
- src/schema/city/index.ts
- src/schema/fair.ts
- src/schema/fairs.ts
- src/schema/home/__tests__/home_page_fairs_module.test.js
- src/schema/home/fetch.ts
- src/schema/home/home_page_fairs_module.ts
- src/schema/home/results.ts
Closes https://artsyproduct.atlassian.net/browse/LD-19
> [City] Make fairs field a connection.

- _schema.graphql
- src/lib/loaders/index.ts
- src/lib/loaders/loaders_without_authentication/gravity.ts
- src/schema/__tests__/city.test.ts
- src/schema/__tests__/fairs.test.js
- src/schema/artist/related.ts
- src/schema/artist/shows.ts
- src/schema/city/index.ts
- src/schema/collection.ts
- src/schema/fair.ts
- src/schema/fairs.ts
- src/schema/gene.ts
- src/schema/home/__tests__/home_page_fairs_module.test.js
- src/schema/home/fetch.ts
- src/schema/home/home_page_fairs_module.ts
- src/schema/home/results.ts
- src/schema/me/artwork_inquiries.ts
- src/schema/me/credit_cards.ts
- src/schema/me/followed_artists.ts
- src/schema/me/followed_artists_artworks_group.ts
- src/schema/me/followed_fairs.ts
- src/schema/me/followed_genes.ts
- src/schema/me/followed_shows.ts
- src/schema/partner.ts
- src/schema/partner_artist.ts
- src/schema/partner_show.ts
- src/schema/sale_artworks.ts
- src/schema/show.ts
Depends on #1527 being merged first. This PR is solely about c8ba2dea6bc80e6fc833cc10d6e6dfbc26810d84.
> Type headers and parse count header

- src/lib/__tests__/all.test.ts
- src/lib/all.ts
- src/lib/helpers.ts
- src/lib/loaders/api/loader_interface.ts
- src/schema/__tests__/city.test.ts
- src/schema/city/index.ts
- src/schema/fair.ts
- src/schema/partner_show.ts
- src/schema/sale/index.ts
- src/schema/sale_artworks.ts
- src/schema/show.ts
Part of https://artsyproduct.atlassian.net/browse/LD-284
> Load all city shows and fairs

- _schema.graphql
- src/schema/__tests__/fair.test.js
- src/schema/fair.ts
- Provides `exhibition_period` to fairs for formatted date range
> Adds exhibition_period to Fairs

- _schema.graphql
- src/data/kaws.graphql
- src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
Related to https://github.com/artsy/kaws/pull/76 and updates a schema change from kaws.
> update kaws schema to use randomizationSeed

- _schema.graphql
- src/lib/date.ts
- src/schema/partner_show_event.ts
- Need to add this to prevent date formatting in emission client
> Adds exhibition_period to partner_show_events

- .vscode/settings.json
- dangerfile.ts
- package.json
- yarn.lock
This is something we've agreed on for a while now, so might as well have a danger rule for it.
> [danger] Fail on snake_case additions.

- src/lib/sponsoredContent/data.json
This PR adds the copy from BMW's press release for Art Basel Hong Kong
[Links to LD-131](https://artsyproduct.atlassian.net/browse/LD-131)
> updated copy from BMW press release

- src/schema/artist/__tests__/insights.test.ts
- src/schema/artist/insights.ts
Update “Participated in a major biennial” to "Included in a major biennial"
branches in force and reaction
> Artist insights 2.0 - Update biennial badge label

- src/lib/sponsoredContent/data.json
- https://artsyproduct.atlassian.net/browse/LD-354
> LD-354 - Updates artGuideUrl to correct URL

- src/schema/__tests__/city.test.ts
- src/schema/city/cityDataSortedByDisplayPreference.json
- src/schema/city/index.ts
Part of https://artsyproduct.atlassian.net/browse/LD-335
> [City] Sort city data for consumption by Emission.

- src/lib/sponsoredContent/data.json
Copy update. [Links to LD-329](https://artsyproduct.atlassian.net/browse/LD-329)
> BMW art guide copy change for HK

- src/schema/sorts/partner_show_sorts.ts
Making it draft for now till Gravity part is fully supported.
> Switch PARTNER_ASC to use fully qualified name

- _schema.graphql
- src/schema/me/followed_shows.ts
Adds a new arg for https://github.com/artsy/gravity/pull/12218
The status is already there.
> Adds support for day threshold to the schema

- _schema.graphql
- src/schema/me/followed_shows.ts
We don't think this is needed, and isn't supported in gravity - let's not set people up to fail
> Uses an Int for dayThreshold and removes sort from followed shows

- src/lib/sponsoredContent/data.json
> Fix static data for sponsored shows

- .env.test
- _schema.graphql
- src/config.ts
- src/data/vortex.graphql
- src/lib/stitching/mergeSchemas.ts
- src/lib/stitching/vortex/link.ts
- src/lib/stitching/vortex/schema.ts
Update: ~~Blocked by https://github.com/artsy/vortex/pull/42~~
----
Stitches vortex's graphql schema to metaphysics, I just followed the steps, so hopefully this works.
> Vortex stitching

- .env.example
- _schema.graphql
- src/lib/loaders/searchLoader.ts
- src/schema/search/SearchEntity.ts
Depends on https://github.com/artsy/gravity/pull/12229
> @dblandin => Add institutions to be an entity type that can be searched for

- src/lib/sponsoredContent/data.json
https://artsyproduct.atlassian.net/browse/LD-500
A few deletions, and one change to the preview bricks.
#trivial
> Pre-launch updates to hard-coded sponsored shows

- _schema.graphql
- src/schema/searchableItem.ts
Pulls out the description included in the Elasticsearch result object.
> Add description attribute to SearchableItem type

- src/schema/search/SearchEntity.ts
> @mzikherman => [Autosuggest] Properly exclude shows from default entities

- src/lib/__tests__/date.test.ts
- src/lib/date.ts
- Shows ending month if different years but same month
> Shows month if different years but same month

- src/lib/sponsoredContent/data.json
A few more deletions per the sponsor's request
> More show changes from sponsor

- src/schema/searchableItem.ts
Add formatting for Article and Sale types. Fallback to the search result item's description, stripping all html tags.
> Update SearchableItem description

- src/schema/__tests__/fair.test.js
- src/schema/fair.ts
- `isActive` now shows past fairs
- https://artsyproduct.atlassian.net/browse/LD-526
> LD-526 - isActive now shows past Fairs

- _schema.graphql
- src/data/vortex.graphql
sample query:
```graphql
query {
partnerStats(partnerId: "4d8b92c44eb68a1b2c0004cb") {
uniqueVisitors
partnerId
artworksPublished {
count
time
samplingFrequency
}
}
}
```
returns
```json
{
"data": {
"partnerStats": {
"uniqueVisitors": 12,
"partnerId": "4d8b92c44eb68a1b2c0004cb",
"artworksPublished": [
{
"count": 3,
"time": "2019-03-14T04:00:00Z",
"samplingFrequency": "DAILY"
},
{
"count": 18,
"time": "2019-03-05T05:00:00Z",
"samplingFrequency": "DAILY"
}
]
}
}
}
```
> Update vortex schema

- docs/adding_a_new_graphql_microservice.md
Documentation for graphql micro-service authentication was missing.
> Add docs for graphql microservice authentication

- _schema.graphql
- src/schema/__tests__/fair.test.js
- src/schema/fair.ts
- Fixes fair show pagination
- https://artsyproduct.atlassian.net/browse/LD-538
> LD-538 - Fair shows pagination

- src/lib/stitching/vortex/__tests__/pricingContext.test.ts
- src/lib/stitching/vortex/stitching.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-964
> Make sure list price is present for pricing context

- src/lib/stitching/vortex/__tests__/pricingContext.test.ts
- src/lib/stitching/vortex/stitching.ts
Fixing https://sentry.io/organizations/artsynet/issues/956770079/?project=299973&query=is%3Aunresolved&statsPeriod=14d&utc=false
> Do proper category mapping for pricingContext

- _schema.graphql
- src/data/vortex.graphql
> Updates vortex schema to include new `ArtworksPublishedStats` query

- _schema.graphql
- src/lib/date.ts
- src/schema/__tests__/fair.test.js
- src/schema/fair.ts
- This is the first step in https://artsyproduct.atlassian.net/browse/LD-568 which will pull the Fair display dates out of Emission and into Metaphysics
> Adds formattedOpeningHours to Fairs

- .circleci/config.yml
AWS IAM credentials set via the "hokusai" circleci context
> update circleci job contexts #PLATFORM-1357

- src/lib/__tests__/date.test.ts
I missed the console warning yesterday.
> [test] Fix warnings about incorrect date format.

- _schema.graphql
- src/data/vortex.graphql
- src/lib/helpers.ts
- src/lib/loaders/loaders_without_authentication/vortex.ts
- src/lib/stitching/mergeSchemas.ts
- src/lib/stitching/vortex/__mocks__/link.ts
- src/lib/stitching/vortex/__tests__/topArtorks.test.ts
- src/lib/stitching/vortex/schema.ts
- src/lib/stitching/vortex/stitching.ts
- src/schema/partner.ts
Fixes [GALL-1592](https://artsyproduct.atlassian.net/browse/GALL-1592)
Similar to [exchange](https://github.com/artsy/metaphysics/blob/620752ae4e5daeb7fd0791e2fd8ff14559648477/src/lib/stitching/exchange/stitching.ts#L174-L191) stitches artwork data under topArtworks nodes.
Thanks @alloy for help with getting it to work.
~Sample query:~ outdated. see comments below 👇 
```graphql
query {
analyticsPartnerStats(partnerId: "4d8b92c44eb68a1b2c0004cb") {
topArtworks(period: FOUR_WEEKS, first: 2) {
edges {
node {
value
period
artwork {
id
title
imageUrl
artist {
name
}
}
}
}
}
}
}
```
returns:
```json
{
"data": {
"analyticsPartnerStats": {
"topArtworks": {
"edges": [
{
"node": {
"value": 1431,
"period": "FOUR_WEEKS",
"artwork": {
"id": "jean-michel-basquiat-in-italian",
"title": "In Italian", …
```
> Add stiched artwrok to topArtworks

- _schema.graphql
- src/data/vortex.graphql
- src/lib/stitching/vortex/__tests__/pricingContext.test.ts
- src/lib/stitching/vortex/stitching.ts
Follow up on https://github.com/artsy/vortex/pull/91
> Fix Vortex Enum Typos

- _schema.graphql
- src/lib/stitching/vortex/__mocks__/link.ts
- src/lib/stitching/vortex/__tests__/pricingContext.test.ts
- src/lib/stitching/vortex/stitching.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-1032
Follow up on artsy/vortex#89
add `appliedFilterDisplay` which will use newly returned `appliedFilters` field from Vortex to generate our filter display string.
> Add appliedFiltersDisplay

- src/lib/stitching/vortex/stitching.ts
Fixes https://sentry.io/organizations/artsynet/issues/992134226/?project=299973&query=is%3Aunresolved
cc: @sweir27
> Fix case when there is no vortex context

- package.json
- yarn.lock
> Update moment timezone for smaller payload size

- _schema.graphql
- src/schema/artwork/__tests__/artwork.test.js
- src/schema/artwork/index.ts
- src/schema/edition_set.ts
Added sizeScore to both Artwork and EditionSet and added tests for both.
This is necessary for the Price in context feature.
WIP because it depends on gravity
> WIP: Metaphysics exposes size_score in its artwork schema

- src/data/vortex.graphql
- src/lib/stitching/vortex/__tests__/pricingContext.test.ts
- src/lib/stitching/vortex/stitching.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-1021
> Use sizeScore when fetching histogram

- renovate.json
Adds renovate to help us keep our deps up to date.
> Add renovate to metaphysics

- _schema.graphql
- src/schema/artist/related.ts
Pretty straightforward, just adds a param and passes it thru for https://github.com/artsy/gravity/pull/12322
#skip_camel
> @ashfurrow => [Related Artists] Add param to filter by a min. for sale artwork count

- src/data/vortex.graphql
> Sync vortex schema

- .circleci/config.yml
- README.md
- _schema.graphql
Uses the new hokusai orb to move metaphysics over to a PR based release process.
> Move metaphysics to a PR based release process

- .circleci/config.yml
- README.md
- _schema.graphql
- src/data/vortex.graphql
> Deploy updated vortex schema

- _schema.graphql
- src/schema/home/params.ts
- src/schema/index_v2.ts
- src/schema/object_identification.ts
- src/schema/sale_artwork.ts
Added `HomePageModuleParams` to the list of potentially nullable IDs.
> Fix HomePageModuleParams nullability change crashing eigen

- _schema.graphql
- src/data/kaws.graphql
- src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
Related to: https://github.com/artsy/kaws/pull/97
This updates the kaws schema in metaphysics.
> [Related Collections] sync kaws schema

- _schema.graphql
- _schemaV2.graphql
- src/data/vortex.graphql
https://artsyproduct.atlassian.net/browse/GALL-1503
This also updated v2 schema and want to make sure it's ok. cc @zephraph @alloy.
Closed the [previous one](https://github.com/artsy/metaphysics/pull/1734) and PRed from upstream branch.
> Update schema for order count from Vortex (GALL-1503)

- _schema.graphql
- _schemaV2.graphql
- src/data/vortex.graphql
https://artsyproduct.atlassian.net/browse/GALL-1673
Following https://github.com/artsy/vortex/pull/146, this updates the MP schema with the changes.
> Update Vortex schema (GALL-1673)

- index.js
- package.json
- src/index.ts
- yarn.lock
This depends on an updated version of https://github.com/artsy/artsy-xapp/pull/7
> @eessex => [XAPP] Correctly set xapp token when refreshed

- _schemaV2.graphql
- package.json
- patches/graphql-tools+4.0.4.patch
- src/lib/__tests__/cache.test.ts
- src/lib/cache.ts
- src/lib/loaders/loaders_without_authentication/gemini.ts
- src/lib/stitching/vortex/__tests__/pricingContext.test.ts
- src/schema/sale/__tests__/index.test.js
- src/schema/v2/RenameArguments.ts
- src/schema/v2/RenameIDFields.ts
- src/schema/v2/__tests__/v2.test.ts
- src/schema/v2/index.ts
- src/test/helper.js
Closes https://artsyproduct.atlassian.net/browse/PLATFORM-1441
> [v2] Rename node __id arg to id

- hokusai/production.yml
- hokusai/staging.yml
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1523
> Use named ports

- _schemaV2.graphql
- src/schema/v2/index.ts
> [v2] Don't drop PartnerShow just yet, wait till we drop deprecated fields

- _schema.graphql
- _schemaV2.graphql
- src/data/vortex.graphql
To get missing inquiry time series.
> Update vortex schema again

- _schema.graphql
- _schemaV2.graphql
- Updates schema with new fields added in https://github.com/artsy/metaphysics/pull/1788
> Updates schema 

- _schema.graphql
- _schemaV2.graphql
- src/data/vortex.graphql
vortex PR: https://github.com/artsy/vortex/pull/161
> Update schema for grouped stats

- _schema.graphql
- _schemaV2.graphql
- src/data/kaws.graphql
- src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
New optional string property on collections, used when the collection shows up in a hub's rail.
> added thumbnail to collection schema

- _schema.graphql
- _schemaV2.graphql
- src/data/vortex.graphql
for grouped stats device, referral and landing page metrics
> Vortex schema update

- _schema.graphql
- _schemaV2.graphql
Follow up to https://github.com/artsy/metaphysics/pull/1834
> Actually update MP schema

- _schema.graphql
- _schemaV2.graphql
- src/data/kaws.graphql
- src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
Related to: https://github.com/artsy/kaws/pull/123
> Updates kaws schema

- _schema.graphql
- _schemaV2.graphql
- src/lib/__tests__/deprecate.test.ts
- src/lib/deprecation.ts
- src/schema/artist/index.ts
- src/schema/artist/shows.ts
- src/schema/artwork/index.ts
- src/schema/ecommerce/types/order.ts
- src/schema/featured_link.ts
- src/schema/filter_artworks.ts
- src/schema/filter_sale_artworks.ts
- src/schema/home/home_page_hero_units.ts
- src/schema/me/collector_profile.ts
- src/schema/me/consignments/create_submission_mutation.ts
- src/schema/me/consignments/submission.ts
- src/schema/me/consignments/update_submission_mutation.ts
- src/schema/me/conversation/index.ts
- src/schema/me/conversation/message.ts
- src/schema/me/notifications.ts
- src/schema/me/suggested_artists_args.ts
- src/schema/object_identification.ts
- src/schema/partner.ts
- src/schema/partner_artist.ts
- src/schema/partner_show.ts
- src/schema/schema.ts
- src/schema/sellable.ts
- src/schema/show.ts
For https://github.com/artsy/codemods/pull/2
> [v2] Preparations to make codemodable

- _schema.graphql
- _schemaV2.graphql
- src/lib/__tests__/deprecate.test.ts
- src/lib/deprecation.ts
- src/schema/artist/index.ts
- src/schema/artist/shows.ts
- src/schema/artwork/index.ts
- src/schema/ecommerce/types/order.ts
- src/schema/featured_link.ts
- src/schema/filter_artworks.ts
- src/schema/filter_sale_artworks.ts
- src/schema/home/home_page_hero_units.ts
- src/schema/me/collector_profile.ts
- src/schema/me/consignments/create_submission_mutation.ts
- src/schema/me/consignments/submission.ts
- src/schema/me/consignments/update_submission_mutation.ts
- src/schema/me/conversation/index.ts
- src/schema/me/conversation/message.ts
- src/schema/me/notifications.ts
- src/schema/me/suggested_artists_args.ts
- src/schema/object_identification.ts
- src/schema/partner.ts
- src/schema/partner_artist.ts
- src/schema/partner_show.ts
- src/schema/schema.ts
- src/schema/sellable.ts
- src/schema/show.ts
Reverts artsy/metaphysics#1838. 
I messed up the commit (squashed instead of merge commit). 
I'm reverting so I can reapply those commits.
> Revert "[v2] Preparations to make codemodable"

- _schema.graphql
- _schemaV2.graphql
- src/lib/__tests__/deprecate.test.ts
- src/lib/deprecation.ts
- src/schema/artist/index.ts
- src/schema/artist/shows.ts
- src/schema/artwork/index.ts
- src/schema/ecommerce/types/order.ts
- src/schema/featured_link.ts
- src/schema/filter_artworks.ts
- src/schema/filter_sale_artworks.ts
- src/schema/home/home_page_hero_units.ts
- src/schema/me/collector_profile.ts
- src/schema/me/consignments/create_submission_mutation.ts
- src/schema/me/consignments/submission.ts
- src/schema/me/consignments/update_submission_mutation.ts
- src/schema/me/conversation/index.ts
- src/schema/me/conversation/message.ts
- src/schema/me/notifications.ts
- src/schema/me/suggested_artists_args.ts
- src/schema/object_identification.ts
- src/schema/partner.ts
- src/schema/partner_artist.ts
- src/schema/partner_show.ts
- src/schema/schema.ts
- src/schema/sellable.ts
- src/schema/show.ts
This is the reapplication of #1838 that I messed up by accidentally squashing. >_>
GitHub could not automatically pick a button for me, that'd be nice.
> Make codemodable 2

- src/schema/v1/__tests__/filter_artworks.test.js
- src/schema/v1/test/utils.ts
- src/schema/v2/__tests__/filter_artworks.test.js
- src/schema/v2/test/utils.ts
h/t @joeyAghion who suggested adding a spec for this.
> @mzikherman => [FilterArtworks] Test for Emission-specific query parsing

- src/schema/v2/filter_artworks.ts
- src/schema/v2/gene.ts
- src/schema/v2/home/context.ts
Fixes
* https://artsyproduct.atlassian.net/browse/PLATFORM-1665
* https://artsyproduct.atlassian.net/browse/PLATFORM-1666
> [v2] A few fixes for issues surfaced in Emission

- _schema.graphql
- _schemaV2.graphql
- src/data/exchange.graphql
this updates the schema with changes in https://github.com/artsy/exchange/pull/455
> Update with latest Exchange schema

- _schema.graphql
- _schemaV2.graphql
- src/data/exchange.graphql
catch up with latest exchange changes
> [Deploy] Update with latest Exchange schema (#1863)

- _schemaV2.graphql
- src/schema/v2/__tests__/sale_artworks.test.js
- src/schema/v2/aggregations/aggregation_count.ts
- src/schema/v2/gene.ts
Part of: https://artsyproduct.atlassian.net/browse/PLATFORM-1683
As [discussed in Slack](https://artsy.slack.com/archives/C1HH3KNJG/p1566396382002700).
> [HOLD] [v2] Cleanup AggregationCount field naming.

- _schema.graphql
- _schemaV2.graphql
- src/schema/v1/artwork/index.ts
- src/schema/v2/artwork/index.ts
- src/types/gravity/artworkResponse.d.ts
- Metaphysics side to expose whether tax is included in the price of an artwork
- Gravity side https://github.com/artsy/gravity/pull/12518
> Adds priceIncludesTax to Artwork

- src/schema/v2/sale_artworks.ts
Fixes https://artsyproduct.atlassian.net/browse/PLATFORM-1710
This field’s args could do with some test coverage, but not going to do so right now 🤷‍♂
> [v2] Fix sale artworks field passing incorrectly cased params to Gravity

- _schemaV2.graphql
- src/schema/v2/__tests__/article.test.js
- src/schema/v2/__tests__/articles.test.js
- src/schema/v2/__tests__/artists.test.js
- src/schema/v2/__tests__/causality_jwt.test.js
- src/schema/v2/__tests__/collection.test.js
- src/schema/v2/__tests__/credit_card.test.ts
- src/schema/v2/__tests__/filterArtworksConnection.test.js
- src/schema/v2/__tests__/gene_families.test.js
- src/schema/v2/__tests__/genes.test.js
- src/schema/v2/__tests__/object_identification.test.js
- src/schema/v2/__tests__/ordered_set.test.js
- src/schema/v2/__tests__/ordered_sets.test.js
- src/schema/v2/__tests__/partner.test.js
- src/schema/v2/__tests__/partners.test.js
- src/schema/v2/__tests__/profile.test.js
- src/schema/v2/__tests__/suggested_genes.test.js
- src/schema/v2/__tests__/user.test.js
- src/schema/v2/__tests__/users.test.js
- src/schema/v2/artists/__tests__/popular.test.js
- src/schema/v2/artists/__tests__/trending.test.js
- src/schema/v2/artwork_version.ts
- src/schema/v2/match/__tests__/gene.test.js
- src/schema/v2/schema.ts
- src/schema/v2/system/__tests__/time.test.js
Part of https://artsyproduct.atlassian.net/browse/PLATFORM-1734
These are the ones that don’t require any changes in Emission.
> [v2] Disable all root fields unused by Emission.

- src/data/exchange.graphql
Update to latest Exchange schema which includes new optional param for fix failed payment intent.
> Update to latest Exchange schema

- _schema.graphql
- _schemaV2.graphql
Follow up on https://github.com/artsy/metaphysics/pull/1929, new laptop didn't automatically run `yarn dump:local` for some reason!
thanks @zephraph
> Update MP schema with latest Exchange change

- _schemaV2.graphql
- patches/@types/graphql-relay+0.4.9.patch
- patches/graphql-relay+0.5.4.patch
- src/schema/v2/__tests__/sale_artwork.test.js
- src/schema/v2/__tests__/sale_artwork_max_bid_env.test.js
- src/schema/v2/__tests__/sale_artworks.test.js
- src/schema/v2/artwork/index.ts
- src/schema/v2/match/__tests__/artist.test.js
- src/schema/v2/me/__tests__/sale_registrations.test.js
- src/schema/v2/me/followed_fairs.ts
- src/schema/v2/me/followed_shows.ts
- src/schema/v2/me/index.ts
- src/schema/v2/me/sale_registrations.ts
- src/schema/v2/object_identification.ts
- src/schema/v2/partner_artist.ts
- src/schema/v2/sale_artwork.ts
- src/schema/v2/sale_artworks.ts
- src/schema/v2/sales.ts
- src/schema/v2/schema.ts
Part of https://artsyproduct.atlassian.net/browse/PLATFORM-1734
These changes need updates in Emission: https://github.com/artsy/emission/pull/1831
> [v2] Remove more root fields

- src/lib/loaders/loaders_without_authentication/gravity.ts
- src/schema/v2/sales.ts
The loader used here should resolve headers, so added a new one since we're using batching for sales currently (which doesn't support resolving headers).
> @ds300 => [V2 Sales] Use  a loader that resolves headers for the connection

- .circleci/config.yml
- package.json
- scripts/schema-drift.ts
This adds a script to help ensure we're considering what files need to be changed in v1 and v2.
> Automatically detect and alert when v1 and v2 file changes drift

- _schema.graphql
- _schemaV2.graphql
- src/schema/v1/partner.ts
- src/schema/v2/partner.ts
Fixes [PURCHASE-1574](https://artsyproduct.atlassian.net/browse/PURCHASE-1574)
Is there a test strategy for these fields? I just found specs for `website` [field](https://github.com/artsy/metaphysics/blob/master/src/schema/v1/__tests__/partner.test.js#L33) and not anything else
> Adds isVerifiedSeller to Partner

- _schema.graphql
- _schemaV2.graphql
- src/schema/v1/artwork/__tests__/artwork.test.js
- src/schema/v1/artwork/index.ts
- src/schema/v2/artwork/__tests__/artwork.test.js
- src/schema/v2/artwork/index.ts
discussion about adding this field in addition to `certificateOfAuthenticity`:[here](https://github.com/artsy/reaction/pull/2896/files#r334499431)
>  Add `hasCertificateOfAuthenticity`

- src/index.ts
> @zephraph => [Boot] Remove unneeded log line

- _schema.graphql
- _schemaV2.graphql
- src/data/kaws.graphql
- src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
Address: [GROW-1597](https://artsyproduct.atlassian.net/browse/GROW-1597)
We added `featuredArtistExclusionIds` to the Collection model. This PR updates the kaws schema to reflect that change.
> [GROW-1597] update kaws schema

- _schemaV2.graphql
- src/schema/v2/schema.ts
- Adds `Partner` as a root field, needed for Emission
> Adds Partner as root field

- src/lib/stitching/vortex/stitching.ts
- src/schema/v1/artwork/__tests__/artwork.test.js
- src/schema/v2/artwork/__tests__/artwork.test.js
Somehow I fudged on #2015 and merged some failing tests. 
Not sure how I missed that. This should fix them though.
> Rename Price fields in ListPrice to be Money

- src/lib/sponsoredContent/data.json
Addresses: [GROW-1621](https://artsyproduct.atlassian.net/browse/GROW-1621)
BMW updated the URL  for “Get the BMW Art Guide” without redirecting to a new URL so the page now displays the wrong content. This PR updates the hardcode URL value within metaphysics.
> [GROW-1621] update the Get the BMW Art Guide URL in city guide

- _schemaV2.graphql
- src/schema/v2/__tests__/user.test.ts
- src/schema/v2/artwork/index.ts
- src/schema/v2/bidder.ts
- src/schema/v2/fields/pagination.ts
- src/schema/v2/filterArtworksConnection.ts
- src/schema/v2/sale_artworks.ts
- src/schema/v2/schema.ts
- src/schema/v2/user.ts
First one that feels comfortable can take this PR and merge 👍 
cc @mzikherman
> [v2] Add PageCursors to ArtworkConnectionInterface

- src/schema/v2/artist/shows.ts
Working on the artist page, realized that the CV tab was showing incorrect info.
> @alloy => [v2] Convert camel case args to snake case for artist shows

- src/schema/v2/filterArtworksConnection.ts
This is present in the [v1 version](https://github.com/artsy/metaphysics/blob/4e2eb62d14de4b9f86426d6d912e1a15da32461b/src/schema/v1/filter_artworks.ts#L377).
> @mzikherman => [v2] Allow page to be specified by client

- _schemaV2.graphql
- src/schema/v2/filterArtworksConnection.ts
Forgot to update this field, used by gene/tag pages.
> @alloy => [v2] Some tweaks to filter schema for gene pagination

- src/schema/v2/filterArtworksConnection.ts
Little self-merge, got too happy with the snake and camel casing!
> @mzikherman => [v2] Correct tag and gene facet for filter artworks

- src/schema/v2/__tests__/partner.test.js
- src/schema/v2/partner.ts
- Adds `totalCount` to `Partner.locationsConnection`
> Adds totalCount to locationsConnection

- .circleci/config.yml
- .gitignore
- Dockerfile
- package.json
- Adds default settings for code coverage on Jest runs
- Adds codecov orb and upload report post-step to Circle test runs
> Add code coverage and codecov uploads

- src/data/kaws.graphql
- src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
adds `descriptionMarkdown` and `hasDescriptionMarkdown` to kaws schema.
> new schema from kaws

- _schema.graphql
- _schemaV2.graphql
- src/data/kaws.graphql
- src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
Follow up to #2119. 
https://artsyproduct.atlassian.net/browse/FX-1732
> Remove hasMarkdownDescription boolean from Marketing Collection schema

- .circleci/config.yml
- peril/compareReactionSchema.ts
Will enable in peril-settings.
> @mzikherman => Move schema check into Peril directory

- peril/compareReactionSchema.ts
I think this should work! We derive the path to the file in question based on the PR details.
> @mzikherman => [Peril] Tweak schema check to infer URL to PR schema

- peril/compareReactionSchema.ts
> @mzikherman => [Peril] Tweak output of schema warning

- _schemaV2.graphql
- src/schema/v2/artist/index.ts
Once https://github.com/artsy/diffusion/pull/185 is merged and deployed, this will catch up with that change.
> Switch organization to be an array

- _schema.graphql
- _schemaV2.graphql
- src/data/kaws.graphql
- src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
> FX-1808: Update KAWS schema to include isDepartment

- src/lib/sponsoredContent/data.json
https://artsyproduct.atlassian.net/browse/FX-1791
This was an expected update to the content added in #2173
> [FX-1791] Update a sponsored content url in City Guide

- _schemaV2.graphql
- src/lib/loaders/loaders_with_authentication/gravity.ts
- src/schema/v2/me/__tests__/identityverification.test.ts
- src/schema/v2/me/identity_verification.ts
- src/schema/v2/me/index.ts
This pr adds an identity verification query by id under the `me` type. I copied the date type's implementation from another file and removed some l8n logic from what i copied - see a4e21e0. Otherwise I think this is good to go. Thanks to @sweir27 for the pair on testing.
> Expose identity verifications

- src/schema/v2/__tests__/auction_results.test.js
- src/schema/v2/artist/index.ts
Reverts artsy/metaphysics#2195
Problem is solved in diffusion database. We no longer need this patch.
cc: @sepans
> Revert "Remove auction results for now"

- scripts/dump-remote-schema.ts
- src/data/convection.graphql
Updates the URL so that we can start developing against configurable endpoints (like localhost).
> [Convection] Make API endpoint configurable by ENV

- _schema.graphql
- _schemaV2.graphql
- src/schema/v1/artwork/__tests__/artwork.test.js
- src/schema/v1/artwork/index.ts
- src/schema/v2/artwork/__tests__/artwork.test.js
- src/schema/v2/artwork/index.ts
Thanks @mzikherman for flagging this!
Revert of https://github.com/artsy/metaphysics/pull/2201 here. And moving the new field to v2
> Reverting changes in v1 in favor of moving them to v2

- _schemaV2.graphql
- src/schema/v2/artwork/__tests__/artwork.test.js
- src/schema/v2/artwork/index.ts
- src/schema/v2/sale/__tests__/index.test.js
- src/schema/v2/sale/index.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-916
> Metaphysics developer can see whether a sale should show a lot condition report

- _schema.graphql
- _schemaV2.graphql
- src/data/convection.graphql
Synching schema, we just added a new `created_at` field: https://github.com/artsy/convection/pull/510
> Sync Convection schema

- src/data/convection.graphql
This PR incorporates the image urls exposed over on https://github.com/artsy/convection/pull/515.
> Update convection schema

- src/data/convection.graphql
Another, much smaller update to the convection schema filtering through the stack.
> Update convection schema again

- _schemaV2.graphql
- src/schema/v2/me/__tests__/index.test.js
- src/schema/v2/me/index.ts
Completes https://artsyproduct.atlassian.net/browse/AUCT-962
The related Gravity API change is already in production.
> [AUCT-962] Add identityVerified to me object

- _schemaV2.graphql
- src/schema/v2/sale/__tests__/index.test.js
- src/schema/v2/sale/index.ts
We forgot to add this field to `Sale` as part of https://github.com/artsy/metaphysics/pull/2260.
> Add requireIdentityVerification field to Sale

- _schema.graphql
- _schemaV2.graphql
- src/data/gravity.graphql
Following up on https://github.com/artsy/metaphysics/pull/2292 - I forgot to update MP's copy of Gravity's schema!
> Update Gravity schema

- src/schema/v2/home/title.ts
https://artsyproduct.atlassian.net/browse/MX-276
Copy tweaks for home modules.
> [MX-276] - Copy updates for eigen home page

- src/schema/v2/home/__tests__/home_page_artwork_module.test.js
- src/schema/v2/home/title.ts
A couple missed casing changes for home rails Sam called out.
https://artsyproduct.atlassian.net/browse/MX-281
> [MX-281] - Missed homepage casing updates #trivial

- _schema.graphql
- _schemaV2.graphql
- src/data/gravity.graphql
- src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
Followup from https://github.com/artsy/gravity/pull/13021 - shouldn't be merged till that one is resolved!
> Add slug to viewing rooms types + make less fields nullable

- _schemaV2.graphql
- src/lib/loaders/loaders_without_authentication/gravity.ts
- src/schema/v2/Feature/Feature.ts
- src/schema/v2/Feature/FeatureImageType.ts
- src/schema/v2/Feature/FeatureImageVersionEnum.ts
- src/schema/v2/Feature/FeatureType.ts
- src/schema/v2/Feature/index.ts
- src/schema/v2/fields/markdown.ts
- src/schema/v2/image/cropped.ts
- src/schema/v2/image/proxies/embedly.ts
- src/schema/v2/image/proxies/gemini.ts
- src/schema/v2/image/proxies/index.ts
- src/schema/v2/image/resized.ts
- src/schema/v2/schema.ts
```gql
{
feature(id: "alserkal-art-week") {
name
isActive
description(format: HTML)
image {
width
height
url(version: WIDE)
}
}
}
```
```json
{
"data": {
"feature": {
"name": "Alserkal Art Week",
"isActive": true,
"description": "<p>Alserkal Art Week Online</p>\n<p>Discover new exhibitions by Alserkal Avenue Galleries</p>\n",
"image": {
"width": 3240,
"height": 2160,
"url": "https://d32dm0rphc51dk.cloudfront.net/wsfiG9lAGOzs0Rey0felsQ/wide.jpg"
}
}
},
"requests": {
"gravity": {
"requests": {
"feature/alserkal-art-week": {
"time": "0s 148.453ms",
"cache": false,
"length": "N/A"
}
}
}
},
"requestID": "5b64a810-913c-11ea-a822-9d8c9bdc0114"
}
}
```
> Feature Type

- _schemaV2.graphql
- src/schema/v2/Feature/FeatureType.ts
- src/schema/v2/item.ts
- src/schema/v2/ordered_set.ts
- src/types/runtime/gravity/OrderedItem.ts
```gql
{
feature(id: "alserkal-art-week") {
name
setsConnection(first: 10) {
totalCount
edges {
node {
__typename
id
name
orderedItemsConnection(first: 10) {
totalCount
edges {
node {
... on FeaturedLink {
title
image {
url
}
}
}
}
}
}
}
}
}
}
```
```json
{
"data": {
"feature": {
"name": "Alserkal Art Week",
"setsConnection": {
"totalCount": 2,
"edges": [
{
"node": {
"__typename": "OrderedSet",
"id": "T3JkZXJlZFNldDo1ZTZmNWVlMmM1MmE1OTAwMTExMTEyMWY=",
"name": "Latest News",
"orderedItemsConnection": {
"totalCount": 1,
"edges": [
{
"node": {
"title": "Upcoming Exhibitions at Alserkal Avenue",
"image": {
"url": "https://d32dm0rphc51dk.cloudfront.net/_SzbXBMwj9JIj0QFspYcZQ/large_rectangle.jpg"
}
}
}
]
}
}
},
{
"node": {
"__typename": "OrderedSet",
"id": …
```
> Exposes union type item connection; deprecates existing

- src/lib/stitching/gravity/__tests__/stitching.test.ts
- src/lib/stitching/gravity/stitching.ts
Update to https://github.com/artsy/metaphysics/pull/2382, based on comments. 
Thanks for looking into this @starsirius!
> [ViewingRoom] Updates formattedTimeAt logic

- scripts/push-schema-changes.js
Reverts artsy/metaphysics#2396
This caused build failures so I'm going to revert to avoid confusing other folks until we have a chance to resolve the issue. Looks like yarn's engines check is failing, I should have anticipated that, my bad.
> Revert "Update relay types when updating Eigen's copy of MP schema"

- _schema.graphql
- _schemaV2.graphql
- src/data/gravity.graphql
- src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
Following Gravity changes: https://github.com/artsy/gravity/pull/13071
> Make optional fields on viewing room nullable in graphql type

- scripts/push-schema-changes.js
self-merging this trivial fix to the CI script.
> fix cwd in push-schema-changes

- src/schema/v2/me/__tests__/credit_cards.test.ts
- src/schema/v2/me/__tests__/index.test.js
- src/schema/v2/me/__tests__/index.test.ts
In preparation for [AUCT-997](https://artsyproduct.atlassian.net/browse/AUCT-997), there were some quick TS wins in the specs related to `meCreditCardsLoader `
> meCreditCardsLoader test type cleanup

- src/schema/v2/artist/targetSupply/index.ts
Adds a new `size` arg to our `microfunnel.artworks` list:
```graphql
{
artist(id: "alex-katz") {
targetSupply {
microfunnel {
artworks(size: 2) {
realizedPrice
}
}
}
}
}
```
```json
{
"data": {
"artist": {
"targetSupply": {
"microfunnel": {
"artworks": [
{
"realizedPrice": "$5,000"
},
{
"realizedPrice": "$8,500"
}
]
}
}
}
}
}
```
> [Microfunnel] Add size prop to artworks

- .babelrc
- _schemaV2.graphql
- package.json
- yarn.lock
Adds [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) and nullish coalescing. Surprised this wasn't already here!
> [Toolchain] Add optional chaining

- _schema.graphql
- _schemaV2.graphql
- src/schema/v1/index.ts
- src/schema/v2/index.ts
This gives us better sorting for our schema, prompted by [this issue](https://github.com/graphql/graphql-js/issues/2036#issuecomment-520613892).
> Sort schema

- scripts/push-schema-changes.js
Now that reaction is retired, update Force when the schema changes.
> [Toolchain] Push schema changes to force

- _schema.graphql
- _schemaV2.graphql
- src/data/convection.graphql
Addresses: [CSGN-140](https://artsyproduct.atlassian.net/browse/CSGN-140)
Blocked by https://github.com/artsy/convection/pull/663
This copies the convection graphql schema into metaphysics to make it accessible to volt.
> [CSGN-140] update convection graphql schema with new saleLocation property

- _schemaV2.graphql
- src/schema/v2/me/__tests__/index.test.ts
- src/schema/v2/me/index.ts
Blocked by deployment of https://github.com/artsy/gravity/pull/13103
* See https://github.com/artsy/gravity/pull/13103 for more context
* Includes some prettier diff, likely made unnecessary from
https://github.com/artsy/metaphysics/pull/2429, but don't want to
create needless work dependencies here!
Jira: https://artsyproduct.atlassian.net/browse/AUCT-1013
> Proxy `Me.can_request_email_confirmation` to Gravity

- src/lib/loaders/__tests__/request_id.test.js
- src/lib/loaders/__tests__/user_agent.test.js
- src/lib/loaders/loaders_with_authentication/gravity.ts
https://artsyproduct.atlassian.net/browse/AUCT-1031 🔒 
All of the pages mentioned in the ticket use this one loader.
> set size for me/lotStandings to 100

- _schema.graphql
- _schemaV2.graphql
- src/data/convection.graphql
Updates convections schema with a new `userAgent` prop.
> [Convection] Update schema stitching

- _schema.graphql
- _schemaV2.graphql
- src/data/convection.graphql
Depends on https://github.com/artsy/convection/pull/682
> [Convection] Sync schema

- Dockerfile
`hokusai build` was failing waiting for confirmation from apt-get install... not sure how this was working without it?
> add -y to apt-get install

- _schemaV2.graphql
- src/schema/v2/me/__tests__/__snapshots__/update_me_mutation.test.js.snap
- src/schema/v2/me/__tests__/update_me_mutation.test.js
- src/schema/v2/me/update_me_mutation.ts
Added `me`  in the response of updateMyProfileMutation.
> Added Me to updateMyProfileMutation

- _schemaV2.graphql
- src/schema/v2/me/__tests__/index.test.ts
- src/schema/v2/me/index.ts
Added hasPassword to me
We need to hide the change password option from frontend.
> Add hasPassword to me query

- .circleci/config.yml
- .gitignore
- Dockerfile
- package.json
- yarn.lock
Use node v12
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-2287
> Upgrade Node to v12

- hokusai/config.yml
Hoping to fix post-deploy issues seen on staging: https://circleci.com/gh/artsy/metaphysics/10085
Related thread: https://artsy.slack.com/archives/CP9P4KR35/p1592934718274700
> Update hokusai required version

- _schema.graphql
- _schemaV2.graphql
- src/data/gravity.graphql
- src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
> GALL-2935 Add featured to viewing room query

- src/lib/stitching/gravity/__tests__/stitching.test.ts
- src/lib/stitching/gravity/stitching.ts
> @anandaroop => [ArtistSeries] Fallback to a representative artwork if an image is not set

- _schema.graphql
- _schemaV2.graphql
- src/lib/stitching/gravity/stitching.ts
Just reopening this one from the local branch. Wanted to delete unused inport.
> Add viewing room connection to viewer

- _schema.graphql
- _schemaV2.graphql
- src/data/gravity.graphql
- src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
> @mzikherman => [Schema] Update from Gravity

- _schema.graphql
- _schemaV2.graphql
- src/data/gravity.graphql
- src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
Related Gravity ticket: https://github.com/artsy/gravity/pull/13319
[Jira ticket](https://artsyproduct.atlassian.net/browse/GALL-3097)
> Add caption to VR subsection update mutation [GALL-3097]

- _schema.graphql
- _schemaV2.graphql
- src/data/convection.graphql
Sync schema from https://github.com/artsy/convection/pull/737 changes.
> [Convection] Sync graphql schema

- _schemaV2.graphql
- src/lib/helpers.ts
- src/schema/v2/Feature/FeatureMeta.ts
- src/schema/v2/Feature/FeatureType.ts
Re: [FX-2124](https://artsyproduct.atlassian.net/browse/FX-2124)
> [FX-2124] Exposes meta fields on Features
