artsy/metaphysics

src/lib/loaders/loaders_with_authentication/gravity.ts

This reverts the one irrelevant change from https://github.com/artsy/metaphysics/pull/4854
I'm assuming this didn't actually intend to be committed but in the future if one ever updates loaders to return headers, you need to find every call site and update it accordingly.

fix: reverts profile loaders change

---

_schemaV2.graphql
src/lib/stitching/exchange/__tests__/stitching.test.ts
src/lib/stitching/exchange/v2/stitching.ts
src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/me/index.ts
src/schema/v2/schema.ts

**Work-in-progress**, relating to https://artsyproduct.atlassian.net/browse/PX-5448: we'd like to retire partners' usage of user APIs and instead source any buyer attributes from the "collector profile" APIs instead.
Thanks for the pair. This _almost_ works. For example, the following query successfully resolves a `buyerProfile`:
```graphql
query {
commerceOrder(code:"690747315") {
buyer {
... on CommerceUser {
id
}
}
buyerProfile {
name
email
}
}
}
```
However, if the `buyer` is not included in the query, the whole `commerceOrder` ends up being `null`. Feedback or pushes welcome.

feat: expose buyerProfile properties directly on orders, rather than via users

---

_schemaV2.graphql
src/schema/v2/conversation/__tests__/message.test.js
src/schema/v2/conversation/index.ts

[NX-3485]
We need this flag to control whether include delivery pending is passed or not (for example: in case a partner is requesting conversations this flag must be used so the messages that were sent by them but haven't yet been delivered will still be displayed for them)
Keep in mind that the changes regarding access on the partner-side or on the collector-side must be handled on Impulse.
We can move forward with this PR isolated from that one.
The changes here are not breaking changes, it just means that when performing the following query:
```
{
conversationsConnection(	
type: PARTNER,
partnerId: "5f80bfefe8d808000ea212c1",
first: 3
) {
edges {
node {
internalID
messagesConnection(first: 5, includeDeliveryPending: true) {
edges {
node {
body
}
}
totalCount
}
}
}
}
}
```
Impulse will …

chore(NX-3485): Enable delivery pending flag to be passed as an arg to messages

---

src/lib/__tests__/helpers.test.ts
src/lib/helpers.ts
src/schema/v2/artworksForUser/helpers.ts
src/schema/v2/me/__tests__/artistRecommendations.test.ts
src/schema/v2/me/artistRecommendations.ts
src/schema/v2/me/artworkRecommendations.ts
src/schema/v2/notifications/index.ts

This is an attempt to fix issues where artwork IDs passed to the artworks loader get shuffled (https://github.com/artsy/metaphysics/pull/4232, https://github.com/artsy/metaphysics/pull/4867, https://github.com/artsy/metaphysics/pull/2537). 
The root cause is that query params [are sorted to increase cache hits](https://github.com/artsy/metaphysics/blob/c9498007a41dbd9dd402f8a075ac5e867fb9439b/src/lib/helpers.ts#L75). This PR fixes the issue by preventing sorting when a non-empty array is passed as a query param (e.g. `?id[]=one&id[]=two&id[]=three`).

fix: Keep order of arrays when passing them to data loaders

---

_schemaV2.graphql
src/schema/v2/conversation/__tests__/message.test.js
src/schema/v2/conversation/index.ts

Reverts artsy/metaphysics#4875 because of issues observed in Force conversations after deploying artsy/impulse#900 (reverted in artsy/impulse#902).

Revert "chore(NX-3485): Enable delivery pending flag to be passed as an arg to messages"

---

src/schema/v2/artist/helpers.ts

Just a minor copy update - looks like this:
https://artsyproduct.atlassian.net/browse/GRO-1619
/cc @artsy/grow-devs @mbransfield

feat: Update artist insight label copy GRO-1619

---

src/lib/stitching/gravity/v2/stitching.ts

The type of this PR is: **chore**
This PR solves [GRO-1582]
This is an update to the collections populating the home screen of the app. It took me a while to find where the curated collections slugs for the home feed were coming from, but thanks to these PRs by @mdole & @jonallured I think I might have found the right place to make the change: 
https://github.com/artsy/metaphysics/pull/4399/
https://github.com/artsy/metaphysics/pull/4677
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1582]: https://artsyproduct.atlassian.net/browse/GRO-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore (app home screen): update curated collections

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

This resolves [CX-3524]
This PR adds the Request Price Estimate requirements to the artwork type as a boolean field called `isPriceEstimateRequestable`
```graphql
{
artwork(id: "foo-bar") {
isPriceEstimateRequestable
}
}
```
```json
{
"data": {
"artwork": {
"isPriceEstimateRequestable": false
}
}
}
```
[CX-3524]: https://artsyproduct.atlassian.net/browse/CX-3524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3524): Add isPriceEstimateRequestable field to artwork type

---

src/schema/v2/__tests__/auction_result.test.ts
src/schema/v2/auction_result.ts

**Note:**
This change might lead to performance issues in case we query for different artists from different lots but given that we are not doing this in any surface, we won't do the optimisation unless needed.

chore: fix artist interface inside auction result

---

src/lib/stitching/gravity/v2/stitching.ts

The type of this PR is: **chore**
This PR solves [GRO-1580]
This is an update to the collections populating the search screen on the app. It took me a while to find where the curated collections slugs for the home feed were coming from, but thanks to this PR by @nickskalkin I believe I found the correct place to make the change: 
https://github.com/artsy/metaphysics/pull/4521
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1580]: https://artsyproduct.atlassian.net/browse/GRO-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore (app search screen): update curated collections

---

_schemaV2.graphql
src/lib/stitching/gravity/v2/stitching.ts

This stitches in the `me` field to the payload for creating a saved search. We need it to access the updated counts object.

feat(mutation): adds me field to create saved search payload

---

src/schema/v2/auction_result.ts

This PR addresses [CX-3574]
- Enables passing `sale_date` (note: Not `-sale_date`) as sort param in order to receive results in ASC order
Related to https://github.com/artsy/diffusion/pull/710
[CX-3574]: https://artsyproduct.atlassian.net/browse/CX-3574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(CX-3574): Support Lots ASC param

---

src/schema/v2/CollectorProfile/__tests__/updateCollectorProfileWithID.test.ts
src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/me/__tests__/collector_profile.test.js
src/schema/v2/me/__tests__/update_collector_profile.test.js
src/schema/v2/partner/__tests__/partnerInquirerCollectorProfile.test.ts

Reverts artsy/metaphysics#4868
Rather than digging in to the `owner` object (which erroneously _exposed_ these properties, which will be removed in https://github.com/artsy/gravity/pull/16228), it's correct + preferred to take them from the root/parent document (the collector profile JSON itself in this case).
Assuming there is a stale/caching issue on Gravity for when owners update their information, and it's not reflected here - (from https://github.com/artsy/gravity/pull/16149), I will take a look at what's going on there - we should be able to get that working as expected.

Revert "fix(CX-3459): Update collector profile resolvers"

---

_schemaV2.graphql
src/schema/v2/me/__tests__/collection.test.ts
src/schema/v2/me/collection.ts

- [Jira ticket](https://artsyproduct.atlassian.net/browse/FX-4725)
Add an option to `artworksCount` to count only visible artworks
Request:
```graphql
{
me {
collection(id: "2fc5f80e-759f-4fbf-90a1-5a7f58785921") {
name
privateArtworksCount: artworksCount
visibleArtworksCount: artworksCount(onlyVisible: true)			
}
}
}
```
Response:
```graphql
{
"data": {
"me": {
"name": "All Saves",
"privateArtworksCount": 161,
"visibleArtworksCount": 157
}
}
}
}
```

feat(FX-4725): allow counting only visible artworks for collections

---

_schemaV2.graphql
src/schema/v2/artist/index.ts
src/schema/v2/fields/__tests__/pagination.test.js
src/schema/v2/fields/pagination.ts

This PR updates page numbers cap logic to be able to load more than 100 pages for auction results. Also added `page` and `size` to use pagination by page for auction results instead of cursor pagination.
JIRA - [DO-675]
[DO-675]: https://artsyproduct.atlassian.net/browse/DO-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update pagination for auction results.

---

src/lib/loaders/helpers.ts

Addresses [CX-3534]
Reduce number of loaded artists in AuctionResultsByFollowedArtists. Sending more than 100 artworks to Diffusion could be the reason for these timeouts ([Slack Thread](https://artsy.slack.com/archives/C01B2P6LJUU/p1681324853790219)).
[CX-3534]: https://artsyproduct.atlassian.net/browse/CX-3534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Reduce number of loaded artists in AuctionResultsByFollowedArtists

---

_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/v2/stitching.ts

Lots of marketing collections do not have thumbnail images attached. When searching by collection name in the app, a collection without a thumbnail image will have a grey image placeholder instead.
This PR gets the `representativeArtworkId` from gravity and uses its `imageUrl` as the fallback image to display as the thumbnail image of those marketing collections.
for eg:

feat: fallback image for marketing collection

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/me/__tests__/collector_profile.test.js

This is a follow-up to https://github.com/artsy/metaphysics/pull/4934, where I tried to expose a `conversation.fromProfile` property that could serve in place of `conversation.fromUser.collectorProfile`. The latter depends on a request to the unprivileged user API that I would like to retire, but doesn't actually _need_ any of the data from that API (as all necessary fields are already available on the collector profile).
This PR adds the `initials` property that volt-v2 requires. It's based on the user name, which is handily available on the collector profile as well.

feat: add initials property to CollectorProfileType (PLATFORM-5094)

---

src/schema/v2/conversation/conversations.ts

[NX-3505]
Makes dismissed param false by default querying Conversations.
[NX-3505]: https://artsyproduct.atlassian.net/browse/NX-3505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3505): conversation dismissed is false by default on query

---

_schemaV2.graphql
src/schema/v2/conversation/__tests__/__snapshots__/conversation.test.js.snap
src/schema/v2/conversation/__tests__/conversation.test.js
src/schema/v2/conversation/index.ts

[NX-3437]
- Adds unreadByPartner and unreadByCollector fields to the conversation
- deprecates `unread` in favor of `unreadByCollector` to improve the general understanding of it
[NX-3437]: https://artsyproduct.atlassian.net/browse/NX-3437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3437): add unread fields for Partner and Collector

---

src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/me/__tests__/collector_profile.test.js

Depends on https://github.com/artsy/gravity/pull/16260, so a draft for now.
As described there, these verification statuses are no longer available within the nested `owner`, so they must be resolved from the top-level collector profile properties. Once that's merged, we can validate and release this change.

fix: restore access to identity and email verification status via collector profiles

---

src/schema/v2/artwork/taxInfo.ts

The PR updates one help center URL for Zendesk to Salesforce transition.
https://artsyproduct.atlassian.net/browse/TX-1097

[Release on 4/18] Update the help center URL for Zendesk to Salesforce transition # Summary

---

_schemaV2.graphql
src/schema/v2/conversation/__tests__/update_conversation_mutation.test.js
src/schema/v2/conversation/update_conversation_mutation.ts

Resolves [NX-3438](https://artsyproduct.atlassian.net/browse/NX-3438)
The `updateConversation` mutation now takes a `toLastViewedMessageId` that updates the `to_last_viewed_message_id` field on Impulse.
[NX-3438]: https://artsyproduct.atlassian.net/browse/NX-3438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(NX-3438): Allow updateConversation mutation to update toLastViewedMessageId

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/__tests__/sale_artworks.test.ts
src/schema/v2/sale_artworks.ts

Addresses [CX-3621]
This PR allows trusted clients to fetch sale artworks by user ID as a param by passing the user ID to Gravity.
Related Gravity PR: https://github.com/artsy/gravity/pull/16258
---
**Query:**
```
{
viewer {
saleArtworksConnection(
first: 10
includeArtworksByFollowedArtists: true
isAuction: true
liveSale: true
userId: "a-user-id"
) {
pageInfo {
hasNextPage
startCursor
endCursor
}
edges {
node {
id
href
slug
}
}
}
}
}
```
[CX-3621]: https://artsyproduct.atlassian.net/browse/CX-3621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Allow trusted clients to fetch sale artworks by user ID

---

index.js
src/lib/cache.ts

We had an incident today when all MP pods were removed, presumably failing a health-check. We also observed some logs and metrics that were pointing to increased cache latency.
At first, it seemed like MP should be resilient to this, as all the `get` calls are wrapped in a way that will time them out fairly aggressively.
However, we were actually making a call to the cache for health-checks, which would likely hang. Let's just remove it! With this call, MP is not very resilient to a slowly-responding cache server, and I think our goal is to be as resilient as possible (while not masking real issues, which I believe to be caught by more dedicated monitoring for the cache, which we already have via datadog, Elasticache metrics, etc.)

fix: remove cache availability check from health-check endpoint

---

index.js
src/index.ts
src/lib/bodyParserMiddleware.ts

Passing in a request body that was > 100kb to Metaphysics (now happening due to page management), led to a 'silent' 404. It turns out that the default for `body-parser` is 100kb. MP would return a 404 (and Chrome complained about a CORS issue in the dev console, likely a red herring due to the 404 not returning some appropriate headers). The 404 was 'silent' b/c there  were no logs from the MP webserver indicating something like 'Request size too large'.
I suppose we shouldn't spam logs with every issue related to an invalid request, but I dunno - it certainly would have been nice to have seen that in this case!
Additionally, looks like there's an extra use of `bodyParser` middleware that's not needed, so removing that too.

fix: bump request body limit to 1mb from 100kb

---

_schemaV2.graphql
src/schema/v2/__tests__/notification_preferences.test.ts
src/schema/v2/notification_preferences.ts

The type of this PR is: **Feat**
This PR solves [GRO-1650]
The goal of this PR is to update `notificationPreferences` to support a channel field to be passed to Gravity as part of a first step towards rebuilding the user preference center to include push notifications.
Tech plan: https://www.notion.so/artsy/Notification-Preference-Center-Mobile-Web-294c4c1967e9491984048cef8c91893a 
TODO
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1650]: https://artsyproduct.atlassian.net/browse/GRO-1650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(pref center): update metaphysics to support channel field for push

---

.tool-versions

I'm not totally sure what happened here but at least for me this way of specifying a node version does not work with asdf:
```
jon@sabretooth:~/code/temp/metaphysics(main)% asdf current
java            zulu-11.58.15   /Users/jon/.tool-versions
nodejs          18.15           Not installed. Run "asdf install nodejs 18.15"
python          3.9.13          /Users/jon/.tool-versions
ruby            3.1.0           /Users/jon/.tool-versions
rust            1.55.0          /Users/jon/.tool-versions
15:25:17
jon@sabretooth:~/code/temp/metaphysics(main)% asdf install nodejs 18.15
Trying to update node-build... ok
node-build: definition not found: 18.15
```
So all I did here was specify down to the patch level. I assume this is fine but lmk if I'm missing something!

Update tool versions file

---

src/schema/v2/artists/__tests__/curatedTrending.test.ts
src/schema/v2/artists/curatedTrending.ts

https://artsyproduct.atlassian.net/browse/FX-4782
Related to [this Slack thread](https://artsy.slack.com/archives/C02BAQ5K7/p1683551869036359) and maybe [this one too](https://artsy.slack.com/archives/C02BAQ5K7/p1683640885033599).
When data for the [curated trending collection](https://www.artsy.net/collection/trending-this-week?metric=in) is invalid — e.g in the staging environment after a failed prod→staging weekend copy — then the response for the `curatedTrendingArtists` field might under certain circumstances be unusable, i.e. data that is both incorrect and invalid. See the ticket^ for sleuthing details.
This addresses that by doing an early return if it appears that the trending collection is itself empty.
The relevant change is in f916a4ca0c2dc372cdb3f78bf4f2d9a27f431574

fix(trending artists): handle invalid/empty response more defensively

---

_schemaV2.graphql
src/schema/v2/me/myCollectionInfo.ts

I would like to be able to use a pagination fragment for myCollectionInfo. To support that, we need to make a node out of my collection info.
This will also allow help relay store tell that some fields changed by returning them directly without need to refresh the store

chore: make my collection info node

---

_schemaV2.graphql
src/schema/v2/artist/index.ts
src/schema/v2/me/__tests__/myCollectionInfo.test.ts
src/schema/v2/me/myCollectionInfo.ts

As mentioned in https://github.com/artsy/metaphysics/pull/4997#discussion_r1191597267 , proposing this as an alternate schema design (and possible pattern) for future counts + metadata-type stuff.

feat: use an edge field on an artistsConnection to store some counts

---

src/schema/v2/partner/partner.ts

Following a big discussion and a confluence of factors -- ty @oxaudo for your help, otherwise this would have been much more confusing -- we realized that `published: false` no longer returns all artworks; now, to see all artworks, we pass no `published` argument to gravity at all. By default it falls back to `published: true`. 
Before:
After: 
cc @artsy/mobile-platform

fix(partner): Update includeUnpublished logic to return all

---

_schemaV2.graphql
src/schema/v2/OrderedSet/__tests__/addOrderedSetItemMutation.test.ts
src/schema/v2/OrderedSet/__tests__/deleteOrderedSetItemMutation.test.ts
src/schema/v2/OrderedSet/addOrderedSetItemMutation.ts
src/schema/v2/OrderedSet/deleteOrderedSetItemMutation.ts

This PR extends the `deleteOrderedSetItemMutation` and the `addOrderedSetItemMutation`s to support returning the parent `OrderedSet`. It directly supports the `sets` page refactor in `forque`: https://github.com/artsy/forque/pull/827.
TODO:
[PLATFORM-5151]
[PLATFORM-5151]: https://artsyproduct.atlassian.net/browse/PLATFORM-5151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: optionally return the set when adding or removing a set item

---

src/lib/loaders/loaders_with_authentication/gravity.ts

Missed a commit on #5012. We need to include the `setItemsLoader` in `loaders_with_authentication` to avoid cached data being returned with the mutation.

feat: add setItemsLoader to authenticated loaders

---

_schemaV2.graphql
src/schema/v2/conversation/conversations.ts

[NX-3538]
Adds the `fromId` option when filtering conversations as a `Partner`.
[NX-3538]: https://artsyproduct.atlassian.net/browse/NX-3538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3538): add filter by from_id in ConversationsConnection

---

_schemaV2.graphql
src/schema/v2/conversation/conversations.ts

[NX-3537]
Adds the `artistId` option when filtering `ConversationsConnection`.
[NX-3537]: https://artsyproduct.atlassian.net/browse/NX-3537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3537): add artistId filter to conversationConnection query

---

src/schema/v2/conversation/conversations.ts

[NX-3537]
Param name on the endpoint must be `artist_id` (and not `artistId`)
[NX-3537]: https://artsyproduct.atlassian.net/browse/NX-3537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(NX-3537): Fix name of param passed as artist id to conversations

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/HeroUnit/HeroUnitType.ts
src/schema/v2/HeroUnit/createHeroUnitMutation.ts
src/schema/v2/HeroUnit/deleteHeroUnitMutation.ts
src/schema/v2/HeroUnit/heroUnit.ts
src/schema/v2/HeroUnit/heroUnitsConnection.ts
src/schema/v2/HeroUnit/updateHeroUnitMutation.ts
src/schema/v2/home/__tests__/home_page_hero_units.test.js
src/schema/v2/home/home_page_hero_units.ts
src/schema/v2/schema.ts

This PR adds a set of operations for hero units:
* heroUnitsConnection - list of hero units
* heroUnit - a particular hero unit
* createHeroUnit - to create
* deleteHeroUnit - to delete
* updateHeroUnit - to update
This is in service of force wanting to display hero units and forque that wants to manage them. I stole things from a few places to put this all together so lmk if anything look wonky! I'm especially interested to know if anybody sees missing tests.
https://artsyproduct.atlassian.net/browse/GRO-1683

feat: Add hero unit operations GRO-1683

---

_schemaV2.graphql
src/schema/v2/sale_artworks.ts

Support a new boolean `marketable` argument for the `saleArtworksConnection` query field, allowing clients to specify the backend should filter to only marketable works.
Jira: [FX-4777](https://artsyproduct.atlassian.net/browse/FX-4777)
[FX-4777]: https://artsyproduct.atlassian.net/browse/FX-4777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: support marketable arg for saleArtworks connection

---

_schemaV2.graphql
src/schema/v2/artist/__tests__/meta.test.js
src/schema/v2/artist/meta.ts

The type of this PR is: **Chore**
This PR solves [GRO-1671]
* adds `ArtistPageEnumType` to `ArtistMeta` to make it easier to get the tag's content depending on the Artist page tab
This is 🤝 with https://github.com/artsy/force/pull/12430
[GRO-1671]: https://artsyproduct.atlassian.net/browse/GRO-1671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(GRO-1671): update meta tags based on the selected tab on the Artist page

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/locationHelpers.ts
src/schema/v2/me/showsConnection.ts
src/schema/v2/partner/partners.ts

Addresses [CX-3688]
This PR adds all parameters to `partnersConnection` introduced in https://github.com/artsy/gravity/pull/16387.
[CX-3688]: https://artsyproduct.atlassian.net/browse/CX-3688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add follow and sort args to partnersConnection

---

src/schema/v2/auction_result.ts

This PR adds current user id to the comparables query. Since the id is added for testing proposes I added it as a query parameter.
JIRA - [DO-692]
[DO-692]: https://artsyproduct.atlassian.net/browse/DO-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add user id to comparables query

---

src/schema/v2/conversation/conversations.ts

When `artistId` is `null` we send undefined to the server in order to avoid computing.

fix(conversationsConnection): gracefully handle null artistId

---

_schemaV2.graphql
src/schema/v2/artist/meta.ts

Follow up on https://github.com/artsy/metaphysics/pull/5024 and making `ArtistMeta` type non-nullable.
I thought this was committed to my previous PR but the git hooks kept reverting that change so here it is again!

chore(GRO-1671) Follow up

---

src/schema/v2/HeroUnit/heroUnitsConnection.ts

This purpose of this PR is to troubleshoot why we can't seem to get hero units to show up over on the Force review app for https://github.com/artsy/force/pull/12459 when signed out. There were some theories that it was something to do with different loaders being used so here I'm eliminating that as a possibility by only using the basic hero units loader all the time.
Note that this does break forque but that's ok since we haven't fully cut anything over and are still WIP on this stuff.

Only return all active hero units

---

src/schema/v2/HeroUnit/heroUnitsConnection.ts

This reverts commit ac5aa40277eb896ea8f436b170911e9ef605c82a.
https://github.com/artsy/metaphysics/pull/5059
This experiment didn't fix anything so I'm going back to the way it was.

Revert "Only return all active hero units"

---

_schemaV2.graphql
src/schema/v2/FeaturedLink/createFeaturedLinkMutation.ts

We received a request from the curatorial team to not require a description when creating a featured link. This removes that requirement from the `MP` schema. It also matches the current old admin [implementation](https://github.com/artsy/torque/blob/eda88b6919945c5880e6439f797653f50f4457d8/app/templates/frames/featured_link.jade#LL21C6-L21C97). A follow-up will be made in `Forque` to remove the client form validation.

refactor: allow null description in createFeaturedLinkMutaion

---

_schemaV2.graphql
src/schema/v2/HeroUnit/__tests__/heroUnitsConnection.test.ts
src/schema/v2/HeroUnit/heroUnitsConnection.ts

This PR adds some much needed specs around picking which hero units loader to use. Prior to this PR it was not easy enough to understand when which of the three loaders would be used and I wanted to further complicate things so I started by extracting a function and wrapping the existing behavior with tests.
Then I added the complexity - if a flag called `private` is passed then use the authenticated loader and if not use the normal one.
So that's what this PR does - adds a flag to the hero units connection and then improves the resolver function by extracting the business logic to a separate function. That function is now wrapped with tests that help articulate the cases and should clarify when each of the loaders will be used.
This is all in service of changing Force to conditionally …

chore: Add flag to include private hero units GRO-1755

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/__tests__/profiles.test.ts
src/schema/v2/profiles.ts
src/schema/v2/schema.ts

Our initial migration of the sets editor from `torque` did not include the `profile` item type as part of its scope. Once we cut over it was [surfaced](https://artsy.slack.com/archives/C0376CFU527/p1683046933073749) that this is blocking the retirement of the `torque` implementation. 
Support managing sets with the `profile` item type. In support of that this PR: 
- Adds a `profilesLoader`
- Adds a `profiles` type (queryable with `profilesConnection`), which uses the `matchLoader` if a `term` argument is provider, otherwise it falls back to the `profilesLoader`. It also supports passing an array of `ids`. 
<details>
<summary>Search without term</summary>
</details>
<details>
<summary>Search with term</summary>
</details>
<details>
<summary>Search with array of ids</summary> 
</details>
- …

feat: add profilesConnection

---

_schemaV2.graphql
src/lib/locationHelpers.ts
src/schema/v2/me/showsConnection.ts
src/schema/v2/partner/partners.ts

Add includePartnersNearIpBasedLocation param to partnersConnection.
This PR adds the parameter `includePartnersNearIpBasedLocation` to partnersConnection. When set to true, the IP address from context is used to do the geo lookup (introduced in https://github.com/artsy/metaphysics/pull/5055).
I removed the param `ip`. It's not used yet by any clients and this breaking change shouldn't break anything.
--- 
**Related PRs:**
- https://github.com/artsy/metaphysics/pull/5079

feat: Add includePartnersNearIpBasedLocation param to partnersConnection

---

_schemaV2.graphql
src/schema/v2/partner/partners.ts

This PR adds the param `maxDistance` to `partnersConnection` to be able to pass it to Gravity. This is needed to not default to 75 when sorting by distance on the new "Galleries for You" screen in the app.

feat: Add maxDistance param to partnersConnection

---

_schemaV2.graphql
src/schema/v2/__tests__/requestLocation.test.ts
src/schema/v2/requestLocation.ts

This PR modifies the `requestLocation` field as follows:
-  Making the `ip` parameter optional and adjusting the resolver to use the IP address from the context (obtained from the request headers).
-  Adding field coordinates to the `requestLocation` type.
---
The location lookup request should be cached, so the following query should only do one request:
```graphql
{
requestLocation {
country
coordinates {
lat
lng
}
me {
showsConnection(includeShowsNearIpBasedLocation: true) {
totalCount
}
}
}
```
---
These changes enable us to use the user's location in the app when retrieving content based on the user's (IP-based) location (https://github.com/artsy/eigen/pull/8902, https://github.com/artsy/eigen/pull/8901).

feat: Use IP address from header for location request

---

_schemaV2.graphql
src/schema/v2/__tests__/identityVerification.test.ts
src/schema/v2/identityVerification.ts
src/schema/v2/me/__tests__/sendIdentityVerficationEmailMutation.test.ts
src/schema/v2/me/sendIdentityVerficationEmailMutation.ts

Companion to https://github.com/artsy/gravity/pull/16451. Makes `saleID`, `orderID`, and `initiatorID` settable and fetchable.

feat: support sending and fetching source id on IDV

---

src/data/gravity.graphql
src/lib/stitching/gravity/schema.ts

[FX-4642](https://artsyproduct.atlassian.net/browse/FX-4642) & [FX-4819](https://artsyproduct.atlassian.net/browse/FX-4819)
Follow-up to:
- https://github.com/artsy/metaphysics/pull/5087
- https://github.com/artsy/gravity/pull/16457
Now that the Algolia fields have been [removed](https://github.com/artsy/gravity/pull/16457) from GravQL we update the Gravity schema over here in MP too (and remove references to the stitched types that no longer exist).
[FX-4642]: https://artsyproduct.atlassian.net/browse/FX-4642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FX-4819]: https://artsyproduct.atlassian.net/browse/FX-4819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update schema and stitching after upstream Algolia removal

---

src/lib/locationHelpers.ts
src/schema/v2/me/showsConnection.ts
src/schema/v2/partner/__tests__/partners.test.js
src/schema/v2/partner/partners.ts

[Jira Ticket](https://artsyproduct.atlassian.net/browse/CX-3809)
The `partnerConnection`'s `maxDistance` parameter is currently not passed on to Gravity if the `near` parameter is set. This pull request fixes the issue and adds some tests. 
It also fixed a bug where Boolean parameters aren't passed to Gravity if they are set to `false`.

fix: Pass partners connection arguments correctly

---

src/schema/v2/me/__tests__/newWorksByInterestingArtists.test.ts
src/test/fixtures/gravity/order.json
src/types/runtime/gravity/Artwork.ts

This is the references I could find to Artwork `private` field here.
A bit confusing one is the one on `collectionsConnection`. Those are requesting artworks but I believe `private` in those requests refers to `private` collection vs `private` artwork...

chore: removing some private mentions from artwork

---

_schemaV2.graphql
src/schema/v2/__tests__/verify_address.test.ts
src/schema/v2/verifyAddress.ts

This PR fixes some issues with our address verification fields which was causing our `verifyAddress` query to not work. It also includes a **breaking change** to move all address field arguments under a single `address:` argument, allowing for more flexibility in the future. This field is not yet used by any client.
completes [EMI-1278](https://artsyproduct.atlassian.net/browse/EMI-1278)
cc @artsy/emerald-devs 
[EMI-1278]: https://artsyproduct.atlassian.net/browse/EMI-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: incorrect & inconsistent address validation fields

---

_schemaV2.graphql
src/schema/v2/me/__tests__/collectionsConnection.test.ts
src/schema/v2/me/collectionsConnection.ts

- [Jira ticket](https://artsyproduct.atlassian.net/browse/ONYX-116)
Add two new sort options to `collectionsConnection`: `UPDATED_AT_ASC` and `UPDATED_AT_DESC`.
Do not merge until https://github.com/artsy/gravity/pull/16523 is on production!

feat(ONYX-116): support sorting collections by recency

---

src/lib/loaders/__tests__/request_id.test.js
src/lib/loaders/__tests__/user_agent.test.js
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/artwork/index.ts
src/schema/v2/conversation/__tests__/submit_inquiry_request_mutation.test.ts
src/schema/v2/me/__tests__/myCollection.test.ts

We shouldn't name loaders with 'authenticated' or 'unauthenticated' since that's kind of redundant - also, it's by design that we can name them the _same_ between the authenticated and unauthenticated files, and when the user is logged in, the authenticated one is selected.
This should obviate the `authenticatedArtistLoader || artistLoader` pattern, and means this PR - https://github.com/artsy/metaphysics/pull/5134 - can just be closed, it'll work as expected.

chore: rename redundantly named authenticatedArtistLoader

---

src/lib/timer.ts

While checking the logs printed in MP, I noticed that the logs printed are pretty hard to read and spent some time to see if I can make them a bit prettier.
**Before**
___
**After**

chore: better formatted logs in MP

---

_schemaV2.graphql
src/schema/v2/artist/index.ts
src/schema/v2/artist/updateArtistMutation.ts

Very simple change here. Just exposes the `coverArtwork` field on an artist, falls back to the most iconic work, and adds the support to update it in the mutation.

feat(artist): supports cover artworks

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/userInterest.test.ts
src/schema/v2/me/index.ts
src/schema/v2/me/userInterest.ts
src/schema/v2/userInterests.ts

Addresses [ONYX-118]
This PR adds a `userInterest` field under `me` to fetch user interests by ID. The new field is needed because we have decided against returning all the necessary data in the `userInterestsConnection`.
**Query:**
```graphql
{
me {
userInterest(id: "user-interest-id") {
internalID
interest {
__typename
... on Artist {
internalID
}
}
}
}
}
```
[ONYX-118]: https://artsyproduct.atlassian.net/browse/ONYX-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: me userInterest field

---

src/lib/HTTPError.ts
src/lib/__tests__/gravityErrorHandler.test.ts
src/lib/apis/fetch.ts
src/lib/gravityErrorHandler.ts
src/schema/v2/__tests__/deleteUserMutation.test.ts
src/schema/v2/me/__tests__/createCollectionMutation.test.ts
src/schema/v2/me/__tests__/updateCollectionMutation.test.ts
src/schema/v2/me/createCollectionMutation.ts
src/schema/v2/me/updateCollectionMutation.ts

I tweaked the Gravity error parsing code to work with the formats from https://github.com/artsy/gravity/blob/04a76103bcf26516a656537a3e98e45248127aa6/app/api/util/error_handlers.rb
namely:
```
error: not always present, can be contents of entire error, or `error` property
message: human-readable, should be always present
detail: array of field-level errors
type: more short-hand 'type' of error
```
This works with the common errors from Gravity, and obviates the fix added in https://github.com/artsy/metaphysics/pull/5076 for collections.

feat: update some gravity error parsing code to be more accurate

---

_schemaV2.graphql
src/lib/__tests__/helpers.test.ts
src/lib/helpers.ts
src/schema/v2/me/__tests__/myCollection.test.ts
src/schema/v2/me/myCollection.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts

Addresses [ONYX-140]
- Related Gravity PR: https://github.com/artsy/gravity/pull/16558
This PR adds an `artistIDs` param to the connection `me.myCollectionConnection` to filter artworks by artist ID.
[ONYX-140]: https://artsyproduct.atlassian.net/browse/ONYX-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add artistIDs param to myCollectionConnection

---

_schemaV2.graphql
src/schema/v2/verifyAddress.ts

Let's make these top-level types all present, which they should be.
#minor

make top-level fields non-null in verifyAddress response

---

_schemaV2.graphql
src/schema/v2/me/__tests__/userInterestsConnection.test.ts
src/schema/v2/me/userInterestsConnection.ts

This PR resolves: [ONYX-159]
This PR adds support to interest ids filtering within `userInterestsConnection`.
**The PR is reviewable in its current state / Gravity changes are needed though before it's ready to be merged**
[ONYX-159]: https://artsyproduct.atlassian.net/browse/ONYX-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-159): support interest id filtering within userInterestsConnection

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/artist/__tests__/verifiedRepresentatives.test.ts
src/schema/v2/artist/index.ts
src/schema/v2/artist/verifiedRepresentatives.ts

We are introducing the VerifiedRepresentative field[] to the Artist schema. This addition will be as the definitive source for information on galleries representing artists.
[DIA-43]
https://artsy.slack.com/archives/C05EEBNEF71/p1689862876720839
[DIA-43]: https://artsyproduct.atlassian.net/browse/DIA-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add verified representatives to Artist schema

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/impulse.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/lib/stitching/gravity/v2/stitching.ts
src/schema/v2/conversation/__tests__/conversation.test.js
src/schema/v2/conversation/conversationEvent.ts
src/schema/v2/conversation/index.ts
src/schema/v2/partner/partner.ts

Companion to https://github.com/artsy/impulse/pull/956.
This PR introduces a new `messagesAndConversationEventsConnection` field inside a `conversation`, which fetches messages and events (like an offer being submitted or rejected) together in a single chronologically-ordered connection.
Sample query (note that to run this, you'll need to change the ID to be a conversation you're part of):
```graphql
query {
me {
conversation(id: "208433") {
messagesAndConversationEventsConnection(first: 50) {
edges {
node {
__typename
... on Message {
internalID
isFromUser
body
}
... on ConversationEvent {
buyerBody
sellerBody
eventKey
}
}
}
}
}
}
}
```
Jira ticket: https://artsyproduct.atlassian.net/browse/AMBER-28

feat(AMBER-28): create messages and conversation events query

---

.circleci/deploy_event.sh
hokusai/config.yml

https://artsyproduct.atlassian.net/browse/PHIRE-81
We no longer want to send deploy events to datadog via a custom script and so this removes the script and `post-deploy` configuration in hokusai config.

chore: remove post-deploy from hokusai config

---

_schemaV2.graphql
src/schema/v2/artist/__tests__/helpers.test.ts
src/schema/v2/artist/helpers.ts

[DIA-65]
Description: 
It exposes last two data points for the artist insights. 
Corresponding [Gravity PR](https://github.com/artsy/gravity/pull/16522) 
cc @artsy/diamond-devs 
[DIA-65]: https://artsyproduct.atlassian.net/browse/DIA-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add curated_trending and curated_emerging to artist insights

---

src/schema/v2/artist/__tests__/helpers.test.ts
src/schema/v2/artist/helpers.ts

This PR resolves the error caused with recent introduction of recent_career_event. 
AC: 
There should be value in expandable box.
```
{
error  {
message  {
String cannot represent value: ["2022 New York: 1962 - 1964"]     
}
}
}
```
https://app.datadoghq.com/apm/traces?query=env%3Aproduction%20service%3Ametaphysics.graphql%20operation_name%3Agraphql.execute%20%40issue.id%3A%2A%20AND%20resource_name%3A%22query%20ArtistCareerHighlightsQuery%28%24id%3AString%21%29%7Bartist%28id%3A%24id%29%7Bid...ArtistCareerHighlights_artist%7D%7Dfragment%20ArtistCareerHighlights_artist%20on%20Artist%7Bhref%20insights%7Bdescription%20entities%20kind%20label%7Dname%7D%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&graphType=flamegraph&historicalData=true&messa …

fix: use correct recent career event type

---

src/lib/loaders/api/loader_without_cache_factory.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/__tests__/filterArtworksConnection.test.ts
src/schema/v2/filterArtworksConnection.ts

On an auction page, when sorting by price - we want those results to start being more real-time and 'live' - and so while there's likely a couple of related PR's for that functionality incoming - we definitely need an uncached loader in Metaphysics for it.
This will be in use whenever any user (logged-in or not) includes the relevant sort and filter. For those requests, irregardless of whether they are logged-in or not, we'd want to make the live request to Gravity.
Fixes https://artsyproduct.atlassian.net/browse/ONYX-199
As a bonus - added logging and the request extension debug information for loaders of this type:
and

feat: add an uncached loader for filterArtworks, and use when filtering by a sale and sorting by price

---

src/schema/v2/__tests__/filterArtworksConnection.test.ts
src/schema/v2/filterArtworksConnection.ts

Following up on https://github.com/artsy/metaphysics/pull/5191#discussion_r1283779732 , the real-time behavior of sorting by a price looks to be good - so let's add the filtering by price behavior as well - that was still stale in mocktion-ing.

feat: use uncached filterArtworksLoader when filtering by price within a sale

---

src/schema/v2/__tests__/filterArtworksConnection.test.ts
src/schema/v2/filterArtworksConnection.ts

As a follow-up to https://github.com/artsy/metaphysics/pull/5194 , let's require a `priceRange` which is truthy and _not_ `*-*` (as that's not really filtering by price at all and so we don't need to skip the cache for 'real-time' results).

fix: check for *-* priceRange filters, as thats not really filtering

---

_schemaV2.graphql
src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch.ts
src/schema/v2/searchCriteriaLabel.ts

https://artsyproduct.atlassian.net/browse/ONYX-173
This nests a new `displayName` field under the root-level `previewSavedSearch` field.
```graphql
query {
previewSavedSearch(
attributes: {
artistIDs: ["kaws"]
priceRange: "100-1000"
additionalGeneIDs: "prints"
attributionClass: "limited edition"
}
) {
displayName # 👈🏽👈🏽👈🏽
labels {
displayValue
}
}
}
```
```json
{
"data": {
"previewSavedSearch": {
"displayName": "KAWS — $100–$1,000, Print, Limited edition",  👈🏽👈🏽👈🏽
"labels": [
{
"displayValue": "KAWS"
},
{
"displayValue": "Limited edition"
},
{
"displayValue": "Print"
},
{
"displayValue": "$100–$1,000"
}
]
}
}
}
```
- `previewSavedSearch` was added in https://github.com/artsy/metaphysics/pull/3864 so that we could centralize some logic for displaying an unpersisted saved search in …

feat(alerts): add a displayName field for saved search criteria

---

src/schema/v2/partner/__tests__/partners.test.js
src/schema/v2/partner/partners.ts

We need to prevent sorting partners by distance when no location is provided in the following query (because Gravity expects the `near` param when sorting by distance). This case can happen when the IP-based location lookup fails ([Slack Thread](https://artsy.slack.com/archives/C02BAQ5K7/p1691567528217389)).
```graphql
{
partnersConnection(
maxDistance: 10
type: GALLERY
eligibleForListing: true
excludeFollowedPartners: false
defaultProfilePublic: false
sort: DISTANCE
) {
edges {
node {
internalID
}
}
}
}
```
Gravity returns the following error when sorting by `location` without providing `near`:
```
when `near` param is not provided and ip based location lookup fails › returns a list of partners without sending `distance` param
```
**Open Question:**
This could also be fixed in Gravity by …

fix: Prevent sorting partners by distance without provided location param

---

src/schema/v2/artist/__tests__/helpers.test.ts
src/schema/v2/artist/helpers.ts

Fixes the logic of displaying the recent show and expandable label.
[Slack thread.](https://artsy.slack.com/archives/C03N12SR0RK/p1691579953459749)

fix: display recent shows from the last 3 years only

---

_schemaV2.graphql
src/lib/stitching/gravity/v2/stitching.ts
src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch.ts

Repurposes the generated display name used for previewSavedSearch for additional use under the existing SearchCriteria type, currently stitched from Gravity's GraphQL schema.
This will allow us to render this generated default/fallback name when the user has not supplied their own custom name for the alert.
Follow-up to #5186.
Jira: [ONYX-234](https://artsyproduct.atlassian.net/browse/ONYX-234)
```graphql
{
previewSavedSearch(attributes: { artistIDs: ["andy-warhol"], priceRange: "0-50000", attributionClass: ["unique"] }) {
displayName
}
me {
email // quirk to get the following stitched query to execute
savedSearchesConnection(first: 5) {
edges {
node {
displayName
}
}
}
}
}
```
```json
{
"data": {
"previewSavedSearch": {
"displayName": "Andy Warhol — $0–$50,000, Unique"
},
"me": { …
```

feat(alerts): expose displayName under stitched SearchCriteria GraphQL type

---

_schemaV2.graphql
src/schema/v2/__tests__/auction_results.test.js
src/schema/v2/aggregations/filterAuctionResultsAggregation.ts
src/schema/v2/artist/index.ts

This PR enhances the Auction Results functionality by adding a currency filtering and aggregations option. This allows users to filter and view auction results specific to certain currencies.
[Diffusion PR](https://github.com/artsy/diffusion/pull/772)

feat: add currency filter and currencies aggregation for Auction Results

---

_schemaV2.graphql
src/schema/v2/__tests__/verify_address.test.ts
src/schema/v2/verifyAddress.ts

The current `verifyAddress` error handling approach is not in pair with what we usually have for other queries and mutations, which is preventing us to handle errors correctly client side.
This updates the resolver to be more in pair with the pattern we use across Gravity queries, i.e., using the `...OrError` and `Success` or `Failure` types.
**After**
_successful response_
_failed response_

feat(EMI-1286) Handle gravity errors in metaphysics verifyAddress query resolver

---

_schemaV2.graphql
src/schema/v2/artist/updateArtistMutation.ts

In order to support migrating more fields to the Forque artist edit page this PR adds more fields to the input type in the update mutation. Note that I was very confused about why adding the fields to the interfaces wasn't enough so I pulled up the actual `inputFields` too. This makes it even easier to see that when you add a field you have to add it in three places. :hurtrealbad: 
https://artsyproduct.atlassian.net/browse/DIA-22

chore: Add more fields to artist update mutation DIA-22

---

src/lib/stitching/gravity/v2/stitching.ts

I unintentionally doubled the fragment spread in [#5201][pr]. This removes that extra weirdness, beyond the standard GraphQL stitching weirdness!
> Why the double ... on SearchCriteria?
Caught by @mzikherman via https://github.com/artsy/gravity/pull/16660#issuecomment-1679035552.
[pr]: https://github.com/artsy/metaphysics/pull/5201
cc/ @anandaroop  @mzikherman

chore: remove double fragment spread in gravity stitching

---

src/lib/artworkMediums.ts
src/schema/v2/__tests__/searchCriteriaLabel.test.ts
src/schema/v2/searchCriteriaLabel.ts

QA'ing the auto-alert creation, which uses id's instead of slugs for `additionalGeneIDs` (coming from the map [here](https://github.com/artsy/gravity/blob/8fa2bc4c4b46d6c81f33032473cdb5d14d8fe751/app/models/user_search_criteria.rb#L26))
Since slugs can change (although the id's can too if the entire gene is 'moved'), I _think_ we might as well update the FE to be able to work with both. (vs. updating the auto-creation on the backend to persist slugs).

fix: format search alert labels when additionalGeneIDs contains ids not just slugs

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/__tests__/user.test.ts
src/schema/v2/user.ts

This PR resolves [ONYX-259]
- Related Forque PR: https://github.com/artsy/forque/pull/956
- Slack Thread for context: https://artsy.slack.com/archives/C05EQL4R5N0/p1692288587491529
This PR exposes a user's My Collection artworks under `user` ([similar to `savedArtworksConnection`](https://github.com/artsy/metaphysics/pull/4363)).
The new connection will be used to display a user's My Collection artworks in in Forque (for user's with the role `customer_support` only).
```graphql
{
user(id: "blah") {
myCollectionArtworksConnection(first: 10) {
totalCount
edges {
node {
title
}
}
}
}
}
```
[ONYX-259]: https://artsyproduct.atlassian.net/browse/ONYX-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-259): Allow admins to query a user's My Collection artworks

---

src/lib/loaders/loaders_with_authentication/gravity.ts

We want to do some user-specific stuff in Gravity as a result of an auto-suggest query (such as use an Unleash flag that is user-specific / AB test).
This means that we need to use an authenticated loader (and skip caching unfort!) for search.

chore: use an authenticated loader for search to be able to use unleash on the backend

---

src/schema/v2/artist/index.ts

This PR addresses an issue where null values were causing parameter exceptions in the diffusion. It has been observed that when nulls are sent, they are being converted to empty strings "", leading to unexpected behavior. 
To resolve this, we've enhanced the parameter handling logic to exclude sending parameters when they are null. 

feat: improve sending of sale end date params

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

[Jira ticket](https://artsyproduct.atlassian.net/browse/ONYX-264)
Enables queries like this - which I think should be helpful to Force/Eigen in order to get the suggested artworks shelf (as well as the count, to know whether or not to even include it at all).

feat: add suggestedArtworksConnection for a saved search on Artwork type

---

_schemaV2.graphql
src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/schema.ts
src/lib/stitching/gravity/v2/stitching.ts
src/schema/v2/__tests__/artists.test.ts
src/schema/v2/artists.ts

This is part two of the stitching work to get things read into MP, where we decorate a gravity graphql type and "connect" it to mp-backed fields -- in this case, transforming `artistIDs` into an `artistsConnection` and attaching the `searchCriteriaConnection` to `partner`. 
Along the way discovered a bug in the `artistsConnection` resolver, where anytime we used the argument `ids` it wouldn't return a connection. Fixed that, and also added some tests. 
Additionally cleaned up the gravity stitching file, mostly through alphabetization (its a large and sprawling file and was getting kinda crazy). GH automatically collapsed things, but i've left comments at the areas that have actually changed!
**Query**:
```graphql
{
partner(id: "gagosian") {
searchCriteriaConnection(first: 1) {
edges { …
```

feat(searchCriteriaConnection): Connect stitched field to artists and fix bug in artistsConnection

---

src/index.ts
src/lib/loaders/api/index.ts
src/lib/loaders/api/loader_without_authentication_factory.ts

This is what we were discussing in Slack - that the mutation schema for a response can sometimes resolve with the changed data (when it's literally the response of the upstream POST/PUT/DELETE) - but sometimes there's a mutation schema which includes fields which make other fetches, and in that mutation context we'd likely always want to skip the cache.
Thus far, this has probably not ever come up b/c any loaders being invoked in the mutation response skip the cache already (authenticated loaders), _or_ that the mutation response schema returns just the changed object directly, sometimes the parent (which might be ok to cache), or some variation of this.
This might altogether be too clever, and perhaps better served by a `X-Skip-Cache` header that can be added by clients for mutations as …

feat: if query body contains the string "mutation", skip cache for gravity loaders

---

_schemaV2.graphql
src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/v2/stitching.ts

Quick and easy. Stitches things into the root-most `Query` type so that we can write queries like:
```
{ 
searchCriteriaConnection(...)  { ... } 
}
```
Will evaluate in a bit if its even worth it to stitch it in under `partner`. Seems fine and idiomatic to make the partnerID argument implicit, but still -- less code in stitching the better, and this root query (exclusively) being used is the least number of LOC, at the expense of a single additional argument passed in. Will see. 
(Super straight forward so just gonna merge this and keep going 👀)

feat(searchCriteriaConnection): Stitch in connection to root `Query`

---

_schemaV2.graphql
src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/v2/stitching.ts

Related: 
- https://github.com/artsy/metaphysics/pull/5244
Need to add this to the `Viewer` type as well, for relay pagination.

feat(searchCriteria): Stitch in connection to root `Viewer`

---

_schemaV2.graphql
src/data/gravity.graphql

Ran 
```
rake graphql:schema:idl
```
and copied to MP
```
cp _schema.graphql path_to_your_local_metaphysics/src/data/gravity.graphql
```
to update gravity graphql schema with latest gravity changes

chore: Update gravity graphql schema with latest gravity changes

---

_schemaV2.graphql
src/data/gravity.graphql

Update gravity graphQL schema with new `SearchCriteriaSinceEnum` + surface in MP schema
Ran 
```
rake graphql:schema:idl
```
and copied to MP
```
cp _schema.graphql path_to_your_local_metaphysics/src/data/gravity.graphql
```
to update gravity graphql schema with latest gravity changes

chore: Update gravity graphql schema with new since enum types

---

src/lib/loaders/loaders_with_authentication/gravity.ts

Reverts artsy/metaphysics#5225
Now that we rolled out the feature and no longer need `current_user` for the Unleash flag - we can drop the authenticated loader here (which should improve performance as there will be some caching re-instated, altho in practice it likely didn't do much, when breaking the caching w/ this change I didn't see any differences in datadog metrics for the endpoint).

Revert "chore: use an authenticated loader for search to be able to use unleash on the backend"

---

_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/v2/stitching.ts

Removes usage of previewByArtist from grav graphql and related stitching as it is not needed
Grav PR: https://github.com/artsy/gravity/pull/16746
VoltV2 PR: https://github.com/artsy/volt-v2/pull/629

chore: Removes usage of previewByArtist from grav graphql and related stitching

---

_schemaV2.graphql
src/schema/v2/__tests__/requestLocation.test.ts
src/schema/v2/requestLocation.ts

Jira Ticket: [ONYX-45]
This PR adds a city field to `requestLocation` in order to show the name of the city of the user in the new "Galleries Near You" artsy home page rail.
[ONYX-45]: https://artsyproduct.atlassian.net/browse/ONYX-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add city name to requestLocation

---

src/schema/v2/__tests__/auction_result.test.ts
src/schema/v2/auction_result.ts

This PR is followup for Diffusion improvements for lots/comparable_lots endpoint.
[Diffusion PR](https://github.com/artsy/diffusion/pull/788)

fix: add handler for not qualified comparable lots

---

_schemaV2.graphql
src/schema/v2/__tests__/auction_results.test.js
src/schema/v2/aggregations/filterAuctionResultsAggregation.ts

This PR adds new aggregation for lots by year created, using `lots.date` field in Diffusion.
[Diffusion PR](https://github.com/artsy/diffusion/pull/780)

feat: add lots by created date aggregation

---

_schemaV2.graphql
src/schema/v2/artist/groupIndicator.ts
src/schema/v2/artist/index.ts
src/schema/v2/artist/targetSupply/index.ts
src/schema/v2/artist/updateArtistMutation.ts

Working through [the list](https://www.notion.so/artsy/5128c372c8e744a28a2accc758b8a480?v=b7d7ce2c8b184dd7834920e1f47fd02d).
This PR adds support for the few remaining enum fields on artists.

feat(artist): adds support for updating target supply and group indicator

---

_schemaV2.graphql
src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/v2/stitching.ts

This updates our SearchCriteria type to support two new fields:
- lowPriceAmount
- highPriceAmount
These fields are derived from the `priceArray` field from GravQL and then passed through our metaphysics money helpers.

feat(searchCriteria): Stitch in lowPriceAmount and highPriceAmount and format via currency 

---

_schemaV2.graphql
src/lib/stitching/gravity/v2/stitching.ts

Previously clients were expected to pass in an integer, now allow clients to pass in an Enum value to reduce date parsing/converting
And will also fix this hidden error from GravityGraphQL
---
Example use
```
{
searchCriteriaConnection(first: 500, highQuality: true, since: LAST_30_DAYS) {
totalCount
edges {
node {
priceArray
internalID
}
}
}
}
}
``` 
Eg:

chore: Use SearchCriterianSinceEnum as part of SearchCriteriaConnection

---

_schemaV2.graphql
src/lib/stitching/gravity/schema.ts
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

This adds `isSavedToList`, including support for the default artwork saves list. In practice, this one field may replace `isSaved` and the custom `collectionsConnection`-exist-y check that is being done currently to determine list-inclusion for the current user/artwork.
I think it's a nice schema addition (suggested by @dblandin ) which will slightly simplify the [client fetch](https://github.com/artsy/force/blob/be6754ecf650bafd5a27203dcee2f29e459e23a3/src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButtonV2.tsx#L96-L102).
Additionally, it allows us to possibly further optimize this field (via batching) for the list-inclusion check, as there's some indication that might be [increasing](https://artsy.slack.com/archives/C05EQL4R5N0/p1693499825263889) artwork grid load …

feat: add isSavedToList to Artwork type

---

_schemaV2.graphql
src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch.ts

- [Jira ticket](https://artsyproduct.atlassian.net/browse/ONYX-317) (forked from [this one](https://artsyproduct.atlassian.net/browse/ONYX-254))
We need to add a button that leads to artist artworks grid based on saved alerts attributes. Currently Force computes `href` on frontend side ([link](https://github.com/artsy/force/blob/4331d87e14354f15419e682ec609f9e897d65d8f/src/Components/SavedSearchAlert/SavedSearchAlertContext.tsx#L109)). In order to avoid duplicating such logic in Eigen we've decided to encapsulate `href` calculation in Metaphysics.
Such request:
```graphql
query MyQuery {
previewSavedSearch(
attributes: {
acquireable: true
additionalGeneIDs: "prints"
artistIDs: ["kaws"]
atAuction: true
attributionClass: ["limited edition", "unique"]
colors: ["yellow", "red"] …
```

Add href field to previewSavedSearch

---

src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/v2/stitching.ts

Addressing part of this ticket:
https://artsyproduct.atlassian.net/browse/AMBER-191
Convert asterisks to:
$0 if there’s no min specified (e.g. `$0-$1,000` instead of `*-$1000`)
“+” if there’s no max specified (e.g. `$1,000+` instead of `$1000-*`

fix: Change formatting of price high/lows

---

src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/v2/stitching.ts

Addressing some money formatting feedback
and [here](https://github.com/artsy/volt-v2/pull/684) too
If lowPrice is null return `0` with currency
$0 if there’s no min specified (e.g. “$0-$1,000” instead of “*-$1000”)

fix: Adds back currency formatting for zero values

---

_schemaV2.graphql
src/lib/stitching/gravity/v2/stitching.ts

This PR comes as follow up on https://github.com/artsy/metaphysics/pull/5287
Although we're stitching the schema, we need to update the list of params specified in `stitching.ts` to match the gravity changes.
**Note:** The changes from the previous PR only had an impact on the `_unused_gravity_savedSearchesConnection`

chore: update artistIDs param to match the one Gravity requests

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/notification.test.ts
src/schema/v2/me/index.ts

[Jira ticket](https://artsyproduct.atlassian.net/browse/ONYX-210)
Adds `me.notification` query field, backed by Gravity's `/notifications/:id` endpoint ([PR](https://github.com/artsy/gravity/pull/16823)).
```graphql
query MyQuery {
me {
notification(id: "6507d7d60cc903ed2ec2b7f4") {
internalID
title
message
artworksConnection(first: 4) {
edges {
node {
title
}
}
}
}
}
}
```
Response:
```json
{
"data": {
"me": {
"notification": {
"internalID": "6507d7d60cc903ed2ec2b7f4",
"title": "Works by Banksy $50,000 - 50",
"message": "6 works added",
"edges": [
{
"node": {
"title": "Integrity Can Buy with Fraud Review"
}
},
{
"node": {
"title": "Integrity Can Buy with Fraud Review"
}
},
{
"node": {
"title": "Integrity Can Buy with Fraud Review"
}
},
{
"node": { …
```

feat(onyx-210): add me.notification query field

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/__tests__/utilities.test.ts
src/schema/v2/artwork/index.ts
src/schema/v2/artwork/utilities.ts

https://artsyproduct.atlassian.net/browse/ONYX-363
This moves the responsibility for determining _whether an artwork is eligible to have an alert created from it_ up into Metaphysics, instead of being scattered across client code paths in a divergent or error-prone way, e.g.:
- Force: [ArtworkSidebarCreateArtworkAlert.tsx ](https://github.com/artsy/force/blob/e0118180edc02645e595100177e67453e8acfdfa/src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateArtworkAlert.tsx#L79C1-L79C1)
- Force: [ArtworkSidebarBiddingClosedMessage.tsx](https://github.com/artsy/force/blob/156b302c328600c704360e4998168c1a72186d44/src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx#L24)
- Eigen: [ArtworkScreenHeaderCreateAlert.tsx](https://github.com/artsy/eigen/blob/090a8262 …

feat(alerts): add `isEligibleToCreateAlert` to Artwork type

---

src/index.ts
src/lib/apis/gravity.ts
src/lib/loaders/api/index.ts
src/lib/loaders/index.ts

This allows an `X-Impersonate-User-ID` header to be passed in to an MP request. If so, it will propagate to gravity, and it will also allow access to the authenticated loaders.
As a demo, this PR allowed the following query to happen (I just tested a piece of the schema that uses the endpoint that was opted-in to this behavior in https://github.com/artsy/gravity/pull/16856).
I specified an `X-Xapp-Token` header, generating one based on the 'Braze staging' client application (which has the `email_provider` role), and my own user id as the `X-Impersonate-User-Id` header value.
And voila!
So I think we might be good - as a POC this proves out that Braze can not only directly query Gravity with that header, but can query MP w/ the header and things work as expected.

feat: allow x-impersonate-user-id headers to grant access to authenticated loaders and propagate

---

_schemaV2.graphql
src/schema/v2/artist/__tests__/index.test.js
src/schema/v2/artist/index.ts

Closes [DIA-171](https://artsyproduct.atlassian.net/browse/DIA-171)
So ultimately this corrects the existing logic and then respects the `partnerBio: false` argument to never return a partner bio.
* I want the partner bio and, if none is available, fall back to the Artsy provided bio: `partnerBio: true`
* I want the Artsy provided bio and, if none is available, fall back to the partner bio: `partnerBio: false`
* `defaultValue: false`
* I want the partner bio and, if none is available, fall back to the Artsy provided bio: `partnerBio: true`
* I only want the Artsy provided bio: `partnerBio: false`
* `defaultValue: true`
------
What would make more sense would just be to separate these into different fields. But since these are used in Eigen this is the only way to fix the bug that's …

fix(artist): returns null for bio when partner bio is false and we do not have a blurb

---

_schemaV2.graphql
src/schema/v2/__tests__/createAdvisoryOpportunity.test.ts
src/schema/v2/createAdvisoryOpportunity.ts

The mutation can optionally accept these fields and pass them through to the backend, which will set the phone number on the user if provided - https://github.com/artsy/gravity/pull/16901

chore: allow passing in phone number attributes when creating an advisory opportunity

---

_schemaV2.graphql
src/schema/v2/conversation/__tests__/__snapshots__/conversation.test.js.snap
src/schema/v2/conversation/__tests__/conversation.test.js
src/schema/v2/conversation/index.ts

Sister PR to https://github.com/artsy/impulse/pull/987.
Pretty sure this is safe to remove entirely and not just deprecate; it's not referenced in Eigen and AFAIK conversations haven't been touched there for a while. If folks feel it would be safer to mark as deprecated though, can switch to that.

chore(AMBER-215): remove lastMessageDeliveryID

---

src/schema/v2/artist/helpers.ts

Remove the descriptions so we use the entities instead.
[Slack](https://artsy.slack.com/archives/C05EEBNEF71/p1696869404116629)

fix: remove description for some insights

---

src/lib/loaders/loaders_without_authentication/diffusion.ts
src/schema/v2/__tests__/auction_results.test.js
src/schema/v2/auction_result.ts

This PR removes the old loader for created dates.
Currently, this query is only used in [Eigen](https://github.com/artsy/eigen/blob/a031acc72df3314723456c9523500cd9dbdb7e18/src/app/Components/Artist/ArtistInsights/ArtistInsightsAuctionResults.tsx#L93). 
We can create a follow-up ticket to replace the Eigen aggregation and then remove `createdYearRange` completely from the schema. @MounirDhahri 
[Metaphysics - the new aggregations](https://github.com/artsy/metaphysics/pull/5255/files)
[Diffusion PR](https://github.com/artsy/diffusion/pull/780)
[DIA-133]
@artsy/diamond-devs 
[DIA-133]: https://artsyproduct.atlassian.net/browse/DIA-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove the old created year aggregation for auction results

---

src/schema/v2/me/myCollectionInfo.ts

This came up when reviewing https://github.com/artsy/metaphysics/pull/5337/files#r1355377518 , and I traced it back to where it was introduced - https://github.com/artsy/metaphysics/pull/4200
That PR is pretty much wrong (I don't know how else to put it 😆 ) - the `userID` already will exist in the context, and so plucking it out of the `me` response and _setting_ it into context is unnecessary - it's already there!
Furthermore, writing to `context` in a resolver is an anti-pattern / bug waiting to happen - that will 'leak' to other fields + resolvers that are happening in the same request. Another field accessing `context.userID` later in the request will be reading this same global value. In practice this may not be a bug b/c the `userID` is likely going to be the same, but still. …

fix: dont set user id into context when its already there

---

hokusai/development.yml
hokusai/templates/docker-compose-service-dev.yml.j2

Follow-up to https://github.com/artsy/metaphysics/pull/5341
Fixes broken [builds](https://app.circleci.com/pipelines/github/artsy/metaphysics/19542/workflows/f5a03efe-b092-402c-a818-b05997961431/jobs/41167?invite=true#step-106-1555_25) as a result of `docker-compose` template change.

fix: incorporate -dev compose template

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/system/__tests__/userRoles.test.ts
src/schema/v2/system/causality_jwt.ts
src/schema/v2/system/index.ts
src/schema/v2/system/userRoles.ts

This is the partner to https://github.com/artsy/gravity/pull/16963. I was able to copy+paste my way to a working response. Feedback welcome.
Unfortunately Causality already exposes a `Role` enum, so I called the new type `UserRole` which sort of matches the few mutations in this area.

feat: expose userRoles at root

---

scripts/push-schema-changes.js

Reverts artsy/metaphysics#5360
Prediction _does_ need an updated copy of Metaphysics' schema, but this automatic push failed with errors like:
```
Error: Command failed: yarn relay
Watchman:  spawn watchman ENOENT
...
error Command failed with exit code 100.
at checkExecSyncError (node:child_process:885:11)
at execSync (node:child_process:957:15)
...
```
`yarn relay` also fails locally with slightly different errors. Until that can be fixed, let's exclude Prediction from this step so Metaphysics can build successfully.

Revert "feat: update prediction mp schema"

---

scripts/push-schema-changes.js

This reverts https://github.com/artsy/metaphysics/pull/5360 and re-adds https://github.com/artsy/metaphysics/pull/5363.
It should only be merged after https://github.com/artsy/prediction/pull/1224, which fixes Prediction's `yarn relay` command.

Revert "Revert "feat: update prediction mp schema""

---

_schemaV2.graphql
src/lib/stitching/gravity/v2/stitching.ts

Exposing `sort` argument in gravity stitching for searchCriteriaConnection
Discovered it was missing [here](https://artsy.slack.com/archives/C05F8TNKGAV/p1698172709479449)

fix: Expose sort argument in gravity stitching for searchCriteriaConnection

---

.eslintrc.json
package.json

I was motivated to create this PR after reading this [comment](https://github.com/artsy/metaphysics/pull/5358#discussion_r1370290136). To simplify the linting process for everyone, we could introduce the ESLint rule `sort-keys`. We can begin with 'warn' first before implementing it as an 'error' to avoid any blockers.

feat: add eslint rule sort-keys

---

.eslintrc.json
_schemaV2.graphql
src/lib/stitching/gravity/v2/stitching.ts

Trivial update to wire up the stitched argument `represented` through to GravityQL

feat(searchCriteriaConnection): Add `represented` argument to field

---

.circleci/config.yml

Not sure how this failure suddenly emerged, but it seems the last LTS version introduced this issue.
[Docs here](https://circleci.com/developer/orbs/orb/circleci/node#jobs-test)
[Before Spin up Environment](https://app.circleci.com/pipelines/github/artsy/metaphysics/19818/workflows/926dd583-8616-48c9-a78b-16fe984c9d12/jobs/41689/parallel-runs/0/steps/0-0)
[After Spin up Environment](https://app.circleci.com/pipelines/github/artsy/metaphysics/19819/workflows/3f164445-1632-47f9-b8fc-745d75143c57/jobs/41694/parallel-runs/0/steps/0-0)

ci: add node version for test job

---

src/index.ts
src/schema/v2/me/__tests__/recentlyViewedArtworks.test.ts
src/schema/v2/me/__tests__/similarToRecentlyViewed.test.ts
src/schema/v2/me/index.ts
src/schema/v2/me/recentlyViewedArtworks.ts
src/schema/v2/me/similarToRecentlyViewed.ts
src/types/graphql.d.ts

This PR is addressing the issues caused by recent changes for braze impersonations.

fix: add improvements for recently viewed artwork ids queries

---

src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/__tests__/searchCriteriaLabel.test.ts
src/schema/v2/me/index.ts
src/schema/v2/searchCriteriaLabel.ts

Addresses [ONYX-472]
This PR adds metric support for the saved search `displayName` and `size` (+ custom size) labels. The metric is retrieved from the user's preferred metric (`me.length_unit_preference`) and defaults to inches.
- This change will apply to [previewSavedSearch](https://github.com/artsy/metaphysics/blob/eb7038505ce95d8d2ad2e69314a7ba016e669da1/src/schema/v2/previewSavedSearch.ts#L1), [savedSearch](https://github.com/artsy/metaphysics/blob/eb7038505ce95d8d2ad2e69314a7ba016e669da1/src/lib/stitching/gravity/v2/stitching.ts#L655) and [savedSearchesConnection](https://github.com/artsy/metaphysics/blob/eb7038505ce95d8d2ad2e69314a7ba016e669da1/src/lib/stitching/gravity/v2/stitching.ts#L667).
- When querying `previewSavedSearch` without a logged-in user, the metric falls back to …

feat: Add metric support to Saved Search display name and labels

---

_schemaV2.graphql
src/data/gravity.graphql
src/lib/stitching/gravity/v2/stitching.ts

MP changes to support deprecation of `high_quality` [concept in Gravity](https://github.com/artsy/gravity/commit/b60db3f2d0b3c345e573d70bb69d15746d773bb9)
This filter is no longer being used by clients and we are marking as deprecated
Assigning myself so I can deploy after gravity goes out

chore: deprecate and remove usage of highQuality filtering concept

---

package.json
scripts/setup.sh

As per https://github.com/artsy/README/pull/530, this updates setup to pull shared configuration from its new, simpler location.

chore: simplify S3 path for shared configuration

---

_schemaV2.graphql
src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/__tests__/searchCriteriaLabel.test.ts
src/schema/v2/previewSavedSearch.ts
src/schema/v2/searchCriteriaLabel.ts

https://artsyproduct.atlassian.net/browse/ONYX-487
Allows `previewSavedSearch` to take a new `artistSeriesIDs` argument and:
- derive artist series’ label data via `previewSavedSearch.labels`
- include artist series in the generated default name via `previewSavedSearch.displayName`
```graphql
{
previewSavedSearch(
attributes: {
artistIDs: ["4e934002e340fa0001005336"], 
artistSeriesIDs: ["kaws-astroboy"]}
) {
displayName
labels {
name
displayValue
field
value
}
}
}
```
```json
{
"data": {
"previewSavedSearch": {
// generated alert name
"displayName": "KAWS — Astroboy",     
"labels": [
{
"name": "Artist",
"field": "artistIDs",
"value": "4e934002e340fa0001005336"
"displayValue": "KAWS",
},
// derived labels with machine and human-friendly data
{
"name": "Artist Series",
"field": …
```

feat(alerts): support artist series in previews and labels

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/alerts.ts
src/schema/v2/artist/__tests__/index.test.js
src/schema/v2/artist/index.ts
src/schema/v2/partner/__tests__/partner.test.js
src/schema/v2/partner/partner.ts

This is built on top of https://github.com/artsy/metaphysics/pull/5409 , so can look at the latest commit for just these changes. It consumes a summary endpoint added in https://github.com/artsy/gravity/pull/17066.
It adds a schema of the form:
```
partner(id: "test-partner") {
alertsSummaryArtistsConnection(first: 10, represented: true) {
edges {
counts {
}
isRecentlyEnabled
topHit {
}
}
node {
name
}
}
}
```
which feels good and can power the summary-view in Volt-V2.

feat: add alertsSummaryArtistsConnection under Partner

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

Realized we need this truth-y filter for /demand (Gravity already supports this, forgot to include here).

chore: add `represented` filter to `alertsSummaryArtistsConnection`

---

_schemaV2.graphql
src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch.ts

Resolves [ONYX-515]
This PR brings a mock structure for the upcoming suggested filters work. We are starting here by returning a mock then we will introduce the logic in the upcoming tickets.
[ONYX-515]: https://artsyproduct.atlassian.net/browse/ONYX-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: introduce mock structure for suggested filters

---

.env.development
hokusai/development.yml

Supports https://artsyproduct.atlassian.net/browse/PHIRE-293
This tweaks the `.env.development` to use docker service name when connecting to gravity and also increments the Memcached port exposed on the host to prevent port collision when `gravity-memcached` service is already running as part of gravity local dev stack.
If needed to use `localhost`, those overrides can go into `.env`.

chore: docker development changes

---

_schemaV2.graphql
src/schema/v2/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch.ts

Resolves [ONYX-520]
This PR adds rarity as a suggested filter. We are getting the most popular rarity for artists based on aggregations. 
**Open questions:**
1. The above logic considers "unique" and "limited edition" as rarities with the same weight. I do however believe that they're not the same and users might be interested in unique works more if both counts are close. I would suggest here to increase the weight of unique artworks to cover for that. Open to other ideas -> Answer: no need for that now
2. Should we consider "Uknown edition" as a valid rarity suggestion? -> Answer: let's remove it
Both questions answered ✅ 
[ONYX-519]: https://artsyproduct.atlassian.net/browse/ONYX-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

feat(ONYX-520): add rarity as a suggested filter

---

_schemaV2.graphql
src/schema/v2/alerts.ts
src/schema/v2/artist/__tests__/index.test.js
src/schema/v2/artist/index.ts

To make things a bit more consistent with the summary schema which includes metadata on the edge, lets use that here as well. This metadata is a bit less compelling to be on the edge from a very pedantic perspective IMO, but we can add it.

feat: move some metadata onto the edge between Alert and Artist nodes

---

_schemaV2.graphql
src/schema/v2/alerts.ts
src/schema/v2/artist/__tests__/index.test.js

Missed this! Update to https://github.com/artsy/metaphysics/pull/5422, which moves count info into `counts`, so that things are aligned with the summary query structure. As future counts are needed, we can continue populating this subfield (also similar to the summary page)

chore(counts): Move `totalUserSearchCriteriaCount` to counts

---

src/schema/v2/__tests__/searchCriteriaLabel.test.ts
src/schema/v2/searchCriteriaLabel.ts

Frontends works with `slugs` instead of `IDs`: when a user filters artworks grid by artist series - `slug` is being added to the filters / alert context. `previewSavedSearch` returns `IDs`, and because of this the logic to remove a pill doesn't work.

fix: previewSavedSearch returns artist series slugs instead of IDs

---

_schemaV2.graphql
src/schema/v2/__tests__/user.test.ts
src/schema/v2/me/__tests__/__snapshots__/update_me_mutation.test.js.snap
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/__tests__/update_me_mutation.test.js
src/schema/v2/me/index.ts
src/schema/v2/me/update_me_mutation.ts
src/schema/v2/user.ts

This PR resolves [EMI-1557]
This PR is a follow-up on artsy/gravity#17116 🔒
This PR adds `receivePartnerOfferNotification` field to the `user` and `me` namespaces to access user preference for push notifications
Request:
```graphql
query {
me {
receivePartnerOfferNotification
}
}
```
Response:
```json
{
"me": {
"receivePartnerOfferNotification": true,
}
}
```
[EMI-1557]: https://artsyproduct.atlassian.net/browse/EMI-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1557): add receivePartnerOfferNotification

---

_schemaV2.graphql
src/schema/v2/artist/index.ts
src/schema/v2/partner/partner.ts

Our standard pagination controls in the connection resolver already do the right thing (ie- prefer `page/size` if specified over connection arguments). This is needed, typically, to let a client UI arbitrarily load any URL of the form `?page=4` (so helps with deep-linking).

chore: support page/size for arbitrary paging in alert connections

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/__tests__/partnerInquirerCollectorProfile.test.ts
src/schema/v2/partner/partnerInquirerCollectorProfile.ts
src/schema/v2/partner/partnerInquiryRequest.ts

This PR unwires the old data loader `partner/${partnerId}/inquiry_request/${inquiryId}/collector_profile` in favor of the new `partner_collector_profile?partner_id=${partnerId}&user_id=${userId}` data loader.
We also expose the new field `hasPartnerFollow`.

feat(DIA-345): wire Inquiry new data loader and expose hasPartnerFollow

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/stitching/gravity/v2/stitching.ts
src/schema/v2/alerts.ts
src/schema/v2/notifications/Item/AlertNotificationItem.ts
src/schema/v2/notifications/Item/ArticleFeaturedArtistNotificationItem.ts
src/schema/v2/notifications/Item/ArtworkPublishedNotificationItem.ts
src/schema/v2/notifications/Item/ShowOpenedNotificationItem.ts
src/schema/v2/notifications/Item/ViewingRoomPublishedNotificationItem.ts
src/schema/v2/notifications/Item/__tests__/index.test.ts
src/schema/v2/notifications/Item/index.ts
src/schema/v2/notifications/index.ts

This implements (more or less, some naming tweaks) the suggested schema in the tech plan - https://www.notion.so/artsy/Schema-for-Single-Notification-Page-9716fa45eee245d5b6def139d8c3d407.
There's no specs (yet), and we should discuss the naming and things like that, so please comment here!
This introduces the `content: NotificationContent` schema under the `Notification` schema brought up in the [tech plan](https://www.notion.so/artsy/Schema-for-Single-Notification-Page-9716fa45eee245d5b6def139d8c3d407).
It allows a richer schema for each notification type to be specified (using a union type), so we can more easily build out a 'single-notification-landing-page' experience.
For instance, when someone lands/clicks/taps on an individual notification based on a viewing room being published …

feat: add new NotificationItem schema

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Partially solves [AMBER-361]
This PR undoes some of the work done in a previous Metaphysics PR: https://github.com/artsy/metaphysics/pull/4412. This is because the `draft` `visibility_level` is being deprecated in Gravity. Moving forward, only the `published` attribute will be the deciding factor of whether an artwork is in draft form or not. `visibility` is only relevant to published works and details how accessible it is, whether it is indexed in Elasticsearch or externally etc.
There are currently no artworks with a visibility_level of `draft` at the moment, however this Gravity PR: https://github.com/artsy/gravity/pull/17175 should be merged first to ensure that it will no longer be possible to avoid any weird states. This PR is also blocked by the following Force PR: …

chore: AMBER-361 - remove draft from visibility enum

---

src/schema/v2/previewSavedSearch/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch/suggestedFilters.ts

https://artsyproduct.atlassian.net/browse/ONYX-604
Based on [this discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1702548068831999?thread_ts=1702492997.351529&cid=C05EQL4R5N0) we are moving the artist series suggestions to be presented after the rarity/medium suggestions.
|Before|After|
|---|---|
|![beforee](https://github.com/artsy/metaphysics/assets/140521/24814e05-7789-4627-9e17-94a74b136046)|![afterr](https://github.com/artsy/metaphysics/assets/140521/a99089b2-861b-436f-bae5-6234e5ad6824)|

fix(alerts): change order of artist series suggestions

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

https://artsyproduct.atlassian.net/browse/EMI-1589
When an Artwork has the price hidden, the `listPrice` field is not reliable, so we need to expose the actual `price_listed`.
This field will be used for discount calculations, so we need it as Float, for displaying the price, we already have `internalDisplayPrice` doing the formatting.
Example where the artwork has the price hidden:
```
{
"node": {
"internalDisplayPrice": "$123",
"priceListed": 123,
"listPrice": null
}
}
```
Note: you may need to set `"shallow": false` for it to appear on certain endpoints.

feat(EMI-1589): expose Artwork#price_listed field as Float

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/alerts.ts
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts

Opening this a tad early, still need to add some specs.
Looks like:
This adds `alert` and `alertsConnection` under `Me` -> corresponding to the following currently being stitched in: https://github.com/artsy/metaphysics/blob/edc18163c18e5d83f3281987078da791318ba521/src/lib/stitching/gravity/v2/stitching.ts#L130-L131
This also adds `artistsConnection` to `Alert` -> corresponding to the following currently being stitched in: https://github.com/artsy/metaphysics/blob/edc18163c18e5d83f3281987078da791318ba521/src/lib/stitching/gravity/v2/stitching.ts#L160
Still to do:
- Need to add the CRUD mutations. This _should_ be relatively straightforward.
- Need to support the following fields on `Alert`, currently being stitched in to `SearchCriteria`: …

feat: add `alert` and `alertsConnection` under `Me`

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/artwork/index.ts

This PR adds a new partner offers connection to the artworks connection edge. This will allow partners to query the partner offers that have been made on an artwork.

feat: allow clients to query an artwork's last partner offer (EMI-1617)

---

_schemaV2.graphql
src/schema/v2/image/index.ts

> [!NOTE]
> This PR is part of [#hack13-blurhash](https://artsy.slack.com/archives/C06E4ND6EBV) 🔒
This PR adds the blurhash field into the Image type
Query:
```graphql
query() {
artwork(id: "xyz") {
image {
blurhash
}
}
}
```
Result:
```json
{
"data": {
"artwork": {
"image": {
"blurhash": "xxxxx"
}
}
}
}
```

feat(H13): Add blurhash field to Image type

---

src/schema/v2/partner/partner.ts

This PR adds the incoming `sort` param to the `partner/:id/artworks/all` query when a query on Partner.artworksConnection includes `shallow: false`.

fix: preserve sorting when requesting non-shallow partner.artworkConnection properties

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

Part of [EMI-1649]
This PR removes the deprecated `savedAtLeastOnce` argument from the `partner.artworksConnection` field. The only usage of this field was removed from [here](https://github.com/artsy/volt-v2/blame/b7ac9d15792ab44d8edd101f685c449efa3afb9d/src/pages/send-offers/components/SavedArtworksTable.tsx#L160) in artsy/volt-v2#117.
[EMI-1649]: https://artsyproduct.atlassian.net/browse/EMI-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove savedAtLeastOnce arg from partner.artworksConnection

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

Pagination of the CMS send offers table only works when navigating client-side (e.g. by clicking on the paginator), but does not work when visiting the URL with params directly (e.g. https://cms-staging.artsy.net/send-offers?page=12 ) or refreshing the page. It seems the page param was ignored and it always fetches the first page.
This will enable pagination using query string and allow volt-v2 to use url params to navigate to the page correctly.

feat(EMI-1623): expose page arg for Partner#artworksConnection

---

_schemaV2.graphql
package.json
src/schema/v2/image/__tests__/index.test.js
src/schema/v2/image/index.ts
yarn.lock

This supports returning a `blurhashDataURI` for an image where a `blurhash` is available.
I'm not sure about the right parameters re: what kind of dimensions the blurred image should be - presumably we can have a 'small' blurred placeholder (like 64px wide as the default for instance), which will look acceptable when scaled 'up' in the artwork grid. But, for the artwork page we might want a larger placeholder blurred image, so left `width` as an argument.
We can probably iterate on those exact settings (esp if we wind up going with a Force review app or feature flag for the front-end expression of this).

feat: support blurhashDataURI for Image

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfile.ts

Resolves [DIA-398]
Exposes inquiry requests count on the collector profile.
[DIA-398]: https://artsyproduct.atlassian.net/browse/DIA-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(DIA-398): Expose inquiry requests count on collector profile

---

_schemaV2.graphql
src/schema/v2/image/__tests__/index.test.js
src/schema/v2/image/index.ts

As pointed out by @anandaroop we should roll with 'url' naming!

chore: rename blurhashDataURI to blurhashDataURL

---

_schemaV2.graphql
src/lib/stitching/exchange/__tests__/stitching.test.ts
src/lib/stitching/exchange/v2/stitching.ts
src/schema/v2/conversation/collectorResume.ts
src/schema/v2/conversation/index.ts

This PR stitches the Exchange's buyerActivity to collectorResume.
Follow-up to: 
- https://github.com/artsy/exchange/pull/1995 
- https://github.com/artsy/metaphysics/pull/5539
Ticket [DIA-368]
[DIA-368]: https://artsyproduct.atlassian.net/browse/DIA-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add buyerActivity to collectorResume

---

src/schema/v2/partner/partner.ts

While doing https://github.com/artsy/volt-v2/pull/1141, I noticed that if a page number that is 1 more than the maximum page number is given, it would still return some data when it should return an empty array.
I am not sure why this is happening but forcing a return when the `artworkIds` is empty solved the issue.
I've checked Gravity and it is returning the expected empty array, so there's is something wrong with Metaphysics pagination helpers.
Check slack thread for more context: https://artsy.slack.com/archives/CP9P4KR35/p1706528000848069
Relates to: https://github.com/artsy/volt-v2/pull/1141

fix(EMI-1623): force an empty return if there are no artwork IDs

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts
src/schema/v2/artworkResult/__tests__/index.test.ts
src/schema/v2/artworkResult/index.ts
src/schema/v2/fields/requestError.ts
src/schema/v2/schema.ts

This is an alternate approach to https://github.com/artsy/metaphysics/pull/5523 , and tbh I like this one a lot better.
This elevates our `orError` pattern (from mutations), to actual fields - better allowing us to handle errors in a first-class way, vs. trying to use the basic `errors` key in the GraphQL response, or custom `extensions`.
This way, the artwork page/screen query can start to look like:
``` graphql
artwork(id: "...") {
... on Artwork {
...ArtworkApp_artwork
}
... on ArtworkError {
...ArtworkErrorApp_artworkError
}
}
```
with a partial artwork schema being available in the error case (now that https://github.com/artsy/gravity/pull/17283 is merged).
Looks like - 
What do y'all think?

feat: add artworkResult root field for first-class error handling

---

_schemaV2.graphql
src/schema/v2/artworkResult/__tests__/index.test.ts
src/schema/v2/artworkResult/index.ts

Little one, nice to have these identifiers as first-class on the partial artwork 'error' response.

chore: add internalID and slug to PartialArtwork

---

src/schema/v2/artworkResult/__tests__/index.test.ts
src/schema/v2/artworkResult/index.ts

This was an odd one!
Before this change, an owner logged in viewing an unpublished artwork, would still be served the new error page!
Since I think we need to support unpublished artworks resolving properly with a 200 and normal artwork page to owners, instead of checking `published`, let's check if we got a 'full response', which would indicate this is an owner who should resolve the full type.

fix: allow owners accessing unpublished artworks to resolve fully

---

_schemaV2.graphql
src/schema/v2/__tests__/createPartnerOfferMutation.test.ts
src/schema/v2/createPartnerOfferMutation.ts

The table in "Send Offers" page in volt-v2 needs to be refreshed when the user performs an action. Instead of hard reloading the page, @damassi suggested to use relay fragments to reload the affected rows. This approach is only possible if we include the `partner` type in the mutation payload.
See slack thread for more context https://artsy.slack.com/archives/C02JHHHKP5K/p1706106297053579
Relates to https://github.com/artsy/volt-v2/pull/1153

feat(EMI-1618): return partner on createPartnerOfferMutation

---

src/schema/v2/artworkResult/__tests__/index.test.ts
src/schema/v2/artworkResult/index.ts

Just a little cleanup. Switches a check (to see if there was a full artwork response or not) to be more imperative, rather than inferring from the response.

chore: add a comment + small cleanup in artworkResult

---

src/schema/v2/artworkResult/__tests__/index.test.ts
src/schema/v2/artworkResult/index.ts

After https://github.com/artsy/gravity/pull/17300 added `partner_id`, we can inject that in and have access to the 'Other Works by Partner' section.

chore: resolve a `partner`in PartialArtwork

---

_schemaV2.graphql
src/schema/v2/edition_set.ts

The current price fields in the EditionSet type (`listPrice`, `internalDisplayPrice` and `price`)  can't be used for integer calculations without too much trouble converting them.
Similar to https://github.com/artsy/metaphysics/pull/5497 where we exposed the `Artwork#price_listed` field, which is more reliable for discount calculations and https://github.com/artsy/pulse/pull/1827, which used the `EditionSet#price_listed` field to display the price in emails, we need to expose this in the EditionSet Type so we can use it in volt-v2 for discount calculations for artworks with edition sets.
<details><summary>Example payload</summary>
<p>
```
query ArtworksConnection($partnerId: String!, $first: Int,$sort: ArtworkSorts, $shallow: Boolean, $partnerOfferable: Boolean) {
partner(id: $partnerId) …
```

feat(EMI-1641): expose EditionSet#priceListed for offer discount calculations

---

src/lib/stitching/exchange/link.ts

This PR enables request [from Impulse](https://github.com/artsy/impulse/pull/1110) to be proxied to Exchange.

feat: pass through the app token for exchange

---

hokusai/production.yml

In [this discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1707146887579779), we determined that Metaphysics capacity is the limiting factor in gracefully handling the high volume of requests sometimes sent by Braze. During these floods, the upstream services like Gravity and Vortex receive a large volume of requests, but seem to handle them fine.
We've identified a few _other_ steps to take (especially: limiting the rate via Braze's configuration, and caching the back-fill artworks that ~half of these queries load), but in the meantime I don't see any harm in increasing Metaphysics' maximum scale. Here, I somewhat arbitrarily raise it by 25%. What do you think?

chore: allow deployment to scale up further, to better handle internal floods of requests

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfile.ts

Exposes the new `saved_artworks_count`, `followed_artists_count`, `collected_artworks_count`, and `total_bids_count` fields on the collector profile.

chore: Expose collector profile counts

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfile.ts

This is to get at the `interestsConnection` on the `UserType`.
The existing `userInterests` field on the collector profile only fetches for the logged in user and isn't a connection type anyway.
We'll need to add filtering options to the `interestsConnection` once that's done in Gravity.

fix(collectorprofile): exposes owner field

---

_schemaV2.graphql
src/schema/v2/me/markNotificationsAsSeenMutation.ts
src/schema/v2/me/mark_all_notifications_as_read_mutation.ts
src/schema/v2/me/mark_notification_as_read_mutation.ts

* [ONYX-750](https://artsyproduct.atlassian.net/browse/ONYX-750)
In order to update the notification read count, this PR updates all Notification mutations to return `me`. This should allow us to update `unreadNotificationsCount` automatically in the Relay store when notifications are marked as read without manipulating the store imperatively ([example](https://github.com/artsy/force/blob/29a650d2548a31325e8d507acdfa12d7c27ca425/src/Components/Notifications/Mutations/markNotificationsAsSeen.ts#L11))
```graphql
mutation {
markNotificationAsRead(input: { id: "feed_id" }) {
... on MarkNotificationAsReadSuccess {
me {
unreadNotificationsCount
}
success
}
}
}
}
```
[ONYX-750]: https://artsyproduct.atlassian.net/browse/ONYX-750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …

feat: Return `me` from notification mutations

---

_schemaV2.graphql
src/schema/v2/Alerts/index.ts
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/previewSavedSearch/generateDisplayName.ts
src/schema/v2/previewSavedSearch/previewSavedSearch.ts
src/schema/v2/previewSavedSearch/searchCriteriaLabel.ts

[Ticket](https://artsyproduct.atlassian.net/browse/ONYX-729)
We need this PR to support upcoming design changes. Notice that alerts list has artist names as titles and the rest of criteria as subtitles on the next lines:
```graphql
query X {
me {
alert(id: "143292") {
displayName
title: displayName(only: [artistIDs])
subtitle: displayName(except: [artistIDs])
}
}
```
returns
```json
{
"data": {
"me": {
"alert": {
"displayName": "Damien Hirst — Painting, Limited edition",
"title": "Damien Hirst",
"subtitle": "Painting, Limited edition"
}
}
},
}
```

feat(onyx-729): alert.displayName allows querying artist name and the rest of criteria separately

---

_schemaV2.graphql
src/schema/v2/Alerts/index.ts
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts

Couple of little updates that made Force non-stitched alerts work more smoothly re: types, plus the sort support

chore: add a `sort` to `alertsConnection` and tighten up some types

---

_schemaV2.graphql
src/schema/v2/Alerts/index.ts
src/schema/v2/me/__tests__/index.test.ts

[Ticket](https://artsyproduct.atlassian.net/browse/ONYX-730)
We need to query alert's artworks in a few placed. Currently, we fetch search criteria first and then pass them to `filterArtworksConnection` as arguments. This PR adds support to query artworks easier, via `alert.artworksConnection`.
```graphql
query X {
me {
alert(id: "143292") {
counts {
total
}
edges {
node {
title
}
}
}
}
}
}
```
produces:
```json
{
"data": {
"me": {
"alert": {
"counts": {
"total": 1
},
"edges": [
{
"node": {
"title": "The Hours Spin Skull"
}
}
]
}
}
}
}
}
```

feat(onyx-730): add alert.artworksConnection field

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/unleash.ts
src/schema/v2/admin/index.ts
src/schema/v2/admin/mutations/createFeatureFlagMutation.ts

Noticed that creating feature flags was (kinda) broken in forque (would create, but on create it couldnt find the flag), and we needed to update the api path slightly.

fix(feature-flags): fix feature flag creation responses

---

_schemaV2.graphql
src/schema/v2/admin/featureFlags.ts
src/schema/v2/admin/index.ts

A little more cleanup here, particularly with variants being able to be null. And when fetching an individual FF, we need an ID for relay.

fix(feature-flags): Remove non-null on Variants

---

_schemaV2.graphql
src/schema/v2/me/__tests__/createCollectionMutation.test.ts
src/schema/v2/me/collection.ts
src/schema/v2/me/createCollectionMutation.ts

Make `shareable_with_partners` available as a not required param for Collections creation. 
Followup from https://github.com/artsy/gravity/pull/17388
**Param not given**

feat(EMI-1710, EMI-1711): add shareableWithPartners to Collections

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

@gkartalis found [this error](https://app.datadoghq.com/apm/services/metaphysics.graphql/operations/graphql.execute/resources?env=production&fromUser=false&graphType=flamegraph&groupMapByOperation=null&panels=qson%3A%28data%3A%28resource%3A%28resourceName%3Aquery%2520ArtworkAboveTheFoldQuery%2528%2524artworkID%253AString%2521%2529%257Bartwork%2528id%253A%2524artworkID%2529%2540principalField%257Bid...Artwork_artworkAboveTheFold%257Dme%257Bid...Artwork_me%257D%257Dfragment%2520ArtworkActions_artwork%2520on%2520Artwork%257BheightCm%2520id%2520image%257Burl%257DisHangable%2520sale%257Bid%2520isAuction%2520isClosed%257Dslug%2520widthCm...ArtworkSaveButton_artwork%257Dfragment%2520ArtworkAuctionBidInfo_artwork%2520on%2520Artwork%257BmyLotStanding%2528live%253Atrue%2529%257BactiveBid%257Bid%2520 …

fix Gene Not Found error when calling artwork.savedSearch.suggestedArtworksConnection

---

_schemaV2.graphql
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/me/index.ts
src/schema/v2/previewSavedSearch/previewSavedSearch.ts

[Context for this PR](https://github.com/artsy/gravity/pull/17398)
Adds support for filtering alerts by search criteria attributes:
```graphql
query X {
me {
email
alertsConnection(first: 1, attributes: { artistIDs: ["kaws"], acquireable: true }) {
edges {
node {
displayName
}
}
}
}
}
```

feat: allow querying alerts by search criteria

---

_schemaV2.graphql
src/schema/v2/conversation/index.ts

`interetsConnection` is not fully working with Relay pagination when under `CollectorProfileType`, this PR moves it and renames it for better understanding to the `Conversation` type.

feat(collectorInterestsConnection): move collectorInterestsConnection to the Conversation type

---

_schemaV2.graphql
src/lib/stitching/exchange/v2/stitching.ts
src/schema/v2/conversation/collectorResume.ts
src/schema/v2/conversation/index.ts
v2

This PR addresses the calculation of non-BNMO purchases and combines them with BNMO purchases from Exchange.
Please find related Gravity PR [here](https://github.com/artsy/gravity/pull/17444).
[DIA-503]
[DIA-503]: https://artsyproduct.atlassian.net/browse/DIA-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add non bnmo purchases to CollectorResume buyerActivity

---

_schemaV2.graphql
src/schema/v2/conversation/message.ts

This updates our schema to account for `sentAt`, so we can distinguish between messages sent on platform or via email. 
This will help us distinguish when we need to make wide conversation bubbles in Convos clients in partner / collector apps.

feat(messages): Add sentAt and messageSentOnPlatform

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/vortex.ts
src/lib/loaders/loaders_without_authentication/vortex.ts
src/schema/v2/artworksForUser/__tests__/artworksForUser.test.ts
src/schema/v2/artworksForUser/__tests__/helpers.test.ts
src/schema/v2/artworksForUser/artworksForUser.ts
src/schema/v2/artworksForUser/helpers.ts

There is existing code to support the current recs + backfill w/ some helpers. That code generally winds up being pretty different than what we want for auction lot recommendations (different backfill methodology, using Vortex GraphQL instead of REST), so the general approach here was to add the new argument (`includeAuctionArtworks`), and thread it through to the two helpers used (fetching artwork id's from Vortex, and fetching backfill works if required), and branch there.

feat: add support for auction lot new-for-you recommendations

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

This updates our schema with a new `isUnlisted` field on artwork:
```graphql
{
artwork(id: "foo") {
isUnlisted
}
}
```

feat(artwork): Add isUnlisted to artwork schema

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/me/__tests__/updateCollectionsMutation.test.ts
src/schema/v2/me/updateCollectionsMutation.ts
src/schema/v2/schema.ts

Port the work done at https://github.com/artsy/gravity/pull/17431 to metaphysics.
Example request for reference:
```
mutation {
updateMeCollectionsMutation(
input: {
attributes: [
{
id: ""
shareableWithPartners: false
},
{
id: ""
shareableWithPartners: true
},
]
}
) {
meCollectionsOrErrors {
... on UpdateMeCollectionsSuccess {
collection {
id
shareableWithPartners
name
artworksCount
}
}
... on UpdateMeCollectionsFailure {
type
message
}
}
}
}
}
```
Successful request
Failed request

feat(EMI-1727): create updateCollectionsMutation

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Fairly vanilla - adds a `listedArtworksConnection` field to `Artwork`, which will return a connection of [commercial] artwork listings based on a given artwork (specifically, a consigned/MyCollection artwork).

feat: add listedArtworksConnection on Artwork

---

src/schema/v2/Alerts/index.ts
src/schema/v2/me/__tests__/index.test.ts

There is a mismatch between the artworks user sees in the new "View artworks" screen and when navigating to the artworks grid when clicking "See all matching works" button. This happens because "View artworks" screen uses `alert.artworksConnection` field witch lacks `for_sale` attribute. This PR adds the missing attribute.
Demo of the bug (notice 22 artworks before and 11 after):
<video src="https://github.com/artsy/metaphysics/assets/3934579/bc62a8ec-7262-444e-af67-8557cfcabf8f" />

fix: alert.artworksConnection shows only for sale artworks

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

This to follow up on discussion from https://github.com/artsy/eigen/pull/10008 as I'm about to add this display to Artwork page with offer.
I also followed the logic of price display from saleMessage as that is what we want I believe to match how the artwork price is displayed on the Artwork page when offer is not present except that we always want to return the price if it's available if the work has a publicly available price.

feat: add priceListedDisplay to Artwork that always returns display for price if it's publicly available)

---

_schemaV2.graphql
src/schema/v2/me/updateUserInterestMutation.ts
src/schema/v2/userInterests.ts

Because, for reasons that escape me, a `UserInterest` is modeled in two different ways: as a node `UserInterest` and as an edge `UserInterestEdge`, when you perform a mutation you can't update the UI because when you fetch user interests you get the edge type and this mutation returns the node type.
This lead the implementation in Eigen to use a completely separate data store from Relay. We do not want to do that in Force, so here we just return the edge type in addition. This is deeply ugly but works fine.

fix(userinterests): returns edge type to support updating ui

---

src/lib/loaders/loaders_with_authentication/gravity.ts

patches #5642. The `saleAgreementLoader` needs to pass an `X-ACCESS-TOKEN` to authorize access to unpublished agreements. This was mistakenly removed from a previous [revert](https://github.com/artsy/metaphysics/pull/5642/commits/5711a2351957f2e20ccd25cd2f0b04ec50043794).

fix: add saleAgreementLoader to gravity auth loaders

---

scripts/push-schema-changes.js

This fixes a regression that was introduced in https://github.com/artsy/metaphysics/pull/5502, where we were simplified how we handle graphql schema syncing over in Volt. Unfortunately, this doesn't account for artemis, our server-side graphql client. So now we're restoring the old command (while retaining the new addition from #5502, since we need both types.

fix(schema-sync): Update schema sync to also push .json format

---

src/schema/v2/user.ts

Related to: https://github.com/artsy/gravity/pull/17584 and [ONYX-898](https://artsyproduct.atlassian.net/browse/ONYX-898)
I _think_ this is all that's required? Locally, queries such as:
```graphql
query {
user(email:"joey@example.com") {
myCollectionArtworksConnection(first: 10) {
edges {
node {
submissionId
}
}
}
}
}
```
...now include internal properties like `submissionId`. [The only references](https://github.com/search?q=org%3Aartsy%20myCollectionArtworksConnection&type=code) to this `user.myCollectionArtworksConnection` schema are from Forque, which [makes the corresponding view available](https://github.com/artsy/forque/blob/0b5d3129da192dd3dd4901a994329a1fe41d271c/src/system/index.ts#L56) only to `customer_support` users.
[ONYX-898]: …

feat: request more MyCollection artwork properties from privileged contexts (ONYX-898)

---

_schemaV2.graphql
src/schema/v2/artist/index.ts
src/schema/v2/artist/updateArtistMutation.ts

This PR enables the `criticallyAcclaimed`, `vanguardYear`, and `awards` fields to be used as input for updateArtist mutation.
[Gravity PR](https://github.com/artsy/gravity/pull/17582)

feat: enable more artist insight fields for update

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/image/normalize.ts
src/schema/v2/me/__tests__/notification.test.ts
src/schema/v2/notifications/index.ts

Resolves [ONYX-780]
This PR adds a `previewImages` field to the `Notification` type that returns preview images depending on the activity type. The new field is intended to replace [this](https://github.com/artsy/eigen/blob/604593ef797f62c403398d621b5e77202ad8e406/src/app/Scenes/Home/Components/ActivityRailItem.tsx#L178) function in Eigen and be used in Force and Eigen in the Activity Panel.
[ONYX-780]: https://artsyproduct.atlassian.net/browse/ONYX-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add previewImages field to Notification type

---

src/schema/v2/artworksForUser/__tests__/helpers.test.ts
src/schema/v2/artworksForUser/helpers.ts

This reverts commit 0a2016c6415cc65ebd9ad40272257cc874611a39.
This should solve this [bug feedback](https://artsy.slack.com/archives/C03N12SR0RK/p1713280359576229)
I've executed this query (key part is `onlyAtAuction: true`):
```graphql
artworksForUser(includeBackfill: true, first: 20, onlyAtAuction: true) {
edges {
node {
slug
}
}
}
```
and get:
```
"message": "https://stagingapi.artsy.net/api/v1/filter/artworks?exclude_disliked_artworks=true&marketing_collection_id=top-auction-lots&size=20&sort=-decayed_merch - {\"type\":\"access_error\",\"message\":\"Can not access user-only field.\",\"detail\":{\"exclude_disliked_artworks\":[\"Can not access user-only field.\"]}}",
```
I will look for a proper fix later, for now simply reverting this change because no client relies on new …

Revert "feat(onyx-886): exclude disliked artworks from artworksForUser recommendations (#5658)"

---

_schemaV2.graphql
src/schema/v2/artist/index.ts
src/schema/v2/artist/updateArtistMutation.ts

This PR resolves and enables the `recent_show` field to be used as input for updateArtist mutation.
[Gravity PR](https://github.com/artsy/gravity/pull/17602)

feat: add recent_show for managing artist insights

---

src/schema/v2/artworksForUser/__tests__/helpers.test.ts
src/schema/v2/artworksForUser/helpers.ts

Initial description of a problem is here: https://github.com/artsy/metaphysics/pull/5658
After releasing ☝️ we discovered a bug - metaphysics was sending a non-authenticated request to `/filter/artworks` endpoint with a new `exclude_disliked_artworks=true` parameter. Earlier, thanks to @joeyAghion's suggestion, I made this parameter `user_only` in Gravity, which makes Gravity fail with `Can not access user-only field` error when it's requested without a user. The fact that Gravity crashes was very fortunate - otherwise I would probably not spot that artworks returned by `filter/artworks` endpoint contain disliked artworks.
This PR reverts a revert (https://github.com/artsy/metaphysics/pull/5668) and also switches to authenticated requests.

feat(onyx-886): exclude disliked artworks from artworksForUser recommendations

---

_schemaV2.graphql
src/schema/v2/artworksForUser/__tests__/artworksForUser.test.ts
src/schema/v2/artworksForUser/__tests__/helpers.test.ts
src/schema/v2/artworksForUser/artworksForUser.ts
src/schema/v2/artworksForUser/helpers.ts

This PR adds `excludeDislikedArtworks` option to `artworksForUser`. We have some concerns about performance of non-cached personalised calls to `/filter/artworks` endpoint (to exclude disliked artworks we have to make user-authenticated call to gravity).
When `excludeDislikedArtworks` is `false` - we continue using unauthenticated filter artworks loader - otherwise authenticated one.
New option is `false` by default, and only clients (Force / Eigen) will set it to `true` initially. When (if) we feel confident that `artworksForUser` query can handle Braze's load - we can set this option to true by default.

add excludeDislikedArtworks option to artworksForUser

---

src/lib/loaders/loaders_without_authentication/gravity.ts

This should resolve the reported issue where logged-out users (on Force) weren't able to access the listing of sale agreements.

fix: add saleAgreementsLoader to logged-out gravity loaders

---

src/schema/v2/notifications/__tests__/index.test.ts

This works to fix the faily test _right now_ locally and in CI. Who knows what tomorrow brings.

fix: time zone-sensitive test failures

---

src/schema/v2/artworksForUser/__tests__/artworksForUser.test.ts
src/schema/v2/artworksForUser/__tests__/helpers.test.ts
src/schema/v2/artworksForUser/artworksForUser.ts
src/schema/v2/artworksForUser/helpers.ts

It [surfaced](https://artsy.slack.com/archives/C03N12SR0RK/p1713280359576229) that duplicates appear in auction recommendations, where personalized and back-fill items are concatenated together. This is understandably more common among auction lots, where there's a relatively small universe of live auction lots at any time. This PR tries to filter duplicates out.
I made some guesses and have some questions, so I'll ask them inline. Thanks for bearing with me while I get familiar!
https://artsyproduct.atlassian.net/browse/ONYX-899

fix: avoid duplicates in back-filled recommendations (ONYX-899)

---

src/schema/v2/me/index.ts

This count is used during onboarding, and so can be requested on many different pages. We've seen some evidence that fetching the total count and paginating the collection w/ `total_count: true` can be slow for power users.
Rather than un-pack some of the complexity involved there - let's isolate our attention to _just_ this count field, which as part of onboarding gets queried often, and so might give us some bang for our buck here, even if we aren't touching any _other_ places `savedArtworks` are paginated w/ `total_count: true`.
Since fetching the collection already returns a `visible_artworks_count` 'live' query - https://github.com/artsy/gravity/blob/42969a41ba98a3b8adc860677be5ab05d62a21b1/app/models/domain/collection.rb#L242 - let's use it here. It should be faster than the current …

chore: switch savedArtworks count to return the value from the Collection

---

_schemaV2.graphql
src/schema/v2/artist/index.ts

Adds partnerProvidedBiography field to Artist, originally we wanted to use `biographyBlurb` provided function but it only returns the partner provided bio for `featured` partner artists, see [here](https://github.com/artsy/metaphysics/blob/bf5f37c86646adbbe2c68c464bf69e9add480ad9/src/schema/v2/artist/index.ts#L495)
We need a more flexible solution for our new private artworks experience
```graphql
{
artist(id: "662664897e9e2b00073fae7d") {
partnerBiographyBlurb {
text
}
biographyBlurb {
text
}
}
}
```

feat: Adds partnerProvidedBiography field to Artist

---

src/schema/v2/artist/__tests__/index.test.js

Fast follow Just wanted to test the case when PartnerArtist bio is `null` in case of 💥 
https://github.com/artsy/metaphysics/pull/5693

chore: adding some additional specs for new Artist field

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/CollectorProfile/partnerEngagement.ts

Now that we have some newer data points in https://github.com/artsy/gravity/pull/17626 and https://github.com/artsy/gravity/pull/17625 , I decided to get a stake in the ground on trying to add these concepts to `CollectorProfile`. I decided to go with `partnerEngagement(partnerID: ID!): PartnerEngagement` (as these are partner-specific) and include all these properties.
For now just these counts are being exposed, and it's very much a WIP (for instance - maybe we should just combine all of these into a single API call, they're arbitrarily split up now). This `PartnerEngagement` type is where we could also add the `userIntroduction` natural-language sentence, although in the designs I saw there was still room to present some of these headline counts.
Looks like-
What do we think?

feat: add partnerEngagement to CollectorProfile

---

src/schema/v2/me/index.ts

For the count to come back if the collection is private, we need to always include this param.

fix: include private=true param for savedArtworks count

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/me/__tests__/collector_profile.test.js

Just to get something in here to iterate on! It is static and pretty boring to start.
I did add a required `partnerID` argument as it seems as though this sentence will be partner-aware or partner-specific, we can relax this if needed.

feat: add a summarySentence on CollectorProfile

---

scripts/push-schema-changes.js

Reverts artsy/metaphysics#5655
This implementation has the effect of blowing away the updates to the `graphql` file from the previous step in this configuration, so reverting this for now.

Revert "fix(schema-sync): Update schema sync to also push .json format"

---

scripts/setup.sh

This switches to `asdf` as the default version manager for node, as per https://github.com/artsy/README/pull/505.
Like in https://github.com/artsy/force/pull/13834, I left the `.nvmrc` file in place as a convenience for developers that haven't yet made the switch.

chore: switch from nvm to asdf

---

src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/me/__tests__/collector_profile.test.js

Related to [DIA-561]
This PR is related to `CollectorProfile#isProfileComplete` and changes:
- removes `bio` from the gauge
- adds `icon` to the gauge
So far this prop has been used by Eigen, so with this change, we don't expect any super weird stuff in the current Edit profile screen.
[DIA-561]: https://artsyproduct.atlassian.net/browse/DIA-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-561): use icon to check collector profile completion and remove bio from it

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts

[Jira ticket](https://artsyproduct.atlassian.net/browse/ONYX-897).
From the ticket:
> [Force](https://github.com/artsy/force/blob/e64ac8ce6881c2200aa56cc1d32c72d0cbbdfbb8/src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx) and [Eigen](https://github.com/artsy/eigen/blob/addcd491a72c01cf41458b81929d993a48b21711/src/app/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkSubmissionStatus.tsx) display a colorful description of the submission state, along with some help text. There’s some duplication, and in the case of “approved” submissions, the help text is misleading (“determined that we do not currently have a market for it”).
When pairing with @joeyAghion we agreed that it feel awkward to specify palette colors in …

feat(onyx-911): consignment submission state info

---

.vscode/settings.json
_schemaV2.graphql
scripts/push-schema-changes.js
src/schema/v2/artists.ts

Attempting to fix issue noted in this [revert PR here](https://github.com/artsy/metaphysics/pull/5713). 
The fix is converting the `dest` argument to an array rather than a string, and then allowing the ability to pass multiple output destinations _per repo_. With this in place we no longer clobber the previous git push in the array of repos, but rather perform two operations if necessary (as is the case with volt, where we need to output two different schema types).

feat(sync-schema): Update schema sync to also account for Artemis - Take 2

---

src/schema/v2/image/__tests__/index.test.js
src/schema/v2/image/index.ts

This PR is a follow-up on https://github.com/artsy/metaphysics/pull/5722
Since the SEO issue is related to Web, I figured out why not keep this enabled on App. Please let me know what you think.

chore: enable blurhashes on Eigen

---

_schemaV2.graphql
src/schema/v2/artist/index.ts

Marks unused partnerBiographyBlurb field as deprecated from artist schema
It was not used and perhaps we need to devise a different solution for our needs as per the discussion https://github.com/artsy/metaphysics/pull/5693#discussion_r1579434764
https://github.com/artsy/metaphysics/pull/5693
As per [here](https://github.com/artsy/metaphysics/pull/5721/files), eigen stores a reference to this field in certain versions so it is not safe to just directly remove

chore: deprecate partnerBiographyBlurb field from artist schema

---

src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/artist/__tests__/helpers.test.ts
src/schema/v2/artist/__tests__/insights.test.ts
src/schema/v2/artist/helpers.ts
src/schema/v2/artist/insights.ts
src/schema/v2/me/__tests__/myCollectionInfo.test.ts
src/schema/v2/me/myCollectionInfo.ts

This PR introduces the `artist_career_highlights` endpoint used for retrieving artist insights (institutions) for solo, group, venues collected by major institutions.
[Gravity PR](https://github.com/artsy/gravity/pull/17668)

feat: use artist career highlights for artist insights

---

_schemaV2.graphql
src/schema/v2/conversation/conversations.ts
src/schema/v2/me/__tests__/conversations.test.js

This PR adds the `totalCount` field back into the `conversationsConnection` so that the total number of conversations between a collector and a gallery can be displayed in that collector's profile in CMS.

feat: add total count to conversations connection

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/artist/__tests__/careerHighlights.test.ts
src/schema/v2/artist/careerHighlights.ts
src/schema/v2/artist/index.ts
src/schema/v2/careerHighlight/__tests__/createCareerHighlightMutation.test.ts
src/schema/v2/careerHighlight/__tests__/deleteCareerHighlightMutation.test.ts
src/schema/v2/careerHighlight/__tests__/updateCareerHighlightMutation.test.ts
src/schema/v2/careerHighlight/careerHighlight.ts
src/schema/v2/careerHighlight/createCareerHighlightMutation.ts
src/schema/v2/careerHighlight/deleteCareerHighlightMutation.ts
src/schema/v2/careerHighlight/updateCareerHighlightMutation.ts
src/schema/v2/schema.ts

[DIA-632](https://artsyproduct.atlassian.net/browse/DIA-632)
This PR adds the mutation for managing artist career highlights.
[Forque PR](https://github.com/artsy/forque/pull/1187)
[DIA-632]: https://artsyproduct.atlassian.net/browse/DIA-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add artist career highlights mutations

---

_schemaV2.graphql
src/lib/stitching/exchange/v2/stitching.ts

Intersected this in the orders app rebuild in volt. In order to support our modern relay pagination patterns, we need to be able to access root fields from `Viewer`. Normally this is easy to add (just [add the type](https://github.com/artsy/metaphysics/blob/main/src/schema/v2/schema.ts#L351) to `rootFields`, and `Viewer` automatically picks it up -- no work necesary), however with orders we're stitching from exchange, so one has to do the annoying SDL stitching dance.  

feat(exchange): Extend viewer with commerceOrders exchange field

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

This PR resolves part of [EMI-1881]
This PR adds a new field to the Artwork type
The new field is called `offerableActivityCount`, and it's the count of collectors who have eligible offerable activity on a the current artwork
Request
```graphql
query {
artwork(id: "XYZ") {
offerableActivity {
totalCount
}
}
}
```
Response:
```json
{
"data": {
"artwork": {
"offerableActivity": {
"totalCount": 2
}
}
}
}
```
[EMI-1881]: https://artsyproduct.atlassian.net/browse/EMI-1881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1881): Add offerableActivityCount to artwork

---

_schemaV2.graphql
src/schema/v2/artwork/artworkVisibility.ts
src/schema/v2/artwork/index.ts
src/schema/v2/partner/partner.ts

Reported internally: private artworks were not being returned in the partner artworksConnection call that powers Folio views
The associated gravity endpoint allows for clients to [request certain visibility levels ](https://github.com/artsy/gravity/blob/main/app/api/v1/partners_artworks_endpoint.rb#L131)and returns the correct artworks if the user has access to view them ([partner user vs collector user for example](https://github.com/artsy/gravity/blob/main/app/api/v1/partners_artworks_endpoint.rb#L173-L175))
<details>
<summary>Query Example</summary>
```graphql
{
artworksConnection(first: 100, artistID: "6648c2ecbdb841000701ee77", visibilityLevels: ["listed", "unlisted"]) {
edges {
node {
title
visibilityLevel
}
}
}
}
}
```
```graphql
{
"data": { …
```

fix: Expose visibilityLevel argument on partner artworksConnection

---

_schemaV2.graphql
src/schema/v2/artwork/artworkSignatureTypes.ts
src/schema/v2/artwork/index.ts
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

- Specifiy signature details (as open text input)
- Specify signature types (via structured enum)
**Request**
```graphql
mutation {
myCollectionUpdateArtwork(input: {
signatureDetails: "artist initials",
signatureTypes: [HAND_SIGNED_BY_ARTIST]
}) {
artwork {
internalID
signature
signatureInfo {
details
label
}
}
}
}
}
}
```
**Response**
```json
{
"data": {
"artwork": {
"internalID": "64de2e913850ca000dd2b967",
"signature": "artist initials",
"signatureInfo": {
"details": "Hand-signed by artist, artist initials",
"label": "Signature"
}
}
}
}
}
```

feat: support signature information for MyC artworks

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Add `isFramed`, `framedMetric`, `framedDepth`, `framedWidth`, `framedHeight` fields to MyCollection create / update artwork mutations.
I can add `framedDimensions` later, it requires Gravity changes
```graphql
mutation {
myCollectionCreateArtwork(input: { title: "test nikita", artistIds: ["banksy"], isFramed: true, framedMetric: "cm", framedDepth: "1", framedHeight: "10", framedWidth: "10" }) {
artwork {
title 
isFramed
framedMetric
framedDepth
framedHeight
framedWidth
}
}
}
}
}
```
Response
```json
{
"data": {
"artwork": {
"title": "test nikita",
"isFramed": true,
"framedMetric": "cm",
"framedDepth": "1",
"framedHeight": "10",
"framedWidth": "10"
}
}
}
}
}
```

MyC mutations support 'framed' fields

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/conversation/index.ts
src/schema/v2/me/__tests__/collector_profile.test.js

This adds `summaryParagraph` as a field under `CollectorProfile` - so it can be queried for - pretty vanilla just hooking it up to the API endpoint.
Since the summary is _also_ based on an artwork (someday we can generalize the concept maybe to still produce a summary w/o an artwork - for use in a different context in CMS perhaps) - that can be an arg passed in - _however_ for easier use in CMS conversations, that artwork identifier will be injected in from the parent so you can more simply query the field from a client in a fragment w/o specifying any arguments.

feat: hook up summaryParagraph on CollectorProfile to DataLoader

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Adds additional information field to MyC artwork mutations.
```graphql
mutation {
myCollectionCreateArtwork(input: { title: "test nikita", artistIds: ["banksy"], additionalInformation: "hello?" }) {
artwork {
title 
additionalInformation
}
}
}
}
}
```
Response:
```json
{
"data": {
"artwork": {
"title": "test nikita",
"additionalInformation": "hello?"
}
}
}
}
}
```

feat: support additional information for MyC artworks

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Adds `conditionDetails` field to MyC artwork mutations.
```graphql
mutation {
myCollectionUpdateArtwork(input: { artworkId: "6655fcce28a249000f872965", conditionDescription: "very good condition" }) {
artwork {
title
conditionDescription {
label
details
}
}
}
}
}
}
```
Response:
```json
{
"data": {
"myCollectionUpdateArtwork": {
"artwork": {
"title": "Napalm - Unsigned",
"conditionDescription": {
"label": "Condition details",
"details": "Very good condition"
}
}
}
}
}
}
```

feat: support condition details for MyC artworks

---

_schemaV2.graphql
src/schema/v2/artist/__tests__/index.test.js
src/schema/v2/partner/__tests__/partner_artist.test.js
src/schema/v2/partner/partner_artist.ts

This is to support a feature request in folio, for partners to be able to toggle off particular artists wholesale from CMS from display in the folio list view if presentation mode is on. 
This updates the partner artist fields with a new `isPartnerArtistHiddenInPresentationMode`, which we can now toggle on and off in volt. 
```graphql
{
partner(id: "foo") {
allArtistsConnection(includeAllFields: true) {
edges {
node {
isPartnerArtistHiddenInPresentationMode
name
}
}
}
}
}
```

feat(partner-artist): Add #isPartnerArtistHiddenInPresentationMode

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Adds certificate of authenticity fields to MyC artwork mutations (also adds structured certificate of authenticity response to artwork field).
```graphql
mutation {
myCollectionCreateArtwork(input: { title: "test nikita", artistIds: ["banksy"], hasCertificateOfAuthenticity: true, coaByAuthenticatingBody: true, coaByGallery: true }) {
artwork {
title
hasCertificateOfAuthenticity
certificateOfAuthenticityDetails {
coaByAuthenticatingBody
coaByGallery
}
}
}
}
}
}
```
Response:
```json
{
"data": {
"artwork": {
"title": "test nikita",
"hasCertificateOfAuthenticity": true,
"certificateOfAuthenticityDetails": {
"coaByAuthenticatingBody": true,
"coaByGallery": true
}
} …
```

feat: support certificate of authenticity fields for MyC artworks

---

_schemaV2.graphql
src/schema/v2/artworksForUser/__tests__/helpers.test.ts
src/schema/v2/artworksForUser/artworksForUser.ts
src/schema/v2/artworksForUser/helpers.ts

This PR adds a new argument to the `artworksForUser` query called `excludeArtworkIds` and when it is provided then matching recommendations from vortex are excluded.
<details><summary> Here's some visual proof </summary>
<p>
</p>
</details> 
When I make a query for the recs without the new argument then I get a particular artwork. When I use the new argument and provide that artwork's id then it is skipped. 😎 
https://artsyproduct.atlassian.net/browse/DIA-652
/cc @artsy/amber-devs @isakelaris

chore: Add argument to exclude certain works from artwork recs DIA-652

---

_schemaV2.graphql
src/schema/v2/me/collection.ts

This still needs to be deployed + backfilled in Gravity, but this would be the API (just new arguments to the connection/endpoint) - hopefully that works for getting hooked up to a FE price slider + availability checkbox filter.

chore: add new filter arguments to artworks in a collection

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts
src/schema/v2/partner/partner_artist.ts

Previously, we supported the use of `allArtistsConnection` for returning authenticated partner.artist counts data. However, that's clunky and returns everything at once, and doesn't support pagination. 
This updates the (bettter) `partner.artistConnection` to support authentication, and also fixes an issue where relay-based cursor pagination support was broken. 
In addition to adding better connection support to CMS, this will allow us to sanely page through lengthy artist lists in folio, vs rendering everything which has terrible network performance. 

feat(partner.artistsConnection): Add support for returning authenticated fields

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/__tests__/updatePartnerShowMutation.test.ts
src/schema/v2/partner/updatePartnerShowMutation.ts
src/schema/v2/schema.ts

Quick PR that adds the paperwork for calling a mutation for updating a partner show:
Query:
```graphql
mutation updatePartnerShowMutation($input:UpdatePartnerShowMutationInput!) {
updatePartnerShow(input:$input) {
showOrError {
... on UpdatePartnerShowSuccess {
show {
internalID
isFeatured
partner {
... on Partner {
showsConnection(first:10) {
edges {
node {
isFeatured
slug
}
}
}
}
}
}
}
... on UpdatePartnerShowFailure {
error
message
}
}
}
}
}
```
Response: 

feat(partner): Add updatePartnerShow mutation

---

_schemaV2.graphql
src/data/convection.graphql
src/lib/stitching/convection/__tests__/stitching.test.ts
src/lib/stitching/convection/__tests__/testingUtils.ts
src/lib/stitching/convection/v2/stitching.ts

[Jira ticket](https://artsyproduct.atlassian.net/browse/ONYX-1042)
To more easily query for artwork metadata stored in My Collection via an associated Submission (in Convection), expose an artwork field under Submission within the GraphQL schema.
```graphql
query X {
submission(id: "250396") {
myCollectionArtworkID
artwork {
internalID
title
}
}
}
```
Response:
```json
{
"data": {
"submission": {
"myCollectionArtworkID": "665f27035e8fac000efde37c",
"artwork": {
"internalID": "665f27035e8fac000efde37c",
"title": "No Ball Games (Green) Test - MyC changes"
}
}
}
}
```

feat(onyx-1042): Expose the associated My Collection artwork underneath a Submission

---

src/lib/loaders/loaders_with_authentication/gravity.ts

Fixes some weird caching behavior that was observed when marking shows as featured and discussed in slack [here](https://artsy.slack.com/archives/C05F8TNKGAV/p1718033011169169). 
TLDR, as we "metaphysics-ize" more of volt via mutations this will likely come up again, where realtime results need to be returned as uncached. If something seems off, check to see if the loader has been added to `src/lib/loaders/loaders_with_authentication/gravity.ts`, and not just `loaders_without_authentication`. If so, you'll likely run into unexpected behavior due to MP-level redis caching. 

chore(partnerShows): Add loader to `loaders_with_authentication`

---

_schemaV2.graphql
src/schema/v2/partner/__tests__/partner_artist.test.js
src/schema/v2/partner/partner_artist.ts

This updates our partnerArtist edge to return the associated partner artist image:
```graphql
{
partner(id: "foo") {
artistsConnection(includeAllFields: true, first: 10) {
edges {
artist {
name
}
imageUrl
image {
url
}
}
}
}
}
```

feat(partnerArtist): Add partner artist image support

---

_schemaV2.graphql
src/schema/v2/me/__tests__/myCollection.test.ts
src/schema/v2/me/myCollection.ts

Jira ticket [ONYX-1067]
This PR adds `includeOnlyTargetSupply` to `MyCollectionConnection`. This is required in order to show a valid list of eligible artworks in users' collection.
[ONYX-1067]: https://artsyproduct.atlassian.net/browse/ONYX-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add includeOnlyTargetSupply param to MyCollectionConnection

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/edition_set.ts

Solves [AMBER-724]
With the addition of a new type of sale message (added in https://github.com/artsy/gravity/pull/17819) we want to ensure that Metaphysics honours this and doesn't override it with a hardcoded value.
[AMBER-724]: https://artsyproduct.atlassian.net/browse/AMBER-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-724 - inquiry sale message

---

src/schema/v2/conversation/__tests__/__snapshots__/conversation.test.js.snap
src/schema/v2/partner/partnerInquiryRequest.ts

This PR prevents a trailing comma from appearing in conversation messages in CMS when questions are attached to an inquiry.

fix: trailing comma in inquiries with questions

---

src/lib/stitching/convection/__tests__/stitching.test.ts
src/lib/stitching/convection/v2/stitching.ts

**Request**
```graphql
{
submission(id: "d641cd14-98b4-41c3-9332-f7b2904c4dc8") {
myCollectionArtwork {
internalID
}
}
}
```
**Response**
```json
{
"data": {
"submission": {
"myCollectionArtwork": null
}
}
}
```
```
"message": "Variable \"$_v0_id\" of non-null type \"String!\" must not be null.",
```

fix: avoid schema error when Submission#myCollectionArtworkID is null

---

_schemaV2.graphql
src/schema/v2/me/__tests__/index.test.ts
src/schema/v2/partnerOffer.ts
src/schema/v2/partnerOfferToCollector.ts

Part of https://artsyproduct.atlassian.net/browse/EMI-1924
Return isActive so clients can easily know if an offer is active or not and can render banners or messaging accordingly.
Basically reverting this revert https://github.com/artsy/metaphysics/pull/5586/commits/7aff9df4157c4ed48d1351261fce67f17c654748

feat(EMI-1924): return isActive for partner offers

---

_schemaV2.graphql
src/schema/v2/notifications/Item/CollectorProfileUpdatePromptNotificationItem.ts
src/schema/v2/notifications/Item/index.ts

This should allow the /notifications page and bell dropdown (on web) to render -> right now the queries error out if your feed includes an item of this type b/c the richer `Item` schema is being queried for (for some activity types), and even though we likely don't need it for this type, as it is a union type we need to include something minimally - it simply throws an exception otherwise.
With this addition the query will succeed, however the rendering of the notification will be basically empty, as we're not returning any 'real' data from MP for this activity type -> it's really more of a placeholder.
My thinking is while some of the copy used is shared between Force/Eigen and so _can_ go to MP (possibly using the existing `headline` and `message` fields, _or_ as part of the richer …

feat: support collector profile update activity type in Item schema

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/collectorProfile.ts
src/schema/v2/me/__tests__/update_collector_profile.test.js
src/schema/v2/me/update_collector_profile.ts

Companion to https://github.com/artsy/gravity/pull/17839 , allows timestamp to be set via mutation and also adds it to schema.

chore: set timestamp of collector profile update prompt

---

_schemaV2.graphql
src/lib/__tests__/artworkToSubmissionMapping.test.ts
src/lib/artworkToSubmissionMapping.ts
src/lib/stitching/convection/__tests__/stitching.test.ts
src/lib/stitching/convection/schema.ts
src/lib/stitching/convection/v2/stitching.ts

This PR allows to sync artwork data when specifying it's ID as `myCollectionArtworkID` argument to `createConsignmentSubmission` mutation.
Previously, `createConsignmentSubmission` was simply stitched from Convection. This PR adds a resolver for this mutation (keeping the same name). This mutation does two things:
- If  `myCollectionArtworkID` is specified - fetches artwork data using `artworkLoader` and prepares it to be passed to Convection.
- Calls `convectionCreateConsignmentSubmission` mutation (which was renamed from `createConsignmentSubmission`) with artwork data + mutation input arguments (mutation input arguments override artwork data if specified)
Example request (uses this [artwork](https://staging.artsy.net/collector-profile/my-collection/artwork/6654590c43bd0200125ea0b1)): …

feat(onyx-1071): allow syncing my collection artwork data when creating submission

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/convection.ts
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts
src/schema/v2/me/__tests__/submissionsConnection.test.ts
src/schema/v2/me/index.ts
src/schema/v2/me/submissionsConnection.ts

[SPIKE]
This PR adds a new connection to the `Me` interface that returns a list of submitted artworks by a certain user. I added only one argument currently to filter through the state of the submissions.
https://github.com/artsy/metaphysics/assets/11945712/3340c2fd-f8ef-4738-907a-59696487303e

feat: return list of user submissions

---

_schemaV2.graphql
src/lib/stitching/convection/__tests__/stitching.test.ts
src/lib/stitching/convection/v2/stitching.ts

This PR adds a new field to `ConsignmentSubmission`  called `userPhoneNumber` that returns a `PhoneNumberType` instead of a `string` to make using it easier in the frontend and avoid destructuring it in client apps.

feat: stitch userPhoneNumber to ConsignmentSubmission

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts
src/schema/v2/edition_set.ts

[AMBER-769]
During the work done in https://github.com/artsy/gravity/pull/17851, we ensured sale message will return the correct value according to the artwork availability. Therefore, we no longer need to perform these checks in Metaphysics (we do not want to have different versions of the sale message depending on the spot it's used).
The only sale message logic that was not yet removed from MP is the one we use to build the price display text.
The reasoning is that there are many more inconsistencies on those and it should be a separate refactor.
----
Even within Metaphysics, we have different formats used.
See, for example, the way we display prices depending on whether we're querying from artwork or edition sets:
- `US` prefix before the dollar sign
- No spaces around the hyphen
- …

chore(AMBER-769): Remove sale message condition checks

---

src/schema/v2/static_content.ts

Awhile ago I've added `specialistBios` section under `staticContent`: https://github.com/artsy/metaphysics/pull/5653. Before, `staticContent` was used to fetch `pages` from Gravity. User can specify ID or slug of a page to fetch it:
```graphql
query X {
staticContent(id: "swa-listing-terms") {
id
slug
name
content
}
}
```
ID field was required (otherwise how would it be possible to fetch a Page). In this PR ⬆️ I've made this field optional, because now we want to put all sorts of static (really static) content under `staticContent` scope. For specialist bios it looks like this:
```graphql
query X {
staticContent {
specialistBios {
name
firstName
jobTitle
}
}
}
```
This query doesn't fail, but it fails when querying other top-level `staticContent` fields, such as `id` or `slug`:
```graphql …
```

fix: static content returns hardcoded ID and slug

---

_schemaV2.graphql
src/schema/v2/notifications/Item/CollectorProfileUpdatePromptNotificationItem.ts

Needs `me` in order to access the user interests to determine the state of the CTA

feat: exposes me under notification

---

_schemaV2.graphql
src/schema/v2/specialistBios.ts

Changing the types of fields from `TYPE` to `new GraphQLNonNull(TYPE)` to simplify implementation on the frontend.

chore: change type for swa specialist fields

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/artworkCondition.ts
src/schema/v2/artwork/index.ts
src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
src/schema/v2/me/myCollectionCreateArtworkMutation.ts
src/schema/v2/me/myCollectionUpdateArtworkMutation.ts

Depends on https://github.com/artsy/gravity/pull/17872
We want to allow users to pick an artwork condition when submitting an artwork for purchase.
```graphql
mutation {
myCollectionCreateArtwork(input: { artistIds: ["bea-nettles"], title: "Hello", condition: VERY_GOOD, conditionDescription: "no scratches!" }) {
artwork {
title
condition {
value
displayText
description
}
}
}
}
}
}
```
Response:
```json
{
"data": {
"artwork": {
"title": "Hello",
"condition": {
"value": "VERY_GOOD",
"displayText": "Very good",
"description": "No scratches!"
}
}
}
}
}
}
```
```graphql
mutation {
myCollectionUpdateArtwork(input: { artworkId: "668406f9b3e438648d4c4e82", condition: FAIR, …
```

feat(onyx-1084): add artwork condition

---

src/schema/v2/artwork/__tests__/meta.test.ts
src/schema/v2/artwork/meta.ts

[AMBER-776]
If an an artwork is listed as "Inquire about availability, it means the partner is choosing the new setting instead of the default one ("Price on request") for artworks with hidden price. In that case, we want the language to feel less commercial, therefore, the metadata shouldn't indicate any mentions to sales
cc @artsy/amber-devs 
[AMBER-776]: https://artsyproduct.atlassian.net/browse/AMBER-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(AMBER-776): Omit sale mentions in case of VIP listing

---

_schemaV2.graphql
src/data/gravity.graphql

Chore: Keeps gravity.graphql up to latest schema to remove Location from being queried on Artwork type
Building off of @mzikherman's work here: https://github.com/artsy/gravity/pull/17883

Chore: Keeps gravity.graphql up to latest schema

---

_schemaV2.graphql
src/schema/v2/Alerts/index.ts
src/schema/v2/partner/partner.ts

Expose optional `artistID` filter param + adjusts capitalization of some id related fields
To note these fields are not used in any client yet!
Gravity changes here: https://github.com/artsy/gravity/pull/17914

feat: Expose optional `artistID` filter param

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

Resolves: https://artsyproduct.atlassian.net/browse/PHIRE-1053
Exposes representedByOrHasPublishedArtworks arg added here so we can use the paginated endpoint on partner pages. 
https://github.com/artsy/gravity/pull/17934
Hold on merging until gravity changes are deployed. 
Potential follow-up: 
- Should we deprecate the arg here that does the same thing in non-paginated endpoint?: https://github.com/artsy/metaphysics/blob/0425a51714086a25f182e5026ddaf14abc23d922/src/schema/v2/partner/partner.ts#L394

feat: expose arg in paginated endpoint

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewComponent.ts
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/index.ts
src/schema/v2/homeView/stubData.ts
src/schema/v2/homeView/stubDataResolver.ts
src/schema/v2/schema.ts

A first increment towards the goal of a dynamic Art Advisor home view. 
Onyx has been leading a brainstorm and PoC schema for a flexible Home View, which can provide a list of content sections and their recommended components. 
See: [tech plan](https://www.notion.so/artsy/Art-Advisor-Dynamic-Home-View-3615106ef393433a9f16dcf13b2414f2) and [early share-out](https://artsy.slack.com/archives/C07ANEV7RNV/p1721410245056939)
This PR reflects this early, provisional thinking. (We expect this to evolve, perhaps drastically, as the requirements become clearer.)
The high-level goals are:
- the server controls the selection and ordering of such sections (based on personalization/curation/etc)
- the client knows enough to be able to passively render them using standardized components
The section …

feat: add prototype schema for new home view sections

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/__tests__/partner.test.js
src/schema/v2/partner/partner.ts

This adds support for returning partner-authenticated location data from Gravity via a new `private: true` argument:
```graphql
{
partner(id: "some-partner") { 
locationsConnection(first: 100, private: true){
edges {
node {
address
}
}
} 
}
}
```

feat(partner): Add authenticated partnerLocationsConnection loader

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts

As discussed in [this thread](https://artsy.slack.com/archives/D032AFMTJES/p1721828639408619), adding submission copies to MP
Addressed [ONYX-1135](https://artsyproduct.atlassian.net/browse/ONYX-1135) 
[ONYX-1135]: https://artsyproduct.atlassian.net/browse/ONYX-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add submission copy to GraphQL schema

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

I just realised I forgot to add this when writing [AMBER-828], but we need to be able to filter partner locations by address type so we can use this query in Volt (the one currently consumed by orders filters only partner locations with a `Business` address type)
```graphql
{
id
locationsConnection(first: 5, private: true, addressType: BUSINESS) {
edges {
node {
address
city
}
}
}
}
}
```
Ref for the same filter in Volt [here](https://github.com/artsy/volt/blob/cefe12e3145bd76dc6f094b1dc92d84cb5bf2459/app/models/partner.rb#L234)
@artsy/amber-devs 
[AMBER-828]: https://artsyproduct.atlassian.net/browse/AMBER-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Enable address type filter on partner locations query

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Returns true if `Artwork#listed_artworks_ids` is present and non-empty. For use within My Collection surfaces to determine whether we render a component/links representing an artwork's commercial listings or query against any active submission status.
```graphql
{
artwork(id: "ID") {
isListed
}
}
```
| MyC Artwork | Image |
|--------|--------|
| isListed=true | ![Screenshot 2024-07-25 at 17 04 38](https://github.com/user-attachments/assets/87276a6b-9405-4590-bd1d-105e1835217c) |
| isListed=false + active submission | ![Screenshot 2024-07-25 at 17 04 50](https://github.com/user-attachments/assets/b304fafe-ac34-40c7-b4b2-16acd64402db) | 
Source: [Figma](https://www.figma.com/design/E6rVm1tiSI4PW3EzibKKZw/Submission-%26-Pre-Consignment-Management?node-id=2894-17256&t=45sKhcM4NWwKPTmf-0)

feat: Add Artwork#isListed field

---

src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/schema.ts
src/lib/stitching/gravity/v2/stitching.ts
src/schema/v2/artist/index.ts
src/schema/v2/marketingCollections.ts

This PR adds remaining unstitched types to Artist model and flippin' flag to gravity/stitching.

feat: add remaining unstitched marketing collection types

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/artworkResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

Swap out stub data for real data via existing resolvers / data loaders.
- [feat: load real data for homeView > Recently Viewed Artworks](https://github.com/artsy/metaphysics/commit/debf842eb021a87dc120ec5e745cfac7babf0231)
- [feat: load real data for homeView > Auction Lots For You](https://github.com/artsy/metaphysics/commit/82b1c36d9bbe65685dab4fd7fc8f4163974bcd7e)
- [feat: load real data for homeView > Trending Artists](https://github.com/artsy/metaphysics/commit/8e641e9d9026160650d1f96e4bd64e87ef822299)

feat: load real data for new home view sections

---

_schemaV2.graphql
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts

**Description**
This PR adds the missing consignment submission type to the accepted types. This is needed to fix the problem below

fix: add missing consignment submission type

---

src/lib/loaders/loaders_without_authentication/gravity.ts
src/lib/stitching/gravity/schema.ts
src/schema/v2/__tests__/marketingCategories.test.ts
src/schema/v2/marketingCategories.ts
src/schema/v2/marketingCollections.ts
src/schema/v2/schema.ts

This PR is a follow-up to the new [Gravity endpoint](https://github.com/artsy/gravity/pull/17996), and continuation of the unstitching the marketing collections.

feat: add unstitched marketing categories

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/index.ts

Reduces the amount of null-checking needed by the client and we expect all of these types to consistently present data.

chore: make some homeView field types non-nullable

---

src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/v2/stitching.ts

I'm not totally sure what's going on here but something in the recent dependency PR changed how the formatted text args worked and I think the stitched resolvers might have been overlooked. 
This fixes the broken markdown formatted for the stitched ArtistSeries type, as reported [here in Slack](https://artsy.slack.com/archives/C03N12SR0RK/p1722611523473189) 🔒.

fix: handle formatted markdown properly for stitched ArtistSeries type

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts
src/schema/v2/me/loadSubmissions.ts

Expose external submission ID in ArtworkConsignmentSubmission to be able to link to the correct step in the Sell flow (https://github.com/artsy/force/pull/14297).

feat: Expose external submission ID in ArtworkConsignmentSubmission

---

_schemaV2.graphql
src/schema/v2/fair.ts
src/schema/v2/partner/partner.ts

Like, https://github.com/artsy/metaphysics/pull/5878, but for partners. Depends on https://github.com/artsy/gravity/pull/18014 (but can be merged whenever).

feat: partners support featured keywords for curated browsing

---

src/schema/v2/artworksForUser/__tests__/artworksForUser.test.ts
src/schema/v2/artworksForUser/artworksForUser.ts
src/schema/v2/artworksForUser/helpers.ts

Addresses [ONYX-1174](https://artsyproduct.atlassian.net/browse/ONYX-1174)
- [Slack thread with context](https://artsy.slack.com/archives/C05EQL4R5N0/p1722948565984559)
This fixes the pagination logic for `ArtworksForUser` by overfetching recommended artwork IDs and slicing these IDs after adding backfill and excluding disliked artworks.
[ONYX-1174]: https://artsyproduct.atlassian.net/browse/ONYX-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: ArtworksForUser pagination logic

---

src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/artworkResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

This PR resolves [ONYX-1173]
This PR adds a new artwork home section (**Similar to Works You Viewed**) to the list of `Sections` and exposes it to client app.
The process to add this was the following:
[ONYX-1173]: https://artsyproduct.atlassian.net/browse/ONYX-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add similar to works you viewed resolver

---

_schemaV2.graphql
src/schema/v2/sale/index.ts

Like https://github.com/artsy/metaphysics/pull/5878 and https://github.com/artsy/metaphysics/pull/5888, but for sales. Depends on https://github.com/artsy/gravity/pull/18025 but can safely be deployed whenever.

feat: expose featuredKeywords on sales

---

src/schema/v2/fair.ts

This PR fixes the issue of random collections populating as curated highlights on the fair page when the admin field is blank.
[Ticket](https://artsyproduct.atlassian.net/browse/DIA-786)

fix: random collections populating fairs pages

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

Minor chore related to [EMI-2019] - Following https://github.com/artsy/gravity/pull/18042 we will want to filter only active partner offers when finding collector signals for partner offers.
[EMI-2019]: https://artsyproduct.atlassian.net/browse/EMI-2019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2019): filter active partner offers for collector signals

---

src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
src/schema/v2/artwork/artworkConsignmentSubmissionType.ts

Change button label for APPROVED status
Addressed [Notion card](https://www.notion.so/artsy/CTA-should-say-Complete-Listing-41570cab607f4ff2b3abd4cf6a303bb4?pvs=4)

chore: change button label for approved status

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

This PR completes [EMI-2015] by adding auction deadline values to the CollectorSignals type.
Only future dates are included for the date values. I have an alternative idea for the interface, but this essentially collects data that we normally check from multiple different sources - it's mostly up to clients to choose which to prioritize based on presence.
[EMI-2015]: https://artsyproduct.atlassian.net/browse/EMI-2015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2015): Auction deadline collector signals

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/homeView/HomeViewComponent.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/artworkResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

Related: https://github.com/artsy/metaphysics/pull/5912
Adds "Curators' Picks: Emerging" section to our new schema. See a discussion why we came up with some of implementation decisions [in Slack](https://artsy.slack.com/archives/C05EQL4R5N0/p1723746300946949).
```graphql
query {
homeView {
section(id: "home-view-section-curators-picks-emerging") {
... on ArtworksRailHomeViewSection {
component {
title
description
backgroundImageURL
href
}
edges {
node {
title
}
}
}
}
}
}
}
```
And response:
```json
{
"data": {
"homeView": {
"section": {
"component": {
"title": "Curators’ Picks: Emerging",
"description": "The best works by rising talents on Artsy, available now.",
"backgroundImageURL": …
```

feat(onyx-1191): add "Curators' Picks: Emerging" home view section

---

_schemaV2.graphql
src/schema/v2/CollectorProfile/__tests__/updateCollectorProfileWithID.test.ts
src/schema/v2/me/__tests__/update_collector_profile.test.js
src/schema/v2/me/update_collector_profile.ts

This old mutation returns a default `UpdateCollectorProfilePayload` which doesn't fit anywhere using it with relay. 
The changes here expose `collectorProfile` with the type supported by our schema when it comes to spreading fragments. Nothing new here, we have this pattern in other mutations such as `updateMyUserProfile`, and could extend it to something like `collectorProfileOrError` but it seemed too much for this small exposition, open to feedback 😄

feat(updateCollectorProfile): expose CollectorProfileType field 

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

This is a quick followup to @mzikherman's comment in https://github.com/artsy/metaphysics/pull/5889#pullrequestreview-2238572145.
This PR changes how we resolve collector signals to get each field from its own `resolve` function, rather than one single resolver that constructs the entire `collectorSignals` object.
**PROs** for this approach
- It is more in line with our patterns in metaphysics, possibly easier to trace where things come from
- Less need to worry about checks like `isFieldRequested` when thinking about cascading requests
- `DataLoader` used in our loaders will avoid duplicative requests
**Cons:** The collector signals object could be thought of as a unit. If we think of them that way then they are more intuitively structured as a single resolver:
- There has been some …

chore: resolve each collectorSignal field in its own resolver

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts

https://artsyproduct.atlassian.net/browse/ONYX-1201
Addresses two issues in the design of the new `homeView` schema (h/t @mzikherman):
- The schema currently is over-aggressive about declaring non-nullability. It makes that promise even when it can't guarantee it, e.g. when making an async upstream call to fetch the data to fulfill an `artworksConnection` or `artistsConnection`. Not only is this not realistic, it also results in [cryptic error messages that have already derailed developers.](https://artsy.slack.com/archives/C05EQL4R5N0/p1724096191940129?thread_ts=1724081856.316439&cid=C05EQL4R5N0)
- There is a [better way](https://artsy.slack.com/archives/C05EQL4R5N0/p1724099057516639?thread_ts=1724081856.316439&cid=C05EQL4R5N0) to return an empty connection with the correct shape than …

fix(home view): nullability and empty responses

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/featuredFairsResolver.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

```graphql
query X {
homeView {
section(id: "home-view-section-featured-fairs") {
... on FairsRailHomeViewSection {
__typename
component {
title
}
fairsConnection(first: 10) {
edges {
node {
__typename
name
}
}
}
}
}
}
}
```
Response:
```
{
"data": {
"homeView": {
"section": {
"__typename": "FairsRailHomeViewSection",
"component": {
"title": "Featured Fairs"
},
"fairsConnection": {
"edges": [
{
"node": {
"__typename": "Fair",
"name": "Intersect Aspen 2024"
}
},
{
"node": {
"__typename": "Fair",
"name": "The Aspen Art Fair 2024"
}
},
...
}
}
}
}
}
```
```

feat(onyx-1199): add 'Featured Fairs' home view section

---

src/lib/loaders/__tests__/helpers.test.ts
src/lib/loaders/helpers.ts

This adds a `withTimeout` wrapper that you can use when invoking a data loader, passing in a timeout (in milliseconds).
If the loader takes longer than the specified timeout, the method throws - when configuring it as a test via `withTimeout(artworkLoader(id), 50)` (an intentionally short timeout) - looks like:
Based on the Slack discussion about wanting more finer-grained control over homepage data resolution. I can envision homeview-scoped data loader invocations wanting to use this in order to ensure quick (altho potentially incomplete) responses. Pretty simple approach to start - I decided against over-engineering anything w.r.t to factories and the like (like a 'homeview' data loader factory that always includes this functionality kind of thing).
Do y'all think this might be a useful …

feat: add withTimeout wrapper for DataLoader

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/__tests__/partner.test.js
src/schema/v2/partner/partner.ts

Addresses https://artsyproduct.atlassian.net/browse/AMBER-914
Adds a new connection to the partners alerts eco system:
```graphql
{
partner(id: "cypress-test-partner-for-automated-testing-purposes") {
partnerAlertHitsConnection(first: 10) {
totalCount
edges {
internalID
artwork {
internalID
title
}
userIDs
createdAt
node {
additionalGeneIDs
}
}
}
}
}
```

feat(alerts): Add partnerAlertHitsConnection

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

Missed this! dates should use the `date()` helper. 

fix(partner): Use demand date helper

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/articlesResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

This PR adds a new articles rail home view section. It also exposes "Artsy Editorial" as a new section.
Remaining: Add tests to `HomeViewSection`

feat: add latest articles section

---

_schemaV2.graphql
src/schema/v2/Alerts/index.ts

feat: Expose `artistSeriesNames` field from Search criteria
Exposes the new field from Gravity of human readable Artist series names
https://github.com/artsy/gravity/pull/18060
```graphql
{
slug
name
alertsConnection(first: 10) {
totalCount
edges {
node {
internalID
attributionClass
artistSeriesIDs
artistSeriesNames
}
}
}
}
}
```

feat: Expose artistSeriesNames field from Search criteria

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/featuredFairsResolver.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/marketingCollectionsResolver.ts
src/schema/v2/homeView/sections.ts

```graphql
query {
homeView {
sectionsConnection(first: 4) {
edges {
node {
... on MarketingCollectionsRailHomeViewSection {
component {
title
}
marketingCollectionsConnection(first: 1) {
edges {
node {
title
}
}
}
}
}
}
}
section(id: "home-view-section-marketing-collections") {
... on MarketingCollectionsRailHomeViewSection {
component {
title
}
}
}
}
}
```
Response:
```json
{
"data": {
"homeView": {
"sectionsConnection": {
"edges": [
{
"node": {}
},
{
"node": {}
},
{
"node": {
"component": {
"title": "Collections"
},
"marketingCollectionsConnection": {
"edges": [
{
"node": {
"title": "Trending Now"
}
}
]
}
}
},
{
"node": {}
}
]
},
"section": {
"component": {
"title": "Collections"
}
}
}
}
}
```

feat(onyx-1218): add Collections section to new home view schema

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/__tests__/partner.test.js
src/schema/v2/partner/partner.ts

Adds support for single alert with partner facing metadata so we can support a show single alert page in CMS
[Wires in new Gravity endpoint](https://github.com/artsy/gravity/pull/18073)
This connection should support:
```
{
slug
name
alertsConnection(first: 10) {
totalCount
edges {
id
collectorProfilesConnection(first: 10) {
totalCount
edges {
node {
name
internalID
}
}
}
node {
internalID
attributionClass
}
}
}
}
}
```
but also a
```
{
slug
name
alertsConnection(id: "im-a-regular-old-single-record") {
totalCount
edges {
id
collectorProfilesConnection(first: 10) {
totalCount
edges {
node {
name
internalID
}
}
}
node {
internalID
attributionClass
}
}
}
}
}
```

feat: Allow alertsConnection to accept alert id filter

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/__tests__/verifyUser.test.ts
src/schema/v2/schema.ts
src/schema/v2/verifyUser.ts

Based on https://github.com/artsy/gravity/pull/18058 , this adds support for deciding if a user exists - and so is used in the new authentication flow. Of course, Gravity enforces a very strict rate limit as well as requiring a valid reCAPTCHA, so the Metaphysics implementation can remain vanilla.
I decided to go with `verifyUser` -> return an object so it's future-proof if we wanted to add any related data, and also we have a `verifyAddress` field as well, so went with that pattern - but of course there are a lot of different names for this potentially, `userStatus`, etc.

feat: add verifyUser for new authentication flow

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

```graphql
query {
homeView {
sectionsConnection(first: 4) {
edges {
node {
... on ShowsRailHomeViewSection {
component {
title
}
}
}
}
}
section(id: "home-view-section-shows-for-you") {
... on ShowsRailHomeViewSection {
__typename
component {
title
}
}
}
}
}
```
Response:
```json
{
"data": {
"homeView": {
"sectionsConnection": {
"edges": [
{
"node": {}
},
{
"node": {}
},
{
"node": {
"component": {
"title": "Shows for You"
}
}
},
{
"node": {}
}
]
},
"section": {
"__typename": "ShowsRailHomeViewSection",
"component": {
"title": "Shows for You"
}
}
}
}
}
```

feat(onyx-1224): add reduced schema for Shows for You rail

---

src/schema/v2/artworksForUser/__tests__/artworksForUser.test.ts
src/schema/v2/artworksForUser/__tests__/helpers.test.ts
src/schema/v2/artworksForUser/artworksForUser.ts
src/schema/v2/artworksForUser/helpers.ts

This PR resolves [ONYX-1174](https://artsyproduct.atlassian.net/browse/ONYX-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
- Related Eigen PR: https://github.com/artsy/eigen/pull/10647
This fixes `artworkForUser`'s total count.
[ONYX-1174]: https://artsyproduct.atlassian.net/browse/ONYX-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: New Works for You total count

---

_schemaV2.graphql
src/schema/v2/artist/__tests__/helpers.test.ts
src/schema/v2/artist/helpers.ts
src/schema/v2/artist/index.ts

This PR exposes the foundations insight. 
PR for the ground work are done in Gravity: 
- https://github.com/artsy/gravity/pull/18069
- https://github.com/artsy/gravity/pull/18035 
Successful import:
```
[2024-08-22, 07:13:45 UTC] {batch.py:116} INFO - I, [2024-08-22T07:13:16.617801 #6]  INFO -- : importing data...
[2024-08-22, 07:13:45 UTC] {batch.py:116} INFO - D, [2024-08-22T07:13:17.339910 #6] DEBUG -- : Dalli::Server#connect gravity-prod-memcached-2022.uvuuuk.cfg.use1.cache.amazonaws.com:11211
[2024-08-22, 07:13:45 UTC] {batch.py:116} INFO - I, [2024-08-22T07:13:33.264296 #6]  INFO -- : processed 1000 rows
[2024-08-22, 07:13:45 UTC] {batch.py:116} INFO - I, [2024-08-22T07:13:38.186215 #6]  INFO -- : updated 1304 artists
```

feat: expose foundations insights

---

_schemaV2.graphql
src/schema/v2/auction_result.ts
src/schema/v2/homeView/HomeViewComponent.ts
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/auctionResultsResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

This PR resolves [ONYX-1234]
This PR adds a new home view section for auction results. It also exposes the latest auction results to client apps.
**Query on Insomnia**
___
**New section on Eigen**
[ONYX-1234]: https://artsyproduct.atlassian.net/browse/ONYX-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add add auction results home view section

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

Completes [EMI-2017]
This PR exposes the new `artwork.increased_interest_signal` field through the metaphysics `artwork.collectorSignals` field. In addition it makes the `artwork.collectorSignals` field explicitly null if the artwork is not subject to collector signals.
[EMI-2017]: https://artsyproduct.atlassian.net/browse/EMI-2017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2017): Expose increased interest collector signal

---

src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/articlesResolvers.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/sections.ts

https://artsyproduct.atlassian.net/browse/ONYX-1237
Adds the section data and resolver for the News section of the home view
```graphql
{
homeView {
section(id: "home-view-section-news") {
... on GenericHomeViewSection {
internalID
component {
title
type
}
}
... on ArticlesRailHomeViewSection {
articlesConnection(first: 3) {
edges {
node {
title
href
}
}
}
}
}
}
}
```
```json
{
"data": {
"homeView": {
"section": {
"internalID": "home-view-section-news",
"component": {
"title": "News",
"type": "ArticlesCard"
},
"articlesConnection": {
"edges": [
{
"node": {
"title": "Lauren Halsey to receive first U.K. solo show at Serpentine.",
"href": "/article/artsy-editorial-lauren-halsey-receive-first-uk-solo-serpentine"
}
},
{
"node": {
"title": "$35 million Monet painting to headline inaugural sale …
```

feat: add a News home view section

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/salesResolver.ts
src/schema/v2/homeView/sections.ts

```graphql
query {
homeView {
section(id: "home-view-section-auctions") {
... on SalesRailHomeViewSection {
component {
title
}
salesConnection(first: 2) {
edges {
node {
name
}
}
}
}
}
}
}
```
```json
{
"data": {
"homeView": {
"section": {
"component": {
"title": "Auctions"
},
"salesConnection": {
"edges": [
{
"node": {
"name": "Artsy Auction: 100 x 100 (Part I) "
}
},
{
"node": {
"name": "Collector signals live now"
}
}
]
}
}
}
}
}
```

feat(onyx-1229): add Auctions home view section

---

hokusai/staging.yml

This adds an alternate hostname for the same metaphysics-staging (only) deployment. It aims to simplify caching experiments ([DIA-818](https://artsyproduct.atlassian.net/browse/DIA-818)), which would probably be applied at the "edge" before passing requests through to the actual origin. During these experiments I'd rather not touch the live configuration for `metaphysics-[staging|production].artsy.net`, so this alternate name gives us freedom to experiment while iterating on realistic configuration.
[DIA-818]: https://artsyproduct.atlassian.net/browse/DIA-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: configure alternate ingress host for metaphysics staging (DIA-818)

---

src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/getSectionsForUser.ts
src/schema/v2/homeView/index.ts
src/schema/v2/homeView/sections.ts
src/schema/v2/homeView/zones/__tests__/legacy.test.ts
src/schema/v2/homeView/zones/legacy.ts

https://artsyproduct.atlassian.net/browse/ONYX-1161
This started out as:
- introduce a legacy zone concept to the home view
And then I feature-creeped it with:
- relax the requirement for an _authenticated_ user for requesting the `homeView` fields
So now this can be requested by either an authenticated or an un-authenticated user:
👉🏽  Most of the interesting stuff is in https://github.com/artsy/metaphysics/pull/5948/commits/004450f7f0ddad31556a8848e0fae8a03e0af39c
```graphql
{
homeView {
sectionsConnection(first: 30) {
edges {
node {
... on GenericHomeViewSection {
internalID
}
}
}
}
}
}
```
This represents the "legacy zone", which is an internal but not (as of yet) a client-facing concept. This zone consists of the same sections, in the same order, as the current Eigen home feed. …

feat: add legacy zone logic

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

Paired with @erikdstock on this.
Adds a `curatorsPick` field that is `true` if the artwork is either in the `curators-picks-blue-chip-artists` or `curators-picks-emerging-artists` marketing collections and false otherwise.
I did a smoke test in staging adding one artwork to one of the collections via https://stagingapi.artsy.net/admin/curated_marketing_collection/08b45eb4-b975-49c7-8ccb-b16d2304a308 (it took me some time to find where we edit those collections, so posting here for future reference; **you need the `METADATA_ADMIN` role to see the page**) and it looks good locally.
```
query {
artwork(id: "molly-magai-fladson-test") {
collectorSignals {
increasedInterest
curatorsPick
auction {
bidCount
lotWatcherCount
registrationEndsAt
lotClosesAt
liveBiddingStarted
liveStartAt …
```

feat(EMI-2013): add curatorsPick field to artwork signals

---

src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/index.ts
src/schema/v2/object_identification.ts

This is an alternate version of https://github.com/artsy/metaphysics/pull/5968.
It winds up adding in some generic support union types here, and so this might be good to go and a bit easier to use w.r.t to less boilerplate needed.
Looks like-

feat: add Node support for new homeview sections / support union

---

hokusai/production.yml

Like https://github.com/artsy/metaphysics/pull/5953, but for production. Enables validating any new CDN configuration with live traffic, by targeting the `...-alt` hostname.

chore: configure alternate ingress host for metaphysics production (DIA-818)

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewComponent.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/sections.ts

I've added hrefs and button texts to all sections following @MounirDhahri 's approach from this PR: https://github.com/artsy/metaphysics/pull/5944
Let's debate if we want to implement the interface somehow else. @anandaroop you've left a few comments here: https://github.com/artsy/metaphysics/pull/5944#discussion_r1731598695
> Is this meant to handle both of the current (or future) kinds of placements for the view-all UI? Or would we distinguish between them in the response?
Currently both title section and buttons lead to the same page. I am not sure if it will be different in future, but if there will be a need to distinguish them, will it be possible to do it by expanding current schema and not changing it a lot? Something like this maybe:
```graphql
behaviors {
sectionTitle {
href
} …
```

feat(onyx-1157): add href and button texts to all home view sections that require it

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

Completes [EMI-2049] 🦄 
This PR adds a `primaryLabel` field to collector signals which is an enum of the possible signal labels. PARTNER_OFFER implies existence of the partnerOffer field as well, while others come from a boolean. However this PR does not change the schema to guarantee a partner offer if the label is PARTNER_OFFER.
relates to #5954 and should probably go in after rebasing on that change.
[EMI-2049]: https://artsyproduct.atlassian.net/browse/EMI-2049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2049): expose primaryLabel field

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

Adds a `runningShowOrFair` field that will return the latest running show or fair that the artwork is currently in, sorted by relevance.
My reasoning behind returning the Show or the Fair in one field is that the signal only needs one show/fair to display the name and date, so with this approach we avoid more logic in Force to select which object to show. Also, the `relatedFairs` query was not returning the expected results (see screenshot below), and the `relatedShows` is returning both shows and fairs, so I think it's fine to have it like this. Let me know if anyone has a strong opinion on this.
Staging test
`relatedShows` response for this artwork
```
[
{
"fair": null,
"location": {
"day_schedules": [],
"id": "5f8123abec5de8000ea9b785",
"name": "00b942590fd74a14d9a9ecb68e935f53", …
```

feat(EMI-2016): add runningShowOrFair field to Artwork collector signals

---

src/schema/v2/artist/index.ts

Tweaks the resolver a bit so that if the cover artwork is set _but unpublished/deleted_ (true for ~20% of artists where the cover is set) - we still fallback.

chore: allow a missing _or_ unpublished cover artwork to fallback on Artist

---

src/schema/v2/__tests__/show.test.js
src/schema/v2/show.ts

We definitely have some bad modeling on the data side, but I think this fix is correct.
Basically - we have 'reference' shows which should not have a page on Artsy.
But - we also have 'displayable' shows which do - where displayable can include shows with no published artworks if they have > 2 install shots.
The 'reference' show definition doesn't take that into account - while it requires no published artworks it doesn't check install shots - so we have shows that are set to both 'displayable' _and_ 'reference'. Those concepts seem orthogonal to me since by definition a reference show _isn't_ displayable. Specifically this applies to shows with > 2 install shots, but all unpublished artworks.
I don't think it's worth tangling/un-tangling any of that logic on `PartnerShow` - so decided to …

chore: simplify show href construction to only consider displayable

---

src/schema/v2/previewSavedSearch/__tests__/previewSavedSearch.test.ts
src/schema/v2/previewSavedSearch/__tests__/searchCriteriaLabel.test.ts
src/schema/v2/previewSavedSearch/searchCriteriaLabel.ts
src/schema/v2/previewSavedSearch/suggestedFilters.ts

Akin to https://github.com/artsy/metaphysics/pull/5986 , DataDog reveals internal use from MP to our Gravity GraphQL endpoint using data loaders, which can now be switched to use the new data loaders backed by vanilla REST endpoints.

chore: replace internal use of GravQL for artist series with REST

---

src/schema/v2/homeView/HomeViewComponent.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/sections.ts

This PR comes as a follow-up on https://github.com/artsy/metaphysics/pull/5963#issuecomment-2326108590
Some artwork sections, define their own URL, however some others will be using the generic `home-view/sections/sectionID` route. In this PR, I am setting the `href` to null in the sections where we want the default behaviour to be used.

chore: remove href from generic artwork rails

---

src/schema/v2/homeView/withHomeViewTimeout.ts

Not sure if we want this change, but without it is not very clear for me which section timed out:
```graphql
{
"errors": [
{
"message": "Timeout of 2000ms",
"locations": [
{
"line": 39,
"column": 13
}
],
"path": [
"homeView",
"sectionsConnection",
"edges",
1,
"node",
"artworksConnection"
],
"stack": [...]
}
]
}
```
With this change developer can notice which section failed right away:
```graphql
{
"errors": [
{
"message": "[homeView section #home-view-section-new-works-for-you]: Timeout of 2000ms",
"locations": [
{
"line": 39,
"column": 13
}
],
"path": [
"homeView",
"sectionsConnection",
"edges",
1,
"node",
"artworksConnection"
],
"stack": [...]
}, 
{
"message": "[homeView section #home-view-section-marketing-collections]: Timeout of 2000ms",
"locations": [
{
"line": 79,
"column": 13
}
], …
```

feat: slightly more verbose errors for home view resolvers

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts
src/schema/v2/sale/index.ts

This may not improve performance from end-user perspectives since backend requests from MP are parallelized. Removing unnecessary ones I think always makes sense since you keep all the equivalent data that's being queried, but less requests.
In this case, I went through uses of this loader, and made sure we were consistent in the arguments being used. This prevents a query from being issued which results in two separate requests which actually are identical (but can't be combined by data loader due to different arguments).

chore: always use sale's database id when querying saleArtworkLoader

---

src/schema/v2/artwork/taxInfo.ts

See [Slack](https://artsy.slack.com/archives/C03N12SR0RK/p1726063808864249?thread_ts=1725961290.888429&cid=C03N12SR0RK) for context. The "learn more" link in the shipping and taxes section of the artwork page is broken. The team has merged some articles and this updates the link accordingly.

fix: update help article link for taxes

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

This PR flips the precedence of INCREASED_INTEREST and CURATORS_PICK for the `primaryLabel` value in `artwork.collectorSignals`.
Resolves [EMI-2075]
[EMI-2075]: https://artsyproduct.atlassian.net/browse/EMI-2075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2075): update precedence of collectorSignal.primaryLabel

---

src/lib/loaders/batchSaleArtworkLoader.ts

In staging, was seeing that we were sometimes batching in sizes _less_ than 20, _and_ also when we were over-fetching.
Both of these had the same underlying cause: the loader was being invoked multiple times for the same arguments - need to dedupe those in order to guarantee we're batching at 20 (and not over-fetching).

chore: misc batched loader updates

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

Thie PR adds an optional argument to the `collectorSignals.primaryLabel` field to ignore specific labels on the `primaryLabel` field. See tests for usage.
Resolves [EMI-2076].
[EMI-2076]: https://artsyproduct.atlassian.net/browse/EMI-2076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2076): add arg to suppress primary labels in collector signals

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/index.ts
src/schema/v2/schema.ts

This allows us to query for generally support attributes across all sections without needed a named fragment like `... on HomeViewSectionGeneric`. This does switch the connection from exposing a Union to an Interface, but all else seems to work exactly the same.
I don't see much of a downside here. There was some [recent discussion in Slack](https://artsy.slack.com/archives/C05EQL4R5N0/p1726078732679849?thread_ts=1726069270.194679) regarding the `matchConnection` field using a union type instead of an interface implemented for `searchConnection` but I think the real problems with the `searchConnection` field stems more from [the query introspection and this error](https://github.com/artsy/metaphysics/blob/7bd5e7a988f761185a2310b3132eca9533750ca0/src/schema/v2/search/SearchResolver.ts#L64-L …

chore(homeView): switch from union to interface

---

src/lib/loaders/__tests__/batchSaleArtworkLoader.test.ts
src/lib/loaders/batchSaleArtworkLoader.ts

Follow-up to adding this batch loader, adding specs, and with one real change: adding a `.catch` in our array of promises being invoked via `Promise.all` (+ spec).

chore: add specs and guard in for batch sale artwork loader

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewComponent.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/sections/index.ts

Add `ownerType` to viewAll behaviors with an explicit `href` provided so we can reliably pass this value through to analytics event payloads.

chore(analytics): add ownerType value to home view viewAll signals

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

https://artsyproduct.atlassian.net/browse/EMI-2052
~Return `null` instead of `0` for the `artwork.collectorSignals.auction.lotWatcherCount` if the lot is closed for bidding.
I got the lot closed logic from the current `lotClosesAt` field, so any feedback is welcome on that.~
Return no auction data if the lot is closed for bidding.

feat(EMI-2052): avoid returning lotWatcherCount for closed lots

---

src/schema/v2/homeView/sections/RecommendedArtworks.ts

This was mistakenly set to `recommendedArtistsRail`.

chore(analytics): small fix for RecommendedArtworks contextModule value

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

The type of this PR is **fix**
This PR skips checks for curators' pick and increased interest signals on auction artworks.
This PR resolves [EMI-2093].
[EMI-2093]: https://artsyproduct.atlassian.net/browse/EMI-2093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2093): remove ineligible signals from auction artworks

---

.circleci/config.yml

This removes a redundant dependency in the CI graph, but doesn't have any practical effect.

fix: remove redundant CI dependency

---

_schemaV2.graphql
src/lib/stitching/gravity/__tests__/stitching.test.ts
src/lib/stitching/gravity/schema.ts
src/lib/stitching/gravity/v2/stitching.ts

I've finally started working on viewing rooms un-stitching! One weird thing I've noticed is that there are "duplicates" of connection definitions coming from Gravity: [ViewingRoomConnection](https://github.com/artsy/metaphysics/blob/9271468efc011386216fc146580306a3148f82d2/_schemaV2.graphql#L21822) and [ViewingRoomEdge](https://github.com/artsy/metaphysics/blob/9271468efc011386216fc146580306a3148f82d2/_schemaV2.graphql#L21837) vs [ViewingRoomsConnection](https://github.com/artsy/metaphysics/blob/9271468efc011386216fc146580306a3148f82d2/_schemaV2.graphql#L21905) and [ViewingRoomsEdge](https://github.com/artsy/metaphysics/blob/9271468efc011386216fc146580306a3148f82d2/_schemaV2.graphql#L21920) (last two are plural). First two come from …

feat: expose Gravity's viewingRoomsConnection to replace deprecated viewingRooms query

---

src/schema/v2/filterArtworksConnection.ts

Noticing this lil one, it crashes when the value isn't available.

fix: dont crash if requesting followedArtists count w/o followed artist agg specified

---

src/lib/featureFlags.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
src/schema/v2/homeView/helpers/isSectionDisplayable.ts
src/schema/v2/homeView/index.ts
src/schema/v2/homeView/sections/FeaturedFairs.ts
src/schema/v2/homeView/sections/index.ts
src/schema/v2/homeView/zones/__tests__/legacy.test.ts
src/schema/v2/homeView/zones/legacy.ts

https://artsyproduct.atlassian.net/browse/ONYX-1311
This PR adds a pattern for selectively enabling home view sections via Unleash flags. Those flags can take advantage of the usual Unleash capabilities, such as constraining to set of specific user IDs.
I have created a [`onyx_enable-home-view-section-featured-fairs`](https://unleash.artsy.net/projects/default/features/onyx_enable-home-view-section-featured-fairs) flag which controls the actual `FeaturedFairs` home view section in this PR. 
That one was [cited](https://www.figma.com/board/kgm28u8rZLh3EfznOuOYSe/Homefeed-Versions?node-id=310-704&node-type=table&t=QtUKndCidPTPMG47-0) as a section whose fate is TBD, so seemed like a good enough guinea pig for this pattern. And may give us some early insight into any latency concerns re: …

feat(homeView): add a feature-flagging pattern for home view sections

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/CommerceOptIn/__tests__/commerceOptInReportMutation.test.ts
src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts
src/schema/v2/schema.ts

[AMBER-1036]
Add a mutation that when hit, it generates the report containing eligibility data for Commerce Opt In for a given partner and send it to the current user's email address.
Example:
```graphql
mutation
{ 
commerceOptInReport(input: { id: "<partner-id>", exactPrice: true, certificateOfAuthenticity: false, framed: false, pickupAvailable: true}) {
__typename
commerceOptInReportMutationOrError {
__typename
... on CommerceOptInReportSuccess {
createdCommerceOptInReport {
message
}
}
... on CommerceOptInReportFailure {
message
}
}
}
}
}
```
cc @artsy/amber-devs 
[AMBER-1036]: https://artsyproduct.atlassian.net/browse/AMBER-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(AMBER-1036): Create mutation to generate artworks eligibility report

---

src/schema/v2/homeView/helpers/getSectionsForUser.ts
src/schema/v2/homeView/zones/__tests__/default.test.ts
src/schema/v2/homeView/zones/default.ts

We initially created support for the "zone" concept thinking that we would switch from a "legacy" set of sections to a completely different set of sections, possibly backed by multiple zones.
That need seems less clear and we're now planning more incremental changes, often backed by feature flags or A/B testing setup, to a default set of sections.
This commit removes the label "legacy" from this set of sections in favor of a more neutral "default" name.

chore: rename legacy zone to default

---

src/schema/v2/homeView/helpers/__tests__/isSectionDisplayable.test.ts
src/schema/v2/homeView/helpers/isSectionDisplayable.ts
src/schema/v2/homeView/sections/index.ts

Here we add the ability for a section to define its own displayability check that can govern whether the section should be displayed, considering any arbitrary data or condition _beyond_ the standard ones (auth, feature flags) that we've already defined
(See https://github.com/artsy/metaphysics/commit/d9562a59558fd710653ceb7cfce446dfe3cb9a38  for a less noisy view)

feat(homeView): define an optional displayability check per section

---

src/schema/v2/homeView/sections/_ExampleSection.ts

Tiny follow-up to #6053  that updates the `ExampleSection`

docs: add new display check to ExampleSection

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/sections/index.ts

This will allow devs to optionally omit contextModule (as well as other ownerType value current nullable) from the concrete section defintion while development is ongoing.
Sections shipped to production users should have these values specified and that usually requires some alignment with data to determine values and adding those values in our analytics schema package: [artsy/cohesion][].
[artsy/cohesion]: https://github.com/artsy/cohesion
cc/ @joeyAghion

chore: drop type/schema enforcement for home view section contextModule

---

workers/caching/metaphysics-cdn.ts

Noticed some Sentry errors resulting from the new preflight handling (https://github.com/artsy/metaphysics/pull/6048). This is the 2nd time an inconsequential header causes production issues, so I think we should probably respond dynamically instead of this allow-list.

fix: 'Request header field User-Agent is not allowed by Access-Control-Allow-Headers

---

workers/caching/metaphysics-cdn.ts

This incorporates Metaphysics' old behavior, of reflecting `Access-Control-Request-Headers` dynamically, to the worker's implementation. I referenced the `cors` module's [source](https://github.com/expressjs/cors/blob/791983ebc0407115bc8ae8e64830d440da995938/lib/index.js) and docs to understand the rules and quirks.

fix: allow headers dynamically in response to CORS preflight requests

---

src/lib/__tests__/cache.test.ts
src/lib/cache.ts

This comment - https://github.com/artsy/metaphysics/pull/6067/files#r1779150198 - made me 🦆 myself into thinking -
Datadog seems to automatically pick up `new Error("cache miss")`. Since we're `catch`'ing these and not actually doing anything with them (even when there are other `reject`'s from the cache - even real errors) besides falling thru to the API - this might be a simple fix that helps clean up Datadog.
Basically - cache misses are not errors, so we shouldn't have `new Error` for them.
Simpler version of https://github.com/artsy/metaphysics/pull/6067

fix: dont create new Error for cache miss

---

hokusai/production.yml

We experimented with a lower target CPU utilization [recently](https://artsy.slack.com/archives/CA8SANW3W/p1727625446428559?thread_ts=1727453010.022849&cid=CA8SANW3W), and found that it somewhat mitigated spikes in latency. Otherwise, Metaphysics would operate at low scale but expend increasing amounts of time waiting for HTTP requests, eventually timing out. We still don't have a diagnosis of the root cause, and those requests don't appear to be timing out upstream, but this configuration change allows the deployment to scale up more often and more liberally, spreading the load and decreasing the worst spikes.

fix: lower target CPU utilization, allowing greater scale

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/sections/DiscoverMarketingCollections.ts
src/schema/v2/homeView/sections/index.ts
src/schema/v2/homeView/zones/__tests__/default.test.ts
src/schema/v2/homeView/zones/default.ts

Discover Marketing Collection Component
This PR introduces the new **Discover Marketing Collection** component to the homeView:
[Ticket (figma url in the ticket)](https://artsyproduct.atlassian.net/browse/DIA-861)
Component Preview
Query
Response
The placement, content collections, component style, and wording are still being refined and may change as we continue to complete the feature.

feat: add discover marketing collections to homeview

---

src/schema/v2/homeView/sections/TrendingArtists.ts

Add missing `totalCount` to `home-view-section-trending-artists` section. Because it is missing - this section is not displayed at all (because of this [condition](https://github.com/artsy/eigen/blob/main/src/app/Scenes/HomeView/Sections/HomeViewSectionArtists.tsx#L72) in Eigen).
```graphql
query {
homeView {
section(id: "home-view-section-trending-artists") {
... on HomeViewSectionArtists {
artistsConnection(first: 0) {
totalCount
}
}
}
}
}
```
```json
{
"data": {
"homeView": {
"section": {
"artistsConnection": {
"totalCount": 12
}
}
}
}
}
```
There are other sections that do not return totalCount. Although they do not result to a component not being displayed - I think it's worth fixing all of them. I will create a ticket.

fix: add totalCount to trending artists section

---

src/schema/v2/me/__tests__/recentlyViewedArtworks.test.ts
src/schema/v2/me/recentlyViewedArtworks.ts

This PR should fix a pagination issue for `recentlyViewedArtworksConnection` query (actually any query which uses `RecentlyViewedArtworks` GraphQL field config). Currently `recentlyViewedArtworksConnection` always returns first N recently viewed artworks regardless of cursor (offset, page) provided. 
Here I'm requesting first 2 artworks:
```graphql
query {
me {
recentlyViewedArtworksConnection(first: 2) {
pageInfo {
endCursor
}
edges {
node {
title
}
}
}
}
}
```
Pay attention to returned artworks - Golf Sale and Swimmers with Towel.
```json
{
"data": {
"me": {
"recentlyViewedArtworksConnection": {
"pageInfo": {
"endCursor": "YXJyYXljb25uZWN0aW9uOjE="
},
"edges": [
{
"node": {
"title": "Golf Sale"
}
},
{
"node": {
"title": "Swimmers with Towel"
}
}
]
}
}
}
}
```
Requesting next to artworks …

fix: fix broken pagination for recently viewed artworks query

---

_schemaV2.graphql
src/schema/v2/marketingCollections.ts

Exposes `format` arg so that we can strip the link syntax for meta tags.
Edit: I had to expose a new field because the default arg would make this a breaking change. I can correct this once I switch Force over though.

fix(marketingcollection): exposes arguments for formatting markdown

---

_schemaV2.graphql
src/schema/v2/homeView/HomeViewSection.ts
src/schema/v2/homeView/sections/ExploreByMarketingCollectionCategories.ts

Follow-up on #6058 
Change the route name to `/collections-by-category/foo` on the Explore By Categories element.

feat(DIA-857): ExploreBy adjust wrong field and href route

---

_schemaV2.graphql
src/schema/v2/Alerts/index.ts

Retire custom `AlertsEdgeFields` as they are no longer in use
The usage has been retired in Volt and continued to be retired in gravity
Retired gravity code:
- https://github.com/artsy/gravity/pull/18180
- https://github.com/artsy/gravity/pull/18177
- https://github.com/artsy/gravity/pull/18176

chore: Retire custom AlertsEdgeFields

---

src/schema/v2/artist/index.ts

We see a mismatch when the cover artwork is unpublished. Some queries that propagate an admin's access token will continue to resolve the unpublished artwork. Other queries that are `@cacheable` won't - this mismatch (combined with more prefetching) - leads to images flashing/changing/disappearing.
The fix is to not return unpublished artworks from here by explicitly using a loader that won't.

fix: use unauthenticated artworkLoader for coverArtwork on Artist

---

src/schema/v2/artist/index.ts

So, this field can be cached for up to 24 hours - above the fold artist query.
But, as you prefetch artworks in the artist page grid, that query may be live and uncached - and if an admin has recently changed the cover artwork, you'd get back a totally different one in the prefetch - different `id` and everything.
This has the effect of messing up the Relay store normalization (or rather, it's working as designed), and that component which initially rendered gets lost.
So, let's treat this field with a synthetic id that's static (still scoped to the artist) - and see if that helps this behavior.

chore: return a static `id` for `coverArtwork` for an Artist

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

https://artsyproduct.atlassian.net/browse/PBRW-72
There seems to be a regression after https://github.com/artsy/eigen/pull/10833 that causes the send inquiry button disabled on Eigen when there is no inquiry questions selected. The inquiry artworks associated with the Kamala sale ([example](https://www.artsy.net/artwork/hugh-hayden-potus)) do not return inquiry questions because of [existing condition check](https://github.com/artsy/metaphysics/blob/82f73dd0fcfdd033783cfeeebaadcbab27609c62/src/schema/v2/artwork/index.ts#L735-L736). I propose we decouple inquireability from auctions here, and rely on the main `artwork.inquireable` to determine the inquireability. I think after this change, app users should be able to see the questions and at least able to send an inquiry from the app. …

fix: allow inquiry questions on inquireable artworks

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

Resolves [EMI-2124]
Depends on https://github.com/artsy/gravity/pull/18199
This PR:
- Improves handling of a query for a sale artwork that may come back null.
- Changes our 'is this lot open for bidding? if not, then there are no auction signals' logic to rely on gravity rather than a time comparison on metaphysics.
- Changes our 'has live integration started' logic to rely on a newly-exposed gravity `live_integration_started` property.
cc @artsy/emerald-devs 
[EMI-2124]: https://artsyproduct.atlassian.net/browse/EMI-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2124): no auction signals if no sale artwork, avoid local time comparisons

---

src/schema/v2/partner/partner.ts

Logged-in, we would always use an uncached data loader to return these `cities` - yet the `private` argument which would even return privileged data isn't being used (and `total_count` for some reason was?!).

chore: use cached data loader for fetching `cities` on `Partner`

---

_schemaV2.graphql
src/lib/stitching/vortex/__tests__/pricingContext.test.ts
src/schema/v2/artwork/index.ts
src/schema/v2/artworkResult/__tests__/index.test.ts
src/schema/v2/conversation/__tests__/submit_inquiry_request_mutation.test.ts
src/schema/v2/test/utils.ts

Sort of minor, but we were never using a cached data loader to fetch artists for an artwork/artwork page. There _might_ be some use-cases where we do want to fetch a private artist, so I left this as opt-in, and on the artwork page we can include `private: false`.

chore: use uncached data loader to fetch an artworks artists

---

src/schema/v2/artwork/index.ts

We have `sale_ids` denormalized onto artworks exactly for this reason! You can tell if an artwork is in a sale or not just by fetching the artwork itself. Of course you may need to fetch the sale (or lot standings) to see if the sale is 'live', or fulfill other things, but you can always short-circuit if it's _not_ in a sale.

chore: skip lotStandings fetch when the artwork isnt in an auction

---

src/schema/v2/partner/partner.ts

Seeing traces that imply this is undefined (and can't call `map` on that). I can't actually reproduce this, but for now - coalesce it to `[]`

chore: guard against a null/undefined `body` when resolving partner locations

---

src/config.ts
src/lib/apis/weaviate.ts
src/lib/loaders/api/index.ts
src/lib/loaders/loaders_without_authentication/index.ts
src/lib/loaders/loaders_without_authentication/weaviate.ts

This PR adds Weaviate integration to Metaphysics.  
It sets up unauthenticated loaders, currently accessible only through the staging VPN. I will follow up on resolver types once [this PR](https://github.com/artsy/quantum/pull/36/files) is merged.

feat: add weaviate integration

---

src/schema/v2/partner/partner.ts

We see a large volume of: `GraphQLError: Expected Iterable, but did not find one for field Partner.locations`
It's not actually clear to me why this is happening / a repro! Clearly we're...not returning a list where we should be? But stubbing loader responses of `null`, `[]`, `[null]`, `[[]]` doesn't trigger it.
So I'm a bit surprised, but this feels like a sensible default/update that we can try and see if that clears up the errors (would still love to see a repro though). No test cause no repro

fix: always return a list for Partner.locations

---

src/schema/v2/homeView/sections/FeaturedFairs.ts

Addresses https://www.notion.so/artsy/Subtitle-under-Featured-Fairs-should-it-be-in-sentence-case-11acab0764a0805cb0ead821f47be498
Small QA fix, now follows our [house guidelines](https://docs.google.com/document/d/1NoBSYM-EBA4b6rdux-8CQJWneXcglISHzZNvSkKFDh0/edit#bookmark=id.ki32zyvvxu5h) for subheadings.

fix(homeView): casing in FeaturedFairs section

---

src/lib/loaders/api/loader_without_authentication_factory.ts

Great spot from @joeyAghion .
Consider the scenario:
- a request using a loader with `headers: true` comes in - and caches the data and headers
- a request using a loader without `headers: true` comes in....but with the same resulting arguments/cache key as that first request - it gets served the cached data that's in the wrong form it was expecting
Partner locations seem to be a big offender of it b/c we have two loaders pointing to the same endpoint (easily called w/ identical arguments) - but one specifies `headers: true` and one doesn't.
It's ok to not modify their keys w.r.t to DataLoader - if all of their arguments are identical, we can just make one request to fulfill both data loader requests.
But - they must then be cached differently.
So the fix is - include that `headers` …

fix: include headers: true info in cache key

---

_schemaV2.graphql
src/data/exchange.graphql

https://artsyproduct.atlassian.net/browse/EMI-2085
Following https://github.com/artsy/exchange/pull/2270, this updates MP schema to exposed the new `paymentSet` field on an order.
This picks up the update in https://github.com/artsy/metaphysics/pull/6113. Let's see which one gets merged first! 😬

chore: update schema for Exchange

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/weaviate.ts
src/schema/v2/__tests__/discoverArtworks.test.js
src/schema/v2/createDiscoveryArtworkReferenceMutation.ts
src/schema/v2/createDiscoveryLikedArtworkMutation.ts
src/schema/v2/discoverArtworks.ts
src/schema/v2/schema.ts

This PR introduces the `discoverArtworks` query type and the `createDiscoveryArtworkReference` mutation used for Infinite Discovery:
```graphql
discoverArtworks(
after: String
before: String
first: Int
last: Int
userId: String
): ArtworkConnection
```
```graphql
createDiscoveryArtworkReference(
input: CreateDiscoveryArtworkReferenceMutationInput!
): CreateDiscoveryArtworkReferenceMutationPayload
```

feat: add infinite discovery type and mutation

---

_schemaV2.graphql
src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts

This PR addresses [AMBER-1084]
We're adding `locationID` as a potential attribute for CommerceOptIn and CommerceOptInReport. Will follow up with artsy_shipping in separate PR.
[AMBER-1084]: https://artsyproduct.atlassian.net/browse/AMBER-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(AMBER-1084): Commerce Opt in and Opt in Report allow for locationID param 

---

src/schema/v2/homeView/sectionTypes/Activity.ts
src/schema/v2/homeView/sectionTypes/Articles.ts
src/schema/v2/homeView/sectionTypes/AuctionResults.ts
src/schema/v2/homeView/sectionTypes/Fairs.ts
src/schema/v2/homeView/sectionTypes/MarketingCollections.ts
src/schema/v2/homeView/sectionTypes/Sales.ts
src/schema/v2/homeView/sections/ActiveBids.ts
src/schema/v2/homeView/sections/Auctions.ts
src/schema/v2/homeView/sections/FeaturedFairs.ts
src/schema/v2/homeView/sections/MarketingCollections.ts
src/schema/v2/homeView/sections/SimilarToRecentlyViewedArtworks.ts

As [pointed out a while back](https://artsy.slack.com/archives/C05EQL4R5N0/p1724099057516639?thread_ts=1724081856.316439&cid=C05EQL4R5N0) by @mzikherman, it's technically incorrect to return `[]` for an empty connection.
Instead we have an `emptyConnection` helper that returns the correct shape — 
https://github.com/artsy/metaphysics/blob/0f2e865fbe86b705cace2df46018daf1c7dedaec/src/schema/v2/fields/pagination.ts#L235-L238
We applied this a little bit after that comment, but not everywhere.
This PR fixes that. Confirmed that all sections still look good in simulator 👍🏽

fix(home view): shape of empty connections

---

_schemaV2.graphql
src/data/exchange.graphql

The Force/Relay setup there doesn't seem to like this directive, so for now just remove it manually (but we should follow-up to ensure it doesn't come back in Exchange).

fix: removes @specifiedBy directive from exchange schema

---

src/schema/v2/homeView/helpers/__tests__/withHomeViewTimeout.test.ts
src/schema/v2/homeView/sections/ShowsForYou.ts

Follow-up to [this discussion](https://github.com/artsy/metaphysics/pull/6107/files#r1792716561) 
This tweaks the `ShowsForYou` resolver — known to be slow — to allow a more generous timeout in dev/staging, while still honoring the `HOME_VIEW_RESOLVER_TIMEOUT_MS` env var in production.

feat(home view): allow per-env timeout for shows resolver

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

Building on top of https://github.com/artsy/gravity/pull/18243, this PR updates the edge of the hits connection to include this `PartnerSearchCriteria` id so that we can properly track from the "Matched Alerts" tab in CMS.
https://artsyproduct.atlassian.net/browse/AMBER-1090

chore: Add partner search criteria id to hits edge AMBER-1090

---

_schemaV2.graphql
src/schema/v2/Invoice/invoice.ts

Minor - need this field so we can allow a payment to be made in this numeric amount.

chore: add remainingMinor to Invoice

---

src/schema/v2/__tests__/credit_card.test.ts
src/schema/v2/credit_card.ts

https://artsyproduct.atlassian.net/browse/EMI-2063
We use the credit card brand when displaying card icons, and in the co-branded card compliance project, we'll want to display the preferred card network (that users select) in the icon so that users understand which network will be used to process a card transaction.

feat: return preferred network as card brand when available

---

_schemaV2.graphql
src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts

This PR addresses [AMBER-1085](https://artsyproduct.atlassian.net/browse/AMBER-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
We're adding artsyDomesticShipping as a potential attribute for CommerceOptIn and CommerceOptInReport. 
[AMBER-1085]: https://artsyproduct.atlassian.net/browse/AMBER-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(AMBER-1085): update Commerce Opt in and Opt in Report allow for artsyDomesticShipping param

---

src/schema/v2/homeView/sections/LatestArticles.ts

This PR fixes an issue with the new home view latest articles rail. We were missing the default sorting props and that resulted in returning different articles in the rail compared to the screen.
**Screenshot after changes**

feat: update query args for homeview > latest articles

---

_schemaV2.graphql
src/schema/v2/me/task.ts

Follow up for https://github.com/artsy/gravity/pull/18261
We can remove instead of deprecating as no one is using it yet

chore: remove action message

---

_schemaV2.graphql
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR does two things:
1. Adds the ability to pass in a `certainty` argument that gets passed along to `weaviate`. In effect, `certainty` is a[ similarity rating between 0 and 1](https://weaviate.io/developers/weaviate/api/graphql/search-operators#variables-1), where 1 is almost identical and 0 is an opposite. `certainty` and `distance` get at the same thing, so I am not including `distance`, for now, despite it being the newer approach recommended by `weaviate`.
2. Adds the ability to `sort` by `certainty` level. Defaults to returning more similar artworks first (i.e. artworks with higher `certainty` scores).
Together this gives us greater ability to configure the results coming back from `weaviate`. I'm particularly interested if we get better recommendation by moving slightly away …

feat: support certainty config for discoverArtworks

---

_schemaV2.graphql
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

Patches #6152 to use the correct type for `certainty` argument. Should be a float, not integer.

fix: use float type instead of int type for certainty

---

_schemaV2.graphql
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR adds a fallback for infinite discovery users who don't have any existing "likes", so that we can still produce some artworks for them to react to and start getting personalized recommendations. The fallback query, just gets the first `x` amount (set by `limit`) of artworks from `weaviate`. Additionally, I've added an `offset` argument so that we can get variation in our starting point.

feat: add fallback for discovery users without liked artworks

---

src/schema/v2/homeView/sections/ExploreByCategory.ts

Use `OwnerType.collectionsCategory` as `entityType` of `ExploreByCategory`.

feat(HomeViewSectionCards): use the OwnerType from analytics in entityType

---

.circleci/config.yml

Noticed that we're waiting to push the staging image until after we've run the tests, but this can be parallelized since the deploy step doesn't go out until other checks pass. So optimize this via less staggering, like we do in force. 

ci(circle): Improve CI times more

---

.circleci/config.yml
scripts/push-schema-changes.js

This PR splits the push schema job into 7 shards in order to optimize this expensive step on `main` branch(around 11 minutes).
There's a dummy execution [here](https://app.circleci.com/pipelines/github/artsy/metaphysics/24197/workflows/e85dd38d-c367-4b9c-8c06-c524edca5ee0/jobs/49897) with log outputs for each repo attempt.

feat(CI): split schema push job into shards

---

_schemaV2.graphql
src/schema/v2/artworks.ts

Updating to trigger a schema change, and to see how long the new sharded push-schema-change job takes.

ci(push-schema-changes): trigger schema update to see cycle times

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

It's helpful to have a field that can be used to render a save button in the correct state - saved to any 'saves' list (default or not). Then, we can defer checking non-default list inclusion only when someone unsaves a saved artwork (to see if it was saved in any non-default lists, which prompts a modal interaction).

feat: add isSavedToAnyList to Artwork

---

_schemaV2.graphql
src/schema/v2/me/artworksCollectionsBatchUpdateMutation.ts

The one weird part here is that this mutation technically can operate on a list of artworks, however I don't see any use-cases in Force of that (and that sounds like an interesting 'powerful' UI that I'm not sure where that might be offered - batch updating list memberships _for_ a batch of artworks?).
So, let's just return the artwork.
This lets us add `isSavedToAnyList` and skip Relay store updating in https://github.com/artsy/force/blob/63b000f40aa8dcf3a6a99edad7098874a80bea7f/src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/useSelectArtworkLists.ts#L53

chore: add singular artwork to batch collection update mutation

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/home/results.ts
src/schema/v2/me/index.ts

Trying to mark the old genomic recs graphql loader/endpoint as deprecated, since it was decided in https://github.com/artsy/gravity/pull/18204 to not remove it entirely due to some old mobile clients.

chore: mark the genomic recs gravity loader as deprecated

---

package.json
yarn.lock

The type of this PR is: chore
Description
This PR bumps package.json version of artsy-xapp to use version 2.0.0. The new versions uses native node-fetch instead of superagent. See https://github.com/artsy/artsy-xapp/pull/11 for details.

chore: bump artsy-xapp to 2.0.0

---

src/schema/v2/infiniteDiscovery/resetDiscoveryArtworkReferencesMutation.ts

Patch of #6211 to use the config base url for `weaviate`.
@egdbear - apologize if this is what you were saying in https://github.com/artsy/metaphysics/pull/6211#discussion_r1832883727, and I just didn't understand.

fix: user weaviate internal url in resetDiscoveryArtworkReferencesMutation

---

_schemaV2.graphql
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR adds the recommendation based on [Elastic Search Artwork Similarity Index](https://github.com/artsy/gravity/blob/8b6d8cbfbeb3d55e2d39b365fb3ddce9e075d3b3/app/models/search/indexes/artwork_similarity_index.rb#L1). 
**Recommendation Logic:**
- New Users (No Saved Artworks): Recommendations are generated using the "curators-picks" collection.
- Users with At Least One Saved Artwork: Recommendations are generated using 2 random artworks from the "curators-picks" (we could take more artworks) collection along with artworks from the user’s saved list.
- Users with Multiple Saved Artworks: Recommendations are generated using 2 random artworks from the "curators-picks" collection plus all artworks from the user’s saved collection.
- Maximum Artwork Limit: Recommendations are capped at 30 …

feat: add ES recommendations for infinite discovery

---

_schemaV2.graphql
src/schema/v2/infiniteDiscovery/likedDiscoveryArtworks.ts
src/schema/v2/schema.ts

This PR adds a `likedDiscoveryArtworks` so that we can easily get the artworks a user has liked from weaviate (not just the recommended artworks). Primary motivation for this is to be able to display a list of artworks they have "liked" in the testing prototype.

feat: add likedDiscoveryArtworks

---

jest.config.js

This PR makes it possible to once again run Jest's code coverage tool on demand in MP.
Brief history:
- Automated coverage reporting was added in https://github.com/artsy/metaphysics/pull/2098
- And the orb that enables it was removed in https://github.com/artsy/metaphysics/pull/3822
However the configuration was left in place, which makes it difficult to run code coverage commands locally. (All the output gets shunted to `./coverage` rather than the convenient terminal output you see e.g. [here in Eigen](https://github.com/artsy/eigen/pull/11068))
There was [some talk](https://artsy.slack.com/archives/C2TQ4PT8R/p1730942547171529) of enabling this again in CI. If we do so let's treat that as a separate effort and try to configure it such that it does not interfere with local usage of the …

chore: remove stale coverage settings

---

src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR updates the artwork parameters used for querying the artworks from Elastic Search.
Referring to [this comment](https://github.com/artsy/metaphysics/pull/6219/files#r1837943508), it would make sense during the research phase to include something closer to what we’d ultimately deploy in production

fix: update the artwork params when querying for infinite discovery

---

src/schema/v2/infiniteDiscovery/resetDiscoveryArtworkReferencesMutation.ts

In some more testing of the prototype, I realized `PATCH`ing the `likedArtworks` and `seenArtworks` fields doesn't update the vector. So the user would still effectively have their previous `likedArtworks` persisted. 
This changes the implementation to delete the user instead. This works because we [always check for a user when requesting artworks and create one if it doesn't exist](https://github.com/artsy/metaphysics/blob/aa9c9f57bbc284984c562122fa2c196bb5218011/src/schema/v2/infiniteDiscovery/discoverArtworks.ts#L156-L170).
Will follow up with better naming.

refactor: delete infinite disco user on reference reset

---

src/schema/v2/infiniteDiscovery/discoverArtworks.ts

Another quick fix to ensure that cold start users get a random sampling from all curated artworks. With the previous implementation, it was just shuffling this first `x`, where `x` is the `limit` argument, which defaults to `15` client side.

fix: infinite disco cold start curated limit

---

src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/__tests__/authenticationStatus.test.ts
src/schema/v2/authenticationStatus.ts

This is the complement of https://github.com/artsy/gravity/pull/18332, which introduces a lightweight endpoint for the very frequent `authenticationStatus` queries. **Don't merge** until that's been released.
As discussed there, this is just an experiment and should be rolled back if the `me/ping` endpoint performs similarly to the `me` endpoint. (Although we can probably keep the new tests.)

chore(perf): switch to data-saving me/ping endpoint for authentication status

---

_schemaV2.graphql
src/schema/v2/system/__tests__/time.test.js
src/schema/v2/system/time.ts

Another tiny overhead-savings: resolve time queries immediately instead of making another request to Gravity. The 2 services share hosts and network-time configurations, so Metaphysics' system time should be _fine_ for client calculation purposes.
Will leave a few questions/comments inline...

feat: resolve time queries immediately instead of from main API

---

src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/GravityARImageType.ts
src/schema/v2/__tests__/viewingRoom.test.js
src/schema/v2/__tests__/viewingRoomSubsection.test.ts
src/schema/v2/viewingRoom.ts
src/schema/v2/viewingRoomSubsection.ts

Continuation of https://github.com/artsy/metaphysics/pull/6065 (viewing rooms unstitching)
This PR adds `viewingRoom.subsections` field:
```graphql
{
viewingRoom(id: "leslie-feely-alice-baber") {
subsections {
__typename
body
caption
image {
__typename
internalID
height
width
imageURLs {
__typename
normalized
}
}
internalID
title
}
}
}
```
Response:
```json
{
"data": {
"viewingRoom": {
"subsections": [
{
"__typename": "ViewingRoomSubsection",
"body": "",
"caption": "Alice Baber, 1972, photo by Richard Galef, Alice Baber Papers, AAA",
"image": {
"__typename": "ARImage",
"internalID": "e2185542-6cad-4916-b39c-4e5458f6066b",
"height": 1007,
"width": 1024,
"imageURLs": {
"__typename": "ImageURLs",
"normalized": "https://d32dm0rphc51dk.cloudfront.net/w6qTHWN4EWvAZh7Dxnto5A/normalized.jpg"
}
}, …
```

refactor(onyx-1404): add subsections to viewing room type

---

src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/__tests__/viewingRoom.test.js
src/schema/v2/__tests__/viewingRoomArtwork.test.ts
src/schema/v2/viewingRoom.ts
src/schema/v2/viewingRoomArtwork.ts

Continuation of https://github.com/artsy/metaphysics/pull/6065 (unstitching viewing rooms)
Adds `viewingRoomArtworks` field:
```graphql
{
viewingRoom(id: "leslie-feely-alice-baber") {
viewingRoomArtworks {
__typename
artworkID
internalID
published
}
}
}
```

refactor(onyx-1405): add viewing room artworks to viewing room type

---

src/schema/v2/__tests__/viewingRoom.test.js
src/schema/v2/partner/partnerArtworks.ts
src/schema/v2/viewingRoom.ts

Thanks again @mzikherman for suggesting to try `require` thingy, couldn't figure out where the error was coming from!
Follow-up: https://github.com/artsy/metaphysics/pull/6065#discussion_r1846229641
This PR adds partner artworks connection to viewing rooms:
```graphql
{
viewingRoom(id: "leslie-feely-alice-baber") {
partnerArtworksConnection(first: 1) {
totalCount
edges {
node {
title
}
}
}
}
}
```

refactor(onyx-1406): add partner artwork to viewing room type

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

As described in https://github.com/artsy/force/pull/14885#issuecomment-2494625571, our 2 major clients never need partners' "extended" properties when querying `Artwork.partner`. As a result, I hope it's safe to simply change that property's `shallow` argument to default to `true`. This avoids potentially many unnecessary API requests, and immediately benefits deployed clients.
(Of course, there _is_ some potential for developer confusion when documented properties come back as `null` in the `Artwork` context.)
As a precaution, I've dumped this updated schema locally (`yarn dump:local`) and confirmed that Force and Eigen both relay-compile successfully. For good measure I spot-checked Energy as well and didn't find any references to extended properties.

feat(perf): avoid API requests that are usually unnecessary for Artwork.partner

---

src/lib/gravityErrorHandler.ts
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/stitching/gravity/schema.ts
src/schema/v2/me/secondFactors/secondFactors.ts
src/schema/v2/schema.ts
src/schema/v2/viewingRooms/mutations/__tests__/createViewingRoomMutation.test.ts
src/schema/v2/viewingRooms/mutations/createViewingRoomMutation.ts

(This is one of many PRs for viewing rooms unstitching)
This PR adds `createViewingRoom` mutation. I've compared the responses between stitched and unstitched implementations and they mostly look the same, except errors (structure is the same, but error messages are different sometimes). I will either re-iterate, or will talk to Volt people to see if new errors are fine.

refactor: add create viewing room mutation (unstitching)

---

src/lib/stitching/__tests__/mergeSchemas.test.js
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts
src/schema/v2/artwork/context.ts

This updates two places that we were using the ES-backed `/related/shows` endpoint to fulfill queries that can be fulfilled by the regular database-backed `/shows` endpoint.
Should only be merged after https://github.com/artsy/gravity/pull/18382 is in production.

feat: switch some relatedShowsLoader usage to showsLoader

---

src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/stitching/gravity/schema.ts
src/schema/v2/schema.ts
src/schema/v2/viewingRooms/mutations/ARImageInput.ts
src/schema/v2/viewingRooms/mutations/__tests__/updateViewingRoomMutation.test.ts
src/schema/v2/viewingRooms/mutations/createViewingRoomMutation.ts
src/schema/v2/viewingRooms/mutations/updateViewingRoomMutation.ts
src/schema/v2/viewingRooms/mutations/viewingRoomInputAttributes.ts
src/schema/v2/viewingRooms/mutations/viewingRoomOrError.ts

This PR adds an unstitched version of `updateViewingRoom` mutation. The changes are hidden behind a feature flag.
To test:
```graphql
mutation {
updateViewingRoom(
input: {
viewingRoomID: "room-id"
image: { internalID: "image-id" }
attributes: {
body: "new body2"
endAt: "2024-11-24T00:00:00.000Z"
introStatement: "new intro"
pullQuote: "new quote 2"
startAt: "2024-11-21T00:00:00.000Z"
timeZone: "Europe/Rome"
title: "new title 2"
}
}
) {
viewingRoomOrErrors {
... on ViewingRoom {
title
}
... on Errors {
errors {
message
}
}
}
}
}
```

refactor(onyx-1408): add updateViewingRoom mutation (unstitching)

---

src/lib/stitching/gravity/schema.ts
src/schema/v2/schema.ts
src/schema/v2/viewingRooms/mutations/__tests__/publishViewingRoomMutation.test.ts
src/schema/v2/viewingRooms/mutations/__tests__/unpublishViewingRoomMutation.test.ts
src/schema/v2/viewingRooms/mutations/publishViewingRoomMutation.ts
src/schema/v2/viewingRooms/mutations/unpublishViewingRoomMutation.ts

> [!NOTE]
> The code in this PR is branched from nickskalkin/onyx-1408, as it depends on some of refactoring made there.
This PR adds an unstitched versions of `publishViewingRoom` and `unpublishViewingRoom` mutations. The changes are hidden behind a feature flag.
```graphql
mutation {
(un)publishViewingRoom(
input: { viewingRoomID: "room-id" }
) {
__typename
}
}
```

refactor(onyx-1410): add publish and unpublish viewing room mutations (unstitching)

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts
src/schema/v2/artwork/context.ts

Not for merging yet.
This shows the two invocations of `showsLoader` on the artwork page being able to short-circuit if the artwork doesn't contain any denormalized `show_ids` in the first place.
Should only be merged after https://github.com/artsy/gravity/pull/18384 is fully deployed.

feat: short-circuit shows call for an artwork if no show_ids

---

src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/stitching/gravity/schema.ts
src/schema/v2/viewingRoom.ts
src/schema/v2/viewingRooms/mutations/__tests__/updateViewingRoomArtworksMutation.test.ts
src/schema/v2/viewingRooms/mutations/__tests__/updateViewingRoomSubsectionsMutation.test.ts
src/schema/v2/viewingRooms/mutations/createViewingRoomMutation.ts
src/schema/v2/viewingRooms/mutations/deleteViewingRoomMutation.ts
src/schema/v2/viewingRooms/mutations/publishViewingRoomMutation.ts
src/schema/v2/viewingRooms/mutations/unpublishViewingRoomMutation.ts
src/schema/v2/viewingRooms/mutations/updateViewingRoomArtworks.ts
src/schema/v2/viewingRooms/mutations/updateViewingRoomMutation.ts
src/schema/v2/viewingRooms/mutations/updateViewingRoomSubsections.ts

> [!WARNING]
> I've included _schemaV2.graphql to this PR only to discuss the rest of differences between stitched / unstitched schemas
Made some fixes in order to make stitched / unstitched viewing room schemas look more alike.

refactor: fixes some misalignments between stitched / unstitched viewing rooms

---

src/lib/loaders/loaders_without_authentication/gravity.ts

Looking back at https://github.com/artsy/metaphysics/pull/6247 reminded me that the `systemTimeLoader` is now unused, and can be cleaned up.

chore(perf): clean up unused systemTimeLoader

---

package.json
src/lib/stitching/vortex/v2/stitching.ts

Fixes [this exception](https://app.datadoghq.com/error-tracking/issue/df966ba4-b190-11ef-8b7e-da7ad0900002?query=env%3Aproduction%20service%3Ametaphysics.graphql&fromUser=false&refresh_mode=sliding&from_ts=1733241390337&to_ts=1733327789945&live=true) (happens only when viewing room unstitching flag is enabled).
The reason is that vortex stitching code fallbacks to gravity schema for such requests:
```graphql
{
partner(id: "xxx") {
analytics {
rankedStats(objectType: VIEWING_ROOM, period: FOUR_WEEKS, first: 15) {
edges {
node {
value
entity {
... on ViewingRoom {
title
}
}
}
}
}
}
}
}
```
Now there is no need for such fallback - `viewingRoom` type is supported natively in metaphysics

fix: fix broken analytics.rankedStats query for unstitched viewing rooms

---

package.json
src/lib/featureFlags.ts
src/schema/v2/homeView/sections/InfiniteDiscovery.ts
src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts
src/schema/v2/homeView/sections/index.ts
src/schema/v2/homeView/zones/__tests__/default.test.ts
src/schema/v2/homeView/zones/default.ts
yarn.lock

This PR adds a new home view section for [Infinite Discovery](https://www.figma.com/design/BzXubI34mJlLU9CmmYip0p/Infinite-Discovery?node-id=917-27991&t=BJwsDAs7piAAOw6G-4) so that Diamond can start building it.

feat(DIA-1014): infinite discovery home view section

---

src/lib/featureFlags.ts
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

~DON'T MERGE YET. Will need to coordinate deploy with https://github.com/artsy/force/pull/14897, and we might want to include tracking changes.~ As this work becomes too complex to manage now it requires analytics changes. I decided to guard it behind a [feature flag](https://unleash.artsy.net/projects/default/features/emerald_clientside-collector-signals) so we can continuously and incrementally deliver (vs. releasing all at once).
To [load and render the partner offer signals on the client-side](https://github.com/artsy/force/pull/14897) and still render other primary labels (e.g. "increased interest" and "curators' pick") server-side, we'd want to remove partner offer from the `primaryLabel` field.
The separation of authenticated and unauthenticated data into different fields is also …

feat: remove partner offer from primary label

---

src/lib/artworkMediums.ts
src/schema/v2/__tests__/artworkMediums.test.ts

This PR is associated with [AMBER-1121] 
This change includes 'digital art' to artworkMediums, allowing it (and therefore its corresponding gene) to be filtered in artwork grids and alert setting functionality. 
[AMBER-1121]: https://artsyproduct.atlassian.net/browse/AMBER-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: adding digital art to artworkMediums for artwork grid filtering 

---

_schemaV2.graphql
src/schema/v2/jobs.ts

This change supports transitioning to the Ashby API for our job service. While Ashby doesn't provide direct department-based job querying, we do receive department names with each job record. Instead of introducing breaking changes by creating new job types and fields, I'm opting to handle the department grouping on the frontend rather than in Metaphysics. This approach lets us push the API integration and deprecate the jobs field on department type without introducing breaking changes to the schema.
I'll follow this up with a Force PR to switch over the grouping and then another Metaphysics PR which then replaces the API out from under it.

feat(job): exposes department name field

---

src/schema/v2/sale_artwork.ts

Looks like when sales are unpublished, this field (which is being requested as part of auction artworks in our standard artwork component in Force)- causes an exception which bubbles up in `errors`.
The front-end is defensive enough for this component-wise, _but_ it looks like prefetching doesn't 'commit' to the store if there's an error.
I think there might have been a bunch of old sales unpublished recently (?) - so we're noticing prefetch not working in some contexts.
Let's see if this helps out.

fix: guard agaunst unpublished sales in formattedEndDateTime

---

src/lib/semanticVersioning.ts
src/schema/v2/homeView/helpers/isSectionDisplayable.ts

Temporarily adding some verbose logging (along with a deploy block) to debug user agent issues with infinite disco

chore(debugging home view): chatty logs for home view sections

---

src/schema/v2/homeView/helpers/isSectionDisplayable.ts
src/schema/v2/homeView/sections/InfiniteDiscovery.ts
src/schema/v2/homeView/zones/__tests__/default.test.ts

Testing a theory whereby `@cacheable` directive inteferes with a section that specifies `requiresAuthentication: true`

fix(home view): relax auth requirement for infinite discovery card

---

src/lib/semanticVersioning.ts
src/schema/v2/homeView/helpers/isSectionDisplayable.ts

Removes the debug output from #6309, #6310, #6311 — after this hits staging we can remove the current deploy block.

chore: revert disco debugging logs

---

src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR adds constant values for args to avoid issues when there are no expected args.
✅ Added the `OPENSEARCH_API_BASE` and `OPENSEARCH_ARTWORKS_INFINITE_DISCOVERY_INDEX` env variablwes to staging.

fix: add the constant values for args

---

src/lib/infiniteDiscovery/findSimilarArtworks.ts
src/lib/infiniteDiscovery/getInitialArtworksSample.ts
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

- prevent artworks appearing twice in initial taste builder
- add collapse to query to allow only unique artworks/artists

fix: improvements for discoverArtworks

---

src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR adds backfill functionality for cases when there are fewer than 8 artworks. The requirement is always to have: - 8 artworks, plus 2 random picks (currently limited to curated collection).

feat: add backfill for search results

---

workers/caching/metaphysics-cdn.ts

Reverts artsy/metaphysics#6307
This doesn't harm anything, but we don't need it (no longer have need of tracking this on the front-end after prefetching) and no code > any code.

Revert "feat: add Access-Control-Expose-Header: Cf-Cache-Status to CDN worker"

---

_schemaV2.graphql
src/lib/stitching/gravity/schema.ts
src/schema/v2/schema.ts
src/schema/v2/viewingRooms.ts

When I've started viewing rooms unstitching, one weird thing I've noticed is that there are "duplicates" of connection definitions coming from Gravity: [ViewingRoomConnection](https://github.com/artsy/metaphysics/blob/9271468efc011386216fc146580306a3148f82d2/_schemaV2.graphql#L21822) and [ViewingRoomEdge](https://github.com/artsy/metaphysics/blob/9271468efc011386216fc146580306a3148f82d2/_schemaV2.graphql#L21837) vs [ViewingRoomsConnection](https://github.com/artsy/metaphysics/blob/9271468efc011386216fc146580306a3148f82d2/_schemaV2.graphql#L21905) and [ViewingRoomsEdge](https://github.com/artsy/metaphysics/blob/9271468efc011386216fc146580306a3148f82d2/_schemaV2.graphql#L21920) (last two are plural). First two come from [here](https://github.com/artsy/gravity/blob/7e77d2096fcf96167728eef950f …

fix: bring back unstitched viewingRooms query

---

_schemaV2.graphql
src/lib/infiniteDiscovery/findSimilarArtworks.ts
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR introduces two new parameters for discoverArtworks:
- **`useMltQuery`**  
- When set to `true`, combines k-NN search (visual similarity) with the "More Like This" (MLT) content similarity search.  
- **`mltFields`**  
- An array of fields that the MLT query will use to calculate similarity.  
**Visuals:**  
Example:
**Before** - knn only search 
**After** - mlt + knn search

feat: add improvements for discoverArtworks query

---

_schemaV2.graphql
src/lib/infiniteDiscovery/findSimilarArtworks.ts
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR enhances the OpenSearch query to include a hybrid search pipeline combining `more_like_this` and `knn` queries. Added normalization and combination processors for result scoring and a collapse response processor to filter out duplicated results by artistName.

feat: use hybrid search for open search query

---

_schemaV2.graphql
src/schema/v2/artist/createCanonicalArtistMutation.ts
src/schema/v2/schema.ts

This PR adds a new mutation to create an `Artist` record in gravity. I'm using the term "canonical" here to differentiate this mutation from the existing one called `CreateArtistMutation`. That one is being used to create artists for My Collection purposes and includes an unfortunate requirement that the mutation include a display name.
This assumption does not fit with how our admin users create artists over in Forque. In that context a display name should be optional.
So yeah, all I did here was copy/paste the existing mutation and update its name. Then I updated the type of the display name to optional. Once this lands then I can turn my attention over to Forque and use this mutation instead and allow admin's to skip display name when it's not applicable. …

feat: Add mutation to create canonical artist AMBER-1200

---

_schemaV2.graphql
src/lib/infiniteDiscovery/findSimilarArtworks.ts
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

This PR updates the latest index built using [the OpenSearch pipeline](https://github.com/artsy/zenith/tree/main/projects/infinite_discovery/src).

feat: update open search artworks index

---

scripts/push-schema-changes.js

Addresses the following error when running prettier in repositories where `parser` is configured via `.pretterrc`:
```
$ cd ~/code/artsy/force
$ cp ../metaphysics/_schemaV2.graphql data/schema.graphql 
$ ./node_modules/.bin/prettier --write data/schema.graphql
data/schema.graphql
[error] data/schema.graphql: SyntaxError: Unexpected keyword or identifier. (1:1)
[error] > 1 | directive @cacheable on QUERY
[error]     | ^
[error]   2 |
[error]   3 | directive @optionalField on FIELD
[error]   4 |
```
Surfaced [here in Slack](https://artsy.slack.com/archives/CP9P4KR35/p1736250971875779) and in [a Circle CI build](https://app.circleci.com/pipelines/github/artsy/metaphysics/25022/workflows/5b9c98ba-3d10-4b33-9f1f-0bfd2cd49515/jobs/51495).

chore: use graphql parser when formatting schema during push-schema-changes task

---

scripts/push-schema-changes.js

Follow up to #6337 which didn't support our .json file destinations.
This sync supports both .graphql and .json schema formats. When formatting JSON, we shouldn't supply the --parser argument.

chore: only force --parser=graphql prettier CLI arg when formatting graphql

---

_schemaV2.graphql
src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts

This PR resolves [AMBER-1116]
This work allows us to add selects to the BNMO opt in page for all of the signature fields.
[AMBER-1116]: https://artsyproduct.atlassian.net/browse/AMBER-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(AMBER-1116): Enable signature fields to be selected

---

_schemaV2.graphql
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

Adds configuration option for changing the count of the artworks batch.

feat: add artworks batch count configurable 

---

src/lib/apis/fetch.ts

Initially, this was reported by a gallery partner.  ([slack](https://artsy.slack.com/archives/C07PRTJSD6G/p1734645878738339)). They tried to add more than 21 artworks to a viewing room, but the backend was allowing only 21. I’ve noticed that the fetch doesn’t work correctly - for long arrays, it produces weird results like this one:
```json
{
artworks: [
{   // <- for some reason it reduces a bunch of artworks to a single nested object
'21': [Object],
'22': [Object],
'23': [Object],
'24': [Object],
'25': [Object],
'26': [Object],
'27': [Object],
'28': [Object],
'29': [Object],
artwork_id: '...',
delete: 'false'
},
{ artwork_id: '...', delete: 'false' }, // <- this looks normal
{ artwork_id: '...', delete: 'false' },
{ artwork_id: '...', delete: 'false' },
...
]
}
```
I discovered that qs …

fix: make fetch serialize arrays with more than 21 elements correctly

---

_schemaV2.graphql
src/lib/infiniteDiscovery/getInitialArtworksSample.ts
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

@egdbear let me know what you think. I suppose we may want to experiment with different initial artwork datasets in future, and I think it will be easy if `discoverArtworks` query field has an option to specify which artworks collection to use. For now, I've indexed Most Loved, Street Art, and New this Week marketing collections to the `infinite_discovery_initial_artworks` index (zenith PR to come).

feat(dia-1038): infinite discovery - make initial arworks batch index configurable

---

_schemaV2.graphql
src/schema/v2/homeView/sectionTypes/Tasks.ts
src/schema/v2/homeView/sections/Tasks.ts
src/schema/v2/me/__tests__/ack_task_mutation.test.js
src/schema/v2/me/__tests__/dismiss_task_mutation.test.js
src/schema/v2/me/ack_task_mutation.ts
src/schema/v2/me/dismiss_task_mutation.ts
src/schema/v2/me/task.ts

Part of [EMI-2226].
This PR adds the `homeViewTasksSection` field to our success response type so that we can refresh the home view with an updated task list when dismissing or acknowledging a task. Eigen PR to consume this new field and optimistically update forthcoming.
Somewhat confusingly I realized that I added this field to the `taskOrError` field. It is adjacent to the task on the non-error type but the field name implies that it is one thing - a task. Not sure if there is a better way here.
cc @artsy/emerald-devs
paired with @MrSltun on some of it.
[EMI-2026]: https://artsyproduct.atlassian.net/browse/EMI-2226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMI-2226]: https://artsyproduct.atlassian.net/browse/EMI-2226?atlOrigin=eyJpIjoi …

chore(EMI-2226): Add homeViewTasksSection to success response when clearing a task.

---

_schemaV2.graphql
src/schema/v2/me/__tests__/updateCollectionMutation.test.ts
src/schema/v2/me/collection.ts
src/schema/v2/me/updateCollectionMutation.ts

This one's easy, just thread this argument through in the mutation. Also added `slug` and `private` to the `Collection` type since we'll need that to expose the toggle control / public URL to a user who wants to share.
Up next, once https://github.com/artsy/gravity/pull/18492 is merged, an updated schema that lets you retrieve another user's public collection/artworks (right now all that is only under `me`).

feat: let a user toggle their Collection to public via updateCollectionMutation

---

_schemaV2.graphql
src/schema/v2/__tests__/collection.test.ts
src/schema/v2/collection.ts
src/schema/v2/me/collection.ts
src/schema/v2/schema.ts

I think this should be sufficient to get a public list/My Collection page up. Tested locally w/ two user's, and I'm able to access the expected info for a list that was made public, including My Collection (and via slug).
(screenshot is when logged in as a new user, accessing collections my personal user account set to public)

feat: add root-level collection: Collection to let a user access another user's public collection by slug

---

src/schema/v2/__tests__/filterArtworksConnection.test.ts
src/schema/v2/filterArtworksConnection.ts

Rather than loudly error, MP can more gracefully fallback to not erroring _or_ including any personalized arguments, if they were provided without a user context. Currently there is an ongoing issue where that's occurring, so at least for now we can relax it.
It's debatable whether a loud error, logging but not an error, or silently ignoring these arguments is the 'right' thing to do, generally!

fix: dont error when personalized arguments are used without a user in filtering

---

src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/me/myCollectionInfo.ts

The backend already properly enforces authorization. If a collection is not public, only the owner can read it. If a collection is public, anyone can read it.
So, we can relax that here in MP by defining the loaders we need in the _without_ authentication factory. Now, if you're logged in and make any of these collection requests that use the loaders, it all works as before.
But, if you're logged out and make any of these requests, as long as the collection is public - it will succeed.

feat: let a logged out user view public collection data

---

src/lib/infiniteDiscovery/getInitialArtworksSample.ts

This PR introduces an error handler for cases where no curated artworks are available.  In the future, we'll refine the error message, and it will comply with `ErrorType` once it becomes available from Gravity.

fix: throw exception for case with no curated artworks

---

_schemaV2.graphql
src/schema/v2/__tests__/filterArtworksConnection.test.ts
src/schema/v2/filterArtworksConnection.ts

This PR adds signed as a param to `filterArtworksConnection`. 
This is blocked by https://github.com/artsy/gravity/pull/18512

feat: add signed as a param to filterArtworksConnection

---

src/schema/v2/me/__tests__/create_bidder_mutation.test.js
src/schema/v2/sale/__tests__/index.test.ts
src/schema/v2/sale/index.ts

Followup from https://github.com/artsy/gravity/pull/18527
We have [another case](https://github.com/artsy/metaphysics/blob/main/src/schema/v2/artwork/index.ts#L1541) where Gravity can return `nil` for a Money type and we are returning `null`, so I am following the same pattern.
After this, we can rollback https://github.com/artsy/gravity/pull/18527

fix: handle Sale#totalRaised null case

---

src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/infiniteDiscovery/__tests__/discoverArtworks.test.ts
src/schema/v2/infiniteDiscovery/discoverArtworks.ts

follow-up https://github.com/artsy/gravity/pull/18531
Only authenticated users can access infinite discovery endpoint

feat: discoverArtworks sends user_id to Gravity for user authentication

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

This will update the actual shipping display to what is covered by this diagram:
I did update the specs to follow this diagram. So fairly confident in the logic here. It can be refactored I think but will do for now.

feat: update shippingInfo logic

---

_schemaV2.graphql
src/schema/v2/homeView/sectionTypes/NavigationPills.ts
src/schema/v2/homeView/sections/QuickLinks.ts
src/schema/v2/homeView/sections/__tests__/QuickLinks.test.ts

To elaborate on my comments in https://github.com/artsy/metaphysics/pull/6354 I'm showing what I mean by separating the concepts of section instance and section type.
Just as…
- the `Artists` section type exposes a list of `artists`
-  the `Cards` section type exposes a list of `cards`
I propose that…
- `NavigationPills` section type exposes a list of `navigationPills`
This decouples the `NavigationPills` naming from the specific instance that makes use of this section type (`QuickLinks`). 
Just like the `Cards` naming is decoupled from the specific instances of `DiscoverSomethingNew` and `ExploreByCategory`.
(This may end up being a lot of fuss for nothing if `NavigationPills` never enjoys any re-use, but I still think this is the right default mindset for naming in the home view)

refactor(homeView): naming within new quick link navigation pills

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

The type of this pr is **chore**
Part of [EMI-2278]
This PR adds the following properties to our artwork type for use in our client-side shipping estimates widget:
`depthCm, diameterCm, shippingWeight, shippingWeightMetric, framedDiameter`
It depends on artsy/gravity#18560 for some of the fields.
Some related adjacent fields (like `framedHeight` and `framedWidth` are typed as GraphQL strings instead of floats. I'd argue we should convert these, which would be a breaking schema change, or re-implement these fields to follow the `_Cm` naming convention of our non-framed dimensions fields.
[EMI-2278]: https://artsyproduct.atlassian.net/browse/EMI-2278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add artwork framed dimensions and weight.

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/ArtworkImport/__tests__/artworkImport.test.ts
src/schema/v2/ArtworkImport/__tests__/creatArtworkImportMutation.test.ts
src/schema/v2/ArtworkImport/artworkImport.ts
src/schema/v2/ArtworkImport/createArtworkImportMutation.ts
src/schema/v2/schema.ts

Adds a pretty light/boilerplate-ish schema for an artwork import - as well as creating an artwork import after a CSV upload.
Looks like-

feat: add schema for ArtworkImport and a createArtworkImport mutation

---

_schemaV2.graphql
src/schema/v2/homeView/sectionTypes/NavigationPills.ts
src/schema/v2/homeView/sections/QuickLinks.ts
src/schema/v2/homeView/sections/__tests__/QuickLinks.test.ts

> [!note]
> Required by https://github.com/artsy/eigen/pull/11528
https://artsyproduct.atlassian.net/browse/ONYX-1484
Adds an optional `icon` to the `NavigationPill` section type, which is used by the new `QuickLinks` section:
```graphql
{
homeView {
section(id: "home-view-section-quick-links") {
internalID
__typename
... on HomeViewSectionNavigationPills {
navigationPills {
href
ownerType
title
icon            # 👈🏽 👈🏽 new
}
}
}
}
}
```
```json
{
"data": {
"homeView": {
"section": {
"internalID": "home-view-section-quick-links",
"__typename": "HomeViewSectionNavigationPills",
"navigationPills": [
{
"href": "/favorites",
"ownerType": "follows",
"title": "Follows",
"icon": "FollowArtistIcon" // 👈🏽 👈🏽 icon name included in response, if it is defined
},
{
"href": "/auctions",
"ownerType": …
```

feat(home view): add icons to navigation pills

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts
src/schema/v2/object_identification.ts

In order to 'refetch' on an import (for presenting + paginating thru the rows of an import) - have to do this little dance.

chore: support NodeInterface/refetching on ArtworkImport

---

src/schema/v2/homeView/sections/DiscoverSomethingNew.ts

Addresses [DIA-990] 
This PR removes the Curator's Pick collection which is now redundant, replacing it with "Art Under $1,000".
I also changed the collection category to "Price" instead of "The Artsy Gift Guide" to match the naming patterns in Discover Something New. 
[DIA-990]: https://artsyproduct.atlassian.net/browse/DIA-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-990): Switching out marketing collections in Discover Something New

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/ArtworkImport/__tests__/updateArtworkImportRowMutation.test.ts
src/schema/v2/ArtworkImport/updateArtworkImportRowMutation.ts
src/schema/v2/schema.ts

Adds a mutation that lets a field/value pair be updated for an artwork import row (inline editing).

chore: add updateArtworkImportRow mutation (inline editing)

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/updateArtworkMutation.test.ts
src/schema/v2/artwork/index.ts
src/schema/v2/artwork/updateArtworkMutation.ts
src/schema/v2/edition_set.ts

This updates the `updateArtworkMutation` and exposes some additional gravity fields for the quick edit form:
- ecommerce: boolean
- displayPriceRange: boolean
- offer: boolean
- priceHidden: boolean
- priceListed: string
```json
{
"input": {
"id": "67af5d652ff989000fe339d3",
"availability": "for sale",
"ecommerce": false,
"priceListed": "4100",
"priceHidden": true,
"displayPriceRange": false 
}
}
```
```graphql
mutation foo($input: UpdateArtworkMutationInput!) {
updateArtwork(input: $input) {
... on updateArtworkSuccess {
artwork {
isAcquireable
isOfferable
availability
price 
priceDisplay 
displayPriceRange
}
}
... on updateArtworkFailure {
error
}
}
}
}
}
```
(Might be some quick follow-up PRs after this related to edition sets but this should be good)

feat(updateArtwork): Update mutation with new fields

---

_schemaV2.graphql
src/schema/v2/filterArtworksConnection.ts

Based on https://github.com/artsy/gravity/pull/18589 - this adds support for that argument as an input to the connection - as well as making sure the uncached data loader is used if this argument is specified.

chore: add includeAllJSON argument to filterArtworks

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/ArtworkImport/__tests__/artworkImport.test.ts
src/schema/v2/ArtworkImport/artworkImport.ts
src/schema/v2/partner/partner.ts

Allows us to populate the imports listings page (show a partner their history of imports).

chore: add artworkImportsConnection for a Partner

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/ArtworkImport/__tests__/matchArtworkImportRowImageMutation.test.ts
src/schema/v2/ArtworkImport/artworkImport.ts
src/schema/v2/ArtworkImport/matchArtworkImportRowImageMutation.ts
src/schema/v2/schema.ts

This adds support for image manipulation for artwork imports.
It returns the image data (so in the client, we can show the filenames they specified, as well as a warning if we weren't able to match an uploaded image to the specified filename on a row).
Additionally, there's a mutation that lets a particular row/filename tuple to be updated with the uploaded file location.

feat: support images for an artwork import row

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/__tests__/matchArtworkImportRowImageMutation.test.ts
src/schema/v2/ArtworkImport/matchArtworkImportRowImageMutation.ts

When working on the prototype - I realized when we're uploading all the images - we don't have the row id's - we just have the import and all the filenames from the upload, so this just drops the argument.
https://github.com/artsy/gravity/pull/18594 is the actual backend behavior update that makes it work without the row id.

chore: drop rowID argument from matching an image to an import by filename

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/bulkUpdatePartnerArtworksMutation.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts
src/schema/v2/schema.ts

[AMBER-1272]
Pairing with @jpotts244
Kick-off the MP mutation for triggering Bulk Update operations (Batch Edits)
Example:
```graphql
mutation bulkUpdateArtworksMetadata(
$id: String!
$metadata: BulkUpdateArtworksMetadataInput!
) {
bulkUpdateArtworksMetadata(
input: {
id: $id
metadata: $metadata
}
) {
__typename
bulkUpdateArtworksMetadataOrError {
__typename
... on BulkUpdateArtworksMetadataMutationSuccess {
updatedPartnerArtworks {
ids
}
}
... on BulkUpdateArtworksMetadataMutationFailure {
message
}
}
}
}
}
```
Variables used on local tests:
```json
{
"id": "almine-rech",
"metadata": {
"location_id": "67acd02ac4a53e0007b51cc0",
"category": "foobar"
}
}
```
_Intentionally using a random value for category given we have no validations for this field_
[AMBER-1272]: …

chore: Allow artworks to be updated in bulk (Batch Edits)

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/infiniteDiscovery/__tests__/discoverArtworks.test.ts
src/schema/v2/infiniteDiscovery/createUserSeenArtworkMutation.ts
src/schema/v2/infiniteDiscovery/discoverArtworks.ts
src/schema/v2/schema.ts

This PR introduces a new mutation, createUserSeenArtwork, which will be used to track seen artworks for Infinite Discovery. [Gravity PR](https://github.com/artsy/gravity/pull/18598) that introduced the endpoint for tracking seen artworks.
Ticket [DIA-1155](https://artsyproduct.atlassian.net/browse/DIA-1155)
[DIA-1155]: https://artsyproduct.atlassian.net/browse/DIA-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add user seen artworks mutation

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

I think this will allow Volt's table view of an import to be a bit generic, just showing the user the columns they initially included (and transformed/normalized data values).
Now, Volt still needs to 'know' for example that titles can have inline editing enabled and maybe should render differently than another column type, but I feel like _that_ could be a little config within Volt: column names -> Component kinda thing. We can see if that makes sense to move somewhere upstream - into MP _kinda_ like homeview. But, since Volt is likely to be the _only_ client for this whole imports schema, we can probably keep that stuff in Volt.
Ultimately, we want the specifics of the CSV in question to 'inform' the Volt table rendering of the import. This is b/c different partners may start to include …

chore: add columns and transformedData to ArtworkImport

---

src/schema/v2/artist/meta.ts

I've made this mistake so many times: slugs are ids and we don't have types to tell one otherwise.

fix(artist): uses correct attribute for slug

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/assignArtworkImportArtistMutation.ts
src/schema/v2/ArtworkImport/createArtworkImportArtworksMutation.ts
src/schema/v2/ArtworkImport/matchArtworkImportArtistsMutation.ts
src/schema/v2/ArtworkImport/matchArtworkImportRowImageMutation.ts
src/schema/v2/ArtworkImport/updateArtworkImportRowMutation.ts

Pretty straightforward - we require `artworkImportID` as an argument for all these mutations, so it's easy to add `artworkImport: ArtworkImport` to the mutation payloads for all of them.
This should enable the behavior of triggering a mutation and requesting the `fragment on ArtworkImport` for the next screen in the result.

chore: add artworkImport to mutation payload for all import-related mutations

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Can be used to retrieve the rows/count of rows that aren't eligible to have artworks created.

chore: add blockersOnly to rowsConnection on ArtworkImport

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

[AMBER-1304]
Expose `category` and `price_listed` as metadata possibilities on the Batch Edits mutation
(`category` was supposed to have been added during 6433, but I forgot to push it 🙏  )
cc @artsy/amber-devs 
[AMBER-1304]: https://artsyproduct.atlassian.net/browse/AMBER-1304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(AMBER-1304): Expose category and price fields for Batch Edits

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

We now will have a `state` property coming back with the artwork import JSON.

chore: add state to ArtworkImport

---

src/schema/v2/homeView/sectionTypes/NavigationPills.ts
src/schema/v2/homeView/sections/QuickLinks.ts
src/schema/v2/homeView/sections/__tests__/QuickLinks.test.ts

https://artsyproduct.atlassian.net/browse/ONYX-1558
The approach here is quite similar to https://github.com/artsy/metaphysics/pull/6297 and makes use of the versioning helpers already introduced in that PR.
QuickLinks now can individually set a minimum required Eigen version:
```diff
{
title: "Featured Fairs",
href: "/featured-fairs",
ownerType: OwnerType.fairs,
icon: "FairIcon",
+ minimumEigenVersion: { major: 42, minor: 0, patch: 0 },
},
```
That one-line change should be sufficient to **release** a quick link to supported versions of Eigen.
Note that this does not solve the question of how to return a WIP quick link for **dev or testing** purposes. For that we might have to rely on other techniques like feature flags; or limiting to staging by checking `config.SYSTEM_ENVIRONMENT`. And …

feat(homeView): allow QuickLinks to enforce minimum Eigen version requirements

---

_schemaV2.graphql
src/schema/v2/FeaturedFairs/__tests__/featuredFairs.test.ts
src/schema/v2/FeaturedFairs/featuredFairs.ts
src/schema/v2/homeView/sections/FeaturedFairs.ts
src/schema/v2/homeView/sections/__tests__/FeaturedFairs.test.ts
src/schema/v2/schema.ts

_Note: this departs from the approach in #6421, preferring a GraphQLList return type. If we want to fully model a GraphQL Connection, I think it would be far easier to first model this backfill-enabled + featured concept in Gravity so we can execute against a single API call. It became too complicated to stitch multiple API request responses together to fulfill both a GraphQL Connection response and backfill logic._
---
Returns a simple GraphQLList of fairs. When we don't have enough running fairs to satisfy the requested size, we backfill from recently closed fairs (up to 5).
```graphql
{
featuredFairs(size: 5, includeBackfill: true) {
internalID
name
href
exhibitionPeriod
}
}
```
```json
{
"data":{
"featuredFairs":[
{
"internalID":"672cf102ed11650011a5f70b",
"name":"LA Art Show 2025", …
```

feat: add featuredFairs query field

---

src/schema/v2/ArtworkImport/artworkImport.ts

Playing around with the prototype and realized - at least if price isn't required and we have rows without a price - then there's no `priceListed` (the money resolver will resolve to `$0` otherwise).

chore: dont render empty prices

---

src/schema/v2/notifications/index.ts

Fixes case where a Partner Offer notification activity uses the first image of the images array instead of the default one of the artwork.

fix: get default image for previewImages

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Updates to deal with the changes made in [this Gravity PR](https://github.com/artsy/gravity/pull/18639)
Thanks to pairing with @lidimayra to get this over the line

chore: AMBER-1316 - artwork imports list page

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

This starts the process of migrating away from the JSON scalar type, which is nice to prototype with but comes at the cost of some type safety in the system (and self-docs). So far we've only updated `transformedData` but might as well update `rawData` as well, just not too sure of the shape of that data ATM. (And we're not using it anywhere in the codebase - is it needed?)
Breaking change, but going to push up a quick volt PR with the optimistic update now that this is in.

refactor(batch-import): Migrate away from JSON type

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Threads through the argument from https://github.com/artsy/gravity/pull/18683
Can be used to exclude unmatched artist errors from the current imports client

chore: add excludeErrorTypes arg to rowsConnection on ArtworkImport

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/artist/__tests__/createArtistMutation.test.ts
src/schema/v2/artist/createArtistMutation.ts
src/schema/v2/artist/createCanonicalArtistMutation.ts

For a newly built 'Create Artist' flow in Volt (not Kinetic based) - we need to support not just creating the artist but also associating the partner artist.
This replicates the logic that Volt server side was currently doing [here](https://github.com/artsy/volt/blob/88070a1a394356d51e8ea5b3949ae51a60785c83/app/controllers/artists_controller.rb#L33).

chore: let partner-artist be created when an artist is created by a partner

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Adding some MP niceties that we can take advantage of in Volt. This avoids the direct lookup needed to Gravity of what is possible and helps with development.

chore: artwork import errors are now an enum, as is state

---

src/schema/v2/homeView/sections/InfiniteDiscovery.ts
src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts

This addresses [DIA-1236], updating the homeview image.
[DIA-1236]: https://artsyproduct.atlassian.net/browse/DIA-1236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-1236): Update Discover Daily homefeed image to new asset

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/Contacts/index.ts
src/schema/v2/partner/__tests__/partner.test.js
src/schema/v2/partner/partner.ts

Adds a `contactsConnection` on the `Partner` type for the Settings V2 re-write
Historically this data was fetched via Volt -> Kinetic -> Grav Rest
Adding this to the MP layer
Here's the data needed for the existing screen:
The new MP query will look like this
```graphql
{
contactsConnection(first: 10) {
edges {
node {
name
location {
display
}
}
}
}
}
}
```
---

feat: allow for contacts to be accessible on Partner type

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

feat: Allow clients to pass in contact type arg to contacts connection
The PartnerContact model supports two contact types:
- `admin` 
- `partner`
What is the difference between these two? I dont know! More digging for tomorrow
but TL;DR Gravity's PartnerContact endpoint will return any type of partner type if not specified and Volt only wants records where `contact_type='partner'`
Historically on Volt's side we only display PartnerContact records where the `contact_type='partner'`. See here: https://github.com/artsy/volt/blob/85e135ec5854e1c272f5430bcedd7c1d5172ea46/app/controllers/contacts_controller.rb#L7-L18
Anyway, allow the new `contactsConnection` to accept a type argument so clients can filter

feat: Allow clients to pass in contact type arg to contacts connection

---

_schemaV2.graphql
src/schema/v2/me/collection.ts

This `slug` field was added for collection sharing last Hackathon.
This changes it from non-nullable to nullable, to make it consistent with Gravity, which is [expected to return](https://github.com/artsy/gravity/blob/f0cc2252702133add0d0b62f7f84f13faa6fd5e7/app/models/domain/collection.rb#L273) `slug: null` for any collection which has not yet been made public:
(I'm making some updates to the sharing UI and, without this change, we get the dreaded `Cannot return null for non-nullable field` on the `collection`.)
Since the hackathon feature is the only use of this new `slug` field, and it is [_not_ assumed](https://github.com/artsy/force/blob/dca9d97cce0b24100251d21dd62bba960684566a/src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksHeader.tsx#L98) to be non-null, I believe …

fix: permit collection.slug nullability

---

_schemaV2.graphql
src/schema/v2/__tests__/show.test.js
src/schema/v2/show.ts

Adds `documentsConnection` under the `Show` type (necessary for rebuild of partner show show/edit functionality in Volt).
Technically this existed under `Partner` where you needed to provide a `showID` argument - but I think this is a worthy addition to the `Show` type to make it more inline with other data that lives on this type.

chore: add documentsConnection under Show

---

_schemaV2.graphql
src/schema/v2/show.ts

We have `artists` available, an un-paginated list, as the entire un-paginated set of artists available on a show are included with the show JSON!
But, for convenience and reuse of front-end components that expect a connection (like our `List`) - let's add and front that list w/ a connection.

chore: add artistsConnection to Show

---

src/schema/v2/show.ts

This is probably just for a placeholder since we'll use the ES-backed connection (sharing from new artworks listing). But for now - let's use this, but annoyingly - it didn't offer our standard cursor setup for list pagination!

chore: make sure pageCursors available on artworksConnection: Show

---

_schemaV2.graphql
src/schema/v2/show.ts
src/schema/v2/show_event.ts

Similar to `artists` - we have the full list of `events` included in show JSON - but let's include a connection that lets you slice through that data to work nicer with our FE (specifically list/pagination).

chore: add eventsConnection to Show

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/__tests__/createPartnerContactMutation.test.js
src/schema/v2/partner/createPartnerContactMutation.ts
src/schema/v2/schema.ts

Creates a new mutation that processes the creation of new partner contact records
```graphql
mutation {
createPartnerContact(input: { 
partnerID: "5f80bfefe8d808000ea212c1"
name: "Molly D"
position: "Account Manager"
canContact: true
email: "md@2example.com"
phone: "123-456-7890"
locationID: "location-567"
}) {
partnerContactOrError {
... on CreatePartnerContactSuccess {
contact {
internalID
name
position
canContact
email
phone
location {
display
}
}
}
... on CreatePartnerContactFailure {
message
}
}
}
}
}
```
which will return the created contact or an error:
```json
{
"data": {
"createPartnerContact": {
"partnerContactOrError": {
"contact": {
"internalID": "molly-d-8cd3152d-0684-4735-b2d8-1e962f68dc5d",
"name": "Molly D",
"position": "Account Manager",
"canContact": …
```

feat(settingsV2): Adds mutation to create partner contacts

---

package.json
src/lib/tracer.ts
yarn.lock

[future-friday] I noticed that our dd-trace version `0.36.2` is EOL for a while.

feat: bump dd-trace

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

In preparation to check in Force (EMI-2357) for fixed shipping fee for the order adding this property here. 
Was debating if just request a raw data and do this check in Force but figured it might be helpful in other contexts and also did not want a lot of logic on the client for this one.

feat: add isFixedShippingFeeOnly property to artwork

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts
src/schema/v2/fields/money.ts

This will enable us to be able to highlight the `currencyPrefix` when showing price without having to do additional work on the front end. An example us of this can be found in [this figma file](https://www.figma.com/design/y31Q2l6ggPJEtUfWWtvBuE/Listing-experience?node-id=2654-12379&t=FxVBrxKUGtoid3sy-4).
An example response with these changes is as follows
```
"priceListed": {
"major": 5000,
"minor": 500000,
"currencyCode": "USD",
"display": "US$5,000",
"currencyPrefix": "US$",
"amount": "5,000"
}
```

chore: artwork import price listed currency

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/sharedOrderTypes.ts

Type: Chore
Relates to [EMI-2306]
This PR adds the new exchange `tax_total_cents` field to the Order type. Minor change overall- I updated the queried Money field in our tests to `minor` because I realized that display is rounding the numbers (eg `4299` becomes `"US$43"`). Since we don't need these display fields yet I changed the specs, but we'll probably need to reconfigure that soon.
[EMI-2306]: https://artsyproduct.atlassian.net/browse/EMI-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2306): Add Order.taxTotal money field

---

src/schema/v2/ArtworkImport/artworkImport.ts

Fixes small regression  from https://github.com/artsy/metaphysics/pull/6543
We need to be aware of missing or invalid price information, vs always resolving (which returns values like $US 0 for invalid things).

fix(artworkImport): dont always resolve currency

---

src/lib/loaders/loaders_with_authentication/gravity.ts

We want to use this loader in an authenticated context from CMS (right now it defaults to the unauthenticated one).

chore: add authenticated partnerShowLoader

---

src/lib/featureFlags.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
src/schema/v2/homeView/sections/ExploreByCategory.ts
src/schema/v2/homeView/sections/__tests__/DiscoverSomethingNew.test.ts
src/schema/v2/homeView/sections/__tests__/ExploreByCategory.test.ts

This PR cleans up the obsolete feature flag.
Eigen PR: https://github.com/artsy/eigen/pull/11769
Echo PR: https://github.com/artsy/echo/pull/789

chore: remove marketing-collection-categories feature flag from homeView

---

src/schema/v2/Show/createPartnerShowMutation.ts
src/schema/v2/Show/updatePartnerShowMutation.ts

Whoops! Noticed I didn't have the right argument to line up with the API - which expects the identifier to be called `partner_location`.

chore: correct argument for saving location of a partner show

---

src/lib/apis/fetch.ts
src/schema/v2/Show/createPartnerShowMutation.ts

At first - when creating a show, we can just not send a blank location value.
But - what about when updating a show with a location, and _unsetting_? We likely _never_ have done that before with mutation ('unsetting'), as the way our `fetch` is all hooked up - those variables to a data loader, `key: null`, always make it to the API as `key: ""` - which is _not_ unsetting!
This might be sketchy in that, what if you want to set a string field, like a description, to a blank string? Would just rewriting to `null` be ok? I think it would, and since this allows us to unset fields, I think we need to make this change - but overall something is sketchy in how we're sending mutation payloads upstream - for POSTs we're not even really using a request body but query params!

chore: allow nil locations to be set for a partner show

---

src/schema/v2/order/__tests__/MeOrder.test.ts

Type: **chore**
#minor
Related to [EMI-2306]
This PR adds tests to validate the nullability of the taxTotal money type.
[EMI-2306]: https://artsyproduct.atlassian.net/browse/EMI-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2306): Add tests for Order.taxTotal

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/Show/__tests__/removeInstallShotFromPartnerShowMutation.test.ts
src/schema/v2/Show/__tests__/updateInstallShotForPartnerShowMutation.test.ts
src/schema/v2/Show/removeInstallShotFromPartnerShowMutation.ts
src/schema/v2/Show/updateInstallShotForPartnerShowMutation.ts
src/schema/v2/schema.ts

Now that we can add an install shot, we should be able to remove it, and also update it (currently the only thing we support updating is the caption).

chore: remaining install shot mutations

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/artwork/__tests__/createArtworkMutation.test.ts
src/schema/v2/artwork/createArtworkMutation.ts
src/schema/v2/schema.ts

This adds a minimal mutation that can be used for the **single** artwork upload flow.
Namely - for a given artist(s) (and partner, naturally) - as well as an uploaded image - we can now create an artwork and associate that image. This mimics the current two step flow in https://cms-staging.artsy.net/uploads where you select an artist, and upload images - and one artwork (per image) is created.
There was no Gravity updates needed to get artwork processing working for the image association when specifying the S3 info of an upload in this format! This mutation allowed me to create an artwork and have the image immediately associate and show up on /artworks.

chore: add createArtworkMutation

---

_schemaV2.graphql
src/schema/v2/order/__tests__/setOrderFulfillmentOptionMutation.test.ts
src/schema/v2/order/__tests__/updateOrderMutation.test.ts
src/schema/v2/order/exchangeErrorHandling.ts
src/schema/v2/order/setOrderFulfillmentOptionMutation.ts
src/schema/v2/order/sharedOrderTypes.ts
src/schema/v2/order/updateOrderMutation.ts

type: **fix**
resolves [EMI-2358]
This PR adds a lightweight error handling pattern so we can forward known error types from exchange. Currently it is only concerned with validation errors: these have a `message` and a `code` which are by default the same (unless the error gets a [details](https://github.com/artsy/exchange/blob/main/spec/api/me/orders_endpoint_spec.rb#L246-L249) as well).
We could get more clever about this:
- we could also send the error `type`, ie `validation`
- we could make the various error types a union type
- we could make the various error codes an enum type
Curious on others thoughts but this works for today.
cc @artsy/emerald-devs 
https://github.com/artsy/exchange/blob/main/app/api/concerns/grape_error_handlers.rb#L50-L52
[EMI-2358]: …

fix: correctly handle known errors from exchange

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/__tests__/createPartnerLocationMutation.test.js
src/schema/v2/partner/createPartnerLocationMutation.ts
src/schema/v2/schema.ts

Adds mutation to allow for creating of partner locations
⚠️ [This Gravity change](https://github.com/artsy/gravity/pull/18777) is blocking this PR
Mutation Structure
```graphql
mutation {
createPartnerLocation(input: { 
partnerID: "5f80bfefe8d808000ea212c1"
address: "12345 Happy St"
address2: "Apt 23"
city: "Orchard Park"
state: "NY"
postalCode: "14127"
publiclyViewable: true
}) {
partnerLocationOrError {
... on CreatePartnerLocationSuccess {
location {
internalID
display
}
}
... on CreatePartnerLocationFailure {
message
}
}
}
}
}
```
Response Structure
```json
{
"data": {
"createPartnerLocation": {
"partnerLocationOrError": {
"location": {
"internalID": "67e6e8f7185671000fd3b536",
"display": "12345 Happy St, Apt 23, Orchard Park, NY, 14127"
}
}
}
}, …
```

feat(settingsV2): Adds mutation to allow for creating of partner locations

---

src/schema/v2/Feature/FeatureMeta.ts

Forgot to update the deprecated field to the new definition.

fix(feature): updates name as well

---

_schemaV2.graphql
src/schema/v2/Show/createPartnerShowMutation.ts
src/schema/v2/Show/updatePartnerShowMutation.ts

Adds a few optional fields around fairs + viewing rooms in the partner show mutations.

chore: update partner show mutations to allow fair-specific fields, plus viewing rooms

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/sharedOrderTypes.ts

https://artsyproduct.atlassian.net/browse/EMI-2362
Following https://github.com/artsy/exchange/pull/2486, this adds a `seller` field on the order type in which we'll be able fetch the stripe account id. It's basically to replace the current [stitched version](https://github.com/artsy/metaphysics/blob/c83d5b17aa3cb4cceb9b18978a243b6d36f6e87b/src/lib/stitching/exchange/v2/stitching.ts#L607).
cc @artsy/emerald-devs

feat: add seller field to order

---

src/schema/v2/__tests__/search.test.ts
src/schema/v2/search/SearchResolver.ts

When I type "Claudia" and "Claudia " (with a trailing space) into the search input, I get completely different results:
| "Claudia" | "Claudia " |
|---|---|
| <img src="https://github.com/user-attachments/assets/0818919a-7484-4d3f-a122-46e29ac9dd78" > | <img src="https://github.com/user-attachments/assets/4c89234a-0ec0-4109-a3a0-5b2e5d91a0e1" /> |
We believe this is worth fixing.
The issue occurs because we apply a strong boost to the `name_exact` field, which is a `keyword` field. Keyword fields in Elasticsearch don’t apply any normalization — for example, they don’t trim surrounding whitespace. You can see the difference by comparing the analyzer results between the `name_exact` (keyword) and `name` (text) fields:
```
POST /artists_production/_analyze
{
"field": "name_exact",
"text": " …
```

fix: remove leading and trailing whitespace characters from the search query

---

_schemaV2.graphql
src/schema/v2/show.ts

In CMS, we want to display a linked viewing room to a show, even if it's not publicly viewable. So - we can specify the `statuses:[closed, draft, live, scheduled]` - and for an authorized user they'd see any linked VR, even if it's not public (which we want in CMS).

chore: allow statuses to be passed as an arg to show viewingRoomsConnection

---

_schemaV2.graphql
src/schema/v2/Show/__tests__/createPartnerShowEventMutation.test.ts
src/schema/v2/Show/__tests__/updatePartnerShowEventMutation.test.ts
src/schema/v2/Show/createPartnerShowEventMutation.ts
src/schema/v2/Show/updatePartnerShowEventMutation.ts
src/schema/v2/show_event.ts

This supports displaying the timezone of a show event in a way suitable for a select picker, as well as lets the mutations to create/edit a show event specify a timezone.
The quirk here is that the backend expects one format which is a bit specific to Rails - and we want to be able to translate for a nicer UI to show the partner.
This code supports properly managing data like (note the time zone specific stuff):

chore: support timezones for show events

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/__tests__/partner.test.js
src/schema/v2/partner/partner.ts

Welp I didnt get too far sketching out the [edit functionality in volt](https://github.com/artsy/volt/compare/jpotts244-contact-delete-edit?expand=1)
Adding the ability to fetch a singular partner contact ✅  
Will need this to rehydrate the contact records on the front end after a user edits a record + we dont have to use the larger `contactsConnection` query only in Volt 📈 
--- 
```graphql
{
internalID
contact(contactId: "4820b8cb-983f-4cf8-a35b-90e0f7954d1a") {
internalID
name
email
phone
position
canContact
location {
internalID
display
}
}
}
}
```

feat: Add query to fetch single partner contact

---

src/schema/v2/FeaturedFairs/__tests__/featuredFairs.test.ts
src/schema/v2/FeaturedFairs/featuredFairs.ts

https://artsyproduct.atlassian.net/browse/ONYX-1658
A colleague [reported](https://artsy.slack.com/archives/C03N12SR0RK/p1743691566357749) that the app was displaying **Featured Fairs** that were not visible on web.
This brings the `featuredFairs` field's filtering criteria closer inline with the [existing query](https://github.com/artsy/force/blob/f651e59f4c09ca1e5909802dd745d4a2b93fe168/src/Apps/Fairs/Routes/FairsIndex.tsx#L335) that Force uses to generate the fairs listing on the /fairs landing page.

fix(featured fairs): add missing criteria

---

src/schema/v2/Show/__tests__/createPartnerShowEventMutation.test.ts
src/schema/v2/Show/__tests__/updatePartnerShowEventMutation.test.ts
src/schema/v2/Show/createPartnerShowEventMutation.ts
src/schema/v2/Show/updatePartnerShowEventMutation.ts

Ok, this feels much more correct! Take in the properly formatted timezone as mutation inputs that Gravity will understand. I have a corresponding Volt PR coming that makes use of this field and makes it clear.

chore: tweak timezone handling for mutation input

---

src/schema/v2/Show/createPartnerShowEventMutation.ts
src/schema/v2/Show/updatePartnerShowEventMutation.ts

Noticing that an input like 5:00 and America/New_York was being returned back from Gravity as "1:00pm EDT" -> realized we need to convert that initial timestamp to Unix-style _in the provided timezone_.

chore: send right unix timestamp back with consideration of timezone

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts
src/schema/v2/artwork/updateArtworkMutation.ts
src/schema/v2/edition_set.ts
src/schema/v2/sellable.ts

Ran into an issue where EditionSets are _not_ Artworks, but `Artwork` implements the `Sellable` interface. So expand the `Sellable` interface with some additional `Artwork` types, and implement them via a shared object in `EditionSets` 😵‍💫 
Something feels sloppy here, and i'm not quite sure about naming, but it does smooth things out nicely on the GraphQL consumer side and makes things feel more "artwork like". 
Thoughts?

feat(edition-sets): Share fields with sellable

---

_schemaV2.graphql
src/schema/v2/artist/index.ts
src/schema/v2/artist/updateArtistMutation.ts

This PR adds two new data points to Artist type used for publications and biennials.
[Gravity PR](https://github.com/artsy/gravity/pull/18809)
[Forque PR](https://github.com/artsy/forque/pull/1411)

feat: add biennials and review sources to artist type

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/exchange.ts
src/schema/v2/order/__tests__/unsetOrderFulfillmentOptionMutation.test.ts
src/schema/v2/order/setOrderFulfillmentOptionMutation.ts
src/schema/v2/order/unsetOrderFulfillmentOptionMutation.ts
src/schema/v2/schema.ts

type: **feat**
Related to [EMI-2374]
depends on artsy/exchange#2477
This PR creates a new mutation to unset the fulfillment option on an order. It is mostly a copy-paste of the setFulfillmentOption mutation.
[EMI-2374]: https://artsyproduct.atlassian.net/browse/EMI-2374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2374): create unsetOrderFulfillmentOption mutation + tests

---

_schemaV2.graphql
package.json
src/lib/featureFlags.ts
src/schema/v2/image/__tests__/index.test.js
src/schema/v2/image/index.ts
yarn.lock

In the effort to reduce the number of future flags that 💎  has.
This field is being removed entirely as it's not used by either Eigen or Force and because it appears to be at an attack vector. Usage of it in Force with larger arguments appears to have caused [inc-219](https://artsy.app.opsgenie.com/reports/post-mortem/154274cc-497e-4b30-92a6-6dcc85f45bf1/detail)

chore(dia-1224): removes blurhash feature flag and related field

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

Follow up to https://github.com/artsy/metaphysics/pull/6605#discussion_r2032126895
Makes some new field sub-selections non-nullable. 

fix(artwork): Make signatureMeta subfields non-null

---

src/lib/loaders/loaders_with_authentication/gravity.ts

Fix: uses the correct URL structure to hitting the GET `api/v1/parnter/partner_id/location/id` endpoint
Ooops! You'll always get a 404 as this `locationId` path doesnt exist:

fix: Fix to use the correct endpoint url structure

---

_schemaV2.graphql
src/schema/v2/partner/Settings/createPartnerLocationMutation.ts
src/schema/v2/partner/Settings/updatePartnerLocationMutation.ts

Losening up the `addressType` when creating or updating partner locations
I'll let Gravity [hold the main validation for now](https://github.com/artsy/gravity/blob/main/app/models/domain/partner_location.rb#L56)
I want Volt to be less "aware" of casing logic like [this](https://github.com/artsy/volt/pull/8707/files#diff-4cbcf0d9fa148c5b2ac47eb243a4f8b17b23cf2bdc614219e4f748f6c9e175b0R16-R17) for now!

chore: Adjust address type to just be a string field for now

---

_schemaV2.graphql
src/schema/v2/partner/partner_artist.ts

Supports querying some of the relations (tabs) we need for a partner artist.

chore: add shows/documents/filterArtworks to partner artist

---

_schemaV2.graphql
src/schema/v2/artwork/updateArtworkMutation.ts

Quick one -- expose `published: boolean` argument on `updateArtwork` mutation for publishing an artwork. 

feat(updateArtwork): Add published input argument

---

src/schema/v2/partner/Settings/deletePartnerLocationMutation.ts

Oops!  Fix argument for `locationId`
Otherwise we are always passing in undefined to Gravity

fix: Fix `locationId` argument casing

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/Mutations/PartnerArtist/__tests__/createPartnerArtistDocumentMutation.test.ts
src/schema/v2/partner/Mutations/PartnerArtist/__tests__/deletePartnerArtistDocumentMutation.test.ts
src/schema/v2/partner/Mutations/PartnerArtist/__tests__/updatePartnerArtistDocumentMutation.test.ts
src/schema/v2/partner/Mutations/PartnerArtist/createPartnerArtistDocumentMutation.ts
src/schema/v2/partner/Mutations/PartnerArtist/deletePartnerArtistDocumentMutation.ts
src/schema/v2/partner/Mutations/PartnerArtist/updatePartnerArtistDocumentMutation.ts
src/schema/v2/schema.ts

Boilerplate / following from the show documents mutations. Three new ones for managing (CRUD)

chore: add mutations for managing partner artist documents

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/Settings/__tests__/repositionPartnerLocationsMutations.test.ts
src/schema/v2/partner/Settings/repositionPartnerLocations.ts
src/schema/v2/schema.ts

Adds a new MP loader to hit `POST api/v1/partner/:id/locations/reposition` gravity endpoint ([ref](https://github.com/artsy/gravity/blob/main/app/api/v1/partners_locations_endpoint.rb#L97))
Ex structure:
```graphql
mutation {
repositionPartnerLocations(input: {
partnerId: "5f80bfefe8d808000ea212c1", 
locationIds: ["5f8123abec5de8000ea9b785", "60dcc8f849a149000f9ece3a"], 
}) {
partnerOrError {
... on RepositionPartnerLocationsSuccess {
partner {
internalID
}
}
... on RepositionPartnerLocationsFailure {
message
}
}
}
}
}
```
Here's an example of the Kinetic <> Gravity backed experience, we want to carry this over in settings V2, discussed in this [thread](https://artsy.slack.com/archives/C05F8TNKGAV/p1742413671128289?thread_ts=1742412854.670859&cid=C05F8TNKGAV) …

feat: Adds mutation to support partner location reordering

---

_schemaV2.graphql
src/schema/v2/filterArtworksConnection.ts

This passes through the new `disable_not_for_sale_sorting` argument for our lists, from https://github.com/artsy/gravity/pull/18816

feat(filter): Add disableNotForSaleSorting input arg

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/Mutations/PartnerArtist/__tests__/repositionPartnerArtistArtworksMutation.test.ts
src/schema/v2/partner/Mutations/PartnerArtist/repositionPartnerArtistArtworksMutation.ts
src/schema/v2/schema.ts

Easy breezy boilerplate.
Depends on https://github.com/artsy/gravity/pull/18819 to accept `artwork_ids` .

chore: add repositionPartnerArtistArtworks mutation

---

_schemaV2.graphql
src/lib/stitching/vortex/__tests__/pricingContext.test.ts
src/schema/v2/fields/listPrice.ts
src/schema/v2/sellable.ts

Noticed this wasn't exposed, and also fixes a bug in `listPrice` where if there's no `price_currency` set, don't resolve. ListPrice (and further down, Money) has a hard requirement that it is there. 

feat(edition-sets): Expose listPrice for price ranges

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/exchange.ts
src/schema/v2/order/__tests__/unsetOrderPaymentMethodMutation.test.ts
src/schema/v2/order/unsetOrderPaymentMethodMutation.ts
src/schema/v2/schema.ts

This PR resolves part of [EMI-2391]
This PR is a follow-up on artsy/exchange#2515 🔒
This PR exposes the newly created endpoint to unset the payment method on an order
[EMI-2391]: https://artsyproduct.atlassian.net/browse/EMI-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2391): create unsetPaymentMethod mutation

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/match/__tests__/partner.test.js
src/schema/v2/match/partner.ts
src/schema/v2/schema.ts

This adds a new endpoint mapping to the [partner match endpoint](https://github.com/artsy/gravity/blob/40dab2533b4628f9cc7a48d42bf354c356326e56/app/api/v1/match_endpoint.rb#L40-L70) in gravity. This will be used to recreate the [partner selections page](https://cms-staging.artsy.net/partner_selections) in Volt
```
{
matchPartner(query:"Gallery"){
name
id
... on Partner{
meta {
image
}
}
}
}
```
```
{
"data": {
"matchPartner": [
{
"name": "&Gallery",
"id": "UGFydG5lcjo1YTk1NmVlZTljMThkYjUzMDljMDc0ZjI=",
"meta": {
"image": "https://d32dm0rphc51dk.cloudfront.net/7Vcr5HFjhEGAul-skkNi3Q/square140.png"
}
},
{
"name": "CHROMA GALLERY",
"id": "UGFydG5lcjo1OTU2ZDBiMzljMThkYjNjODcyOWIzYjY=",
"meta": {
"image": "https://d32dm0rphc51dk.cloudfront.net/CIveNUM3si1Zfq4bNZOWjA/square140.png"
}
},
{ …
```

chore: adding match endpoint for partners

---

_schemaV2.graphql
src/schema/v2/partner/__tests__/updatePartnerFlagsMutation.test.ts
src/schema/v2/partner/updatePartnerFlagsMutation.ts
src/schema/v2/schema.ts

This PR takes the work done over on this one: https://github.com/artsy/gravity/pull/18820 and uses it to create a general purpose mutation that can update multiple partner flags. I'll use this mutation in the work I'm doing to migrate the CMS preferences page.
I worked with Claude to do this so I'm not 100% sure if it's following patterns/best practices so def open to feedback!!

chore: Add mutation to update partner flags

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

These filters (artwork ids, partner artist and location) are already available on the Gravity endpoint. Changes here allow them on the mutation as well.

chore: Enable filters for bulk update artworks metadata

---

_schemaV2.graphql
src/schema/v2/partner/partner_artist.ts

Noticed these counts weren't available (but displayed on the partner artist overview).

chore: add documents and shows count to partner artist edge

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/Mutations/PartnerArtist/__tests__/deletePartnerArtistMutation.test.ts
src/schema/v2/partner/Mutations/PartnerArtist/deletePartnerArtistMutation.ts
src/schema/v2/schema.ts

Pretty boilerplate-y - adds a mutation to let a partner clean up a partner artist (which also soft-deletes all their artworks).

chore: add deletePartnerArtist mutation

---

_schemaV2.graphql
src/schema/v2/partner/Mutations/PartnerArtist/updatePartnerArtistMutation.ts

This is for the biography-related editing of a partner artist. You can toggle whether to show the partner-provided bio or the Artsy default one on the partner artist page, as well as the partner-provided bio itself.

chore: add biography-related fields to updatePartnerArtist mutation

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/__tests__/updatePartnerMutation.test.ts
src/schema/v2/partner/updatePartnerMutation.ts
src/schema/v2/schema.ts

This PR adds a new mutation for updating a partner record in the API. I exported the documentation for that REST endpoint and used that as a starting point for this mutation. I asked Claude to follow our typical mutation patterns and I think what emerged looks pretty good but lmk if there's anything that seems off!

chore: Add mutation to update partners

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

Depends on https://github.com/artsy/gravity/pull/18838
Allow `published` to be passed within the metadata to the batch edits mutation.
It can publish or unpublish the artworks depending on its boolean value

feat: Allow artworks to be published/unpublished in batch

---

_schemaV2.graphql
src/schema/v2/edition_set.ts

The type was wrong here and surfaced in the /artworks2 validation in volt.

fix(editionSets): Fix type for artistProofs

---

_schemaV2.graphql
src/schema/v2/filterArtworksConnection.ts

Threads this through so that we can filter based upon specific artwork IDs:
```graphql
query SpecificArtworks {
artworksConnection(first:10, input:{ artworkIDs:[
"67feb54f06661d00100a2e7f", 
"67feb54fe12c8d0014a9da05", 
"67d31fbbdec7ae0013cdba16"
] }) {
edges {
node {
title
artist {
name
}
}
}
}
}
```

feat(artworksConnection): Thread `artworkIDs` prop through to ES

---

_schemaV2.graphql
src/schema/v2/artwork/__tests__/createArtworkMutation.test.ts
src/schema/v2/artwork/createArtworkMutation.ts

This updates our mutation to create an artwork (with an uploaded image via s3 bucket/key) to also support an array of s3 buckets/keys. There is some basic validation on those, and the mutation is backwards compatible - you can use _either_ the singular or plural form (although I've deprecated the singular form as the plural form can handle both).

chore: allow multiple images to be added to a created artwork

---

_schemaV2.graphql
src/schema/v2/partner/partner.ts

In an attempt to reduce some ruby code in Volt, moving this informational VAT string calculation into Metaphysics
This data is rendered within the settings overview UI in CMS.
Where `vatInformation` will be the equivalent to this Volt ruby code ([ref](https://github.com/artsy/volt/blob/main/app/models/partner.rb#L299C1-L308C6))
```ruby
def self.vat_information(partner)
case partner.vat_status
when "registered", "registered_and_exempt"
partner.vat_number
when "ineligible", "exempt"
I18n.t("settings.index.gallery_info.vat_id_number_#{partner.vat_status}")
else
I18n.t("settings.index.gallery_info.vat_id_number_fallback")
end
end
```
Which displays in CMS as so:
---
```
query {
partner(id: "commerce-test-partner"){
vatNumber
vatStatus
vatInformation
}
}
```
Needs some access level changes in …

chore: Add `vatInformation` calculated field to Partner

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/Settings/__tests__/updatePartnerProfileImageMutation.test.js
src/schema/v2/partner/Settings/updatePartnerProfileIconMutation.ts
src/schema/v2/partner/Settings/updatePartnerProfileImageMutation.ts
src/schema/v2/schema.ts

Exposes mutation to update partner profile type images
Wires in Gravity's new endpoint ~[here](https://github.com/artsy/gravity/pull/18850/files)~ [here](https://github.com/artsy/gravity/pull/18852)
Now using `partnerId` on the input type and returning the full partner object (`owner`) from the resolver
Ex:

feat(settingsv2): Exposes mutation to update partner profile type images

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Partially solves [AMBER-1530]
Maps the new `medium` value added in https://github.com/artsy/gravity/pull/18854
[AMBER-1530]: https://artsyproduct.atlassian.net/browse/AMBER-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-1530 - adding medium to match its addition in Gravity

---

CLAUDE.md
_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/profile/__tests__/updateProfileMutation.test.ts
src/schema/v2/profile/updateProfileMutation.ts
src/schema/v2/schema.ts

This PR adds a basic mutation to update a `Profile` record over in Gravity. I used Claude to come up with a plan to add this mutation as it did over on https://github.com/artsy/metaphysics/pull/6632 and https://github.com/artsy/metaphysics/pull/6638 but something seems to have gone a little sideways. Will fix what's wrong and get this back on track!

chore: Add mutation to update profiles

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts

Add a singular `profileLoader` to loaders with authentication
Noticed I was getting `403` accessing partner profile information in MP + Volt even though I was associated with the profile

fix: Add single profileLoader to loaders with authentication

---

_schemaV2.graphql
src/schema/v2/__tests__/purchases.test.ts
src/schema/v2/purchases.ts
src/schema/v2/schema.ts

As part of our effort to finalize the Torque deprecation, we are migrating the Purchases section to Forque. To display the table, we need a new field called `purchasesConnection`:
```graphql
{
purchasesConnection(first: 10) {
edges {
node {
internalID
user {
internalID 
}
artwork {
internalID
}
saleDate
salePrice
}
}
}
}
```

feat(onyx-1663): purchasesConnection

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/__tests__/purchase.test.ts
src/schema/v2/__tests__/purchases.test.ts
src/schema/v2/purchase.ts
src/schema/v2/purchases.ts
src/schema/v2/schema.ts

As part of our effort to finalize the Torque deprecation, we are migrating the Purchases section to Forque. This PR adds `purchase(id: ...)` root field so that we could render /purchase/:id page there
```graphql
{
purchase(id: "purchase-id") {
internalID
}
```

feat(onyx-1669): add purchase root field

---

_schemaV2.graphql
src/schema/v2/partner/updatePartnerMutation.ts

This PR is a follow up to https://github.com/artsy/metaphysics/pull/6638 where I added a mutation to update partner records. I'm not sure how exactly but Claude failed to add a bunch of fields to that initial PR and I def missed it! This time it seems to have correctly taken the API doc and added all the possible fields. The ones I actually needed are the vat ones but this seemed worth doing.

chore: Improve mutation to update partner records

---

src/schema/v2/homeView/__tests__/HomeView.test.ts

These tests started failing when we deprecated the Discover Daily feature flag because that section was hidden by default. This PR updates these tests to look at the `card` title instead of the `component` title when a section is a HomeViewSectionCard type. (This also impacted the assertion for "Galleries Near You".)

chore: update home view tests after removing discover daily feature flag

---

src/lib/featureFlags.ts
src/schema/v2/homeView/mixer/HomeViewMixer.ts
src/schema/v2/homeView/mixer/HomeViewMixerRule.ts
src/schema/v2/homeView/mixer/SectionRule.ts
src/schema/v2/homeView/mixer/__tests__/HomeViewMixer.test.ts
src/schema/v2/homeView/mixer/__tests__/rules/BoostHeroUnitsForNewUsersRule.test.ts
src/schema/v2/homeView/mixer/rules/BoostHeroUnitsForNewUsersRule.ts
src/schema/v2/homeView/mixer/rules/DisplayableRule.ts
src/schema/v2/homeView/zones/default.ts

https://artsyproduct.atlassian.net/browse/ONYX-1674
This implements the proposal sketched out here — [slides](https://docs.google.com/presentation/d/1UdeoZ5XSZSdylohK9xwlyvp0Ak-1bq8Y61KRfvxtDrg/edit?usp=sharing) and [discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1745488800435159) — and presented to Onyx today.
The big idea here is the `HomeViewMixer`, explained in [this slide](https://docs.google.com/presentation/d/1UdeoZ5XSZSdylohK9xwlyvp0Ak-1bq8Y61KRfvxtDrg/edit#slide=id.g34fb28ebba3_0_82):
This PR:
- introduces `HomeViewMixer` 
- adds a `BoostHeroUnitsForNewUsersFilter` — which (unsurprisingly) boosts the `HeroUnit` section for newly created accounts
- puts this new logic behind a `onyx_enable-home-view-mixer` [Unleash …

feat(homeView): introduce HomeViewMixer and use it for for boosting content to new users

---

src/lib/featureFlags.ts
src/schema/v2/homeView/sections/QuickLinks.ts
src/schema/v2/homeView/sections/__tests__/QuickLinks.test.ts

https://artsyproduct.atlassian.net/browse/ONYX-1689
- Implements the new selection of Quick Links names and destinations for the v2 iteration.
- Places this behind the [onyx_enable-quick-links-v2](https://unleash.artsy.net/projects/default/features/onyx_enable-quick-links-v2) Unleash flag (enabled in staging)
When Eigen receives the updated response (and [supports the newest icons](https://github.com/artsy/eigen/pull/12003) ) it will look like this:

feat: implement QuickLinks v2

---

src/schema/v2/artwork/__tests__/createArtworkMutation.test.ts
src/schema/v2/artwork/createArtworkMutation.ts

Passes the new param to sync to ES inline that's been added in https://github.com/artsy/gravity/pull/18881

chore: pass sync_to_es: true when creating an artwork

---

_schemaV2.graphql
src/schema/v2/partner/Settings/__tests__/createPartnerContactMutation.test.js
src/schema/v2/partner/Settings/createPartnerContactMutation.ts

Consolidates the usage of `locationId` in the partner contacts mutation space
You'll notice the create mutation uses one spelling while the update uses another
- https://github.com/artsy/metaphysics/blob/main/src/schema/v2/partner/Settings/updatePartnerContactMutation.ts#L24
- https://github.com/artsy/metaphysics/blob/main/src/schema/v2/partner/Settings/createPartnerContactMutation.ts#L23
It is messing with Volt's side of things!

fix: Use locationId over locationID in partner contact space

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/exchange.ts
src/schema/v2/order/__tests__/updateOrderShippingAddressMutation.test.ts
src/schema/v2/order/updateOrderShippingAddressMutation.ts
src/schema/v2/schema.ts

https://artsyproduct.atlassian.net/browse/EMI-2399
Followup from https://github.com/artsy/exchange/pull/2535
Porting the new `PUT /api/me/orders/:id/shipping` REST endpoint from exchange in order to deprecate the update of shipping address related fields using `updateOrderMutation`.
The next step is to update Force to use this new mutation and remove shipping related fields from the `updateOrderMutation`.

feat(EMI-2399): create updateOrderShippingAddressMutation

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Solves [AMBER-1532]
Maps the new `CertificateOfAuthenticity` value added in https://github.com/artsy/gravity/pull/18886
[AMBER-1532]: https://artsyproduct.atlassian.net/browse/AMBER-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-1532 - adding coa

---

_schemaV2.graphql
src/schema/v2/filterArtworksConnection.ts

Makes for easier querying, rather than needing to go through the `show: Show`.

chore: add showID to filterArtworksConnection

---

src/lib/featureFlags.ts
src/schema/v2/homeView/__tests__/HomeView.test.ts
src/schema/v2/homeView/experiments/experiments.ts
src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
src/schema/v2/homeView/sections/ExploreByCategory.ts
src/schema/v2/homeView/sections/__tests__/DiscoverSomethingNew.test.ts
src/schema/v2/homeView/sections/__tests__/ExploreByCategory.test.ts
src/schema/v2/homeView/zones/__tests__/default.test.ts

This PR sets up part of an A/B test for the `discover_diamond-tab` experiment. This portion is responsible for hiding the _Discover Something New_ and _Explore by Category_ home view sections for users assigned to variant A. (Those users will be able to find those sections in the new discover tab, which is set up in [Eigen](https://github.com/artsy/eigen/pull/11974).)

feat(DIA-1286): set up discover tab a/b test

---

src/schema/v2/homeView/sections/QuickLinks.ts
src/schema/v2/homeView/sections/__tests__/QuickLinks.test.ts

https://artsyproduct.atlassian.net/browse/ONYX-1691
For Quick Links v2, this Implements the conditional **Your Bids** link that is shown only to users with active bids:
```js
{
title: "Your Bids",
href: "/inbox",
ownerType: OwnerType.inbox,
icon: undefined,
}
```
Tapping on the pill takes you to `/inbox`, which in turn defaults to the **Bids** view if there are active bids.
| Pill | Destination |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/429e6a63-a23b-4473-8ded-ba765a90295a" height=400 /> | <img src="https://github.com/user-attachments/assets/fcf37d0f-babd-4fd3-b989-4d68962bfb6d" height=400 /> |

feat: add Your Bids quick link for users with active bids

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/__tests__/updateOrderMutation.test.ts
src/schema/v2/order/__tests__/updateOrderShippingAddressMutation.test.ts
src/schema/v2/order/sharedOrderTypes.ts
src/schema/v2/phoneNumber.ts

type: **Feat**
relates to [EMI-2208] and artsy/force#15460
This PR adds the phone number type to an order's saved `fulfillmentDetails` object. I made minimal modifications to the existing type but it might deserve a larger conversation to make sure this wouldn't break something.
This assumes we would store country codes as the alpha2 code (technically case doesn't matter to the phone validation layer), not the `+{number}` code. This matches the behavior of the settings/shipping address modal which uses downcased alpha2.
This also includes a breaking schema change to the existing field it is replacing but I don't think we use it yet.
[EMI-2208]: https://artsyproduct.atlassian.net/browse/EMI-2208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2208): Rich phone number field for `Order.fulfillmentDetails` type

---

_schemaV2.graphql
src/schema/v2/Show/addInstallShotToPartnerShowMutation.ts
src/schema/v2/show.ts

cc @damassi 
This supports our current backend for the 'cover' of a show. The cover of a show can be selected by a user and is implemented as an install shot set as 'default'.
So we need to update the mutation to create an install shot to support creating one from URL as well as marking a created install shot as default. And then reading the data, on `imagesConnection` you need a way to specify to _exclude_ the cover image - which mimics what Force and Eigen do when presenting install shots (and excluding the cover).

chore: support install shots/covers for a show

---

_schemaV2.graphql
src/schema/v2/filterArtworksConnection.ts

Resolves https://www.notion.so/artsy/Allow-artworks-to-be-filtered-by-Import-Source-1decab0764a080f4be48cb86e0410668?pvs=4
* https://github.com/artsy/gravity/pull/18899
This adds an `importSources` arg to `filterArtworksConnectione` to allow filtering artworks by import source in Volt.

feat: Add `importSources` arg to `filterArtworksConnection`

---

_schemaV2.graphql
src/schema/v2/user.ts
src/schema/v2/users/updateUserMutation.ts

https://artsyproduct.atlassian.net/browse/PHIRE-1759
Related to https://github.com/artsy/gravity/pull/18901
Introduces `enabled` field to `UserType` and `updateUserMutation` to allow toggling of this field on a given user.

feat: add enable field to UserType and updateUserMutation

---

_schemaV2.graphql
src/schema/v2/order/__tests__/updateOrderMutation.test.ts
src/schema/v2/order/updateOrderMutation.ts

This is a followup from https://github.com/artsy/exchange/pull/2550
https://artsyproduct.atlassian.net/browse/EMI-2399

feat(EMI-2399): deprecate shipping params from updateOrderMutation

---

src/schema/v2/homeView/experiments/experiments.ts

I'm removing "diamond_discover-tab" from the list of currently running experiments on the Home View because:
1. It is not an experiment that is exclusive to the home view
2. This causes a tracking event to be fired when users visit the home view in the app

fix: remove discover tab from home view running experiments

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/DisplayTexts.ts
src/schema/v2/order/types/sharedOrderTypes.ts

I was trying to think how to add this additional texts that will be displayed in message for each state and make it shareable between Force and Eigen. Basically we need to cover all states in this table: https://www.figma.com/board/3y8s4tNuSvq69cs4DCb0Mm/Status-Page-Copy-Audit?node-id=64-158&t=MNHfmSmdNhHOcDSZ-4. (there might be some more updates there based on our discussions about arta state). 
Here is my initial proposal.
I tried to go through all the cases and assign them to the appropriate `buyer_state` that we have created previously. And seems like there is some additional sharing between state if we break the whole message into paragraphs. Added those strings into this table: https://docs.google.com/spreadsheets/d/1GOd7UHdyeLOSJTJRppR30ZW2vXq4JwGq_wKE5FFAzAY/edit?gid=346921686#gid= …

feat(WIP): add more properties to order.DisplayTexts

---

_schemaV2.graphql
src/schema/v2/artwork/updateArtworkMutation.ts

As part of Artemis -> Relay orders, missed that we sometimes need to update the artwork with a location (when a partner accepts an offer on an artwork w/ incomplete info and sets the location in the same 'step').

chore: set partnerLocationId when updating an artwork

---

src/lib/featureFlags.ts
src/schema/v2/homeView/mixer/__tests__/rules/AuctionEngagementRule.test.ts
src/schema/v2/homeView/mixer/rules/AuctionEngagementRule.ts
src/schema/v2/homeView/zones/__tests__/default.test.ts
src/schema/v2/homeView/zones/default.ts

https://artsyproduct.atlassian.net/browse/ONYX-1702 (and stacked on #6731)
This incorporates the new user auction segmentation into the [personalization logic](https://www.figma.com/design/3LYkzfvfTPcYAIgzkaOM1C/Personalization?node-id=39-8054&m=dev) for ordering the home view.
It does so by adding a new `AuctionEngagementRule` to the [recently introduced](https://github.com/artsy/metaphysics/pull/6677) `HomeViewMixer` 
This has the effect of taking three auction-related sections — Auctions; Auction Lots for You; Latest Auction Results — and hoisting them up near the top for eligible user segments: auction-`engaged` or auction-`adjacent` users. 
For all others this rule leaves the sections untouched.
```graphql
{
homeView {
sectionsConnection(first: 30) {
edges {
node {
internalID
}
}
}
} …
```

feat: add auction engagment rule to home view mixer

---

_schemaV2.graphql
src/lib/featureFlags.ts
src/lib/loaders/loaders_with_authentication/vortex.ts
src/schema/v2/homeView/mixer/__tests__/rules/AuctionEngagementRule.test.ts
src/schema/v2/homeView/mixer/rules/AuctionEngagementRule.ts
src/schema/v2/homeView/zones/__tests__/default.test.ts
src/schema/v2/homeView/zones/default.ts
src/schema/v2/me/__tests__/auctionSegmentation.test.ts
src/schema/v2/me/auctionSegmentation.ts
src/schema/v2/me/index.ts

https://artsyproduct.atlassian.net/browse/ONYX-1719
> [!NOTE]
> Now also contains the stacked changes from #6732 
Takes the user auction segmentation that newly resides in Vortex, and exposes it in MP on the `me` object.
The value is an enum, based on the [upstream classification](https://github.com/artsy/fulcrum/blob/main/dbt/models/analytics/content_personalization_models/auction_user_segmentation.sql#L2)
(This is mostly done as a convenience, on the way to using this segmentation in the home view mixer, in a separate PR).
```graphql
{
me {
email
auctionSegmentation
}
}
```
```json
{
"data": {
"me": {
"email": "somebody@example.com",
"auctionSegmentation": "ENGAGED"
}
}
}
```

feat: expose current user's auction segmentation from Vortex

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/DisplayTexts.ts
src/schema/v2/order/types/exchangeJson.ts

This will be used for display for https://artsyproduct.atlassian.net/browse/EMI-2436
Currently only has one happy pass test here. We need to figure out more comprehensive strategy for testing here. Created placeholder story for testing part: https://artsyproduct.atlassian.net/jira/software/c/projects/EMI/boards/114
@starsirius - also changed the field names to drop the `test` part per your suggestion. It's a breaking change for Force page but as it's behind feature flag - don't think is a big issue. Will update force as soon as this is merged.

feat: update fields on displayTexts for the order

---

_schemaV2.graphql
src/schema/v2/order/MeOrder.ts

This PR resolves [EMI-2442]
> [!Warning]
> This change is breaking, and we need to coordinate its release with Force (PR artsy/force#15574)
This PR updates the type of `me.order` argument from `String!` to `ID!`
[EMI-2442]: https://artsyproduct.atlassian.net/browse/EMI-2442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2442): Update Me Order argument type to ID

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/DisplayTexts.ts
src/schema/v2/order/types/sharedOrderTypes.ts

Discussed with @MrSltun that it might be really hard (next to impossible) to share html between Force and Eigen. So we might need to repeat texts for the message part as html elements integrated there. 
However we still want to keep the logic of what message is applicable based on all the 'mode', 'payment', 'shipment' etc combinations and create a very specific type just for this messageDisplay.

feat: add messageType as an alternative to displayMessage

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

Relies on the changes added during:
https://github.com/artsy/gravity/pull/18926
Allow bulk operations to filter artworks by published status and allow domestic shipping fee to be updated in batch.

feat: Allow flat fee update and published filter in bulk

---

src/lib/loaders/loaders_with_authentication/gravity.ts

feat: Adds authenticated partnerLoader
Volt's new settingsV2 experience is now _updating_ partner data through metaphysics. Before now there was only an unauthenticated `partnerLoader`, we are implementing an authenticated `partnerLoader` here to make the experience better for partners and bypass the cache of the unauth'ed loader
Tested this locally:
Note the `cache: true`
Note the nice fresh `cache: false` - you cannot tell from the screenshot but the cache was still false after making 10s of requests
This will address staleness reports from or recent QA
- https://www.notion.so/artsy/Settings-V2-1e3cab0764a08081931ed34703c5ead8

feat: Adds authenticated partnerLoader

---

_schemaV2.graphql
src/schema/v2/order/__tests__/DisplayTexts.test.ts
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/DisplayTexts.ts
src/schema/v2/order/types/sharedOrderTypes.ts

Unfortunately looks like sharing html straight out of MP for both Force and Eigen proved difficult. Would still require significant client code to format and interpret it properly and might make tracking and proper formatting more complicated.
So ended up creating the very 'custom' `messageType` here that will be mapped 1x1 to the view variations on client. And refactored it for Force.
Nothing else uses this `message` field so cleaning it up here to keep things simpler.

chore: remove message from displayTexts as we are using  instead

---

_schemaV2.graphql
src/lib/featureFlags.ts
src/lib/loaders/loaders_with_authentication/vortex.ts
src/schema/v2/homeView/helpers/__tests__/priceBucketBasedOnPricePreference.test.ts
src/schema/v2/homeView/helpers/priceBucketBasedOnPricePreference.ts
src/schema/v2/homeView/sections/QuickLinks.ts
src/schema/v2/homeView/sections/__tests__/QuickLinks.test.ts
src/schema/v2/me/__tests__/userPricePreference.test.ts
src/schema/v2/me/index.ts
src/schema/v2/me/userPricePreference.ts

This implements the conditional "Art Under $X" link that is shown only to users with [computed price preferences](https://github.com/artsy/vortex/pull/709). For this feature I've added a new field under `me`, which is called `pricePreference`.
Price buckets are the same as on the website under the "What's new" dropdown:
Request:
```graphql
{
me {
pricePreference
}
homeView {
sectionsConnection(first: 1) {
edges {
node {
... on HomeViewSectionNavigationPills {
navigationPills {
title
href
}
}
}
}
}
}
}
```
Response:
```json
{
"data": {
"me": {
"email": "nikita.skalkin@artsymail.com",
"pricePreference": 250
},
"homeView": {
"sectionsConnection": {
"edges": [
{
"node": {
"navigationPills": [
{
"title": "Discover Daily",
"href": "/infinite-discovery"
},
{
"title": "Auctions",
"href": …
```

feat: adds "Art Under $X" quick pill for users with price preferences

---

src/index.ts
src/schema/v2/__tests__/filterArtworksConnection.test.ts
src/schema/v2/filterArtworksConnection.ts
src/types/graphql.d.ts

Going off of some discussions in Slack around ElasticSearch stability, and noticing that some filters/combinations can be served by our non-ES endpoint - would that work better?
The resolver here is a good place to encapsulate that complexity - 'picking' which loader to use.
I decided to focus just on the initial screen partners see at /artworks (as well as paging through that) - when adjusting a sort, filter, search, etc. - we would fall back to the ES endpoint as usual.
One observation is that this endpoint feels like it could be a bit slower - but that might just be my local Metaphysics.
Another observation is that the code is kind of brittle/complex - but _maybe_ this pattern is ok and we can keep iterating?

chore: use a non-ES loader for a simple request to filterArtworksConnection from CMS

---

src/lib/apis/vortex.ts

This PR follows https://github.com/artsy/force/pull/15609 and ensures that we always use the `VORTEX_TOKEN`.

refactor: always use Vortex's app token

---

src/schema/v2/order/__tests__/DisplayTexts.test.ts
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/__tests__/support.ts
src/schema/v2/order/types/DisplayTexts.ts
src/schema/v2/order/types/PricingBreakdownLines.ts
src/schema/v2/order/types/exchangeJson.ts

Discovered a small bug in displayTexts that was from improper expectation for `selected_fulfillment_option` type. So updating here.

chore: add the type for fulfillment_option and refactor a bit how it's used

---

src/lib/apis/vortex.ts
src/lib/stitching/vortex/link.ts

This PR does two things:
1. Reverts #6769
2. adds a check for `vortex` to only propagate the given application token if it includes subject application. Otherwise, it will use the fallback `VORTEX_TOKEN`. 
This allows us to support both the `force` use case and braze use case. 
co-authored w/ @mzikherman

feat: only propagate vortex token if no subject application

---

src/lib/apis/vortex.ts

This PR patches #6772 . 
Looks like we inspected an incorrect token testing and `force`'s  does include a subject application so we need to fallback on another criteria. In this case, we will use the `email_provider` role.

refactor: fallback to vortex token based on role

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/exchangeJson.ts
src/schema/v2/order/types/sharedOrderTypes.ts

Allow queuing for  totalListPrice on the order. Will be used to display ListPrice for this pr: https://github.com/artsy/force/pull/15612
This value I believe gives us what we want here without looking at underlying artowk/edition_set/list items except for the case where `limited_partner_offer` is present on original artwork. This list price I believe will reflect this original 'partner offer'. Though I think it's valid to display this value as Artwork price in this case?

chore: allow requesting totalListPrice for meOrder

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/createArtworkImportMutation.ts

Thread the `async` argument through (decided not to tie it to the AI argument, can consolidate later if needed).

chore: support async creation of artwork import via mutation

---

src/schema/v2/partner/ArtsyShippingOptIn/__tests__/artsyShippingOptInMutation.test.ts
src/schema/v2/partner/ArtsyShippingOptIn/artsyShippingOptInMutation.ts
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

Resolges [AMBER-NOTION](https://www.notion.so/artsy/Let-bulkUpdateArtworksMetadata-mutation-fail-when-unauthorized-1ffcab0764a08062abf6f245841706d5?pvs=4)
This fixes error handling for `bulkUpdateArtworksMetadataMutation` and `ArtsyShippingOptInMutation`. 
**Before:**
**After:**
**Before:**
**After:**

fix: error handling for `bulkUpdateArtworksMetadataMutation` and `ArtsyShippingOptInMutation`

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/createArtworkImportMutation.ts

Query param added in https://github.com/artsy/gravity/pull/18984/ - to allow hooking up Claude vs GPT radio button in CMS.

chore: add parseWithAIModel input arg when creating artwork import

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

Modern Volt (backed by MP schema) needs to know if an artwork has a title or not. But, artworks can be explicitly titled as 'Untitled' - and MP uses that as a placeholder if an artwork lacks a title.
So, currently - we can't tell if an artwork that comes back as "Untitled" is _actually_ titled that, or is truly lacking a title.

chore: add hasTitle to Artwork type

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/DeliveryInfo.ts
src/schema/v2/order/types/exchangeJson.ts
src/schema/v2/order/types/sharedOrderTypes.ts

Just cherryPicking parts of what you added in https://github.com/artsy/metaphysics/pull/6789 minus this fancy shipperCode/url generation.
Debated if we want to consolidate `estimatedDelivery` and `estimatedDeliveryWindow'` into something like `estimatedDeliveryDisplay` but for now decided against it as clients might want to only display one. Also one is more of a string and the other one is a data format but not necessarily with timezone so might need to tweak it on the client.
Thanks @erikdstock for pushing the Exchange addition. And we can follow up with fancier url generation

chore: add deliveryInfo to order json

---

src/schema/v2/homeView/sections/QuickLinks.ts

Sets min app version to 8.75 for the Art Under $X quick link (introduced earlier here: https://github.com/artsy/metaphysics/pull/6751)

feat: Set app version for Art Under $X quick link to 8.75

---

src/lib/featureFlags.ts
src/schema/v2/homeView/experiments/experiments.ts
src/schema/v2/homeView/sections/NewWorksForYou.ts
src/schema/v2/homeView/sections/__tests__/NewWorksForYou.test.ts

https://artsyproduct.atlassian.net/browse/ONYX-1756
This implements the server-driven home view experiment for New Works for You with  price affinity.
Based on the Unleash flag [`onyx_nwfy-price-affinity-test`](https://unleash.artsy.net/projects/default/features/onyx_nwfy-price-affinity-test):
- users in the `control` group will continue to receive Version C 
- users in the `experiment` group will receive Version A (see [zenith/499](https://github.com/artsy/zenith/pull/499))
The experiment is enabled in staging already, but not in production. (And note that the experiment is app-only ([see thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1750092031700919)) so setting this experiment up for Force is out of scope.)
Here is Eigen emitting the corresponding tracking event based on this …

feat(home view): implement NWFY price affinity experiment

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/Purchases/__tests__/createPurchaseMutation.test.ts
src/schema/v2/Purchases/createPurchaseMutation.ts
src/schema/v2/schema.ts

This is part of the Torque deprecation effort. The new admin panel, Forque, does not include a Purchases section yet. Since Forque communicates with the backend via Metaphysics (unlike Torque, which talks to Gravity directly), we are adding support for creating, updating, and deleting purchases to Metaphysics.
This PR introduces the `createPurchase` mutation:
```graphql
mutation {
createPurchase(
input: { ... }
) {
... on CreatePurchaseSuccess {
purchase {
internalID
}
}
... on CreatePurchaseFailure {
error
message
}
}
}
}
}
```

feat(onyx-1664): createPurchase mutation

---

src/lib/semanticVersioning.ts
src/schema/v2/homeView/helpers/__tests__/isSectionDisplayable.test.ts
src/schema/v2/homeView/helpers/isSectionDisplayable.ts
src/schema/v2/homeView/sections/index.ts

This PR adds a `maximumEigenVersion` to the existing logic that checks whether a Home View section is displayable or not.
This is needed because we will be moving Discover Something New and Explore by Category from the Home tab to the Search tab in an upcoming release, but we still need to guarantee that old versions of the app continue showing them on the Home tab.
For context, we added `minimumEigenVersion` to prevent the Discover Daily entry point from displaying on older versions of the app (that did not know about Discover Daily).
cc: @artsy/diamond-devs

feat(DIA-1363): add maximum eigen version to home view sections

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/infiniteDiscovery/excludeArtistFromDiscoveryMutation.ts
src/schema/v2/schema.ts

This PR adds a new GraphQL mutation that allows users to exclude artists when dismissing them in Discover Daily.
Changes:
- Created excludeArtistFromDiscovery mutation
- Added excludeArtistFromDiscoveryLoader gravity loader with endpoint artworks_discovery/artist/exclude
This mutation follows the same pattern as createUserSeenArtwork but is used when users want to exclude/dismiss artists from Discover Daily.

feat: add excludeArtistFromDiscoveryLoader

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Solves [AMBER-1682]
This maps the newly added attribute for ArtworkImportRowError in this Gravity PR: https://github.com/artsy/gravity/pull/19039
[AMBER-1682]: https://artsyproduct.atlassian.net/browse/AMBER-1682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-1682 - adding blocking attribute per row error

---

_schemaV2.graphql
src/schema/v2/__tests__/marketingCollections.test.ts
src/schema/v2/marketingCollections.ts

This PR makes the `discoveryMarketingCollections` query guarantee non-null results so that clients don't need to filter them out if the discovery collections are changed.

feat(DIA-1363): guarantee non-null discoveryMarketingCollections results

---

src/schema/v2/ArtworkImport/artworkImport.ts

Relates to the changes recently made in Gravity: https://github.com/artsy/gravity/pull/19057
As the error value has been updated for the certificate of authenticity, we need to ensure that the mapping works as expected. There should be no changes required in the consumer of this, Volt.
cc: @artsy/amber-devs

chore: AMBER-1709 - updating error code to be more readable for partners

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/__tests__/fairsConnection.test.ts
src/schema/v2/fairs.ts

Stemming off this PR: https://github.com/artsy/metaphysics/pull/6842
Diagnosing from @lidimayra:
> It looks like the older version relied on the specific match endpoint for fairs ([ref](https://github.com/artsy/volt/blob/36dac6f61cb29b38458922257ddb122f1c25ca08/app/controllers/partner_shows_controller.rb#L33)).
> The new one relies on the generic match ([ref](https://github.com/artsy/volt/blob/36dac6f61cb29b38458922257ddb122f1c25ca08/app/javascript/components/AutocompleteInputs/FairAutocomplete.tsx#L250)).
> When switching from one to the other, we ended up losing the automatic access we had to non-public data if the request came from a user with special permissions ([ref](https://github.com/artsy/gravity/blob/a2f8ddd7960d2da26710f10a67c3da16989f8d32/app/api/v1/match_endpoint.rb#L79-L80)). …

fix: Allow authenticated users to query for `visibile_to_public:false` fairs

---

_schemaV2.graphql
src/schema/v2/order/__tests__/submitOrderMutation.test.ts
src/schema/v2/order/exchangeErrorHandling.ts
src/schema/v2/order/submitOrderMutation.ts
src/schema/v2/order/types/sharedOrderTypes.ts

This PR is of type **FIX**.
Relates to [EMI-2448]
Exchange error handling and transformation into graphql schema error types was implemented at the same time as our `submitOrderMutation` causing us to not do it for that case. As a result we are getting generic errors from these responses.
**Breaking change** in the process of doing this I noticed one type name was too specific so I changed it. I'm not sure if it is safe to merge as is (assuming we don't reference its typename specifically). We can revert it and fix it some other way if necessary.
Paired with @rquartararo for the main fix.
[EMI-2448]: https://artsyproduct.atlassian.net/browse/EMI-2448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2448): propagate exchange processing errors from submit mutation

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Partially solves [AMBER-1735]
Ensure that we are displaying the dimension metric as this will be used on the front end as each Artwork Import has their own denormalised currency and measurement.
[AMBER-1735]: https://artsyproduct.atlassian.net/browse/AMBER-1735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-1735 - artwork import preferences

---

_schemaV2.graphql
src/schema/v2/homeView/sectionTypes/Artworks.ts
src/schema/v2/homeView/sectionTypes/_ExampleSectionType.ts
src/schema/v2/homeView/sections/NewWorksForYou.ts
src/schema/v2/homeView/sections/_ExampleSection.ts
src/schema/v2/homeView/sections/__tests__/NewWorksForYou.test.ts

Solves [ONYX-1780]
This PR adds `enableItemsImpressionTracking` to artwork sections
| section with enableItemsImpressionTracking disabled | section with enableItemsImpressionTracking enabled |
|--------|--------|
| <img width="1148" alt="Screenshot 2025-07-02 at 10 45 51" src="https://github.com/user-attachments/assets/e37aa901-220f-4c77-90ad-305264b8e312" /> | <img width="1153" alt="Screenshot 2025-07-02 at 10 46 05" src="https://github.com/user-attachments/assets/fe0a1d40-935a-4e32-9dda-363a386dfa72" /> | 
[ONYX-1780]: https://artsyproduct.atlassian.net/browse/ONYX-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add trackItemImpressions to HomeViewSectionArtworks

---

src/schema/v2/homeView/sectionTypes/_ExampleSectionType.ts
src/schema/v2/homeView/sections/_ExampleSection.ts

In the interest of keeping the home view schema and docs as tightly scoped to real-world usage as possible I've made a couple of minor tweaks here.
- Defaulting `trackItemImpressions` to `false`, since we only want to opt into the extra analytics traffic deliberately
- Removing the `trackItemImpressions` implementation from the example section type, since as of now it only pertains to _artwork_ section types, which have already been implemented nicely  in https://github.com/artsy/metaphysics/pull/6872. My feeling is that we can expand this capability to other section types as needed, rather than preemptively.

docs: minor updates to home view examples

---

src/schema/v2/artist/__tests__/index.test.js
src/schema/v2/artist/index.ts

This PR adds italics to the credit line that is included in a `biographyBlurb` when the bio was written by a partner.

fix: missing italics in artist bio credit line

---

src/lib/featureFlags.ts
src/schema/v2/homeView/experiments/experiments.ts
src/schema/v2/homeView/sections/NewWorksForYou.ts
src/schema/v2/homeView/sections/__tests__/NewWorksForYou.test.ts

https://artsyproduct.atlassian.net/browse/ONYX-1798
> [!NOTE]
>  We [recently](https://artsy.slack.com/archives/C07SYJBE2BC/p1751017440653529?thread_ts=1745333102.588449&cid=C07SYJBE2BC) standardized some [advice on flag and variant naming](https://www.notion.so/artsy/Feature-Toggles-and-Experiments-43523493b48a4a92882037f0106bef5c?source=copy_link#21bcab0764a0807b9446f66a0db44a44), so this PR adheres to that — thus the slight naming inconsistency between the previous and current experiment.
Last week we [closed](https://artsy.slack.com/archives/C05EQL4R5N0/p1751563795173429) the price affinity experiment (and plan to re-open it at a later date once we have revised the price prediction model).
In the meantime we will run a different experiment in NWYF recs — this time a/b testing a …

feat: create NWFY artist diversity experiment

---

src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
src/schema/v2/homeView/sections/ExploreByCategory.ts
src/schema/v2/homeView/sections/__tests__/DiscoverSomethingNew.test.ts
src/schema/v2/homeView/sections/__tests__/ExploreByCategory.test.ts

This PR adds 8.77.0 as the maximum eigen version for the _Discover Something New_ and _Explore by Category_ home view sections. For version 8.78.0 and beyond those sections will be displayed on the search tab instead of on the home view.
cc: @artsy/diamond-devs

chore: add maximum eigen version for discovery sections

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/partner/BulkOperation/__tests__/bulkAddArtworksToShowMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkAddArtworksToShowMutation.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts
src/schema/v2/partner/BulkOperation/shared.ts
src/schema/v2/schema.ts

Adding mutation level support for bulk add to show
This will power the experience in our bulk edits flow to allow users to batch add artworks to a show
Ex of the spiked behavior end to end can be seen in #bulk_publishing channel

feat: Adding mutation level support for bulk add to show

---

_schemaV2.graphql
src/schema/v2/__tests__/show.test.js
src/schema/v2/show.ts

Updates the show counts field with new `publishedArtworks` and `unpublishedArtworks` counts:
```graphql
{
show(id:"gazelli-art-house-art-dubai-digital") {
counts {
publishedArtworks
unpublishedArtworks
artworks
}
}
}
```

feat(show): Add published / unpublished counts

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Another easy one/no-op!
We now expose currency/dimension metric at the row level, _and_ we can use that currency to generate our nicely formatted prices (vs. needing to inject the import-level one).
With this PR (on top of https://github.com/artsy/gravity/pull/19120), I can go into Volt and update the import table to always use these row-level attributes when rendering the actual row.
That's going to be a no-op as well (backwards compatible).
But, this will unlock something neat - if I go in to a Gravity console and update the currency/dimension metric of a particular row on an import and reload the table in Volt - I'll see that row with the correct info! (and the artwork will be created with those attributes as well).
So that will fully unlock actually integrating setting the row-level …

chore: always use row-level properties for currency and dimension metric for imports

---

_schemaV2.graphql
src/schema/v2/partner/ArtsyShippingOptIn/artsyShippingOptInMutation.ts
src/schema/v2/partner/BulkOperation/__tests__/bulkAddArtworksToShowMutation.test.ts
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkAddArtworksToShowMutation.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts
src/schema/v2/partner/BulkUpdateSourceEnum.ts
src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts

Allow clients to pass in a `source` arg into our batch operation mutations
This allows us to diagnose and record where these batches are getting triggered from
Options include:
- admin
- artworks_list
- partner_artist_artworks_list
- show_artworks_list
See gravity API here
- https://github.com/artsy/gravity/pull/19124
- https://github.com/artsy/gravity/pull/19099

feat: Allow source to be sent in bulk update mutations

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

This fix addresses a signature property misspelling in the previous change [AMBER-1813](https://artsyproduct.atlassian.net/browse/AMBER-1801)
[AMBER-1813]: https://artsyproduct.atlassian.net/browse/AMBER-1813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: correcting signature property name for bulk-update

---

src/schema/v2/homeView/experiments/experiments.ts
src/schema/v2/homeView/sections/NewWorksForYou.ts
src/schema/v2/homeView/sections/__tests__/NewWorksForYou.test.ts

https://artsyproduct.atlassian.net/browse/ONYX-1844
- The [Artist Diversity re-ranking experiment](https://www.notion.so/Artist-Diversity-Re-Ranking-in-NWFY-225cab0764a08056b47ed08d283cf4ab?pvs=21) that was added in https://github.com/artsy/metaphysics/pull/6892 has passed 🎉
- So this removes the experiment flag and serves Version C ([now updated](https://github.com/artsy/zenith/pull/535) to incorporate the winning variant's logic)
TODO

feat(NWFY): serve version C with artist diversity re-reranking to all users

---

_schemaV2.graphql
src/schema/v2/order/__tests__/MeOrder.test.ts
src/schema/v2/order/types/exchangeJson.ts
src/schema/v2/order/types/sharedOrderTypes.ts

Depends on https://github.com/artsy/exchange/pull/2661
Completes [EMI-2506]
This order uses the existing OrderPaymentMethod enum and the new field returned from exchange's order json in artsy/exchange#2661 to add an `Order.availablePaymentMethods` field.
[EMI-2506]: https://artsyproduct.atlassian.net/browse/EMI-2506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2506): add Order.availablePaymentMethods field

---

src/lib/featureFlags.ts
src/schema/v2/homeView/experiments/experiments.ts
src/schema/v2/homeView/sections/NewWorksForYou.ts
src/schema/v2/homeView/sections/__tests__/NewWorksForYou.test.ts

https://artsyproduct.atlassian.net/browse/ONYX-1854
Following established patterns (e.g. the just-concluded [artist diversity experiment](https://github.com/artsy/metaphysics/pull/6892)) we open a new experiment here for the [at-risk gallery boost](https://www.notion.so/artsy/At-Risk-Galleries-Boost-AB-Test-234cab0764a080a9b554dc3e960742b9?v=7bb661aa9b914cfdb5ff867c027ce6f9).
This is based on the Unleash flag [onyx_nwfy-at-risk-gallery-boost-experiment](https://unleash.artsy.net/projects/default/features/onyx_nwfy-at-risk-gallery-boost-experiment), which is already enabled in staging.

feat(NWFY): create at-risk gallery boost experiment

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/ArtworkImport/__tests__/toggleArtworkImportRowExclusionMutation.test.ts
src/schema/v2/ArtworkImport/artworkImport.ts
src/schema/v2/ArtworkImport/toggleArtworkImportRowExclusionMutation.ts
src/schema/v2/schema.ts

Mutation to use https://github.com/artsy/gravity/pull/19171 to deselect an artwork import row from import.
I'll also need to raise another small Gravity PR to make sure those deselected rows are not returned to `rowsConnection`.

chore: add mutation to deselect an artwork import row from import

---

_schemaV2.graphql
src/schema/v2/order/__tests__/confirmationToken.test.ts
src/schema/v2/order/confirmationToken.ts

I realized we don't need this, we can just use `__typename`.
Reverts artsy/metaphysics#6962

revert: "feat(EMI-2674): add a type field to the confirmationToken query"

---

src/lib/loaders/loaders_with_authentication/gravity.ts

Related: https://github.com/artsy/gravity/pull/19205
This updates the endpoint for the artwork_import remove artwork image. 

chore(imports): Update delete artwork endpoint

---

_schemaV2.graphql
src/schema/v2/artist/__tests__/index.test.js
src/schema/v2/artist/index.ts
src/schema/v2/artist/updateArtistMutation.ts
src/schema/v2/artwork/__tests__/artwork.test.js

This PR adds `foundations` and `residencies` fields to updateArtistMutation and cleans up unused `USE_UNSTITCHED_ARTIST_SERIES_SCHEMA` env vars from unrelated tests.
- Add foundations and residencies inputs to the Forque UI for admin support 

feat: add foundations and residencies field to UpdateArtistMutation

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/ArtworkImport/__tests__/updateArtworkImportRowImageMutation.test.ts
src/schema/v2/ArtworkImport/__tests__/updateArtworkImportRowImagesMutation.test.ts
src/schema/v2/ArtworkImport/artworkImport.ts
src/schema/v2/ArtworkImport/updateArtworkImportRowImageMutation.ts
src/schema/v2/ArtworkImport/updateArtworkImportRowImagesMutation.ts
src/schema/v2/schema.ts

Related:
- https://github.com/artsy/gravity/pull/19228.
Adds some mutations to support image reordering in artwork imports.
- `updateArtworkImportRowImage` - Updates single image position
- `updateArtworkImportRowImages` - Batch updates multiple image positions  
- Added `position` field to `ArtworkImportRowImage` type
- Added loaders for both REST endpoints
```graphql
mutation {
updateArtworkImportRowImage(
input: {
artworkImportID: "artwork-import-1"
imageID: "image-1" 
position: 3
}
) {
updateArtworkImportRowImageOrError {
... on UpdateArtworkImportRowImageSuccess {
artworkImportID
}
}
}
}
```
```graphql
mutation {
updateArtworkImportRowImages(
input: {
artworkImportID: "artwork-import-1"
images: [
{ id: "image-1", position: 0 }
{ id: "image-2", position: 1 }
]
}
) { …
```

feat: Add image position mutations for artwork imports

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/__tests__/updateArtworkImportRowImagesMutation.test.ts
src/schema/v2/ArtworkImport/updateArtworkImportRowImagesMutation.ts

Related:
- https://github.com/artsy/gravity/pull/19229
Updates the batch image position mutation to align with simplified Gravity API, addressing GraphQL serialization issues with nested objects in array parameters.
- Simplified `updateArtworkImportRowImages` input to accept flat array of image IDs
- Position determined by array order (0-based indexing) instead of explicit position values
- Updated tests to reflect new API format
```graphql
mutation {
updateArtworkImportRowImages(
input: {
artworkImportID: "artwork-import-1"
positions: ["imageID-3", "imageID-2", "imageID-1"]
}
)
}
```

fix: Simplify batch image position mutation for Gravity API compatibility

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/v2/ArtworkImport/__tests__/removeArtworkImportImageMutation.test.ts
src/schema/v2/ArtworkImport/__tests__/updateArtworkImportRowImagesMutation.test.ts
src/schema/v2/ArtworkImport/removeArtworkImportImageMutation.ts
src/schema/v2/ArtworkImport/updateArtworkImportRowImagesMutation.ts

Related:
- https://github.com/artsy/gravity/pull/19232
Updates artwork import image mutations to align with refactored Gravity API that migrates image operations from import-level to row-level scoping.
- Updated `updateArtworkImportRowImages` mutation to use row-scoped endpoint
- Updated `removeArtworkImportImage` mutation to use row-scoped endpoint  
- Added required `rowID` parameter to both mutations
- Changed `positions` to `sortedImageIDs` for batch updates
- Updated loaders and tests for new API structure
```graphql
mutation {
updateArtworkImportRowImages(
input: {
artworkImportID: "artwork-import-1"
rowID: "row-1"
sortedImageIDs: ["image-3", "image-2", "image-1"]
}
)
}
```

feat: Update artwork import image mutations for row-scoped API

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

feat: Support Certificate of Authenticity related boolean fields in Batch edits
Exposes the backend logic [here](https://github.com/artsy/gravity/blob/main/app/services/partner_artworks/batch_edit_builder_service.rb#L10-L30)
Allows client to send over values for
- certificate of authenticity
- coa by gallery
- coa by 3rd party
AKA: These boolean fields on the artwork form:

feat(batch-edit): Support Certificate of Authenticity related boolean fields

---

src/lib/featureFlags.ts
src/schema/v2/homeView/experiments/experiments.ts
src/schema/v2/homeView/sections/NewWorksForYou.ts
src/schema/v2/homeView/sections/__tests__/NewWorksForYou.test.ts

We open a new experiment for the [view frequency penalty](https://github.com/artsy/zenith/pull/546). You can find an Unleash feature flag [here](https://unleash.artsy.net/projects/default/features/onyx_nwfy-view-frequency-penalty-experiment).

feat(onyx-1874): NWFY - create view frequency penalty experiment

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/__tests__/matchArtworkImportImagesMutation.test.ts
src/schema/v2/ArtworkImport/matchArtworkImportImagesMutation.ts

Ah, didn't update the MP PR after addressing PR feedback in here: https://github.com/artsy/gravity/pull/19251. This moves the rowID arg into the image mutation, to keep things flexible (vs just on the parent arg of the mutation. 

fix(imports): Row id arg should be image level

---

_schemaV2.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/searchLoader.ts
src/schema/v2/Match.ts
src/schema/v2/search/index.ts

Adds `INTERNAL_AUTOSUGGEST` search mode. When specified, it calls the `/match/suggest/internal` endpoint, created to support admin panel needs (e.g., search by slug, ID, etc.).
Related PRs:
- https://github.com/artsy/gravity/pull/19267
- https://github.com/artsy/gravity/pull/19274

feat(onyx-1883): INTERNAL_AUTOSUGGEST mode for matchConnection

---

scripts/push-schema-changes.js

After the work to remove Artemis from Pulse, we don't need to sync the schema there anymore.

chore(EMI-1996): stop pushing schema to Pulse

---

src/schema/v2/me/userAddress/userAddressesConnection.ts

This PR sets the default size for UserAddresses to 20. Normally, the size comes from the client, but this is an exception due to how the stitched experience worked.

chore: set the default size for UserAddresses

---

_schemaV2.graphql
src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts

Resolves [AMBER-1892](https://artsyproduct.atlassian.net/browse/AMBER-1892)
* Related Volt PR: https://github.com/artsy/volt/pull/9818
This adds support for bulk updating signature information. Types and transformation helpers have already been implemented for updating My Collection artworks in https://github.com/artsy/metaphysics/pull/5751 and are reused in this PR.
@artsy/amber-devs 
[AMBER-1892]: https://artsyproduct.atlassian.net/browse/AMBER-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Support bulk updating signature information

---

src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/collectorSignals.ts

Theoretically we could have removed the check for sale_ids as `inquireable` include the check for `at_auction` however the work is considered `at_auction` seems to only be true if the auction is active and not in a live portion but `sale_id` stays persistent. So not sure what exactly we want to 'collector signals` so decided not to touch it.

feat(EMI-2356): return collector signals for inquireable artworks as well as for purchasable

---

_schemaV2.graphql
scripts/push-schema-changes.js
src/schema/v2/ArtworkImport/artworkImport.ts

Also exposes s3Key and s3Bucket on artwork imports

feat(push-changes): Add artsy-mcp to repo list

---

.circleci/config.yml
scripts/push-schema-changes.js

Parallelism needs to match the number of repos we're pushing to, otherwise things error out on ci:
https://app.circleci.com/pipelines/github/artsy/metaphysics/28677/workflows/43d4c458-5636-4c58-9836-50f325b11954/jobs/58288. This was after adding `artsy-mcp` to the list of repos needing changes. 

fix(push-schema): Update parallelism count for push-schema-changes job

---

scripts/push-schema-changes.js

All of our repos typically have relay, prettier, etc installed, but our mcp server just needs the schema. So add a few config options for skipping these common operations.

feat(sync): Add config params for skipping common graphql operations during sync

---

.github/workflows/run-danger.yml
danger/compareForceSchema.ts

Adds reusable workflow to run `compareForceSchema` checks via danger. The intent is to replace the current Peril checks.
Looking at [peril-settings](https://github.com/artsy/peril-settings/blob/main/peril.settings.json#L21-L22) it seems we are only running the `compareForceSchema` checks and not `dangerfile.ts`. Please let me know if I'm mistaken.
I set `fail-on-errors` to false, based off behaviours I could see in other PRs. For example, [this PR](https://github.com/artsy/metaphysics/pull/7065) failed the comparison but the check was marked as successful (apologies if this changes by the time you read this!).
**Testing**
[Here](https://github.com/artsy/metaphysics/pull/7071) is an example of a message being left when there's a breaking change.

feat: add github workflow to compare force schema

---

scripts/push-schema-changes.js

MP CI is failing due to upgrades from yarn 1 to 4, looks like this `ignore-engines` option [isn't supported anymore](https://github.com/yarnpkg/berry/blob/62fd8525b8e1e6fc73431c38e4101eab2496c3b6/packages/plugin-essentials/sources/commands/install.ts#L137).
Not sure if this is the right fix, but figured I'd open a PR for feedback and see.

fix(yarn): yarn 2+ doesn't support ignore-engines

---

scripts/push-schema-changes.js

This updates the push-schema destination config to account for the new artsy-mcp monorepo [setup](https://github.com/artsy/artsy-mcp/pull/16).

fix(push-schema): Update destination path for artsy-mcp schema

---

scripts/push-schema-changes.js

skip deprecated engine check to fix schema update failures in energy.

fix: enable skip deprecated engine check now that energy on yarn 4

---

src/lib/loaders/loaders_without_authentication/gravity.ts

Part of the flow that will support [EMI-2804](https://artsyproduct.atlassian.net/browse/EMI-2804)
- Adds `collector_profiles` and `collector_profile_summary` endpoints to `loaders_without_authentication`.
Allows for requests for `collectorProfile` and `summaryAttributes` to be called without `X-ACCESS-TOKEN`. Instead, we'll pass `X-XAPP-TOKEN` and gate on gravity's side.
[EMI-2804]: https://artsyproduct.atlassian.net/browse/EMI-2804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add collector profile endpoints to non-authenticated loaders

---

_schemaV2.graphql
src/schema/v2/ArtworkImport/artworkImport.ts

Partially solves [AMBER-2009]
Exposes the `ImportSource` field added in https://github.com/artsy/gravity/pull/19395
[AMBER-2009]: https://artsyproduct.atlassian.net/browse/AMBER-2009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-2009 - add import source

---

_schemaV2.graphql
src/schema/v2/artwork/index.ts

fix: Adds `artlogic`, `artcloud`, and `BATCH_UPLOAD` to import source types
Resolves a portion of [AMBER-2032](https://artsyproduct.atlassian.net/browse/AMBER-2032)
This is needed as Volt relies on `ArtworkImportSource` Enum type for import source related filtering
Examples
Note `importSource` is `null` despite having import sources in the DB and thus hiding the Import source filter 🐛 
https://github.com/user-attachments/assets/717a6eaf-1f36-4b98-ac70-0b66e8cfe97d
Note `importSource` value is present and filtering works as expected ✅ 
https://github.com/user-attachments/assets/282e3052-d079-4fd2-bd15-cea6782f0219
cc @artsy/amber-devs 
[AMBER-2032]: https://artsyproduct.atlassian.net/browse/AMBER-2032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …

fix: Adds artlogic, artcloud, and batch upload to import source types

---

src/lib/featureFlags.ts
src/schema/v2/homeView/experiments/experiments.ts
src/schema/v2/homeView/sections/NewWorksForYou.ts
src/schema/v2/homeView/sections/__tests__/NewWorksForYou.test.ts

This implements [price re-ranking home view experiment](https://github.com/artsy/zenith/pull/614/files) for New Works for You. It is based on the Unleash feature flag [onyx_nwfy-price-reranking-test](https://unleash.artsy.net/projects/default/features/onyx_nwfy-price-reranking-test).
`control` group receives version `C`, `experiment` group -- version `A`.
At the moment, the experiment is enabled on staging only.

feat: create NWFY price re-ranking experiment
