.env.test
lib/apis/google_cse.js
lib/loaders/google_cse.js
lib/loaders/index.js
lib/routing.js
schema/day_schedule.js
schema/index.js
schema/search/index.js
schema/search/search_entity.js
schema/search/search_result.js

Re: https://github.com/artsy/metaphysics/issues/13
Trying this made me like Google CSE even less.
Part of the main problem here is that there's not a fantastic way to get a canonical entity ID and type given a URL. So there's a lot of guess work involving parsing the URL and parsing whatever poorly specified meta tags/open graph tags we have around. It's very, very gross.
A query might look like:
```graphql
query search($term: String!) {
search(term: $term) {
results {
id
type
title
href
entity {
... on ArtistSearchEntity {
image {
...CroppedThumbnail
}
artworks(size: 5) {
images(size: 1) {
...CroppedThumbnail
}
}
}
... on ArtworkSearchEntity {
images(size: 1) {
...CroppedThumbnail
}
}
... on ProfileSearchEntity {
image {
...CroppedThumbnail
}
}
... on PartnerShowSearchEntity { …
```

@broskoski: Orchestrate Google CSE results

---

schema/article.js
schema/image/cropped.js
test/schema/image/cropped.js

I feel eh about this.
Basically, positron thumbnail images are just a url to the original:
I still want to use the crop code which returns the proxied URL for this.

@dzucconi => Allow images to just be url

---

README.md

I keep forgetting how to do this, and favor it over clicking the button in the Heroku panel. If only there were a Slack integration.

@dzucconi: Adds instructions for promoting to production from the command line

---

schema/image/resized.js

So... sometimes Gravity gives us a response with an existy image object that's empty. (which makes  zero sense).
On a related note: `cropped` is completely broken because of this https://github.com/artsy/metaphysics/commit/f0f7ab481eb4769139355e1b0e59b1aeb81e6fa0 which wasn't a great idea.
(Mints URLs that look like: `https://i.embed.ly/1/display/crop?url%5Bid%5D=5633b4b772616964060000a2&url%5Bposition%5D=1&url%5Bcaption%5D=&url%5Bdefault%5D=false&url%5Baspect_ratio%5D=&url%5Boriginal_height%5D=&url%5Boriginal_width%5D=&url%5Bimage_url%5D=&url%5Bgemini_token%5D=WagRqg8ovVO3eaBvGBklWw&url%5Bcached%5D=1452802281684&width=300&height=300&key=a1f82558d8134f6cbebceb9e67d04980&quality=95`)
Can you help me resolve this all when you get back @mzikherman?
In the meantime this stops the bleeding on …

@broskoski: image_url null

---

schema/input_fields/partner_categorytype.js
schema/partner_categories.js
schema/partner_category.js
schema/partners.js

I'm putting the query I made here so that I don't forget it
```
{
partner_categories(category_type:"Gallery"){
id
name
primary: partners(eligible_for_primary_bucket: true, has_full_profile:true, default_profile_public:true) {
... partner
} 
secondary: partners(eligible_for_secondary_bucket:true, has_full_profile:true, default_profile_public:true){
... partner
}
}
}
fragment partner on Partner  {
id
initials
locations {
city
}
profile {
image {
url(version:"featured")
}
}
}
```
Partners can take buckets and a bunch of other stuff. Also made it so that Partners nested in a Category can be filtered the same way.

@dzucconi -> add more params to partners, nest them in categories

---

schema/artwork/index.js
schema/image/cropped.js
schema/image/normalize.js
schema/image/resized.js
schema/image/versioned.js
test/schema/image/normalize.js

Artworks *very* often will not have a `larger` version but usually have a `large` (UGH).
This lets us query for an image like:
```
{
artwork(id: "some-id") {
resized(width: 500, version: ["larger", "large"]) {
url
}
}
}
```
In the case of a missing `larger`, we'll get a URL for the `large`.
GraphQL will coerce a list type so queries that use the non array form of `version: "larger"` will work fine.

@dzucconi: Support a prioritized list of image versions for `version` arg

---

schema/aggregations/filter_partners_aggregation.js
schema/filter_partners.js

the `total` aggregation looks different and should be treated different
for my a set of coordinates and selected category, i can get the search results and the total number of results for my given parameters, and the counts of all other categories with results that match my coordinates:

@dzucconi moar filter partners

---

lib/apis/gravity.js
lib/loaders/authenticated_http.js
schema/bidder_position.js
schema/bidder_positions.js
schema/index.js

This allows a single query for "My Active Bids" w00t w00t <3 <3 <3 Metaphysics. Not sure if this makes sense but the query uses `bidder_positions(me: true)` to indicate "find by access token". I noticed we have a `me` schema—maybe it belongs there instead? It seems odd to bloat that schema up with all "me" things though. Open to all ideas.

@dzucconi: Bidder positions schema

---

schema/index.js
schema/me.js

Sorry to be fickle about this, but I just want to decide on a flexible convention for querying "me" resources. My initial thought was something close to the "restful" approach—which would be using a param to modify a root resource e.g. something like `/api/v1/bidder_positions?user_id=me`, so `bidder_positions(me: true)` made sense to me at first. However, I couldn't find any best practices example of this for GraphQL—since we already have a me->profile in place, I think expanding inside `me` makes sense.
It's a small thing, but I think this'll make it more obvious when deciding how to query something, e.g. if down the line we want to query that admin-only "all bidder positions" my first thought would be:
```
bidder_positions {
id
...
}
```
Which would trip me up when it returns only my …

@dzucconi: Move bidder positions under "me"

---

schema/me.js
test/schema/me.js

My `filter/map/map/find/filter/map/find/map/filter/filter/find` logic was going about finding bidder positions in "open" auctions in the wrong direction which caused a subtle bug where it would return dupe bidder positions.
This is because I was approaching it from the auciton->sale_artwork->bidder_position direction—where as now I just filter down the bidder positions according to their related `sale_artwork.sale`.

@dzucconi: Fix logic that was causing dupes for bids in the same auction

---

schema/partner_categories.js

cc @1aurabrown 
On the /institutions page, we don't want to display internal categories. This adds the [param](https://github.com/artsy/gravity/blob/a96a1dd570994ae9d2f5290b7f0e715d8b7c9a82/app/api/v1/partner_categories_endpoint.rb#L11) to the partner_categories schema, and so we can filter them out.

@dzucconi Add the "internal" arg to the partner_categories schema.

---

schema/me/bidder_positions.js

I noticed when testing my active bids stuff that if someone places a ton of bids, they can reach beyond the first pages and not show up. Simple fix—just sort by most recently placed, or `-created_at`

@broskoski: Sort by -created_at

---

schema/artist/statuses.js

@briansw pointed out a bug where the biography tab went missing from artist pages after i started fetching statuses from metaphysics rather than compiling them on the client based on a series of netsed fetches and logic. This fixes that.

@dzucconi : move biography status to metaphysics

---

schema/artist/index.js

The last fallback of the waterfall relaxed restrictions to just be any fair booths.
Some institutional partners (ICI) have fair booths as well (?), so be more explicit with `at_a_fair: false`.
Sort the final 5 selected shows.

Couple tweaks to exhibition highlights

---

schema/sale_artwork.js

I didn't see any `amount_cents` [fields on the sale artwork Gravity](https://github.com/artsy/gravity/blob/master/app/models/domain/sale_artwork.rb#L47)... doesn't seem like we use that anywhere (it does a appear under `highest_bid` so maybe copypasta fluke `¯\_(ツ)_/¯`). We do however have `reserve_cents` which is something that may be useful for Live (at-least for now it'll help me sync data to Causality for dev purpose).

@broskoski: Adds reserve_cents to sale artwork; removes amount_cents

---

schema/me/home_page_modules.js
schema/me/index.js

cc @alloy @mzikherman 
Still working on this but want to keep some feedback before I get too deep in. 
My current thinking is:
```
query {
me{
id
home_page_modules{
key
display
title
}
}
}
```
(would return something like):
```
{
"data": {
"me": {
"id": "547e891d7261691220dc0000",
"home_page_modules": [
{
"key": "followed_artists",
"display": "true",
"title": "Works by Artists you Follow"
},
{
"key": "followed_galleries",
"display": "true",
"title": "Works from Galleries you Follow"
},
{
"key": "saved_works",
"display": "true",
"title": "Recently Saved Works"
},
{
"key": "recommended_works",
"display": "true",
"title": "Recommended Works for You"
},
{
"key": "live_auctions",
"display": "true",
"title": "At auction: Art in General: Benefit Auction 2016"
},
{
"key": "current_fairs", …
```

@dzucconi - home page modules (rails)

---

lib/helpers.js
lib/loaders/delta.js
lib/loaders/google_cse.js
lib/loaders/gravity.js
lib/loaders/positron.js
test/lib/helpers.js

I noticed this in practice on the `artwork_2` page: While although Objects aren't technically sorted, in practice when `qs.stringify` was run it would create keys in the order that one declared the options.
As part of that `artwork_2` query these two keys would get loaded:
```
related/sales?artwork%5B%5D=andy-warhol-electric-chair-18&active=true&size=1
related/sales?size=1&active=true&artwork%5B%5D=andy-warhol-electric-chair-18
``` 
Those now become:
```
related/sales?active=true&artwork%5B%5D=andy-warhol-electric-chair-18&size=1
```
Which of course is neither of those.
So once this gets deployed we should see the cache hit rate drop while these get rebuilt. But we should see reduced cache usage & marginally increased performance later on.

@craigspaeth: Deduplicate similar requests

---

schema/partners.js

Need to match latest gravity changes so we can support term search along with filtering.
https://github.com/artsy/gravity/pull/9965
This is needed in order to support https://trello.com/c/xrTp0Skr/422-galleries-institutions-partner-search-that-differentiates-between-galleries-and-institutions
Modified our `partners` GraphQL schema to match latest Gravity changes and include `term`
cc: @starsirius

@dzucconi => Term Search support for Partners

---

schema/partners.js

Re: https://github.com/artsy/force/issues/4744
We want to sort the partners by `relative_size` and it's added in [Gravity](https://github.com/artsy/gravity/pull/9970) now.

@dzucconi Support sorting partners by relative_size.

---

schema/partner.js

For places where we want to display the 'kind' of partner but the actual type is awkward.
We could also alias this as a new field, but I don't really see a downside to this approach.

@mzikherman: Make displaying partner types less awkward

---

schema/artwork/index.js

**NOT FOR MERGE YET**
Waiting on https://github.com/artsy/gravity/pull/9939 to be deployed, cache updated and migration ran, etc.
The next step once this is deployed is to switch some existing uses of `is_contactable` to this new one and carefully examine...

@dzucconi => Deprecate is_contactable, and introduce is_inquireable

---

lib/date.js
lib/loaders/total.js
schema/partner_show.js
test/lib/date.js
test/lib/loaders/total.js
test/schema/partner_show.js

This is for https://github.com/artsy/emission/issues/11

Missing shows data.

---

schema/artist/index.js

This just passes `page` on to the Gravity API call.

[Artist Artworks] Add pagination.

---

schema/artwork/context.js

Since we can't return inactive fairs as context, also exclude fair booths from showing up

@mzikherman: Exclude fair booths

---

schema/me/bidders.js
test/schema/me/bidders.js

Gravity has two endpoints for retrieving `me`'s sale registration status: `bidders` and `me/bidders` depending one if you specify a `sale_id` or not. This PR adds an optional `sale_id` argument to the `me { bidders }` query.
Paired with @orta on this one.

@broskoski: Adds sale_id to bidder query for server-side filtering

---

schema/causality_jwt.js
test/schema/causality_jwt.js

@sweir27: Allows jwts to be issued using a slug

---

schema/home/add_generic_genes.js
schema/home/context.js
schema/home/index.js
schema/home/logged_out_modules.js
schema/home/params.js
schema/home/results.js
schema/home/title.js

Regarding https://github.com/artsy/force/issues/4769 and https://github.com/artsy/force/issues/4705
This adds the ability for a logged out user to fetch generic, pre-determined gene rails. Will comment more inline.
Next up, iconic works rail.

@dzucconi - adds logged out modules and generic genes

---

schema/partner.js

Needed for backwards compatibility when coercing results into Backbone models.

@mzikherman => Add default_profile_public to Partner schema

---

schema/causality_jwt.js
test/schema/causality_jwt.js

Currently for logged in users, the clients need to have enough stored gravity data to know whether a user is registered to bid. The current implementation on both sides for logged in users to it make the request, see if it fails, then try again with the other one. 
This is a bit of a waste, considering metaphysics already knows this data, and is passing it onwards. It means extra time waiting for a second request to get any data on a client when logged in and not registered.
Instead now you will be downgraded from a BIDDER to an OBSERVER, and that is encoded into the response.

Convert BIDDERs to OBSERVERs automatically if they are not registered for a sale

---

schema/causality_jwt.js

This updates the JWT logic to split the path down it's 4 separate ways...
1. Any logged out users default to "observer" role
2. A logged in user specifying PARTICIPANT gets a "bidder" role if registered
3. A logged in user specifying PARTICIPANT gets a "observer" role if *not* registered
4. An admin specifying OPERATOR gets "operator" role or "unauthorized" if not admin

@sweir27 (cc @acjay): Update Causality JWT logic

---

schema/artist/index.js
schema/home/context.js
schema/home/fetch.js
schema/home/title.js

This is pretty ghetto.
Basically, the context object shouldn't be an `Artist`, but something custom, a struct of the artist and another object that represents the follow it is based on, or maybe we could get away with something as simple as a struct of `{href, follow_annotation}`. 
My JS-fu wasn't good enough to get that tho, so just went with this for now :(
```
{
"data": {
"home_page_module": {
"title": "Works by Jasper Johns",
"key": "related_artists",
"context": {
"href": "/artist/jasper-johns",
"id": "jasper-johns",
"follow_annotation": "Based on Andy Warhol"
}
}
}
}
```

@broskoski => Annotate related artist on homepage with followed artist

---

schema/artist/index.js
test/schema/artist/index.js

@alloy=>Added has_metadata flag and counts for related artists and articles

---

schema/artist/index.js

```json
{
"data": {
"artist": {
"has_metadata": true,
"bio": "British, 1928-2011, Sheffield, United Kingdom",
"blurb": null
}
}
}
```
Fixes `bio` problem in #301

@alloy=>Fixed has_metadata check

---

schema/bidder.js
schema/me/bidders.js
schema/sale/index.js
test/schema/me/bidders.js

We need to access `sale.registration_ends_at` and `bidder.qualified_for_bidding` from within prediction, so adding those fields here.
I also fixed what looks like a bug, more comments inline.

@craigspaeth => add some fields and fix me/bidders scoping

---

schema/artwork/index.js
schema/sale_artwork.js
test/schema/sale_artwork.js

This leverages https://github.com/artsy/gravity/pull/10091 to expose a `bid_increment` field from metaphysics. Which should make it easy to populate the max bid selects.
Down the line we might replace the Gravity call with a Causality call.

@sweir27: Add bid_increment to sale artwork schema

---

lib/apis/fetch.js
lib/cache.js
lib/loaders/http.js

Slightly more useful error handling as well for API errors (by including the failed URL):

@broskoski: Delete keys with requests that 404

---

lib/loaders/http.js

Should be in the request that gets fired off after the cache `get`

@dzucconi: Move to the correct catch

---

schema/causality_jwt.js
test/schema/causality_jwt.js

With the breaking causality changes, we have to send `bidderId` instead of `paddleNumber` in the jwt so they can be matched with the user's `bidderId` in subsequent requests.

@craigspaeth => send bidderId instead of paddle number

---

schema/causality_jwt.js

Solves https://github.com/artsy/metaphysics/issues/312
As Alan mentions in the comments we don't need to filter out bidders MP-side since we can just query for bidders based on the JWT's sale.

@sweir27: Scope fetching bidders by sale

---

schema/bid_increments.js
schema/index.js

Adds the global bid increment policy as something that can be queried at the root.

@ashfurrow: Add bid increments as root query

---

schema/sale_artwork.js
test/schema/sale_artwork.js

Adds an extra fetch for the related sale to get the increment_strategy instead of just using default.

@acjay: Finds increments based on sale's strategy

---

schema/me/bidder_positions.js

Right now the my active bids on the sale page is showing across-auctions. I forget when this regression was introduced, but before we were filtering on the client-side, when ideally we actually filter this down via MP + Gravity. So this allows that.

@sweir27: Query my active bids by sale_id

---

schema/sale/index.js

This exposes a sale's buyer's premium in MP...
In Gravity there's all this other data other than `schedule` that we don't use, but I wanted to check with you that I'm not overlooking something useful in here... e.g. Why would we ever need to know the `name` or `currency` aren't those always the same as the auction itself?
We need this data to render UI's like this that explain the buyer's premium policy...

@sweir27: Expose buyer's premium

---

schema/home/index.js
schema/index.js

Relay requires root fields to be singular, no lists.
I tried adding `deprecationReason` fields to the root `home_page_module` and `home_page_modules` fields, but for some reason these deprecation warnings did not show up when introspecting the schema, so I ended up not adding those. In addition it’s probably easier for force to just switch over and we can remove these fields. /cc @broskoski 
----
```graphql
{
home_page {
module(key: "live_auctions") {
title
},
modules(max_rails: 3) {
title
}
}
}
```
```json
{
"data": {
"home_page": {
"module": {
"title": "Current Auction: Heather James Fine Art: Benefit Auction 2016"
},
"modules": [
{
"title": "Works by Iconic Artists"
},
{
"title": "Current Auction: Heather James Fine Art: Benefit Auction 2016"
},
{
"title": "Current Fair: Art …
```

[Home] Move `module` and `modules` into `home_page` field.

---

schema/image/index.js
schema/object_identification.js

I can’t say I really understand why some image objects wouldn’t have an ID, but MP is complaining about it happening, so for now getting rid of that error.

[Image] May have a nil ID, so reflect in schema.

---

schema/artwork/index.js

Turns out we were interpreting this in different ways in different places. On the artwork page, `is_in_auction` is meant to ask if the artwork was ever part of an auction and on artwork thumbnails, `is_in_auction` is assumed to mean "is this artwork available to bid on?". This keeps `is_in_auction` the same and adds support for `is_biddable`.

@joeyAghion - Fixes active/live discrepancy for artworks in Auctions

---

Procfile.dev
schema/home/home_page_module.js
schema/home/home_page_modules.js
schema/object_identification.js
test/schema/object_identification.js

This generates a globally unique ID for each rail based on `key` and `params.id`. It _could_ also do this based on `params.gene_id` and `params.medium`, which means that `params.id` could be removed entirely, but that assumes you would use the `__id` key to identify rails in Force as well. Not impossible, just something to keep in mind.
```graphql
{
home_page {
module(key: "generic_gene", id: "abstract-art") {
__id
}
}
}
```
```json
{
"data": {
"home_page": {
"module": {
"__id": "SG9tZVBhZ2VNb2R1bGU6eyJrZXkiOiJnZW5lcmljX2dlbmUiLCJpZCI6ImFic3RyYWN0LWFydCJ9"
}
}
}
}
```
```graphql
{
node(__id: "SG9tZVBhZ2VNb2R1bGU6eyJrZXkiOiJnZW5lcmljX2dlbmUiLCJpZCI6ImFic3RyYWN0LWFydCJ9") {
__typename
... on HomePageModules {
key
title
params {
id
}
}
}
}
```
```json
{
"data": {
"node": {
"__typename": …
```

[Home] Add Relay Node support.

---

schema/image/index.js
schema/object_identification.js

This fixes https://github.com/artsy/emission/issues/205 (just need to update the schema there).
The problem was that the `Image` object for an `Article` is not actually its own object and its `id` was thus `null`. Because we encoded that `null` regardless, we ended up with the same `__id` value for each image and Relay would thus treat all those `Image` objects as if they were the same.
Now an `Image` no longer acts as if it has a `__id` and we also won’t encode `null` IDs any longer.

Don’t return the same Node ID for multiple objects.

---

schema/artwork/layer.js
schema/filter_artworks.js
schema/partner.js

@xtina-starr here are some metphysics changes for the artwork page's related artwork sections. adds a partner's artworks, you can use the `exclude` parmeter to exclude the id of the artwork whose page is currently being displayed. also adds size parameter to related artworks.
using the filter artworks endpoint with the partner_id param, instead of /partner/artworks because the latter doesn't support sorting, apparently

@xtina-starr artwork page

---

schema/aggregations/filter_artworks_aggregation.js
schema/filter_artworks.js

For use in: 
This will just be an aggregation, where we also receive the actual artists in order of max merch score.

@broskoski => Merchandisable artists aggregation results

---

schema/fair.js
schema/fairs.js

Once https://github.com/artsy/gravity/pull/10283/files is deployed and data migrated, we can start switching to the new fields!
Only update needed is to Force/MicroG for listings, the large banner is a #no-op and https://github.com/artsy/metaphysics/pull/382/files took care of the homepage.

@broskoski => Add fields to fair schema and fairs endpoint

---

schema/home/context.js
schema/home/fetch.js
schema/home/home_page_artwork_module.js
schema/home/home_page_artwork_modules.js
schema/home/params.js
schema/home/results.js
schema/home/title.js
test/schema/home/home_page_artwork_module.js
test/schema/home/home_page_artwork_modules.js

Sorry for the sloppy history, picking up something I've been tinkering with for a while.
Right now on the homepage, we fetch the last artist the user followed and get an related suggestion based on that. That works fine, but what would be better is if we fetched a different random artist / related pair every time. The tricky part here is that two requests have to match up:
1. On page load we get a response of all the modules that _should_ be displayed. The client should be able to render parts of these modules initially as placeholders (like the title).
2. Then on the client side we fetch each module again individually with all the results, depending on what keys and parameters are returned in the initial fetch. This means that the random artist / related pair needs to match up between …

@craigspaeth - Fetch random related artist

---

lib/loaders/total.js

Here's a complicated explanation, get ready...... 
1. https://github.com/artsy/metaphysics/blob/master/schema/sale/index.js#L136 has default arguments and they were being passed down to the `gravity.all` loader (which is a little unnecessary, but ok).
2. We recently changed the way `total` gets called (which passes options down here https://github.com/artsy/metaphysics/blob/master/lib/all.js#L10 , in this case `page` and `size` where in the options (because they were default values). 
3. Because our cache uses args + path as the cache key, `total` was overwriting the first response's cache (which was identical to the `all` loader requesting the first page).

@bhoggard - Omit page and size from options passed

---

schema/artwork/index.js
schema/home/fetch.js

Fixes https://github.com/artsy/emission/issues/276
See https://github.com/artsy/gravity/issues/10347.
This issue would in some cases cause no fairs to be returned from Gravity. (I guess JS object -> query params encoding has undefined order?)

[Home/Fair Artworks] Hotfix to work around Gravity bug.

---

schema/home/home_page_artist_module.js

When signed it in the `exclude_followed_artists` parameter is included.
For whatever reason `exclude_followed_artists` didn’t seem to work properly yet on staging (cache no invalidated) but it does on production, or maybe I was just doing something wrong. Anyways, keep that in mind when trying it out.

@mzikherman => [Home/Artist] Exclude followed artists from trending/popular.

---

schema/home/home_page_artwork_modules.js

This was happening to a partner on the new homepage where the related artist rail _should_ show but we couldn't find any related artist for the artists they followed. This covers that case and removes the related artist rail from the response.

@mzikherman - Cover case where related artist endpoint returns an empty array

---

schema/partner_show.js
test/schema/partner_show.js

Re: https://github.com/artsy/force/issues/124
We want to include the eligible artworks (published artworks) count of a show in the Sailthru meta tags. It's currently not in the schema but returned in the Gravity [json response](https://github.com/artsy/gravity/blob/3a4a342b738fd3fcffb96aec5c8d09b260241753/app/models/domain/partner_show.rb#L123). This adds it to the schema.
Is there anything I need to do besides the test?

@broskoski Add eligible_artworks_count to partner show schema.

---

schema/partner_show.js
test/schema/partner_show.js

This was returning an error, which Relay, being a ‘type safety’ pedantic lib, interprets as not being reliable data.
```json
{
"data": { … },
"errors": [
{
"message": "Cannot read property 'images' of undefined",
"locations": [
{
"line": 5,
"column": 7
}
]
}
]
}
```

[PartnerShow] Don’t return an error when there’s no cover image.

---

npm-shrinkwrap.json
package.json
server.js

This is required to go from a stack trace in a compiled file:
```
TypeError: Cannot read property 'id' of null
at resolve (index.js:102:44)
at resolveOrError (/app/node_modules/graphql/execution/execute.js:426:12)
```
To the real source:
```
TypeError: Cannot read property 'id' of null
at resolve (/Users/eloy/Code/Artsy/metaphysics/schema/artwork/index.js:173:61)
at resolveOrError (/Users/eloy/Code/Artsy/metaphysics/node_modules/graphql/execution/execute.js:426:12)
```

[logging] Symbolicate stack traces.

---

.env.test
lib/apis/galaxy.js
lib/loaders/galaxy.js
test/lib/apis/galaxy.js

I'm going to need to be able to query [Galaxy](https://github.com/artsy/galaxy-api) for non-Artsy partners. Some partner shows can include a `galaxy_partner_id`, which is a reference to the corresponding entry in Galaxy.
This just adds in the boilerplate, similar to the positron and gravity loaders.
Up next: I need to figure out how to make the `partner` node resolve to a potentially different type, a 'Galaxy partner', which I'm still struggling with doing the 'GraphQL way' (ie- how can a node resolve to one of two types?). That will actually use this, but in the meantime...

@alloy => Add an API loader for Galaxy to retrieve non-Artsy partners

---

schema/artist/index.js
schema/external_partner.js
schema/galaxy_partner.js
schema/index.js
schema/partner_show.js
schema/show.js
test/schema/show.js

This includes the Galaxy commits from https://github.com/artsy/metaphysics/pull/422
Idk if this is the right approach, but we can now get the partner name from a show like this (which works for Artsy or Galaxy partners):
However, this breaks the regular approach:
I don't mind updating Force (and other clients), but there might be lots of places that query partner attributes (from a show) in the original style. Is this the right approach? Or something more graceful?

@alloy => New Show schema, and includes ExternalPartner

---

schema/artist/index.js
schema/external_partner.js
schema/show.js
test/schema/show.js

This is a breaking change to the `exhibition_highlights` field in the `Artist` schema. I don't think we have a choice here (and I'd rather not duplicate the artist schema) as this field is the one I'd like to take advantage of the new `Show` schema.
I can get the updates ready in Force/MG, where the way you query `partner` attributes from `exhibition_highlights` will change to the `... on ExternalPartner` and `... on Partner` style. I'll update here when those PR's are ready. 
I think we can just make sure to merge/deploy the clients, I'll make sure to deploy Metaphysics (which is fast) as soon as the clients are deployed. I think that'll minimize downtime.
Big question- is this being used in iOS land?

@alloy => Switch to Show over PartnerShow for exhibition highlights of an artist #dontmerge

---

schema/show.js
test/schema/show.js

The last piece of the puzzle for 
(rendering the Partner-submitted Admin-moderated reference shows!) is the city name. In Gravity, a show can have two kinds of city fields.
[One](https://github.com/artsy/gravity/blob/c0114584039fd424021a7ca3f6c5c6fd49a50f37/app/models/domain/partner_show.rb#L38) is a rich `Location` object with other attributes.
[The other](https://github.com/artsy/gravity/blob/c0114584039fd424021a7ca3f6c5c6fd49a50f37/app/models/domain/partner_show.rb#L32) is a simple string field, however all UI's that feed into it are powered by Google Maps location search, so the data should be well structured.
I'm not crazy about this `best_city` name, what do you think?

@alloy => Add best_city to accomodate the ref show cities

---

lib/graphql-error-handler.js

The `fetch` function [assigns the `statusCode` field](https://github.com/artsy/metaphysics/blob/511fd8322b7277fc411655957f6e8143e4f2a7f5/lib/apis/fetch.js#L20-L22). If that field exists we now only report it in case of a 5xx error.

[logging] In case of an underlying network error, only report 5xx.

---

schema/show.js
test/schema/show.js

In order to classify shows as 'group', or 'solo', (or a fair booth), the `artists` node was examined. For reference shows, we associate artists directly to a show w/o artworks. Because this is pretty different than the usual association of artists only through artworks, I exposed that as `artists_without_artworks` in the show JSON.
This updates that definition. After the recent Metaphysics PR's, the grand update to the Force artwork page was:
https://github.com/artsy/force/pull/251 (updates artist and artwork page for new partner type)
https://github.com/artsy/force/pull/254 (updates artwork page for new show city)

@alloy => Update kind of show to support reference shows, where artists lack artworks

---

lib/graphql-error-handler.js

There's still something up with the way we pass around errors.
Logging out the `error` object at this state shows that it's been already transformed from [here](https://github.com/artsy/metaphysics/blob/3df9403b57ac9e3c5638123e2117c64a23220a71/lib/apis/fetch.js#L20-L22).

@mzikherman => Dont send Artwork Not Found to NewRelic

---

schema/home/context.js

Previously, modules without `context`'s could resolve to `false` without problems. The new Graphql version is a bit stricter and metaphysics started throwing this error any time a `context`-less module was fetched:
`1. Abstract type HomePageModuleContext must resolve to an Object type at runtime for field HomePageArtworkModule.context with value "false", received "undefined".`
To remedy this, we updated the `Context` field to return `null` instead of `false`, since `false` is a boolean and a `HomePageModuleContext` must resolve to either one of [these](https://github.com/artsy/metaphysics/blob/master/schema/home/context.js#L105) or nothing.

Bug fix for HomePageModuleContext

---

schema/me/lot_standing.js
test/schema/me/lot_standing.js

@sweir27 @acjay - actually hold on unless you think this is worthwhile, see below
linked to https://github.com/artsy/auctions/issues/140
Adding this after talking with sarah- we needed a check for the reserve message ticket to see whether the person was winning on human bids alone. `is_highest_bidder` included reserve, so i added `is_leading_bidder`. 
maybe hold off on this? I looks like the same information is available as the presence on the active_bid object. i'll return

add is_leading_bidder property to LotStanding type

---

lib/helpers.js
schema/filter_artworks.js
schema/gene.js
schema/index.js
test/schema/gene/gene.js

Currently to pull in artworks for a Gene, with refine options, you will need to do a query like:
```graphql
{
gene(id:"500-1000-ce") {
id
}
filter_artworks(gene_id: "500-1000-ce", aggregations:[MEDIUM, PRICE_RANGE, TOTAL], sort:"prices", for_sale:false, page:1){
hits {
title
}
}
}
```
Which is not ideal, as that's not a graph 👯 
This PR allows you to do this:
```graphql
{
gene(id:"500-1000-ce") {
id
filter_artworks(aggregations:[MEDIUM, PRICE_RANGE, TOTAL], sort:"prices", for_sale:false, page:1){
hits {
title
}
}
}
}
```
Which is a graph 🎉 
---
This PR also takes into account how you would normally paginate, e.g.
```graphql
{
gene(id:"500-1000-ce") {
filter_artworks(aggregations:[MEDIUM, PRICE_RANGE, TOTAL], sort:"prices", for_sale:false, page:2){
hits {
title
}
}
}
}
```
and won't make a …

Adds artworks to the gene via the filter_artworks API

---

schema/filter_artworks.js
test/schema/filter_artworks.js

With a relay fragment like:
```js
export default Relay.createContainer(Gene, {
initialVariables: {
medium: null,
price_range: '*-*'
},
fragments: {
gene: () => Relay.QL`
fragment on Gene {
_id
id
${Header.getFragment('gene')}
${About.getFragment('gene')}
filtered_artworks(medium: $medium, price_range:$price_range, aggregations:[MEDIUM, PRICE_RANGE, TOTAL], page:1){
total
aggregations {
slice
counts {
id
name
}
}
}
}
`,
}
```
There is no way to make the medium _not_ get sent along to metaphysics, without a bunch of hacky hack hacks. So we've opted to allow something like the price-range of all - to a known (and documented in the schema) constant of "*".

Support passing a medium through as a '*' have it not sent to gravity

---

schema/artist/index.js
test/schema/artist/index.js

Now that bios come from CMS to the Partner Moderation Admin app, and all the platform work for featuring a bio is done, we want the front-end to display the featured bio, as well as an attribution line.
There was already this field set up to be able to provide a fallback if Artsy hasn't provided a bio. However, the referenced code (in Force) only ever displays Artsy bios, so it should be perfectly safe to modify.
With this update, I can switch Force/Microgravity to support displaying a featured bio if one exists, plus the 'credit' line.

@alloy => Fall back to featured bio in biography_blurb field on Artist

---

schema/home/context.js
schema/home/home_page_artwork_modules.js
schema/home/title.js

We were still requesting the `featuredGene` for the `context`
of each followed gene.
I have a unfinished/unpolished test locally to verify that we don’t make unneeded requests, but I’ll finish and PR that after we’ve done the release.

[Home] Don’t make unneeded single followed gene requests.

---

schema/artist/index.js
test/schema/artist/index.js

So, basically I think we need to have two fields in the schema. One has to be the Artsy blurb, and one should be the featured partner blurb. To do nuanced fallbacks on clients...it's really messy with just one field. Also because in some cases you want to switch behavior on the client based on data that isn't known at the time of the query (such as the partner).
Since one of the fields is exactly that and was deprecated, I just un-deprecated it (and added a spec). Additionally, the other field was set up to do a fallback if there wasn't an Artsy bio, so I just added a param to essentially always return the fallback. In that way, we accomplish our goal of two fields: one for the Artsy blurb and one for the partner, while the latter retains its current behavior: providing an Artsy blurb or …

@alloy => Un-deprecate blurb on Artist

---

lib/loaders/gravity.js
schema/filter_artworks.js
test/schema/filter_artworks.js
test/schema/gene/gene.js

You can now do `gravity.with(accessToken)(...)` anytime you need to pass that along.

@alloy => Cleanup access token handling

---

schema/show.js

..which sometimes returns documents that really don't exist (that endpoint is cached purely based on time).

@mzikherman => Allow these to fail silently on account of related shows endpoint

---

schema/sale_artwork.js
test/schema/sale_artwork.js

Metaphysics orchestrates figuring out the bucket of values that a bidder can bid on. Right now, we use the `minimum_next_bid_amount_cents` and generate 100 increments above that value as possible bid values.
This can get hairy if the starting bids are very high because:
- Gravity only allows you to bid up to its `BIDDER_POSITION_MAX_BID_AMOUNT_CENTS_LIMIT` anyways
- At a certain point, the numbers become > 32-bit integers and metaphysics explodes.
To solve this, we add a `BIDDER_POSITION_MAX_BID_AMOUNT_CENTS_LIMIT` to metaphysics and don't give you increments above that amount.
Note that when we're dealing with actual bids that are above 32-bit integers we'll have to update this and also throw some kind of lavish party.

@mzikherman => dont include bucket increments above set limit

---

schema/artist/statuses.js
test/schema/artist/statuses.js

Now that counts are denormalized onto the artist model (and deployed to prod. with data migrated) we can use them (instead of this expensive ES call) to determine whether to show certain tabs on the artist page.
cc @briansw this should make the 'CV' tab start to show up when the count of total shows for an artist (including ref shows) goes above 15.

@alloy => Use new counts to determine artist tab statuses for shows and CV

---

schema/artist/index.js
test/schema/artist/index.js

Minor bug- even when we prefer to return the featured partner bio, we should always return the Artsy one if there is no featured bio.

@alloy => If there is no featured bio, return the Artsy one

---

.vscode/settings.json
schema/artist/index.js
schema/partner_show.js

Depends on https://github.com/artsy/gravity/pull/10566
Fixes #473 & https://github.com/artsy/eigen/issues/1873

[Artist] Only include displayable shows.

---

schema/artist/index.js

I had removed this field when I refactored the deprecated `partner_shows` and `shows` fields https://github.com/artsy/metaphysics/commit/2363552ecc02328b335548221d9fa47ea8b9d9d1. This is now causing a failure in Force.

[Artist] Add `is_reference` back to `shows`.

---

schema/sale/index.js
test/schema/sale/index.js

Previously, metaphysics would through a `TypeError: Cannot read property 'schedule' of undefined` if a sale had no buyers premium. This updates the logic to check for both the presence of `buyers_premium` and `buyers_premium.schedule` when generating the response for a `sale`.
This will allow us to run live auction integration sales when the sale has no buyers premium.

@alloy => allow sale to have null buyers premium

---

schema/fields/money.js

High estimates for auctions are running above 25M HKD, which is larger than 32 bits and thus borking GraphQL.

@craigspaeth => use float so we get 64 bits

---

schema/artwork/index.js
test/schema/artwork/index.js

Since this is just for a Force test (for now), decided to go this route rather than something more 'official' in Gravity.
If the test succeeds and we want to roll it out to other clients, it probably makes sense to then offer full-fledged first class support in Gravity, which would probably include other changes besides these booleans (better pricing information overall, etc.)
I believe the logic for this field is correct: an artwork should be inquireable and have an exact price. An artwork being sold (and having an exact price), would not be inquireable, and artworks with hidden prices would not have the exact price, so this would be `false` for those cases.

@alloy => Add is_purchasable to artworks to support inquireable artworks w/ exact pricing

---

schema/artwork/index.js

The sales API doesn't filter based on `auction_state`, so this was returning the auction even if it had closed (related issue: https://github.com/artsy/force/issues/450)
This fixes `is_biddable` to instead query the API based on the `live` param, which is handled: https://github.com/artsy/gravity/blob/master/app/api/v1/sales_endpoint.rb#L23. As we set sales to have `live: true` when open and `live: false` when closed, this should achieve the same thing.

@mzikherman => fix how we check for auction state in is_biddable

---

schema/sale/index.js
schema/sale_artwork.js
test/schema/sale/index.js

This PR deprecates the custom `auction_state` implementation, to be more consistent and reduce some unneeded business logic. The API doesn't return `'live'` as a possible state, but from looking at microgravity, force, and eigen, it doesn't look like this is ever used directly (clients either calculate the live status directly based on `live_start_at`, or use `is_live_open`.
Also, to circle back to https://github.com/artsy/metaphysics/pull/131, it seems that the issues we were seeing in staging were due to the fact that staging's cache does not get rewritten when data is copied from production. Doing a quick test in production showed that all of the auction states match what is returned from the API for all published auctions.
If we do end up seeing errors, we should update or remove …

@craigspaeth => deprecate custom auction state

---

schema/artwork/index.js
test/schema/artwork/index.js

In order to update the [price format](https://github.com/artsy/collector-experience/issues/27 ), force needs to determine if there is a price value and whether or not it's a range. This adds those properties for force to consume.

Adds 'is_price_range' and 'price' property

---

schema/artist/index.js

I ran the migration in https://github.com/artsy/gravity/pull/10636 on staging, and then checked out some artist pages locally with this new code- looks good!

@joeyAghion => [Performance] Replace 9 calls for exhibition highlights with 1 call!

---

schema/artwork/index.js
test/schema/artwork/index.js

Inquireable works with a blank price were technically 'passing the regex' and so were considered to have an exact price (since it wasn't a range).
Since a blank price is valid (partner chose to hide the price or not input it), let's check for the existence of a price as well.

@1aurabrown => is_purchasable to return false for blank prices

---

schema/artist/index.js
schema/home/fetch.js
schema/sale/sorts.js

This is related to all of the changes I've been PRing to you...
Live sales may not have an `end_at`, so we should be grabbing sales sorted by `timely_at` for the featured auction on the homepage and the widgets on the artist page.

@broskoski => Sort /sales and /related/sales by timely_at

---

schema/artist/index.js
test/schema/artist/index.js

We were being defensive about missing nationalities, birthdays and deathdays- except it would still crash if _just_ the deathday was provided :(
Fixes errors like: https://rpm.newrelic.com/accounts/1147389/applications/10782493/traced_errors/a83a7f90-c78b-11e6-972d-f8bc124256a0_0_7913

@orta => Dont crash when just deathday is provided

---

package.json
yarn.lock

See https://github.com/apollostack/optics-agent-js/pull/76
Going to self-merge and deploy this.
/cc @craigspaeth

Use fork of Apollo Optics that fixes a unhandled promise rejection bug.

---

schema/artwork/context.js

Going thru Optics, there's a lot of time spent here.
Since `sale_ids` are denormalized, and the sales endpoint can accept the list, we switch to:
- short-circuit if there are no sales
- use preferred sales endpoint over related/sales

@orta => Short circuit an expensive sales lookup for artwork context

---

schema/home/home_page_artwork_modules.js
test/schema/home/home_page_artwork_modules.js

Looks like lodash's `sampleSize` can return less than the amount you specify, hence a check to ensure that the secondary pair is present.

@alloy - Ensure there is a secondary artist pair for followed artist rail

---

schema/sale_artwork.js

I need to access sale artworks' `estimate_cents` field [in causality](https://github.com/artsy/causality/pull/346) but it's not exposed through metaphysics yet; this PR adds it. Ideally this would have been specified in the schema as `estimate` but that field name is already taken as a formatted string value. At least eigen uses this, so renaming it isn't really an option, so I use `estimate_cents`, the same field name as the `SaleArtwork` model in gravity.

Exposes gravity's raw estimate_cents field

---

schema/input_fields/event_status.js
schema/input_fields/format.js
schema/sorts/artist_sorts.js
schema/sorts/artwork_sorts.js
schema/sorts/partner_show_sorts.js

fixes https://github.com/artsy/metaphysics/issues/83
The thing is, you have no way of knowing that these enum values are deprecated unless you intropsect on them somehow. and ideally we'd update all clients, even though the deprecated enum values continue to function.
The graphql ui doesn't seem to alert you, although after looking at their code base it seems like they attempted to add some messaging in the Docs panel if a deprecated enum or field is queried. However, it seems not to be working correctly, or else it doesn't affect enums used as an _argument_. I'm going to make an issue on their repo.

@mzikherman: deprecate lowercase enums

---

schema/filter_artworks.js

After https://github.com/artsy/gravity/pull/10728, we are now able to filter artworks by `sale_id` in ES. We'll need this for the new collect-like interface on the `/auction` page!

@broskoski => add sale_id to filter results

---

package.json
yarn.lock

The version we were using had an issue where too many timeout handlers
were being defined: https://github.com/alevy/memjs/pull/86.
This lead to many warnings like the following in the production logs:
(node:9852) Warning: Possible EventEmitter memory leak detected.
11 timeout listeners added. Use emitter.setMaxListeners() to
increase limit
The logs also show many `ECONNRESET` and similar errors, which may be
related to this: https://github.com/alevy/memjs/issues/89. According to
that thread, however, it seems like version 0.10.0 could also be
suffering from issues, although others report it working for them.

[package] Update memjs to 0.10.0.

---

schema/aggregations/filter_artworks_aggregation.js
schema/filter_artworks.js

Follow-up to: https://github.com/artsy/gravity/pull/10732
Looks like we don't define the acceptable sort params anywhere, but I tested `lot_number` and `searchable_estimate` sorts locally and they look 👌 .

@mzikherman => adds a few additional params for the auction2 page

---

schema/home/home_page_hero_units.js
test/schema/home/home_page_hero_units.js

Related: https://github.com/artsy/force/issues/744
Talked with Robert about a request to make the order of homepage banners random to free up our GP + other members from the overhead of managing this (e.g. it becomes complicated when balancing events with things like pricing for promoted content).
I figured `shuffle`ing at the MP level would allow us to easily surface this in Eigen and web simultaneously. This simply adds that shuffling plus other fields necessary to render on web from MP. I'll comment some minor thoughts inline.

@alloy cc @broskoski: Expand on hero unit schema

---

schema/partner_show.js

We need `created_at` in Force's show page to use it for `sailthru.date` metadata field.
Well... add it :)

Add created_at to partner_show schema

---

schema/index.js
schema/object_identification.js
schema/viewer.js

While experimenting with Relay yesterday I stumbled upon a few hard constraints around supporting root queries with multiple parameters, as well as lists. After talking with @alloy about [this issue](https://github.com/facebook/relay/issues/112) we determined that adding a wildcard "Viewer" type is an OK workaround, at least until Relay 2 is released. 
**Explanation:**
In Relay, this query doesn't work for two reasons; a) it contains two arguments, and b) it returns a list:
```
query {
sales(is_auction: true, sort: CREATED_AT_ASC) {
...
}
}
```
Following https://github.com/facebook/relay/issues/112, if the query is wrapped in a simple "view" container, you can get around this limitation:
```
query {
viewer {
sales(is_auction: true, sort: CREATED_AT_ASC) {
...
}
} 
}
```

Add Viewer Type

---

schema/artwork/index.js

Artworks can have `sale_ids` that point to unpublished sales. This PR updates the artwork schema to fail silently when this is the case (for `sale` and `sale_artwork`).

@mzikherman => catch unpublished sales without erroring

---

schema/artwork/index.js
test/schema/artwork/index.js

We were previously using a definition for determining purchasable eligibility that was: `Is the artwork inquireable, w/ an exact price?` (ignoring edition sets).
Now, we've modified the artwork inquireable state to include a larger set of 'unavailable' works. Since the pricing information is more canonical and independent of business logic, it's perfectly possible to have a not-for-sale/sold/on-hold work w/ an exact price (and which is now inquireable).
We'd like to exclude that set of works from being eligible for the purchase test, so we adjust the definition to now require the work be for sale.

@broskoski => Only include for sale artworks for purchasable test

---

schema/artwork/index.js
test/schema/artwork/index.js

cc @xtina-starr 
As discussed, this supports the new sale message texts across Force/Micro-g/Eigen, for both the artwork detail and list views.
Those can be specified with `view: LIST` and `view: DETAIL`. Calls without any `view` arg just pass through the original sale message from gravity (unformatted).
So, we can just start rendering these simply in clients with no other conditionals, and can be easily updated in the future in just one place.

@broskoski => Support differing sale message for clients detail and list views

---

schema/artwork/index.js
schema/partner.js
test/schema/artwork/index.js

Adds a `contact_message` field on the `Artwork` schema to handle various inquiry prompts based on availability.
Deprecated the one on `Partner` since that can't handle a per-artwork one.
I'll update Force to use this new field when possible, and then we can _probably_ remove the `Partner` one. Microgravity proxies Force, and I think Eigen doesn't use it at all.

@broskoski => Contact message

---

schema/artwork/index.js
test/schema/artwork/index.js

Oops forgot this, we want to blank the text for 'not for sale' works, and include the standard one for 'on hold'.
So:
sold: custom text
on hold/for sale: custom text (diff from sold)
not for sale: no text

@broskoski => Custom text for on hold works as well

---

schema/artists.js

After this PR https://github.com/artsy/gravity/pull/10794, the `/artists` endpoint can be filtered further by `sale_id`. Enabling this here so we can use it on the auction2 page!

@broskoski => adds additional fields to the artists endpoint

---

package.json
schema/artist/artwork_filters.js
schema/artist/index.js
yarn.lock

Closes #543 
This implements an `_artworks` (open to alternate name suggestions) field to the `Artist` schema.
`relay-cursor-paging` automatically handles the conversion from `after`, `first`, etc to params that gravity can understand (`size`, `offset`, etc)
TODO:
- Handle `sort` and `filter` args

@alloy - Adds _artworks field as Relay connection interface

---

schema/me/index.js
schema/me/notifications.js
test/schema/me/notifications.js

Queried like:
Gravity has been deployed but it'll take a few days for enough data to start being saved to notifications for this to be returning data, so by next week it should be good to go.
Up next: I'm going to look into how to make this possible for Relay. For now this is just queryable via the usual means.

@sarahscott => Add notifications schema

---

schema/me/index.js
schema/me/notifications.js
test/schema/me/notifications.js

cc @sarahscott 
I suspect that when you actually go to use this you may find an issue that this endpoint/connection only returns unread feed items.
I think what you want is to be able to return (and thus page thru) all of your feed items (we keep 30 days worth around before evicting them), and be able to know which ones are read/unread.
Currently, you just get the unread ones, and so their status is UNREAD for all of them.
Is it correct that you need that modification (in order to page thru your whole feed)? If so, I'll modify Gravity (and subsequently Metaphysics) with that argument.

@1aurabrown => Make notifications a Relay connection interface

---

lib/loaders/authenticated_http.js
lib/loaders/gravity.js
schema/me/artwork_inquiries.js
schema/me/artwork_inquiry_requests.js
schema/me/index.js
test/schema/me/artwork_inquiries.js

I am including `user_reported_outcome`, `status` and `statuses`, and the client can do whatever it wants with them to determine how to treat artworks in the grid view of the collector loyalty page.

@alloy add artwork inquiry requets field on me

---

schema/filter_artworks.js

Mostly PR-ing this as-is for discussion ( cc @alloy )
The one issue here is that we need the `total` count for results to make relay happy. However in the case of `filter_artworks`, this won't be present unless the query contains the `total` aggregation.

@mzikherman - Add artworks_connection to filter_artworks

---

schema/index.js
schema/viewer.js

As discussed offline, `filter_artworks` is one of those weirdly shaped schema's that is going to need a `viewer` type to work properly....and so adding your `viewer` type back!

@damassi - Adds viewer type back to metaphysics 

---

schema/sale/index.js

This PR adds a new `total_sale_artworks` field to the `Sale` type, in support for an [Artwork lot page update](https://github.com/artsy/auctions/issues/317):

Add `total_sale_artworks` field to Sale

---

lib/auth/middleware.js
test/lib/auth/middleware.js

cc @joeyAghion 
Kind of a weird one, it seems like the combination of POSTs + auth on Metaphysics was breaking Firefox client-side metaphysics requests.
It seems like the OPTIONS pre-flight request had some custom list of stuff in the `Accept` header, and not what was specified for the POST itself:
Specified headers for the POST: https://github.com/artsy/force/blob/72cb7b5096b66d1b216d24dac998610886f2e3a5/lib/metaphysics.coffee#L11
So, the auth middleware was treating the preflight requests from Firefox as though they were coming from the GraphiQL browser, and trying to auth those requests. That check is here: https://github.com/artsy/metaphysics/blob/626e6191b6075bc59f2fef78f40f543ddfbe4146/lib/auth/middleware.js#L9-L11
This can be repro'ed locally, this seems to fix it.

@broskoski => Dont auth on OPTIONS requests

---

schema/aggregations/aggregation_count.js
schema/aggregations/filter_sale_artworks_aggregation.js
schema/filter_sale_artworks.js
schema/index.js
test/schema/filter_sale_artworks.js

This PR adds a `filter_sale_artworks` endpoint, which is mostly modeled after the `filter_artworks`. We'll use this on the `/auction2` page instead of the `filter_artworks` endpoint!

@mzikherman => filter sale artworks endpoint

---

schema/me/notifications.js
test/schema/me/notifications.js

I think I lost the OG branch that produced that screenshot in my last pr and hastily re-wrote the line with `count` instead of `length`... oops. This definitely DEFINITELY uses `length` and adds the url the notifications spec ✅ .

@mzikherman => [Notifications] fix for image url bug

---

lib/loaders/per_type.js
schema/artwork/context.js
schema/artwork/index.js
test/schema/artwork/index.js
test/schema/image/index.js
test/schema/object_identification.js

This updates a bunch of artwork ones.
Still to do: we have some that are nested API routes where the route is built up out of more than just the `id` (https://github.com/artsy/metaphysics/blob/af58764d25fec83433e4535286f0693f8b1e0f3e/schema/artwork/index.js#L289)
+ tests

[DataLoader] Switch to new typed loaders for artwork schema

---

lib/loaders/per_type.js
schema/artwork/index.js

In my aggressive schema/loader updates, I switched this away from fetching each artist individually (but in parallel), to just one fetch (via `ids`).
Only problem is that just returns _short_ JSON, yet we need _public_ JSON (which we were of course getting by fetching each individually).

@joeyAghion => Make sure we fetch each artist individually for an artwork

---

schema/aggregations/filter_artworks_aggregation.js
schema/filter_artworks.js

Related to your work here: https://github.com/artsy/gravity/pull/10886
(also a direct revert of https://github.com/artsy/metaphysics/pull/527, haha :sob:)
This PR removes the `estimate_range` parameter and `ARTIST` aggregation options from the `filter_artworks` endpoint here, as they are no longer supported from our API.

@joeyAghion => revert options for filter artworks endpoint

---

schema/sale/index.js

Verified that the `symbol` field is returning the the sale json from gravity.

@mzikherman => add symbol to sale

---

.env.test
lib/apis/fetch.js
lib/apis/gravity.js
lib/apis/impulse.js
lib/loaders/authenticated_http.js
lib/loaders/gravity.js
lib/loaders/impulse.js
lib/loaders/per_type.js
schema/me/conversations.js
schema/me/index.js
test/lib/loaders/gravity.js
test/schema/me/conversations.js

This isn't really a requirement (yet), but I figured it sort of made sense before the mutation. Basically, this adds the `Impulse` stuff and lets a user start to fetch their own conversations.
The mutation will wind up returning a Conversation type so figured this makes sense first. Also, even though we are just fetching inquiries, if we ever want to fetch conversations we'll have thi.
Additionally, I added a pattern of _first_ getting your credentials from Gravity for the request. This is what we'll use in the mutation.
Still to do: some tests!

@alloy => Add an Impulse loader and fetch user conversations

---

lib/apis/impulse.js
lib/loaders/gravity.js
schema/index.js
schema/me/conversations.js
schema/me/update_conversation.js
test/helper.js
test/schema/me/conversations.js
test/schema/me/update_conversation.js

Adds a mutation in order to set buyer outcome for a conversation.
Still adding specs.

@alloy => Add an updateConversation mutation for buyer_outcome updates

---

schema/sale/index.js

Working on implementing the "Related Sale" component on the new auction page, and realized that we weren't returning the `associated_sale` from metaphysics.
This PR adds that. Unfortunately, since the `associated_sale` returns `reference_properties: :short` from gravity, we need to make an extra request so we can get all of the params we need (like `start_at`, `end_at`, etc.).

@mzikherman => add associated sale to sale index schema

---

schema/articles.js

We want to use metaphysics to populate the "related articles" on the new auction page. Need to allow this param!

@kanaabe => filter auctions by auction id

---

schema/me/collector_profile.js
schema/me/index.js
test/schema/me/collector_profile.js

We'll be storing some information on `CollectorProfile`, namely, when the user has applied for the loyalty program.
So we need a way to retrieve it (and can redirect to the appropriate page in the loyalty app on a subsequent visit).
We'll also need a way to mark that they applied (when they hit the 'Submit' button), which we can do with a mutation (forthcoming PR).

@xtina-starr => Be able to retrieve a users collector profile

---

schema/index.js
schema/me/update_collector_profile.js
test/schema/me/update_collector_profile.js

Builds upon https://github.com/artsy/metaphysics/pull/586
This lets you set the `loyalty_applicant` setting (and I threw in the `professional_buyer` as an example).

@joeyAghion => Mutate collector profile

---

schema/article.js
test/schema/article.js

Eventual goal is to render this widget in force (the `/article-figure` mixin) using data from metaphysics. I think this should do it!

@kanaabe => adds a few more fields to the article schema

---

schema/me/update_collector_profile.js
test/schema/me/update_collector_profile.js

This allows the mutation to not only mark their loyalty applicant status, but also passes thru their `self_reported_purchases`

@l2succes => Save self_reported_purchaes as well as loyalty applicant status

---

schema/me/conversations.js
schema/me/update_conversation.js
test/schema/me/update_conversation.js

went with `BLANK` for the 'unsetting' mode
(We typically use enums in GraphQL for this kind of field/update).

@ashkan18 => Use enums to update buyer outcome

---

schema/me/collector_profile.js
schema/me/update_collector_profile.js
test/schema/me/update_collector_profile.js

So I goofed and didn't realize there was a precise Relay spec for mutations.
I just added sort of arbitrary mutations for conversations and collector profiles, expecting to be able to use them. But after having some difficulty with Relay yesterday I realized I didn't have the proper single `input` parameter format (and potentially other things).
Hoping this is closer/matches the Relay spec.

@cab => Bring collector profile mutation up to Relay spec

---

schema/me/update_conversation.js
test/schema/me/update_conversation.js

We're adjusting our mutation to instead take an array of id's, and set the buyer outcome on those.
This means that we now return an array of conversations, rather than just a single conversation.
~~I've tried various combinations of that in `outputFields`, all to no avail.~~
Since the Relay spec requires an object to be returned, we return a single `conversations` object which is a list of all the modified conversations.

@alloy => Bulk update conversations w/ buyer outcome

---

schema/sale/index.js

It's a bit weird, but eigen needs the ID field for parsing our model objects from JSON. Made this change in the browser editor because metaphysics isn't set up locally on this machine, 🤞 for CI.

Adds ID fields to Buyers Premium

---

schema/fair.js
schema/profile.js
test/schema/fair.js
test/schema/profile.js

Related to https://github.com/artsy/collector-experience/issues/132 where year-round links on the `/fairs` page are 404ing. This is because the [check in force](https://github.com/artsy/force/blob/master/desktop/apps/fairs/templates/fair_upcoming.jade#L2-L3) that creates the link needs an additional check to determine if the fair organizer profile is published. This PR adds a `has_published_organizer_profile` flag to the fair object.

@alloy: Check to if fair organizer profile is published

---

schema/me/save_artwork.js
test/schema/me/save_artwork.js

Just like the title says, returns the artwork instead of the weird thing gravity returns on saving an artwork.

@mzikherman - Actually return artwork on save mutation

---

schema/me/save_artwork.js
test/schema/me/save_artwork.js

Turns out I was returning the fields for the artwork, when relay expects the item to exist in a nested field. The documentation for this is pretty poor, which is part of the reason for the trial and error style.

@mzikherman - Update mutation

---

schema/artwork/index.js
test/schema/artwork/index.js

This PR updates the logic for `is_buy_nowable` (which was wrong for various reasons explained below). 
The updated logic is that an artwork is `is_buy_nowable` if: it is in an auction that is `live` (meaning "open"), and if the artwork is `acquireable`.

@joeyAghion => Fixes is_buy_nowable logic

---

schema/home/home_page_artwork_modules.js
test/schema/home/home_page_artwork_modules.js

See [this Slack thread](https://artsy.slack.com/archives/C02CAB1KW/p1493786263193179) for details. Basically Eigen's homepage is stuck because MP choked on an empty array returned from /api/v1/user/:id/suggested/similar/artists
This fixes that, but maybe I'm not seeing the forest from the trees and this should be fixed further down in Gravity or up in Emission.

@alloy: Skip related artist rail if Gravity returns an empty array for related artists

---

schema/artist/index.js
schema/me/follow_artists.js
schema/me/followed_artists.js
schema/me/index.js
test/fixtures/gravity/follow_artists.json
test/schema/me/__snapshots__/followed_artists.js.snap
test/schema/me/followed_artists.js

Surprisingly, the data wasn't actually an artist (screenshot below), but a FollowArtist, so I'm not _really_ sure on the naming. My options were:
* `followed_artists_connection`
* `follow_artist_connection`
I felt that the former had a better feel if I was reading the query.
* WIP cause tests

[Consignments] Adds support for a saved artists connection

---

schema/artist/index.js
schema/gene.js
test/schema/gene/gene.js

`mode` corresponds to the type of Gene page we should default to, `artists_connection` lets us fetch gene artists via relay.

@mzikherman - Add mode and artists connection to Gene schema

---

.vscode/settings.json

Removes `build` from the sidebar.

Update the VS Code settings

---

schema/sale/index.js
test/schema/sale/index.js

This PR adds `is_registration_closed` to the `Sale` schema. (Following up to logic stored in https://github.com/artsy/force/pull/1469.)

[Auctions] Add is_registration_closed to Sale schema

---

schema/index.js
schema/item.js
schema/ordered_set.js
schema/ordered_sets.js
test/schema/ordered_set.js
test/schema/ordered_sets.js

Pretty small actual change here-- just adds an `ordered_set` interface that accepts an `id`, and the ability to return `Artwork`-type ordered sets. This will be used to power the `RECENTLY_SOLD` section of the consignments landing page.

@broskoski => adds ordered set interface + artwork item type

---

schema/me/conversations.js

Closes: #647 
Turns out the property was already being returned by Impulse and the list is already being sorted by last_message_at desc. It just had to be exposed 😅

[Messaging] adds last_message_at field

---

lib/loaders/per_type.js
schema/gene_families.js
schema/gene_family.js
schema/index.js
test/schema/gene/gene_families.js

As part of the new [Categories page](https://www.artsy.net/categories), we'd like to fetch gene families from the new endpoint. This PR adds a new schema to that end. 
As this is my first non-trivial PR for Metaphysics/GraphQL, there may be some learning opportunities here. So please point out ways in which this  PR could be improved if you see them. 
CC @oxaudo @anandaroop

Add schema for gene families endpoint

---

lib/loaders/followed_profile.js
schema/profile.js
test/lib/loaders/followed_profile.js

This adds the `is_followed` attribute to profiles in preparation for adding follow buttons to the fair booth component (i.e. https://www.artsy.net/art-basel-2017/browse/booths ).

@alloy - Adds is_followed to profile schema

---

schema/index.js

These conventional ones are alas hardcoded in Relay. Rather than trying
ot make Relay adapt to different schemas than FB’s, I chose to just
rename instead. Nobody is really using the names of these types anyways.

[schema] Rename root types to conventional ones.

---

schema/me/conversation/message.js
test/schema/me/conversation/index.js

We currently show Invoice messages `raw_text` which is not readable and useful, I can imagine we may want to detect these invoice messages and show them differently. 
Add a new `is_invoice` attribute to `MessageType` which basically looks for `metadata` of Radiation's message and checks if there is `lewitt_invoice_id` present or not, having `lewitt_invoice_id` in `metadata` means it was an invoice related message.

Add is_invoice to message response

---

schema/me/conversation/message.js
test/schema/me/conversation/index.js

On https://github.com/artsy/metaphysics/pull/686 we added `is_invoice` to messages response, using destructing to check if `metadata` has `lewitt_invoice_id` caused returning `null` when messages don't have `lewitt_invoice_id`, we want to return `false` for `is_invoice` for these cases,
First check if we don't have metadata return `false` and if we do then check for `isExisty`.

Fix null `is_invoice` issue

---

schema/artwork/index.js
test/schema/artwork/index.js

The `is_in_auction` field of an `Artwork` wasn't excluding closed sales. As [discussed in Slack](https://artsy.slack.com/archives/C02BAQ5K7/p1499704577290637) I want to make sure this won't inadvertently break anything else, but I feel like changing `is_in_auction` to behave more like an `is_in_open_auction` makes a lot of sense.
There are some inadvertent changes ESLint made – I kept them in but can remove them if they're not appropriate. The relevant line of the Artwork file is 343.

Filters closed sales from is_in_auction field.

---

schema/me/conversation/send_message_mutation.js
schema/me/conversation/update_mutation.js
schema/me/conversations.js

In https://github.com/artsy/impulse/pull/282 we added `from_id` to `Message` model and we can now pass optional `from_id` to append message request.
This PR updates Metaphysics to pass `from_id` when replying to a message.
cc: @mzikherman @joeyAghion

Add from_id to append message mutation, fix typos

---

schema/collection.js
schema/sorts/artwork_sorts.js
schema/sorts/collection_sorts.js
test/schema/collection.js

Eigen is changing its Favourites view to use Metaphysics ( https://github.com/artsy/eigen/pull/2402 ) and we need the ability to specify artwork sort order and `private` options, added in this PR.

Extends collection artwork_connection with private+sort args

---

schema/me/conversation/index.js
test/schema/me/conversation/index.js

So now that we have the full snapshot (and going forward) for inquiries, for the handful where we weren't able to backfill (actually deleted from the database), we can just silently skip them and avoid a crash.
Clients can choose to then do what they'd like with the requested data, which for other conversation purposes _is_ complete....in Emission, we don't render these in the Inbox. That's because of https://github.com/artsy/emission/pull/695/files#diff-d44670c88b75d348586c602c7216e036R139

@alloy => Dont crash when we dont have an inquireable snapshot

---

schema/me/conversation/message.js
test/schema/me/conversation/index.js

Adds a `from { name, email }` to `Message` schema. It does some parsing of the returned data to separate out the name (I think we discussed this at some point).
Looks like:
(Note currently it returns the _unmasked_ email, but I have an outstanding question about whether we'd prefer to show the _masked_ one. The good news is I can go ahead with the Emission side, and transparently switch this to the masked one if we decide so in the future).

@ashkan18 => Expose from name and email of message initiator

---

schema/me/conversation/message.js
test/schema/me/conversation/index.js

cc @l2succes 
We were using `raw_text`, which included quoted replies, forwarded content, email signatures, etc.
Apparently `body` is the text, but already parsed/cleaned-up (or attempted to), by [Griddler](https://github.com/thoughtbot/griddler), so we should just switch to using it! Then, we can see how our test cases look. This may seriously alter our plans for sanitization/parsing (or the 'REPLY ABOVE THS LINE' thing). I'll switch Emission to use this.
Thanks for the tip @joeyAghion !
If we want to explore other things, there is https://github.com/github/email_reply_parser, which is what GitHub uses to create comments out of email replies.

@joeyAghion => Add body for use instead of raw_text

---

test/schema/me/conversation/index.js
test/utils.js

Prior to this commit it was not possible to use `runAuthenticatedQuery` with a `rootValue`, instead you'd use `runQuery` and provide the authenticated values. Whaa, whaa.
Before considering this change I audited the usage of `runAuthenticatedQuery` and found that in only one place were we not taking the default value for `userID`, and even in that one place we actually WERE using the default value! So, I floated the idea on Slack and it sounded ok to @alloy.
From there I simply copied the signature of `runQuery` and scooped out the defaults to override them in the body of the function. Since you can't mutate a function param without being yelled at, I copied the `rootValue` into a local const and set the appropriate values.
Technically, there is a regression here where you cannot use an …

Improve util function to accept rootValue

---

schema/artist/maps/artist_meta_descriptions.js
schema/artwork/utilities.js
schema/filter_artworks.js
schema/home/fetch.js
schema/home/home_page_artist_module.js
schema/home/results.js
schema/me/artwork_inquiries.js
schema/me/bidder_positions.js
schema/me/conversation/index.js
schema/me/conversation/update_mutation.js
schema/me/conversations.js
schema/me/follow_artist.js
schema/me/lot_standings.js
schema/me/save_artwork.js
schema/partner.js
schema/types/formatted_number.js
test/schema/artist/carousel.js
test/schema/artwork/index.js
test/schema/image/cropped.js
test/schema/image/resized.js

I thought this was going to be a bloody mess, but instead it just worked! Here was the command I ran:
```
yarn prettier -- --write --trailing-comma es5 --print-width 120 --no-semi lib/**/*.js schema/**/*.js test/**/*.js
```
Then there was a little issue with how prettier dealt with some goofy lines in `schema/artwork/utilities.js`, but that was easy to fix - I just moved the eslint disables back to where they belonged.
Other than that linter is happy, prettier is happy and tests are green! 🤗

Run prettier against the entire codebase

---

schema/home/fetch.js
schema/home/home_page_artwork_modules.js

The functions in the `fetch` module are not GraphQL resolvers and thus
won’t get the same arguments passed in by default, especially not seeing
as these functions are invoked by our own code, e.g. `featuredFair()`.
/cc @jonallured My bad for missing this during review 🙈

[HomePage] Pass `fairsLoader` into fetch function.

---

bin/setup
schema/home/logged_out_modules.js

I also added a fix for the setup script's `nvm` check.
Related issue: https://github.com/artsy/collector-experience/issues/362

Put popular_artists module first for logged-out users

---

schema/articles.js
test/schema/articles.js

Also added a spec for `articles` since there weren't any! (a test like this would have caught the error)
cc @alloy

@jonallured => fix args to the articles endpoint

---

schema/artist/carousel.js
schema/artist/index.js
schema/artist/statuses.js
schema/artwork/context.js
schema/artwork/index.js

Some of the uses of loaders where the API path didn't need to be dynamically generated (only params passed thru), were being used as if it were the other style (dynamically generated from id's).

@alloy => Fix some issues in calling certain loaders

---

schema/me/conversation/message.js
test/schema/me/conversation/__snapshots__/message.js.snap
test/schema/me/conversation/message.js

This just relocates some sanitization logic from Emission to Metaphysics. Also adds tests for `messages`.
Related to [this Emission PR](https://github.com/artsy/emission/pull/721).

Added a bit of sanitization for initial messages in conversations

---

schema/home/context.js
schema/home/title.js

During team swap, I did some incorrect work in #707 that I thought was safely reverted in #714, but I was wrong. There were still other places where we had broken functions and this was only caught after deployment to production.
This commit should revert the rest of the broken changes from #707 and fix the bugs seen in production.

Revert even more loader work

---

schema/artist/index.js
test/schema/artist/index.js

This specific guard is needed because from Emission we conditionally
fetch a ‘selected artist’ for the Works for You view, but using an extra
boolean for this proved problematic because it meant that the ID
variable would be unused and GraphQL would complain about that. Instead
we always send the‘selected artist’ request, but with an empty string
when we don’t actually want it.

[Artist] Guard against empty ID string.

---

schema/me/conversation/send_message_mutation.js
test/schema/me/conversation/__snapshots__/message.js.snap
test/schema/me/conversation/__snapshots__/send_message_mutation.js.snap
test/schema/me/conversation/message.js
test/schema/me/conversation/send_message_mutation.js

We use the `body` field nowadays in Emission, not `raw_text` anymore, so added that and faffed a bit with test coverage.

[sendMessageMutation] Add missing data to optimistic response.

---

package.json

Latest version of yarn (which Heroku is using), has an issue: https://github.com/heroku/heroku-buildpack-nodejs/issues/468

@mzikherman => Lock yarn version for Heroku

---

schema/me/conversation/message.js
test/schema/me/conversation/__snapshots__/message.js.snap
test/schema/me/conversation/message.js

Once https://github.com/artsy/impulse/pull/348 is deployed, certain messages will have this available, and so we can return it, instead of relying on the `body` fallback.

@ashkan18 => Use original_text if available for the body

---

schema/collection.js
test/schema/__snapshots__/collection.js.snap
test/schema/collection.js

Eigen 3.2.4 doesn't handle GraphQL errors properly (retrospective forthcoming). To provide an immediate fix, I've modified metaphysics.
The problem is, for some users (and all newly created users) requesting their favourites returns an error from Gravity. This PR catches the error and returns an empty list of results instead. Note this catches *all* errors from that specific endpoint, but I don't believe any services beside eigen rely on this specific part of metaphysics. I can submit a more nuanced error-catching PR later, after the bug has been fixed.

@dblock => Intercepts errors from Gravity

---

schema/collection.js
test/schema/__snapshots__/collection.js.snap
test/schema/collection.js

Gravity has a bug (see [this PR](https://github.com/artsy/gravity/pull/11240)) where total counts being returned for user favourites include unpublished artworks. This count discrepancy causes Relay to return `hasNextPage` as `true` while `endCursor` is `null`, which causes serious problems for users on Eigen (see [this Sentry report](https://sentry.io/artsynet/eigen/issues/347342766/events/7196937891/)). 
This pull requests overrides the `pageInfo.hasNextPage` value returned from Relay to set it to false if the end cursor is missing. I've tested locally on Eigen to verify the fix works, and have added test coverage.
Serious props to @orta for his help reproducing this bug. 
Also removes `console.log` statements I accidentally'd last night.

Add fix for Relay/Gravity count discrepencies.

---

schema/me/conversation/index.js
test/schema/me/conversation/index.js

Added the ability to sort messages in ascending or descending order to support the following feature (https://github.com/artsy/collector-experience/issues/486). Namely, returning messages in a conversation thread starting from the most recent and paginate backwards.

Adds ability to sort conversation messages

---

package.json

Bumps:
- `node` 8.4.x
- `npm` 5.4.x 
- `yarn` 1.0.x
This matches the Node version in Force and Reaction.

@orta => Bump Node v.8.4.0

---

lib/loaders/loaders_with_authentication/index.js
schema/me/lot_standing.js
schema/me/lot_standings.js
test/schema/me/lot_standing.js

This will make it possible to quickly tell if an auction is live or not and also access its `sale` information (i.e. `href`, `title`, etc).
Fixes #750 
cc @sweir27

Adds sale information to LotStanding

---

schema/ordered_sets.js
test/schema/ordered_sets.js

Looks like the schema definition for `OrderedSets` never accepted / forwarded the `size` and `page` parameters to Gravity, presumably because most OrderedSets use cases don't require >10 sets for any given `key`
But the new /categories page in Force in fact does expect ~15 gene families, so in order to be able fetch them all, we simply add the missing pagination params here.

Add missing pagination params for OrderedSets

---

schema/sorts/collection_sorts.js
test/schema/collection.js

As [discussed in Slack](https://artsy.slack.com/archives/C1HH3KNJG/p1506357396000388), the only use of collections is for saved artworks. Gravity defaults to sorting this in the order you added them in, but a more sensible default which metaphysics can expose is to sort them in most recently saved first. Since this is a change to the schema itself, I didn't add any tests but rather had to update the existing tests. Let me know.

Changes collection sort order default.

---

schema/collection.js
test/schema/__snapshots__/collection.js.snap
test/schema/collection.js

This removes two FIXMEs from metaphysics as a part of [Eigen's retrospective](https://github.com/artsy/post_mortems/issues/20). In detail:
- [The first fix](https://github.com/artsy/metaphysics/pull/738) was to overcome a bug in Gravity that's been [fixed](https://github.com/artsy/gravity/pull/11240) and deployed. I've tested locally by favouriting three artworks on staging, unpublishing one, and paging through using GraphiQL. I only get two.
- [The second fix](https://github.com/artsy/metaphysics/pull/737) was kept in, and the FIXME removed to avoid propagating errors from Gravity (that are a part of using this API) to the metaphysics consumer. This makes metaphysics more of an idiomatic GraphQL provider.
Not sure about the lock file changes – any suggestions?

Removes FIXMEs

---

schema/artist/index.js
test/schema/artist/index.js

This is the same fix, but for `exhibition_highlights`.
Note the issue with receiving less data than available is more apparent, the exhibition highlights for Dan Colen will appear slightly anemic for now.
That can be fixed by setting a super low [relevance](https://github.com/artsy/gravity/blob/7fbedb2462c77887155caa096b0323b59533b562/app/models/domain/partner_show.rb#L561-L592) for those partner types, but in the meantime, this is the fix.

@anandaroop => Dont return exhibition highlights for an artist from private partners

---

package.json
yarn.lock

Which includes [this change](https://github.com/artsy/artsy-newrelic/pull/10) that should enable New Relic VM metrics and more gracefully crash when exceeding a dyno's memory limit.

@alloy: Update Artsy New Relic

---

lib/loaders/index.js
lib/loaders/loaders_without_authentication/index.js

Converted into an object in https://github.com/artsy/metaphysics/pull/759 but needs to be a function to ensure they're re-created.
I tried making a test for this, but struggled:
```js
describe("all loaders", () => {
it("recreates all loaders each time", () => {
const firstTimeLoaders = loaders()
const secondTimeLoaders = loaders()
for (const key in firstTimeLoaders) {
if (firstTimeLoaders.hasOwnProperty(key)) {
expect(firstTimeLoaders[key]).not.toEqual(secondTimeLoaders[key])
}
}
})
})
```
```js
describe("all loaders", () => {
it("recreates all loaders each time", () => {
const firstTimeLoaders = loaders()
const secondTimeLoaders = loaders()
expect(firstTimeLoaders).not.toEqual(secondTimeLoaders)
})
})
```
both are equal, there's not really a way I can think of to check memory addresses …

Always create un-auth'd loaders

---

lib/loaders/loaders_with_authentication/index.js
lib/loaders/loaders_without_authentication/gravity.js
schema/artists/popular.js
schema/artists/trending.js
schema/home/context.js
schema/index.js
test/schema/artists/__snapshots__/popular.js.snap
test/schema/artists/popular.js
test/utils.js

Covers the gravity route `artists/popular`, copying the pattern set by `trending_artists`. 
*Interesting sidenote*: this route works for both auth'd and unauth'd users. It's because there [is a param](https://github.com/artsy/gravity/blob/cb728d02a59ca232df2eb0cac19d17d016f629fa/app/api/v1/artists_endpoint.rb#L189) `exclude_followed_artists` which is only accessible if you're logged in. So we switch between auth/unauth'd loaders depending on whether you're a logged in user. 
TBH though, and this is probably something we should do in another PR, or have a quick chat about is that should these kind of things should get scoped somewhere? E.g.
```graphql
{
artist_things {
popular {
}  
trending {
}
}
}
```

Adds a popular Artists schema

---

package.json
test/helper.js
yarn.lock

I ran locally, and everything seemed to work ok, obviously we don't really have a way of verifying _all_ requests, it has however been a ~year since I last updated these https://github.com/artsy/metaphysics/commit/d380856aece429b25bdcd747975f7aed5b175f3b
We're now triggering this warning on every test run / launch, https://github.com/graphql/graphql-js/blob/master/src/utilities/assertValidName.js#L40 so I've currently ignored it - I know you've done a bunch of work there anyway so I think ignoring it i tests is fine, but it shows when you launch the server

Updates GraphQL related dependencies

---

index.js
package.json
yarn.lock

Fixes #777. Used a depth limit of 10 as a default, and added logging so we can monitor staging for a while to see if there are any problems.
I ran through Force, Emission, Eigen, and Prediction uses of metaphysics and the largest depth I found was 7, so 10 feels like a good starting point.

Adds depth limit to metaphysics queries.

---

index.js

Signed-off-by: Ash Furrow <ash@ashfurrow.com>
By importing the module, we are loading New Relic. By using it's middleware, we _were_ adding browser monitoring, which was causing a lot of logs like this:
> {"v":0,"level":40,"name":"newrelic","hostname":"XXX","pid":15,"time":"2017-10-10T20:19:29.239Z","msg":"NREUM: browser_monitoring requires valid application_id","component":"api"}

Removes New Relic browser monitoring.

---

schema/gene.js
schema/gene_families.js

Follow-up to https://github.com/artsy/gravity/pull/11304
This adds pagination and sorting to the `GeneFamily` schema and exposes a few additional `Gene` attributes

Pass thru gene family pagination params to Gravity

---

index.js

Pretty straightforward PR. Since we now know the maximum depths of queries run in production, we no longer need to log them.

Removes logging for Query depths.

---

schema/gene_families.js
test/schema/gene/__snapshots__/gene_families.js.snap
test/schema/gene/gene_families.js

@alloy [pointed out](https://artsy.slack.com/archives/C1HH3KNJG/p1508149028000096) that going forward we should prefer [**connections**](https://facebook.github.io/relay/graphql/connections.htm) for list types in our schemas.
Accordingly, this updates the recently added `GeneFamilies` schema to use a connection.

Convert GeneFamiles pagination to connection

---

schema/filter_artworks.js
schema/gene.js
test/schema/filter_artworks.js
test/schema/gene/gene.js

Part of the fix for https://github.com/artsy/force/issues/1822
The `filter_artworks.artworks_connection` field is problematic, because it requires both `filter_artworks` and `artworks_connection` fields to receive pagination information, which is unintuitive.
Seeing as the `artworks_connection` field on the `Gene` type already is backed by the filter endpoint, I took this opportunity to see what it would look like to integrate the aggregation results more fully inside the connection itself.

[Gene] Add aggregation metadata to artworks connection.

---

schema/me/collector_profile.js
test/schema/me/collector_profile.js

This adds the `intents` property to the `collector_profile` object on the me schema in order to implement the [collector intent question](https://github.com/artsy/collector-experience/issues/504) with a [graphQL mutation](https://github.com/artsy/collector-experience/issues/564#issuecomment-336897545).

[Onboarding] add intents property to collector profile schema

---

schema/filter_artworks.js
test/schema/filter_artworks.js
test/schema/gene/gene.js

This reverts commit 574d4309fdd152f47ac82764342ab326190418ca.
It lead to `options` containing `page: 1` [here](https://github.com/artsy/metaphysics/blob/0839e1e3f1a521c698dc41fe873f0b29af968458/schema/gene.js#L70), which subsequently lead to `page: 1` overriding the calculated `page` [here](https://github.com/artsy/metaphysics/blob/0839e1e3f1a521c698dc41fe873f0b29af968458/lib/helpers.js#L84).
I actually think the `Object.assign(…)` is done in the wrong order, `gravityArgs` should come first, but it felt kinda weird to override a `page` param when it exists, so opted for restoring the previous behaviour instead.

Revert "[FilterArtworks] Default `page` to 1."

---

schema/sale_artwork.js
test/schema/sale_artwork.js

I had pretty much finished this but just never put it up for code review. I believe this should solve the discrepancy for off-increment starting bids. It's a little complicated, but the idea is to respect Gravity's `minimum_next_bid_cents`, even if that's off-increment, but then snap to increments going forward. Gravity should be supplying an on-increment `minimum_next_bid_cents`, but this code does not enforce that. The goal though is to retire this code and have increments dropdowns populated from Causality's future GraphQL API.

Use preset increments

---

tsconfig.json

`"include": ["lib/**/*.js"]` was only including files in `/lib` so everything else wasn't getting indexed.

Fix VSCode import aliasing

---

lib/loaders/loaders_with_authentication/index.js
schema/sale/index.js
test/schema/sale/__snapshots__/index.js.snap
test/schema/sale/index.js
yarn.lock

This adds a Relay connection to the `SaleType` schema. This change is to support a React Native auction view in Emission.

Adds Relay connection for sale artworks to sale schema

---

schema/object_identification.js
schema/sale/index.js
schema/sales.js
test/schema/me/lot_standing.js
test/schema/me/sale_registrations.js
test/schema/sale/index.js

Continues work from #794. Paired with @orta. This is required to get Relay working with Emission for sales.

Adds a Node interface to Sale

---

circle.yml
schema/sale_artwork.js
test/schema/sale/index.js

Without using `slice`, I was mutating the cached promise returned by the call to `/increments`. For future lots with a lower starting price, this resulted potentially in some of the increment policy tiers having been excluded for subsequent calls to the `bid_increments` resolver.

fix bad increments of sale_artwork within sale

---

schema/index.js
schema/suggested_genes.js
test/schema/suggested_genes.js

This adds suggested genes to metaphysics. We use this in iOS and web onboarding and instead of fetching it from s3 directly we decided to added it here to make it a little more reusable.

suggested genes

---

schema/sale_artwork.js
test/schema/sale_artwork.js

This PR changes the list of `bid_increments` to be of the `GraphQLFloat` type instead of `GraphQLInt`. We have sales running now (in HKD) with amounts over $24,000,000 which leads to this error `TypeError: Int cannot represent non 32-bit signed integer value: 2400000000` when trying to load increments.
The migration is to _also_ update the value of `BIDDER_POSITION_MAX_BID_AMOUNT_CENTS_LIMIT` in gravity and metaphysics. The current limit is actually below the starting price of this lot. (This has already been completed.)

@acjay => use graphQLFloat type for increments #migration

---

lib/loaders/loaders_without_authentication/gravity.js
schema/index.js
schema/match/gene.js
test/schema/match/gene.js

This adds a scheme for the `match_gene` in order to search for genes in the [gene follow onboarding component](https://github.com/artsy/collector-experience/issues/506#issuecomment-340519191).

[Onboarding] add match_gene

---

lib/loaders/loaders_with_authentication/gravity.js
schema/me/update_collector_profile.js
test/schema/me/update_collector_profile.js

This updates the `updateCollectorProfile` mutation in order to implement the data submission for the [Collector Intent](https://github.com/artsy/collector-experience/issues/504) question of onboarding. In this PR, I added the intents field, switched the data loader for a custom one, and added some better error handling for when the data loader is missing.

[Onboarding] add intents field to collector profile mutation

---

schema/me/update_collector_profile.js
test/schema/me/update_collector_profile.js

Switch the `intents` input field in the `updateCollectorProfile` mutation to be an enum.

[Onboarding] refactor intents type to be an enum

---

lib/loaders/api/loader_with_authentication_factory.js
lib/loaders/api/loader_without_authentication_factory.js
lib/loaders/api/logger.js
lib/timer.js

Increases the metadata coming from staging/dev mode metaphysics:
```graphql
{
me {
name # Not a dataloader
followed_artists_connection(first:5) {
edges {
node {
artist {
name
}
}
}
}
}
popular_artists {
artists{
name
}
}
artist(id:"banksy") {
name
}
gene(id:"the-fantastic"){ # Not a dataloader
name
display_name
}
}
```
to 
```json
{
"data": {
"me": {
"name": "Orta Therox",
"followed_artists_connection": {
"edges": []
}
},
"popular_artists": {
"artists": [
{
"name": "Pablo Picasso"
},
[...]
]
},
"artist": {
"name": "Banksy"
},
"gene": {
"name": "The Fantastic",
"display_name": null
}
},
"requests": {
"gravity": {
"requests": {
"artist/banksy": {
"time": "0s 128.459ms",
"cache": true
},
"artists/popular": {
"time": "0s 340.384ms",
"cache": false
}, …
```

Add timing/cache metadata to the dev extensions

---

index.js
lib/helpers.js
package-lock.json
package.json

Speeds this up a lot for me locally. Was taking about 5 seconds or so to run the introspection query (which has tons of resolver functions) and now it's like 200ms.

Use setImmediate for all tracing api calls.

---

index.js

As [discussed in Slack](https://artsy.slack.com/archives/C1HH3KNJG/p1511366042000596) here are a few optimisations that:
* Ensure processing is done _after_ the response is sent to the client
* Other code gets a chance to enqueue work
* Only instrument resolvers of object types (we may be missing out on resolvers for scalar fields that _do_ perform IO work, though)
* Do not instrument resolvers of the introspection query
Better detection of interesting resolvers can be done by making them use async/await: https://github.com/artsy/metaphysics/issues/829

Trace optimzations

---

schema/me/__tests__/__snapshots__/update_me_mutation.test.js.snap
schema/me/__tests__/update_me_mutation.test.js
schema/me/update_me_mutation.js
schema/user.js

Signed-off-by: Yuki Nishijima <yuki@artsymail.com>
We added the `price_range_min` and `price_range_max` fields to the `UpdateMyProfile` mutation. Initially we had added `price_range` but discovered that`/me` does not support `price_range`. For more context see [slack conversation](https://artsy.slack.com/archives/C0GNAB0US/p1511284180000014). This work is in support of the data submission for the [onboarding budget question](https://github.com/artsy/collector-experience/issues/507).

[Onboarding] add price_range_min and price_range_max to UpdateMyProfile mutation

---

.env.test
index.js
lib/apis/gravity.js
lib/loaders/loaders_with_authentication/convection.js
lib/mergeSchemas.js
lib/requestIDs.js
lib/tracer.js
mergedSchema.js
package.json
yarn.lock

This bootstraps schema stitching _inside_ MP. In the below example you’ll see the use of MP’s and Convection’s schemas combined and used.
```graphql
{
artist(id: "marina-abramovic-1") {
name
}
submission(id: 186) {
artist_id
artist {
name
}
}
}
```
```json
{
"data": {
"artist": {
"name": "Marina Abramović"
},
"submission": [
{
"artist_id": "marina-abramovic-1",
"artist": {
"name": "Marina Abramović"
}
}
]
}
}
```
----

Neo metaphysics

---

schema/__tests__/object_identification.test.js
schema/__tests__/partner.test.js
schema/partner.js

So we can determine what category of partner represent a partner (where category is 'Blue Chip', 'Top Emerging', etc. - based on being included in that category).

@joeyAghion => Add nested categories to a partner

---

lib/loaders/loaders_with_authentication/convection.js
schema/aggregations/aggregation_count.js
schema/gene.js
schema/index.js
schema/me/__tests__/consignments/__snapshots__/add_asset_to_submission_mutation.test.js.snap
schema/me/__tests__/consignments/__snapshots__/create_submission_mutation.test.js.snap
schema/me/__tests__/consignments/__snapshots__/submissions.test.js.snap
schema/me/__tests__/consignments/__snapshots__/update_submission_mutation.test.js.snap
schema/me/__tests__/consignments/add_asset_to_submission_mutation.test.js
schema/me/__tests__/consignments/create_submission_mutation.test.js
schema/me/__tests__/consignments/submissions.test.js
schema/me/__tests__/consignments/update_submission_mutation.test.js
schema/me/consignments/add_asset_to_submission_mutation.js
schema/me/consignments/asset.js
schema/me/consignments/create_submission_mutation.js
schema/me/consignments/submission.js
schema/me/consignments/submissions.js
schema/me/consignments/update_submission_mutation.js
schema/me/index.js

Paired with @sweir27 on bringing back the JS API for Convection, we've built it with the expectation of this being the API that we'll use when stitching. Now the ENV var switches between a working JS implementation, and a stitched implementation. They're not 100% fit _today_, but it's built with *client side* future proofing in mind.
Opted to having a `submission` always be called `consignment_submission` inside metaphysics. So, things that would need to be done in stitching:
* Rename mutations to something like `createConsignmentSubmission`
* Mutations in Convection change their return types to be `consignment_submission: [data]`
* `Submission` -> `ConsignmentSubmission`

Adds back the JS Convection API

---

lib/loaders/api/loader_without_authentication_factory.js
lib/loaders/loaders_without_authentication/gravity.js
schema/artist/__tests__/highlights.test.js
schema/artist/highlights.js
schema/artist/index.js
schema/partner_artist.js

~~This doesn't actually work (yet), but uses the loaders in the way you might expect (ie- unauthenticated loaders can still cache and resolve with body/headers).~~
This PR does all the things now- it can cache/resolve body/headers for unauthenticated loaders, and also exposes an edge from artist to partners, decorated with `PartnerArtist` info.

@alloy => Make a connection for partner artists (+ cache headers for unauth'ed requests)

---

schema/artist/__tests__/index.test.js
schema/artist/index.js

It seems like its a string field in Mongo, but we're storing lists delimited by a newline.
Looks like:

@joeyAghion => Expose collections to artist schema

---

schema/partner_artist.js

The library appends `Connection` to the name, so no need for this.

@orta => Rename to drop redundant Connection

---

lib/loaders/loaders_with_authentication/gravity.js
schema/me/__tests__/followed_artists_artwork_groups.test.js
schema/me/followed_artists_artworks_group.js
schema/me/index.js
schema/me/notifications.js

Still have to add some specs, but this is working with some minor updates in Emission!
This basically does what's described in https://github.com/artsy/collector-experience/issues/728#issuecomment-349737737
There's a new schema under `me`, that returns something like:

@sarahscott = Add new type under me to group published artworks by followed artists

---

lib/loaders/loaders_without_authentication/gravity.js
schema/__tests__/gene.test.js
schema/gene.js

Adds a `similar` field to the `Gene` type. This is in support of implementing the follow gene for Onboarding.

Adds 'similar' field to Gene type

---

schema/__tests__/suggested_genes.test.js
schema/suggested_genes.js

Right now the `SuggestedGene` type is a different type from the `Gene` type. The Follow Gene step in the onboarding flow needs to deal with both the types and adding the same fields will allow Relay to respect required fields like `name` and `image`.
Alternatively, we could just use the `Gene` type anywhere rather than maintaining two similar types. Let us know if this is something we should be doing.

Add the image field to SuggestedGene type

---

schema/__tests__/filter_artworks.test.js
schema/__tests__/gene.test.js
schema/filter_artworks.js
schema/object_identification.js

This lets subsequent pages (keeping the same filter) to be directly requested via `node(__id: ...)`. This works better with Relay pagination containers. The key is that we have a synthetic `__id` that encodes all the things required to do the fetch, thus letting Relay be able to easily update its store as subsequent pages are requested (Relay takes care of _not_ encoding pagination params in the key).

@orta => Implement NodeInterface for filtered artworks

---

schema/__tests__/tag.test.js
schema/tag.js

Now that the filter artworks schema under Gene is working great, I'm going to use the same pattern for Tag.

@mzikherman => Add filter artworks to tag schema (analogous to gene)

---

lib/loaders/api/index.js
lib/loaders/loaders_without_authentication/gravity.js
package.json
schema/__tests__/sale_artwork.test.js
schema/sale/__tests__/index.test.js
schema/sale/index.js
schema/sale_artwork.js

Adds a new field to `Sale`, `display_timely` and updates `Sale` and `SaleArtwork` schemas to use dataLoaders rather than raw `gravity` call. 
```
{
sales(size: 100 sort:TIMELY_AT_NAME_DESC) {
id,
display_timely_at
}
}
```

[Sale] Add display_timely_at field

---

schema/filter_artworks.js

cc @alloy This fixes the issue where the 'Medium' dropdown aggregation was not including the gene filter, forgot I added it exactly for this reason for the gene page filter a while back.

@mzikherman => Allow param that will return correct medium aggregations for a gene filter

---

lib/loaders/loaders_with_authentication/impulse.js

There's a bunch of pre-radiation conversations ( roughly 0.5% ) which cannot be shown as a set of messages today. If you happen to have one of those lucky conversations then we can't really show messaging for your data. This flag removes them from the API.

Adds a flag to ensure that only conversations with messages come through

---

schema/me/suggested_artists_args.js

I've found another edge case where a duplicate artist could be suggested after searching and following (see https://github.com/artsy/collector-experience/issues/842#issuecomment-353200862). Gravity already has[ a way to exclude specified artists](https://github.com/artsy/gravity/blob/637e2bc8a4e3ee00d538871081ba92cbaf3d1848/app/api/v1/me_suggestions_endpoint.rb#L46), so MP should be able to send the `exclude_artist_ids` argument over to Gravity.

Add excluded artist ids to suggested artist arguments

---

.env.test
index.js
package.json
yarn.lock

The Heroku build step was putting the `src/{config,index}.js` files inside `build/src/` but others were stored in `build/{lib,schema}` and the root `index.js` file was completely missing.

Fix build after changing file tree.

---

scripts/dump-schema.js

This seems to be fallout from the `graphql*` updates, specifically this PR https://github.com/graphql/graphql-js/pull/927
I don't _fully_ understand it yet tbh, but when running `printSchema` on latest master, I was getting output that would crash when being imported into Emission, with extra quotes around our `description` fields:
```
[1] ERROR:
[1] Error loading schema. Expected the schema to be a .graphql or a .json
[1] file, describing your GraphQL server's API. Error detail:
[1] 
[1] GraphQLError: Syntax Error GraphQL request (6:3) Expected Name, found String
[1] 
[1] 5:   input AddAssetToConsignmentSubmissionInput {
[1] 6:   """The type of the asset"""
[1]      ^
[1] 7:   asset_type: String!
[1] 
[1]     at syntaxError (/Users/mzikherman/code/Artsy/emission/node_modules/relay-compile …
```

@orta => Pass option to printSchema method to avoid breaking change

---

src/schema/artists/popular.js

This PR depends on https://github.com/artsy/gravity/pull/11488. It needs to be merged before this PR.
We are working on https://github.com/artsy/collector-experience/issues/811, and this PR adds the `exclude_artist_ids` option so we can exclude already displayed popular artists on the onboarding flow.

[Blocked] Add exclude artist ids to suggested artist args

---

src/schema/__tests__/auction_results.test.js
src/schema/auction_result.js

Passes in `format` arg to `numeral`. This allows clients to have some control over the display, in this case the string `0a` will work for our auction lot abbreviation.
1234 -> 1k
1234567 -> 1m
etc.

@joeyAghion => Allow number formatting to be specified for display prices

---

src/schema/me/save_artwork_mutation.js

Fallout from https://github.com/artsy/metaphysics/pull/879 , the signature of the loader wasn't right.
Reported as part of gene page QA ('save' button not working).

@orta => Fix save/remove artwork mutations

---

src/schema/filter_artworks.js
src/schema/gene.js

Fixes https://github.com/artsy/collector-experience/issues/893
I’ve got a much larger PR coming in with refactoring and tests.

[FilterArtworks] Omit `medium` filter when `null`.

---

src/schema/artist/__tests__/highlights.test.js
src/schema/artist/highlights.js
src/schema/partner_artist.js

Once https://github.com/artsy/gravity/pull/11506 is merged, the param will be respected in the API.
Then, we can update the [client](https://github.com/artsy/reaction/blob/759382ad7ee0229395c82d15d40f31480292261a/src/Components/Artist/MarketInsights/MarketInsights.tsx#L199) to pass `display_on_partner_profile: true`.

@joeyAghion => Pass thru display_on_partner_profile to /partner_artists API

---

package.json
patches/graphql-relay+0.5.3.patch
src/schema/partner_artist.js
yarn.lock

This is just a start, it sets up `patch-package` and implements the logic we need in order to treat an API result (a first-class 'thing' which is generally the `node` in a connection), as the _edges_ (and one of those returned fields as the `node`).
This is accomplished by specifying a `nodeField` param. If present, that field is set as `node`, and then, all the fields that _would_ have been in the node instead, move to the edge.
I'm definitely not crazy about the patch itself, so I'm not sure if its worth it. I think if I came up with a better set of options/names I'd feel better about it.
`patch-package` is cool btw!

@alloy => Use patch-package and support treating an API result as edge fields

---

src/schema/article.js
src/schema/artist/index.js
src/schema/artwork/index.js
src/schema/auction_result.js
src/schema/filter_artworks.js
src/schema/home/home_page_artist_module.js
src/schema/home/home_page_artwork_module.js
src/schema/me/conversation/index.js
src/schema/me/conversation/message.js
src/schema/me/followed_artists.js
src/schema/me/followed_genes.js
src/schema/me/index.js
src/schema/me/notifications.js
src/schema/object_identification.js
src/schema/sale/index.js

https://artsyproduct.atlassian.net/browse/IN-60 #resolve
Closes #865
The specific problem in the linked Jira ticket was about a HTML only Message not being being recognised as such, because it had no `raw_text` field and thus failed `isTypeOf`.

[Node] Replace `isTypeOf` on types in favour of single `resolveType`.

---

src/schema/me/conversation/index.js

We still want to return these messages from Radiation/Impulse and need to make sure we render them properly on client side.
Remove unused/unimplemented param.
cc: @sarahscott

Remove Ignore bulk messages

---

.vscode/settings.json
README.md
package.json

Adds a `yarn promote:production` command which aliases `heroku pipelines:promote -r staging`.

[Toolchain] Add yarn promote:production command

---

src/schema/__tests__/sale_artworks.test.js
src/schema/filter_sale_artworks.js

Gravity's `sales_artworks` endpoint has been updated to include `is_auction` flag to filter lots only in auction. We need to update MP to include that param.
I _think_ there is only one args `filterSaleArtworksArgs` is defined for accessing both `filters` and `sales_artworks` endpoints in Gravity, I added `is_auction` which currently would only be applicable to `sales_artworks` and can be ignored for `filter` endpoint, hope thats ok.

Add is_auction to sale_artworks filter query

---

src/schema/me/conversation/index.js

`last_message.snippet` may sometime be message unrelated to this user.
For now return `null` till we come up with long term solution.
Simple solution of https://github.com/artsy/metaphysics/pull/925

Return null for snippet till we come up with long term solution

---

src/schema/__tests__/partner_show.test.js
src/schema/__tests__/show.test.js
src/schema/partner_show.js
src/schema/show.js

We want to be able to distinguish between `online_exclusive` shows and shows with actual locations.
Add new `boolean` field to `partnerShow` which based on `location`, `fair_location` and `partner_city` of the PartnerShow returns flag showing if it's `has_location` or not.

[STI-36] Add is_online_exclusive flag to partner show

---

src/schema/artist/__tests__/index.test.js
src/schema/artist/index.js

We want to filter out online exclusive shows from artist's exhibition highlights.
https://artsyproduct.atlassian.net/browse/STI-15
In `exhibition_highlights` resolver, add `has_location: true` to make sure we filter shows without location.
Gravity change to support filter by `has_location`.
https://artsyproduct.atlassian.net/browse/STI-39

[STI-15] Filter out shows without location in exhibition highlights query

---

src/schema/sales.js

First Metaphysics PR 🎈 
Following up on pairing yesterday -- adds ids type to sales schema, and updates resolver to use `id` rather than `ids` (to stay in accordance with Gravity).
One thing I noticed is that this file is not yet tested, and many of the plural endpoints are not.  Tried a few of the testing models laid out in the schema folder but kept getting the error `Error: getaddrinfo ENOTFOUND api.artsy.test api.artsy.test:443` -- am I just missing an env var, or maybe this is another pairing opportunity?

@orta => Add ids to sales

---

src/lib/cache.js

We were observing that unpublished artworks were still resolving from Metaphysics' cache (and had to be manually removed), even though they should have been deleted.
Basically, I think we got the `delete` command wrong (in Redis its `del`).
I skipped specs here since we use a completely stubbed client, I don't think it would have caught this necessarily.

@sweir27 => Rename delete -> del to delete from Redis

---

src/schema/__tests__/artists.test.js
src/schema/artists.js

Adds `ids` param to `artists` schema, to return artists matching an array of passed ids.

@alloy => Can return artists by array of ids

---

src/schema/__tests__/fairs.test.js
src/schema/fairs.js

Very similar to https://github.com/artsy/metaphysics/pull/949, adds `:ids` param to Fairs endpoint.

@mzikherman => Search fairs by [:ids]

---

index.js
package.json
yarn.lock

This PR adds gzip compression via the handy [compression](https://github.com/expressjs/compression) package. Part of @yuki24 and I's sprint to improve front-end performance.
We have been using webpagetest.org to benchmark performance of the major force pages (artsy.net, artsy.net/collect, and artsy.net/artist/....). It included this recommendation for how we can improve:

@damassi => compress responses

---

src/lib/__tests__/all.test.js
src/lib/all.js
src/lib/loaders/legacy/gravity.js
src/schema/__tests__/partner_show.test.js
src/schema/__tests__/show.test.js
src/schema/partner_show.js
src/schema/show.js

As I'm working thru remaining legacy data loaders (home page ones coming next!), I figured it's a good idea to PR early and often. Much like voting.
So this removes a legacy `all` helper, that was being used like: `gravity.all("artworks")`, which would continue paginating the API until exhausted. We have a `allViaLoader` helper which is used in a couple places instead (and an open issue to remove the client code in Force which requests that since it's a horrible pattern).
Also removes some rewire/stubbing via explicit DI of the loaders. Definitely doing a lot of this in these PRs, @alloy mentions we can't easily have both Rewire and Jest stubs in the same project, and so it'd be preferable to remove rewire entirely?

@orta => Remove `all` legacy loader, remove couple rewire uses

---

src/schema/artist/__tests__/statuses.test.js
src/schema/artist/statuses.js

Forgot to return from the promise. This bug was spotted just minutes after being introduced in production (no 'Related Artists' tab on artist pages).

@mzikherman => Make sure to return related artist statuses

---

src/schema/artist/index.js

I inadvertently changed the 'level' that a resolver was fetching counts for articles and related artists, so any query to `counts { ... }` would fetch those, even if you _werent_ requesting article counts (for example).
This update moves that back up, but in the process, I discovered that https://github.com/artsy/metaphysics/blob/master/src/schema/fields/numeral.js is very inflexible in that you can't pass in your own resolver. So this just simplifies those and drops that custom field support entirely for these fields.
I checked in Force/Eigen/Emission and we were just using them as numbers anyway, and not _formatted numbers_ (ie- we weren't ever calling `counts { articles(label: .., format: ...) }` which would no longer work. `counts { articles }` remains a number.

@l2succes => Fix for overfetching related artist and article counts

---

src/lib/loaders/loaders_with_authentication/gravity.js
src/lib/loaders/loaders_without_authentication/gravity.js
src/schema/home/__tests__/home_page_artist_module.test.js
src/schema/home/__tests__/home_page_artist_modules.test.js
src/schema/home/__tests__/home_page_artwork_module.test.js
src/schema/home/__tests__/home_page_artwork_modules.test.js
src/schema/home/context.js
src/schema/home/fetch.js
src/schema/home/home_page_artist_module.js
src/schema/home/home_page_artist_modules.js
src/schema/home/home_page_artwork_modules.js
src/schema/home/results.js
src/schema/home/title.js

Making some more progress! 
This refactors home page related code to use new data loaders. The main idea of the refactor, is that there were lots of helpers/methods that were getting `userID` and `accessToken` plucked out of `rootValue` and explicitly passed around, and fetching data. Now, similarly to `totalViaLoader` and `allViaLoader`, these helper methods now accept an actual data loader, as opposed to tokens/ids.
Then, the places that were calling the various helper methods were updated to pass the loaders in.
Force homepage looks fine pointing to staging/prod, both logged in and logged out. I checked the various types of homepage rails/contexts and all matched what's currently deployed.
Figured I'd open the PR early.

@alloy => Update homepage related code to use new data loaders

---

src/lib/graphqlErrorHandler.js

If we determine that the error is a 404, don't send to Sentry. Seems to work locally for things like `artist(id: "andy-waarhol")`.

@alloy => Dont send 401/403, and 404 to Sentry

---

src/lib/__tests__/graphqlErrorHandler.test.js
src/lib/graphqlErrorHandler.js

I initially wanted to blacklist 504 errors, but realised that Gravity actually only returns 500s for timeouts of proxied requests. After giving it some more thought, I realised that it’s not MP’s responsibility at all to report server errors, only client errors (except for the blacklisted ones of course).

 [graphqlErrorHandler] Add tests and don’t report server errors.

---

src/schema/me/__tests__/conversation/__snapshots__/conversation.test.js.snap
src/schema/me/__tests__/conversation/__snapshots__/message.test.js.snap
src/schema/me/__tests__/conversation/conversation.test.js
src/schema/me/__tests__/conversation/message.test.js
src/schema/me/conversation/index.js
src/schema/me/conversation/message.js

Impulse [now](https://github.com/artsy/impulse/pull/441) offers `from_principal` as one of the fields in `Message` json. We can use that here to detect `is_from_user` and `last_message_from_user` easier.

Update is_from_user to use from_principal if available

---

src/schema/sale_artwork.js

Similar to https://github.com/artsy/metaphysics/pull/969 , noticed some requests to fields would fail with a type error in Sentry.
These are all deprecated (I guess some client is still out there!), and the newer fields use float: https://github.com/artsy/metaphysics/blob/eddb94804de02558e4b01c7b320f423ee2c867eb/src/schema/fields/money.js#L56

@sweir27 => Use float instead of int for some legacy _cents fields

---

src/index.js
src/lib/__tests__/apis/galaxy.test.js
src/lib/__tests__/apis/gravity.test.js
src/lib/apis/fetch.js
src/lib/loaders/__tests__/api.test.js
src/lib/loaders/__tests__/user_agent.test.js
src/lib/loaders/api/index.js
src/lib/loaders/index.js
src/lib/loaders/loaders_with_authentication/convection.js
src/lib/loaders/loaders_with_authentication/gravity.js
src/lib/loaders/loaders_with_authentication/impulse.js
src/lib/loaders/loaders_with_authentication/index.js
src/lib/loaders/loaders_without_authentication/delta.js
src/lib/loaders/loaders_without_authentication/diffusion.js
src/lib/loaders/loaders_without_authentication/galaxy.js
src/lib/loaders/loaders_without_authentication/gravity.js
src/lib/loaders/loaders_without_authentication/index.js
src/lib/loaders/loaders_without_authentication/positron.js

This changes that last arg to the loaders/factory to be an object, including the request id and user agent, vs having it just be the user agent. This way, (hopefully!), if we want to add another option, we don't have to keep modifying the signature all the way around.
Closes https://github.com/artsy/metaphysics/issues/937

@sweir27 => Propagate original user agent, and append with Metaphysics

---

src/lib/loaders/loaders_with_authentication/gravity.js
src/lib/loaders/loaders_without_authentication/gravity.js
src/schema/__tests__/users.test.js
src/schema/index.js
src/schema/users.js

- Adds an endpoint for Users to query by [:ids]
- Adds gravityLoader for Users
Wasn't completely sure that I needed to use the authenticated loader here, but it seemed like the right idea for user info.  We are passing in the user access token in positron's fetch, so I'm assuming that will be enough to get what we need.  (When I run the query on the local version, I get `"Not authorized"` error.

@mzikherman => Users endpoint/schema

---

src/lib/apis/fetch.js

Thank you for catching this, this modifies the passed-in options which are later used in the throttled cache refresh call.

@alloy => [HotFix] Clone api options to avoid always injecting a `headers` key

---

Dockerfile

Looking into DNS resolution errors from Metaphysics, I came across [hints](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues) that Alpine may be the source of the problem.  Try the base Debian image instead of Alpine.  This will significantly increase the image size, but may fix our issues:
- https://sentry.io/artsynet/metaphysics-production/issues/485726406/?query=is:unresolved
- https://sentry.io/artsynet/metaphysics-production/issues/486003936/events/16130527608/
cc @mzikherman

move from Alpine to Debian base image

---

src/schema/__tests__/partner.test.js
src/schema/partner.js

Some client is consistently requesting this, over a year since it was removed from the schema (and all Artsy clients). We can't figure out where it's coming from (and it _is_ raising errors in Sentry and returning 400), so let's be good schema stewards and remain backwards compatible.

@joeyAghion => Add is_limited_fair_partner for backwards caompatability

---

hokusai/production.yml
hokusai/staging.yml

Use the [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) to scale metaphysics-web in response to load.
Also use the "hard" `requiredDuringSchedulingIgnoredDuringExecution` `nodeAffinity` selector to ensure these pods are always scheduled on `tier=foreground` nodes, and if resource is unavailable, prompt the [cluster autoscaler](https://github.com/artsy/substance/pull/77) to scale up this node group.
Staging: `hokusai staging update`
Production: `hokusai production update`
cc @alloy @saolsen

#migration require pod execution on foreground nodes and autoscale deployment

---

src/lib/loaders/loaders_with_authentication/gravity.js
src/schema/index.js
src/schema/sale/__tests__/end_sale_mutation.test.js
src/schema/sale/end_sale_mutation.js
src/schema/sale/index.js

In order to enable users in prediction to [end a sale](https://github.com/artsy/prediction/pull/528) a Metaphysics mutation needed to call gravity api [endpoint](https://github.com/artsy/gravity/blob/6628b39cf30c1d4a7f83c3168048622fd8deb85e/app/api/v1/sales_endpoint.rb#L125).
(paired with @ashfurrow and @bhoggard)

Adds mutation for ending a sale

---

package.json
src/lib/mergeSchemas.js
yarn.lock

v3 should have a fix for interface and union fragments with fragment
spreads

Update to v3 of graphql-tools pre-release

---

src/schema/me/__tests__/recently_viewed_artworks.test.js
src/schema/me/recently_viewed_artworks.ts

whoopsie, an empty array will just fall back to fetching `/artworks`

@mzikherman => Make sure to return an empty connection when RVA is empty

---

src/schema/me/__tests__/recently_viewed_artworks.test.js
src/schema/me/recently_viewed_artworks.ts

Just return the inputted `artwork_id`, to match the stitched Gravity mutation, so we can use them exactly the same by clients, whether or not stitching is enabled.

@mzikherman => Match stitched mutation output

---

src/schema/__tests__/partner.test.js
src/schema/partner.js

Partner Merchant account might not be crated for partner at all or it might not be configured properly. In case of merchant account never created for partner Lewitt GraphQL request returns `Document not found` error when queried for merchant account, which I think is correct. However metaphysics should handle it with setting `acceptsCardPayments` to false rather than rethrowing the error.
Not sure exactly how to properly test it but the logic is correct I believe.

set credit_card_enabled to false if partner_product_merchant_account not found for partner

---

src/lib/attributionClasses.js
src/schema/artwork/__tests__/artwork.test.js

One of the changes requested by this latest artwork info design update is to make attribution link not incluse `.`, like dot at the end should not be underlined. I think the easiest way to achieve that is not to include `.` as part of link and just insert it at the end.

removing periods from info and short description for attribution class

---

src/schema/me/__tests__/order/update_order_mutation.test.js
src/schema/me/order/update_order_mutation.js

Per your comment on my previous PR!
We need to be able to pass `reserve: true` when we update an order.

@joeyAghion => allow reserve to be passed when updating an order

---

src/schema/home/context.js
src/schema/home/home_page_artwork_modules.js
src/schema/home/results.js
src/schema/home/title.js

Pretty simple, if `recently_viewed_works: true` is a value that Gravity returns for the initial query as to which 'modules' (aka rails/sections) on the homepage to show, from https://github.com/artsy/gravity/blob/846fdd4798b92c6679aad29be3901014f76a297c/app/api/v1/me_modules_endpoint.rb , then you can request is in the usual way:
This should be safe to merge, I'll make the Gravity change be dependent on a lab feature/flag so that we can see how it looks in Emission/Force. I don't think it will break those b/c AFAIK they work by 'opting-in' to rails: https://github.com/artsy/force/blob/45de3408bb8fa55eb6d517fc7f7cebfcc4e2ad73/src/desktop/apps/home/queries/initial.coffee#L6 and similarly in Emission

@damassi => Support recently viewed artworks homepage rail

---

src/lib/loaders/loaders_with_authentication/gravity.js
src/schema/me/__tests__/bidder_position.test.js
src/schema/me/bidder_position.js
src/schema/me/bidder_position_status.js
src/schema/me/index.js

Fixes: https://artsyproduct.atlassian.net/browse/PURCHASE-98
Makes it possible to send queries like
```
query {
me {
bidder_position(id: "5ae1df168b3b8141bfc32e5d") {
processed_at
}
}
}
```
and check to see if the bidding position is successfully created.

Query Bidder Position by ID

---

src/schema/me/__tests__/bidder_position.test.js
src/schema/me/bidder_position.js

Missed to update loader from `bidderPosition` to `meBidderPosition` in all places in the previous PR: https://github.com/artsy/metaphysics/pull/1023
This PR fixes that.

#quickfix for bidder_position

---

src/lib/loaders/loaders_with_authentication/gravity.js
src/lib/loaders/loaders_without_authentication/gravity.js

This just adds the `userLoader` to loaders without authentication. We discovered last week that we don't need a user token to make this request but simple an app token.

@l2succes: adds userLoader to loaders without authentication

---

.env.example
src/schema/artist/index.js

Editorial wants to restrict the articles attached to artist pages -- this adds the option to include an `in_editorial_field` boolean on the articles query to positron.  
Also updates the env.example to use the correct positron staging url.

Query articles from editorial feed on artists

---

src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.js

This PR is follow-up from [a discussion in eigen](https://github.com/artsy/eigen/pull/2609#issuecomment-388435489) about routing the new bid flow.
This PR adds a new, optional parameter to the `sale_artwork` field in the `Artwork` type. Theoretically, but not in practice, artworks can be in more than one sale; metaphysics simply returns the sale artwork from the first sale, which could cause problems down the road.

Adds optional arg to sale_artwork field.

---

src/schema/me/__tests__/bidder_position.test.js
src/schema/me/bidder_position.js
src/schema/me/bidder_position_messages.js
src/schema/me/bidder_position_mutation.js
src/schema/types/bidder_position_result.js

`bidder_position_mutation` returns status and error message when an error occurs at the time of placing the bidder position. After that the client (emission) polls MP to check if the bidder position is processed and then if it is active and met reserve.
This PR adds `status` and `message_header` and `message_description_md` to `bidder_position`  query returns similar to `bidder_position_mutation` to make the flow consistent on the client, also move the logic of checking bidder position status to MP.
**Note:** `bidder_position` (https://github.com/artsy/metaphysics/pull/1023) query is pretty new and hasn't been used on production yet so it is okay to change its return type.
sample query:
```
{
me {
bidder_position(id: "5af9fce35acaa60020dbeeed") {
status
position {
processed_at
is_active …
```

bidder_position returns status/message 

---

package.json
src/lib/loaders/api/loader_with_authentication_factory.js
src/lib/loaders/api/loader_without_authentication_factory.js
src/lib/loggers.js
src/schema/collection.js

We want the `error` logs to be enabled in production and staging, so it should really only log unexpected/severe situations.

[debug] Add `warn` log level and make some logging less severe.

---

src/lib/cache.js

The docs aren’t entirely clear on whether or not the global event
listener on the client will always log errors or truly only when
individual commands do not have callback handlers attached. However,
this code in the library does seem to suggest that the latter is the
case: https://github.com/NodeRedis/node_redis/blob/9bb1454ca183f4132dbec8d12d010f28303cdebd/lib/utils.js#L87-L93

[debug] Make sure we log errors comming from `redis.get()`

---

src/lib/__tests__/cache.test.js
src/lib/cache.js

This simplifies the code a little, but most importantly it makes it so that the promise rejects once the timeout passes but we still get logs if the read passed the `CACHE_QUERY_LOGGING_THRESHOLD_MS` so we still know how long long reads are taking.

[debug] Still log cache read duration even if timed out.

---

src/lib/__tests__/graphqlErrorHandler.test.js
src/lib/__tests__/graphqlTimeoutMiddleware.test.ts
src/lib/graphqlErrorHandler.js
src/lib/graphqlTimeoutMiddleware.ts

Gotta clean up after ourselves!
Also log all error messages (to paper trail) that don’t get reported to Sentry.

[graphqlTimeoutMiddleware] Clear timers.

---

package.json
yarn.lock

The latest release fixes a bunch of stuff: https://github.com/DataDog/dd-trace-js/releases
Hopefully, we'll find it improves aggregation of the spans into a single trace.

upgrade to dd-trace 0.2.1 to hopefully fix trace propagation

---

src/lib/cache.js

Thought not a fire any longer, we are still experiencing [cache timeouts](https://papertrailapp.com/groups/3675843/events?q=host%3Ametaphysics-web%20Cache).
I want to log some diagonistic info about the redis client when we hit the timeout, particularly whether the internal [should_buffer](https://github.com/NodeRedis/node_redis/blob/master/index.js#L118) flag has been set, and the length of the various internal queues particularly the [pipeline_queue](https://github.com/NodeRedis/node_redis/blob/master/index.js#L129).
The `should_buffer` flag is going to be set to `true` when the socket's [stream write method](https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback) returns `false`, i.e. when
> Returns: <boolean> false if the stream wishes for the calling code to …

log redis client info on cache timeouts

---

src/lib/cache.js

Follow-up to https://github.com/artsy/metaphysics/pull/1077 - I want to see the position of the timed-out command within the redis client's [command_queue](https://github.com/NodeRedis/node_redis/blob/master/index.js#L127)

dump client command queue to error logs

---

src/lib/loaders/loaders_with_authentication/gravity.js
src/schema/__tests__/causality_jwt.test.js
src/schema/causality_jwt.js
src/schema/sale/index.js

https://artsyproduct.atlassian.net/browse/SELL-530
- Adds a new `external_operator` role to the Causality JWT. Checks if aspiring `OPERATOR` is first an admin; if not, checks whether or not they qualify to be an `external_operator`. External operators have access to the partner managing the sale. 
- Adds `mePartnersLoader` that fetches the partners the user currently has access to. Depends on https://github.com/artsy/gravity/pull/11736.
- Adds access to partner object in sale schema so that we can fetch the sale partner's ID in Prediction.

Create external operator role in causality_jwt

---

src/schema/__tests__/causality_jwt.test.js
src/schema/causality_jwt.js

Causality expects a JWT with `externalOperator` instead of `external_operator`, so we're renaming to match what Causality expects.

Rename external_operator to externalOperator

---

hokusai/production.yml
hokusai/staging.yml

We've seen pods get into a bad state, with high latency and high memory usage. As a mitigating measure, we [discussed](https://artsy.slack.com/archives/CA8SANW3W/p1528376895000157) lowering the memory limit, in order to kill those runaway pods earlier in their degradation.
This brings the `production.yml` in line with `staging.yml`. Both of these were part of the original transition (https://github.com/artsy/metaphysics/pull/968). This has been applied already (via `hokusai production update`), but is worth monitoring for a bit.
CC @izakp

@acjay: Lower production memory limit to kill runaway pods earlier

---

hokusai/production.yml
hokusai/staging.yml

We've been running between 5 and 6 pods since the downtime the other week, which led to the cache investigation.  The spec was still set to the old min replicas and this is definitely insufficient.
Let's throw more resource at it.  We have the capacity.
`hokusai staging update && hokusai production update`
cc @joeyAghion @alloy @mzikherman

#migration scale up replicas

---

src/lib/loaders/loaders_with_authentication/gravity.js
src/schema/__tests__/order.test.js
src/schema/index.js
src/schema/order.js

Adds endpoint to query an Order by ID to be used from volt to show user orders in volt.
Sample Query:
```
query {
order(id:"5b185c215070dc001f2af229") {
id 
telephone
email
line_items {
quantity
artwork {
id
title
artist(shallow: true) {
name
}
}
edition_set {
id
is_for_sale
is_sold
price
is_acquireable
edition_of
}
partner {
id
}
partner_location {
id
}
shipping_note
sale_conditions_url
}
item_total {
amount
display
}
shipping_address {
name
street
city
region
postal_code
country
}
}
}
```

Endpoint for retrieving an order

---

hokusai/production.yml

This isn't intended to be more than a temporary measure, but I wanted to commit the change I made locally (and applied to production).
Note that updating the deployment's YAML via the kubernetes dash _or_ using its built-in dialog to "scale" the deployment or the replica set didn't persist across refreshes.

@acjay: Temporarily boost replicas

---

index.js

Collecting express metrics as middleware was creating a new route for each GraphQL query.  Not sure why the query params were collected - the express [getRoute helper](https://github.com/idanto/express-node-metrics/blob/master/src/middleware.js#L32) is called in the middleware module of the metrics library.
In any case I am hesitant to throw this out on production - let's just start with basic Node and GC metrics before re-enabling this (or possibly just writing our own middleware function).

Only collect and expose process metrics

---

src/schema/me/__tests__/index.test.js
src/schema/me/index.js

We tracked the bug this morning to the fact that we were checking for `has_qualified_credit_cards` in one place, but only checking whether the user had credit cards at all (qualified or not) in another place.
This adds a field for us to check whether or not a user has a credit card on file at all.

Add field for returning whether user has credit cards at all

---

src/lib/cache.js

move redis client info to verbose - drop logging full command queue as it's too noisy
cc @alloy @mbilokonsky

hotfix - logging redis client info

---

src/schema/__tests__/auction_results.test.js
src/schema/article.js
src/schema/artist/__tests__/index.test.js
src/schema/artist/index.js
src/schema/artwork/index.js
src/schema/auction_result.js
src/schema/fields/pagination.js

This is on top of https://github.com/artsy/metaphysics/pull/1087 so there's a large diff which will go away, the only new commit adding that is: https://github.com/artsy/metaphysics/commit/8461bc7fc84756f99109261d538b7b81b8ae38b4
It's relatively straightforward, the existing `articles` field under artist (currently in use) just returns a flat list of articles, so I added a new proper connection. `auctionResults` already was a connection so I just added the page cursor info.
Tested it locally via GraphiQL, works! 👍 
I'll add shows and related artists similarly, but I wanted to refactor those a bit (since they will require new connection types, as currently they are just flat lists).

@damassi => Add `articlesConnection` and enable cursor info on `auctionResults`

---

src/lib/loaders/loaders_without_authentication/gravity.js
src/schema/artist/__tests__/carousel.test.js
src/schema/artist/__tests__/index.test.js
src/schema/artist/carousel.js
src/schema/artist/index.js
src/schema/artist/shows.js
src/schema/artwork/context.js
src/schema/artwork/index.js
src/schema/show.js

This adds a proper connection for shows with the cursor info we added for articles, auction results, and filter artworks.
I refactored a bit- moved all the 'related shows' stuff out of the artist index, and into its own file.

@damassi => Show pagination

---

src/schema/artist/__tests__/related.test.js
src/schema/artist/index.js
src/schema/artist/related.js

This should be the last pagination we need, for `main` and `contemporary` related artists.
We already had a `related` field for an artist w/ `suggested` artists, so I added `main` and `contemporary` there as well.
```
artist {
related {
suggested {
...
}
main {
...
}
contemporary {
...
}
}
}
```

@damassi => Related artists pagination

---

hokusai/production.yml
hokusai/staging.yml
index.js
src/index.js
src/lib/cache.js

Simple health check endpoint that tests the Redis connection.
I want to also test that the application is completely bootstrapped but don't know how to go about this.  (Sometimes when I start the node process, the first time I hit an endpoint I get a `200` but the body is `Cannot GET /` - the next time I hit it I get the GraphiQL interface.
@alloy is there some lazy loading going on when `src/index.js` is imported via `index.js`?  The `startApp()` [function](https://github.com/artsy/metaphysics/blob/master/src/index.js#L67) in the former file appears to be `async`.
Ideally I want the app to be completely loaded and ready to serve traffic before the the `/health` endpoint returns `200`
Finally, if we want to react on a certain metric we can take the pod out of service by evaluating the …

implement health check

---

hokusai/production.yml
hokusai/staging.yml

Express [force-ssl middleware](https://www.npmjs.com/package/express-force-ssl) is causing the health check route to return a 301 redirect when hit via the Kubernetes readiness probe.
The middleware doesn't appear to allow you to disable for certain routes.  Until we fix use a tcp probe on port 3000 for a readiness check.

hotfix - use tcp health check to bypass force-ssl middleware

---

hokusai/production.yml
hokusai/staging.yml

Set `X-FORWARDED-PROTO:https` header to bypass redirect to https on the health check

Fix Http health checks

---

src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.js

This I *think* will allow us to rely only on `sale_message` and `is_inquireable` to display all the variations of availability+price from those designs: https://app.zeplin.io/project/5b113f413ede4bb10dbfdc42/screen/5b114000413156335e285483
Should not affect any current force displays because we are checking availability there directly before looking as `sale_message`

updated sale_message to include Permanent Collection

---

src/lib/__tests__/cache.test.js
src/lib/cache.js

Making an experiment to split cache reads and writes onto two separate clients, each with their own connection pools - in this way ensure that no `SET` or `DEL` commands can be interleaved with `SET` commands.
cc @acjay @alloy

#experimental split cache client to reader and writer clients

---

src/lib/stats.js

@mbilokonsky lots of good stuff from this appmetrics project if you want to do some research into what would be useful to collect then send to Dogstatsd - another thing we might try (and I think @joeyAghion wanted to do) is to send a signal like `USR2` to Node to get it to dump out VM info when a pod / process is in a "bad state" - implemented by https://www.npmjs.com/package/node-report

hotfix - disable unused appmetric integrations

---

src/lib/stats.js

`loop` gives us actual timings where `eventLoop` gives us latencies. This PR adds loop timing data to our log, which also includes CPU usage both in user land and in system land during the measured period.
I'm writing this all to histograms, which feels right but may not be the most useful?

add loop metrics

---

src/schema/__tests__/auction_results.test.js
src/schema/artist/index.js
src/schema/auction_result.js

So, since we're now displaying auction results completely from Diffusion, there's a couple things we still needed in the schema.
- estimate range display
- proper connection populating of `hasNextPage` and `hasPreviousPage` (for supporting prev/next pagination)

@damassi => Auction result tweaks for integration into new page

---

package.json
src/lib/__tests__/apis/fetch.test.ts
src/lib/apis/fetch.js
src/lib/cache.js
yarn.lock

This reverts commit 9a1d8bdcc4a1fa494fa8c3f88203b7afb534eb89, reversing
changes made to e331386e91fee444057fe7efa9a789cdfab5da9b.
See https://github.com/artsy/metaphysics/pull/1108
Deploying this to production caused a spike in CPU / event loop latency and memory usage
cc @alloy @mbilokonsky @orta @acjay

Revert "Merge pull request #1108 from izakp/fea-async-json"

---

src/schema/__tests__/auction_results.test.js
src/schema/artist/__tests__/index.test.js
src/schema/artist/index.js
src/schema/artist/shows.js
src/schema/fields/pagination.js

This adds two last pieces of information we need:
- includes `totalCount` in the connection metadata, which we need to display on the 'Auction Results' tab. We do get a total back when we're doing artwork filtering, but that's via an aggregation which is specific to artwork filtering, so I chose to add this as a connection metadata field (next to `pageInfo`, `edges`, etc.). Seems reasonable that clients may want this more generally. Then, I augmented the auction results connection resolver to include that.
- Injects our own computation for `hasNextPage` and `hasPreviousPage` (which enables the Prev/Next in pagination), analogous to what we did for auction results, but for shows.

@damassi => Last connection pieces of info for artist page

---

src/lib/__tests__/graphqlTimeoutMiddleware.test.ts
src/lib/graphqlTimeoutMiddleware.ts
src/test/helper.js

Changes here cause us to lose HTTP / Memcached metrics and processed exhibited sawtooth memory growth.
This was in production from today, June 21st @ 10:38 UTC (see image tag `production--2018-06-21--10-38-53`) until reverted @ 12:00 UTC (see image tag `production--2018-06-21--12-00-31`)
Other metrics appear unchanged - overall query latency / eventloop latency seemed unaffected.
See:
https://app.datadoghq.com/apm/service/metaphysics.graphql-query/graphql.query
https://app.datadoghq.com/apm/service/metaphysics.memcached/cache
https://app.datadoghq.com/apm/service/metaphysics.http-client/http.request
https://app.datadoghq.com/dash/635153
Would advise taking another pass at this but first implementing GC metrics collection and comparing before / after

Revert changes to GraphQL timeout middleware

---

package.json
src/__tests__/integration.test.ts
yarn.lock

This adds a test that runs a query at express level, instead of directly against the known schema. This means it'll run though everything set up in app.js.
Also amends https://github.com/artsy/metaphysics/pull/1122 as eslint can't parse ts files

Adds an integration test that lives almost entirely outside of the schema resolution

---

src/schema/artist/__tests__/related.test.js
src/schema/artist/related.js

Added these two related artists fields (to be able to use them as a connection w/ pagination), but actually they're exactly the same thing, just a different 'kind' of related artists.
So combines them into one, like:
```
artist(id: "andy-warhol") {
related {
artists(kind: CONTEMPORARY) {
...
}
}
}
````

@damassi => Combine main/contemporary related artists

---

src/lib/__tests__/apis/fetch.test.ts
src/lib/apis/fetch.js
src/lib/http_error.js

We [construct an error message](https://github.com/artsy/metaphysics/blob/597405d0678e941948275c006cb256acb343eccd/src/lib/apis/fetch.js#L32-L35) based on the request URI and the response body and assign it to the error object. This is most useful when debugging in a client like GraphiQL, but sometimes we [split the error message back](https://github.com/artsy/metaphysics/blob/597405d0678e941948275c006cb256acb343eccd/src/schema/me/bidder_position_mutation.js#L50-L51) within Metaphysics to generate a more helpful error message for the end-user. We should not have to do this as you already have the response in place.
This PR updates the `fetch` function to assign the response body to the `HTTPError` object so we will gain direct access to the body.

Inject response body to HTTPError whenever possible

---

src/schema/__tests__/auction_results.test.js
src/schema/fields/__tests__/pagination.test.js
src/schema/fields/pagination.js

As discussed, we want to settle on `first/after` style 'forward' pagination, so as to benefit from Relay caching.
We already do this when clicking 'Next', or when clicking on any page in a pagination bar. However, we were doing 'backward' pagination using `last/before` when clicking 'Previous', so we weren't benefiting from any caching (even if you had already loaded that page using forward pagination).
This adds a specific `previous` entry into the cursor metadata, which will enable 'Prev' pagination to use the same `first/after` values and save that call. Thanks for pointing this out!

@damassi => Add cursor info for previous page, for better implementation of Prev 

---

src/schema/me/__tests__/bidder_position.test.js
src/schema/me/__tests__/bidder_position_mutation.test.js
src/schema/me/bidder_position_messages.js

Now that we have https://github.com/artsy/emission/pull/1083 in and we should update the error descriptions for `BidderPositionResult`. I confirmed the `\n` syntax adds a line break properly. Let me know if there's any feedback!

Properly format error description for BidderPositionResult with '\n'

---

src/lib/stats.js

- Adds memory and GC metrics measured by Node's VM
- Only send metrics in production environments - change tagging to match `pod_name` rather than `hostname` so as to match metrics collected by the kubernetes integrations

Fea custom metrics

---

src/schema/artwork/index.js
src/schema/edition_set.js
src/schema/saleable.ts

Yay, our first real interface!
I’m not sure why the `EditionSet` type is called like that, isn’t each an entry in the set? Anyways, after thinking about `Edition`, `Piece`, etc for a while, I figured I’d go with an adjective form for interfaces as can be found in various examples, e.g. [`Searchable`](https://medium.com/the-graphqlhub/graphql-tour-interfaces-and-unions-7dd5be35de0d). Obviously I then had to choose between the various flavours of English (sellable, saleable, scalable) and settled on the one that seemed the most used in both English and Simplified (US) English.
----
This now allows you to have a fragment on `Saleable` and query any type that implements it:
```graphql
{
artwork(id: "banksy-flower-bomber-by-brandalism") {
...Piece
edition_sets {
...Piece
}
}
}
fragment Piece …
```

[Saleable] Add interface to Artwork & EditionSet.

---

src/data/exchange.graphql
src/schema/ecommerce/types/order.js
src/test/fixtures/gravity/order.json

- `item_total_cents` was [renamed](https://github.com/artsy/exchange/pull/45) to `items_total_cents` in Exchange, reflect that change here in MP
- Update `exchange.graphql` to reflect latest changes

Update exchange.graphql and fix itemsTotalCents

---

src/__tests__/integration.test.ts
src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.js
src/schema/sale/__tests__/index.test.js
src/schema/sale/index.js

Depends on https://github.com/artsy/gravity/pull/11796
This example still uses the incorrect `Artwork.sale` field which assumes that there’s only ever 1 live sale, but the `Artwork. bidderStatus` schema addition in this PR will correctly return a list, which for now the client should just select the first entry from.
```graphql
{
artwork(id: "yohei-imamura-self-portrait") {
sale {
registrationStatus {
qualified_for_bidding
}
}
bidderStatus(live: true) {
is_highest_bidder
}
}
}
```
```json
{
"data": {
"artwork": {
"sale": {
"registrationStatus": {
"qualified_for_bidding": true
}
},
"bidderStatus": [
{
"is_highest_bidder": true
}
]
}
}
}
```

[WIP] Add user fields to sale and artwork bidding status

---

src/lib/stitching/exchange/link.ts
src/schema/__tests__/ecommerce/create_order_mutation.test.js
src/schema/__tests__/ecommerce/submit_order_mutation.test.js
src/schema/ecommerce/create_order_mutation.js
src/schema/ecommerce/submit_order_mutation.js
src/schema/ecommerce/types/order.js
src/schema/ecommerce/types/order_return.js
src/schema/index.js

MP mutation endpoints that call express mutations to [create](https://github.com/artsy/exchange#create-an-order) or [submit](https://github.com/artsy/exchange#submit-an-order) an order.
I am not completely familiar with MP filename conventions so I wasn't sure if these mutations need to be under `/me/` path since they are triggered by a user from force, or better grouped with other e-commerce endpoints where it is now?
* create
```
mutation {
createOrder(input: {
partnerId: "111",
userId: "111",
currencyCode: "usd",
lineItems: [{
artworkId: "111",
quantity: 1
priceCents: 300000
}]
}) {
result {
order {
id
code
currencyCode
state
partner {
id
name
}
user {
id
email
}
lineItems {
edges {
node {
artwork {
id
title
}
}
}
}
}
}
}
``` 
* submit
```
mutation {
submitOrder(input: {
orderId: …
```

Ecommerce Mutations for Users

---

src/schema/ecommerce/order.js
src/schema/ecommerce/orders.js

Paired with @ashkan18 to return errors coming from Exchange to client.
Sample result when there is an error:
```
{
"errors": [
{
"message": "Not permitted",
"locations": [
{
"line": 158,
"column": 3
}
],
"path": [
"orders"
],
"stack": "Not permitted\n\nGraphQL request 
...
}
],
"data": {
"orders": null
},
"requests": {
"gravity": {
"requests": {
"me/token?client_application_id=5b228bb2f7052934876c02cb": {
"time": "0s 146.66ms",
"cache": false
}
}
}
},
"requestID": "ea5cba50-7e27-11e8-a88b-8318a4ff5156"
}
}
```

WIP: Returns order query errors to client #minor

---

src/schema/__tests__/ecommerce/create_order_mutation.test.js
src/schema/__tests__/ecommerce/order.test.js
src/schema/__tests__/ecommerce/orders.test.js
src/schema/__tests__/ecommerce/submit_order_mutation.test.js
src/schema/ecommerce/create_order_mutation.js
src/schema/ecommerce/order.js
src/schema/ecommerce/orders.js
src/schema/ecommerce/submit_order_mutation.js
src/test/fixtures/exchange/order.json
src/test/fixtures/exchange/orders.json
src/test/fixtures/results/sample_order.js

`itemsTotalCents` was added in https://github.com/artsy/metaphysics/pull/1144 but it was not added to queries made to Exchange for fetching it, it was always null because of that.
Add it :)
Add other price related fields, tax, shipping etc.

Fix null itemsTotalCents

---

src/lib/loaders/loaders_with_authentication/gravity.js
src/schema/__tests__/ecommerce/create_order_mutation.test.js
src/schema/__tests__/ecommerce/order.test.js
src/schema/__tests__/ecommerce/orders.test.js
src/schema/__tests__/ecommerce/submit_order_mutation.test.js
src/schema/artwork/index.js
src/schema/ecommerce/types/order_line_item.js

`artworkLoader` which was previously used was under `loaders_without_authentication` so it was receiving `artwork` object visible to  regular users without `inventory_id`. Suggestions about naming and better ways of handling this case is welcomed.

Adds inventory id to order return

---

src/schema/__tests__/ecommerce/create_order_mutation.test.js
src/schema/__tests__/ecommerce/order.test.js
src/schema/__tests__/ecommerce/orders.test.js
src/schema/__tests__/ecommerce/submit_order_mutation.test.js
src/schema/artwork/index.js
src/test/fixtures/results/sample_order.js

Missed a piece in the [previous PR](https://github.com/artsy/metaphysics/pull/1155) to rename `inventory_id` to `inventoryId`. To make up for that adding it to tests.

inventory_id -> inventoryId, 2nd attempt

---

src/schema/me/__tests__/bidder_position.test.js
src/schema/me/__tests__/bidder_position_mutation.test.js
src/schema/me/bidder_position_messages.js

#superminor we weren't using smart quotes in a few places here!
Looks like there are some extra white space changes which I think should be fine (just from prettier I'd guess).

@sepans => use smart quotes when returning bidder position messages

---

src/schema/me/lot_standing.js

The gravity endpoint supports an optional `sale_artwork_id` param, and I'd like to use this from emission's side (since we'll be scoped by sale artwork at the point of entering the bid flow).
It means we don't get fancy validations around the inputs. Not sure if there's a way to say `(artwork_id && sale_id) || sale_artwork_id` with the types there.

Lot standings endpoint supports inputting the sale_artwork_id 

---

src/schema/__tests__/sale_artwork.test.js
src/schema/me/lot_standings.js
src/schema/sale_artwork.js

I'm opening this so we can start to have a discussion... _code talks_.
The problem I'm trying to solve is:
- in multiple places at Artsy (i.e. in emission and in force/reaction right now) we need to show users a dropdown list of increments that they can bid with. The logic for determining where to _start_ this increments list lives [here](https://github.com/artsy/force/blob/master/src/desktop/apps/artwork/components/auction/templates/bid.jade#L3-L4) right now, but as I'm working on adding it to emission it would live there as well.
This proposal moves the logic upstream to metaphysics, where it could potentially be re-used by force/reaction (I'm not sure if this has been implemented yet for the new artwork page, but presumably it would have to be).
Things I'm not sold on:
- …

@mzikherman => Adds my_increments to sale_artwork

---

src/schema/__tests__/sale_artwork.test.js
src/schema/sale_artwork.js

While testing this out again, I noticed two minor things:
- If you attempt to pass `useMyMaxBid: true` but aren't logged in, we'd get an error from `lotStandingLoader` not existing. I updated this to check if that's there-- if not we return the generic increments.
- I think we can actually update the logic to consider your `leading` status (leading means you're the highest bidder on the lot-- I don't way "winning" since that has other implications around the reserve). More explanation below...
Current logic:
- If you have no bids on the lot, we return increments beginning at the `minimum_next_bid_cents`
- If you have a bid on the lot but aren't _leading_, we return increments beginning at the `minumum_next_bid_cents`. In this case, your max bid must be lower than the `minimum_next_bid` or …

Updates logic around increments when useMyMaxBid is true

---

src/schema/me/__tests__/bidder_position.test.js
src/schema/me/__tests__/bidder_position_mutation.test.js
src/schema/me/bidder_position_messages.js

Per our mocktion yesterday. This messaging can be misleading.

Remove the "bid again to take the lead" message from the bidder position mutation

---

src/lib/__tests__/gravityErrorHandler.test.js
src/lib/graphqlErrorHandler.js
src/lib/gravityErrorHandler.js
src/schema/me/__tests__/create_credit_card_mutation.test.js
src/schema/me/create_credit_card_mutation.js

Marking this a WIP since I want to get some feedback before I write tests.
This represents yet another version of error handling... informed heavily by [this discussion](https://github.com/facebook/graphql/issues/298).
Some thoughts:
- For many mutations, the errors are known and useful to clients. We want to be able to present these in a first-class way, so it's beneficial to be able to do some formatting at the metaphysics level.
- It seems that there's a difference between errors (that should be handled as actual errors) and known validation failures and things like that. Overloading the `errors` field to include both doesn't seem quite right.
This solution allows us to query for both successes and failures in a first-class way:

Adds union type for returning success and failure on credit card mutation

---

src/schema/artist/__tests__/current.test.js
src/schema/artist/current.js

There will be a sibling reaction PR shortly.
This PR aims to update the fields of the current event to match a little closer to what they are as opposed to the placeholders that were there previously. 
It also adds fields that were missing before... the fields should be
- image
- event status
- event name
- partner
- event details
- page (url to the event page)
Some tests should probably be added. I wasn't sure about some things... like if sales have partners associated with them. The designs actually don't show displaying a partner if it's an auction, but I'm not sure if that was intentional or if it was an oversight. 
Also, @mzikherman, I need to have a link to the show or sale... that's what the **page** field represents currently. I don't know that that's the best name for that field. …

Update fields of current event to match domain model

---

index.js
package.json
yarn.lock

There's a possibility that we're using features in bluebird that aren't available in the native implementation (and without types, we don't know) so I'm doing a run through - FWIW, tests all pass, including a single integration test.

Switch to the native promise in node

---

src/lib/loaders/loaders_without_authentication/gravity.js

Sale artworks have bid increments which change often, so we don't want to cache them. https://github.com/artsy/metaphysics/pull/1178 changed the sale artwork _root_ loader to not use the cache, but sale artworks accessed through the artwork schema were still being cached. Consider the following two ways to access the same information:
```graphql
{
artwork(id:"5b4de57ef0676200017a0b15")  {
sale_artwork {
minimum_next_bid {
display
}
}
}
sale_artwork(id:"5b4de57ff0676200017a0b1c") {
minimum_next_bid {
display
}
}
}
```
Even though they operate on the same model, they use different caching strategies. This PR would make them both uncached.
This is a fix for [PURCHASE-297](
https://artsyproduct.atlassian.net/browse/PURCHASE-297).

Uses uncached gravity loader for artworks' sale artworks

---

hokusai/production.yml
hokusai/staging.yml

Use the pod config `dnsPolicy: Default` to bypass internal DNS - this directly inherits `/etc/resolv.conf` from the host machine, and in our case in AWS it is set to:
```
nameserver 10.0.0.2
search ec2.internal
```
This will completely bypass the Kubernetes DNS service and use the AWS internal DNS resolvers - the pod will not be able to resolve other internal service names like `gravity-web` and `datadog`, but it will work around the known [ndots problem](https://rsmitty.github.io/KubeDNS-Tweaks/) and avoid redundant DNS queries for `api.artsy.net.default.svc.cluster.local` / `api.artsy.net.svc.cluster.local` / `api.artsy.net.ec2.internal` - without `ndots` specified, only domains without _any_ dots are treated as un-fully-qualified and the search domains are applied.
We do need to talk …

Workaround DNS issues - use default DNS resolvers inherited from the host machine

---

Dockerfile

https://github.com/artsy/metaphysics/pull/1182 is not working correctly on k8s because k8s sends a `SIGTERM` to PID 1 in the container on termination, which is by default `sh -c` which does not proxy signals to the process(es) it spawns.  `dumb-init` is designed to fix this problem as well as others arising from processes run as PID 1.

hotfix - use dumb-init to proxy signals correctly to node

---

Dockerfile
index.js
package.json
yarn.lock

Follows up on https://github.com/artsy/metaphysics/pull/1192 and https://github.com/artsy/metaphysics/pull/1182 - keepalive HTTP connections need to be destroyed otherwise server will not shut down.  Use https://www.npmjs.com/package/http-shutdown to destroy keepalive connections.
Also a fix in Dockerfile `CMD` syntax
cc @alloy @orta

hotfix - destroy keepalive HTTP connections on shutdown

---

src/lib/loaders/api/loader_with_authentication_factory.ts

I think we only want batching to be enabled on our data loaders when we can make the underlying data fetch as a batch. Otherwise, slowest response dominates the batch. Asking for a bunch of review just because I'm not sure whether the batching was intentional for reasons I'm overlooking.

dont batch data loaders that dont fetch in batch

---

hokusai/production.yml

This sets up a "green" production deployment to test against the current "blue" deployment with cache compression disabled (all env vars hardcoded in the kubernetes yaml spec override any pulled in from the config map (set with `hokusai [staging|prouduction] env`)
The deployment will create 2 replicas which will be targeted by the metaphysics service along with the existing replicas, and so will receive a proportional amount of the traffic (around 8% with the current metaphysics scaling parameters)
We will be able to compare metrics taken from this sample set to existing metrics as they will come up as separate "metaphysics-green" services set by `DD_TRACER_SERVICE_NAME`
Run `hokusai production update` to create the new deployment

#migration test cache compression in metaphysics-web-green deployment

---

hokusai/production.yml
hokusai/staging.yml

- Bump memory request for better scheduling
- Unbounded CPU limit (shouldn't ever really go over 1 as node is single-threaded so no need to cap it)
- Add `temperament: cpu-hog` label and an [anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity) scheduling rule for this label - Metaphysics pods will "repel" one another as well as any other pods with the `temperament: cpu-hog` label applied - this will mean that no two Metaphysics pods should ever be scheduled on the same host, and no Metaphysics pod should be scheduled on the same host of any [gravity-web pod](https://github.com/artsy/gravity/pull/11829) as it also uses this label.

Resource / Autoscaling tweaks - introduce cpu-hog label

---

src/schema/gene.js

This is breaking gene links on the new artist page. Our convention on these is to prefix with the slash.

@mzikherman => Correct href for genes

---

src/schema/ecommerce/orders.js
src/schema/ecommerce/types/orders_sort_method_enum.ts

Adds `sort` parameter to `orders` query. The param was there in exchange but not exposed through MP.
**Sample query:**
```
query sortedOrders {
orders(partnerId: "581b45e4cd530e658b000124", state: "SUBMITTED", sort: UPDATED_AT_ASC){
edges {
node {
state
id
stateUpdatedAt
stateExpiresAt
createdAt
updatedAt
}
}
}
}
```

Adds sort to orders query

---

hokusai/production.yml
hokusai/staging.yml

- remove extraneous `default` namespace from pod template
- use `maxUnavailable` so as not to block rollouts
- adjust autoscaling params
- make cpu-pod scheduling a hard requirement to keep away from Gravity pods

update k8s deployments

---

src/schema/ecommerce/approve_order_mutation.js
src/schema/ecommerce/create_order_with_artwork_mutation.js
src/schema/ecommerce/fulfill_order_at_once_mutation.ts
src/schema/ecommerce/reject_order_mutation.js
src/schema/ecommerce/set_order_payment_mutation.ts
src/schema/ecommerce/set_order_shipping_mutation.ts
src/schema/ecommerce/submit_order_mutation.js

In cases where running a mutation causes an error which is not coming from exchange (like authentication errors from gravity)
the error is in `result.errors` and not in `result.data.<query/mutation-name>.errors` so 
```
const { order, errors } = result.data.<query/mutation-name>
```
throws a javascript runtime error in metaphysics and client receives the ambiguous error message: *Cannot match against 'undefined' or 'null'.*
This change saves developers debugging time for now, while we are figuring out the best pattern to handle graphql errors for order mutations.
(cc @orta)

Returns non-exchange order errors to client.

---

src/schema/artist/statuses.js

Right now articles should only appear if `in_editorial_feed` is `true`; however, in code that determines whether we should show the Articles tab, this condition isn't accounted for, leading to a situation where the tab appears yet no articles are rendered.

@mzikherman => [BUGFIX artist] Fix issue where statuses shows article erroneously

---

src/lib/loaders/loaders_with_authentication/gravity.js
src/schema/__tests__/credit_card.test.js
src/schema/__tests__/ecommerce/order.test.js
src/schema/credit_card.js
src/schema/ecommerce/order.js
src/schema/ecommerce/types/order.ts
src/schema/index.ts
src/schema/me/create_credit_card_mutation.js
src/test/fixtures/exchange/mockxchange.js
src/test/fixtures/exchange/order.json
src/test/fixtures/results/sample_order.js

Since this PR: https://github.com/artsy/gravity/pull/11861, a user can view their credit card information on an order.
This updates the MP schema to return credit card information as part of the root (mostly useful right now for testing), and as part of an `order`. 
```graphql
query {
credit_card(id: "test123") {
brand
}
}
```
```graphql
query order {
order(id: "130") {
createdAt
id
creditCard {
id
brand
last_digits
}
}
}
```

Adds creditCardLoader to return creditCard information in root and ecommerce orders

---

README.md

The instructions for getting a local GraphiQL app setup were tripping me up and @alloy suggested I do this process instead, and that we should update the README to match.

Update access token retrieval instructions

---

src/index.js
src/lib/checkForProblematicArtistQuery.ts

Middleware that will log out and return a 500 immediately if the old artist page query is being used (Force was deployed yesterday).

@alloy => Log out if old artist query is being used

---

hokusai/production.yml
hokusai/staging.yml

Depends on https://github.com/artsy/substance/pull/103 - Do not merge this PR until it is
Run [goreplay](https://goreplay.org/) as a sidecar container with Metaphysics (containers in the same Pod share a network interface as if they were on the same host) - scrape traffic and forward to `goreplay.stg.artsy.systems` / `goreplay.prd.artsy.systems` for later reply.
Enabling / disabling traffic scraping and forwarding can be done by commenting out these changes, then running `hokusai [staging|production] update` (can't think of a good way enable / disable with an env var as running another container or not alongside MP is the cleanest deployment strategy)
After merging, sync your local `master` branch then run:
Staging: `hokusai staging update`
Production: `hokusai production update`

#migration add goreplay sidecar container and forward scraped traffic

---

hokusai/production.yml
hokusai/staging.yml

Reverts artsy/metaphysics#1212
This caused the `hokusai pipeline promote` task to fail oddly.

Revert "#migration add goreplay sidecar container and forward scraped traffic"

---

Dockerfile
hokusai/development.yml
hokusai/production.yml
hokusai/staging.yml
scripts/run-goreplay.sh

Follow-up to https://github.com/artsy/metaphysics/pull/1212
Install Goreplay inline and use the same image ref to run the sidecar container, working around the Hokusai guard that all containers in a Pod need to reference the same image tag.
As before, I'd let this sit on staging for a bit and check that everything is flowing correctly and it doesn't step on the toes of the normal application operation / ci pipeline before promoting to production and running the migration.
After merging, sync your local `master` branch then run:
Staging: `hokusai staging update`
Production: `hokusai production update`

#migration add goreplay sidecar container and forward scraped traffic... again

---

Dockerfile
scripts/create-heapsnapshot.sh

Take heapsnapshots and upload to s3 with https://docs.minio.io/docs/minio-client-complete-guide
Includes an update to dumb-init
Invoke `./scripts/create-heapsnapshot.sh` with env vars "AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_BUCKET and AWS_BUCKET_PATH"
Execute on a running pod - i.e. for pod `metaphysics-web-2612115710-645fg` (which you would find via `hokusai [staging|production] status`), and passing in your own AWS credentials to upload to the `artsy-data` bucket, `metaphysics/heapsnapshots/staging` path, you would run:
```
kubectl exec metaphysics-web-2612115710-645fg -- bash -c "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_BUCKET=artsy-data AWS_BUCKET_PATH=metaphysics/heapsnapshots/staging ./scripts/create-heapsnapshot.sh"
```
Snapshots …

Fea take heapsnapshots

---

scripts/create-heapsnapshot.sh

Snapshots are being updated prematurely (before the full snapshot file contents were written to disk) wait for the node process to release all `.heapsnapshot` file descriptors before moving to upload stage

bugfix in scripts/create-heapsnapshot.sh

---

index.js
src/index.js

Previously the app would start launching when the initial request comes
in, but not yet be finished launching, which would lead to the inital
request failing. This was especially painful when that initial request
was an introspection query being performed by e.g. GraphiQL and then
leading to the app not knowing the schema.

[dev] Make sure app is fully started on initial request.

---

src/schema/me/__tests__/followed_artists_artwork_groups.test.js
src/schema/me/followed_artists_artworks_group.js

expose a connection of artworks, vs just a flat list, for each notification group. This is for https://github.com/artsy/reaction/pull/1154

@damassi => Add artworksConnection to notification bundles, for use in grid component

---

src/schema/artwork/index.js

This still needs tests but PRing it here early to get some feedback.
The UI we need to create in force is like that:
https://app.zeplin.io/project/5ac6790d7f57100518f9ab44/screen/5b606192307c780395c2b26e
My thinking is that the best way to accomplish that is to return an object that stores label/details for each row and then metaphysics is going to be responsible for setting those properly. UI in force will just look if the object is there - display it - otherwise skip the row.

add data for Artwork condition box in force

---

src/index.js
src/lib/loaders/__tests__/request_id.test.js
src/lib/requestIDs.js

Set the `X-Forwarded-For` [header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#Directives) on downstream requests to represent a proxy chain to downstream services.
If the header exists, append the Client IP to the header from `req.connection.remoteAddress` - if it does not exist, simply set it to the Client IP.

set X-Forwarded-For header on downstream requests

---

hokusai/production.yml

We just observed a spike in search requests that caused API latency to increase. It recovered after ~5 minutes, but Metaphysics latency couldn't recover. All pods' logs were filled with messages like:
```
...[Cache#get] Timeout...
```
or
```
...[Cache#get] Slow read of 1537ms for key...
```
The pods were getting OOM-killed and all entered the `CrashLoopBackOff` state. (It reminded me of [recent outages](https://github.com/artsy/post_mortems/issues/32).)
I don't know how much it helped, but we ended up updating the `minReplicas` in an effort to give the pods more breathing room and start to actually handle requests.

@sepans: Temporarily boost minReplicas

---

src/schema/artwork/index.js

This adds the `price_currency` to the artwork schema for https://artsyproduct.atlassian.net/browse/GROW-845.

@orta: add price currency to artwork schema

---

src/data/exchange.graphql
src/schema/__tests__/ecommerce/order.test.js
src/schema/__tests__/ecommerce/order_fields.ts
src/schema/__tests__/ecommerce/orders.test.js
src/schema/ecommerce/approve_order_mutation.js
src/schema/ecommerce/create_order_with_artwork_mutation.ts
src/schema/ecommerce/fulfill_order_at_once_mutation.ts
src/schema/ecommerce/order.js
src/schema/ecommerce/orders.js
src/schema/ecommerce/query_helpers.ts
src/schema/ecommerce/reject_order_mutation.js
src/schema/ecommerce/set_order_payment_mutation.ts
src/schema/ecommerce/set_order_shipping_mutation.ts
src/schema/ecommerce/submit_order_mutation.js
src/schema/ecommerce/types/order.ts
src/schema/ecommerce/types/order_party_union.ts
src/test/fixtures/exchange/mockxchange.js
src/test/fixtures/exchange/order.json
src/test/fixtures/exchange/orders.json
src/test/fixtures/results/sample_order.js

`User` and `Partner` are very specific terms and not clear when it comes to ecommerce platform, we decided to [rename](https://github.com/artsy/exchange/pull/121) these fields in Exchange. This PR matches those changes by:
- Adding `OrderPartyUnionType`
- Switch all the places we use `user` and `partner`
Make sure to update your `orders` query. Replace `partnerId` argument to `sellerId` and `sellerType` with seller type being `Partner` (we can make this an enum too later.
in your queries replaces
```
userId
partnerId
```
to 
```graphql
seller {
...on Partner {
id
name
}
... on User {
id
email
}
}
buyer {
... on User {
id
email
}
...on Partner {
id
name
}
}
```
Ideally this gets deployed around the same time as https://github.com/artsy/exchange/pull/121

Buyer/Seller is the new User/Partner

---

src/schema/filter_artworks.js

This wound up not being used, since we renamed the backend param to include the `_only`.

@mzikherman => Rename and pass thru inquireable_only param

---

.gitignore
scripts/compare-stitched-schema.sh
scripts/dump-schema.ts

This gives us insight into what is different in the schemas between stitched and unstitched today.
Looks like gravql and convection issues. Personally, I'm a little surprised that exchange is perfect, but maybe I shouldn't be? Maybe it's because all that code is being included anyway.
This PR doesn't attempt to fix, but to provide a way to get insight.
```sh
~/d/p/a/j/a/metaphysics  $ ./scripts/compare-stitched-schema.sh                                                                                                                     stitch_vs_unstitched
yarn run v1.9.4
$ babel-node --extensions '.ts,.js' ./scripts/dump-schema.ts _schema.graphql
✨  Done in 1.30s.
yarn run v1.9.4
$ babel-node --extensions '.ts,.js' ./scripts/dump-schema.ts tmp/stitched.graphql
✨  Done in 1.36s.
⏳ …
```

Adds a script to compare the unstitched vs stitched schemas

---

.vscode/settings.json
docs/testing.md
package.json
src/__tests__/runStoredQueryTests.ts

OK, so given the results of #1257 - I took a step back and wondered what other linting tools can we have that don't require putting stitching on staging. One of them is to run our production queries against different hosts of metaphysics.
This PR takes our stored queries, loops through them and calls them against an instance of MP
- it handles looking up variables for a bunch of queries (I focused on root query renderers as they tend to have the complexity I'm interested in testing)
- it skips mutations
- it uses the same env var names as reaction, so you can C&P
It *does not* add to CI - that's feasible, I'm not too sure where the value lives there, but I'm open to ideas.

Creates a script for running emission stored queries against instances of metaphysics

---

package.json
src/lib/loaders/__tests__/request_id.test.js
src/lib/requestIDs.ts
yarn.lock

Seeing some remote ip addresses set to ipv6 notation in the proxy chain `X-Forwarded-For` headers rather than ipv4. See https://stackoverflow.com/questions/29411551/express-js-req-ip-is-returning-ffff127-0-0-1
Resolve ipv6 to ipv4 notation where appropriate.

resolve ipv6-formatted addresses to ipv4

---

scripts/dump-schema.ts

I tried synching reaction to metaphysics and got this error: 
```
$ babel-node --extensions '.ts,.js' ./scripts/dump-schema.ts ../../data
fs.js:646
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
^
Error: EISDIR: illegal operation on a directory, open '../../data'
at Object.fs.openSync (fs.js:646:18)
at Object.fs.writeFileSync (fs.js:1299:33)
at Object.<anonymous> (/Users/davidsheldrick/code/artsy/reaction/externals/metaphysics/scripts/dump-schema.ts:24:4)
...
```
The dump-schema.ts file was recently changed to allow specifying either a folder or a file path, but it seems like the folder path option was no longer working properly.

fix dump-schema.ts

---

package.json
yarn.lock

This reverts commit 853c329c1c7b753ea4ca88623e94dcd284e38100.
For when I’m done testing in production.

Revert "[package] Update to test agent v0.4"

---

_schema.graphql
src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.js
yarn.lock

This PR addresses [PURCHASE-440](https://artsyproduct.atlassian.net/browse/PURCHASE-440) to support hiding the pickup radio button UI if the artwork isn't available for pickup.

Adds pickup_available field to Artwork type

---

src/schema/artwork/index.ts
yarn.lock

This is probably controversial but here's what's up:
Right now in force, we need control over both the fact that an artwork is `inquireable` and `acquireable`. i.e. for now, if a work has `{ acquireable: true, inquireable: true }`, we want to be able to show the inquiry button _unless_ they have the lab feature enabled. This is currently impossible because we don't expose `inquireable` in its truthful form.
☝️ that's the practical requirement, which could be solved in multiple ways.
The second important piece is that I don't think we should have `is_inquireable` conflate the meaning of what it means to be `inquireable` and `acquireable`. What if an offering we give to galleries is the ability to both buy _or_ inquire on a work? Now that metaphysics is acting as an API and not just as a …

Change the definition of is_inquireable to mean just inquireable

---

yarn.lock

https://github.com/DataDog/dd-trace-js/compare/27c00ff3428ae4fa76a61590de9787d5cf37fa6e...9945be573c86a5827a00b8e258cdcf88af7a0cbd

[tracer] Update to latest version of upstream v0.6.0 branch.

---

_schema.graphql
src/schema/ecommerce/types/order_line_item.ts
tsconfig.json

Some apps where requesting edition set details https://github.com/artsy/volt/pull/3227 by doing 
```graohql
order{
editionSet{
id
}
}
```
Which raises error.
We had `editionSet` as a field with type `EditionSet.type` on an `Order` but we were not actually resolving it to an `EditionSet` and we were just returning `editionSetId`.
Remove `editionSet` field and just expose `editionSetId`.

Remove un-resovled EditionSet from Order

---

_schema.graphql
src/lib/stitching/exchange/schema.ts
src/schema/ecommerce/approve_order_mutation.ts
src/schema/ecommerce/create_order_with_artwork_mutation.ts
src/schema/ecommerce/fulfill_order_at_once_mutation.ts
src/schema/ecommerce/order.js
src/schema/ecommerce/orders.js
src/schema/ecommerce/reject_order_mutation.ts
src/schema/ecommerce/set_order_payment_mutation.ts
src/schema/ecommerce/set_order_shipping_mutation.ts
src/schema/ecommerce/submit_order_mutation.ts
src/schema/index.ts
src/test/fixtures/exchange/mockxchange.js

OK, so this one *really* fixes the issues we were seeing. What happened is:
- Adding #1279 changed the exchange schema manipulations for fields
- This broke the *internal* graphql resolving for exchange
- I thought it broke the external resolving (thus #1289 which this reverts)
Now the internal schema (and its test fixtures) are always in sync.

Removes the newly created resolvers, and fixes the internal schema resolving for exchange 

---

package.json
src/lib/__tests__/rateLimiter.test.ts
src/lib/rateLimiter.ts

Turns out that Force does not add its own IP to the `x-forwarded-for` list (@izakp is this correct?) so we can’t detect legit clients based on that. Instead just detect if the `x-request-id` header exists.

[rateLimiter] Use request ID to (naively) recognize legit clients.

---

src/lib/__tests__/rateLimiter.test.ts
src/lib/rateLimiter.ts

Because the DD libs already patch all outgoing HTTP requests to include
this, meaning we don’t need to go through all our code to find the
places where we make requests and update each of those.
Additionally we shouldn’t rely on these types of headers at all in the
long run, so using this for pragmatic reasons seems fine.

[rateLimiter] Trust clients based on having set a DataDog header.

---

.circleci/config.yml

Fix circleci deployment / https://github.com/artsy/metaphysics/pull/1296 -- `--git-remote` option added to `hokusai [staging|production] deploy` in [v 0.4.5](https://github.com/artsy/hokusai/blob/master/CHANGELOG.md#v045) 
cc @alloy @mbilokonsky

update hokusai version in circleci config

---

_schema.graphql
src/schema/credit_card.js

A lot of credit cards in Gravity do not have these fields filled in and marking them as NonNull would make it impossible to query.

Make credit card billing address fields nullable

---

src/lib/nameOldEigenQueries.ts

Removes the extra wrappers around mutations as a mutation cannot live inside a query.

Removes the extra query wrapping for eigne queries that are mutations

---

scripts/dump-schema.ts

Runs results through prettier for more consistent formatting

Run schema.json through prettier

---

src/schema/__tests__/ecommerce/set_order_payment_mutation.test.ts
src/schema/ecommerce/set_order_payment_mutation.ts

When getting `creditCard` info back after `setOrderPayment` mutation, we were getting `null` even when credit card was set properly on the order.
We were missing getting `creditCardId` from the Exchange's response coming back.
Well... add it!

Add creditCardId to response coming back from Exchange

---

package.json
scripts/dump-schema.ts

This means the defaults are always set for schema dumping.

Dumping a schema first applies the example env vars, then your own

---

_schema.graphql
src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.ts

This exposes the price (in cents) of a work. Since works can be exact priced, or in a range, we provide a min/max/exact object for clients.
This hasn't been needed up until now, and the only use case is the comparables visualizer will grab this for a given artwork, and pipe the results back into a filter query (adding 10% buffer to the min/max).

@damassi => Expose min and max price in cents for an artwork

---

hokusai/production.yml
hokusai/staging.yml

antiAffinity scheduling rules based on the label `cpu-hog` (ensuring only one pod with the label `cpu-hog` is run per node) are not used in Gravity any more as of https://github.com/artsy/gravity/pull/11945 so they are redundant here as well

remove cpu-hog constraints from metaphysics-web pods

---

_schema.graphql
src/data/exchange.graphql
src/lib/stitching/exchange/__tests__/__snapshots__/schema.test.ts.snap
src/schema/ecommerce/approve_order_mutation.ts
src/schema/ecommerce/confirm_pickup_mutation.ts
src/schema/ecommerce/create_order_with_artwork_mutation.ts
src/schema/ecommerce/fulfill_order_at_once_mutation.ts
src/schema/ecommerce/order.ts
src/schema/ecommerce/orders.ts
src/schema/ecommerce/reject_order_mutation.ts
src/schema/ecommerce/set_order_payment_mutation.ts
src/schema/ecommerce/set_order_shipping_mutation.ts
src/schema/ecommerce/submit_order_mutation.ts
src/schema/ecommerce/types/order.ts

Exposes `commissionRate` and `displayCommissionRate` on Order as implemented in https://github.com/artsy/exchange/pull/224.

Add commissionRate to EcommerceOrder

---

src/schema/home/home_page_hero_units.js

The BNMO hero unit is in the first position, but it turns out we ignore the positioning entirely (except for returning them from the API _in_ that order), by shuffling them here. This just removes the shuffle.

@sweir27 => Remove random shuffling of hero units

---

src/schema/fields/__tests__/pagination.test.js
src/schema/fields/pagination.js

We've discussed this in many places (in standup, in slack, and even on Github https://github.com/artsy/reaction/pull/1412#discussion_r225246844), but seems like we just want to cap the results to 100 for the time being. This PR updates the `createPageCursors`  function to check the `totalPages` and replaces it with `100` if it exceeds more than that. This may affect pagination results globally, and I wonder if there should be a way of capping a more specific element. Open to suggestions. Let me know what you all think!

Cap pagination results to 100

---

hokusai/production.yml

Schedule MP pods on `tier=api` nodes (our [fixed capacity group](https://github.com/artsy/substance/blob/master/clusters/production/federation/kubernetes-production-orion.artsy.systems/spec.yml#L93) in k8s production) preferentially, [as we do in Gravity](https://github.com/artsy/gravity/blob/master/hokusai/production.yml#L57) 
`hokusai production update`

#migration schedule MP pods on api tier nodes

---

src/schema/__tests__/filter_artworks.test.js
src/schema/fields/pagination.js
src/schema/filter_artworks.js

finishes https://artsyproduct.atlassian.net/browse/GROW-954
We've seen that the `Next` link is still enabled even when the user is on the `100` page. This is because the logic we compute the `hasNextPage` flag isn't based on the `totalPages` we compute in the `createPageCursors` function but instead we just use the `connectionFromArraySlice` from `graphql-relay`. What this means is that we can't easily apply this to all the connections globally but need to patch one-by-one. At the time of writing the `filter_artworks` is the only connection type we generate the pagination window for, so patching `filter_artworks` will fix the issue both in the Artist page and the Collect page. We may want to update the architecture if we find this pattern more common, but for now this should be good.

The hasNextPage flag should be false on page=100 when pagination results are capped to 100

---

src/lib/stitching/kaws/stitching.ts

This removes aggregation hardcoded value so one can be passed in.

[stitching] Remove default aggregations for MarketingCollection #trivial

---

src/lib/loaders/loaders_with_authentication/gravity.ts

Removing order loader, these are not currently used and also wont be useable after https://github.com/artsy/gravity/pull/11968, we've switched to Exchange's order

Remove unused gravity loaders

---

hokusai/production.yml
hokusai/staging.yml

Another k8s update - reconfigure Metaphysics to use the in-cluster DNS service.
Update `dnsPolicy` and `dnsConfig` options - this will create an `/etc/resolv.conf` file with the following content, where `100.x.x.x` is the IP of the internal cluster  [kube-dns service](https://kubernetes.artsy.net/#!/service/kube-system/kube-dns?namespace=kube-system):
```
nameserver 100.x.x.x
search default.svc.cluster.local svc.cluster.local cluster.local ec2.internal
options ndots:1
```
With this configuration, all DNS queries will use the in-cluster DNS service, and any domain name with at least one `.` will be considered fully-qualified.

set dnsPolicy: ClusterFirst and dnsConfig option ndots: 1

---

src/schema/types/formatted_number.ts

Turns out that when I pulled this into Reaction as a TS file, the compiler pointed out that the second part of the condition would always pass.

[formatted_number] Fix validation

---

src/schema/show.js

Fixes a typo that breaks querying for `images` on `show`.

Correctly destructure partnerShowImagesLoader in Show

---

README.md

I accidentally pushed the git tag for a production deploy to my fork instead of Artsy's repo, so I wanted to update our docs to make it explicit which to use and how to fix it if you mess it up.

Updates deployment docs

---

src/schema/image/__tests__/normalize.test.js
src/schema/image/normalize.js

We've had a few instances (that we know of) that a normalized image has been delivered in production. These images are huge and should likely _never_ be used. On the off chance they they are needed, they should be explicitly provided. 
Currently when querying and artwork image without specifying a size, there's a chance that normalized will return. 
Here are at least two issues that has been caused by this. 
https://github.com/artsy/force/pull/3032
https://github.com/artsy/force/pull/2233
This PR simply filters out `normalized` from the list of default options. 
I still have some concerns about this though. I thought that `image_versions` would be ordered from smallest size to largest size. The idea here seeming to be that if the image size isn't specified then we'd want to choose the …

Ensure normalized is never an image default

---

src/index.ts
src/lib/stitching/exchange/link.ts

First part of https://artsyproduct.atlassian.net/browse/PURCHASE-574
tl;dr we want to track user agent and ip address at bnmo order creation time. We're already correctly setting the `x-forwarded-for` header, which supplies the user's ip address to exchange. This PR forwards the user agent too.

Forward original user agent to exchange

---

_schema.graphql
src/schema/credit_card.js
src/schema/me/__tests__/create_credit_card_mutation.test.js
src/schema/me/__tests__/credit_cards.test.ts
src/schema/me/credit_cards.ts

Finally!
With these few changes my relay dreams will be a reality. ✨ 
This PR:
- Adds `limit` to the `me: creditCards` query so that we can pull a high number from gravity (it's a little hacky, but the UI is also not optimized for someone viewing 100 credit cards at once so I think it's OK for now).
- Returns a `creditCardEdge` from the `createCreditCardMutation` so that we can update our relay store with the result and have our UI magically be complete.

Some updates to credit card schema/mutation

---

_schema.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/artwork_version.ts
src/schema/ecommerce/types/order_line_item.ts

I'm working on this ticket:
https://artsyproduct.atlassian.net/browse/SELL-1031
And had a convo with @ashkan18 on Slack here:
https://artsy.slack.com/archives/CB110C6LE/p1539269193000100
What I'm attempting to do with this PR is have orders resolve their artwork using the particular version of the artwork at the time of the sale. This should ensure that any mutations on the artwork won't cause the order detail page in CMS to blow up.
I have no idea if I have done this correctly, so looking for direction, but this seemed like all I had to do!

Use artwork version when resolving orders

---

_schema.graphql
src/data/exchange.graphql
src/lib/stitching/exchange/__tests__/__snapshots__/schema.test.ts.snap
src/schema/__tests__/ecommerce/order_fields.ts
src/schema/ecommerce/query_helpers.ts
src/schema/ecommerce/types/order.ts
src/schema/ecommerce/types/order_line_item.ts
src/test/fixtures/exchange/order.json
src/test/fixtures/exchange/orders.json
src/test/fixtures/results/sample_order.js

https://github.com/artsy/exchange/pull/273
- Deprecate `offerTotal` fields from `Order`
- Add `totalListPrice` fields to `Order`
- Deprecated `priceCents` from `LineItem`
- Added `listPriceCents` to `LineItem`
This should make all these deploys safe as long as Exchange gets deployed first because of accessing `listPriceCents` in MP

Line item changes

---

_schema.graphql
src/schema/sale_artwork.js

Gravity consider's a SaleArtwork's `position` to be a float.  Metaphysics had it as an integer.
Auction ops relies on it being a float, so we update Metaphysics here. Downstream clients may need to be updated as well.

Change sale_artwork.position from int to float

---

_schema.graphql
src/schema/fair.ts

As part of [LD-27](https://artsyproduct.atlassian.net/browse/LD-27), exposes the Fair's `hours` field.

Expose hours field on Fair

---

_schema.graphql
src/data/kaws.graphql
src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
src/lib/stitching/kaws/__tests__/schema.test.ts
src/lib/stitching/kaws/schema.ts

Pair session with @l2succes 
- Updates schema to include `categories` from Kaws as `MarketingCollectionCategories`
- Updates name remapping when using Kaws queries in Metaphysics 
- Fixes tests to look for Kaws variables instead of Metaphysics

@xtina-starr => Update Kaws schema

---

_schema.graphql
src/data/exchange.graphql
src/schema/__tests__/ecommerce/seller_accept_offer_mutation.test.ts
src/schema/ecommerce/query_helpers.ts
src/schema/ecommerce/seller_accept_offer_mutation.ts
src/schema/ecommerce/types/offer_mutation_input_type.ts
src/schema/schema.ts

Jira: https://artsyproduct.atlassian.net/browse/SELL-1150
Adds `sellerAcceptOfferMutation` to MP, so that it can be consumed by force.
WARNING: If this deployed to production before, Exchange https://github.com/artsy/exchange/commit/b03a4a6f51cb88ca5d9637f5012586b8a0306af0 is deployed to production, then MP might break as MP-prod will have a newer version of Exchange's schema than Exchange-prod.
----
N.B: local MP is on my dev branch, integrating with Gravity staging.

SELL-1150: Update exchange.graphql to reflect artsy/exchange#271

---

index.js

This adds a warning in case you accidentally set `ENABLE_QUERY_TRACING` to `true` in dev.

Add warning for ENABLE_QUERY_TRACING in dev

---

src/lib/stitching/exchange/link.ts

https://artsyproduct.atlassian.net/browse/PURCHASE-644
Small bugfix to properly forward user agent strings from client to exchange.

Fix exchange link user-agent forwarding

---

_schema.graphql
src/schema/filter_artworks.js

We want to add this to the landing page/initial query for Collect and Collections (https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-493) , to ensure no nude or provocative images appear (which is essential for marketing purposes).
This safe to merge, even though the Gravity part hasn't been deployed yet.

@l2succes => Add `marketable` as a filter artworks param

---

src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.ts

Pages for artworks which were previously enrolled in an e-commerce program still display shipping information provided during enrollment in the program.
This creates an inconsistent user experience. If an artwork is removed from a program, we should not display any shipping information previously entered during enrollment.
This commit updates Metaphysics to return a `null` value for `shippingInfo` unless the artwork is `acquirable` designating active enrollment in one or more of our e-commerce programs.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-494

DISCO-494: Return null shipping info if artwork is not acquirable

---

_schema.graphql
src/schema/__tests__/partner_show.test.js
src/schema/__tests__/show.test.js
src/schema/partner_show.ts
src/schema/show.ts

Adds a new `saleArtworks` connection to `PartnerShows` and converts the file to TypeScript. 
Related: https://github.com/artsy/gravity/pull/12027
```gql
{
partner_show(id: "cardi-gallery-cardi-gallery-at-art-basel-miami-beach-2018") {
artworksConnection(first: 2) {
pageInfo {
hasNextPage
}
edges {
node {
id
}
}
}
}
}
```
```json
{
"data": {
"partner_show": {
"pageInfo": {
"hasNextPage": true
},
"edges": [
{
"node": {
"id": "michelangelo-pistoletto-untitled-12"
}
},
{
"node": {
"id": "lucio-fontana-concetto-spaziale-attese-139"
}
}
]
}
},
}
}
```

[PartnerShow] Add saleArtworks connection

---

_schema.graphql
src/schema/__tests__/formattedDaySchedules.test.ts
src/schema/location.js
src/schema/types/formattedDaySchedules.ts

We want to format `Location.day_schedules` for display as part of ongoing local discovery work. Force contains some logic that deduplicates and squashes this data [here](https://github.com/javamonn/force/blob/55e47edd24106806705bef82cdd74314148097af/src/desktop/models/partner_show.coffee#L201-L255). This PR runs that coffeescript through [decaffinate](https://github.com/decaffeinate/decaffeinate), cleans it up a bit, and adds the formatted result as a `displayDaySchedules` on `Location`.

Port daySchedules formatting logic from force

---

.prettierignore
.vscode/settings.json
_schema.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/__tests__/partner.test.js
src/schema/ecommerce/initial_offer_mutation.ts
src/schema/partner.ts

Adds a new `artworksConnection` field to `Partner`.
(Need to follow up with Gravity PR for `exclude`) 
```gql
{
partner(id:"bau-xi-gallery") {
artworksConnection(first:3) {
pageInfo {
hasNextPage
}
edges {
node {
id
}
}
}
}
}
```
```json
{
"data": {
"partner": {
"pageInfo": {
"hasNextPage": true
},
"edges": [
{
"node": {
"id": "cara-barer-iceberg"
}
},
{
"node": {
"id": "david-leventi-rezzonico"
}
},
{
"node": {
"id": "virginia-mak-hidden-nature-08"
}
}
]
}
},
}
}
```

[Partner] Add artworksConnection field

---

_schema.graphql
src/schema/location.ts
src/schema/show.ts

This exposes the new fields from Gravity's api responses:
- `PartnerShow#is_local_discovery`
- `PartnerLocation#day_schedule_text`

Resolve new fields for PartnerShow & PartnerLocation

---

src/schema/artist/index.ts

Depends on https://github.com/artsy/gravity/pull/12034
Adds a new `exclude` field to `artworks_connection`: 
```gql
{
artist(id: 'andy-warhol') {
artworks_connection(first: 5, exclude: ['foo', 'bar', 'baz]) { ... }
}
}
```

[Artist] Add `exclude` field

---

_schema.graphql
src/schema/artwork/index.ts
src/schema/filter_artworks.ts

Comments out two currently-used deprecations until https://github.com/apollographql/apollo-tooling/issues/805 is addressed. (Deprecation notice has been moved to `description` field.)

[FIXME] Comment out used deprecations

---

src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.ts

Reverts artsy/metaphysics#1385
ticket: https://artsyproduct.atlassian.net/browse/DISCO-544 :lock: 
This caused a regression in the order flow preventing shipping information from displaying on the receipt once an order is submitted.
We've updated Force (desktop and mobile) to hide shipping information for artworks not enrolled in an e-commerce program ([PR](https://github.com/artsy/force/pull/3161)). We can now remove this logic from Metaphysics.
There's an ongoing discussion on how client-specific responses from Metaphysics should be. There's more context available in the original PR [here](https://github.com/artsy/metaphysics/pull/1385#issuecomment-441789606) and in the Force PR [here](https://github.com/artsy/force/pull/3161#issue-235886148).

Revert "DISCO-494: Return null shipping info if artwork is not acquirable"

---

_schema.graphql
src/schema/__tests__/show.test.js
src/schema/fair.ts
src/schema/filter_artworks.ts
src/schema/show.ts

The Show and Fair screens implement as part of Local Discovery contain an "All works" screen that allows filtering over all associated works: https://app.zeplin.io/project/5bef4c7dae2b6a3eb6a75f4a/screen/5bf32e8c072fb97e8f6b295f. This PR exposes `filteredArtworks` fields to both `Show` and `Fair` using the existing `filter_artworks` field type.
Implements [LD-72](https://artsyproduct.atlassian.net/browse/LD-72).
Note that a similar filtered view exists for fairs on the web: https://staging.artsy.net/ink-miami-2018/browse/artworks?for_sale=. This view is also ES backed, making use of Force's [`filter2`](https://github.com/artsy/force/blob/master/src/desktop/components/filter2/README.md) component.

Add filtered artworks to Show, Fair

---

_schema.graphql
src/schema/__tests__/city.test.ts
src/schema/__tests__/show.test.js
src/schema/city/index.ts
src/schema/show.ts

Implements https://artsyproduct.atlassian.net/browse/LD-40
Allows clients to request a list of shows that includes local discovery stubs, as well as regular displayable shows.
We do this by taking the new `discoverable` scope that was [added](https://github.com/artsy/gravity/pull/11995) to Gravity's `/shows` endpoint, and bring it into MP in two places:
- as an optional arg provided to a city's `shows` resolver
- as an optional arg provided to a show's `nearbyShows` resolver

Expose stub shows for local discovery

---

_schema.graphql
src/schema/show.ts

Implements https://artsyproduct.atlassian.net/browse/LD-85
This supports the opening reception free text that was [added to shows](https://github.com/artsy/gravity/pull/12047) for local discovery stubs

LD-85 Expose opening_reception_text on Show

---

_schema.graphql
src/data/exchange.graphql
src/schema/__tests__/ecommerce/seller_counter_offer_mutation.test.ts
src/schema/ecommerce/seller_counter_offer_mutation.ts
src/schema/schema.ts

Fixes [SELL-1177](https://artsyproduct.atlassian.net/browse/SELL-1177)
Followed the same input pattern as `AddInitialOfferToOrderMutation` using `MoneyInput`
Sample query:
```graphql
mutation sellerCounterOffer($offerId: String!, $offerPrice: MoneyInput!){
ecommerceSellerCounterOffer(input: {offerId: $offerId, offerPrice: $offerPrice}){
orderOrError {
... on OrderWithMutationSuccess {
order{
id
mode
buyer {
__typename
... on User {
id
name
}
}
seller {
__typename
... on Partner {
id
name
}
}
itemsTotalCents
shippingTotalCents
commissionFeeCents
taxTotalCents
buyerTotalCents
sellerTotalCents
itemsTotal
shippingTotal
commissionFee
taxTotal
buyerTotal
sellerTotal
lineItems{
edges{
node{
id
artwork{
title
artist{
name
}
}
}
}
}
... on OfferOrder {
myLastOffer {
id
amount
shippingTotal …
```

Adds SellerCounterOfferOnOrderMutation

---

_schema.graphql
src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.ts
src/schema/edition_set.ts

Now that https://github.com/artsy/gravity/pull/12050 is merged, we can offer a price-sorted list of edition sets.
Once this is merged (and the schema in Reaction updated), we can do `edition_sets(sort: PRICE_ASC)` and drop the sorting there.

@dblandin => Allow edition sets to be sorted by price

---

_schema.graphql
src/schema/__tests__/ecommerce/buyer_reject_offer_mutation.test.ts
src/schema/ecommerce/buyer_reject_offer_mutation.ts
src/schema/ecommerce/seller_reject_offer_mutation.ts
src/schema/ecommerce/types/cancel_reason_type_enum.ts
src/schema/ecommerce/types/reject_offer_mutation_input_type.ts
src/schema/schema.ts

I forgot to manually stitch the new buyerRejectOffer mutation from Exchange into Metaphysics when I was working on [PLATFORM-689](https://artsyproduct.atlassian.net/browse/PURCHASE-689) so this PR does that.
I also rearranged some of the accept, counter, and reject declarations in the schema so that that they would follow the following order:
1. buyer accept
2. seller accept
3. buyer counter
4. seller counter
5. buyer reject
6. seller reject

Stitched the Exchange mutation for a buyer to reject an offer

---

_schema.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/__tests__/fair.test.js
src/schema/fair.ts
src/schema/sorts/fairArtistSorts.ts

~Depends on: https://github.com/artsy/gravity/pull/12048~ (Merged!)
Implements: [LD-83](https://artsyproduct.atlassian.net/browse/LD-83).
Uses Gravity's [FairArtistsEndpoint](https://github.com/artsy/gravity/blob/master/app/api/v1/fairs_artists_endpoint.rb) to expose an `artistsConnection` field on Fair. This field backs the mock seen [here](https://app.zeplin.io/project/5bef4c7dae2b6a3eb6a75f4a/screen/5bf32e8aa6dc5049913296b9). Emission will paginate over this field, sorted by name, and build alphabetical groupings as more data is fetched.

Add artistsConnection to Fair

---

_schema.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/__tests__/show.test.js
src/schema/show.ts

Exposes the count of artists associated with a show, as part of [LD-51](https://artsyproduct.atlassian.net/browse/LD-51), which is [designed to include text with "X works by Y artists"](https://app.zeplin.io/project/5bef4c7dae2b6a3eb6a75f4a/screen/5c1427dea15cd3246ec6a953).

Add Show.counts.artists

---

.circleci/config.yml
hokusai/config.yml

This should ensure that Git tags are always pushed when a `hokusai
pipeline promote` or `hokusai staging` are invoked.

Add git remote option to MP

---

_schema.graphql
src/schema/artist/__tests__/insights.test.ts
src/schema/artist/index.ts
src/schema/artist/insights.ts

We're beginning to load in new artist insights to show on the artist page.
This will expose insights from Gravity via GraphQL, when available for an artist.
Related to https://github.com/artsy/gravity/pull/12059 :lock: 
ticket: https://artsyproduct.atlassian.net/browse/DISCO-588 :lock:

Expose and structure artist insights from Gravity

---

_schema.graphql
src/schema/artwork/__tests__/meta.test.ts
src/schema/artwork/index.ts
src/schema/artwork/meta.ts

Addresses https://artsyproduct.atlassian.net/browse/DISCO-628
Adds a new `share` field for returning a properly formatted description in a share context. 
```gql
{
artwork(id:"hans-hartung-p-25-1975-h-8") {
meta {
share
}
}
}
```
```json
{
"data": {
"artwork": {
"meta": {
"share": "Check out Hans Hartung, P. 25-1975-H-8 (1975), From Galerie Michel Descours"
}
}
}
}
```

[Artwork#meta] Add new `share` field

---

_schema.graphql
src/lib/__tests__/geospatial.test.ts
src/lib/geospatial.ts
src/schema/__tests__/city.test.ts
src/schema/city/constants.ts
src/schema/city/index.ts

Implements: https://artsyproduct.atlassian.net/browse/LD-64
Follow-up to: https://github.com/artsy/emission/pull/1252#discussion_r243255869
This allows a client to find a local discovery city by latititude/longitude, as obtained e.g. via a device's geolocation API.
To do this we modify the root `city` query to allow lookup by lat/lng (in addition to the already implemented lookup by slug).
The lat/lng lookup is subject to a threshold, such that if you supply a point close enough to an existing city you will get a result:
But if you supply a point not close enough, you will get `null`:
In the Emission thread we discussed having this query return the city if an appropriate one is found, or else `null` or something representing _no city found_. I've modeled this as a simple `null` for now …

Allow finding a local discovery city nearest to an arbitrary point

---

src/schema/artist/__tests__/index.test.js
src/schema/artist/shows.ts

The responsive artist page's CV tabs is using the shows connection to fulfill its list of shows.
That was not using the previously existing blacklist logic, this PR adds that.

Filter out unwanted shows from artist's shows connection

---

_schema.graphql
src/schema/__tests__/fair.test.js
src/schema/fair.ts

This PR adds a new default profile id field in the Fairs exhibitors_grouped_by_name field.
[See LD-115](https://artsyproduct.atlassian.net/browse/LD-115)

exposing partner/exhibitor profile ids in Fairs

---

src/lib/__tests__/graphqlErrorHandler.test.ts
src/lib/graphqlErrorHandler.ts

Part of https://artsyproduct.atlassian.net/browse/DISCO-671
Augments an error with `extensions`, as described in the spec https://facebook.github.io/graphql/draft/#sec-Errors.

[graphqlErrorHandler] Include upstream HTTP status code.

---

_schema.graphql
src/data/exchange.graphql
src/lib/stitching/exchange/__tests__/__snapshots__/schema.test.ts.snap
src/schema/ecommerce/create_offer_order_with_artwork_mutation.ts
src/schema/ecommerce/types/create_order_input_type.ts

Catch up with latest exchange which includes optional `findActiveOrCreate` flag for `createOfferOrderWithArtwork` mutation.

Switch to latest Exchange schema to add findActiveOrCreate

---

src/schema/artist/__tests__/carousel.test.js
src/schema/artist/carousel.ts
src/types/gravity/artworkResponse.d.ts

This addresses AS-285 as a reasonable hot-fix at the metaphysics layer
Before:
See that blue lady sitting? That's a print that isn't  really *that* iconic, maybe the original is, then there's an edition multiple after that and so on. These works aren't the most canonical works for an artist, and so we don't want to be highlighting them inside the Artists carousel. This PR removes their ability to show up. 
It does this by over asking for artworks, and filters out artworks based on their attribution types.
---
Also adds a type definition for a gravity API response, so that you can feel safer working with those rest responses.

Don't allow highlighting artworks in the artists carousel which are not canonical artworks

---

_schema.graphql
src/schema/__tests__/partner.test.js
src/schema/__tests__/show.test.js
src/schema/partner.ts
src/schema/show.ts

This PR adds a partner url field  in the Shows schema to expose the web address galleries have directly uploaded to CMS.
[Links to LD-148](https://artsyproduct.atlassian.net/browse/LD-148)
[Also links to LD-129](https://artsyproduct.atlassian.net/browse/LD-129)

expose gallery website urls in Shows field

---

_schema.graphql
src/schema/ecommerce/types/order.ts

*Partially* resolves https://artsyproduct.atlassian.net/browse/PURCHASE-796. 
Removes the deprecated `lastOffer` and `offers` fields from the `Order` type. (They exist on `OrderOffer` instead.)
The following clients have been checked for use of these fields:
* Eigen: does not use them
* Force: does not use them
* Reaction: Was using `lastOffer`. [Reaction PR #1929](https://github.com/artsy/reaction/pull/1929) has been merged ~, but needs to be released to production before this PR can be merged~ [and deployed!!!](https://github.com/artsy/force/pull/3401).
* Volt: Was using `offers`. [Volt PR #3409](https://github.com/artsy/volt/pull/3409) ~needs to be merged & released to production before this PR can be merged~ [has been merged and deployed!!!](https://github.com/artsy/volt/pull/3414). …

Remove deprecated fields from “Order”

---

hokusai/production.yml

Since we're scheduling concurrently with Causality and Gravity now, I would like that we don't get into the position of nodes evicting pods - so request as much memory as the limit.
Also set CPU requests to 1 core to avoid overscheduling on any given node.  Seeing high CPU consumption and scheduling of up to 4 metaphysics pods on a given `tier=api` node.  Setting this request higher will avoid over-allocation.
```
$ kubectl top pods --selector app=metaphysics
NAME                              CPU(cores)   MEMORY(bytes)
metaphysics-web-c45f9fb4c-4ffcn   853m         1203Mi
metaphysics-web-c45f9fb4c-7hr5g   889m         1143Mi
metaphysics-web-c45f9fb4c-7j9mr   1173m        844Mi
metaphysics-web-c45f9fb4c-cpft6   802m         1219Mi
metaphysics-web-c45f9fb4c-dnh78   759m         690Mi …
```

set memory requests equal to limits in production to avoid evictions - set CPU requests to 1 core and deprioritize scheduling on API nodes

---

_schema.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/lib/loaders/searchLoader.ts
src/schema/__tests__/search.test.ts
src/schema/artist/index.ts
src/schema/artwork/index.ts
src/schema/schema.ts
src/schema/search.ts
src/schema/searchable.ts
src/schema/searchableItem.ts

Alternate approach to https://github.com/artsy/metaphysics/pull/1475 which introduces a `Searchable` interface instead of defining a `SearchResult` type.
Add a new global search connection to support a reimplementation and redesign of the search bar and search results page on artsy.net.
This implementation introduces a new `Searchable` interface. Searchable entities represented in Metaphysics and supported by the Gravity API should implement this interface.
If entity-specific attributes are requested, the appropriate loader should be wired up so that the resolver can fetch the full object from Gravity and include it within the query response. We determine whether a
particular search result item should be fetched by inflecting on the GraphQL query AST and looking for an inline fragment …

Add GraphQL interface for global Artsy search

---

_schema.graphql
src/data/kaws.graphql
src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
src/lib/stitching/kaws/stitching.ts

cc @alloy @l2succes in case you have any suggestions/thoughts.
~~This uses https://github.com/artsy/kaws/pull/53 to stitch in marketing collections for a given artist. Namely:~~
```
artist(id: "kaws") {
marketingCollections {
// all fields from MarketingCollection
}
}
```
~~However, I'm running into an issue with trying to issue a query to a remote schema with arguments. To me, it appears to me this: https://github.com/apollographql/graphql-tools/issues/820 , which is a blocker for being able to do it. Current uses of stitching in Metaphysics enhance remote schemas with local things (so the other way around, here we are trying to enhance the local Metaphysics schema with a remote one).~~
~~I attempted to also accomplish this by writing out the query and selecting all available fields from …

@orta => [MarketingCollections] Use stitching to expose marketing collections for an artist

---

_schema.graphql
src/data/exchange.graphql
src/schema/__tests__/ecommerce/add_initial_offer_to_order_mutation.test.ts
src/schema/__tests__/ecommerce/buyer_counter_offer_mutation.test.ts
src/schema/__tests__/ecommerce/order_fields.ts
src/schema/__tests__/ecommerce/seller_counter_offer_mutation.test.ts
src/schema/ecommerce/query_helpers.ts
src/schema/ecommerce/seller_counter_offer_mutation.ts
src/schema/ecommerce/types/initial_offer_input_type.ts
src/schema/ecommerce/types/offer.ts
src/test/fixtures/exchange/offer_order.json
src/test/fixtures/results/sample_order.js

This adds the `note` field to "buyer counter offer", "seller counter offer", and "initial offer" mutations, along with corresponding tests.
Completes https://artsyproduct.atlassian.net/browse/GALL-1372

Add offer notes to offer mutations

---

src/lib/__tests__/graphqlErrorHandler.test.ts
src/lib/graphqlErrorHandler.ts

I saw [this in](https://sentry.io/artsynet/metaphysics-production/issues/868039286/?environment=production&referrer=alert_email) my email inbox and got annoyed
Now Metaphysics won't send GraphQL syntax errors to Sentry.

Removes GraphQL syntax errors from sentry

---

package.json
yarn.lock

Looks like there were no new packages added since this PR so the GH UI 'revert' is working.

@joeyAghion => Revert "[package] Update dd-trace client to latest."

---

package.json
yarn.lock

Going to do an orchestrated deploy of this and the Force equivalent: https://github.com/artsy/force/pull/3474

[package] Update dd-trace client to latest, again.

---

src/lib/__tests__/modifyOldEigenQueries.test.ts
src/lib/modifyOldEigenQueries.ts

Follows on from #1491,  #1488  and #1487 
This ensures that Eigen responses are the same JSON shape as it expects. Switched to use `inlineSnapshots` as the prettier 80 char limit was faffing with whitespace.

Ensure that eigen receives the same shaped query response

---

_schema.graphql
src/schema/__tests__/search.test.ts
src/schema/searchableItem.ts

Re: https://github.com/artsy/reaction/pull/1997#discussion_r254482426 , this adds id fields to `SearchableItem`.

@dblandin => [SearchableItem] Add gravity id fields (id/_id) to response

---

_schema.graphql
src/lib/loaders/__tests__/tracked_entity.test.js
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/loaders_with_authentication/tracked_entity.ts
src/schema/__tests__/show.test.js
src/schema/show.ts

Supersedes #1485. I modified the Gravity endpoint [on Matt's suggestion](https://github.com/artsy/metaphysics/pull/1485#discussion_r253689096) in [this PR](https://github.com/artsy/gravity/pull/12144). Fixes LD-184.
This is a WIP until the Gravity deploy is confirmed. I'm actually not sure how the process works for blocking PRs with dependent Gravity changes, but my gut says this should be fine to merge since it's only an addition.

Adds is_followed to show

---

_schema.graphql
src/lib/loaders/searchLoader.ts
src/schema/search/SearchEntity.ts
src/schema/search/index.ts

Expand the current list of supported entity types (Artist, Artwork) to:
Artist, Artwork, Article, City, Collection, Fair, Feature, Gene, Profile, Sale, and Tag.
Note: The `Collection` entity type is currently only supported for the `AUTOSUGGEST` search mode.
Next steps:
- Add support for the `Collection` entity type on the `SITE` search mode in Gravity.
- Add `Searchable` interface support to these full types in Metaphysics, allowing queries including type-specific attributes.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-729 :lock:

Support additional entity types during search

---

src/lib/__tests__/graphqlErrorHandler.test.ts
src/lib/graphqlErrorHandler.ts

Saw that we were reporting these 404s again:
* https://sentry.io/artsynet/metaphysics-production/issues/810021918/?query=is%3Aunresolved
* https://sentry.io/artsynet/metaphysics-production/issues/873514466/?query=is%3Aunresolved

[graphqlErrorHandler] Fix us reporting all errors but syntax errors.

---

src/lib/loaders/__tests__/tracked_entity.test.js
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/loaders_with_authentication/tracked_entity.ts
src/schema/__tests__/gene.test.js
src/schema/__tests__/show.test.js

This came up in [a PR discussion yesterday](
https://github.com/artsy/metaphysics/pull/1497#discussion_r254783623). This PR refactors `trackedEntityLoaderFactory` to use an options object instead of positional parameters; we agreed this was a good idea and doing it sooner is easier than waiting.

Refactors trackedEntityLoaderFactory to use options param

---

src/lib/loaders/api/extensionsLogger.ts
src/lib/loaders/api/loader_with_authentication_factory.ts
src/lib/loaders/api/loader_without_authentication_factory.ts

Adds the ability you log out the size of a request received by MP. Does not do it in cached requests, because there aren't headers for the size.
Uncached:
Cached:

Adds the size of the data to the extension logger

---

src/schema/__tests__/search.test.ts
src/schema/searchableItem.ts

Noticed that we get Genes back (but display them as 'Category'), Profiles (but display them as Gallery/Institution/Fair), and also Sales (but display them as 'Auction').
Left one very big TODO about the sale/auction stuff!

@dblandin => [Searchable] Translate some labels into more UI friendly strings

---

_schema.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/schema/fair.ts

This adds a new field to fairs in metaphysics, `followed_content`. Inside of followed content are `artists` and `galleries`, which embed raw arrays containing artwork and galleries that the current user follows AND which are affiliated with this fair.
This is tricky to test, and gravity caching seems to make it a little trickier. The bulk of the work here was actually around getting viable data into gravity that represented sufficient complexity to test that this code works as expected. Right now, I just ran the data setup code you'll find below, so this data all lives on the gravity staging server. (It'll be wiped over the weekend, though, so someone should rerun it on Monday if necessary!)
```
User.where(email:'local_disco_user@artsymail.com').count > 0
app = …
```

Fix fair follows

---

_schema.graphql
src/data/kaws.graphql
src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
src/lib/stitching/kaws/stitching.ts

~~Unfortunately this doesn't work :((~~
~~I think everything is updated properly, and this seems to conform to examples.~~
~~It doesn't like the `size` param.~~
```
{
artist(id:"kaws") {
marketingCollections(size: 4) {
id
}
}
}
```
~~results in `"Unknown argument \"size\" on field \"marketingCollections\" of type \"Artist\"`~~
EDIT: works!!

@orta => [Stitching] Pass size param to KAWS collections for an artist

---

src/schema/__tests__/formattedDaySchedules.test.ts
src/schema/types/formattedDaySchedules.ts

This change is to support a fix for the bug described in [LD-211](https://artsyproduct.atlassian.net/browse/LD-211), which is where an empty schedule was showing up in the app as the following ("Monday–Sunday: Closed"):
Gravity is serving up an empty `location.day_schedules` array, so the issue is that Metaphysics is misinterpreting empty data. There was no test for empty schedules, so I asked on Slack if this was intended (not likely, since this logic was recently ported from Force and isn't used in Reaction, Volt, or even Force itself yet). 
With the new change, clients can check for an empty array. Here's the difference in the query response:
| Before | After |
|--------|-------|
| <img width="1211" alt="screen shot 2019-02-14 at 4 27 27 pm" …

Returns empty formatted schedules for empty schedules.

---

src/schema/asset_uploads/__tests__/create_asset_request_mutation.test.js
src/schema/asset_uploads/__tests__/finalize_asset_mutation.test.js
src/schema/asset_uploads/create_asset_request_mutation.ts
src/schema/asset_uploads/finalize_asset_mutation.ts

finishes https://artsyproduct.atlassian.net/browse/AUCT-64
It seems that a `()` is missing when a function is returned from a factory `loader` function, causing the `createGeminiEntryForAsset` and `requestCredentialsForAssetUpload` mutations to fail due to a return value mismatch. This PR adds a missing `()` so the function actually does the work.

Fixes an issue where Gemini-related mutations always return an error

---

_schema.graphql
src/schema/__tests__/fair.test.js
src/schema/fair.ts

- Restructures `exhibitors_grouped_by_name` to have one array of `exhibitor` objects and adds correct `profile_id`

Restructures exhibitors_grouped_by_name

---

_schema.graphql
src/lib/stitching/kaws/__tests__/stitching.test.ts
src/lib/stitching/kaws/stitching.ts
src/schema/filter_artworks.ts

[[[GROW-1005]](https://artsyproduct.atlassian.net/browse/GROW-1005)](https://artsyproduct.atlassian.net/browse/GROW-1005)
When fetching collections info from Kaws, set keyword_match_exact parameter to true if collections has keywords for artwork filters.
[GROW-1005]: https://artsyproduct.atlassian.net/browse/GROW-1005

Set keyword_match_exact when keywords are set on a Kaws collection.

---

src/schema/__tests__/search.test.ts
src/schema/searchableItem.ts

Hooks up links to remaining items (cribbed from https://github.com/artsy/force/blob/a6ac904b489f8e07c25f96f8e0f01efba6ce0cb8/src/desktop/models/search_result.coffee#L37) so that other types work w/ linking. Also tweaked display so `MarketingCollection` -> `Collection`

@jonallured => [Autosuggest] Hook up /href linking to searchable items

---

src/index.ts

Follow-up to #1520
Fixes queries that use `viewer`.

Insert rootValue object to resolvers for those that relied on it.

---

_schema.graphql
src/data/kaws.graphql
src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap

Address: https://artsyproduct.atlassian.net/browse/GROW-1145
This is a part of the work to add support for randomizing collections and updates the kaws schema in metaphysics.

update kaws schema to include new randomize argument

---

_schema.graphql
src/schema/ecommerce/query_helpers.ts
src/schema/ecommerce/types/order.ts

We'll need to reference this in reaction when deciding whether or not to allow you to visit the `/payment/new` page.

Exposes lastTransactionFailed from exchange

---

src/schema/__tests__/show.test.js
src/schema/show.ts

fixes https://artsyproduct.atlassian.net/browse/LD-300
We were passing wrong param to Gravity when filtering by show.

Fix wrong artwork filtering on show page

---

src/schema/__tests__/fair.test.js

Some how this failing spec slipped passed Circle CI in [this PR](https://github.com/artsy/metaphysics/pull/1536). This open PR fixes that and [restores the master build](https://circleci.com/gh/artsy/metaphysics/4202). It's weird because the [build on the initial PR showed green](https://circleci.com/gh/artsy/metaphysics/4197) but failed when it ran against master. I've seen this happen in kaws and I thought it was an isolated issue.
@orta and ideas why this is?

fixes failing test

---

src/lib/all.ts
src/lib/loaders/__tests__/api.test.ts
src/lib/loaders/api/index.ts
src/lib/loaders/api/loader_interface.ts
src/lib/loaders/api/loader_with_authentication_factory.ts
src/lib/loaders/api/loader_without_authentication_factory.ts
src/lib/loaders/api/loader_without_cache_factory.ts
src/lib/loaders/index.ts
src/schema/__tests__/fair.test.js
src/schema/city/index.ts

Closes https://artsyproduct.atlassian.net/browse/LD-284
This PR also:
* Actually passes one-off API options to the loader, such as `requestThrottleMs` (cc @mzikherman I think you added some of these in the past and so that never really worked previously)
* Disables a broken test, see 
https://github.com/artsy/metaphysics/pull/1536/files#r262078512

Cache city shows and fairs for a day

---

src/lib/loaders/loaders_with_authentication/tracked_entity.ts

This is to avoid running into a `414 – Request-URI Too Long` from Gravity.

[trackedEntityLoader] Batch in chunks of 200 IDs.

---

src/schema/__tests__/city.test.ts
src/schema/city/index.ts

When getting shows in a city, we were getting fair booths, these would show up as shows with location id but without coordinates.
Gravity provides a param for filtering out fair booths, we now by default set `at_a_fair` flag to `false` for these queries.

Exclude fair-booths from shows in a city

---

.vscode/settings.json
_schema.graphql
src/lib/shared_resolvers/followedArtistsResolver.ts
src/schema/me/followed_artists.ts
src/schema/show.ts

https://github.com/artsy/gravity/pull/12185
Add `followedContents` to `show` type so we can get user's followed artists in a specific show.
We can wait till https://github.com/artsy/gravity/pull/12185 gets into prod to merge this.
```graphql
show(id:'something') {
followedArtists{
id
edges {
node{
artist{
id
}
}
}
}
}
```

Add followedContents to fetch followed artists in a show

---

_schema.graphql
src/lib/sponsoredContent/data.json
src/lib/sponsoredContent/index.ts
src/schema/__tests__/city.test.ts
src/schema/__tests__/fair.test.js
src/schema/city/index.ts
src/schema/fair.ts

https://artsyproduct.atlassian.net/browse/LD-316
This PR introduces a home for the little bits of static sponsored content — prose descriptions, hyperlinks — that need to show up in certain client contexts such as the city view and the fair view in Eigen.
The content is stored in a [json file](https://github.com/artsy/metaphysics/commit/5f3d301323d707b0fa8179456115c92e38ffa97b#diff-545f2f7a00f714e6b0739c868b93f0b5), and made available through a `sponsoredContent` field that is now available on `city` and `fair`:
If these fields are requested when there is no content, it's just `null`:

Add static sponsored content

---

_schema.graphql
src/lib/loaders/searchLoader.ts
src/schema/__tests__/search.test.ts
src/schema/fields/pagination.ts
src/schema/search/SearchAggregation.ts
src/schema/search/index.ts

Still need to add some specs (and make sure it's all working right!).
You'll be able to include 
``` js
aggregations {
slice
counts {
count
name
}
}
```
as a fragment on `SearchableConnection`.
The result will look like:
```
aggregations: [
{
slice: "TYPE",
counts: [
{
count: 100
name: "artwork"
}
{
count: 100
name: "artist"
}
]
}
]
```

@dblandin => [Search] Expose aggregations for entity type and counts

---

src/schema/__tests__/search.test.ts
src/schema/searchableItem.ts

Fixes the href for a marketing collection search result item (from `/marketingcollection/:slug` to `/collection/:slug`).

@dblandin => [Autosuggest] Correct href attribute for marketing collection results

---

src/lib/all.ts
src/schema/city/index.ts

Fixed by https://github.com/artsy/gravity/pull/12196
Related to https://artsyproduct.atlassian.net/browse/LD-305
Still want to test this out first when Gravity is deployed to staging.

[allViaLoader] No longer need to fetch any content to get /shows count.

---

_schema.graphql
src/schema/__tests__/city.test.ts
src/schema/city/index.ts

Closes: https://artsyproduct.atlassian.net/browse/LD-315
Implements subtask: https://artsyproduct.atlassian.net/browse/LD-333
This closes the loop on partner type bucketing in the city shows query (following https://github.com/artsy/gravity/pull/12190 and https://github.com/artsy/gravity/pull/12198).

Add partner-type filtering to city shows field

---

_schema.graphql
src/schema/__tests__/city.test.ts
src/schema/city/index.ts

Depends on https://github.com/artsy/gravity/pull/12191
Deprecate current `discoverable` argument and for time being resolve that to `displayable: true` and `include_local_discovery: true`.
Introduce new `includeStubShows` and `displayable` as alternative of `discoverable`.

Add includeStubShows and displayable and deprecate discoverable

---

src/schema/__tests__/city.test.ts
src/schema/city/index.ts

Discussed here: 
https://github.com/artsy/emission/pull/1385#discussion_r263934065 Follow up from #1559.
When making a query with a null `partnerType` (something the schema allows), Gravity was throwing an error:
```
https://stagingapi.artsy.net/api/v1/shows?at_a_fair=false&displayable=true&has_location=true&include_local_discovery=true&max_distance=25&near=51.51%2C-0.13&page=3&partner_types=&size=10&sort=start_at&status=current&total_count=true - {\"type\":\"param_error\",\"message\":\"Invalid parameters.\",\"detail\":{\"partner_types\":[\"does not have a valid value\"]}}
```
This PR changes metaphysics to only send the `partnerType` param to Gravity if it's truthy.

Allows null partner type for show parameters

---

_schema.graphql
src/schema/__tests__/city.test.ts
src/schema/city/index.ts
src/schema/input_fields/event_status.ts

https://artsyproduct.atlassian.net/browse/LD-337
Added new `dayThreshold` argument to `city { shows (...)}` which can be used to filter shows in `UPCOMING` and `CLOSING_SOON` states.
https://github.com/artsy/gravity/pull/12204

Add optional dayThreshold and new ClosingSoon status

---

_schema.graphql
src/schema/show.ts

This converts the field name on Show to our favored terminology, deprecates the old one (and fixes an ambiguous related description).
#skip_camel

Deprecate is_local_discovery in favor of isStubShow

---

_schema.graphql
src/schema/location.ts

https://artsyproduct.atlassian.net/browse/LD-221
We already have 3 fields describing day schedules in different ways for a `Location`
- `day_schedules`: Array of `DayScheduleType` set mostly by partners themselves
- `day_schedule_text`: A string set by artsy admins
- `displayDaySchedules`: currently a field that formats `day_schedules` data to array of `FormattedDaySchedules`
Currently clients need to decide which field to use, we want to have MP be the source of truth and have the priority logic about which one to use?
Added a new `openingHours` field which is a union of `OpeningHoursArray` and `OpeningHoursText`, if we have `day_schedules` we resolve this field to `OpeningHoursArray` otherwise we use `OpeningHoursText`.
```graphql
{
show(id: "galerie-crone-emmanuel-bornstein-clinamen") …
```

Display DaySchedule union

---

src/schema/__tests__/city.test.ts
src/schema/city/index.ts

The schema permits sending `null` values, and Emission needs to do that so we can use a single query renderer for city section lists (ie: upcoming, galleries, museums, closing soon).

Fixes shows resolver to accept null status/dayThreshold values

---

src/schema/__tests__/city.test.ts
src/schema/city/index.ts

https://artsyproduct.atlassian.net/browse/LD-392
Follow-up to https://github.com/artsy/metaphysics/pull/1563#discussion_r264039531
Sponsored content shows can be either stubs shows _or_ plain old partner-provided shows. If the latter, they should obey the normal constraints around `displayable`-ness, which is what this PR adds. h/t @ashkan18 for catching this.
#trivial

Ensure non-stub sponsored shows follow normal displayable rules

---

_schema.graphql
src/schema/sorts/partner_show_sorts.ts

Add support for new `PARTNER_ASC` sort for `PartnerShow` type.
At the moment Gravity doesn't support it yet but this is so Emission could start using it while we figure out how to support it on Gravity end. For now it will just do a `name` sort. 
https://artsyproduct.atlassian.net/browse/LD-380

Add support for PARTNER_ASC sort option for partner_shows

---

src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/utilities.ts

Had a chat with Stephen about why [this work](https://staging.artsy.net/artwork/robert-natkin-sonoma-mission-inn-signed-twice-and-inscribed-with-heart-drawing
) wasn't available for VIR. Figured we could give it a shot for 2d works with depth under and inch.

Support showing an artwork as VIRable when it's depth is under and inch

---

src/lib/loaders/loaders_without_authentication/gravity.ts
src/lib/stitching/kaws/__tests__/stitching.test.ts
src/lib/stitching/kaws/stitching.ts

Adds new dataloader `filterArtworksLoaderWithCache` for use on collections.  Current cache time is 1 hour.

Add filterArtworksLoaderWithCache

---

_schema.graphql
src/schema/me/followed_shows.ts

This allows consumers of the `me.followsAndSaves.shows` query to use an optional `city` argument. This argument must be one of the pre-determined city slugs that are tracked in `metaphysics/src/schema/city/cityDataSortedByDisplayPreference.json`, and Metaphysics will return an error that enumerates valid city slugs if an invalid string is passed in.
First, we've got to create some mock data. Let's create two shows, one in New York and one in Hong Kong, and then follow both with the User we're using in GraphiQL. As this PR, the following data already exists - feel free to lookup and reuse for your own testing, or feel free to make your own.
```ruby
user = User.find_by_email("mykola.bilokonsky@artsymail.com").first
location_nyc = PartnerLocation.create!(name: 'nyc_location', coordinates: …
```

Add optional `city` argument to me.followsAndSaves.shows

---

src/lib/sponsoredContent/data.json

Once this PR deploys, sponsored show listings and preview bricks will be out of sync until the next production → staging copy
#trivial

Associate sponsored show data in production

---

src/schema/city/cityDataSortedByDisplayPreference.json

Now that (a) we've consolidated LD geo truth in this file, and (b) we might be ready to tackle map viewport constraints, I'm adding these max bounds to our city file.
These results come from my Observable notebook. Here's the NYC example:
- Purple represents our LD search radius of 25km
- Red represents a buffer of 50km beyond that
- Green represents the bounding box that encompasses the buffer area
In my experience we'd want a generous buffer zone around the area of interest so as not to make the map feel overly confining. But this is all tune-able, of course.
As for how to specify the actual bounding box rect 🙄 of course there are like seventeen ways to do this.
But according to this ["Restrict map panning to an area"](https://docs.mapbox.com/ios/maps/examples/constraining-gestures/) …

Adds max bounds per city to constrain LD map panning

---

_schema.graphql
src/lib/sponsoredContent/data.json
src/lib/sponsoredContent/index.ts
src/schema/__tests__/city.test.ts
src/schema/city/index.ts

https://artsyproduct.atlassian.net/browse/LD-454
This fixes an issue where sponsored content shows are returned from Grav to MP to Emission in unspecified order, which prevents us from relying on the order of results to pull out the first two shows for featuring in illustrated bricks.
Instead we can add a separate field guaranteed to have the correct shows.
```graphql
{
city(slug: "new-york-ny-usa") {
slug
name
sponsoredContent {
featuredShows {
id
}
}
}
}
```

Support querying featured sponsored shows explicitly

---

_schema.graphql
src/schema/input_fields/event_status.ts

This is to unblock Emission, for now mapping it to `current` till we figure out how to support this in Gravity.

Add new running_and_upcoming status

---

_schema.graphql
src/lib/loaders/loaders_with_authentication/gravity.ts
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/__tests__/sendFeedbackMutation.test.ts
src/schema/schema.ts
src/schema/sendFeedbackMutation.ts

This adds a mutation that lets us send feedback (currently needed for search results).
It uses the existing `/api/v1/feedback` endpoint so that it's hooked into the same place our current 'Send Feedback' functionality lives. It is emailed to support@, and also an event is propagated on event queues, so there's other things happening: posts to Slack, semantic analysis on whether the message is positive/negative/neutral, etc.

@dblandin => [Feedback] Add mutation to send feedback

---

src/lib/loaders/loaders_without_authentication/gravity.ts
src/lib/stitching/kaws/__tests__/stitching.test.ts
src/lib/stitching/kaws/stitching.ts

Follow up to https://github.com/artsy/metaphysics/pull/1575, removes dataloader `filterArtworksLoaderWithCache` in favor of explicitly adding caching to the Kaws stitching file.

Move Kaws caching to stitching file

---

src/lib/__tests__/date.test.ts
src/lib/date.ts

- https://artsyproduct.atlassian.net/browse/LD-304
- Previously the date range didn't include the end year if the end year was the same as the present year. E.g. It would display `Apr 10, 2016 - Feb 16` instead of `Apr 10, 2016 - Feb 16, 2019`

LD-304 - Updates date exhibitionPeriod format

---

src/schema/city/cityDataSortedByDisplayPreference.json

We chose a center point for HK that was a sort of good centroid-ish point based on the actual distribution of partners we had there. However that point happened to fall on a body of water, which is leading to bad UX in the current iteration of the LD map. 
IANA HK expert but I am nudging the center point to a major intersection near a cluster of partners in the Central district:
And while I'm in here finessing neighborhoods I'm also going to drop my earlier pedantry about the precision these lat/lng floats should have. Bumping up to 3 sig digs, which gives us [neighborhood/street level precision](https://en.wikipedia.org/wiki/Decimal_degrees#Precision).

Nudge Hong Kong for LD

---

_schema.graphql
dangerfile.ts
src/lib/loaders/searchLoader.ts
src/schema/__tests__/search.test.ts
src/schema/search/SearchEntity.ts
src/schema/search/index.ts

For 'short' result sets (< 5 pages, for whatever the page size requested is), `pageCursors.last` isn't present (all the cursors are contained in `around`), and so this check was failing.
Updates the `hasNextPage` logic to be more consistent.
Also...noticed a `debugger` statement sneaked in :( , so added a Danger rule for there as a bonus 😅

@dblandin => [SearchResults] Fix `hasNextPage` calculation for short result sets

---

src/schema/__tests__/show.test.js
src/schema/show.ts

https://artsyproduct.atlassian.net/browse/LD-468
We've observed that it's not possible to tap into _some_ shows in the app, usually (but not always) stub shows.
Gravity returns them but MP doesn't. That is likely because they are being 404'd due to not being [_either a displayable show or a reference show or a fair booth_](https://github.com/artsy/metaphysics/blob/0e1658cb735102ff53640a9e7c8ab4e54f61ce92/src/schema/show.ts#L653-L655)
This PR prevents stub shows by being filtered out in this way, by adding stub shows to the allowlist above.
A good question is why we don't see this more often. I'm not certain, but it's possibly because we tend to tap into stubs that _also_ happen to be displayable by virtue of having install shots (such as the sponsored content shows).
In any case, this …

Do not filter out stub shows from show query

---

src/lib/loaders/index.ts
src/lib/stitching/kaws/__tests__/stitching.test.ts
src/schema/__tests__/filter_artworks.test.js
src/schema/__tests__/gene.test.js
src/schema/__tests__/show.test.js
src/schema/__tests__/tag.test.js
src/schema/artist/__tests__/index.test.js
src/schema/filter_artworks.ts

This implements what we've been discussing, namely, for our filter endpoint we can introspect on the params, and if they're not personalized, we can fall back to the cached loader.
Since all the loaders are merged at the root of context, we added a separate `unauthenticatedLoaders` and `authenticatedLoaders` key.
@eessex the KAWS stitching in place here: https://github.com/artsy/metaphysics/blob/1a7167465f572063b6c3970d4dd63600a73e3e4b/src/lib/stitching/kaws/stitching.ts#L122 is no longer quite valid, in all cases (auth and unauth) we will be using the cached loader w/ 5 second refresh. We can pair next week on cleaning that up and propagating.

@alloy => [Loaders] Always use cached loader when filter arguments permit

---

src/lib/stitching/kaws/__tests__/stitching.test.ts
src/lib/stitching/kaws/stitching.ts

This wraps up https://github.com/artsy/metaphysics/pull/1597 , by making sure that we inject a longer cache option for the KAWS resolving of filter artworks.

@joeyAghion => [Stitching] Inject longer cache into stitched KAWS filter loader

---

hokusai/config.yml
hokusai/staging.yml

Set up Nginx as a sidecar container in Metaphysics staging, serving both http and https with artsy.net wildcard certificates.  Also create an internal cluster service for Metaphysics mapping ports 80 and 443 to the Nginx container.  This will allow us to resolve, for example, `metaphysics-staging.artsy.net` to `metaphysics-web-internal.default.svc.cluster.local` by means of Kubernetes' internal DNS server, and transparently route all traffic originating from within the cluster through the cluster-internal service (fixing the "hairpin" traffic pattern we now have, where `metaphysics-staging.artsy.net` resolves to the CNAME of an external ELB, and traffic is routed out of Kubernetes' internal network, to the external ELB then back into the Kubernetes' internal network.
Also running a …

add Nginx to metaphysics staging and internal cluster service

---

src/schema/artist/__tests__/carousel.test.js
src/schema/artist/carousel.ts

This was added at a time where we were trying to filter out ephemera and reproductions from the carousel. Since that time, upstream changes have caused this filtering to be no longer needed and, in fact, to be filtering more than it should be.
All this PR does is remove the filtering function.

DISCO-720: Remove stale artwork filter

---

_schema.graphql
src/schema/__tests__/fair.test.js
src/schema/fair.ts

https://artsyproduct.atlassian.net/browse/LD-503
This adds a new `isActive` field (and deprecates the old `is_active` field).
The new `isActive` field's definition is:
- true when the fair's `active_start_at` is in the past and `end_at` is in the future
- false otherwise
#skip_camel

Expose an isActive flag on Fair

---

_schema.graphql
src/schema/show.ts

This just exposes the `press_release_url` field on the underlying show.  The field does not exist / has not been populated yet, but will be shortly. This work simply unblocks some Emission work for the next release.
```graphql
{
show(id: "pace-prints-david-hockney-etchings-1") {
id
pressReleaseUrl
}
}
```

Expose pressReleaseUrl on Show

---

src/schema/__tests__/city.test.ts
src/schema/city/index.ts

We want to by default exclude shows that were blocked from discovery in `city` query used in City Guide.
https://artsyproduct.atlassian.net/browse/LD-370
Use [newly added Gravity param](https://github.com/artsy/gravity/pull/12214) and send `false` by default to exclude these shows.

Exclude shows that were blocked from discovery

---

src/lib/loaders/loaders_without_authentication/gravity.ts

The other day, we struggled to confirm _any_ visible performance improvements from switching to the cached and unauthenticated loaders for any filter requests that don't require personalized responses. This was even after confirming locally and in staging the expected behavior. This [we think] was due to a few things:
* The request-throttling is only good for 5 seconds and handled _per-process_. In production there are quite a few horizontally scaled processes serving traffic, so we wouldn't see rapid consolidation of requests.
* There are still multiple search requests being made to serve each response. We couldn't figure out why, but ticketed the most egregious cases.
This PR doesn't solve either of those, but does attempt to extend the 5 second period in which any single pod won't …

Attempt to extend expiration of memoized filter responses

---

src/lib/loaders/searchLoader.ts
src/schema/artist/carousel.ts
src/schema/search/SearchEntity.ts

Over on artsy/reaction#2182 I added the list of entities that would work for autosuggest searches, but @mzikherman advised me to move that up the chain so that MP actually knows which ones are right for suggest searches. This PR refactors the search loader to use objects for the fallback entities and path, then I added a new const to list the suggest entities.

Exclude show from suggest search

---

src/schema/show.ts

The data for a show is cached with a long TTL by the 'city' loader/schema.
Some of the fields of a show schema, wind up needing to make further requests to resolve (and can't just be resolved from the cached show data).
For fields in the show schema that make further requests (such as `cover_image`), they need to be made resilient to these further requests crashing, due to inconsistencies in the long lived cache of city shows, and actual shows (for example, a show might be deleted).
This adds that to `cover_image`. If you can take a look at the various queries used for Local Discovery, if there are other references to fields in this schema that need to make further requests to resolve, we can add a `catch` there too.

@ashfurrow => [Show] Allow cover_image to return null if the show doesnt exist

---

src/schema/input_fields/event_status.ts
src/schema/me/__tests__/followed_shows.test.ts

This is a tiny change in the source file, but I took the opportunity to add a few more tests to our followed_show spec. Now, there's a case to be made that this test doesn't really help us - that the GraphQLEnumType constrains values enough. But this change made me think about the fact that for a while we had:
```
RUNNING_AND_UPCOMING : {
value: "current"
}
```
I dunno about y'all but once I have enum keys to read I rarely go look at the values. In this case, it seemed reasonable to assert that our enum keys correspond directly to our enum values - if that ever changes again, this test will have to change, and anyone reading the tests to figure out why they keep requesting `status=FOO` but the system keeps returning data as if it had requested `status=BAR` will get a useful piece of …

Emission queries for 'running_and_upcoming' now redirect correctly.

---

src/schema/__tests__/causality_jwt.test.js
src/schema/causality_jwt.ts

There is a [bug][1] where Metaphysics raises an exception due to `sale.partner` being `null`. This commit fixes it so the client can run a more reliable check rather than just checking a raw Javascript error message.
Also, the test needs to call `done()` otherwise the test will call no `expect`s and it will just pass.
[1]: https://sentry.io/organizations/artsynet/issues/841789531/?project=299973&query=is%3Aunresolved&statsPeriod=14d&utc=false

Fixes a bug where CausalityJWT resolver fails due to Cannot read property '_id' of null

---

src/lib/__tests__/graphqlTimeoutMiddleware.test.ts

For some reason the delay call does not wait enough in CI, so let's see if increasing delay fixes it.

Fix builds by increasing wait time

---

docs/adding_a_new_graphql_microservice.md

So that people can see their stitched queries going upstream

Note the env var when stitching 

---

src/schema/__tests__/filter_artworks.test.js
src/schema/filter_artworks.ts

This was all that was needed to allow the Reaction component to specify a `page: $page` style variable for the filter, and thus load any arbitrary page from a number! This was that annoying bug where the filter wouldn't respect an incoming page param from URL.

@damassi => [FilterArtworks] Allow a page param to be specified and override cursor

---

hokusai/production.yml

Set up Nginx and metaphysics for internal Kubernetes DNS resolving `metaphysics-production.artsy.net` to `metaphysics-web-internal.default.svc.cluster.local`

add Nginx and metaphysics-web-internal service to production #PLATFORM-1306

---

_schema.graphql
src/schema/__tests__/filter_artworks.test.js
src/schema/__tests__/search.test.ts
src/schema/fields/pagination.ts
src/schema/filter_artworks.ts
src/schema/search/index.ts

Much like https://github.com/artsy/metaphysics/pull/1633
There's also a bug fix for that initial PR. I noticed that when jumping in on an arbitrary page from the URL, clicking 'Next' wasn't working since our calculation for `endCursor` was incorrect. We need to calculate that ourselves from the incoming page param, vs rely on the lib to calculate it from the connection cursor params...since there _are_ no incoming cursor params when you initially load at an arbitrary page.
I tested this locally and everything seems hunky-dory. Also have a Reaction PR that adds pagination to 'Artists' tab.

@damassi => Add support for jumping in to the search connection w/ arbitrary page

---

src/schema/SearchableItem/SearchItemRawResponse.ts
src/schema/SearchableItem/SearchableItemPresenter.ts

Define a `SearchItemRawResponse` type for objects returned from gravity and use instead of `any`.

Update SearchableItemPresenter to use new type

---

src/schema/city/index.ts

This should prevent the issue where deprecated/hidden shows still show up in certain tabs in City View for much longer than expected.

Reduce city query's TTL from 24 hours to 2

---

_schema.graphql
src/schema/SearchableItem/SearchItemRawResponse.ts
src/schema/SearchableItem/SearchableItemPresenter.ts
src/schema/SearchableItem/__tests__/SearchableItemPresenter.test.ts
src/schema/SearchableItem/index.ts

Use `start_at`, `end_at`, `venue`, `location`, and `artist_name` attributes of the search result item from Elasticsearch to generate a formatted description for `PartnerShow` entities.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-867 :lock:

Add SearchableItem description formatting for PartnerShow entity type

---

src/schema/SearchableItem/SearchableItemPresenter.ts

When building up the description for shows and fair booth search result items, make sure that we're comparing moment timestamps within the same UTC zone.
Should address this flickering spec: https://circleci.com/gh/artsy/metaphysics/4712

Make sure that we're comparing timestamps in the same zone

---

src/schema/SearchableItem/SearchItemRawResponse.ts
src/schema/SearchableItem/SearchableItemPresenter.ts
src/schema/SearchableItem/__tests__/SearchableItemPresenter.test.ts
src/schema/SearchableItem/index.ts

Indexed shows are occasionally returning a 404ing missing_image.png asset url. Until we can address that issue at index time, patch the attribute here.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-895 :lock:

Override 404ing missing_image.png asset reference

---

.vscode/settings.json
peril/schemaValidatorUtils.ts
peril/upstreamSchemaValidator.ts
src/integration/__tests__/runStoredQueryTests.ts

Adds a way for us to validate that a PR changing any `schema.graphql`s have been updated.
What it does is:
- There is a map of services to their prod/staging endpoints
- We see if any of the PRs modified files include the schemas for those endpoints
- If they do then compare the fs copy of the schema SDL in Metaphysics to the prod/staging SDL in the API
- Then do a breaking change check for all those schemas
- If anything is broken then fail/warn on the PR
What this can't do:
- Deploys are still done on a person's computer, so it can't do production check. If we moved to PR based deploys for MP, then it would check _all_ schemas to ensure no breaking changes between prod and the versions in the fs.
Could be a good reason to move to PR deploys.

Upstream schema checking

---

src/schema/search/SearchResolver.ts
src/schema/search/index.ts

- Move search resolver logic to separate file
This allows us to better encapsulate the resolution behavior from the GraphQL interface/schema definition. We'll be able to add on more optimizations with this split in place.
- Memoize query introspection during search query resolution
ticket: https://artsyproduct.atlassian.net/browse/DISCO-865 :lock:

Memoize query introspection during search query resolution

---

src/schema/search/SearchResolver.ts

This was accidentally left out during a recent change:
https://github.com/artsy/metaphysics/pull/1643/files#r272283282

Restore handling of null page number in search resolver

---

src/schema/__tests__/partner_show_events.test.ts
src/schema/partner_show_event.ts

https://artsyproduct.atlassian.net/browse/LD-561
@kierangillen and I have been pairing on this fix for incorrect times displaying in City Guide for partner show events.
Currently datetimes for `PartnerShowEvents` — e.g. opening receptions, artist talks, and other one-off events that are associated with a show — are sent from CMS to Gravity without timezone information, and these get stored in the db as having a UTC offset of +00:00. They are returned this way over the wire as well by MP:
```graphql
{
"data": {
"show": {
"id": "helwaser-gallery-anton-ginzburg-views",
"events": [
{
"start_at": "2019-03-28T18:00:00+00:00",
"end_at": "2019-03-28T21:00:00+00:00"
},
{
"start_at": "2019-04-13T14:00:00+00:00",
"end_at": "2019-04-13T16:00:00+00:00"
}
]
}
}
}
```
Previously other clients [have …

Use custom date resolver for partner show events

---

src/schema/SearchableItem/SearchableItemPresenter.ts

Compare now, at the beginning of the day, with show / fair booth start/end timestamps.

Pin comparison date to start of day

---

src/schema/__tests__/causality_jwt.test.js
src/schema/causality_jwt.ts

fixes https://artsyproduct.atlassian.net/browse/AUCT-313
The check that got removed in this commit: https://github.com/artsy/metaphysics/commit/9e39a429e85052f54348986ddb7fb8a6356b7b13?w=1#diff-873fe1c7874f0eb5e4c8c9caed5efd90L105 should not have been removed. Because of the lack of the check any partner could open the Operator2 for any auction. This PR brings the check back to fix it.

Partner operator shouldn't be able to access another partner's auctions

---

src/lib/stitching/vortex/__tests__/pricingContext.test.ts
src/lib/stitching/vortex/stitching.ts

This PR updates our logic to hide the histogram in some more cases!
Current logic is:
- artwork is _not_ in an auction
- artwork has a visible price listed in USD (could be range or exact)
- artwork has 1 artist
- artwork is for sale
- artwork has a width/height
- artwork has a category (edited) 
Verified with these artworks:
- not for sale: andy-warhol-mao-102
- no height or width: andy-warhol-chateau-mouton-rothschild-premier-cru-classe-en-1975
- no category: andy-warhol-dollar-sign-yellow-fs-ii-dot-278
- non-USD: andy-warhol-heian-shrine-kyoto-japan
- multiple artists: andy-warhol-andy-warhol-and-jamie-wyeth-portraits-of-each-other-signed-by-both-wyeth-and-warhol
- no list price: andy-warhol-volkswagen
- hidden list price: andy-warhol-alexander-the-great-trial-proof-fs-iib-dot-291

Conditionally show histogram on artwork page

---

src/lib/sponsoredContent/data.json

This simply removes some dummy content to prevent it showing up in the iOS app.
#trivial

Remove placeholder content from sponsored content fair activations

---

src/lib/__tests__/date.test.ts
src/lib/date.ts

In my timezone, these tests were breaking with:
```
Expected: "Jan 1, 2011 – Apr 19, 2014"
Received: "Dec 31, 2010 – Apr 18, 2014"
```

[date] Fix tests breakage due to TZ ambiguity.

---

src/schema/fields/__tests__/date.test.js
src/schema/fields/date.ts

I came across some weird behaviour from Metaphysics when working on [this PR](https://github.com/artsy/reaction/pull/2282). It appeared as though various dates on MP's `Sale` type were being resolve to that literal string `"Invalid date"`:
I confirmed with Reaction's MP logging middleware that these strings were _actually_ being returned from MP, but visiting the in-browser GrapiQL interface shows all the results as `null`:
So this is weird, eh? We even have code in Reaction that works around this bug:
https://github.com/artsy/reaction/blob/2d9f867189e716f6881d8d8c6792bcd24a47c23b/src/Components/v2/AuctionTimer.tsx#L25-L28
`"Invalid date"` is [moment's default value for unparsable dates](https://github.com/moment/moment/blob/d0f0dd8f40be987593767a3dc5e27c45c6a3fa49/moment.js#L451); I took …

Returns null for missing dates

---

src/schema/__tests__/ecommerce/buyer_counter_offer_mutation.test.ts
src/schema/ecommerce/buyer_counter_offer_mutation.ts

Related to #incident-36
The response from this mutation gets used to populate the relay store and render the counter offer "review" page. Because we weren't including the `creditCardId` here, metaphysics was unable to resolve and was returning `null` for the credit card.
Since we recently [updated the display](https://github.com/artsy/reaction/pull/2275/files#diff-a25e611754f0b81c6407b2690f479f87R30) of the `CreditCardDetails`, a `null` credit card started causing the page rendering to error based on this missing field. (Note this wasn't an issue before because after the response from the mutation, we make another query that _does_ include the proper `creditCardId`).
The real follow-up is to remove all of this fake-stitching. 😄

Return credit card ID from buyer counter mutation

---

src/schema/SearchableItem/SearchableItemPresenter.ts
src/schema/SearchableItem/__tests__/SearchableItemPresenter.test.ts

Auction start and end times are currently input by Artsy staff in UTC time.
Staying consistent with how we display auction times on artsy.net, convert the timestamps from UTC to the `America_New_York` timezone for display on the search results page.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-905 :lock:

Use Eastern Time when formatting timestamps for auction search results

---

src/schema/SearchableItem/SearchableItemPresenter.ts

The previous style resulted in `undefined` appended to the formatted string when location was unavailable.

Fix location formatting in SearchableItemPresenter

---

src/lib/loaders/__tests__/batchLoader.test.ts
src/lib/loaders/batchLoader.ts

When the sales endpoint is being called _without_ an id, ensure we short circuit the batching process.

When a list endpoint is requested without an id, skip batching

---

_schema.graphql
src/schema/sale/__tests__/index.test.js
src/schema/sale/index.ts

Fixes: https://artsyproduct.atlassian.net/browse/PURCHASE-1020
Since we're trying to move to camelCase anyways, I took the opportunity to add `isBenefit` and deprecate `is_benefit`.
#skip_camel

Adds isBenefit and isGalleryAuction to sale schema

---

src/lib/stitching/vortex/__tests__/pricingContext.test.ts
src/lib/stitching/vortex/stitching.ts

Fixes: https://artsyproduct.atlassian.net/browse/PURCHASE-1010
Artworks with this category are too diverse to be grouped together.

If an artworks category is OTHER, dont show a histogram for that artwork

---

src/schema/__tests__/auction_results.test.js
src/schema/auction_result.ts

Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-954
A bunch of recent-ish data that was imported (and so is showing up near the front of 'Auction Result' tabs for a bunch of artists) are lacking images (rather than an empty array), so was crashing when requesting the data. This makes that code more defensive by simply allowing nulls, and the possible data-quality issue has been raised in #data-team.

@kierangillen => [AuctionResults] Be allowing of null images from Diffusion response

---

src/schema/SearchableItem/SearchItemRawResponse.ts
src/schema/SearchableItem/SearchableItemPresenter.ts
src/schema/SearchableItem/__tests__/SearchableItemPresenter.test.ts

There are 5 possible states a live sale could be in (live as in live auction integration):
1. Published on Artsy, open for registration, but not yet open for any kind of bidding
2. Open for registration & pre-bidding, but not yet open for live bidding
3. Registration closed, pre-bidding open to those who previously registered, but not yet open for live bidding
4. Open for live bidding
5. Closed
_Thanks to Melanie Borinstein for this context!_
For live auctions, we want to display the date an auction becomes available for live bidding (4), not when the auction enters any previous state (1-3). We currently display the date corresponding to state 2, when an auction is open for registration and pre-bidding.
Depends on https://github.com/artsy/gravity/pull/12316
ticket: …

Display when a sale is available for live bidding, when available

---

src/schema/artist/__tests__/carousel.test.js
src/schema/artist/carousel.ts

- Some artists ( e.g. https://www.artsy.net/artist/andy-warhol ) carousels do not display enough images which leads to a single image being cropped. This leads to strange UX when the carousel only advances 10-20 pixels.
- Increases artist carousel slides from 7 to 10

Increases artst carousel slides from 7 to 10

---

src/lib/sponsoredContent/data.json

https://artsyproduct.atlassian.net/browse/GROW-1224
This adds a sponsored content blurb (but no url) to Frieze New York 2019.
Trivial text update, no tests…

Update sponsored content text

---

src/schema/home/__tests__/home_page_artwork_module.test.js
src/schema/home/home_page_artwork_module.ts

I think this was broken from some past refactors :(
It looks like this param signifies 'this user has followed categories, so there should be a rail of those'.
The results for such a rail are fetched here: https://github.com/artsy/metaphysics/blob/065d05b7d206917efdcea24950ef21d955c31b64/src/schema/home/results.ts#L64-L69 , and it looks like Emission expects an `id` (a specific followed gene?) to be present.
Whereas Force won't, and so a 'featured gene' needs to be fetched from the user's follows.
I attempted to keep this backwards compatible for any clients/use-cases that are passing a valid id.

@joeyAghion => [BugFix] Fix followed gene rail

---

_schema.graphql
src/lib/__tests__/date.test.ts
src/lib/date.ts
src/schema/__tests__/fair.test.js
src/schema/artist/current.ts
src/schema/fair.ts
src/schema/partner_show.ts
src/schema/partner_show_event.ts
src/schema/show.ts

- Creates date formatting fields to match formatting documented here: https://www.notion.so/artsy/Formatting-Time-f6f4aaeeba414583a207013fec5a9794
- `Current.CurrentEvent`, `Show.exhibition_period`, `PartnerShowEvent.dateTimeRange`, `PartnerShowEvent.exhibitionPeriod`, `PartnerShow.exhibition_period`, `Fair.exhibition_period`, `Fair.formattedOpeningHours` now take a hardcoded `"UTC"` timezone which we can replace once corresponding inputs handle timezone entry.

Adds new formatted date fields

---

src/lib/__tests__/date.test.ts

- Updates date tests to be grammatically correct using `it` as first word

Updates date tests to be grammatically correct

---

src/schema/artwork/index.ts
src/schema/fields/__tests__/money.test.ts
src/schema/fields/money.ts

https://artsyproduct.atlassian.net/browse/PURCHASE-995
Need to check that we're not breaking usages of this before merging (I'm checking in reaction, emission, and volt):

'amount' helper should handle zero correctly [PURCHASE-995]

---

_schema.graphql
src/data/vortex.graphql

This PR brings MP up to date with current Vortex schema, which includes info on Pageviews that will be consumed by the Activity section of the new Partner Analytics dashboard ([spec](https://app.zeplin.io/project/5aabc6f28d835c7b2585fdf4/screen/5c9a75f087814d603e229d7a)).
Note that the change to `timeSeries` is theoretically breaking (but only for the cms.artsy.net/analytics route, which is only accessible to users with the CMS lab flag) - that said, as far as @ansor4 and I can tell it should already be breaking things and isn't. Might be because the format of the data hasn't changed at all, only the type expected.

update to use most recent version of vortex schema

---

_schema.graphql
src/data/vortex.graphql

https://artsyproduct.atlassian.net/browse/GALL-1671
- Update Vortex schema with the [sales stats change](https://github.com/artsy/vortex/pull/115) and [cumulative sales time series](https://github.com/artsy/vortex/pull/125).
- ~Stitch in formatted `total` fields for sales stats and time series.~ Decided to pull the stitching part out to a separate branch and unblock UI development.

Update Vortex schema with partner sales stats (GALL-1671)

---

_schema.graphql
src/data/vortex.graphql

This PR updates MP's copy of Vortex schema with a new field, `OrderResponseTime`. That field is implemented in [Vortex #134](https://github.com/artsy/vortex/pull/134).
Although this is a non-breaking change and is not currently being consumed by anything, I marked as `Do not merge` in case we decide to do something like change the field name. Once the associated Vortex PR is merged, I'll update the title and we can go for it.

GALL-1753: Add order response time to Vortex schema

---

_schema.graphql
src/schema/image/index.ts
src/schema/index_v2.ts

Sentry is reporting the following error:
```
Cannot return null for non-nullable field Image.__id.
__id
```
Previously, `__id` wasn't present on the `Image` and its `id` field is nullable. I'm restoring it back to the old nullable field and we can follow up later on how to resolve it. 
It _does_ seem like there are places in reaction that's actually querying `__id` on the image.

Make image id nullable again

---

_schema.graphql
src/lib/stitching/vortex/__mocks__/link.ts
src/lib/stitching/vortex/__tests__/partnerStatsSales.test.ts
src/lib/stitching/vortex/__tests__/topArtworks.test.ts
src/lib/stitching/vortex/stitching.ts

https://artsyproduct.atlassian.net/browse/GALL-1671
Following existing patterns, this exposes formatted string fields for `totalCents` on `AnalyticsPartnerSalesStats` and `AnalyticsPartnerSalesTimeSeriesStats`.

Expose formatted total fields for partner sales stats (GALL-1671)

---

_schema.graphql
src/schema/fair.ts
src/schema/index_v2.ts
src/schema/me/conversation/index.ts

Upon performing an audit of the `id` fields that have changed since #1678 these types had `id`s that went from nullable to non-nullable:
- BuyOrder
- Offer
- OfferOrder
- Order
- OrderFulfillment
- OrderLineItem
- Conversation
- FairExhibitor
According to @ashkan18 the order/offer types should add have ids present and the reason they were left nullable was a misunderstanding of the `ID` type. (It was assumed that a field typed as `ID` was always non-nullable). 
The last two on the list we're not confident about so I've reinstated their nullability just to be on the safe side. 
Getting this in before #1727.

Shore up nullable ids

---

_schema.graphql
_schemaV2.graphql
index.js
src/schema/index_v2.ts
src/schema/object_identification.ts

Noticed that `Conversation`, which comes from impulse, had a `gravityID` instead of `internalID`.

 [v2] Properly rename nullable id field on non-Gravity types

---

_schema.graphql
_schemaV2.graphql
src/schema/index_v2.ts
src/schema/me/consignments/submission.ts

`ConsignmentSubmission` has all the id fields right now, but no clients should be using anything other than `id` on v1, so I’m just going to remove the others as it keeps transforming slightly simpler.

 [ConsignmentSubmission] Remove ID fields other than DB ID

---

hokusai/test.yml
package.json

Metaphysics PR builds have been failing ever since we stopped sharing secrets with forked PRs.
I honestly don't know how critical some of [Danger's current checks](https://github.com/artsy/metaphysics/blob/master/dangerfile.ts) are to our workflow. If they are, seems like our best option is migrating them to something like Peril. I don't think we should tolerate build failures until then, so I suggest we exclude Danger for now.

Exclude danger for now

---

_schema.graphql
_schemaV2.graphql
src/data/vortex.graphql

This PR adds the `PartnerInquiryStats` type from the Vortex GraphQL schema into Metaphysics and exposes it as `AnalyticsPartnerInquiryStats`.
This change allows the CMS to display information about a partner's inquiries (specifically, how many they received and how soon they were able to respond to them in a given time period) to the Sales section of the analytics dashboard.

Update schema for inquiry stats from Vortex (GALL-1503)

---

src/lib/__tests__/date.test.ts
src/lib/date.ts

- The tests for `dateRange` used `moment()` without a timezone which were failing the tests when tested outside of EST.

Removes moment without TZ from date tests

---

_schema.graphql
src/data/kaws.graphql
src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap

This updates the kaws schema as part of [GROW-1284](https://artsyproduct.atlassian.net/browse/GROW-1284).

update kaws schema with relatedCollections field

---

_schema.graphql
_schemaV2.graphql
src/schema/__tests__/artworkAttributionClasses.test.ts
src/schema/artwork/attributionClass.ts
src/schema/artworkAttributionClasses.ts
src/schema/schema.ts

Subtask of https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=41&modal=detail&selectedIssue=PURCHASE-1105
__User Story__
As a user, I can tap on the attribution class below the tombstone to learn more. Tapping on the link will open a new page with all of Artsy’s classifications.
I can click the back button or “OK” to go back to the artwork page.
__Spec__
https://zpl.io/aX3O198

PURCHASE-1168: Serves the artwork attribution class descriptions from Metaphysics instead of storing them in-app

---

hokusai/production.yml
hokusai/staging.yml

Follow-up to https://github.com/artsy/metaphysics/pull/1764
Another gotcha!  `hokusai staging update --dry-run` succeeded but `hokusai staging update` failed with `"/Users/isacpetruzzi/Code/artsy/metaphysics/hokusai/staging.yml": Service "metaphysics-web" is invalid: [spec.ports[0].targetPort: Invalid value: "metaphysics-http": must be no more than 15 characters, spec.ports[1].targetPort: Invalid value: "metaphysics-http": must be no more than 15 characters]`

rename port metaphysics-http to mp-http to observe 15 character limit on port names

---

_schema.graphql
_schemaV2.graphql
src/data/vortex.graphql
src/lib/stitching/vortex/__mocks__/link.ts
src/lib/stitching/vortex/__tests__/rankedStats.test.ts
src/lib/stitching/vortex/stitching.ts

~depends on https://github.com/artsy/vortex/pull/149~ (deployed to production)
We tried two other approaches ([1](https://github.com/artsy/metaphysics/pull/1762) , [2](https://github.com/artsy/metaphysics/compare/master...sepans:ranked-stats-2?expand=1)) but with this one we got it right:
cc: @alloy 
query:
```graphql
query {
partner(id: "4d8b92c44eb68a1b2c0004cb") {
analytics {
topArtworks: rankedStats(first: 1, objectType: ARTWORK, period: ONE_YEAR) {
edges{
node{
entity {
... on Artwork{
title
artists {
name
}
}
... on PartnerShow{
name
}
}
}
}
}      
topShows: rankedStats(first: 1, objectType: SHOW, period: ONE_YEAR) {
edges{
node{
entity {
... on Artwork{
title
artists {
name
}
}
... on PartnerShow{
name
}
}
}
}
}
}
}
}
```
response:
```JSON
{
"data": {
"partner": {
"analytics": { …
```

Stitch AnalyticsRankedStats union

---

src/lib/__tests__/hasFieldSelection.test.ts
src/lib/hasFieldSelection.ts

Once we deployed #1761 , `/collect` page broke.
Thanks to @mzikherman we found the breaking query:
```graphql
query {
viewer {
...CollectApp_viewer_3XOIsA
}
}
fragment CollectApp_viewer_3XOIsA on Viewer {
filter_artworks(aggregations: [MEDIUM, TOTAL], size: 0) {
__id
}
...CollectFilterContainer_viewer_3XOIsA
}
fragment CollectFilterContainer_viewer_3XOIsA on Viewer {
filter_artworks(aggregations: [MEDIUM, TOTAL], size: 0) {
aggregations {
slice
counts {
name
id
__id
}
}
__id
}
}
```
Trying things locally, we found out that the fact that we limited visiting nodes only to  `fieldNodes[0]` in this specific query we were not traversing `CollectFilterContainer_viewer_3XOIsA`. 
The fix here was to traverse all `fieldNodes` instead of only the first one.
YES! i wrote a test for this but having …

Dynamic field fetch take ii

---

src/lib/__tests__/date.test.ts
src/lib/date.ts
src/schema/sale/index.ts

-  Adds `formattedStartDateTime` and `initials` to auctions for the `AuctionsEntityItem` (see image below)
- Removes unnecessary `formattedOpeningHoursDate` from dates.ts
- Creates `formattedStartDateTime`
- Removes hours displaying from `singleDate` and creates new field `singleDateTime` to show date with hours. `singleDate` isn't used yet, so this fix will have no breaking changes.

Adds new fields to Auction and creates new date fields

---

src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.ts

Previously, when framed and `certificate_of_authenticity` were `true` they resolved to an object with a label field with the value "Framed"/"Certificate of authenticity" and a details field that was `null`.
When they were `false` or `null` they resolved to `null`. 
Because of this we had no way to distinguish between a case where the partner checked the "no" box and a case where they left both boxes unchecked. We want a different behavior for these cases in emission, so this needed to change. 
When `true` it returns
```
{ label: "Framed", details: "Included" }
``` 
when `false` it returns 
```
{ label: "Framed", details: "Not included" }
```
and when `null` it returns `null`.
When `certificate_of_authenticity` is `true` it returns
```
{ label: "Certificate of authenticity", details: …
```

PURCHASE-1231: Update resolvers for framed and certificate_of_authenticity

---

_schema.graphql
_schemaV2.graphql
src/data/kaws.graphql
src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap

Copying over schema updates generated [here](https://github.com/artsy/kaws/pull/108). This satisfies [GROW-1337](https://artsyproduct.atlassian.net/browse/GROW-1337).

updated KAWS schema with new collection hub data

---

_schema.graphql
_schemaV2.graphql
src/schema/artwork/index.ts
src/schema/v2/RenameFields.ts
src/schema/v2/__tests__/v2.test.ts
src/schema/v2/index.ts

We did this by adding `v2Shows` to `Artwork` and then rename `shows` to `deprecatedShows` and then `v2Shows` to `shows` on V2 version of `Artwork`.
follow up on #1792

Add `shows` as `Show` in Artwork v2

---

_schema.graphql
_schemaV2.graphql
src/schema/artwork/__tests__/artwork.test.js
src/schema/artwork/index.ts

I updated the resolver for signatureInfo so that "Not signed" is added to its details. Previously, if "Not signed" was checked it but there was no data for other fields signatureInfo would resolve to null. I will also update Emission so that we show the details field of signatureInfo instead of just showing signature. If other fields are selected or filled out in addition to "not signed" (Such as "stamped by artist estate") the will be comma separated and will all be displayed.
I am not sure why the "commercialVisitors" schema changes are showing as part of my changes. I did not add them.

[PURCHASE-1268] If work is "Not Signed", we should show "Not signed" in Signature section under artwork details

---

hokusai/es5.yml

Set up an Canary app to point to gravity's es5 canary deployment `stagingaip-es5.artsy.net` managed by https://github.com/artsy/gravity/pull/12459
Re-tagged `staging` image to `es5` with:
```
hokusai registry pull --tag staging --local-tag es5
hokusai registry push --tag es5 --force --no-build --skip-latest
```
- Run `hokusai staging create --filename ./hokusai/es5.yml`
- Create an internal load balancer so set up a DNS record for it `metaphysics-es5.artsy.net`

#migration add es5 canary

---

.circleci/config.yml

Removes redundant push-production-image step from CI workflow. Related to https://artsyproduct.atlassian.net/browse/PLATFORM-1596

Remove redundant push-production-image step

---

src/config.ts

This is a weird one! Basically, when you triggered a hot-reload of schema files, eventually the `config` file would get reloaded (I think). And there...the `GRAVITY_XAPP_TOKEN` is set to `null`. All subsequent unauthenticated requests would then fail (after any 60 second long cached data expired). Making authenticated requests wouldn't result in an error as sending an access token is sufficient.
That's pretty annoying! (and sort of breaks the benefit of hot reloading completely).

@sweir27 => [XAPP] Change default setting of xapp token constant to better support reloading

---

_schema.graphql
_schemaV2.graphql
src/lib/stitching/exchange/__tests__/replaceComerceDateTime.test.ts
src/lib/stitching/exchange/schema.ts
src/lib/stitching/exchange/transformers/replaceCommerceDateTimeType.ts

Exchange date fields are exposed as `CommerceDateTime`, when switched to Exchange stitched version, this is different than our old merged version of MP's `dateField`. This makes our switch to stitched Exchange schema painful and almost not possible in a clean way.
Before stitchign, transform Exchange's schema by adding a new `Transformer` that replaces `CommerceDateTime` fields with MP's `dateField`.

Fix Exchange CommerceDateTime issue

---

src/data/vortex.graphql

Most important thing is order is `orderResponseTime` can be null

Update vortex schema

---

__mocks__/dd-trace.js
src/lib/cache.ts
src/lib/stats.js
src/lib/tracer.ts

The combination of dd-trace and (probably) statsd seems to be causing
this. I dug a bit into dd-trace upto TracerProxy, but still unsure where
the exact cycle is. For now, and also in general, not loading these
libraries at all during tests is a good enough solution.

[test] Fix leak that retains memory across tests.

---

_schemaV2.graphql
package.json
src/schema/v2/SearchableItem/index.ts
src/schema/v2/__tests__/filter_artworks.test.js
src/schema/v2/__tests__/object_identification.test.js
src/schema/v2/__tests__/users.test.js
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/artworkContextGrids/__tests__/fairContext.test.ts
src/schema/v2/collection.ts
src/schema/v2/featured_link.ts
src/schema/v2/filter_artworks.ts
src/schema/v2/home/home_page_artist_module.ts
src/schema/v2/home/home_page_artwork_module.ts
src/schema/v2/match/__tests__/gene.test.js
src/schema/v2/me/conversation/index.ts
src/schema/v2/me/conversation/message.ts
src/schema/v2/me/followed_artists_artworks_group.ts
src/schema/v2/me/notifications.ts
src/schema/v2/object_identification.ts
src/schema/v2/sale_artwork.ts
src/schema/v2/v2/__tests__/v2.test.ts
src/schema/v2/v2/index.ts

This addresses the ID fields for types defined in MP’s local schema, not yet for upstream services like Exchange–which we still transform and [will be addressed separately](https://artsyproduct.atlassian.net/browse/PLATFORM-1448).
(Note, for now we're not running v2 tests, we'll fix the test suite after we have everything up and running.)

[v2] drop IDs transform

---

_schemaV2.graphql
src/schema/v2/bidder.ts
src/schema/v2/credit_card.ts

Last week, we saw that auction registration wasn't working. We traced it down to an error returned from Metaphysics:
```
[ { message: 'Cannot return null for non-nullable field CreditCard.internalID.',
locations: [ { line: 9, column: 11 } ],
path: 
[ 'createCreditCard',
'creditCardOrError',
'creditCard',
'internalID' ] } ],
```
Looking into MP's v2 schema, we found that Bidders and CreditCards were expecting `_id` fields from Gravity, but were actually getting `id` fields.
Daniel and I _think_ this is the right change to make, but we have two questions:
- Is this the correct change? 
- How can we be rigorous about testing these kinds of mappings, from MP v2 and Gravity IDs? Specifically, how can we make sure there aren't more Gravity models that are breaking this expectation?
We saw that …

[AUCT-528] Fixes ID fields for CreditCards and Bidders (?)

---

src/schema/v1/fields/__tests__/money.test.ts
src/schema/v1/fields/money.ts
src/schema/v2/fields/__tests__/money.test.ts
src/schema/v2/fields/money.ts

We have an `amount` wrapper that we use to resolve money-related fields, such as those returned from Exchange.
To determine the relevant currency symbol, the helper uses either a `symbol` arg that's passed in, or the `symbol` on the parent object passed in.
This PR updates the helper to also use the parent object's `currencyCode` to determine which symbol to show.
This will allow us to return the correct amounts from metaphysics (via Exchange) when an order is in a currency other than USD.
Note that `currencyCode` is suggested naming [here](https://www.notion.so/artsy/Currency-Best-Practices-95081d370e664509928509e3dbd74c81), although metaphysics does not yet comply with the best practices set in that doc. That feels out of scope of this!

PURCHASE-1282: Use currencyCode to determine symbol in amount() helper, if it exists

---

_schemaV2.graphql
src/schema/v2/bidder.ts
src/schema/v2/credit_card.ts
src/schema/v2/object_identification.ts

@kierangillen reported an issue where a query for edition sets was failing. 
Here's a [minimal repro](https://metaphysics-staging.artsy.net/v2/?query=%7B%0A%20%20artwork(id%3A%20%22alex-dordoy-5th-genome-test-partner-test-2%22)%20%7B%0A%20%20%20%20edition_sets%20%7B%0A%20%20%20%20%20%20internalID%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A). Here's the error:
```
Cannot return null for non-nullable field EditionSet.internalID.
```
I checked the [edition set id definition](https://github.com/artsy/metaphysics/blob/3aebfd943cdb6d131e1dfa011e56910cde205eb8/src/schema/v2/edition_set.ts#L39) to see where the id was coming from. That pointed to the `object_identification` file's `internalIDFields` definition. 
https://github.com/artsy/metaphysics/blob/2b4328130668c226e76361723baeba1f6661e16f/src/sche …

Ensure InternalIDFields maps to id instead of _id

---

src/lib/hasFieldSelection.ts

This fixes the issue (I hadn't tested scrolling in Emission w/ the update).
This is more of a 'hot-fix', as the TODO item should be addressed. I think my understanding of fully parsing the AST for a query and traversing the various fragments isn't complete.

@zephraph => [FilterArtworks] Fix for Emission using count/cursor instead of first/after

---

dangerfile.ts

This is a follow-up to #1785 and Incident-46, where an accidental destructive edit to the query map led to a brief production outage. This should prevent that from happening again.

Adds Danger rule to prevent destructive query map edits.

---

_schema.graphql
src/schema/v1/artwork/index.ts
src/schema/v1/sellable.ts

The pass-through field `Artwork.price` is used in a few different ways in Reaction, from analytics to JSONLD, with the suggested field `sale_message` being different in form from the parseable `price`. Since `price` usage is being discouraged, this updates the deprecation pointer to suggest `listPrice`.

Update `Artwork.price` deprecation to point to `listPrice`

---

src/lib/hasFieldSelection.ts
src/schema/v1/__tests__/filter_artworks.test.js
src/schema/v2/__tests__/filter_artworks.test.js

Taking a closer look, and I think this makes more sense logically (and clears up `as any`, and would have avoided the Eigen issue).
It's more generic, so whether arguments are passed in-line, or as variables (and whatever the variable is called), it works!

@alloy => [Util] Improve argument parsing during query introspection for connection optimization

---

_schema.graphql
_schemaV2.graphql
src/lib/stitching/exchange/__tests__/stitching.test.ts
src/lib/stitching/exchange/stitching.ts

When we stitched Exchange schema we missed resolving `Order.creditCardId` and adding `Order.creditCard`.
Stitch `creditCard` using `Order.creditCardId` on both `buy` and `offer` orders.
When we try to `delegateToSchema` the `fieldName` on V1 is `credit_card` while this has change in V2 to `creditCard`. Current stitched code is shared between V1 and V2 and current code would only work for V1.
Knowing this is only used by Reaction (`V1`) at the moment, this may be fine for now but we may want to duplicate exchange stitching to get `V2` version actually working.

Stitch creditCard on Exchange Order

---

_schemaV2.graphql

This just removes the `__allowedLegacyNames` entry with `__id` in it. 
@alloy the `_schemaV2.graphql` updates might be from it not properly being updated in #1874?
I can revert that part if needed.

Commit generated changes from v2 schema

---

_schema.graphql
_schemaV2.graphql
src/lib/stitching/exchange/transformers/replaceCommerceDateTimeType.ts

As part of #1803 , we replaced all `CommerceDateTime` fields with MP's `dateTime`. But `createdAt` field under `Order` is still coming as `CommerceDateTime`.
When we did replacement, the transformer replaces the field resolver based on `type.name` of the field, but when a field is not nullable, the type is `GraphQLNotNull` and `type.ofType.name` for that field would be `CommerceDateTime`.
Check for `type.ofType` when there is available also.

Fix skipping not null CommerceDateTime in stitching replacement

---

src/lib/stitching/exchange/__tests__/stitching.test.ts
src/lib/stitching/exchange/stitching.ts

creditCardResolver should return null if the id is null rather than trying to delegate the request to gravity
See discussion here: 
https://artsy.slack.com/archives/C9YNS4X32/p1564760261125200

creditCardResolver returns null if the id is null

---

src/lib/stitching/exchange/__tests__/stitching.test.ts
src/lib/stitching/exchange/stitching.ts

@mdole noticed that our resolvers for `CommerceOrder` weren't working-- in particular, the fields under `CommerOrder` wrapped in the `amount` helper weren't resolving correctly.
It appears this issue is due to the fact that we weren't actually including the `CommerceOrder` in our resolvers for the stitched version of the schema.
This should fix!

Fix CommerceOrder stitching

---

src/schema/v2/fields/date.ts

finishes https://artsyproduct.atlassian.net/browse/AUCT-539
GIven the query:
```graphql
{
sale(id: "yuki-contemporary-art-august-5th") {
endAt
liveStartAt
startAt
}
}
```
or for v1:
```graphql
{
sale(id: "yuki-contemporary-art-august-5th") {
end_at
live_start_at
start_at
}
}
```
They should return the same data except the keys are cameCase in v2. However, in v2, camelCase keys are not properly snake_cased on resolving. As a result, these date field always end up being `null`.
In the `date` resolver, look up the date value with a snake cased key when the value corresponding to the original field name is not present in the object:
This would probably affect any other date fields so I wanted to make sure this is a safe change. Also, I wonder if there is other place that requires a case …

Fixes an issue where snake case date fields are present

---

src/schema/v2/__tests__/filterArtworksConnection.test.js
src/schema/v2/filterArtworksConnection.ts
src/schema/v2/object_identification.ts

Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=64&projectKey=PLATFORM&modal=detail&selectedIssue=PLATFORM-1685
Goofed and passed the wrong set of params to the connection helper. The Relay connection args are expected, but was passing the underlying API options instead. Added a spec that passes locally.

@zephraph => [filterArtworksConnection] Pass proper params to connection helper

---

src/lib/__tests__/hasFieldSelection.test.ts
src/lib/hasFieldSelection.ts
src/lib/helpers.ts
src/schema/v1/filter_artworks.ts
src/schema/v2/__tests__/filterArtworksConnection.test.js
src/schema/v2/filterArtworksConnection.ts

Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=64&projectKey=PLATFORM&modal=detail&selectedIssue=PLATFORM-1675
Since we were introspecting to grab connection parameters (in order to consolidate multiple backend fetches), this led to us not respecting if said connection was skipped via the GraphQL directive. As in, the optimization didn't take this into account, and still fetched all the artworks. It did the 'optimum' combined one call, but the whole fetching of the artworks in the first place was unneeded due to the skip.
So, this PR takes that into account and no longer parses those connection parameters (if the entire connection is skipped). Additionally, we set a size of 0 explicitly on any calls where there was no unskipped artwork connection requested. …

@zephraph => Filter optimization; don't request (and set size=0 explicitly), when connection is skipped

---

src/schema/v2/home/__tests__/home_page_fairs_module.test.js

This particular test seems to have a field that flip flops based on whether jest cache is available or not. I'm just gonna disable it for now until we can dig into it further.

Disable failing snapshot test

---

src/lib/__tests__/graphqlErrorHandler.test.ts
src/lib/graphqlErrorHandler.ts

So far, I'm able to generate 401/404 and 500s downstream, and verify that the correct `httpStatusCheck` comes back.
For instance, `/orders/234234` (if you're not authorized to view that order, or it doesn't exist), now  correctly returns a 404, without this [custom logic](https://github.com/artsy/force/blob/3f46e35ecda1d0b92615eb70a89584709f780043/src/desktop/apps/order/routes.tsx#L60-L66). Reaction will correctly serve and render the relevant error page.

@alloy => [Error Handling] Expose status code for errors occurring during stitching

---

_schema.graphql
src/schema/v1/me/__tests__/consignments/__snapshots__/submissions.test.js.snap
src/schema/v1/me/__tests__/consignments/create_submission_mutation.test.js
src/schema/v1/me/__tests__/consignments/submissions.test.js
src/schema/v1/me/__tests__/consignments/update_submission_mutation.test.js
src/schema/v1/me/consignments/create_submission_mutation.ts
src/schema/v1/me/consignments/submission.ts
src/schema/v1/me/consignments/update_submission_mutation.ts

fixes [slack #incident-55](https://artsy.slack.com/archives/CMLQ0288K/p1567453723004300).
Apparently [the type of `edition_size` has been set to `String` in Emission](https://github.com/artsy/emission/blob/07d6b28ca5903e821faeed41a119d1aa849dca9d/src/lib/Components/Consignments/index.tsx#L43) since the beginning but the actual type of it is `Int`, so Metaphysics has been rejecting any submission mutation with a `edition_size` from the iOS app. This PR updates the type to `String` to make it consistent with Emission so we can fix it without cutting a new Eigen release. 
I believe this started being reported to Sentry since we deployed #1910. This deploy had this line: https://github.com/artsy/metaphysics/pull/1910/files#diff-f41e9d04a45c83f3b6f6e630f10117feR202
```
formatError: …
```

Fixes an issue where an incorrect use of edition size type prevents users from submitting consignments

---

src/lib/helpers.ts
src/lib/stitching/vortex/__tests__/rankedStats.test.ts
src/schema/v1/collection.ts
src/schema/v1/gene.ts
src/schema/v1/me/index.ts
src/schema/v1/partner.ts
src/schema/v1/tag.ts
src/schema/v2/collection.ts
src/schema/v2/gene.ts
src/schema/v2/me/index.ts
src/schema/v2/partner.ts
src/schema/v2/tag.ts
src/test/utils.ts

Fixes [GALL-1627](https://artsyproduct.atlassian.net/browse/GALL-1627)
`parseFieldASTsIntoArray` function assumes the top level `fieldASTs`s are of type `Field` so with `map(flatMap(fieldASTs, "selectionSet.selections"), "name.value")` it gets the name of all of them, but when that assumption is not true (e.g. top level `fieldAST` is an inline fragment) it doesn't go deeper into the tree.
This hasn't been previously a problem but when we stitched `analytics` under `partner` the top level AST is [this](https://github.com/artsy/metaphysics/blob/master/src/lib/stitching/vortex/stitching.ts#L239-L241) inline fragment and `parseFieldASTsIntoArray` returns `[undefined]` and the `queriedForFieldsOtherThanBlacklisted` function fails to recognize that there are no other fields in the query and …

[GALL-1627] Partner loader query fix for partner analytics

---

src/schema/v1/filter_artworks.ts

Related to https://github.com/artsy/metaphysics/pull/1905. We were attempting to fix the size property which was getting overwritten to zero. We checked for `relayOptions.size` when it should be `gravityOptions.size`.
For more context, the query below returns zero artwork hits because the gravityOptions contains the size param and not relayOptions.
```graphql
{
marketingCollection(slug: "street-art-now") {
title
id   
linkedCollections {
name
groupType
members {
slug
headerImage
thumbnail
title
price_guidance
artworks(size: 3) {
hits {
artist {
name
}
title
image {
url(version: "small")
}
}
}
}
}
}
}
```

use the correct size property

---

src/schema/v1/schema.ts
src/schema/v2/schema.ts

Turns out if you pass in an array, you overwrite the built-in directives!
https://github.com/graphql/graphql-js/blob/e67f2e5515739295bad006ecde0e6ce5db0dc83d/src/type/schema.js#L107-L115

@alloy => [Directive] Dont overwrite specified directives

---

src/index.ts

Pairing with @ds300  on the graphql issue we're seeing now in Emission -- Looks like `requestLoggerExtensions` needs to be spread as `res.json.extensions` is missing the `requests` object.

Fixes extensions object

---

_schema.graphql
_schemaV2.graphql
src/schema/v1/artwork/__tests__/artwork.test.js
src/schema/v1/artwork/index.ts
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/artwork/index.ts

Putting this field here means we'll be able to remove this logic from Emission/Reaction (and it should be easier to iterate on).

PURCHASE-1475: Adds priceIncludesTaxDisplay field to artwork schema

---

patches/express-graphql+0.9.0.patch

I forgot to hit 'Save' when I added this check and ran `patch-package`. This was failing on staging for non-string params, (but working locally, where I modified the `node_modules/` file directly), before I realized 😓 
#mergeongreen

@mzikherman => [Patch] Only attempt variable coercion on string fields

---

patches/express-graphql+0.9.0.patch

Our patch was breaking when there were no variables (`undefined`), which is what you'd get when hitting GraphiQL directly.
Side note- as this sits on staging for a bit I will add some specs for the patch. I added that in https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=64&projectKey=PLATFORM&modal=detail&selectedIssue=PLATFORM-1766

@anandaroop => [Patch] Dont coerce variables when there are none

---

src/integration/__tests__/integration.test.ts

Trying to write a spec for recent patches, and noticed we have this handy integration spec.
However, it is guarded to  _only_ run on CI, and I can't get it work locally.
I'm pretty skeptical this is being run on CI...

@joeyAghion => [Patch] Add specs around variable coercion patch

---

_schema.graphql
_schemaV2.graphql
src/schema/v1/__tests__/user.test.js
src/schema/v1/sale/__tests__/index.test.js
src/schema/v1/sale/index.ts
src/schema/v1/user.ts
src/schema/v2/__tests__/user.test.js
src/schema/v2/sale/__tests__/index.test.js
src/schema/v2/sale/index.ts
src/schema/v2/user.ts

We need these additional fields in the new auctions emails: https://zpl.io/25GYlzo

Add more auction-related fields to User and Sale

---

src/schema/v2/artwork/index.ts

[PURCHASE-1497]
I noticed that the additionalInformation field was coming up as null. It appears that someone accidentally forgot to pass something to `markdown()` in v2, so the field was always null and nothing was being displayed in emission. I fixed this and now the field returns the proper content.
__Before:__
__After:__
[PURCHASE-1497]: https://artsyproduct.atlassian.net/browse/PURCHASE-1497

PURCHASE-1497:  additionalInformation is null

---

src/schema/v2/artwork/index.ts

#minor 
I scanned through the rest of the codebase and I _think_ this is the last instance of this, but it's possible there are still more places where we're assuming the shape of the data is the same as the shape of the field we're returning.

Pass through gravity field for exhibitionHistory

---

src/extensions/principalFieldDirectiveExtension.ts
src/schema/v1/__tests__/principalFieldDirective.test.ts

Noticed this when testing out https://github.com/artsy/reaction/pull/2836 and I've seen it in Sentry as well. Just need to be defensive here.

@eessex => [principalDirective] Don't error when a non-principal error occurs

---

_schema.graphql
_schemaV2.graphql
src/schema/v1/sale/__tests__/index.test.js
src/schema/v1/sale/index.ts
src/schema/v2/sale/__tests__/index.test.js
src/schema/v2/sale/index.ts

https://artsyproduct.atlassian.net/browse/AUCT-626
We are only adding time zone, with the expectation that clients will manage formatting to local time zones for now. Times are still stored in UTC.
I had one question: Is it expected that adding time zone to Sale would cause it to appear in multiple places in the generated V1 schema file?

Add time_zone/timeZone to Sale

---

_schemaV2.graphql
src/schema/v2/schema.ts

Related: https://github.com/artsy/metaphysics/pull/1906
Re-adding `Viewer` type during our MPv2 migration in Reaction. We can revisit once the migration is complete.

[V2] Readd Viewer type

---

_schema.graphql
_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v1/schema.ts
src/schema/v1/static_content.ts
src/schema/v2/schema.ts
src/schema/v2/static_content.ts

- Adds `staticContent` to resolve page content from Gravity's `Page` model
Example:
```
{
staticContent(id: "how-auctions-work-bidding") {
content
name
}
}
```

Adds StaticContent

---

src/lib/sponsoredContent/data.json

https://artsyproduct.atlassian.net/browse/GROW-1550
This fulfills a time-sensitive content sponsor request: https://artsy.slack.com/archives/C9SATFLUU/p1569513951321800
In lieu of having final copy, not that I pulled the first ¶ from the provided [press release](https://www.press.bmwgroup.com/global/article/detail/T0299793EN/camille-blatrix-to-explore-concept-of-desire-for-bmw-open-work-2019-artwork-inspired-by-bmw-technology-to-premiere-at-frieze-london-in-october-2019) body to use as the "activation text."
This is similar but not _identical_ to how the copy for previous fairs was handled — **please confirm that this text is okay (or update this PR as necessary) before merging**.

[City Guide] Add sponsored content for Frieze London 2019

---

src/index.ts

Looks like:
```
formatError` is deprecated and replaced by `customFormatErrorFn`. It will be removed in version 1.0.0.
```

Avoid deprecation warning on every request

---

_schemaV2.graphql
src/schema/v2/sale/__tests__/__snapshots__/index.test.js.snap
src/schema/v2/sale/__tests__/index.test.js
src/schema/v2/sale/index.ts

depends on https://github.com/artsy/gravity/pull/12610
In a Zeplin mockup like https://zpl.io/brLyq53, we would like to fetch a subset of sale artworks in a sale rather than loading every one of them or fetching each one-by-one. Right now we do this in an iteration which isn't efficient.
This PR adds a new `internalIDs` argument so the client can only get relevant data. It may not be the best name as it could be confusing when there are `id` and `internalID`, but I would like feedback on this as well.

Update SaleArtworksConnection to accept the internalIDs argument

---

src/schema/v2/sale/__tests__/index.test.js
src/schema/v2/sale/index.ts

Paired with @yuki24 on this. When passing an empty array to metaphysics, it removes the empty array rather than passing `ids: []` to gravity as expected.

return empty array for sale artworks when internalIDs == empty array

---

src/lib/__tests__/date.test.ts
src/lib/date.ts
src/schema/v1/sale/index.ts
src/schema/v2/sale/index.ts

Semi-related to [PURCHASE-1584] and [PURCHASE-1539]
This will allow the context card to show messaging about auction start/end times that will be consistent with the auction timer (I have another PR in emission to update that). I also fixed a bug where the string was coming back with "Invalid date" in some cases. I also made the dateTimes timezone specific but defaulting to UTC, whereas before they were always in UTC. 
__Before:__
__After:__
__After (when it gets timezone from the client):__
[PURCHASE-1584]: https://artsyproduct.atlassian.net/browse/PURCHASE-1584
[PURCHASE-1539]: https://artsyproduct.atlassian.net/browse/PURCHASE-1539

Update formattedStartDateTime to account for live sales and fix bugs

---

src/lib/date.ts
src/schema/v1/sale/index.ts
src/schema/v2/sale/__tests__/index.test.js
src/schema/v2/sale/index.ts

https://artsyproduct.atlassian.net/browse/PURCHASE-1598
We were not honoring `ended_at` field of the auction and we were only using `end_at`.
`end_at` can be `null` and `ended_at` is for live auctions where we store the actual time the auction ended.
When calling `formattedStartDateTime` use `ended_at` and if it's null, use `end_at`.

Fix not honoring ended_at for live auctions

---

_schema.graphql
_schemaV2.graphql
src/schema/v1/__tests__/sale_artwork.test.js
src/schema/v1/sale_artwork.ts
src/schema/v1/types/calculated_cost.ts
src/schema/v2/__tests__/sale_artwork.test.js
src/schema/v2/sale_artwork.ts
src/schema/v2/types/calculated_cost.ts

finishes https://artsyproduct.atlassian.net/browse/AUCT-671
This PR adds a new `calculatedCost` field to the `SaleArtwork` type. The actual logic that does the math isn't implemented yet, but this should allow us to work on GraphQL clients since they need the schema to be updated.

Add CalculatedCost type to SaleArtwork

---

_schema.graphql
_schemaV2.graphql
src/lib/stitching/vortex/stitching.ts
src/schema/v1/artwork/__tests__/artwork.test.js
src/schema/v1/fields/listPrice.ts
src/schema/v1/fields/money.ts
src/schema/v2/artwork/__tests__/artwork.test.js
src/schema/v2/fields/listPrice.ts
src/schema/v2/fields/money.ts

This work was spawned from https://github.com/artsy/reaction/pull/2939. 
For structured data google needs the currency amounts of work in unformatted fields. @mzikherman and I paired on adding this field to `ListPrice` on the artwork type. The `ListPrice` only provided cents which isn't directly useful from a display perspective. We added an enhanced `Price` type.
In doing so we noticed that there were a lot of [duplicated types](https://artsy.slack.com/archives/C1HH3KNJG/p1571769864042100) because they used the [money](https://github.com/artsy/metaphysics/blob/ca2f97377170399ff86d3a91c00c284733c66979/src/schema/v1/fields/money.ts#L80) factory. Generally this is an anti-pattern because it creates duplicate types throughout the schema. We've depreciated this factory pattern in favor of …

Updated list price to use new Price type

---

_schemaV2.graphql
src/schema/v2/partner.ts

- We need to surface Current & Upcoming, and Closed shows for the Partner page.
- This borrows from the City model's `showConnection`'s `dayThreshold` and `status` fields

Adds dayThreshold and status to Partner shows

---

_schemaV2.graphql
src/schema/v2/artist/__tests__/index.test.js
src/schema/v2/artist/index.ts

Works locally, and I confirmed these are the same artworks as displayed on staging:
I'm open to feedback on the tests – I tried to test the integration with the existing `filterArtworksConnection` rather than test the `filterArtworksConnection` itself. An inline snapshot works for me, but again, open to feedback 👍 
This is related to work on [ME-65](https://artsyproduct.atlassian.net/browse/ME-65).

Adds filteredArtworksConnection to Artist type

---

src/lib/stitching/kaws/stitching.ts

Definitely not sure what's going on here, but this seems to fix the failing query (and all tests pass, although there are no true integration tests exercising KAWS stitching and running a real query, unlike some of the other stitched apps/environments). I will try to add some tests here.
The docs seem to be pretty clear that you _do_ want to pass in the transforms used on the remote schema, here:  https://www.apollographql.com/docs/graphql-tools/schema-delegation/#transforms-arraytransform
But, I think there's some bug there, and if this seems to work, maybe it's fine? The specifically extended schema here, adding filtered artworks under a marketing collection, wouldn't really need to know any of the transforms used for KAWS, would it? I'm sure there is a circumstance where it would (such …

@zephraph => [KAWS] Fix stitching transform issue causing price fields to be renamed

---

hokusai/production.yml
hokusai/staging.yml

…in Kubernetes specs in accordance with memory limits
Following up on the success of https://github.com/artsy/force/pull/4759 why not do the same in Metaphysics?
Also setting this flag via `NODE_OPTIONS` means we can keep it in Kubernetes spec files so we remember to update it when we update container mem limits.

set --max_old_space_size via NODE_OPTIONS 

---

_schema.graphql
_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v1/__tests__/sale_artwork.test.js
src/schema/v1/sale_artwork.ts
src/schema/v1/types/calculated_cost.ts
src/schema/v2/__tests__/sale_artwork.test.js
src/schema/v2/sale_artwork.ts
src/schema/v2/types/calculated_cost.ts

Update the `calculatedCost` field on sale artworks to pull calculation
results from the Gravity API.
The following subfields are exposed:
- `bidAmount`: Echos the input provided by the client along with formatted
results
- `buyersPremium`: The calculated buyer's premium for the bid amount
provided
- `subtotal`: The combination of the supplied bid amount and the
calculated buyer's premium
_Note: This does break the API contract defined along with the mock data. I think it's worth making this change now and early to align with defined naming preferences._
**Request**
```graphql
{
sale(id: "finarte-photographs-4") {
saleArtwork(id: "franco-fontana-paesaggio-baia-delle-zagare") {
calculatedCost(bidAmountCents: 100000) {
bidAmount {
display
minor
currencyCode
major
}
buyersPremium {
display …
```

Update SaleArtwork#calculatedCost to run calculation via Gravity

---

_schemaV2.graphql
src/schema/v2/__tests__/search.test.ts
src/schema/v2/gene.ts
src/schema/v2/search/SearchResolver.ts

```graphql
{
searchConnection(query: "minim", first: 10, entities: [GENE], mode: AUTOSUGGEST) {
edges {
node {
... on Gene {
name
}
}
}
}
}
```
```json
{
"data": {
"searchConnection": {
"edges": [
{
"node": {
"name": "Minimalism"
}
},
{
"node": {
"name": "Minimalism and Contemporary Minimalist"
}
},
{
"node": {
"name": "Contemporary Minimalist"
}
},
{
"node": {
"name": "Political Minimalism"
}
},
{
"node": {
"name": "Postminimalism"
}
}
]
}
}
}
```

[v2] Make Gene Searchable

---

_schema.graphql
_schemaV2.graphql
src/lib/helpers.ts
src/lib/stitching/kaws/stitching.ts
src/lib/stitching/mergeSchemas.ts
src/test/utils.ts

Alright, got KAWS stitching in V2 and use the filter artworks connection instead. I also automated the schema extension so that it’s always up-to-date with the filter args defined in MP.

[v2] Add KAWS stitching of filterArtworksConnection

---

src/lib/helpers.ts

Perhaps allowing the `size` argument rather than always using `first` has made this more complex than necessary, but that ship has sailed 🤷‍♂

[v2] Don't override pagination size when it is specified.

---

src/lib/sponsoredContent/data.json

This PR adds the press release information to Paris Photo 2019 fair.
[Links to GROW-1650](https://artsyproduct.atlassian.net/browse/GROW-1650)

Adds press release info for Paris Photo 2019

---

_schemaV2.graphql
src/lib/stitching/exchange/__tests__/testingUtils.ts
src/lib/stitching/exchange/stitching.ts
src/lib/stitching/mergeSchemas.ts
src/schema/v2/schema.ts

Exchange's stitching relied on the `Query#credit_card` field in v1, on it so I added it back in v2 with camelCase.

Add creditCard field to v2

---

src/lib/stitching/mergeSchemas.ts
src/lib/stitching/vortex/__tests__/partnerStatsSalesv1.test.ts
src/lib/stitching/vortex/__tests__/pricingContextv1.test.ts
src/lib/stitching/vortex/__tests__/rankedStatsv1.test.ts
src/lib/stitching/vortex/stitchingv1.ts

This PR allows us to use vortex stitching with metaphysics v2.
I opted for the "quick and dirty" approach here (duplicating our stitching manifest vs. adding special logic to allow the same stitching manifest to work for both).
Once reaction and volt are migrated (I imagine the latter is probably not _too_ involved), it will be really easy to rip out the `v1` code.
The tests are exact copies of the v1 ones, except they reference `runQuery` from the `v2` folder.

Make sure vortex stitching works with v2

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/fair.ts
src/schema/v2/location.ts
src/schema/v2/partner.ts
src/schema/v2/show.ts

- Adds `Partner.locationsConnection`, `Partner.locations` is now removed and had not been used prior to the future `6.0` release.
- Adds `Partner.cities`, in cases we were using the original `Partner.locations` it was just cases where we need a list of the `cities`, this new resolver provides a unique array of the Partners' cities.

Partner.locationsConnection & Partner.cities

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/fair.ts
src/schema/v2/location.ts
src/schema/v2/partner.ts
src/schema/v2/show.ts

Reverts artsy/metaphysics#2049
`Partner.locations` is still being used-- this reverts that change to fix an incident.

Revert "Partner.locationsConnection & Partner.cities"

---

_schema.graphql
_schemaV2.graphql
src/data/kaws.graphql
src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap

Related to https://github.com/artsy/kaws/pull/172 this removes the unused `Image` type from the KAWS schema.

Remove unused Image type from kaws schema

---

_schemaV2.graphql
src/lib/loaders/loaders_without_authentication/gravity.ts
src/schema/v2/fair.ts
src/schema/v2/location.ts
src/schema/v2/partner.ts
src/schema/v2/show.ts

- Reapplies this revert: https://github.com/artsy/metaphysics/pull/2051 while fixing the initial issue. Initially `Partner.locations` was removed, this PR leaves `Partner.locations` while adding `Partner.locationsConnection` as a separate field.

[V2] - Adds Partner.locationsConnection & Partner.cities while leaving Partner.locations

---

src/schema/v2/gene.ts

Genes weren't paginating because we weren't actually passing pagination options into `getPagingingParameters` which means we always got 0 results.

Fix gene pagination

---

src/schema/v2/partner.ts

- Adds `total_count` to `Cities` to ensure `body` is returned

Add `total_count` arg to Gravity request for partner locations

---

_schemaV2.graphql
src/schema/v2/__tests__/object_identification.test.js
src/schema/v2/fair.ts
src/schema/v2/object_identification.ts

This should allow `node(id: ...)` to resolve a fair. This might help address issues noticed in the inf. scroll grid of a fair view (which is shared among other types and thus uses the `Node` interface to fetch).

@kierangillen => [v2] Allow a fair to be retrieved as a node
